### PR TITLE
refactor: directly create snapshot stores

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Instead of taking a detour through a factory that lazily constructs snapshot stores when accessed for the first time, we now create a snapshot store during partitions startup and give both Zeebe and Raft partitions access to it.

Relates to #14085

### CODE REVIEW

**Comment by npepinpe** [comment]
getting closer to the plan :rocket:

**Review by deepthidevaki — APPROVED** [review]
:heart_eyes:

**Comment by oleschoenburg** [comment]
bors merge

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
