### PR TITLE
feat(engine) Error codes in incident error message

### LINKED ISSUE #7566: Include the errorCode when raising incidents due to UnhandledErrorEvent
**Is your feature request related to a problem? Please describe.**

When an incident is raised due to Unhandled error event, the incident message does not show the errorCode that is missing. It is difficult to debug.

To reproduce: https://github.com/camunda-cloud/game-day-cookbook/tree/main/mains/uncaught-error

In the above reproducer, the mismatch is due to a trailing white space which is not easy to identify by viewing the model via the modeller.  The error message shown by Operate only contains `Email service unavailable`. 

**Describe the solution you'd like**

When an incident is raised due to Unhandled error event, the error message should contain the errorCode that is thrown. In addition, it would be also good to add available error events in the message. Something similar to the following:
`An error was thrown with the code 'transmission-failed' with message 'Email service unavailable',  but not caught. Available error events are ['transmission-failed ' ]`

**Describe alternatives you've considered**
None

**Additional context**
The error message will be shown in operate. Thus it will be easier for a user to identify the problem.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Added the used error code and the available error codes to incident error messages.

## Related issues

closes #7566

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by saig0 — CHANGES_REQUESTED** [review]
@remcowesterhoud thank you for improving the error message :tada: 

The changes look good in general :+1:  Please have a look at my comments and suggestions. 
I'm open to questions or comments (here on Github or Zoom).  

If you add new changes then please do them as separate commits. It makes it easier to check the updates. 
Request the review again when you're done. 

---

Note that we're using an emoji code for code reviews (currently, in an evaluation phase). Read more about it [here](https://devblogs.microsoft.com/appcenter/how-the-visual-studio-mobile-center-team-does-code-review/#introducing-the-emoji-code).

**Review by saig0 — CHANGES_REQUESTED** [review]
@remcowesterhoud thank you for applying the hints :cookie: And the manual testing :rocket: 

Please have a look at my remaining comments.

**Review by saig0 — APPROVED** [review]
Looks good :+1:

**Comment by remcowesterhoud** [comment]
bors retry

**Pull request merged**
