### PR TITLE
Use protobuf when persisting ClusterTopology locally

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Replace json serialization with protobuf. Protobuf is used for gossiping. We reuse the same messages for writing to local file.

## Related issues

related #13765 #13801

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
:tada:

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
Go client test failed.

bors retry

**Pull request merged**
