### PR TITLE
fix(clients/java): omit polling exception if closing

### LINKED ISSUE #3318: False warning/exceptions due to race condition when closing JobWorker
**Describe the bug**

When closing a job worker, and immediately after the client, the job poller may throw an exception about the channel being closed. This is expected for us, but from a user point of view, this is unnecessary and more alarming than anything. 

My guess is this happens because if we close the worker (which cancels the next poll) while we were already going to poll (so we passed into the critical section), and then we close the client, the `activateJobs` call will fail. Again no big deal if you know about, but we shouldn't throw exceptions to user if we can avoid it.

**To Reproduce**

You can reproduce it fairly consistently using the Java getting started guide, i.e.:

<p><details><summary>Application.java</summary>

```java
package io.zeebe;

import io.zeebe.client.ZeebeClient;
import io.zeebe.client.api.response.DeploymentEvent;
import io.zeebe.client.api.response.WorkflowInstanceEvent;
import io.zeebe.client.api.worker.JobWorker;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class Application {

  public static void main(String[] args) {
    final String contactPoint = args.length >= 1 ? args[0] : "127.0.0.1:26500";

    System.out.println("Connecting to broker: " + contactPoint);

    final ZeebeClient client =
        ZeebeClient.newClientBuilder().brokerContactPoint(contactPoint).usePlaintext().build();

    System.out.println("Connected to broker: " + contactPoint);

    final DeploymentEvent deployment =
        client.newDeployCommand().addResourceFromClasspath("order-process.bpmn").send().join();

    final int version = deployment.getWorkflows().get(0).getVersion();
    System.out.println("Workflow deployed. Version: " + version);

    final Map<String, Object> data = new HashMap<>();
    data.put("orderId", 31243);
    data.put("orderItems", Arrays.asList(435, 182, 376));

    final WorkflowInstanceEvent wfInstance =
        client
            .newCreateInstanceCommand()
            .bpmnProcessId("order-process")
            .latestVersion()
            .variables(data)
            .send()
            .join();

    final long workflowInstanceKey = wfInstance.getWorkflowInstanceKey();

    System.out.println("Workflow instance created. Key: " + workflowInstanceKey);

    final JobWorker jobWorker =
        client
            .newWorker()
            .jobType("payment-service")
            .handler(
                (jobClient, job) -> {
                  final Map<String, Object> variables = job.getVariablesAsMap();

                  System.out.println("Process order: " + variables.get("orderId"));
                  System.out.println("Collect money");

                  // ...

                  final Map<String, Object> result = new HashMap<>();
                  result.put("totalPrice", 46.50);

                  jobClient.newCompleteCommand(job.getKey()).variables(result).send().join();
                })
            .fetchVariables("orderId")
            .open();

    waitUntilClose();

    jobWorker.close();

    client.close();
    System.out.println("Closed.");
  }

  private static void waitUntilClose() {
    try (Scanner scanner = new Scanner(System.in)) {
      while (scanner.hasNextLine()) {
        final String nextLine = scanner.nextLine();
        if (nextLine.contains("close")) {
          return;
        }
      }
    }
  }
}
```

</p></details>

**Expected behavior**

**Log/Stacktrace**
If possible add the full stacktrace or Zeebe log which contains the issue. 

<details><summary>Full Stacktrace</summary>
 <p>

```
worker_1  | Connecting to broker: zeebe-broker:26500
worker_1  | Connected to broker: zeebe-broker:26500
worker_1  | Workflow deployed. Version: 1
worker_1  | Workflow instance created. Key: 2251799813685261
worker_1  | Closed.
worker_1  | 15:25:06.057 [grpc-default-executor-0] WARN  io.zeebe.client.job.poller - Failed to activated jobs for worker default and job type payment-service
worker_1  | io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked
worker_1  | 	at io.grpc.Status.asRuntimeException(Status.java:533) ~[zeebe-worker.jar:?]
worker_1  | 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [zeebe-worker.jar:?]
worker_1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [zeebe-worker.jar:?]
worker_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
worker_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
worker_1  | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.22.0-alpha1

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Checks if the job worker is closing before logging an exception to prevent misleading the user by showing an expected failure.

## Related issues

closes #3318 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by MiguelPires** [comment]
bors retry

**Comment by npepinpe** [comment]
bors retry

**Comment by MiguelPires** [comment]
Bors r+

**Pull request merged**
