### PR TITLE
refactor(gateway): remove responsiveness indicator

### LINKED ISSUE #11799: Investigate usage of client in gateway
**Description**

It looks like we using the Zeebe client in the gateway, which is somehow weird. It add an unnecessary dependency to the client, and makes unnecessary requests. 

This was recently discovered here https://github.com/camunda/zeebe/pull/11599#discussion_r1109846523 

Furthermore, the impact was discovered also in one of the chaos days https://zeebe-io.github.io/zeebe-chaos/2023/02/23/Recursive-call-activity/

general

> One interesting fact is that the topology request rate is also up to 0.400 per second, so potentially every 2.5 seconds we send a topology request to the gateway. But there is no application deployed that does this. [I have recently found out again](https://github.com/camunda/zeebe/pull/11599#discussion_r1109846523), that we have the Zeebe client usage in the gateway to request the topology. Might be worth investigating whether this is an issue.

Right now I'm not sure how problematic it is, whether it is just toil or whether this might be an actual bigger issue.

relates to https://jira.camunda.com/browse/SUPPORT-16945

### LINKED ISSUE #13431: Gateway readiness fails when tls enabled
**Describe the bug**

When tls enabled on gateway for [secure client communication](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/security/secure-client-communication/), readiness check fails. 

<details><summary>Failed health status</summary>
 <p>

```
{
   "components" : {
      "diskSpace" : {
         "details" : {
           ....
         },
         "status" : "UP"
      },
      "gatewayClusterAwareness" : {
         "status" : "UP"
      },
      "gatewayPartitionLeaderAwareness" : {
         "status" : "UP"
      },
      "gatewayResponsive" : {
         "details" : {
            "error" : "java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\nChannel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]",
            "healthZeebeClientProperties" : {
               "requestTimeout" : "PT0.5S",
               "securityProperties" : {}
            },
            "timeOut" : "PT0.5S"
         },
         "status" : "DOWN"
      },
      "gatewayStarted" : {
         "status" : "UP"
      },
      "livenessGatewayClusterAwareness" : {
         "details" : {
            "derivedFrom" : "ClusterAwarenessHealthIndicator",
            "lastSeenDelegateHealthStatus" : {
               "status" : "UP"
            },
            "maxDowntime" : "PT5M",
            "wasEverUp" : true
         },
         "status" : "UP"
      },
      "livenessGatewayPartitionLeaderAwareness" : {
         "details" : {
            "derivedFrom" : "PartitionLeaderAwarenessHealthIndicator",
            "lastSeenDelegateHealthStatus" : {
               "status" : "UP"
            },
            "maxDowntime" : "PT5M",
            "wasEverUp" : true
         },
         "status" : "UP"
      },
      "livenessGatewayResponsive" : {
         "details" : {
            "derivedFrom" : "ResponsiveHealthIndicator",
            "lastSeenDelegateHealthStatus" : {
               "details" : {
                  "error" : "java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception\nChannel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]",
                  "healthZeebeClientProperties" : {
                     "requestTimeout" : "PT5S",
                     "securityProperties" : {}
                  },
                  "timeOut" : "PT5S"
               },
               "status" : "DOWN"
            },
            "maxDowntime" : "PT10M",
            "wasEverUp" : false
         },
         "status" : "DOWN"
      },
      "livenessMemory" : {
         "details" : {
            "threshold" : 0.01
         },
         "status" : "UP"
      },
      "livenessState" : {
         "status" : "UP"
      },
      "ping" : {
         "status" : "UP"
      },
      "readinessState" : {
         "status" : "UP"
      }
   },
   "groups" : [
      "liveness",
      "readiness",
      "startup"
   ],
   "status" : "DOWN"
}
```

</p>
</details>

Both `gatewayResponsive` and `livenssGatewayResponsive` fails because of some SSL error.   

This was unnoticed before because readiness check was disabled by default in camunda platform helm until 8.2. From 8.2 it is enabled by default. 

**To Reproduce**

Start a single gateway with TLS enabled as documented [here](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/security/secure-client-communication/). And then query `http://gateway-host:9600/actuator/health`.

**Expected behavior**

Health and readiness check should work with TLS enabled.

**Environment:**
- Zeebe Version: All versions (reproduced with 8.0.x, 8.1.5, and 8.2.7)

related to https://jira.camunda.com/browse/SUPPORT-17529 
https://jira.camunda.com/browse/SUPPORT-16945

### PR DESCRIPTION
**Pull request by megglos**
## Description

It doesn't yield much benefit over the existing health indicators for cluster and leader awareness. It rather adds complexity requiring the user to configure the client additionally to the gateway itself while not adding much benefit over the existing checks. General GRPC availability can be validated [using the GRPC Health Probe instead](https://github.com/camunda/zeebe/pull/7737).

## Related issues

closes #13431 
closes #11799

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by megglos** [comment]
Hey @aivinog1,
as you contributed previously to the [internal client config ](https://github.com/camunda/zeebe/commit/f93c8dcb96f69c2633d0d91621d2bbe4ecbec107) do you have any feedback on our intend to remove this indicator?

**Review by npepinpe — APPROVED** [review]
:tada: 

Can we backport this to 8.2. and 8.1 as well?

**Comment by megglos** [comment]
> 🎉
> 
> Can we backport this to 8.2. and 8.1 as well?

I'm in favor of doing so, it's not strictly a breaking change, will have to announce it in the docs still though as if anyone used the specific client config they can remove it going forward.

**Comment by megglos** [comment]
bors merge

**Pull request merged**
