### PR TITLE
fix(gateway, broker, clients/java): allow to use IPv6 addresses in a cluster

### LINKED ISSUE #5951: Gateway not able to parse ipv6 addresses
**Describe the bug**
I am trying to get a 1 gateway & 3 broker setup done on an env with **ipv6.**

I am getting this in each broker, so I know they are starting correctly.

```
2020-12-02 07:38:26.429 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-2 succeeded. Started 14 steps in 16049 ms.
```
however when I try to exec inside the broker and try "zbctl status" or "zbctl status --insecure" I keep getting this error

```
kubectl exec -it z2943-broker1-01 /bin/bash
root@z2943-broker1-01:/usr/local/zeebe# zbctl status
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"
root@z2943-broker1-01:/usr/local/zeebe# zbctl status --insecure
Error: rpc error: code = Unknown desc = 
```
If I try to specify the pod address...
```
root@z2943-broker1-01:/usr/local/zeebe# zbctl status --address 240b:c0e0:202:5e2b:b424:2:0:51f
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address tcp/c0e0: unknown port"
root@z2943-broker1-01:/usr/local/zeebe# zbctl status --address [240b:c0e0:202:5e2b:b424:2:0:51f]
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: address [240b:c0e0: missing ']' in address"
```

My guess is that the brokers are not able to differentiate between a ipv4 and ipv6 address.

**To Reproduce**
1 gateway with 3 clusters with the below settings - 

for broker - > image version is 0.25.1
env vars are ->
     ZEEBE_BROKER_CLUSTER_NODEID: '1' #different 0,1,2 for each of the three brokers.
     ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT: '3'
     ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR: '3'
     ZEEBE_BROKER_CLUSTER_CLUSTERSIZE: '3'
     ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS: '{{APP_NAME}}-broker1-cl-0:26502,{{APP_NAME}}-broker2-cl-0:26502,{{APP_NAME}}-broker3-cl-0:26502'
     ZEEBE_BROKER_CLUSTER_CLUSTERNAME: 'zeebe-cluster'
     ZEEBE_BROKER_NETWORK_COMMANDAPI_PORT: '26501'
     ZEEBE_BROKER_NETWORK_INTERNALAPI_PORT: '26502'
     ZEEBE_BROKER_NETWORK_MONITOIRNGAPI_PORT: '9600'

for gateway -> image version is 0.25.1
env vars are ->
     ZEEBE_STANDALONE_GATEWAY: 'true'
     ZEEBE_GATEWAY_NETWORK_HOST: '0.0.0.0'
     ZEEBE_GATEWAY_NETWORK_PORT: '26500'
     ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT: '{{APP_NAME}}-broker1-cl-0:26502'
     ZEEBE_GATEWAY_CLUSTER_CLUSTERNAME: 'zeebe-cluster'
     ZEEBE_GATEWAY_CLUSTER_MEMBERID: '3'
     ZEEBE_GATEWAY_CLUSTER_HOST: '0.0.0.0'
     ZEEBE_GATEWAY_CLUSTER_PORT: '26502'

**Expected behavior**
Gateway should be able to connect to the brokers and I should be able to use zbctl status to see the brokers,replications,partitions.

**Log/Stacktrace**
This error comes up inside the gateway
```
2020-12-02 07:45:11.612 [] [grpc-default-executor-0] ERROR io.grpc.internal.SerializingExecutor - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@501e95a8
java.lang.NumberFormatException: For input string: "c0e0"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at io.zeebe.gateway.EndpointManager.addBrokerInfo(EndpointManager.java:78) ~[zeebe-gateway-0.25.1.jar:0.25.1]
	at io.zeebe.gateway.EndpointManager.lambda$topology$1(EndpointManager.java:253) ~[zeebe-gateway-0.25.1.jar:0.25.1]
	at org.agrona.collections.IntArrayList.forEach(IntArrayList.java:588) ~[agrona-1.8.0.jar:1.8.0]
	at io.zeebe.gateway.EndpointManager.topology(EndpointManager.java:250) ~[zeebe-gateway-0.25.1.jar:0.25.1]
	at io.zeebe.gateway.GatewayGrpcService.topology(GatewayGrpcService.java:135) ~[zeebe-gateway-0.25.1.jar:0.25.1]
	at io.zeebe.gateway.protocol.GatewayGrpc$MethodHandlers.invoke(GatewayGrpc.java:1532) ~[zeebe-gateway-protocol-impl-0.25.1.jar:0.25.1]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.33.0.jar:1.33.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.33.0.jar:1.33.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

My pods are
```
kubectl get pods -o wide | grep z2943
z2943-broker1-01                        1/1     Running            0          54m     240b:c0e0:202:5e2b:b424:2:0:51f
z2943-broker2-01                        1/1     Running            0          54m     240b:c0e0:202:5e2b:b424:2:0:37b
z2943-broker3-01                        1/1     Running            0          54m     240b:c0e0:202:5e2b:b424:2:0:c56
z2943-gateway-01                        1/1     Running            0          53m     240b:c0e0:202:5e2b:b424:2:0:af3
```

**Environment:**
 - OS: kubernetes - ipv6
 - Zeebe Version: 0.25.1
 - Configuration: 1 gateway with 3 brokers

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

This is the backported #6484 to 0.25

## Related issues

closes #5951 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [X] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [X] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [X] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Hey, there's some testcontainers related errors. It seems to be related to https://github.com/testcontainers/testcontainers-java/issues/3574, and the solution is to bump the testcontainers version to 1.15.1. Could you also add that to be PRs?

**Comment by aivinog1** [comment]
Hey @npepinpe, I cherry-picked your commit 7cc8808829261ee6a0a69407fac212c418cc7cd9 and applied it here with a few modifications. Can you take a look at it? After that, I will squash them into one commit :)

**Comment by npepinpe** [comment]
Seems like the atomix module is complaining about a used undeclared dependency:

```
[2021-04-16T15:52:11.510Z] [WARNING] Used undeclared dependencies found:
[2021-04-16T15:52:11.510Z] [WARNING]    io.zeebe:zeebe-util:jar:0.25.4-SNAPSHOT:compile
[2021-04-16T15:52:11.510Z] [INFO] Add the following to your pom to correct the missing dependencies: 
[2021-04-16T15:52:11.510Z] [INFO] 
[2021-04-16T15:52:11.510Z] <dependency>
[2021-04-16T15:52:11.510Z]   <groupId>io.zeebe</groupId>
[2021-04-16T15:52:11.510Z]   <artifactId>zeebe-util</artifactId>
[2021-04-16T15:52:11.510Z]   <version>0.25.4-SNAPSHOT</version>
[2021-04-16T15:52:11.510Z] </dependency>
```

**Comment by aivinog1** [comment]
@npepinpe Hey, I fixed the dependency issue, can you try to build again, please? :)

**Review by npepinpe — APPROVED** [review]
bors r+

**Pull request merged**
