### PR TITLE
[Backport stable/1.2] Close journal readers to remove references to compacted segments

### LINKED ISSUE #7767: Readers are not closed
**Describe the bug**

It looks like some journal readers are not closed. They are referenced in the list of readers in the "SegmentedJournal", but not used anywhere else. 

image

This can lead to the segments not deleted from the disk. In the following the first segment  created several hours ago is marked for deletion. But not yet deleted because there are readers referencing it.

image

**To Reproduce**

Start a cluster, and introduce several leader changes by disconnecting networks. Do not restart the pods as this will clean up the files.

**Expected behavior**
No references to deleted files should exists for ever.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Backport of #8124 

closes #7767

### CODE REVIEW

**Comment by deepthidevaki** [comment]
@Zelldon  There was a small merge conflict in `RaftContext`. Otherwise it is same as the original PR.

**Comment by deepthidevaki** [comment]
Also had to add missing utility functions in the test.

**Review by ChrisKujawa — APPROVED** [review]
:+1:

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors merge

**Pull request merged**
