### PR TITLE
Mac docker install

### PR DESCRIPTION
**Pull request by danielccyr**
for when the `camunda/zeebe:latest` is ready

### CODE REVIEW

**Comment by meyerdan** [comment]
Hi Daniel,

thanks for sending us our first PR :) 

@menski, @jsam does one of you want to take this?

**Comment by menski** [comment]
Hi @danielccyr,

thanks for providing this documentation. But may I ask why you describe how to setup docker with `docker-machine` on Mac and Windows. As far as I know the current recommend setup for [Mac](https://docs.docker.com/docker-for-mac/install/) and [Windows](https://docs.docker.com/docker-for-windows/install/) does not use `docker-machine` anymore as they rely on xhyve resp. hyper-v and not Virtual Box.

Also if you use `docker-machine` what is the advantage of creating a new `docker-machine`/Virtual Box instance only for zeebe instead of using the default one? Sorry I'm neither a Mac nor Windows user so maybe I'm not aware of how to run docker effectively on these systems.

Cheers,
Sebastian

**Comment by danielccyr** [comment]
Hi @menski 

The docker-machine way is the only way that will work for pre-2010 Macs;
hence the " (using docker-machine)" words I used;
In the docs, this PR should be at the end of the Docker Install section and targeted to owners of older hardware

**Comment by danielccyr** [comment]
second part of your question, the [docs](https://docs.docker.com/machine/get-started/#use-machine-to-run-docker-containers) states
"If this is your first machine, name it default as shown in the example. If you already have a “default” machine, choose another name for this new machine"

**Comment by menski** [comment]
Hi @danielccyr,

thanks again for your contribution. I merged it but had to [adjust the memory size to 4GB](https://github.com/zeebe-io/zeebe/commit/65108b27d3f9f16661b99c073898eb8a4fd1f90e) as we noted yesterday that a [VM with 2GB is not enough](https://github.com/zeebe-io/zeebe/issues/390). Maybe you could try out the latest camunda/zeebe:0.1.0 image and verify that it works on your system. Thanks

Cheers,
Sebastian

**Pull request merged**
