### PR TITLE
Clean up ES exporter test refactoring

### LINKED ISSUE #8609: [EPIC] Refactor Elasticsearch Exporter Tests
**Description**

The `elasticsearch-exporter` integration tests are currently quite convoluted. Historically, the `elasticsearch-exporter` tests used to depend on `zeebe-test` which was removed in https://github.com/camunda-cloud/zeebe/pull/8608. During the removal, some of the `zeebe-test` utilities ended up in the `elasticsearch-exporter` module where we also needed to add a lot of test scoped dependencies.

The main goals here were:

- Cover as much as possible via only unit tests. This gives us a faster feedback cycle when changing something - developers can focus on first fixing unit tests, which have smaller blast radius and faster execution, before even looking at integration tests.
- Narrow the scope of the integration tests as much as possible. This meant getting rid of the broker, workflow engine semantics, etc., and just testing the integration of the exporter instance with Elasticsearch.

In general, I wanted to keep the same coverage as before. I think the coverage is now higher, but that was not the original motivation.

**Breakdown**

- [x] #9162
- [x] #9315
- [x] #9316
- [x] #9317
- [x] #9318
- [x] #9319
- [x] #9320
- [x] #9321
- [x] Clean up ElasticsearchExporter test refactoring

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR cleans up some of the left overs from the test refactoring. It removes unnecessary POM properties and configuration (as they are not required anymore), and it turns some of the DTOs into records to cut down on boilerplate.

It also removes the special exporter job, and now considers the ES exporter as a normal module CI-wise. The integration tests are fairly lightweight and stable now, I don't see much need to have a separate job anymore.

## Related issues

closes #8609 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Uh, the Jenkins pipeline ran into a flaky test for `ElasticsearchExporterIT#shouldExportJobRecordWithOverlappingCustomHeaders`, where exporting just timed out after 30 seconds.

I have brought shame and dishonor :dizzy_face:

**Comment by npepinpe** [comment]
Adding the ES exporter tests to the integration job seems to add about 1 minute to it. So it's a ~12% increase more or less, for that single job. I don't know what to think about it. We could omit changing the pipeline for now, I guess. I feel like this won't scale over time, maybe we need to rethink our approach in how we divide IT and units. :thinking:

**Review by remcowesterhoud — APPROVED** [review]
Changes look good ⭐ 

I would propose leaving the exporters as a separate step in the pipeline instead of adding a minute to the IT steps. That way they can at least run in parallel.

**Comment by npepinpe** [comment]
I don't like that there's a special treatment for the ES tests which is undocumented, but I agree it's probably better to tackle this in a different scope (for example, why do we run the exporter tests separately but the broker's integration tests are in the same IT job?).

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
