### PR TITLE
feat(broker): distinguish multi-instance body records

### LINKED ISSUE #2892: I can distinguish the multi-instance body from the inner instances
**Is your feature request related to a problem? Please describe.**
Looking at the record stream (as an exporter), it's hard to distinguish between the multi-instance body from the inner instances. The records are equal (same element id, same element type, etc.) except that the inner instances have the key of the body instance as flow scope key.

**Describe the solution you'd like**
* the multi-instance body has the BPMN element type `MULTI_INSTANCE_BODY`

**Describe alternatives you've considered**
* using only the flow scope key to distinguish the records - the consumer/exporter needs to be aware of the previous records
* using a special element id (e.g. `elementId#multiInstanceBody` like in Camunda BPM 7) - confusing to see records for non-existing element id

### PR DESCRIPTION
**Pull request by saig0**
## Description

* the multi-instance body has the BPMN element type `MULTI_INSTANCE_BODY`
* the inner instances have the BPMN element type of the element itself (e.g. `SERVICE_TASK`)

## Related issues

closes #2892 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by saig0** [comment]
bor r+

**Comment by saig0** [comment]
bors retry

**Pull request merged**
