### PR TITLE
feat(bpmn elements): allow conversion of BpmnElementTypes back to String

### LINKED ISSUE #7506: Offer two-way conversion of supported BpmnElementTypes to BpmnModelConstants
**Is your feature request related to a problem? Please describe.**
In Optimize, we import Runtime engine activity instances and store it's type as part of Optimize's activity instance data structure. For example, a start event from the engine will have type `startEvent` (or any other type from `BpmnModelConstants`). We use these types for some of our reports and the underlying aggregations. Think of a user task report, this will filter for all activity instances that have type `userTask`.

Now that we also import Zeebe process instance data, we have the following problem:
- Zeebe process instance records have their own `bpmnElementType`, which is independent from the runtime engine. When we read a process instance event that has been exported from Zeebe, we extract the type and now see a value like `USER_TASK`. Before we save that in Optimize, we need to convert it to be `userTask` to make it work. Currently we have a basic switch statement for this conversion
- If a new `BpmnElementType` is added to Zeebe (like with `SEND_TASK ` in the most recent release), Optimize doesn't know how to make this conversion to its `BpmnModelConstants` representation and the import fails for that activity.

**Describe the solution you'd like**
Rather than Optimize needing to support the same list of supported elements for the reverse conversion, I think it makes sense for Zeebe to allow conversion of each enum field back to its `BpmnModelConstants` String representation as part of the enum itself.

**Describe alternatives you've considered**
- Handling this in Optimize would be tolerable, but an unknown change to the enum breaks the import, as described above 
- Saving the `bpmnElementType` string isn't an option we would like to explore, as Optimize is quite tightly built around the existing `BpmnModelConstants` we get from the runtime engine. If we ever want to support both zeebe and the runtime engine in the same Optimize instance, this would make things awkward

**Additional context**
This could probably be done at the same time as https://github.com/camunda-cloud/zeebe/issues/7290

### PR DESCRIPTION
**Pull request by RomanJRW**
Returns the optional BpmnModelConstant String representation of each BpmnElementType to allow Optimize to convert them to compatible types consistent with their model constant

## Description

closes #7506

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
bors merge

Thanks for the PR!

**Comment by npepinpe** [comment]
bors cancel

Looks like there's a checkstyle violation :) 

```
[2021-07-15T16:19:05.660Z] [ERROR] src/main/java/io/camunda/zeebe/protocol/record/value/BpmnElementType.java:[63,3] (coding) DeclarationOrder: Instance variable definition in wrong order.
```

**Comment by npepinpe** [comment]
The instance variables would go above the constructors, but below the constants. Once you've fixed this, feel free to merge this yourself by commenting `bors r+`

**Comment by RomanJRW** [comment]
Thanks for the help and quick review @npepinpe 👍 
I fixed the previous problem but there is another checkstyle violation it looks like. Where can I actually find the violations themselves? The logs tell me the violating file but I couldn't see where the specific problem is

**Comment by npepinpe** [comment]
It's buried in the log, unfortunately, because we build things in parallel (so the logs are sort of jumbled up). If you build locally and not in parallel it becomes clearer.

Now there is a formatting issue, which is most likely in the file. If you run a local build it will format the file appropriately.

**Comment by npepinpe** [comment]
Weird, the build passed but bors failed. 🤷‍♂️ 

bors retry

**Pull request merged**
