### PR TITLE
chore(broker): monitor health of raft partition

### LINKED ISSUE #3853: Health monitor can monitor raft threads of a partition
**Description**

For the health monitor to detect failures in raft threads, we have to make the `RaftPartition` monitorable and able to report failures back to the monitor.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Integrate raft health check to the broker

## Related issues

closes #3853

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by deepthidevaki** [comment]
I was running a benchmark this changes. Observed the following:

```
I 2020-03-18T18:45:11.659679902Z 2020-03-18 18:45:11.658 [] [raft-server-2-raft-partition-partition-1] ERROR io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - An uncaught exception occurred
 
I 2020-03-18T18:45:11.659704106Z java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/96899299-3-1584557110454/007259.sst
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbPendingSnapshot.write(DbPendingSnapshot.java:103) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.atomix.protocols.raft.roles.PassiveRole.onInstall(PassiveRole.java:297) ~[atomix-raft-3.2.0-SNAPSHOT.jar:?]
	at io.atomix.protocols.raft.roles.FollowerRole.onInstall(FollowerRole.java:81) ~[atomix-raft-3.2.0-SNAPSHOT.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$null$10(RaftContext.java:229) ~[atomix-raft-3.2.0-SNAPSHOT.jar:?]
	at io.atomix.protocols.raft.impl.RaftContext.lambda$runOnContext$33(RaftContext.java:266) ~[atomix-raft-3.2.0-SNAPSHOT.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:182) ~[atomix-utils-3.2.0-SNAPSHOT.jar:?]
	at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:55) ~[atomix-utils-3.2.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.nio.file.NoSuchFileException: /usr/local/zeebe/data/raft-partition/partitions/1/pending/96899299-3-1584557110454/007259.sst
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at io.zeebe.broker.clustering.atomix.storage.snapshot.DbPendingSnapshot.write(DbPendingSnapshot.java:98) ~[zeebe-broker-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	... 12 more
 
I 2020-03-18T18:45:11.660772631Z 2020-03-18 18:45:11.660 [Broker-1-SnapshotDirector-1] [Broker-1-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Replicate snapshot chunk /usr/local/zeebe/data/raft-partition/partitions/1/snapshots/96899299-3-1584557110454/008369.sst
 
I 2020-03-18T18:45:11.662415483Z 2020-03-18 18:45:11.662 [Broker-2-ZeebePartition-1] [Broker-2-zb-actors-1] ERROR io.zeebe.broker.system - raft failed, marking it as unhealthy
```

As expected, an exception caused raft to be marked as unhealthy.

Reason for this exception is unknown though. Also not sure if this exception should lead to raft failure or is it something that can be handled with in the operation.

**Comment by Zelldon** [comment]
Probably related https://github.com/zeebe-io/zeebe/issues/4078

**Comment by npepinpe** [comment]
I'm confused by the stack trace - it failed to write because the file does not exist? I mean...it shouldn't exist before we write it? Does this error mean that it was deleted during the write?

**Comment by npepinpe** [comment]
Nevermind, I looked at it, yes the file is created before we write by the `Files.newByteChannel`, so it is strange it is removed - the only thing I can think of is a slow follower replicating, but the leader getting a new snapshot which causes the deletion of this orphaned snapshot. This was not an issue before because with multiple snapshots the chances of this happening were quite low, but I guess with a single snapshot this is more likely now.

I'm not sure what the best solution is in the end to handle these two concurrent snapshot replication mechanisms, obviously it's causing issues - let's discuss it tomorrow. I guess since the others are working on FEEL, you guys are automatically volunteers for this ;)

**Review by npepinpe — COMMENTED** [review]
LGTM - one small question, should we remove the failure listener on closing? As far as I can tell it should have little to no side effect, as even if the actor closes and the raft partition does not, since the monitors are poll based it should be fine. Though if we ever get to a point where we start/stop partition it might cause a memory leak of adding listeners, I guess. 

I would personally remove the listener on close for completion sake, but open to challenge it.

**Comment by deepthidevaki** [comment]
Do you mean when closing `ZeebePartition`? It would make sense to remove the listeners, not just the failure listener, but rolechange and commit listeners as well.

**Comment by npepinpe** [comment]
I believe we already remove the commit and role change listeners on close - I think I remember fixing an issue related to that :thinking: Did you see a case where those listeners where not removed?

**Comment by deepthidevaki** [comment]
Yes. They are removed. It was not where I expected it to be :grinning:

**Comment by deepthidevaki** [comment]
@npepinpe wondering if #4092 is enough as a health detection instead of this pr.

**Comment by npepinpe** [comment]
Hm, if unhealthy on the Raft side always translate to us transitioning to inactive (which could make sense), then that PR would be enough. Is this the case? Should it be the case? Intuitively it makes sense to me, but I might be forgetting something.

**Comment by deepthidevaki** [comment]
> Hm, if unhealthy on the Raft side always translate to us transitioning to inactive (which could make sense), then that PR would be enough. Is this the case? Should it be the case? Intuitively it makes sense to me, but I might be forgetting something.

Normally, yes. But after the discussion for this PR #https://github.com/zeebe-io/atomix/pull/195 , in case transition to inactive failed due to exceptions, there is a rare chance that notification is missed. So let's continue with this PR. I will update this PR once https://github.com/zeebe-io/atomix/pull/195 is merged.

**Review by npepinpe — COMMENTED** [review]
LGTM :+1: 

I know we have a test checking the health of the partition - can we build on that to check that we close the partition as well? I'm not sure how observable it is that the partition is closed :thinking: 

Side note, on the Atomix side we will block on the inactiveTransitionFuture - should we add a time out there? I'm a bit wary of blocking forever in case we have some problem with our chain of async operations.

**Comment by deepthidevaki** [comment]
I don't think it is observable.

**Comment by deepthidevaki** [comment]
> Side note, on the Atomix side we will block on the inactiveTransitionFuture - should we add a time out there? I'm a bit wary of blocking forever in case we have some problem with our chain of async operations.

What worse can happen if it is blocked for ever? Partition is already in failed state and not recoverable.

**Comment by npepinpe** [comment]
At the moment, nothing I guess, because we will have exactly one listener - but from reading the code it breaks the principle of least astonishment imo. I can imagine it would also lead to us scratching our heads some times, like "why is it saying it will transition to inactive but then not doing X, Y, Z?".

**Review by npepinpe — APPROVED** [review]

**Comment by deepthidevaki** [comment]
Right. In general that is a problem I think. We don't have timeouts for role transitions in ZeebePartition. We rely on exceptionally completed futures to detect transition failed. But we don't currently detect if it never completes.

**Pull request merged**
