### PR TITLE
Check backwards compatibility in Go client

### LINKED ISSUE #3640: Enforce backwards compatibility Go client
**Description**

To enforce backwards compatibility in the Go client, we first must decide and document what guarantees we want to provide since [most changes](https://blog.merovius.de/2015/07/29/backwards-compatibility-in-go.html) have the potential to break something. One simple option is to follow the [Go1 promise](https://golang.org/doc/go1compat#expectations). This is also easily supported by this [tool](https://github.com/smola/gocompat).

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Prevents breaking backwards compatibility to the extent that Go1 makes the same guarantee (i.e., we can still add fields to structs and methods to types although these might break clients).

## Related issues

closes #3640 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — CHANGES_REQUESTED** [review]
Looks good :+1: 

As discussed, just add the API update as part of the release process.

**Comment by MiguelPires** [comment]
Thanks for the feedback @npepinpe. The compatibility file is now updated each release. I'll also add a wiki page on what to do when we have breaking changes

**Comment by MiguelPires** [comment]
Hey @npepinpe. I made an additional minor modification: 
The ignored changes files (used when we have to break compatibility) are already set up in the parent/pom.xml and they're removed during the release, if any exist. It's a small change but I think it completely eliminates any backwards compatibility related work during the release. The only work that must be done is if you have breaking changes and it's documented here https://github.com/zeebe-io/zeebe/wiki/Breaking-Changes

**Comment by npepinpe** [comment]
Looks good but the builds are failing due to missing symbols??

**Review by npepinpe — APPROVED** [review]
Looks good, thanks! :+1:

**Pull request merged**
