### PR TITLE
4581 run all tests

### LINKED ISSUE #4581: Run all tests, then analyze the log to fail the build
**Description**

Currently tests will fail the build as soon as one module has test failures. 

The goal of this issue is to run all tests, then analyze the log for test failures and fail the build

### PR DESCRIPTION
**Pull request by pihme**
## Description

This runs all tests even if there are failures in the first modules. After running the tests, the log is parsed to fail the build stage automatically in case of failures. 

## Related issues

closes #4581

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

commit messages will be cleaned up after review

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 843c07c4a2cd2788c297804f2d74b2bf09333407
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a850871343b1e8d8eaed6f3c52d0cb4f0270d425
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: cd93c09e1a2ac91e1ba53ae13c461ad0ddcf30b1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by menski — CHANGES_REQUESTED** [review]
It took me a while to find the new `-fn` flag in the mvn command. Could you please use the long version of the flag which makes it also more clear what the behavior is (`--fail-never `).

Then I noticed that you use the same name for the `test.txt` meaning all parallel CI branches will write in the same file. Which might create a problem based on the timing, I would recommend to use a script specific file or us a tempfile, i.e. calling `tmpfile=$(mktemp)`.

Alternative to the first `if` statement and the `PIPESTATUS` could be the bash option `pipefail`, i.e.
```
set -o pipefail
```

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 843c07c4a2cd2788c297804f2d74b2bf09333407
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a850871343b1e8d8eaed6f3c52d0cb4f0270d425
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: cd93c09e1a2ac91e1ba53ae13c461ad0ddcf30b1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by menski** [comment]
Is there a reason why you prefer the `PIPESTATUS` over the `set -o pipefail` option. I would prefer to have `pipefail` set to handle pipe failures in general.

**Review by menski — APPROVED** [review]
Okay then let's keep it like this and see what the next changes bring.

bors r+

**Pull request merged**
