### PR TITLE
[BACKPORT] chore(raft): fix flaky failover test

### LINKED ISSUE #4662: RaftFailOverTest.shouldTruncateLogOnNewerSnapshot flaky
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**

Kept the build: https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/4340-do-not-merge-monitor-build-health-branch/1125/

### LINKED ISSUE #4954: RaftFailOverTest.shouldTruncateLogOnNewerSnapshotEvenAfterRestart flaky
**Summary**

- How often does the test fail? at least once so far
- Does it block your work? no
- Do we suspect that it is a real failure? unknown

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.lang.AssertionError: 

Expecting:
 <[Indexed{index=62, entry=ZeebeEntry{term=1, timestamp=1594460614633, lowestPosition=661, highestPosition=671}},
    Indexed{index=63, entry=ZeebeEntry{term=1, timestamp=1594460614640, lowestPosition=672, highestPosition=682}},
    Indexed{index=64, entry=ZeebeEntry{term=1, timestamp=1594460614640, lowestPosition=683, highestPosition=693}},
    Indexed{index=65, entry=ZeebeEntry{term=1, timestamp=1594460614640, lowestPosition=694, highestPosition=704}},
    Indexed{index=66, entry=ZeebeEntry{term=1, timestamp=1594460614640, lowestPosition=705, highestPosition=715}},
    Indexed{index=67, entry=ZeebeEntry{term=1, timestamp=1594460614644, lowestPosition=716, highestPosition=726}},
    Indexed{index=68, entry=ZeebeEntry{term=1, timestamp=1594460614644, lowestPosition=727, highestPosition=737}},
    Indexed{index=69, entry=ZeebeEntry{term=1, timestamp=1594460614644, lowestPosition=738, highestPosition=748}},
    Indexed{index=70, entry=ZeebeEntry{term=1, timestamp=1594460614644, lowestPosition=749, highestPosition=759}},
    Indexed{index=71, entry=ZeebeEntry{term=1, timestamp=1594460614646, lowestPosition=760, highestPosition=770}},
    Indexed{index=72, entry=ZeebeEntry{term=1, timestamp=1594460614646, lowestPosition=771, highestPosition=781}},
    Indexed{index=73, entry=ZeebeEntry{term=1, timestamp=1594460614646, lowestPosition=782, highestPosition=792}},
    Indexed{index=74, entry=ZeebeEntry{term=1, timestamp=1594460614646, lowestPosition=793, highestPosition=803}},
    Indexed{index=75, entry=ZeebeEntry{term=1, timestamp=1594460614650, lowestPosition=804, highestPosition=814}},
    Indexed{index=76, entry=ZeebeEntry{term=1, timestamp=1594460614650, lowestPosition=815, highestPosition=825}},
    Indexed{index=77, entry=ZeebeEntry{term=1, timestamp=1594460614650, lowestPosition=826, highestPosition=836}},
    Indexed{index=78, entry=ZeebeEntry{term=1, timestamp=1594460614650, lowestPosition=837, highestPosition=847}},
    Indexed{index=79, entry=ZeebeEntry{term=1, timestamp=1594460614671, lowestPosition=848, highestPosition=858}},
    Indexed{index=80, entry=ZeebeEntry{term=1, timestamp=1594460614671, lowestPosition=859, highestPosition=869}},
    Indexed{index=81, entry=ZeebeEntry{term=1, timestamp=1594460614671, lowestPosition=870, highestPosition=880}},
    Indexed{index=82, entry=ZeebeEntry{term=1, timestamp=1594460614673, lowestPosition=881, highestPosition=891}},
    Indexed{index=83, entry=ZeebeEntry{term=1, timestamp=1594460614677, lowestPosition=892, highestPosition=902}},
    Indexed{index=84, entry=ZeebeEntry{term=1, timestamp=1594460614682, lowestPosition=903, highestPosition=913}},
    Indexed{index=85, entry=ZeebeEntry{term=1, timestamp=1594460614684, lowestPosition=914, highestPosition=924}},
    Indexed{index=86, entry=ZeebeEntry{term=1, timestamp=1594460614685, lowestPosition=925, highestPosition=935}},
    Indexed{index=87, entry=ZeebeEntry{term=1, timestamp=1594460614689, lowestPosition=936, highestPosition=946}},
    Indexed{index=88, entry=ZeebeEntry{term=1, timestamp=1594460614689, lowestPosition=947, highestPosition=957}},
    Indexed{index=89, entry=ZeebeEntry{term=1, timestamp=1594460614689, lowestPosition=958, highestPosition=968}},
    Indexed{index=90, entry=ZeebeEntry{term=1, timestamp=1594460614689, lowestPosition=969, highestPosition=979}},
    Indexed{index=91, entry=ZeebeEntry{term=1, timestamp=1594460614693, lowestPosition=980, highestPosition=990}},
    Indexed{index=92, entry=ZeebeEntry{term=1, timestamp=1594460614693, lowestPosition=991, highestPosition=1001}},
    Indexed{index=93, entry=ZeebeEntry{term=1, timestamp=1594460614693, lowestPosition=1002, highestPosition=1012}},
    Indexed{index=94, entry=ZeebeEntry{term=1, timestamp=1594460614693, lowestPosition=1013, highestPosition=1023}},
    Indexed{index=95, entry=ZeebeEntry{term=1, timestamp=1594460614697, lowestPosition=1024, highestPosition=1034}},
    Indexed{index=96, entry=ZeebeEntry{term=1, timestamp=1594460614697, lowestPosition=1035, highestPosition=1045}},
    Indexed{index=97, entry=ZeebeEntry{term=1, timestamp=1594460614697, lowestPosition=1046, highestPosition=1056}},
    Indexed{index=98, entry=ZeebeEntry{term=1, timestamp=1594460614697, lowestPosition=1057, highestPosition=1067}},
    Indexed{index=99, entry=ZeebeEntry{term=1, timestamp=1594460614700, lowestPosition=1068, highestPosition=1078}},
    Indexed{index=100, entry=ZeebeEntry{term=1, timestamp=1594460614700, lowestPosition=1079, highestPosition=1089}},
    Indexed{index=101, entry=ZeebeEntry{term=1, timestamp=1594460614700, lowestPosition=1090, highestPosition=1100}},
    Indexed{index=102, entry=InitializeEntry{term=2, timestamp=2020-07-11 09:43:35,666}},
    Indexed{index=103, entry=ZeebeEntry{term=2, timestamp=1594460616007, lowestPosition=1101, highestPosition=1111}},
    Indexed{index=104, entry=ZeebeEntry{term=2, timestamp=1594460616029, lowestPosition=1112, highestPosition=1122}},
    Indexed{index=105, entry=ZeebeEntry{term=2, timestamp=1594460616030, lowestPosition=1123, highestPosition=1133}},
    Indexed{index=106, entry=ZeebeEntry{term=2, timestamp=1594460616030, lowestPosition=1134, highestPosition=1144}},
    Indexed{index=107, entry=ZeebeEntry{term=2, timestamp=1594460616030, lowestPosition=1145, highestPosition=1155}},
    Indexed{index=108, entry=ZeebeEntry{term=2, timestamp=1594460616034, lowestPosition=1156, highestPosition=1166}},
    Indexed{index=109, entry=ZeebeEntry{term=2, timestamp=1594460616034, lowestPosition=1167, highestPosition=1177}},
    Indexed{index=110, entry=ZeebeEntry{term=2, timestamp=1594460616034, lowestPosition=1178, highestPosition=1188}},
    Indexed{index=111, entry=ZeebeEntry{term=2, timestamp=1594460616035, lowestPosition=1189, highestPosition=1199}},
    Indexed{index=112, entry=ZeebeEntry{term=2, timestamp=1594460616038, lowestPosition=1200, highestPosition=1210}},
    Indexed{index=113, entry=ZeebeEntry{term=2, timestamp=1594460616038, lowestPosition=1211, highestPosition=1221}},
    Indexed{index=114, entry=ZeebeEntry{term=2, timestamp=1594460616038, lowestPosition=1222, highestPosition=1232}},
    Indexed{index=115, entry=ZeebeEntry{term=2, timestamp=1594460616038, lowestPosition=1233, highestPosition=1243}},
    Indexed{index=116, entry=ZeebeEntry{term=2, timestamp=1594460616042, lowestPosition=1244, highestPosition=1254}},
    Indexed{index=117, entry=ZeebeEntry{term=2, timestamp=1594460616042, lowestPosition=1255, highestPosition=1265}},
    Indexed{index=118, entry=ZeebeEntry{term=2, timestamp=1594460616042, lowestPosition=1266, highestPosition=1276}},
    Indexed{index=119, entry=ZeebeEntry{term=2, timestamp=1594460616042, lowestPosition=1277, highestPosition=1287}},
    Indexed{index=120, entry=ZeebeEntry{term=2, timestamp=1594460616045, lowestPosition=1288, highestPosition=1298}},
    Indexed{index=121, entry=ZeebeEntry{term=2, timestamp=1594460616046, lowestPosition=1299, highestPosition=1309}},
    Indexed{index=122, entry=ZeebeEntry{term=2, timestamp=1594460616046, lowestPosition=1310, highestPosition=1320}},
    Indexed{index=123, entry=ZeebeEntry{term=2, timestamp=1594460616046, lowestPosition=1321, highestPosition=1331}},
    Indexed{index=124, entry=ZeebeEntry{term=2, timestamp=1594460616049, lowestPosition=1332, highestPosition=1342}},
    Indexed{index=125, entry=ZeebeEntry{term=2, timestamp=1594460616049, lowestPosition=1343, highestPosition=1353}},
    Indexed{index=126, entry=ZeebeEntry{term=2, timestamp=1594460616049, lowestPosition=1354, highestPosition=1364}},
    Indexed{index=127, entry=ZeebeEntry{term=2, timestamp=1594460616050, lowestPosition=1365, highestPosition=1375}},
    Indexed{index=128, entry=ZeebeEntry{term=2, timestamp=1594460616053, lowestPosition=1376, highestPosition=1386}},
    Indexed{index=129, entry=ZeebeEntry{term=2, timestamp=1594460616053, lowestPosition=1387, highestPosition=1397}},
    Indexed{index=130, entry=ZeebeEntry{term=2, timestamp=1594460616056, lowestPosition=1398, highestPosition=1408}},
    Indexed{index=131, entry=ZeebeEntry{term=2, timestamp=1594460616056, lowestPosition=1409, highestPosition=1419}},
    Indexed{index=132, entry=ZeebeEntry{term=2, timestamp=1594460616060, lowestPosition=1420, highestPosition=1430}},
    Indexed{index=133, entry=ZeebeEntry{term=2, timestamp=1594460616060, lowestPosition=1431, highestPosition=1441}},
    Indexed{index=134, entry=ZeebeEntry{term=2, timestamp=1594460616060, lowestPosition=1442, highestPosition=1452}},
    Indexed{index=135, entry=ZeebeEntry{term=2, timestamp=1594460616066, lowestPosition=1453, highestPosition=1463}},
    Indexed{index=136, entry=ZeebeEntry{term=2, timestamp=1594460616067, lowestPosition=1464, highestPosition=1474}},
    Indexed{index=137, entry=ZeebeEntry{term=2, timestamp=1594460616068, lowestPosition=1475, highestPosition=1485}},
    Indexed{index=138, entry=ZeebeEntry{term=2, timestamp=1594460616077, lowestPosition=1486, highestPosition=1496}},
    Indexed{index=139, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1497, highestPosition=1507}},
    Indexed{index=140, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1508, highestPosition=1518}},
    Indexed{index=141, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1519, highestPosition=1529}},
    Indexed{index=142, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1530, highestPosition=1540}},
    Indexed{index=143, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1541, highestPosition=1551}},
    Indexed{index=144, entry=ZeebeEntry{term=2, timestamp=1594460616090, lowestPosition=1552, highestPosition=1562}},
    Indexed{index=145, entry=ZeebeEntry{term=2, timestamp=1594460616090, lowestPosition=1563, highestPosition=1573}},
    Indexed{index=146, entry=ZeebeEntry{term=2, timestamp=1594460616090, lowestPosition=1574, highestPosition=1584}},
    Indexed{index=147, entry=ZeebeEntry{term=2, timestamp=1594460616090, lowestPosition=1585, highestPosition=1595}},
    Indexed{index=148, entry=ZeebeEntry{term=2, timestamp=1594460616094, lowestPosition=1596, highestPosition=1606}},
    Indexed{index=149, entry=ZeebeEntry{term=2, timestamp=1594460616094, lowestPosition=1607, highestPosition=1617}},
    Indexed{index=150, entry=ZeebeEntry{term=2, timestamp=1594460616094, lowestPosition=1618, highestPosition=1628}},
    Indexed{index=151, entry=ZeebeEntry{term=2, timestamp=1594460616094, lowestPosition=1629, highestPosition=1639}},
    Indexed{index=152, entry=ZeebeEntry{term=2, timestamp=1594460616111, lowestPosition=1640, highestPosition=1650}}]>
to end with:
 <[Indexed{index=66, entry=ZeebeEntry{term=1, timestamp=1594460614640, lowestPosition=705, highestPosition=715}},
    Indexed{index=67, entry=ZeebeEntry{term=1, timestamp=1594460614644, lowestPosition=716, highestPosition=726}},
    Indexed{index=68, entry=ZeebeEntry{term=1, timestamp=1594460614644, lowestPosition=727, highestPosition=737}},
    Indexed{index=69, entry=ZeebeEntry{term=1, timestamp=1594460614644, lowestPosition=738, highestPosition=748}},
    Indexed{index=70, entry=ZeebeEntry{term=1, timestamp=1594460614644, lowestPosition=749, highestPosition=759}},
    Indexed{index=71, entry=ZeebeEntry{term=1, timestamp=1594460614646, lowestPosition=760, highestPosition=770}},
    Indexed{index=72, entry=ZeebeEntry{term=1, timestamp=1594460614646, lowestPosition=771, highestPosition=781}},
    Indexed{index=73, entry=ZeebeEntry{term=1, timestamp=1594460614646, lowestPosition=782, highestPosition=792}},
    Indexed{index=74, entry=ZeebeEntry{term=1, timestamp=1594460614646, lowestPosition=793, highestPosition=803}},
    Indexed{index=75, entry=ZeebeEntry{term=1, timestamp=1594460614650, lowestPosition=804, highestPosition=814}},
    Indexed{index=76, entry=ZeebeEntry{term=1, timestamp=1594460614650, lowestPosition=815, highestPosition=825}},
    Indexed{index=77, entry=ZeebeEntry{term=1, timestamp=1594460614650, lowestPosition=826, highestPosition=836}},
    Indexed{index=78, entry=ZeebeEntry{term=1, timestamp=1594460614650, lowestPosition=837, highestPosition=847}},
    Indexed{index=79, entry=ZeebeEntry{term=1, timestamp=1594460614671, lowestPosition=848, highestPosition=858}},
    Indexed{index=80, entry=ZeebeEntry{term=1, timestamp=1594460614671, lowestPosition=859, highestPosition=869}},
    Indexed{index=81, entry=ZeebeEntry{term=1, timestamp=1594460614671, lowestPosition=870, highestPosition=880}},
    Indexed{index=82, entry=ZeebeEntry{term=1, timestamp=1594460614673, lowestPosition=881, highestPosition=891}},
    Indexed{index=83, entry=ZeebeEntry{term=1, timestamp=1594460614677, lowestPosition=892, highestPosition=902}},
    Indexed{index=84, entry=ZeebeEntry{term=1, timestamp=1594460614682, lowestPosition=903, highestPosition=913}},
    Indexed{index=85, entry=ZeebeEntry{term=1, timestamp=1594460614684, lowestPosition=914, highestPosition=924}},
    Indexed{index=86, entry=ZeebeEntry{term=1, timestamp=1594460614685, lowestPosition=925, highestPosition=935}},
    Indexed{index=87, entry=ZeebeEntry{term=1, timestamp=1594460614689, lowestPosition=936, highestPosition=946}},
    Indexed{index=88, entry=ZeebeEntry{term=1, timestamp=1594460614689, lowestPosition=947, highestPosition=957}},
    Indexed{index=89, entry=ZeebeEntry{term=1, timestamp=1594460614689, lowestPosition=958, highestPosition=968}},
    Indexed{index=90, entry=ZeebeEntry{term=1, timestamp=1594460614689, lowestPosition=969, highestPosition=979}},
    Indexed{index=91, entry=ZeebeEntry{term=1, timestamp=1594460614693, lowestPosition=980, highestPosition=990}},
    Indexed{index=92, entry=ZeebeEntry{term=1, timestamp=1594460614693, lowestPosition=991, highestPosition=1001}},
    Indexed{index=93, entry=ZeebeEntry{term=1, timestamp=1594460614693, lowestPosition=1002, highestPosition=1012}},
    Indexed{index=94, entry=ZeebeEntry{term=1, timestamp=1594460614693, lowestPosition=1013, highestPosition=1023}},
    Indexed{index=95, entry=ZeebeEntry{term=1, timestamp=1594460614697, lowestPosition=1024, highestPosition=1034}},
    Indexed{index=96, entry=ZeebeEntry{term=1, timestamp=1594460614697, lowestPosition=1035, highestPosition=1045}},
    Indexed{index=97, entry=ZeebeEntry{term=1, timestamp=1594460614697, lowestPosition=1046, highestPosition=1056}},
    Indexed{index=98, entry=ZeebeEntry{term=1, timestamp=1594460614697, lowestPosition=1057, highestPosition=1067}},
    Indexed{index=99, entry=ZeebeEntry{term=1, timestamp=1594460614700, lowestPosition=1068, highestPosition=1078}},
    Indexed{index=100, entry=ZeebeEntry{term=1, timestamp=1594460614700, lowestPosition=1079, highestPosition=1089}},
    Indexed{index=101, entry=ZeebeEntry{term=1, timestamp=1594460614700, lowestPosition=1090, highestPosition=1100}},
    Indexed{index=102, entry=InitializeEntry{term=2, timestamp=2020-07-11 09:43:35,666}},
    Indexed{index=103, entry=ZeebeEntry{term=2, timestamp=1594460616007, lowestPosition=1101, highestPosition=1111}},
    Indexed{index=104, entry=ZeebeEntry{term=2, timestamp=1594460616029, lowestPosition=1112, highestPosition=1122}},
    Indexed{index=105, entry=ZeebeEntry{term=2, timestamp=1594460616030, lowestPosition=1123, highestPosition=1133}},
    Indexed{index=106, entry=ZeebeEntry{term=2, timestamp=1594460616030, lowestPosition=1134, highestPosition=1144}},
    Indexed{index=107, entry=ZeebeEntry{term=2, timestamp=1594460616030, lowestPosition=1145, highestPosition=1155}},
    Indexed{index=108, entry=ZeebeEntry{term=2, timestamp=1594460616034, lowestPosition=1156, highestPosition=1166}},
    Indexed{index=109, entry=ZeebeEntry{term=2, timestamp=1594460616034, lowestPosition=1167, highestPosition=1177}},
    Indexed{index=110, entry=ZeebeEntry{term=2, timestamp=1594460616034, lowestPosition=1178, highestPosition=1188}},
    Indexed{index=111, entry=ZeebeEntry{term=2, timestamp=1594460616035, lowestPosition=1189, highestPosition=1199}},
    Indexed{index=112, entry=ZeebeEntry{term=2, timestamp=1594460616038, lowestPosition=1200, highestPosition=1210}},
    Indexed{index=113, entry=ZeebeEntry{term=2, timestamp=1594460616038, lowestPosition=1211, highestPosition=1221}},
    Indexed{index=114, entry=ZeebeEntry{term=2, timestamp=1594460616038, lowestPosition=1222, highestPosition=1232}},
    Indexed{index=115, entry=ZeebeEntry{term=2, timestamp=1594460616038, lowestPosition=1233, highestPosition=1243}},
    Indexed{index=116, entry=ZeebeEntry{term=2, timestamp=1594460616042, lowestPosition=1244, highestPosition=1254}},
    Indexed{index=117, entry=ZeebeEntry{term=2, timestamp=1594460616042, lowestPosition=1255, highestPosition=1265}},
    Indexed{index=118, entry=ZeebeEntry{term=2, timestamp=1594460616042, lowestPosition=1266, highestPosition=1276}},
    Indexed{index=119, entry=ZeebeEntry{term=2, timestamp=1594460616042, lowestPosition=1277, highestPosition=1287}},
    Indexed{index=120, entry=ZeebeEntry{term=2, timestamp=1594460616045, lowestPosition=1288, highestPosition=1298}},
    Indexed{index=121, entry=ZeebeEntry{term=2, timestamp=1594460616046, lowestPosition=1299, highestPosition=1309}},
    Indexed{index=122, entry=ZeebeEntry{term=2, timestamp=1594460616046, lowestPosition=1310, highestPosition=1320}},
    Indexed{index=123, entry=ZeebeEntry{term=2, timestamp=1594460616046, lowestPosition=1321, highestPosition=1331}},
    Indexed{index=124, entry=ZeebeEntry{term=2, timestamp=1594460616049, lowestPosition=1332, highestPosition=1342}},
    Indexed{index=125, entry=ZeebeEntry{term=2, timestamp=1594460616049, lowestPosition=1343, highestPosition=1353}},
    Indexed{index=126, entry=ZeebeEntry{term=2, timestamp=1594460616049, lowestPosition=1354, highestPosition=1364}},
    Indexed{index=127, entry=ZeebeEntry{term=2, timestamp=1594460616050, lowestPosition=1365, highestPosition=1375}},
    Indexed{index=128, entry=ZeebeEntry{term=2, timestamp=1594460616053, lowestPosition=1376, highestPosition=1386}},
    Indexed{index=129, entry=ZeebeEntry{term=2, timestamp=1594460616053, lowestPosition=1387, highestPosition=1397}},
    Indexed{index=130, entry=ZeebeEntry{term=2, timestamp=1594460616056, lowestPosition=1398, highestPosition=1408}},
    Indexed{index=131, entry=ZeebeEntry{term=2, timestamp=1594460616056, lowestPosition=1409, highestPosition=1419}},
    Indexed{index=132, entry=ZeebeEntry{term=2, timestamp=1594460616060, lowestPosition=1420, highestPosition=1430}},
    Indexed{index=133, entry=ZeebeEntry{term=2, timestamp=1594460616060, lowestPosition=1431, highestPosition=1441}},
    Indexed{index=134, entry=ZeebeEntry{term=2, timestamp=1594460616060, lowestPosition=1442, highestPosition=1452}},
    Indexed{index=135, entry=ZeebeEntry{term=2, timestamp=1594460616066, lowestPosition=1453, highestPosition=1463}},
    Indexed{index=136, entry=ZeebeEntry{term=2, timestamp=1594460616067, lowestPosition=1464, highestPosition=1474}},
    Indexed{index=137, entry=ZeebeEntry{term=2, timestamp=1594460616068, lowestPosition=1475, highestPosition=1485}},
    Indexed{index=138, entry=ZeebeEntry{term=2, timestamp=1594460616077, lowestPosition=1486, highestPosition=1496}},
    Indexed{index=139, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1497, highestPosition=1507}},
    Indexed{index=140, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1508, highestPosition=1518}},
    Indexed{index=141, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1519, highestPosition=1529}},
    Indexed{index=142, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1530, highestPosition=1540}},
    Indexed{index=143, entry=ZeebeEntry{term=2, timestamp=1594460616082, lowestPosition=1541, highestPosition=1551}},
    Indexed{index=144, entry=ZeebeEntry{term=2, timestamp=1594460616090, lowestPosition=1552, highestPosition=1562}},
    Indexed{index=145, entry=ZeebeEntry{term=2, timestamp=1594460616090, lowestPosition=1563, highestPosition=1573}},
    Indexed{index=146, entry=ZeebeEntry{term=2, timestamp=1594460616090, lowestPosition=1574, highestPosition=1584}},
    Indexed{index=147, entry=ZeebeEntry{term=2, timestamp=1594460616090, lowestPosition=1585, highestPosition=1595}},
    Indexed{index=148, entry=ZeebeEntry{term=2, timestamp=1594460616094, lowestPosition=1596, highestPosition=1606}}]>

	at io.atomix.raft.RaftFailOverTest.shouldTruncateLogOnNewerSnapshotEvenAfterRestart(RaftFailOverTest.java:401)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
</pre>
</details>

**Hypotheses**

**Logs**

> 200 MB https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/develop/1533/artifact/test-reports.zip

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Backport #4995 

## Related issues

closes #4954
closes #4662

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
bors r+

**Comment by deepthidevaki** [comment]
bors retry

**Comment by deepthidevaki** [comment]
bors retry

**Comment by Zelldon** [comment]
Bors r+

**Comment by Zelldon** [comment]
Bors r+

**Comment by Zelldon** [comment]
Bors r+

**Comment by deepthidevaki** [comment]
bors retry

**Pull request merged**
