### PR TITLE
fix: limit validation result output to a certain size and print the number of remaining errors

### LINKED ISSUE #19595: Update zeebe to use the newer version of `camunda-bpm-platform` supporting writing with a `maxSize` limit

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description

Limit validation result output to a certain size and print the number of remaining errors

- updating `camunda-bpm-platform` version to `7.22.0-alpha3` since it has our new api allowing a size limit
- extended the formatter to implement methods to format a suffix with the number of non-printed results
- aggregating the design-time and the run-time results, so it's easier to set the limit once for all and print the correct remaining items
- made max size configurable to allow different values for different cluster configs

## Related issues

closes #19595
related to #11284
related to https://github.com/camunda/camunda-bpm-platform/issues/4443

### CODE REVIEW

**Review by remcowesterhoud — COMMENTED** [review]
Thanks @mustafadagher!

I may be missing some context, but I was going from this [comment here](https://github.com/camunda/camunda/issues/11284#issuecomment-2175926433).

❓ The comment says:
>allow specifying a max validation results size in bytes by overloading the ValidationResultsCollectorImpl constructor, by default it's not set and unused

But it also mentions:
> We should try to stay pragmatic for defaults
> ...
> - Let's simply take half of this as the max validation results size: 2K.
> - Let's try it out and see what happens when using the example process model to see if that default makes sense
> - If the default makes sense in general, let's postpone making it configurable until users request it

Right now I don't see anything defining this 2k bytes default, as it's set to `Integer.MAX_VALUE`. Realistically this changes nothing unless specifically configured to be lower. What I understand from this comment is that `DEFAULT_VALIDATORS_RESULTS_OUTPUT_MAX_SIZE` should be set to 2k. What do you think?

**Comment by mustafadagher** [comment]
> Thanks @mustafadagher!
> 
> I may be missing some context, but I was going from this [comment here](https://github.com/camunda/camunda/issues/11284#issuecomment-2175926433).
> 
> ❓ The comment says:
> 
> > allow specifying a max validation results size in bytes by overloading the ValidationResultsCollectorImpl constructor, by default it's not set and unused
> 
> But it also mentions:
> 
> > We should try to stay pragmatic for defaults
> > ...
> > 
> > * Let's simply take half of this as the max validation results size: 2K.
> > * Let's try it out and see what happens when using the example process model to see if that default makes sense
> > * If the default makes sense in general, let's postpone making it configurable until users request it
> 
> Right now I don't see anything defining this 2k bytes default, as it's set to `Integer.MAX_VALUE`. Realistically this changes nothing unless specifically configured to be lower. What I understand from this comment is that `DEFAULT_VALIDATORS_RESULTS_OUTPUT_MAX_SIZE` should be set to 2k. What do you think?

Hi @remcowesterhoud ! 
Those are valid questions.

While the conversation on the original ticket doesn't show much context, let me explain some here:

In the meantime while working on this part of the fix, I also took to the infra side trying to increase our header-size limits (PR: https://github.com/camunda-cloud/camunda-operator/pull/3025), now the default is `16kb` not `4kb`.

I didn't want to limit this here by default, and thought to leave it as big as it could until we test the effectiveness of the infra change, and leave limiting it here only as an option when needed.

I also created a follow up ticket as a follow-up, from the findings that came out from testing the infra changes (Issue: https://github.com/camunda/camunda/issues/19829).

I can still change the default here, but I believe that half the header max size would be unfair, because I'd think that validation errors might actually be taking about 80-90% of it in reality.

**Comment by remcowesterhoud** [comment]
Thanks for the extra context!

> I can still change the default here, but I believe that half the header max size would be unfair, because I'd think that validation errors might actually be taking about 80-90% of it in reality.

I would prefer doing this, maybe it doesn't have to be half but we can set it to 12 (~80% of 16kb). My reasoning behind this is that **if** someone still exceeds it, at least they get a helpful error instead of being none the wiser which is what would happen now.

**Comment by mustafadagher** [comment]
> Thanks for the extra context!
> 
> > I can still change the default here, but I believe that half the header max size would be unfair, because I'd think that validation errors might actually be taking about 80-90% of it in reality.
> 
> I would prefer doing this, maybe it doesn't have to be half but we can set it to 12 (~80% of 16kb). My reasoning behind this is that **if** someone still exceeds it, at least they get a helpful error instead of being none the wiser which is what would happen now.

I agree with you, I wanted to do it as well, but now before implementing the changes from https://github.com/camunda/camunda/issues/19829, the java-client throttles that at `8kb`, and I wasn't sure if I should set the default value here considering the other fix will follow, or considering the current limit by the client. So in the end, I left it as is 😄 

I'll update it to something 12, and work on the client change in the meantime.

Thanks!

**Review by remcowesterhoud — APPROVED** [review]
Awesome, LGTM 🚀 Let's see if I still have merge permissions 😄 

bors merge

**Comment by tmetzke** [comment]
> Awesome, LGTM 🚀 Let's see if I still have merge permissions 😄
> 
> bors merge

We replaced bors by GitHub merge queue 🙂

**Pull request merged**
