### PR TITLE
Remove protocol version check from stream platform

### LINKED ISSUE #14204: Remove protocol version check in the broker
### Description

Zeebe is unable to bump the SBE protocol version due to the following problem. During a rolling upgrade:
1. Broker 1 is upgraded and comes back online.
2. Broker 2 is being upgraded
    1. While broker 2 is upgraded, a leader election is triggered
    2. Broker 2's engine starts replaying events
    3. Broker 1 sends event records with a higher protocol version
    4. Broker 2 throws an error that it can't handle these events and crashes

The problem is that we're misusing the SBE protocol version:
* SBE uses the protocol version to be able to handle (serialize/deserialize) new fields from the later protocol version.
   * By not bumping the protocol version when adding new fields, we're making it difficult for SBE to work properly
* The Zeebe stream platform (mis)uses the protocol version to check if it will be able to (semantically) understand what was deserialized.
   * This was done to guard against a change in the content of the SBE fields, not against adding new fields (which SBE will easily handle, by ignoring them on older versions).
   * This was also done to avoid changes causing bugs on older brokers

Currently, Zeebe has a metadata property `recordVersion` which we currently use to differentiate events when they should be applied differently. I.e. an event is something that happened in the past. It describes a state change and should always produce that state change when replayed. Even when its a bug. When we want to fix a bug in an event applier, we need to change the command processor to append events of a new `recordVersion` and add a new event applier version that fixes the bug.

### Solution

The addition of the `recordVersion` mechanism described above makes the stream-platform protocol version check redundant (and as described above as well, error-prone). As a result, it can be removed.

### AC

The protocol version check is removed.

### Additional context
* Problem discussion ([internal Slack thread](https://camunda.slack.com/archives/C05Q0EXE9V4/p1693500298465369))
* Related to #9949

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Remove the protocol version check as it was made redundant with the introduction of versioned EventAppliers and the RecordMetadata#recordVersion property.

## Related issues

closes #14204 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by koevskinikola** [comment]
@npepinpe I've added you as reviewer as you're already familiar with the topic. Feel free to re-assign it to someone else from ZDP if you're overloaded with tasks.

@korthout as the `stream-platform` module is maintained by ZDP, I've added you as an optional reviewer (for awarenes) from the ZPA side.

**Review by korthout — APPROVED** [review]
👍 I'm fine with these changes. Semantic changes to records should be described by appending these records with a higher `recordVersion`.

Please note that when an event should be applied differently, that the newer leader will append the event with a `recordVersion` that the older follower may not have an event applier for. In that case, the same situation as described in [the issue](https://github.com/camunda/zeebe/issues/14204) occurs again, but due to the follower being unable to replay (i.e. apply) the event.

**Review by npepinpe — APPROVED** [review]
:rocket:

**Comment by korthout** [comment]
I think we should backport this to 8.2 so it's easier for fully patched 8.2 clusters to upgrade to 8.3. There's nothing we can do for unpatched clusters.

**Comment by koevskinikola** [comment]
bors merge

**Pull request merged**
