### PR TITLE
chore(project): enforce jdk8 and maven >=3.3

### PR DESCRIPTION
**Pull request by hawky-4s-**
Prevent people from getting failures during compilation using JDKs > 8.

### CODE REVIEW

**Review by menski — CHANGES_REQUESTED** [review]
This change is not preventing me from running the build with java 11.

```
mvn enforcer:display-info
[INFO] --- maven-enforcer-plugin:1.2:display-info (default-cli) @ zeebe-root ---
[INFO] Maven Version: 3.6.0
[INFO] JDK Version: 11.0.1 normalized as: 11.0.1
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 4.19.4-arch1-1-arch
```

**Comment by hawky-4s-** [comment]
That happens when you just test it with older JDK cos you don't have >8 installed 💃 
Fixed it and tested it locally using
```
docker run -it --rm -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3-jdk-8-slim mvn clean compile
=> works
docker run -it --rm -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3-jdk-9-slim mvn clean compile
=> does not work
docker run -it --rm -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3-jdk-11-slim mvn clean compile
=> does not work
```

**Review by menski — APPROVED** [review]

**Comment by menski** [comment]
Works like a charm, thanks :cookie: 

bors r+

**Comment by menski** [comment]
bors retry

**Pull request merged**
