### PR TITLE
Try compacting on out of disk space on leader append

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR modifies the leader append pipeline to attempt compacting if currently out of disk space, before retrying. It will only retry if there was anything compacted.

Note that this is a best of effort attempt, as compacting may report that something was deleted even if it was only soft deleted and no new space was made available (e.g. there's a reader still pointing to the compacted segment).

> **Note** The follower was already doing this previously, though it would compact then fail the append instead of retrying synchronously.

## Related issues

follow up of #11521

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — CHANGES_REQUESTED** [review]
Thanks @npepinpe, this was great to review :+1: 

I don't think that this works though. Just calling `compact()` again doesn't help the leader because the compaction bound is still based on snapshot index - the `preferSnapshotReplicationThreshold` offset. [My idea](https://github.com/camunda/zeebe/pull/11521#discussion_r1094248238) was to compact without offset when an OOD occurs.

**Comment by npepinpe** [comment]
Can you elaborate? We need to pass an offset, otherwise we'd be compacting data we still need. And as far as I can tell, this is a remnant from when the Raft context used to also take the snapshot based on processing, so at that time it made no sense to try compacting if we couldn't append new data.

Since we snapshot asynchronously, this doesn't seem too crazy for me, as the compactable index may change. Though we could check it as well.

But maybe you can explain what you meant without offset.

**Comment by oleschoenburg** [comment]
> Since we snapshot asynchronously, this doesn't seem too crazy for me, as the compactable index may change

Oh yeah, in that light the PR does make sense anyway :+1: 

> But maybe you can explain what you meant without offset.

Compaction is always done based on the latest compactable index. With offset log compaction, this now subtracts the `preferSnapshotReplicationThreshold`:
https://github.com/camunda/zeebe/blob/0f51bb95428bfe61fbb7b7d3d794386f0b0d5eb6/atomix/cluster/src/main/java/io/atomix/raft/partition/impl/RaftPartitionServer.java#L200-L205

I thought that compacting **without** offset when an OOD occurs would be beneficial. But that'd require some additional refactoring. For example, the offset could be managed by `LogCompactor` directly which then offers two `compact` variants, one respecting the offset and one ignoring it.

**Review by lenaschoenburg — APPROVED** [review]

**Comment by npepinpe** [comment]
Oh, I wasn't aware of that. I knew we had some threshold involved, but I missed that the compactable offset is already considering the threshold. I thought it was just for replication.

OK, now I get your comment. I would like to have that, hopefully it's a low hanging fruit. Let me try quickly.

**Comment by npepinpe** [comment]
Last commit contains changes to allow compacting ignoring the threshold. It pushes the management of the compacting logic (incl. threshold) down to the compactor.

**Comment by npepinpe** [comment]
Failing checks are due to Testcontainers timeout. I'll restart those jobs once the others are finished.

**Review by lenaschoenburg — APPROVED** [review]
Cool, thanks again @npepinpe :+1:

**Comment by npepinpe** [comment]
Actually, this last commit broke a bunch of stuff :smile:

**Comment by npepinpe** [comment]
So we have two options here: one is we disable the threshold for `RaftFailoverTest`, since there we always want to force compaction/replication. The other is when someone calls `RaftRule#compact`, we assume it's forced, and we bypass it. I don't like the idea of bypassing it though, imo, so I would simply disable it for this specific test.

When the test fails, the logs contain a clear message of what was compacted (or not), so I think that's OK for future tests as well.

**Comment by npepinpe** [comment]
The last two commits were added to allow bypassing the threshold in tests. The assumption is that if you call compact in the RaftRule, you typically want to bypass the replication threshold and enforce compaction if possible.

One commit adds a new utility to `ThreadContext` where you can submit a task and get a `CompletableFuture` back. This is a pattern we were using a lot, so I figured we'd just simplify it. I didn't replace all of the instances though, just some - we can do that as we go along.

**Comment by npepinpe** [comment]
@oleschoenburg ping! Or let me know if I should just merge. I figured the last two commits were a little bit too large to just merge after the review :sweat_smile:

**Review by lenaschoenburg — APPROVED** [review]
Oops, missed this on friday :+1:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
Ugh, merge conflicts.

**Pull request merged**
