### PR TITLE
Use v8 major version in Go module name

### PR DESCRIPTION
**Pull request by korthout**
## Description

Go enforces a rather strange and stupid naming convention for major version releases. It requires the module name to contain the major version (if it isn't v0 or v1). Since we just moved to v8, we need to make it part of the module name.

This PR changes the module name, updates the internal imports, and updates the build and test scripts, accordingly.

See https://donatstudios.com/Go-v2-Modules for more info.

## Related issues

closes NA

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Comment by korthout** [comment]
This PR should be forward ported to the default branch, so it is labeled as `backport main`.

**Comment by korthout** [comment]
By merging this into the `release-8.0.0`, we don't have to forward port this PR. Specifically, because #9051 still needs to be merged.

**Comment by korthout** [comment]
@npepinpe As you're also the reviewer for #9051, please also have a look at this.

**Review by npepinpe — APPROVED** [review]
:+1: 

Tested with the Go chaos worker, only had to update the import paths. Annoying, but I guess there's no way around it. So for the Go client, this is effectively (due to how Go is) a breaking release :disappointed:

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
