### PR TITLE
ci: remove jvm args for smoke tests

### LINKED ISSUE #12469: Smoke tests fail due to full code cache
Happened twice now:
- https://github.com/camunda/zeebe/actions/runs/4731056097/jobs/8395540393
- https://github.com/camunda/zeebe/actions/runs/4730193543/jobs/8393592546

For smoke tests we set additional JVM options:
https://github.com/camunda/zeebe/blob/c51d6ab7a0f4d2e6250602f90f8b76e4c59baa2a/.github/workflows/ci.yml#L172

We should re-evaluate those. I suspect that we can simply remove them.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Removes custom JVM args that were only set for smoke tests. These seem to be no longer necessary.

closes #12469

### CODE REVIEW

**Comment by oleschoenburg** [comment]
Test runs:
- https://github.com/camunda/zeebe/actions/runs/4731429980
- https://github.com/camunda/zeebe/actions/runs/4731509277
- https://github.com/camunda/zeebe/actions/runs/4731509554
- https://github.com/camunda/zeebe/actions/runs/4731509702
- https://github.com/camunda/zeebe/actions/runs/4731509905
- https://github.com/camunda/zeebe/actions/runs/4731510087

**Review by npepinpe — APPROVED** [review]
:question: Do we know that this fixes the issue? Locally my ReservedCodeCacheSize is 240MB, so if that's the same in the cloud then :+1: Did we verify that?

The tiered compilation stuff was just disabling some compilation optimizations since they're smoke tests, but it probably doesn't change much in terms of runtime which will be dominated by downloading dependencies :smile:

**Comment by npepinpe** [comment]
BTW we should probably backport this :+1:

**Comment by oleschoenburg** [comment]
> Do we know that this fixes the issue?

Not exactly but I couldn't reproduce the issue in 10 runs so I'm optimistic :sweat_smile: 
Also I think it makes sense in general to not set too many flags in some places and not in others, that just makes things more difficult.

**Pull request merged**
