### PR TITLE
Add workflow key to incident record

### LINKED ISSUE #2437: Add workflow key to incident record
To group incidents by workflow it would be helpful to include the workflow key in the incident record.

### PR DESCRIPTION
**Pull request by menski**
closes #2437

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

One comment mentioned that the workflow key can be null of an incident does not belong to a workflow; is that an actual case?

**Comment by menski** [comment]
@npepinpe it is mentioned in all the javadocs of the attributes, I asked myself the same but am not aware how an incident would be not related to a workflow instance. I assume this is a left over from the standalone jobs times, where jobs could be created without a workflow instance. @saig0 any comment on that?

**Comment by saig0** [comment]
I agree. I think it is just a left over :see_no_evil:

**Comment by menski** [comment]
I created a follow-up issue https://github.com/zeebe-io/zeebe/issues/2442

**Pull request merged**
