### PR TITLE
feat(docker-compose) Added docker compose cluster and small reorganiz…

### PR DESCRIPTION
**Pull request by jsam**
* Added docker compose cluster
* Reorganized all docker stuff into docker folder

### CODE REVIEW

**Review by menski — CHANGES_REQUESTED** [review]
- the `docker-utils` files where moved but the path in the `Dockerfile` was not updated
- I would not move the `Dockerfile` into a sub folder because that prevents to build the docker image with the tar.gz under `dist/target`
```
$ docker build -t camunda/zeebe:latest --build-arg DISTBALL=../dist/target/zeebe-distribution-0.2.0-SNAPSHOT.tar.gz .                                                                                                                                                            
Sending build context to Docker daemon  2.048kB                                                                                                                                                                                                                                 
Step 1/11 : FROM openjdk:8                                                                                                                                                                                                                                                      
 ---> 4551430cfe80
Step 2/11 : ARG DISTBALL
 ---> Using cache
 ---> 9bb1c511df61
Step 3/11 : ENV ZB_HOME /usr/local/zeebe/ DEBUG false DEPLOY_ON_KUBERNETES false
 ---> Using cache
 ---> 77fa4ab7d2d3
Step 4/11 : COPY ${DISTBALL} ${ZB_HOME}
COPY failed: Forbidden path outside the build context: ../dist/target/zeebe-distribution-0.2.0-SNAPSHOT.tar.gz ()
```

**Comment by menski** [comment]
Okay the build would work if we use the `-f` option to specify the Dockerfile location and build from root. So I will only adjust the docker-utils path and merge this. Thanks

```
docker build -t camunda/zeebe:latest --build-arg DISTBALL=dist/target/zeebe-distribution-0.2.0-SNAPSHOT.tar.gz -f docker/Dockerfile . 
```

**Comment by menski** [comment]
I moved the `Dockerfile` to root, otherwise the `COPY` would depend from where the docker build is started.

**Comment by jsam** [comment]
thanks :rocket:

**Comment by menski** [comment]
thank you for your contribution :lollipop:

**Pull request merged**
