### PR TITLE
Log node member ID via the scheduler name as part of actor logging context

### LINKED ISSUE #13281: Define actor names for new remote stream actors
**Description**

We added many actors with the new job push feature, but forgot to name them properly. Having properly named actors (with the node ID and behavior) helps a lot when debugging to understand who is doing what.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR removes the need to pass around the node ID to all actor names, and instead leverages the fact that the scheduler name already contains it. The scheduler's name is now part of the actor's logging context, and displayed in either the logging pattern, or as its own field in the JSON logging context.

Additionally, the node ID is removed everywhere from the actor names, as it's now redundant.

This closes the job push relevant issue, as it now has all the information it needed.

Logs now look like this when using the normal console appender:

```
19:24:49.843 [Broker-0] [zb-actors-1] [ZeebePartition-2] INFO  io.camunda.zeebe.broker.system - Shutdown RocksDB metric timer
19:24:49.844 [Broker-0] [zb-actors-1] [ZeebePartition-2] INFO  io.camunda.zeebe.broker.system - Shutdown LogDeletionService
19:24:49.885 [Broker-0] [zb-fs-workers-0] [SnapshotStore-2] DEBUG io.camunda.zeebe.logstreams.snapshot - Closed database from '/home/nicolas/tmp/data/raft-partition/partitions/2/runtime'.
19:24:49.888 [Broker-0] [zb-fs-workers-1] [SnapshotStore-1] DEBUG io.camunda.zeebe.logstreams.snapshot - Closed database from '/home/nicolas/tmp/data/raft-partition/partitions/1/runtime'.
19:24:49.910 [] [raft-server-0-raft-partition-partition-2] [] DEBUG io.camunda.zeebe.journal.file.SegmentsManager - Closing segment: Segment{id=12, index=820387}
19:24:49.910 [] [raft-server-0-raft-partition-partition-1] [] DEBUG io.camunda.zeebe.journal.file.SegmentsManager - Closing segment: Segment{id=12, index=822412}
19:24:49.921 [Broker-0] [zb-actors-1] [Startup] INFO  io.camunda.zeebe.broker.system - Shutdown Embedded Gateway
```

Otherwise, it's simply a field called `actor-scheduler` under the JSON context.

## Related issues

closes #13281 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
I'm on the fence about backporting this. It's not required, but it would be nice to have uniform logging no matter the version. Let me know what you think :+1:

**Review by deepthidevaki — APPROVED** [review]
:rocket: Thanks.

I think it makes sense backport this.

**Comment by npepinpe** [comment]
Let's try it - if it's too much manual effort to backport we can omit it for a specific version :sweat_smile:

**Comment by npepinpe** [comment]
8.0 has diverged quite a lot - we refactored the inter partition command sender, how we inject the scheduler into the standalone artifacts, and others. Since it's being phased out in September, I would skip this backport, so we'll only have the old logging schema there for one month.

**Pull request merged**
