### PR TITLE
Rename broker-core module

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Rename broker-core module to broker so we are also consistent to our git commit messages and Changelog, where we only use broker. 

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by Zelldon** [comment]
@npepinpe gate failed ? :sweat_smile:

**Comment by npepinpe** [comment]
I assume it's because now the whole thing is "new code" :sweat_smile:

**Review by miguelpires — CHANGES_REQUESTED** [review]
My only issue is that the git history of every file in broker is lost. I tried to `git mv` all of broker-core and as far as I can tell it works. Is there any reason why we can't do that?

**Comment by Zelldon** [comment]
> My only issue is that the git history of every file in broker is lost. I tried to git mv all of broker-core and as far as I can tell it works. Is there any reason why we can't do that?

This was not intended. I thought git will do this automatically. thanks @MiguelPires will fix this

**Comment by Zelldon** [comment]
OK I tested in the morning with `git mv` and it didn't work. 
The reason is that git will not keep track of the history.
https://stackoverflow.com/questions/2314652/is-it-possible-to-move-rename-files-in-git-and-maintain-their-history

How exactly you moved the files? That you kept the history ? :sweat_smile: 

**Btw:** There is no difference with `mv` and adding it manually.
https://stackoverflow.com/questions/1094269/whats-the-purpose-of-git-mv

**Comment by MiguelPires** [comment]
You're right, we can see the history with `git log --follow`, it just doesn't show up on Github. My bad then, I guess that's fine

**Review by miguelpires — APPROVED** [review]

**Pull request merged**
