### PR TITLE
Remove Operate post-importer

### LINKED ISSUE #24297: Migrate post-importer to archiver
# Description

The goal is to migrate the existing post-importer as a new background task to be executed inside the exporter, e.g. alongside the archiver jobs.

The post importer task should reschedule itself like the archiver jobs. For the first iteration, we can keep the hard coded delay between runs (3s), instead of making it configurable (like with the archiver task), as this is the current state of the post-importer.

To do this, we will refactor the existing archiver such that it becomes a `BackgroundTaskManager`, and the `ReschedulingTask` to accept more generic tasks. Every background task will now return as result how much work items they did, and pass to the rescheduling task what is the minimum expected amount of work to know whether or not to increase the backoff delay. For the post importer, we will keep this as 1, so we keep the same behavior as before.

```[tasklist]
### First iteration
- [ ] https://github.com/camunda/camunda/pull/24921
- [ ] https://github.com/camunda/camunda/pull/24922
- [ ] https://github.com/camunda/camunda/issues/24929
- [ ] https://github.com/camunda/camunda/pull/25067
- [ ] https://github.com/camunda/camunda/issues/24930
- [ ] https://github.com/camunda/camunda/issues/24931
- [ ] https://github.com/camunda/camunda/issues/24990
```

### LINKED ISSUE #24990: Remove the old post-importer code
# Description
Once we have the first iteration of the migrated post-importer, we can then remove the code for the old post importer.

Enjoy this nice gift :)

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR removes the Operate post importer code, which is now superseded by the `IncidentUpdateTask` of the new exporter.

It removes:

- Post importer configuration
- The post importer itself
- Post importer related test code

## Related issues

closes #24990 
closes #24297

### CODE REVIEW

**Comment by npepinpe** [comment]
There will be one failing test which relies on the post importer: `IncidentZeebeImportIT`. I think we could remove it, but it may be testing more incident behavior we would like to keep. I'll check with Svetlana - but my gut feeling is we want to remove it.

**Comment by ChrisKujawa** [comment]
@npepinpe can we get this merged?

**Comment by npepinpe** [comment]
It was blocked by the E2E tests, so :crossed_fingers:

**Comment by ChrisKujawa** [comment]
Looks like different errors than on main ? Do we know the issue?

**Comment by npepinpe** [comment]
Alright, so failing on main:

```
     [chromium] › tests/childProcessInstanceMigration.spec.ts:47:7 › Child Process Instance Migration @roundtrip › Migrate Child Process Instances 
    [chromium] › tests/operations.spec.ts:96:7 › Operations › Retry and Cancel single instance @roundtrip 
    [chromium] › tests/operations.spec.ts:177:7 › Operations › Retry and cancel multiple instances @roundtrip 
    [chromium] › tests/processInstanceMigration.spec.ts:157:7 › Process Instance Migration › Auto Mapping @roundtrip 
    [chromium] › tests/processInstancesFilters.spec.ts:157:7 › Process Instances Filters › variable filters 
```

Failing in this PR:

```
     [chromium] › tests/batchMoveModification.spec.ts:45:7 › Process Instance Batch Modification › Move Operation @roundtrip 
    [chromium] › tests/childProcessInstanceMigration.spec.ts:47:7 › Child Process Instance Migration @roundtrip › Migrate Child Process Instances 
    [chromium] › tests/dashboard.spec.ts:78:7 › Dashboard › Statistics ─────────────────────────────
    [chromium] › tests/operations.spec.ts:96:7 › Operations › Retry and Cancel single instance @roundtrip 
    [chromium] › tests/operations.spec.ts:177:7 › Operations › Retry and cancel multiple instances @roundtrip 
    [chromium] › tests/processes.spec.ts:100:7 › Processes › Processes Page Initial Load ───────────
    [chromium] › tests/processInstance.spec.ts:103:7 › Process Instance › Resolve an incident @roundtrip 
    [chromium] › tests/processInstanceMigration.spec.ts:157:7 › Process Instance Migration › Auto Mapping @roundtrip 
```

So the ones failing _only_ in this PR:

```
     [chromium] › tests/batchMoveModification.spec.ts:45:7 › Process Instance Batch Modification › Move Operation @roundtrip 
    [chromium] › tests/dashboard.spec.ts:78:7 › Dashboard › Statistics ─────────────────────────────
    [chromium] › tests/processes.spec.ts:100:7 › Processes › Processes Page Initial Load ───────────
    [chromium] › tests/processInstance.spec.ts:103:7 › Process Instance › Resolve an incident @roundtrip 
```

Surprisingly, there's on main that's not failing here :shrug:

**Comment by npepinpe** [comment]
In a completely [separate PR](https://github.com/camunda/camunda/actions/runs/12300544244/job/34329039737), I see the following failing:

```
    [chromium] › tests/batchMoveModification.spec.ts:45:7 › Process Instance Batch Modification › Move Operation @roundtrip 
    [chromium] › tests/childProcessInstanceMigration.spec.ts:47:7 › Child Process Instance Migration @roundtrip › Migrate Child Process Instances 
    [chromium] › tests/operations.spec.ts:96:7 › Operations › Retry and Cancel single instance @roundtrip 
    [chromium] › tests/operations.spec.ts:177:7 › Operations › Retry and cancel multiple instances @roundtrip 
    [chromium] › tests/processInstanceMigration.spec.ts:157:7 › Process Instance Migration › Auto Mapping @roundtrip 
```

So I think I can safely ignore `[chromium] › tests/batchMoveModification.spec.ts:45:7 › Process Instance Batch Modification › Move Operation @roundtrip `

And focus on the 3:

```
    [chromium] › tests/dashboard.spec.ts:78:7 › Dashboard › Statistics ─────────────────────────────
    [chromium] › tests/processes.spec.ts:100:7 › Processes › Processes Page Initial Load ───────────
    [chromium] › tests/processInstance.spec.ts:103:7 › Process Instance › Resolve an incident @roundtrip 
```

**Comment by ChrisKujawa** [comment]
> In a completely [separate PR](https://github.com/camunda/camunda/actions/runs/12300544244/job/34329039737), I see the following failing:
> 
> ```
>     [chromium] › tests/batchMoveModification.spec.ts:45:7 › Process Instance Batch Modification › Move Operation @roundtrip 
>     [chromium] › tests/childProcessInstanceMigration.spec.ts:47:7 › Child Process Instance Migration @roundtrip › Migrate Child Process Instances 
>     [chromium] › tests/operations.spec.ts:96:7 › Operations › Retry and Cancel single instance @roundtrip 
>     [chromium] › tests/operations.spec.ts:177:7 › Operations › Retry and cancel multiple instances @roundtrip 
>     [chromium] › tests/processInstanceMigration.spec.ts:157:7 › Process Instance Migration › Auto Mapping @roundtrip 
> ```
> 
> So I think I can safely ignore `[chromium] › tests/batchMoveModification.spec.ts:45:7 › Process Instance Batch Modification › Move Operation @roundtrip `
> 
> And focus on the 3:
> 
> ```
>     [chromium] › tests/dashboard.spec.ts:78:7 › Dashboard › Statistics ─────────────────────────────
>     [chromium] › tests/processes.spec.ts:100:7 › Processes › Processes Page Initial Load ───────────
>     [chromium] › tests/processInstance.spec.ts:103:7 › Process Instance › Resolve an incident @roundtrip 
> ```

Yes exactly I also saw the others previously on other PRs

**Comment by npepinpe** [comment]
OK, got it. So the issue is that the E2E tests use the snapshot image. There's a bug fix which this PR depends on, but since the E2E tests uses the deployed snapshot, it won't pick up that fix.

So the tests are failing :melting_face:

**Comment by npepinpe** [comment]
We need to merge https://github.com/camunda/camunda/pull/26005 first otherwise.

**Comment by ChrisKujawa** [comment]
Then we could alao just merge?

**Comment by npepinpe** [comment]
I'd like to make sure I'm right at least once.

**Comment by npepinpe** [comment]
And I can't base it - I think I wasn't clear. It doesn't matter if I base on the same branch - the service starts by pulling an image from Docker Hub, it won't use the latest Zeebe changes. I think this will cause such issues to come back in the future, and should be fixed anyway.

**Comment by ChrisKujawa** [comment]
> And I can't base it - I think I wasn't clear. It doesn't matter if I base on the same branch - the service starts by pulling an image from Docker Hub, it won't use the latest Zeebe changes. I think this will cause such issues to come back in the future, and should be fixed anyway.

Sorry I think you were clear I just haven't thought fully about what I wrote before (I did something in parallel sorry 😅 )

**Comment by npepinpe** [comment]
Let's merge https://github.com/camunda/camunda/pull/26005 and then this one. And then we're done for now with post-importer (minus the dozen improvements missing :D)

**Comment by npepinpe** [comment]
Yup, looks good - locally I now only have these failing tests, similar to main:

```
  5 failed
    [chromium] › tests/childProcessInstanceMigration.spec.ts:47:7 › Child Process Instance Migration @roundtrip › Migrate Child Process Instances 
    [chromium] › tests/operations.spec.ts:96:7 › Operations › Retry and Cancel single instance @roundtrip 
    [chromium] › tests/operations.spec.ts:177:7 › Operations › Retry and cancel multiple instances @roundtrip 
    [chromium] › tests/processInstanceListeners.spec.ts:125:7 › Process Instance Listeners › Listeners list filtered by listener type @roundtrip 
    [chromium] › tests/processInstanceMigration.spec.ts:157:7 › Process Instance Migration › Auto Mapping @roundtrip 
```

**Review by ChrisKujawa — APPROVED** [review]

**Comment by ChrisKujawa** [comment]
Do we need to rebase first? I can push the merge button

**Comment by ChrisKujawa** [comment]
Awesome that was quick merge now. Thanks @npepinpe for your work :rocket:

**Pull request merged**
