### PR TITLE
Bring internal socket back

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

 After replacing transport we used only one socket for cluster and
 command communication. The problem with this approach is that we can't
 replace the current transport implementation independent from our cluster
 implementation (atomix), which was our goal.
 We created for the transport implementation an extra abstraction layer,
 but when we only support one port for all communication then we still
 depend on the atomix implementation.

 Furthermore the command traffic and cluster communication can
 compete with each other on the single socket. Using one socket will also cause a lot of changes
user configurations and cloud setup.

 In order to still support two sockets for internal communication and
 external commands, we need to use a different MessagingService at the
 ServerTransport implementation. The transport implementation now only
 uses the MessagingService interface instead of the fat
 ClusterCommunicationInterface, which means the requests are now send
 based on addresses instead of node ids.

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 62caf367161eab69dd6ac05acad36004f90608eb
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci, build**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 62caf367161eab69dd6ac05acad36004f90608eb
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci, build**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by menski — APPROVED** [review]
bors r+

**Comment by Zelldon** [comment]
bors retry

**Comment by Zelldon** [comment]
Bors r+

**Comment by Zelldon** [comment]
Bors r+

**Pull request merged**
