### PR TITLE
fix(protocol-impl): copy deployment resources

### LINKED ISSUE #2727: If multiple resources are deployed in a single command the resource names are duplicated
See https://github.com/zeebe-io/zeebe/commit/eb65c8f798852abb76b6b63fac8a219fcda1ea61 for a failing test case

### PR DESCRIPTION
**Pull request by miguelpires**
closes #2727

### CODE REVIEW

**Comment by menski** [comment]
We basically now have to different solutions next to each other for the same problem I guess.

What's the better solution, or is ask in a different way, do we need a full copy? @Zelldon @MiguelPires  any opinion?

`getResources` creates a new wrapper around the underlying buffer
https://github.com/zeebe-io/zeebe/blob/1879de32d8fbe28eda9bddc9bed1e38fe064c7c7/protocol-impl/src/main/java/io/zeebe/protocol/impl/record/value/deployment/DeploymentRecord.java#L56-L65

`getWorkflows` does a full copy of the buffer
https://github.com/zeebe-io/zeebe/blob/1879de32d8fbe28eda9bddc9bed1e38fe064c7c7/protocol-impl/src/main/java/io/zeebe/protocol/impl/record/value/deployment/DeploymentRecord.java#L69-L86

**Comment by Zelldon** [comment]
The first solutions uses the new public API methods, which will create strings or byte arrays from the underlying buffer. This means 
`r.getResourceName` will create a new String and past them into the new resource object, for the resource a new byte array is allocated and copied and resource type is a enum so no problem in copying. 

The second solution was implemented before we migrated to the interfaces, but nevertheless I personally prefer to just copy in one step and create the object out of this. 

Because if we had mistakenly choose one of the old methods in the first solution we had again the same problem. :man_shrugging:

**Comment by menski** [comment]
Sounds reasonable to me. @MiguelPires in case you agree with Chris could you please adjust the fix to be similar to the `getWorkflows` method. Thanks.

**Comment by MiguelPires** [comment]
Sure, I'm fine with that. I pushed the new version

**Review by menski — APPROVED** [review]
bors r+

**Pull request merged**
