### PR TITLE
Introduce new migration partition transition step

### LINKED ISSUE #14252: When upgrading to 8.3, ensure that the runtime state gets migrated accordingly
**Description**

With the introduction of multi-tenancy in the upcoming 8.3 release, the runtime state stored needs to be migrated because:

1. For most of the column families, the key layout changes, i.e., the respective `tenantId` becomes part of the key.
2. By including the `tenantId` in the key, the data of the corresponding column families needs to be reindexed to new column families.

Currently, the migration only happens when a Zeebe broker becomes the leader for a given partition after upgrading to a newer Zeebe version:

https://github.com/camunda/zeebe/blob/7598696d5af5eebbf233f64deecb6cbeff0f9355/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/StreamProcessor.java#L325-L338

(Please note: The `DbMigrationController` - to run the actual migration - is called by ` l.onRecovered(streamProcessorContext)`.)

Now with the upcoming changes introduced by multi-tenancy, a Zeebe broker upgraded from 8.2 to 8.3 won't be able to replay anything because it won't find the necessary data anymore in RocksDB. This is because the key layout changed and the newly introduced column families (which are empty at that point). Meaning, the data is not migrated before the replay, so the latest snapshot corresponds to the 8.2 RocksDB schema. But when applying the events from the logstream, it assumes that the runtime state is already in the 8.3 RocksDB schema.

In a nutshell:
* After upgrading to 8.3, the followers won't be able to replay any command as long as the runtime state is not migrated to 8.3.
* Even after an upgrade a Zeebe broker - running in version 8.3 - becomes leader, it won't be able to replay. Hence, the leader won't process any new incoming command.

---

required by #13315 
related to #7248

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Pull out-migration of engine state from StreamPlatform to
PartitionTransition.

Previously, migration was done only if StreamProcessor was installed
with processing in mind (leader only).

The new migration step will allow to migrate the state in all cases and
role changes.

Potential role changes:

* When transitioning from Follower to Leader, the database is reused,
which means migration has happened already and is automatically skipped.

* When transitioning from Follower to Candidate and back to follower the database is reused as well.

* If follower receives a snapshot, partition goes to INACTIVE and FOLLOWER
again and this approach also allows to migrate received old snapshots.

* Only if Leader becomes follower, and state is recreated from snapshot
migration has to run again. Or on broker restart.

Migration can take time, and is blocking the partition installation.
This is the reason why we need to decouple the ready status from the
Zeebe partition installation, see https://github.com/camunda/zeebe/pull/14299

See related summaries in issue #14252 and pro's and cons of alternatives. 

⚠️ @romansmirnov mentioned one issue during our discussion, that if the Leader is on 8.3, replicates a snapshot to a follower on 8.2, and such follower replays and inserts data it might be problematic if this node becomes leader. Later the snapshot might not migrated because the marker is already set. Here we need a better detection of whether to migrate data or not, but this doesn't affect the current solution or doesn't need to change our current approach (where to do the migration). Might be also interesting to think about whether we want to reject snapshots from different versions, but this needs to be discussed and think about more carefully. 

## Related issues

closes #14252 

blocked by https://github.com/camunda/zeebe/pull/14299
<!-- Cut-off marker
_All lines under and including the cut-off marker will be removed from the merge commit message_

### CODE REVIEW

**Comment by Zelldon** [comment]
Second benchmark with should test rolling update from 8.2 to our branch version.

[Build up of some state:](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=rc-migration-rolling-update&var-pod=All&var-partition=All)
state

Running upgrade:

```sh
tag=rc-migration-step-benchmark-26af196
helm upgrade rc-migration-rolling-update zeebe-benchmark/zeebe-benchmark \
--set starter.replicas=0 \
--set worker.replicas=1 \
--set global.image.tag=$tag \
--set camunda-platform.zeebe.image.repository=gcr.io/zeebe-io/zeebe \
--set camunda-platform.zeebe.image.tag=$tag \
--set camunda-platform.zeebe-gateway.image.repository=gcr.io/zeebe-io/zeebe \
--set camunda-platform.zeebe-gateway.image.tag=$tag \
--reuse-values
```

We can see that the brokers become ready after ~40-50 seconds. To be specific we can see that Broker-2 (where rolling update starts) is becoming ready around 15:29:09 and [the migration for partition two on Broker 2 starts one minute after](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22rc-migration-rolling-update%22%0Alabels.k8s-pod%2Fapp%3D%22camunda-platform%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22zeebe-broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22rc-migration-rolling-update%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fpart-of%3D%22camunda-platform%22%0Alabels.%22k8s-pod%2Fstatefulset_kubernetes_io%2Fpod-name%22%3D%22rc-migration-rolling-update-zeebe-2%22;pinnedLogId=2023-09-13T13:30:05.506355031Z%2Faphklt0010fy8apn;summaryFields=jsonPayload%252Fcontext%252FpartitionId:false:32:beginning;cursorTimestamp=2023-09-13T13:30:05.523247203Z;duration=PT15M?project=zeebe-io), which proves that this is now decoupled.

rdy-migration

The migration of around ~200 mb of state took ~2 seconds for the ProcessInstanceByProcessDefinitionMigration. This might be interesting and improve further, especially when we want to migrate the whole database for multi-tenancy.

**Comment by Zelldon** [comment]
With the latest benchmark, we see a successful rolling update with migration from 8.2 to 8.3

We started instances before the upgrade and completed the jobs after the upgrade. 🎉 

rolling-update-migration

**Review by romansmirnov — APPROVED** [review]
LGTM!

**Pull request merged**
