### PR TITLE
docs: update docs link

### PR DESCRIPTION
**Pull request by christinaausley**
## Description

https://github.com/camunda/camunda/pull/17585 went stale -- re-opening. Fix broken link to documentation.

## Related issues

https://github.com/camunda/doc-hospital/issues/14

closes #

https://github.com/camunda/doc-hospital/issues/14

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]

**Comment by christinaausley** [comment]
Hi @Zelldon — can you explain why these checks are failing and I’ll get this cleaned up and merged?

**Comment by Zelldon** [comment]
@npepinpe can you check when you are back?

**Review by npepinpe — APPROVED** [review]

**Comment by npepinpe** [comment]
As the PR is too old to rerun the failed checks, I will try closing/reopening so we can add it to the merge queue.

**Comment by christinaausley** [comment]
Ha -- thank you all for reviving this. Am I free to merge?

**Pull request merged**
