### PR TITLE
Improve latency metrics section

### LINKED ISSUE #7076: Remove processing event latency
**Description**

Due to our latest refactorings and migration to event sourcing we no long process events. This makes the process latency for events metric and panel obsolete.

proc-event-lat

### PR DESCRIPTION
**Pull request by ChrisKujawa**
### Before

before-latency1
before-latency2
before-latency3

### After change

latency1
latency2

Rework the Processing Latency Section:

 * Rename it to Latency, since it contains more then only processing
   latencies
 * Remove unnecessary event processing, it is no longer exported
 * Resize and reorganize panels to make view more clean
 * Rename panels and adjust descriptions to make the purpose more clear

The record type label for the processing metric didn't make sense anymore since we only process commands. I removed it.

## Related issues

closes #7076 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
bors merge

:tada:

**Comment by Zelldon** [comment]
@npepinpe it seems these changes have been overwritten. Do you know why?

Have a look at our grafana dashboard you can see again these panels, with no metrics :eyes: 

no-metrics

**Comment by npepinpe** [comment]
If they were it wasn't on purpose. Maybe we merged something that changed them? I know we did a few things lately in the dashboard.

**Comment by Zelldon** [comment]
It seems my second PR overwrote it :facepalm: I try to get it back but it is not that easy as I  like it to be...

**Pull request merged**
