### PR TITLE
fix(clients/go): fix zbctl building failure for Windows

### LINKED ISSUE #3238: Problems on Zbctl build
**Describe the bug**
It seems that we have a problem on building zbctl (locally and on the ci).

```
+ .ci/scripts/distribution/build-go.sh
+ set -o pipefail
+ export CGO_ENABLED=0
+ CGO_ENABLED=0
+ ORG_DIR=/go/src/github.com/zeebe-io
+ mkdir -p /go/src/github.com/zeebe-io
+ ln -s /home/jenkins/agent/workspace/zeebe-io_zeebe_develop /go/src/github.com/zeebe-io/zeebe
+ go get -u github.com/jstemmer/go-junit-report
+ cd /go/src/github.com/zeebe-io/zeebe/clients/go
+ make install-deps
go get -u github.com/golang/dep/cmd/dep
dep ensure
+ cd /go/src/github.com/zeebe-io/zeebe/clients/zbctl
+ ./build.sh
+ OS=(linux windows darwin)
+ BINARY=(zbctl zbctl.exe zbctl.darwin)
++ dirname ./build.sh
+ SRC_DIR=.
+ DIST_DIR=./dist
+ VERSION=development
++ git rev-parse HEAD
+ COMMIT=0af6066561ba901d4f9d4c07e1175491214721b2
+ mkdir -p ./dist
+ rm -rf './dist/*'
+ for i in "${!OS[@]}"
+ for i in "${!OS[@]}"
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=amd64
+ for i in "${!OS[@]}"
+ go build -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/zbctl/cmd.Version=development -X github.com/zeebe-io/zeebe/clients/zbctl/cmd.Commit=0af6066561ba901d4f9d4c07e1175491214721b2' -o ./dist/zbctl ./main.go
+ CGO_ENABLED=0
+ GOOS=windows
+ GOARCH=amd64
+ go build -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/zbctl/cmd.Version=development -X github.com/zeebe-io/zeebe/clients/zbctl/cmd.Commit=0af6066561ba901d4f9d4c07e1175491214721b2' -o ./dist/zbctl.exe ./main.go
+ wait
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=amd64
+ go build -a -tags netgo -ldflags '-w -X github.com/zeebe-io/zeebe/clients/zbctl/cmd.Version=development -X github.com/zeebe-io/zeebe/clients/zbctl/cmd.Commit=0af6066561ba901d4f9d4c07e1175491214721b2' -o ./dist/zbctl.darwin ./main.go
# github.com/zeebe-io/zeebe/clients/go/vendor/github.com/docker/docker/pkg/system
../go/vendor/github.com/docker/docker/pkg/system/filesys_windows.go:111:24: cannot use uintptr(unsafe.Pointer(&sd[0])) (type uintptr) as type *"github.com/zeebe-io/zeebe/clients/go/vendor/golang.org/x/sys/windows".SECURITY_DESCRIPTOR in assignment
```
After having this locally I had no zbctl.exe in my dist folder, only `zbctl` and `zbctl.darwin`.

**To Reproduce**

Run  `clients/zbctl/build.sh`

**Expected behavior**
No errors on build.

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Makes the container rule a test file so it's ignored by go build and doesn't cause the docker dependency to fail the build.

## Related issues

closes #3238 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by npepinpe** [comment]
Good catch, I'm sorry I missed it the first time :sweat_smile:

**Comment by npepinpe** [comment]
Can we double check that we have no other test files being compiled by mistake? e.g. `clients/go/utils/test_utils.go`, is that compiled? It's prefixed with `test_` but I think only things suffixed with `_test` are ignored?

**Comment by MiguelPires** [comment]
`test_utils` can't be renamed to `utils_test` because then it wouldn't be compiled and tests in other packages that depend on it would fail (namely the tests in the command package). I didn't see any other cases that are missing the `_test.go`

**Comment by npepinpe** [comment]
It was just an example :sweat_smile: Seems like in go test utilities are meant to be in a package (like `httptest`) and only imported in test code. 

Anyhow :+1: , it's fine to leave `test_utils`, let's just make sure we have no other test files missing `_test`.

**Review by npepinpe — APPROVED** [review]

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
