### PR TITLE
feat(exporter/elasticsearch): Add sequence to record template 

### PR DESCRIPTION
**Pull request by saig0**
## Description

Add a new property `sequence` to the general record template. It contains a number that is increased for each exported record grouped by its value type.

It can be used to limit the number of records when reading from the index. For example, by using a range query like `RangeQuery: last_imported_sequence < sequence <= last_imported_sequence + batch_size`.

## Related issues

part to #10568 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by saig0** [comment]
@koevskinikola please have a look. When you viewed the changes, ping me and we can go over it together.

**Review by koevskinikola — COMMENTED** [review]
hey @saig0, the changes look good, they make sense to me, and the test coverage looks good.

Before I approve the PR, I'd like to clarify the following:
* How does this change impact records that have already been exported and indexed? 
* Do we need to take care of some type of migration, or ES handles this, and I just lack the knowledge there? :smiley:

**Review by koevskinikola — APPROVED** [review]
lgtm :rocket: 

During our call, @saig0 provided answers to my questions above:
* ES takes care of providing different indexes for records from different Zeebe versions. The consuming applications take care of how the different data is imported. So the ZPA team doesn't need to provide anything regarding the migration of old records.

bors merge

**Comment by saig0** [comment]
bors merge

**Comment by saig0** [comment]
bors merge

**Pull request merged**
