### PR TITLE
Increase parallelism of integration tests

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

The pod where our IT tests are running appeared to be underutilized so I increased the number of tests that are run in parallel.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by oleschoenburg** [comment]
@npepinpe I know you are quite busy now but this change is quite small and you are working on CI anyway so I requested your review. Let me know if you don't have time.

**Comment by Zelldon** [comment]
Do I see this right that it gives 2 min speed up :rocket:  https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/ci-increase-it-parallelism/8/pipeline/257 vs https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/develop/1054/pipeline/266

**Comment by oleschoenburg** [comment]
Sometimes even more apparently: https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/alexanderavdeev14%2F7630-not-null-response-client/2/pipeline/257
it looks like even more.

**Comment by npepinpe** [comment]
Increasing parallelism always has a risk of increasing flakiness when you max out the resource usage. Can you trigger several builds in a row to see how stable it is compared to the normal branch? I know right now it's unstable so this may be difficult, but if it's only the same tests that are flaky then we could say it's stable enough with increased parallelism.

Say, let's run 8 builds?

**Comment by oleschoenburg** [comment]
That's fair, I'll trigger more runs. By the way, while playing around with the number here I've never managed to trigger a flaky tests :shrug:

**Comment by npepinpe** [comment]
<details><summary>challenge accepted</summary>

[challenge accepted]

</details>

**Comment by npepinpe** [comment]
I've triggered 8 more builds, let's check the outcome after lunch.

**Comment by npepinpe** [comment]
The ElasticsearchExporter flaky test is common so I don't think you introduced more flakiness on this one. I see otherwise some aborted builds, and some other flaky tests, but I haven't had time to compare with staging/develop, so can't gauge.

I'm happy to merge this anyway with the caveat that please monitor the pipeline in the next days/week, and to revert it as quickly as possible if it causes issue. Another option would be to use these parameters only on the develop branch, and to go back to running our develop builds more than once a day (maybe 6x a day or some such), so we could get a feel for how this performs without impacting people's work and ability to merge.

**Comment by oleschoenburg** [comment]
Okay, I'll merge as is and promise to keep an eye on it in the next weeks

bors merge

**Comment by oleschoenburg** [comment]
Let's try that again once @npepinpe approves.

**Review by npepinpe — APPROVED** [review]
:+1: 

Make sure to keep an eye on `develop` then and on `staging`. Please also announce it in the team channel so if others notice an increase in instability in their feature branches they can ping you in case it's due to this.

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
