### PR TITLE
Introduce query API client in the gateway

### LINKED ISSUE #7756: Introduce a simple query api to the gateway
**Description**

Introduce a simple Query API to the gateway that can be used to send `ExecuteQueryRequest` to the broker. 

It should be accessible to the configured gRPC interceptors.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR adds a new query API client in the gateway. The client can send `BrokerQueryRequest` (which map to `ExecuteQueryRequest` and `ExecuteQueryResponse` messages) and query the process ID of a given resource from a broker.

There are currently not integration test, as we're still missing the last part (the interceptors), and writing integration tests here would require a lot of knowledge of the implementations.

Additionally, while we made the query service in the broker `@Deprecated` to indicate its temporary nature, I was unsure as to do it here as well for the `QueryApi`, as that may be used by users. Let's discuss this.

## Related issues

closes #7756 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
@menski let me know if you don't find time for this

**Comment by npepinpe** [comment]
Looks like some tests are failing, I'll ping you again for a review.

**Comment by npepinpe** [comment]
I'm starting to second guess making the API asynchronous, mostly because in a bare bones interceptor you don't really have any execution context. Let's say I write something like:

```java
public final class MyInterceptor implements ServerInterceptor {
  private final QueryApi api;

  public MyInterceptor(final QueryApi api) {
    this.api = api;
  }

  @Override
  public <ReqT, RespT> Listener<ReqT> interceptCall(
      final ServerCall<ReqT, RespT> call,
      final Metadata headers,
      final ServerCallHandler<ReqT, RespT> next) {
    try {
      api.getBpmnProcessIdForProcess(1, Duration.ofSeconds(5)).whenComplete((processId, error) -> {
        if (error == null) {
          // do something with processId
          next.startCall(call, headers);
        } else {
          // handle errors and make sure to terminate the call
        }
      });
    } catch (final Exception e) {
      // handle error and terminate the call just to be safe
    }
  }
}
```

That works, but it also means your callback in `whenComplete` is executed in the actor scheduler threads (i.e. the transport module thread) context, which is not the same context in which you were initially executed, which can be confusing and problematic if your interceptor uses (directly or indirectly) the thread context class loader. 

So ideally if we do some asynchronous code, either the interceptor can ask to handle the result on the right thread context, or we just do synchronous calls - but that blocks one thread in the gRPC pool, which is also meh.

**Review by menski — APPROVED** [review]
Looks good to me

As discussed in Slack maybe let's add a note in the Java Doc that future callback might be executed on a different thread.

Also regarding your question of deprecated vs experimental, I think the current state is fine, we could note it again in the javadoc of the class. Based on https://docs.camunda.io/docs/reference/public-api non of the classes in the gateway are public API

**Comment by npepinpe** [comment]
The asynchronous issue will be documented in the next PR. I think I found an OK-ish solution for it.

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors retry

**Comment by npepinpe** [comment]
bors retry

**Comment by npepinpe** [comment]
bors retry

**Pull request merged**
