### PR TITLE
Fix line separators `ModifyProcessInstanceRejectionTest`

### LINKED ISSUE #12875: `ModifyProcessInstanceRejectionTest#shouldRejectActivationWhenAncestorScopeIsNotFlowScope` test fails on Windows
**Summary**

Run `ModifyProcessInstanceRejectionTest#shouldRejectActivationWhenAncestorScopeIsNotFlowScope` test failed on Windows 10.

**Logs**

<details><summary>Logs</summary>
<pre>
E PI   SEQ_FLOW_TAKEN    - #63->#05 K21 - SEQUENCE_FLOW "sequenc..b588006" in <process "process"[K03]>
C PI   ACTIVATE          - #64->#05 K22 - PARALLEL_GATEWAY "join" in <process "process"[K03]>
R PI   ACTIVATE          - #65->#05 K22 - PARALLEL_GATEWAY "join" in <process "process"[K03]> !INVALID_STATE (Expected to be able to activate parallel gateway 'join', but not all sequence flows have been taken.)
C MOD  MODIFY            - #66-> -1 K03 - <activate "A" no vars> <activate "B" no vars> <activate "A" no vars> 
R MOD  MODIFY            - #67->#66 K03 - <activate "A" no vars> <activate "B" no vars> <activate "A" no vars>  !INVALID_ARGUMENT (Expected to modify instance of process 'process' but it contains one or more activate instructions with an ancestor scope key that is not an ancestor of the element to activate:
- instance '2251799813685257' of element 'subProcess2' is not an ancestor of element 'A'
- instance '2251799813685263' of element 'B' is not an ancestor of element 'A')

java.lang.AssertionError: [Expect that subProcess2 cannot be selected as ancestor of task A] 
Expecting rejectionReason of:
  <{"valueType":"PROCESS_INSTANCE_MODIFICATION","key":2251799813685251,"position":67,"timestamp":1685115125924,"recordType":"COMMAND_REJECTION","intent":"MODIFY","partitionId":1,"rejectionType":"INVALID_ARGUMENT","rejectionReason":"Expected to modify instance of process 'process' but it contains one or more activate instructions with an ancestor scope key that is not an ancestor of the element to activate:\r\n- instance '2251799813685257' of element 'subProcess2' is not an ancestor of element 'A'\r\n- instance '2251799813685263' of element 'B' is not an ancestor of element 'A'","brokerVersion":"8.3.0","value":{"processInstanceKey":2251799813685251,"ancestorScopeKeys":[],"terminateInstructions":[],"activateInstructions":[{"ancestorScopeKeys":[],"elementId":"A","ancestorScopeKey":2251799813685257,"variableInstructions":[]},{"ancestorScopeKeys":[],"elementId":"B","ancestorScopeKey":2251799813685257,"variableInstructions":[]},{"ancestorScopeKeys":[],"elementId":"A","ancestorScopeKey":2251799813685263,"variableInstru...>
to be:
  <Expected to modify instance of process 'process' but it contains one or more activate instructions with an ancestor scope key that is not an ancestor of the element to activate:
- instance '2251799813685257' of element 'subProcess2' is not an ancestor of element 'A'
- instance '2251799813685263' of element 'B' is not an ancestor of element 'A'>
but was:
  <Expected to modify instance of process 'process' but it contains one or more activate instructions with an ancestor scope key that is not an ancestor of the element to activate:
- instance '2251799813685257' of element 'subProcess2' is not an ancestor of element 'A'
- instance '2251799813685263' of element 'B' is not an ancestor of element 'A'>

	at io.camunda.zeebe.engine.processing.processinstance.ModifyProcessInstanceRejectionTest.shouldRejectActivationWhenAncestorScopeIsNotFlowScope(ModifyProcessInstanceRejectionTest.java:664)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
</pre>
</details>

```
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.bitness: 64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64

```

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

This test failed on some Windows machines because the line separators didn't match. We create the message with the platform-specific line separator. However, in our test we don't do this. Instead, it used \n. This commit switches the test to use a platform-specific line separator as well.

## Related issues

closes #12875 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by korthout — APPROVED** [review]
LGTM 👍 

Thanks @remcowesterhoud

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors retry

**Comment by remcowesterhoud** [comment]
bors retry

**Pull request merged**
