### PR TITLE
chore(util): clean up StreamUtil

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Fixes an LGTM warning and clean up the class.

## Related issues

related https://github.com/zeebe-io/zeebe/issues/5647

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
This seems to now be only used in the DebugHttpServer? Can't we just move it next to it as a utility for it instead of something in the util module? To be honest I don't see much use to this here anyway, we should be using transfer channels instead of copying between streams with a temporary buffer, no? But if it's just for the debug stuff, meh, I would just move it next to it.

**Comment by Zelldon** [comment]
I'm also fine of deleting the debughttpexporter :sweat_smile:

**Comment by npepinpe** [comment]
I'm thinking about it as I don't think anybody uses it, but I'd like to replace it with something. Let's leave it as is for now until we have a proposal for a streaming debug exporter.

**Comment by Zelldon** [comment]
@npepinpe thanks for the review. I replaced everything

**Review by npepinpe — APPROVED** [review]
:tada:

**Pull request merged**
