### PR TITLE
test(github): add testfile to backport

### PR DESCRIPTION
**Pull request by korthout**
## Description

This PR exists to test our new GitHub actions workflow to automatically backport PRs to other branches.

## Related issues

NA

### CODE REVIEW

**Comment by korthout** [comment]
@pihme please have a look. Should be ready to merge now

**Review by pihme — APPROVED** [review]

**Comment by korthout** [comment]
bors retry

**Comment by korthout** [comment]
flaky test

bors retry

**Comment by korthout** [comment]
The action failed, because the fix was in `develop` (the main branch), but not yet in this PR. So, we'll have to test it again

**Pull request merged**
