### PR TITLE
Distribute DMN decision to other partitions

### LINKED ISSUE #8567: Distribute DMN decision to other partitions
## Description

The deployed DMN decisions are part of the deployment event. The deployment event is distributed from the deployment-partition (i.e. partition 1) to all other partitions. On the other partitions, we should put the DMN decisions in the state to evaluate DMN decisions on all partitions.

* extend the event applier for the deployment `DISTRIBUTED` event
  * insert the decisions and DRGs in the DMN decision state         

blocked by #8069
blocked by #8072

### PR DESCRIPTION
**Pull request by saig0**
## Description

* put DMN resources of distributed deployment event in the state
* verify the distribution by checking the presents of the `distributed` and `fully distributed` deployment events
  * unfortunately, the tests don't check that the DMNs are really put in the state
  * I would postpone the full test until we can evaluate decisions with business rule tasks   

## Related issues

closes #8567

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by korthout — CHANGES_REQUESTED** [review]
Thanks @saig0 The main parts look good, but I think something is missing.

❌ the deployment should be cleaned up again once it is fully distributed. AFAIK, we only store this to accommodate failure/restart during the deployment distribution.

**Comment by saig0** [comment]
> :x: the deployment should be cleaned up again once it is fully distributed. AFAIK, we only store this to accommodate failure/restart during the deployment distribution.

What do you mean exactly?

The deployment is distributed from partition 1 to the other partitions by sending a deployment `distribute` command. This command contains all resources and the deployment metadata. The process / decision / decision-requirements records themself are not distributed. 

This PR uses the existing distribution logic and just extends the event applier for the deployment `distributed` event. As a result, the decisions and DRG should be distributed.

Which parts did I miss? :sweat_smile:

**Comment by saig0** [comment]
The `DeploymentFullyDistributedApplier` keeps track of pending deployments. If a deployment is fully distributed then it removes the deployment from the pending column family. Since this happens for the whole deployment, we don't need to extend the applier.

The `DeploymentDistribution` appliers keep track to which partitions the deployment is distributed. The deployment distribution command is sent from a partition to the deployment partition (i.e. partition 1). The command/event just contains the deployment key and the partition id. Since this works also for the whole deployment, we don't need to change something. 

@korthout does this make sense for you?
Feel free to discuss it f2f.

**Review by korthout — APPROVED** [review]
Sorry for keeping this blocked, but it's clear to me now that the pending deployments are cleaned up correctly.

LGTM 🏆

**Comment by saig0** [comment]
bors merge

:notebook: note that we should write internal documentation about the deployment distribution.

**Comment by saig0** [comment]
bors merge

**Pull request merged**
