### PR TITLE
build: re-enable dependency analyzer

### LINKED ISSUE #8690: Re-enable the dependency analyzer plugin
**Description**

It seems version 1.12.0 of the analyzer was released. By bumping it and its plugin to 3.2.0, we should be able to re-enable it. It will flag certain dependencies as in the wrong scope, and from quickly looking at them it seems it's correct, they are in the wrong scope and should be fixed.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Re-enables the dependency analyzer plugin and tries to fix all dependency issues. 

## Related issues

closes #8690

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
:+1: 

There are some false positives it seems, specifically grpc-core comes up more than once. What happened when we didn't mark it as such? I could imagine the client, for example, not directly depending on grpc-core except in the tests.

**Comment by oleschoenburg** [comment]
>  I could imagine the client, for example, not directly depending on grpc-core except in the tests.
Yeah, that's exactly what's being flagged, a test-test scoped dependency being used only in tests. Tbh. I assumed that this must be a false positive and ignored this warning. Are you saying that the java client really doesn't use grpc-core in production?

**Comment by npepinpe** [comment]
It does transitively via other gRPC libraries, but it doesn't have a direct dependency on it except in tests. That's why I asked, what happens if you scope it as a test dependency?

**Comment by oleschoenburg** [comment]
Marking grpc-core as test scoped causes compilation to fail:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.0:compile (default-compile) on project zeebe-client-java: Compilation failure: Compilation failure:
[ERROR] /home/ole/Source/zeebe/clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientImpl.java:[125,28] cannot access io.grpc.internal.AbstractManagedChannelImplBuilder
[ERROR]   class file for io.grpc.internal.AbstractManagedChannelImplBuilder not found
[ERROR] /home/ole/Source/zeebe/clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientImpl.java:[129,19] cannot find symbol
[ERROR]   symbol:   method userAgent(java.lang.String)
[ERROR]   location: variable channelBuilder of type io.grpc.netty.NettyChannelBuilder
[ERROR] /home/ole/Source/zeebe/clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientImpl.java:[131,26] cannot find symbol
[ERROR]   symbol:   method build()
[ERROR]   location: variable channelBuilder of type io.grpc.netty.NettyChannelBuilder
[ERROR] /home/ole/Source/zeebe/clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientImpl.java:[165,23] cannot find symbol
[ERROR]   symbol:   method overrideAuthority(java.lang.String)
[ERROR]   location: variable channelBuilder of type io.grpc.netty.NettyChannelBuilder
[ERROR] -> [Help 1]
```

I'm treating this as a false positive then.

**Comment by npepinpe** [comment]
Weird, when I checkout the branch and mark it as test scoped I don't get compilation errors :thinking:

**Review by npepinpe — APPROVED** [review]
:rocket:

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
