### PR TITLE
Conform dependabot PRs to commitlint

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

Removes the non-scopes from the dependabot commits (e.g. `deps(maven)`, `deps(go)`). Scope is optional for our commits, and I don't think specifying the type of update is all that useful. Since dependabot cannot figure out the real scope, we might as well just omit it.

An example PR which fails commit lint: https://github.com/camunda/zeebe/pull/12319

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by Zelldon** [comment]
I think another issue in some prs was that the body was too long.

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]
@npepinpe I don't mind removing this but as Zell mentioned this is not why the PR you linked is failing. The body is too long, so I think we should increase, or just remove, the max body size.

**Comment by npepinpe** [comment]
Really? I thought we restricted the scopes, so it seemed obvious to me that `maven` would be rejected as a scope :thinking: Maybe I misunderstood the config file.

**Comment by npepinpe** [comment]
Seems I was wrong. Not sure where I got that :shrug: Happy to close it

**Comment by remcowesterhoud** [comment]
I mean we definitely should fix the issue with the body size still 😄

I can create a PR for this tomorrow

**Pull request closed without merging**
