### PR TITLE
docs: fixed broken links in README.md

### PR DESCRIPTION
**Pull request by jenshb**
## Description

Fixed the broken links in READM.me due to https://github.com/camunda/camunda/commit/fa3919f106b653f02dec43365450679719edca4f

### CODE REVIEW

**Review by korthout — APPROVED** [review]
Thanks @jenshb 💯 

👍 LGTM

**Comment by korthout** [comment]
Due to a limitation in our current CI, I'll need to create a new PR with your changes. This is just for technical reasons and will be done on behalf of you as contributor @jenshb. For more details, please refer to:
- https://github.com/camunda/camunda/issues/19222

**Comment by jenshb** [comment]
thanks, Nico!

**Comment by korthout** [comment]
Thanks for the contribution @jenshb 🙇

**Pull request merged**
