### PR TITLE
Propagate secret to test job reusable workflow

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

When the test workflow is called as a reusable workflow, it doesn't receive secrets unless the calling workflow specifies them. This breaks the Testcontainers Cloud integration which requires the token to be present.

This PR just propagates all secrets from the deploy job down to the test job. Additionally, we skip setting up the Testcontainers Cloud agent if no token is available. The tests will run just fine without the agent and instead will use the available local Docker daemon, so performance may be different. This can be helpful for PRs opened by bots, or forks, for example. In this case not so much since we use a self-hosted runners, so forks are out of luck, but if we use it in other jobs not using self hosted runners it could be useful.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
One small question, don't we also want to check code quality before we deploy? Am I reading this right that we only check tests?

**Review by lenaschoenburg — APPROVED** [review]
Thanks! 👍

bors merge

**Comment by npepinpe** [comment]
Looks like the job hung for exporters and was simply not picked up. Let's try this again.

bors r-

**Comment by npepinpe** [comment]
It's again stuck waiting for exporter/slow unit tests. I'll try tomorrow early in the morning I guess.

**Pull request merged**
