### PR TITLE
Recreate jmh benchmarks for mappings

### PR DESCRIPTION
**Pull request by ChrisKujawa**
* restore merge mapping behavior jmh test
 * create throughput test for merge and extract

We will need these benchmarks for the next mapping improvements.

### CODE REVIEW

**Review by menski — CHANGES_REQUESTED** [review]
Currently only this jmh suite takes 21mins on Jenkins that brings the whole Jenkins pipeline over 30min. Is this really required for these benchmarks?

**Comment by menski** [comment]
> Why the jmh are execute on every run?

I think the idea was to see performance changes per commit.

> Maybe it is enough to execute them like the performance tests only once a day?

I don't have a real opinion here, at the moment they are executed in parallel to the normal tests. So as long as they are not longer then the normal test suite there is not much of a difference. If we run them once per day on the develop branch, you would not see the impact of your changes to the performance. I don't claim that anyone is looking at the numbers at the moment. We could also move them into a separate job, which is trigger async by any build so they are executed on there own.

**Comment by Zelldon** [comment]
>  I don't claim that anyone is looking at the numbers at the moment.

Yes, agree. I also think that if you interested  in the numbers or aware that your changes hit the performance, then you can do it manually and if you don't know, then the current state do not help either because it will not fail. 

> If we run them once per day on the develop branch, you would not see the impact of your changes to the performance

Ah ok, since the job is only execute on develop not on the branches you see no changes, got it.

> We could also move them into a separate job, which is trigger async by any build so they are executed on there own.

Yeah maybe.

**Comment by Zelldon** [comment]
Reduced the parameters and fixed the dependency scope.

**Comment by menski** [comment]
Thanks @Zelldon, I will take care of squashing the commits and merging it to develop. Enjoy your remaining vacation :beach_umbrella:

**Review by menski — APPROVED** [review]

**Comment by Zelldon** [comment]
Thanks :) will do :sun_with_face:

**Pull request merged**
