### PR TITLE
Replace Dashboard uids with human readable versions

### LINKED ISSUE #12601: Make dashboard UIDs human-readable
**Description**

Came up in https://github.com/camunda-cloud/alerts/pull/91, raised by @multani 

Right now our UIDs are not human readibly see https://github.com/camunda/zeebe/blob/11c54b23ab2d567c6933cf7925327481562d0b32/monitor/grafana/zeebe.json#L14934 which means it is hard to reference them and understand what the request dashboard is about.

Benefit references like this https://github.com/camunda-cloud/alerts/blob/e2245885e6010d08de2924d0da4750be9d33bb32/generated/camunda-cloud-240911/development-worker-1/monitoring.coreos.com_v1_prometheusrule_zeebe-crashlooping.yaml#L17 would be more clear

Changing the UID would improve this, I think this would be a simple and straight forward change. Similar to https://github.com/camunda-cloud/grafana-dashboards/issues/21

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Replaces the different grafana dashboard uids with human readable terms.

As follow up I created several other PRs in other repositories.

- [ ] https://github.com/zeebe-io/zeebe-engineering-processes/pull/337
- [ ] https://github.com/zeebe-io/zeebe-performance-test/pull/8
- [ ] https://github.com/camunda-cloud/alerts/pull/123
- [ ] https://github.com/camunda-cloud/runbook/pull/176
- [ ] https://github.com/camunda-community-hub/camunda-8-helm-profiles/pull/59
- [ ] https://github.com/camunda-cloud/camunda-cloud-management-apps/pull/773

## Related issues

closes #12601 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

Tried to think how we could make sure future dashboards also have human readable UIDs, but I guess we'll just have to remember for now. Not like we add them so often :shrug:

**Comment by Zelldon** [comment]
bors r+ 

Thanks for all the review @npepinpe :heart:

**Comment by npepinpe** [comment]
bors r+

Agh, it feels like we fix one flaky test (which comes up again and again), and then 10 pop up :sweat:

**Pull request merged**
