### PR TITLE
Add link to review guidelines in pr template

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Add review guidelines to the PR template

### CODE REVIEW

**Comment by npepinpe** [comment]
Looks good! I also read the page, good stuff! The only thing I found, and it's so small, is we actually support 2 minor versions, not 3 (I already edited it). Anyway, I like it!

**Review by npepinpe — APPROVED** [review]

**Comment by remcowesterhoud** [comment]
So close to perfection 😄 Thanks for reviewing!

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors retry

**Pull request merged**
