### PR TITLE
Rename distribution artifact from camunda-cloud-zeebe to camunda-zeebe

### LINKED ISSUE #8911: Rename distribution to camunda-zeebe
**Description**

As we're now aligning around Camunda 8, we will rename the distribution from `camunda-cloud-zeebe` to simply `camunda-zeebe`.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR renames the distribution artifact produced by `dist` to `camunda-zeebe`. This aligns the artifact names with other Camunda 8 artifacts in order to avoid confusion between Camunda and Camunda Cloud.

NOTE: I haven't tested the release since our release job picks up the scripts from `main`. I will test it once it's merged, but before the release. I anyway need to test the repo move before the release in April, so I would test them both then.

## Related issues

closes #8911

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Reviewed in the sense that I checked that there are no more mentions of `camunda-cloud-zeebe`, but really I have no idea what might break because of this :sweat_smile:

**Comment by npepinpe** [comment]
I think renaming the artifact won't break much, as it's pretty self contained. It might break other scripts which expect the name in other repositories, but I'm not really aware of any.

**Comment by npepinpe** [comment]
Just fixed merge conflicts, nothing else.

bors merge

**Pull request merged**
