### PR TITLE
Disable faulty subject-case commitlint rule

### PR DESCRIPTION
**Pull request by korthout**
## Description

We had disabled the subject case 'always' 'lowercase' rule, because our CONTRIBUTING guide does not specify any rules for casing.

However, from @commitlint/config-conventional we inherit a different rule:

Never
- sentence-case
- start-case
- pascal-case
- upper-case

This meant that we still get an error on a commit message like:
```
fix: Do the thing
subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
```

I've swapped the subject-case rule so we disable the inheritted rule.

## Related issues

encountered in #11902 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by remcowesterhoud — APPROVED** [review]
Man the syntax of commitlint takes some getting used to 😄 

So this means there is a rule that a commit subject may **never** contains sentence-case, start-case, pascal-case and upper-case. And we have now **disabled** this rule. So this means we now allow sentence-case, start-case, pascal-case and upper-case in the commit subject?

If it works like I think it LGTM

**Comment by korthout** [comment]
>So this means there is a rule that a commit subject may never contains sentence-case, start-case, pascal-case and upper-case. And we have now disabled this rule. So this means we now allow sentence-case, start-case, pascal-case and upper-case in the commit subject?

That is how I understand it.

We inherit [this subject-case rule](https://www.npmjs.com/package/@commitlint/config-conventional#subject-case) from `@commitlint/config-conventional` due to line 2 (which is sorta required as I understand it):
> extends: ['@commitlint/config-conventional'],

**Comment by korthout** [comment]
Let's see whether [f5685dd](https://github.com/camunda/zeebe/pull/12423/commits/f5685ddeac5af1eab108f33c1d98a6c05dfb7c17) passes commitlint

**Comment by korthout** [comment]
[f5685dd](https://github.com/camunda/zeebe/pull/12423/commits/f5685ddeac5af1eab108f33c1d98a6c05dfb7c17) passed commitlint, I'll remove it again and force-push

**Comment by korthout** [comment]
bors merge

**Pull request merged**
