### PR TITLE
Centralize entry serialization

### LINKED ISSUE #10919: Implement a `Serializer` that writes record batches with dispatcher framing
The sequencer is an implementation of `LogStreamBatchWriter`. It supports multiple writers and a single reader.
Every `LogAppendEntry` is assigned a position and `LogStreamBatchWriter.tryWrite` returns the highest position of the batch.

To prevent unlimited buffering of `LogAppendEntry`, the queue length is controlled. If it is too long, `tryWrite` will result in an error code.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

Adds a new class to handle the `LogAppendEntry` serialization. This class currently expects to work with the dispatcher, but this is mostly visible in tests. It will need a bit of adapting in the future once the dispatcher is removed to make it really agnostic.

## Related issues

closes #10919 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Blocked by #11115 - please review this first.

**Comment by npepinpe** [comment]
Classic CodeQL when you have a different base branch :smile:

**Review by lenaschoenburg — APPROVED** [review]

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors r+

Failed uploading the test artifacts?

**Pull request merged**
