### PR TITLE
Mark in processing via flag

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Previously the processing has been marked implicit via the currentProcessor
in order to move the processing call out to the engine, we need to mark
the processing more explicit.

## Related issues

as preparation for #9725 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by pihme — COMMENTED** [review]
:question: I am still wondering whether this can work. I can see that it works for the happy path, i.e. no exception. I don't see how it works in case an exception happens. At the same time, I also don't understand how it would work with the code before. So maybe this is how it is supposed to work? I.e. any exception will stop the acor?

If you have more background for this question, please share with me.

**Comment by Zelldon** [comment]
Exceptions in processing are catched here https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ProcessingStateMachine.java#L259-L271

And we always follow this state machine https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/streamprocessor/ProcessingStateMachine.java#L45-L76 where at some point we reach the execute side effects again and reset the flag.

**Review by pihme — APPROVED** [review]

**Comment by pihme** [comment]
@Zelldon Already rebased it.

**Comment by pihme** [comment]
bors retry

**Pull request merged**
