### PR TITLE
feat: add tasklist-listview template and follow up entity template classes

### LINKED ISSUE #21845: [Root Task] Search Task by Variable
```[tasklist]
### Tasks
- [ ] https://github.com/camunda/camunda/issues/21843
- [ ] https://github.com/camunda/camunda/issues/21846
- [ ] https://github.com/camunda/camunda/issues/21848
- [ ] https://github.com/camunda/camunda/issues/21849
```

### PR DESCRIPTION
**Pull request by nathansandi**
## Description

- Create tasklist-list-view template for ES/OS
- Create TasklistListView entity
- Create TasklistListViewTemplate Class

This contains
- Simple process flow node to set as parent
- Variable data
- User Task Data (As it is made for tasklist-task) but considering only V2 Necessary data (the same field names were used as tasklist-task, considering hybrid approach in 8.7 (to use both `tasklist-task` and `tasklist-listview` to retrieve task when variables are included in search) in the future. 

The importers will be created in a follow up Pull Request 

**Validation:**

image

## Related issues

closes #https://github.com/camunda/camunda/issues/21843

### CODE REVIEW

**Review by houssain-barouni — COMMENTED** [review]
Hi @nathansandi,

❓ I am wondering if we can split `TasklistListViewEntity` into 3 classes (Task, Variable and Process) like it is done in [Operate](https://github.com/camunda/camunda/tree/main/operate/schema/src/main/java/io/camunda/operate/entities/listview) and create a `ListViewJoinRelation` class to define the relations between the classes. 
This should improve the separation of concerns and can make the code easier to manage and extend.

**Comment by nathansandi** [comment]
> Hi @nathansandi,
> 
> ❓ I am wondering if we can split `TasklistListViewEntity` into 3 classes (Task, Variable and Process) like it is done in [Operate](https://github.com/camunda/camunda/tree/main/operate/schema/src/main/java/io/camunda/operate/entities/listview) and create a `ListViewJoinRelation` class to define the relations between the classes. This should improve the separation of concerns and can make the code easier to manage and extend.

Hello @houssain-barouni 
I have studied this possibility, but it would create confusion with the existent classes, and the fact we have V1 data from those classes, I believe when we do not have v1 inconsistencies and differences, this would be possible, because we wont have Task data with v1 fields (like formEmbedded).

If the fields are exactly the same, this would be possible, but it is not the case. We can split this in the further, once we have consistency over the classes. For now, to avoid this complexity over edge cases, and increase the complexity, I would prefer to keep as is (it is not a problem revisit this in the future)

**Comment by houssain-barouni** [comment]
> Hello @houssain-barouni, thanks for bringing this up.
> 
> I have considered this approach before, but it might introduce confusion given the existing classes and the differences in fields between versions. Currently, we have some fields in V1 that won’t be present in the ListView for V2 (e.g., formEmbedded, formVersion). Splitting the entity now could lead to having two TaskEntity classes, which could increase complexity, especially with edge cases. Also, another point the Entities are used over SchemaValidators, and the fields must be the same (not more because the dynamic is set as strict)
> 
> However, once we achieve consistency across these classes and no longer support Job Worker, this refactoring could become more feasible and beneficial. For now, I believe it’s best to keep the current structure to avoid unnecessary complexity. That said, I’m open to revisiting this idea in the future when the conditions are more favorable.

What about the V2 stack? Are you planning to create new entity classes under `camunda-service` module?

**Comment by nathansandi** [comment]
> > Hello @houssain-barouni, thanks for bringing this up.
> > I have considered this approach before, but it might introduce confusion given the existing classes and the differences in fields between versions. Currently, we have some fields in V1 that won’t be present in the ListView for V2 (e.g., formEmbedded, formVersion). Splitting the entity now could lead to having two TaskEntity classes, which could increase complexity, especially with edge cases. Also, another point the Entities are used over SchemaValidators, and the fields must be the same (not more because the dynamic is set as strict)
> > However, once we achieve consistency across these classes and no longer support Job Worker, this refactoring could become more feasible and beneficial. For now, I believe it’s best to keep the current structure to avoid unnecessary complexity. That said, I’m open to revisiting this idea in the future when the conditions are more favorable.
> 
> What about the V2 stack? Are you planning to create new entity classes under `camunda-service` module?

No, I am going to reuse the existent ones already created there (UserTaskEntity) in V2. Only the query will be updated (it will be clear when the PR is there)

**Comment by houssain-barouni** [comment]
> Hey @houssain-barouni No, I am going to reuse the existent ones already created there (UserTaskEntity) in V2, which is already with the fields in V2. Only the query will be updated (it will be clear when the PR is there).

Will you also reuse the existing VariableEntity ? It has different naming for the fields (example `varValue` vs `value`)

**Comment by nathansandi** [comment]
> > Hey @houssain-barouni No, I am going to reuse the existent ones already created there (UserTaskEntity) in V2, which is already with the fields in V2. Only the query will be updated (it will be clear when the PR is there).
> 
> Will you also reuse the existing VariableEntity ? It has different naming for the fields (example `varValue` vs `value`)

I have no answer for this question now, once it is not in the scope of the Search Task by Variable (We wont retrieve variables on user-task). So I wont use `VariableEntity` for this query. 
But I understand your point here, and this decision can be made on the development of Search Variables.

**Comment by nathansandi** [comment]
Hello @houssain-barouni  I have just pushed the changes as we discussed on Slack

**Review by houssain-barouni — COMMENTED** [review]
Thanks @nathansandi for the sync explanation of the unique identifier of the new entities
as discussed, we need to add the `partitionId` and `tenantId to ProcessInstance and Variable entities

**Review by houssain-barouni — APPROVED** [review]

**Pull request merged**
