### PR TITLE
[Backport stable/8.1] refactor(engine): append side-effects to writer

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Manual backport of https://github.com/camunda/zeebe/pull/11502

### CODE REVIEW

**Comment by Zelldon** [comment]
@oleschoenburg was it just a simple cherry-pick or any changes?

**Comment by oleschoenburg** [comment]
@Zelldon No, pretty much all files had merge conflicts because of the restructuring done for 8.2. The only conflicts I had to solve were import paths though.

**Review by ChrisKujawa — APPROVED** [review]
Thanks @oleschoenburg LGTM :+1:

**Pull request merged**
