### PR TITLE
chore(broker): renamed UpdateWorkflowInstancePayload to SetVariables

### LINKED ISSUE #1617: I can update payload with local semantics
With #1616, we change the behavior of the update payload command in a way that variables are propagated by default. So we need an optional parameter in the command to not propagate the variable and set/update them in the given scope locally.

AT:
* I can create new variables or update the value of existing variables in the given scope
* the variables are not propagated if they don't exist in the given scope

### PR DESCRIPTION
**Pull request by npepinpe**
- can specify local/propagating semantics when updating variables

BREAKING CHANGE:
- renames UpdateWorkflowInstancePayload to SetVariables
- renames UpdatePayloadCommand to SetVariablesCommand

### CODE REVIEW

**Comment by npepinpe** [comment]
A lot of the modifications are generated code, since I had to change the protocol.

There is a follow up issue to remove the `payload` property from the `WorkflowInstanceRecord`, and one to update the documentation after #1617.

One thing I wasn't sure was whether or not to rename the `payload` property of the request to, say, `variables` (for the clients). On one hand it makes more sense for the command, but on the other we use the payload word (and with rules on what is a "good" payload) in other places, so I kept it, but open to discussion.

I also did minor maintenance on the go projects since we generate code from binaries (`mockgen` and `protoc-gen-go`), which were not vendored with our dependencies, leading to errors when used by the vendored libraries.

**Comment by Zelldon** [comment]
> One thing I wasn't sure was whether or not to rename the `payload` property of the request to, say, `variables` (for the clients). On one hand it makes more sense for the command, but on the other we use the payload word (and with rules on what is a "good" payload) in other places, so I kept it, but open to discussion.

I would like to have then variables instead of payload, I would argue that it is more consistent .
Furthermore ` Sets the payload containing the new values for the given variables.` sounds a bit weird

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a584acb4821e4622baf0fc2d5f89b9e888104acd
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by npepinpe** [comment]
See latest changes, renamed `payload` to `variables` where relevant.

**Comment by Zelldon** [comment]
Sorry mistakenly pressed the button :see_no_evil: 

Don't want to be nitpicky but maybe you can also fix the java docs? :sweat_smile:

**Comment by npepinpe** [comment]
Created a follow up issue to rename payload #2086

**Review by ChrisKujawa — APPROVED** [review]

**Pull request merged**
