### PR TITLE
chore(broker): create services related to leader role together

### LINKED ISSUE #3274: AsyncSnapshotDirector is not removed cleanly on failover
**Describe the bug**
It often happens on multiple fail overs in shorter time period that the AsyncSnapshotDirector can't be removed. If the node becomes leader again it can't reinstall the service since it still exist. The service has dead references now of already closed databases, processors and exporters. It also happens that the director triggers even if the node is follower for that partition, since it haven't been removed.

Related issues #3257, #3211 

This causes probably also some of the SIGSEG we had in the past.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

- Create stream processor services and exporter services together with other leader services. This ensures that the services are also removed atomically. 

## Related issues

closes #3274 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by npepinpe** [comment]
Is the `ExporterManagerTest` flaky or did we break it with these changes? :thinking:

**Comment by deepthidevaki** [comment]
Not flaky. I broke it.

**Review by npepinpe — CHANGES_REQUESTED** [review]
Looks good, the only thing is I have a failing test in `ExporterManagerPartitionTest#shouldRunExporterForEveryPartition`

EDIT: Ah, just saw your comment, sorry :sweat_smile:

**Comment by deepthidevaki** [comment]
@npepinpe fixed it.

**Review by npepinpe — APPROVED** [review]
:+1:

**Pull request merged**
