### PR TITLE
Use read lock on opening reader

### LINKED ISSUE #7846: StreamProcessor fail on follower because segment not open
**Describe the bug**

While starting StreamProcessor for the Follower role, a new snapshot was received and it deleted the segments. This caused recovery to fail because there is no reader exists. No reader exists because creationg of logStreamReader failed due to segment not open.

```
exception: "java.lang.IllegalStateException: Segment not open
	at com.google.common.base.Preconditions.checkState(Preconditions.java:510) ~[guava-30.1.1-jre.jar:?]
	at io.camunda.zeebe.journal.file.JournalSegment.checkOpen(JournalSegment.java:176) ~[zeebe-journal-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.journal.file.JournalSegment.createReader(JournalSegment.java:147) ~[zeebe-journal-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentedJournalReader.initialize(SegmentedJournalReader.java:39) ~[zeebe-journal-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentedJournalReader.<init>(SegmentedJournalReader.java:33) ~[zeebe-journal-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.journal.file.SegmentedJournal.openReader(SegmentedJournal.java:208) ~[zeebe-journal-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.raft.storage.log.RaftLog.openCommittedReader(RaftLog.java:73) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.atomix.raft.partition.impl.RaftPartitionServer.openReader(RaftPartitionServer.java:211) ~[zeebe-atomix-cluster-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.storage.atomix.AtomixLogStorage.newReader(AtomixLogStorage.java:43) ~[zeebe-logstreams-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.storage.atomix.AtomixLogStorage.newReader(AtomixLogStorage.java:24) ~[zeebe-logstreams-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.createLogStreamReader(LogStreamImpl.java:196) ~[zeebe-logstreams-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
```

```
exception: "java.lang.NullPointerException: null
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:272) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:116) ~[zeebe-workflow-engine-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
```

```
D 2021-09-17T07:32:37.268858Z Broker-1-ZeebePartition-2 Partition 2 closed all previous open resources, before transitioning.  Broker-1-ZeebePartition-2
D 2021-09-17T07:32:37.269488Z Broker-1-ZeebePartition-2 Available snapshot: FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/2620432-4-6923500-6815002, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/2620432-4-6923500-6815002.checksum, checksum=2252972254, metadata=FileBasedSnapshotMetadata{index=2620432, term=4, processedPosition=6923500, exporterPosition=6815002}}  Broker-1-ZeebePartition-2
I 2021-09-17T07:32:37.272209Z RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Started receiving new snapshot FileBasedReceivedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/pending/2951306-4-7664936-7664215-2, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@7ec36f15, metadata=FileBasedSnapshotMetadata{index=2951306, term=4, processedPosition=7664936, exporterPosition=7664215}} from 2  
D 2021-09-17T07:32:37.359536Z Broker-1-ZeebePartition-2 Opened database from '/usr/local/zeebe/data/raft-partition/partitions/2/runtime'.  Broker-1-ZeebePartition-2
D 2021-09-17T07:32:37.359810Z Broker-1-ZeebePartition-2 Recovered state from snapshot 'FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/2620432-4-6923500-6815002, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/2620432-4-6923500-6815002.checksum, checksum=2252972254, metadata=FileBasedSnapshotMetadata{index=2620432, term=4, processedPosition=6923500, exporterPosition=6815002}}'  Broker-1-ZeebePartition-2
I 2021-09-17T07:32:37.360347Z Broker-1-ZeebePartition-2 Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@3911c542)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@5d5d0585, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@71cf2e27, configuration: Configuration(false)]  Broker-1-ZeebePartition-2
I 2021-09-17T07:32:37.375083Z Broker-1-SnapshotStore-2 Committed new snapshot 2951306-4-7664936-7664215  Broker-1-SnapshotStore-2
D 2021-09-17T07:32:37.375777Z Broker-1-SnapshotStore-2 Deleting previous snapshot 2620432-4-6923500-6815002  Broker-1-SnapshotStore-2
D 2021-09-17T07:32:37.377031Z Broker-1-DeletionService-2 Scheduling log compaction up to index 2951306  Broker-1-DeletionService-2
I 2021-09-17T07:32:37.377103Z RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Committed snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/2951306-4-7664936-7664215, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/2951306-4-7664936-7664215.checksum, checksum=2948084336, metadata=FileBasedSnapshotMetadata{index=2951306, term=4, processedPosition=7664936, exporterPosition=7664215}}  
I 2021-09-17T07:32:37.377450Z RaftServer{raft-partition-partition-2}{role=FOLLOWER} - Delete existing log (lastIndex '2945304') and replace with received snapshot (index '2951306')  
D 2021-09-17T07:32:37.431079Z Broker-1-LogStream-2 Configured log appender back pressure at partition 2 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled  Broker-1-LogStream-2
E 2021-09-17T07:32:37.434214Z Broker-1-LogStream-2 Uncaught exception in 'Broker-1-LogStream-2' in phase 'STARTED'. Continuing with next job.  Broker-1-LogStream-2
E 2021-09-17T07:32:37.435775Z Broker-1-StreamProcessor-2 Unexpected error on retrieving reader from log stream.  Broker-1-StreamProcessor-2
D 2021-09-17T07:32:37.436909Z Broker-1-StreamProcessor-2 Recovering state of partition 2 from snapshot  Broker-1-StreamProcessor-2
I 2021-09-17T07:32:37.438052Z Broker-1-StreamProcessor-2 Engine created. [value-mapper: CompositeValueMapper(List(io.camunda.zeebe.el.impl.feel.MessagePackValueMapper@6fedcc36)), function-provider: io.camunda.zeebe.el.impl.feel.FeelFunctionProvider@2dc791d3, clock: io.camunda.zeebe.el.impl.ZeebeFeelEngineClock@447e7df5, configuration: Configuration(false)]  Broker-1-StreamProcessor-2
E 2021-09-17T07:32:37.439470Z Broker-1-StreamProcessor-2 Actor Broker-1-StreamProcessor-2 failed in phase STARTED.  Broker-1-StreamProcessor-2
E 2021-09-17T07:32:37.440469Z Broker-1-StreamProcessor-2 Actor Broker-1-StreamProcessor-2 failed in phase FAILED.  Broker-1-StreamProcessor-2
E 2021-09-17T07:32:37.440937Z Broker-1-StreamProcessor-2 Unexpected error occurred in task Broker-1-StreamProcessor-2 ACTIVE phase: FAILED  Broker-1-StreamProcessor-2
```

I expect it to recover from it when a new transition happened due to installation of new snapshot. But it seems it did not happen immediately. I see a new transition only after ~5 mins. This was probably triggered by another transition.

**To Reproduce**

Start a cluster. Disconnect brokers randomly. This might reproduce the error.

```
disconnectRandomPod() {
  namespace=$1
  echo "Disconnect random broker in namespace $namespace"
  pod=$(kubectl \
    --namespace "$namespace" \
    -o 'jsonpath={.items[*].metadata.name}' \
    get pods -l "app.kubernetes.io/component=broker" | \
      tr " " "\n" | \
      shuf | \
      head -n 1)

   kubectl --namespace "$namespace" exec $pod -- tc qdisc replace dev eth0 root netem loss 100%
   sleep 10
   kubectl --namespace "$namespace" exec $pod -- tc qdisc replace dev eth0 root netem loss 0%
}

while true; do
  disconnectRandomPod $namespace
  sleep 400
done

```

**Expected behavior**

**Log/Stacktrace**

[Logs](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-17T07%3A35%3A22.505425000Z&dateRangeStart=2021-09-17T06%3A33%3A07.439Z&dateRangeEnd=2021-09-17T08%3A33%3A07.439Z&project=zeebe-io&minLogLevel=0&customFacets=jsonPayload.context.actor-name&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.pod_name%3D%22dd-old-transition-zeebe-1%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.container_name%3D%22zeebe-cluster-helm%22%0Aresource.labels.namespace_name%3D%22dd-old-transition%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Atimestamp%3D%222021-09-17T07%3A32%3A37.439470000Z%22%0AinsertId%3D%22khil4o3c6z0l13qt%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-17T07%3A40%3A30.174707000Z)

**Environment:**
Zeebe Version : 1.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Test tries to reset journal concurrently with opening an reader and fails.
```
Exception in thread Thread-1 java.lang.IllegalStateException: Segment not open
	at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
	at io.camunda.zeebe.journal.file.JournalSegment.checkOpen(JournalSegment.java:176)
	at io.camunda.zeebe.journal.file.JournalSegment.createReader(JournalSegment.java:147)
	at io.camunda.zeebe.journal.file.SegmentedJournalReader.initialize(SegmentedJournalReader.java:39)
	at io.camunda.zeebe.journal.file.SegmentedJournalReader.<init>(SegmentedJournalReader.java:33)
	at io.camunda.zeebe.journal.file.SegmentedJournal.openReader(SegmentedJournal.java:209)
	at io.camunda.zeebe.journal.file.SegmentedJournalTest.lambda(SegmentedJournalTest.java:503)
	at java.base/java.lang.Thread.run(Thread.java:829)

org.opentest4j.AssertionFailedError:
Expecting value to be true but was false
Expected :true
Actual   :false
```

After adding locks test is green.

## Related issues

closes #7846 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
Great :rocket: Thanks.

**Comment by Zelldon** [comment]
bors cancel

**Pull request merged**
