### PR TITLE
Adjust medic dashboard to new load

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Mixed benchmark load will be reduced to 15 PI/s. This PR adjusts the thresholds in the medic dashboard.

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Thanks again :)

bors merge

**Comment by Zelldon** [comment]
Thanks to you @oleschoenburg for thinking about it 🙇🏼

**Comment by Zelldon** [comment]
I hate to use bors for such changes 😅

**Pull request merged**
