### PR TITLE
fix(broker): reject deployments with duplicate process ids

### LINKED ISSUE #546: Duplicate Workflows in Deployment create workflows with the same process id and version
Deploying a duplicate workflows in one deployment will cause a problem since different workflows can be deploy with the same bpmn process id and version. See the following test case.

```java
@Test
    public void shouldCreateDeploymentWithMultipleResources()
    {
        // given
        final WorkflowDefinition definition1 = Bpmn.createExecutableWorkflow("process1").startEvent().done();
        final WorkflowDefinition definition2 = Bpmn.createExecutableWorkflow("process2").startEvent().done();
        final WorkflowDefinition definition3 = Bpmn.createExecutableWorkflow("process2").startEvent().serviceTask().taskType("j").taskHeader("k", "v").done().done();

        final List<Map<String, Object>> resources = Arrays.asList(deploymentResource(definition1, "process1.bpmn"),
                                                                  deploymentResource(definition2, "process2.bpmn"),
                                                                  deploymentResource(definition3, "process2.bpmn")
        );

        // when
        final ExecuteCommandResponse resp = apiRule.createCmdRequest()
                .partitionId(Protocol.SYSTEM_PARTITION)
                .eventType(EventType.DEPLOYMENT_EVENT)
                .command()
                    .put(PROP_STATE, "CREATE_DEPLOYMENT")
                    .put("topicName", ClientApiRule.DEFAULT_TOPIC_NAME)
                    .put("resources", resources)
                .done()
                .sendAndAwait();

        // then
        assertThat(resp.key()).isGreaterThanOrEqualTo(0L);
        assertThat(resp.getEvent()).containsEntry(PROP_STATE, "DEPLOYMENT_CREATED");

        final List<SubscribedEvent> workflowEvents = apiRule.topic().receiveEvents(workflowEvents("CREATED"))
                .limit(3)
                .collect(toList());

        assertThat(workflowEvents)
            .extracting(s -> s.event().get(PROP_WORKFLOW_BPMN_PROCESS_ID))
            .contains("process1", "process2", "process2");
    }


        assertThat(workflowEvents)
            .extracting(s -> s.event().get(PROP_WORKFLOW_VERSION))
            .contains(1, 1, 1);

```

One solution would be to increment the  version.

### PR DESCRIPTION
**Pull request by miguelpires**
The missing null check in `isDuplicateOfLatest` was the reason why a duplicate process id would cause an error. With that change alone the duplicate behavior would simply cause the version id to increment. The remaining code implements the filtration of duplicates.

closes #546

### CODE REVIEW

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Looks good :+1: 

On suggestion I have is to change the `transformResource` to something like the following, such that we do not need to check for duplicates when we already know that it is invalid.
```java
  private boolean transformResource(
      final DeploymentRecord deploymentEvent,
      final StringBuilder errors,
      final DeploymentResource deploymentResource) {
    boolean success = false;
    final String resourceName = deploymentResource.getResourceName();

    try {
      final BpmnModelInstance definition = readWorkflowDefinition(deploymentResource);
      final String validationError = validator.validate(definition);

      if (validationError == null) {
        final String bpmnIdDuplicateError = checkForDuplicateBpmnId(definition, resourceName);

        if (bpmnIdDuplicateError == null) {
          transformWorkflowResource(deploymentEvent, deploymentResource, definition);
          success = true;
        } else {
          errors.append("\n").append(bpmnIdDuplicateError);
        }
      } else {
        errors.append("\n'").append(resourceName).append("': ").append(validationError);
      }
    } catch (RuntimeException e) {
      LOG.error("Unexpected error while processing resource '{}'", resourceName, e);
      errors.append("\n'").append(resourceName).append("': ").append(e.getMessage());
    }
    return success;
  }
```

What do you think?

**Comment by MiguelPires** [comment]
Totally agree. I made a new commit with that suggestion

**Review by ChrisKujawa — APPROVED** [review]

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
