### PR TITLE
fix: don't replicate snapshot if member already has the latest snapshot

### LINKED ISSUE #9820: Leaders with no log before snapshot get stuck in a loop when replicating the snapshot
**Describe the bug**

When a leader's first log entry is the next entry after the snapshot, the leader will get stuck in a snapshot replication loop, sending the same snapshot over and over again. The follower won't receive regular appends and will not catch up to the leader.

**To Reproduce**

Given this scenario:
Leader has a snapshot with index X, and a log that starts at index X+1.

After finishing snapshot replication to a member, the members position is reset to the snapshot position X + 1. That causes a seek for the previous position, X, followed by a read of the next entry, X+1. The position X does not exist (log starts with X+1) which means that the member context has no current entry and thus currentIndex = 0. This means that `shouldReplicateSnapshot` will decide to replicate the snapshot again, closing the loop.

**Expected behavior**

After successful snapshot replication, regular event replication should continue and the same snapshot shouldn't be sent over and over again. 

This is a valid scenario that has worked previously but we removed one condition from `shouldReplicateSnapshot` that prevented repeated snapshot replication: https://github.com/camunda/zeebe/commit/6ffc0cb40ad355daf2b97882aa4db35765f41382

```java
if (member.getSnapshotIndex() >= persistedSnapshot.getIndex()) {
  return false;
}
```

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

This fixes an issue where a leader becomes stuck in a snapshot replication loop if the leader's log starts right after the snapshot index. After successfully installing a snapshot, the leader attempts to seek back to the log entry before the snapshot which will fail if the log starts after the snapshot. When that happens, the member context has no current entry until the next append request is send so we must not use the current entry of the member to decide between sending a snapshot or not. Instead, we can bail out and decide not to send a snapshot when the member has the latest snapshot.

## Related issues

closes #9820 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

If I understand correctly, the leader will keep track of each member's position to know which entry to send to them next. When we've replicated a snapshot at X, then we reset the member's context to X+1 (which means pointing at X such that the next entry is X+1). If there's no X, then we set the member's current index to 0? It seems a little strange to me, but I guess we really cannot set it to X :smile: Or would it be "OK" for the context to have X, as we treat the snapshot as that first entry? :thought_balloon: I wonder if it would make sense to have a different view in this context.

At any rate, just thinking out loud. Good catch!

**Comment by oleschoenburg** [comment]
Yep, that's summarized well I think :+1: 
I'd rather fix it differently (similar to how you described it) too. We could either: 
* track the current index separately (set it whenever we set currentEntry but also when installing a snapshot)
* Have currentEntry be more flexible, so that it can either be a `IndexRaftLogEntry` or a snapshot.

Either way seems like they require a lot of changes in `RaftMemberContext` so I'd rather fix this by just re-adding this check. The check makes sense anyway, we never want to re-install a snapshot.

**Comment by oleschoenburg** [comment]
bors retry

**Comment by korthout** [comment]
@oleschoenburg I think this should've been added to the [release notes](https://drive.google.com/drive/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape).

**Pull request merged**
