### PR TITLE
Add Broadcast Signal RPC

### LINKED ISSUE #11878: Create a new gRPC API for signal broadcast command
### Description
Introduce new broadcast signal RPC in gateway-protocol, this includes the extending of the gRPC Protobuf definition and the handling of the requests and responses. 

Example api:
```rpc
message BroadcastSignalRequest {
  // The name of the signal
  string signalName = 1;

  // JSON document that will instantiate the variables for the root variable scope of the
  // process instance; it must be a JSON object, as variables will be mapped in a
  // key-value fashion. e.g. { "a": 1, "b": 2 } will create two variables, named "a" and
  // "b" respectively, with their associated values. [{ "a": 1, "b": 2 }] would not be a
  // valid argument, as the root of the JSON document is an array and not an object.
  string variables = 2;
}

message BroadcastSignalResponse {}
```

### PR DESCRIPTION
**Pull request by lzgabel**
## Description
This PR introduces new broadcast signal RPC. It includes the extension of the gateway protocol and the mapping of the request and the response.

## Related issues
closes #11878

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by lzgabel** [comment]
Hi @korthout. Please take a moment to check this out. 🙇

**Review by korthout — CHANGES_REQUESTED** [review]
Again great stuff @lzgabel 💖 

I have a few change requests, please have a look 🙇

**Comment by lzgabel** [comment]
Hi @korthout. I have applied your suggestions and squashed the commits. Please check this out. :bow:

**Review by korthout — APPROVED** [review]
Great work @lzgabel 👏 

LGTM 👍 

bors merge

**Pull request merged**
