### PR TITLE
[BACKPORT 0.24] Truncate follower log on restart

### LINKED ISSUE #4587: Follower should reset his log on restart when it has received a newer snapshot
**Describe the bug**
Based on the fix of https://github.com/zeebe-io/zeebe/pull/4451 we introduced logic where the follower deletes the log when he receives an snapshot with higher index then the last entry.

The problem with this is that it might fail in between, which means we still have a small chance that this happens, because of node crash.

**To Reproduce**
We need a slow follower, which receives a regular snapshot. Before he is able to delete the log the node needs to be shutdown. On start the follower has the old log and the newer snapshot.

**Expected behavior**
The follower detects it has an newer snapshot and resets his log based on that.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Backports #4900

## Related issues

closes #4587

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release annoncement

### CODE REVIEW

**Comment by Zelldon** [comment]
@npepinpe do you want that in 0.24.1 or in 0.24.2 ?

**Comment by npepinpe** [comment]
0.24.1 will only contain the fix to make sure we can do the rolling upgrade - all other fixes go into 0.24.2. This is mostly a cautious move to avoid adding more things in 0.24.0. We'll release 0.24.2 next week :slightly_smiling_face:

**Comment by Zelldon** [comment]
Sounds good 👍

**Review by npepinpe — APPROVED** [review]

**Pull request merged**
