### PR TITLE
refactor: decouple CamundaSecurityConfiguration from REST enabled

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Review by remcowesterhoud — APPROVED** [review]
Looks good to me @houssain-barouni 🚀

**Comment by remcowesterhoud** [comment]
How did that merge so fast 😲 Did it not go hrough the merge queue or something?

**Comment by houssain-barouni** [comment]
> How did that merge so fast 😲 Did it not go through the merge queue or something?

I have a premium github account 😆 

the destination branch is your branch `[25373-align-auth-config](https://github.com/camunda/camunda/tree/25373-align-auth-config)` and is not protected by merge queue rules

**Comment by remcowesterhoud** [comment]
Ooh right. I completely missed that 🤦

**Pull request merged**
