### PR TITLE
Fix protobuf code generation

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Fixes the process for generating protobuf Go code. Also regenerates the protobuf code it has changed substantially since with protobuf 1.4 and this caused some confusion in another PR. The test changes are due to new protobuf format, which introduced some unexported fields which caused the comparison to fail.

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
Looks good, what were the gocompat changes? It's pretty much unreadable since it's a single line.

**Comment by MiguelPires** [comment]
There were fields used internally (by protobuf) that were removed or replaced by other unexported fields, here's a sample:

```
[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_Size MethodDeleted
[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".ThrowErrorRequest.XXX_DiscardUnknown MethodDeleted
[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_NoUnkeyedLiteral FieldDeleted
[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_unrecognized FieldDeleted
[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_sizecache FieldDeleted
[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_Unmarshal MethodDeleted
[2020-09-17T06:03:32.681Z] "github.com/zeebe-io/zeebe/clients/go/pkg/pb".BrokerInfo.XXX_Marshal MethodDeleted
```

I scanned it briefly to check that these were the only changes but I can reproduce the whole log and paste it here so you can verify, if you want. It's technically a breaking change (protobuf reserves the right to do this to fix certain issues https://github.com/golang/protobuf#compatibility) but it shouldn't impact users, since there's no reason why they would be using this

**Review by npepinpe — APPROVED** [review]
No, all good, I believe you - just asking :slightly_smiling_face:

**Pull request merged**
