### PR TITLE
Hard reject resolving incident with missing failed command

### LINKED ISSUE #7127: A rejected incident resolve command was simultaneously accepted
**Describe the bug**
Incidents for which the failed command can longer be found in the state can be resolved and have the resolve command rejected at the same time. We should never reject a command and simultaneously accept it as well.

Generally, this situation should not happen. For example, this situation would occur when an incident's associated element instance has been deleted from the state, but that should never be the case. However, we've seen this situation occur for specific bugs. For example, this happened in https://github.com/camunda-cloud/zeebe/issues/6952#issuecomment-843253325, for which a solution was already provided. 

Other still unknown or not yet present bugs, may in the future lead to a similar situation. Even in the case of bugs, I'd expect commands that fail in some way should be rejected and not also accepted.

**To Reproduce**

I've provided an example failing test case that reproduces the problem.

<details><summary>Failing Testcase</summary>
<p>

Just create this java test case class in the test sources of the engine project under `io.camunda.zeebe.engine.processing.incident`.

```java
package io.camunda.zeebe.engine.processing.incident;

import static org.assertj.core.api.Assertions.assertThat;

import io.camunda.zeebe.engine.util.EngineRule;
import io.camunda.zeebe.model.bpmn.Bpmn;
import io.camunda.zeebe.protocol.record.intent.IncidentIntent;
import io.camunda.zeebe.test.util.record.RecordingExporter;
import io.camunda.zeebe.test.util.record.RecordingExporterTestWatcher;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;

public final class IncidentRejectionTest {

  @ClassRule public static final EngineRule ENGINE = EngineRule.singlePartition();

  @Rule
  public final RecordingExporterTestWatcher exporterWatcher = new RecordingExporterTestWatcher();

  @Test
  public void shouldNotRejectAndAlsoResolveAnIncident() {
    // given a deployed process with a service task with an output expression
    ENGINE
        .deployment()
        .withXmlResource(
            Bpmn.createExecutableProcess("process-incident-on-leaving-task")
                .startEvent()
                .serviceTask(
                    "task",
                    b -> b.zeebeJobType("task").zeebeInputExpression("unknown_var", "output"))
                .done())
        .deploy();

    // and an instance of that process is created without a variable for the output expression
    final var processInstanceKey =
        ENGINE.processInstance().ofBpmnProcessId("process-incident-on-leaving-task").create();

    // and an incident created
    final var incident =
        RecordingExporter.incidentRecords(IncidentIntent.CREATED)
            .withProcessInstanceKey(processInstanceKey)
            .getFirst();

    // and the associated element instance is accidentally removed from state
    ENGINE
        .getZeebeState()
        .getElementInstanceState()
        .removeInstance(incident.getValue().getElementInstanceKey());

    // when we try to resolve the incident
    final var resolveResponse =
        ENGINE.incident().ofInstance(processInstanceKey).withKey(incident.getKey()).resolve();

    assertThat(
            RecordingExporter.incidentRecords(IncidentIntent.RESOLVE)
                .onlyCommandRejections()
                .withRecordKey(incident.getKey())
                .exists())
        .describedAs("then the resolve command is rejected")
        .isTrue();

    assertThat(
            RecordingExporter.incidentRecords(IncidentIntent.RESOLVED)
                .withRecordKey(incident.getKey())
                .exists())
        .describedAs("and the incident is not resolved")
        .isFalse();
  }
}
```

</p>
</details>

**Expected behavior**

The incident resolve command is rejected and the incident is not resolved.

**Environment:**
 - Zeebe Version: 1.0.0

### PR DESCRIPTION
**Pull request by korthout**
## Description

Throw an exception when we try to resolve an incident, but cannot find the failed command. This is an unrecoverable situation for that process instance.

The exception helps visibility of the problem to engineers (it pops up in the logs). The exception leads to a command rejection which is communicated to the client that sent the resolve command.

An alternative solution was to accept the resolved and recreate a new incident. This idea was challenged during the review.

Another solution was blacklisting the instance, which would stop all processing on the instance. This blocks more than necessary.

## Related issues

closes #7127

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by saig0 — COMMENTED** [review]
I agree that it makes no sense to reject the command after accepting it :smile: 

However, creating a new incident is maybe not the best option. Currently, we run into this case if the element instance of the incident is not in the state (anymore) or if the intent of the element instance is unexpected. 

I don't see that we could recover from both cases. And they should only occur if there is a bug in the engine.

I suggest writing a log statement to indicate the failure but don't create a new incident.

**Comment by korthout** [comment]
@saig0 sorry for the late reply, but I had to think about this one a bit. I want to propose a third option: blacklisting the instance.

> I suggest writing a log statement to indicate the failure but don't create a new incident.

I wondered if this would be less visible to users than an incident. Their instance would not make progress, but they don't see why. Unless they happen to look at the logs of the broker. Logging it at ERROR level has one extra advantage because it would alert us for CCSaaS users running into this problem. The recreated incident would just keep re-appearing, which also doesn't tell the user much, except that somehow they are unable to completely resolve this incident. 

It would be great if we could inform our users of an actual error in a process instance. At some point, we've discussed that we want to re-imagine the process instance blacklisting, and this might be part of it. So I wonder whether we should just throw an exception and blacklist the instance. Currently, that leaves the same visibility as 'just logging' and I assume we log blacklisting situations at error level anyways. It would then also allow to deal with these instances in an improved way in the future. Lastly, there was also a proposal to add metrics to the number of blacklisted instances. Which would further increase the visibility. 

How do you feel about that idea?

**Comment by saig0** [comment]
That is a valid point. In general, I don't like to blacklist the instance because it doesn't allow to continue processing on this instance. On the other hand, raising an incident doesn't fit well because it can't be solved by a user.

In this case, I agree that we can throw an exception to indicate the inconsistent state. It aligns with other behaviors.

**Review by saig0 — APPROVED** [review]
Looks good :cookie:

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
bors retry

**Pull request merged**
