### PR TITLE
Remove compensation subscription when terminating subprocess 

### LINKED ISSUE #16808: Remove compensation subscription when terminating subprocess
## Description

When an activity with a compensation boundary event is completed, the process instance creates a new compensation subscription. When the process instance completes the compensation handler, it completes the subscription and removes it from the state. If the compensation is not triggered then the process instance removes the subscription at the completion/termination of the instance.

If the activity is inside an embedded subprocess and the subprocess is interrupted then the compensation handler can't be invoked anymore. In this case, we should remove the subscription of the activity to clean the state. This can be relevant to long-living processes.  

- On terminating a subprocess, delete all compensation subscriptions in this scope (recursively) by writing a `DELETED` event   

Screenshot from 2024-03-11 10-47-39

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

If a subprocess is terminated, all the compensation subscriptions inside the subprocess scope must be deleted from the state

## Related issues

closes #16808 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by saig0 — CHANGES_REQUESTED** [review]
@nicpuppa very good. :rocket: 

:x: For the deletion, we should consider one more case: a multi-instance subprocess with inner compensation handlers. Assuming that 2 of 3 instances are completed and a boundary event of the multi-instance is triggered, then we should delete the compensation subscriptions of the 2 completed instances.

**Comment by nicpuppa** [comment]
Hey @saig0 I added a test case to verify the behaviour of multi instance subprocesses, do you think it is enough ?

**Review by saig0 — APPROVED** [review]
@nicpuppa LTGM. :rocket: 

The commit-linter is not happy about the commit messages. Please have a look.

**Comment by nicpuppa** [comment]
> The commit-linter is not happy about the commit messages. Please have a look.

No more scope in the commit message ? When this changed @megglos @korthout ?

**Comment by korthout** [comment]
@nicpuppa It was changed recently as a result of a [Zeebe Teams Sync](https://docs.google.com/document/d/1TO4Lq0trdFhOhMZwK0aPOMg9_smJu-CW4NUPz4qNXpY/edit#heading=h.ufyfh0qjaa4i) discussion:
- https://github.com/camunda/zeebe/pull/16712

**Comment by nicpuppa** [comment]
> @nicpuppa It was changed recently as a result of a [Zeebe Teams Sync](https://docs.google.com/document/d/1TO4Lq0trdFhOhMZwK0aPOMg9_smJu-CW4NUPz4qNXpY/edit#heading=h.ufyfh0qjaa4i) discussion:

Many thanks, I missed it 🙏

**Pull request merged**
