### PR TITLE
feat(clients/go): add grpc dial options in client constructor

### LINKED ISSUE #4561: Pass gRPC Dial Options to Go Client
**Is your feature request related to a problem? Please describe.**
We want to add custom grpc interceptors when using the go client.

**Describe the solution you'd like**
The go client constructor is variadic and accepts  `...grpc.DialOption` as second argument. These   options are then used when the client instantiates the grpc connection. This change would not be breaking as the constructor would be variadic.

**Describe alternatives you've considered**
Currently, I dont have considered alternatives. Please feel free to discuss them here.

### PR DESCRIPTION
**Pull request by zeromberto**
## Description
Add a parameter in client constructor to pass grpc dial options to the connection instantiation.

## Related issues
closes #4561 

## Pull Request Checklist
- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] ~~If submitting code, please run `mvn clean install -DskipTests` locally before committing~~ (no java code changes)

### CODE REVIEW

**Comment by npepinpe** [comment]
Hi, thanks for the submission! As there's no related issue, what is the problem you're trying to solve here? I have some idea but I'd like to hear it from you :slightly_smiling_face:

**Comment by zeromberto** [comment]
Hi, I added the issue: #4561 
What do you think @npepinpe ?

**Comment by MiguelPires** [comment]
Hi @zeromberto, thanks for submitting this. One small thing, we're using a ClientConfig struct to configure the client, so it'd be nice if we were consistent and used the same here.

**Review by miguelpires — APPROVED** [review]
Thanks for your contribution @zeromberto

**Pull request merged**
