### PR TITLE
Unhandled error incident on job can be resolved

### LINKED ISSUE #6000: I can retry a job if an error was thrown but not caught
**Is your feature request related to a problem? Please describe.**
A job worker can throw an error to indicate that a business error occurred during the processing of the job. If the error is not caught in the workflow (e.g. by an error boundary event) then an incident is raising. 

Currently, this incident can not be resolved. If the incident is marked as resolved then a new incident similar to the previous one is reached. 

Internally, it tries to throw the error event again. Since the workflow is not changed, it will create just a new incident.

**Describe the solution you'd like**
Fix the business error by adding/modifying a variable, updating/fixing the job worker, or modifying an external system. Then, mark the incident as resolved. The job worker can process the job again and produce a different result.

The behavior is similar to the case when the job is marked as failed without remaining retries.

Since the retries of the job are not decreased, it might not be necessary to set/increase the retries of the job first.

Internally, the job is marked as failed. When the incident is resolved then the job can be activated again. In the meantime, the service task stays active.

**Describe alternatives you've considered**
Stay with the current behavior. Eventually, it will be possible to modify workflows and migrate workflow instances. Using the migration, it will be possible to fix a couple of these problems.

However, some of these cases will not be covered. For example, if the job worker throws an error accidentally or using the wrong error code (e.g. a typo in the error code) then you don't want to modify your workflow to catch the wrong error. Instead, you want to fix the job worker and continue the workflow instance. 

**Additional context**
Documentation about error events: ~https://docs.zeebe.io/bpmn-workflows/error-events/error-events.html#unhandled-errors~ https://docs.camunda.io/docs/reference/bpmn-processes/error-events/error-events#unhandled-errors

The issue was raised on the [support](https://jira.camunda.com/browse/SUPPORT-9357) channel.

### PR DESCRIPTION
**Pull request by korthout**
## Description

When an error is thrown for a job and uncaught, an incident is raised. Previously, this incident could not be resolved. This PR adds support for resolving this type of incident by making the job activatable again.

Specifically, it removes the resolve incident command rejection for this incident type, and makes the job activatable when the incident is resolved.

Note that the `job.elementId` was already updated to `NO_CATCH_EVENT_FOUND` for incident's created on older versions, as well as for newly created incidents of this type. The event applier can simply reset this state through a lookup, which does not affect the backwards compatibility.

Reviewer: These changes are backwards compatible, because incidents related to jobs in error_thrown state cannot have been resolved. However, there is something to say about checking the version of the record in the event applier. Please consider whether we need this now, since the event appliers lack knowledge of a record's version at this time.

## Related issues

closes #6000 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [x] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by korthout** [comment]
Manual test:

```
zbctl --insecure activate jobs task
{
  "jobs": [
    {
      "key": "2251799813685256",
      "type": "task",
      "processInstanceKey": "2251799813685251",
      "bpmnProcessId": "benchmark",
      "processDefinitionVersion": 1,
      "processDefinitionKey": "2251799813685249",
      "elementId": "task",
      "elementInstanceKey": "2251799813685255",
      "customHeaders": "{}",
      "worker": "zbctl",
      "retries": 3,
      "deadline": "1623772428349",
      "variables": "{}"
    }
  ]
}
```

```
zbctl --insecure throwError job 2251799813685256 --errorCode=uncaught
Threw error with code 'uncaught' on job with key 2251799813685256
```

```
zbctl --insecure activate jobs task
{
  "jobs": []
}
```

```
zbctl --insecure resolve incident 2251799813685268
Resolved an incident of a process instance with key '2251799813685268'
```

```
zbctl --insecure activate jobs task
{
  "jobs": [
    {
      "key": "2251799813685256",
      "type": "task",
      "processInstanceKey": "2251799813685251",
      "bpmnProcessId": "benchmark",
      "processDefinitionVersion": 1,
      "processDefinitionKey": "2251799813685249",
      "elementId": "task",
      "elementInstanceKey": "2251799813685255",
      "customHeaders": "{}",
      "worker": "zbctl",
      "retries": 3,
      "deadline": "1623772491383",
      "variables": "{}"
    }
  ]
}
```

**Review by saig0 — APPROVED** [review]
Great job :medal_sports: 

Please look at my optional suggestion before merging.

**Comment by saig0** [comment]
@korthout please mention the change in the release announcements. This is something nice for the users :rocket:

**Comment by korthout** [comment]
bors merge

**Pull request merged**
