### PR TITLE
feat(msg-pack): merge multiple documents

### LINKED ISSUE #1320: I can merge multiple msg-pack documents
* With and without applying mappings
* Without writing intermediate result documents to a buffer

blocks #1232

### PR DESCRIPTION
**Pull request by ThorbenLindhauer**
- keeping a single intermediate representation, i.e. not multiple
  read-modify-write cycles
- I ran the benchmarks a couple of times and it seems that the performance has degraded significantly for those cases that just extract payload from a document. The reason is that the method `MsgPackTree#merge` is currently critical/limiting for overall performance and in the new implementation we always call this method. We could optimize this case as it was before (i.e. avoid `merge` when we are essentially merging with an empty document). I decided against maintaining this optimization for now as performance is not (yet) a goal and it is unclear what good/bad performance means for us (e.g. I couldn't answer the question if optimizing this would help us at all in the bigger picture).

closes #1320

### CODE REVIEW

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Looks good there a few things we need to discuss I think.
Maybe you have time in the afternoon today?

**Comment by Zelldon** [comment]
> I decided against maintaining this optimization for now as performance is not (yet) a goal and it is unclear what good/bad performance means for us (e.g. I couldn't answer the question if optimizing this would help us at all in the bigger picture).

Personally I disagree, since the main goal of our project is performance :sweat_smile: Furthermore since merging is now used really often on workflow execution it will be a limiting factor and that is why I think it is mandatory to run fast.

This are the benchmark results on develop:

```
Benchmark                                                          (keyCount)  (mappingDepthPercentage)  (mappingKeyPercentage)  (maxDepth)   Mode  Cnt       Score        Error  Units
i.z.m.m.merge.MergeBehvaiorBenchmark.overwriteDocument                    100                       N/A                     N/A         N/A  thrpt    5   38673.258 ±    784.774  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.overwriteDocument                   1000                       N/A                     N/A         N/A  thrpt    5    3630.057 ±     73.579  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.overwriteDocument                  10000                       N/A                     N/A         N/A  thrpt    5     291.673 ±     96.217  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeDefaultBehavior         100                       N/A                     N/A         N/A  thrpt    5   13363.329 ±    429.103  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeDefaultBehavior        1000                       N/A                     N/A         N/A  thrpt    5    1135.293 ±      8.519  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeDefaultBehavior       10000                       N/A                     N/A         N/A  thrpt    5      84.160 ±     18.678  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeViaMappings             100                       N/A                     N/A         N/A  thrpt    5     908.302 ±    127.489  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeViaMappings            1000                       N/A                     N/A         N/A  thrpt    5      10.375 ±      1.099  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeViaMappings           10000                       N/A                     N/A         N/A  thrpt    5       0.098 ±      0.014  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                         0                       1           0  thrpt    5  819325.602 ±  30912.420  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                         0                       1           3  thrpt    5   20239.217 ±   4980.327  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                       0.5                       1           0  thrpt    5  235835.878 ± 116256.402  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                       0.5                       1           3  thrpt    5   28393.779 ±   2696.486  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                         1                       1           0  thrpt    5  235291.482 ±  75945.985  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                         1                       1           3  thrpt    5    8377.316 ±   1211.090  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                         0                       1           0  thrpt    5  537440.608 ±  16626.289  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                         0                       1           3  thrpt    5    2966.080 ±    971.996  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                       0.5                       1           0  thrpt    5  134206.824 ±  22202.047  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                       0.5                       1           3  thrpt    5    3151.489 ±    624.909  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                         1                       1           0  thrpt    5  121614.273 ±  72896.993  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                         1                       1           3  thrpt    5    1069.840 ±    217.494  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                         0                       1           0  thrpt    5  361447.597 ±  50504.012  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                         0                       1           3  thrpt    5    9610.770 ±    796.761  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                       0.5                       1           0  thrpt    5  192245.917 ±  14840.694  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                       0.5                       1           3  thrpt    5   12193.439 ±    733.540  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                         1                       1           0  thrpt    5  201048.395 ±   8184.609  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                         1                       1           3  thrpt    5    6020.901 ±    460.134  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                         0                       1           0  thrpt    5  205584.076 ±  29114.840  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                         0                       1           3  thrpt    5    1236.297 ±    250.251  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                       0.5                       1           0  thrpt    5  106911.828 ±   1960.884  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                       0.5                       1           3  thrpt    5    1546.405 ±    109.922  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                         1                       1           0  thrpt    5  108075.413 ±   2432.816  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                         1                       1           3  thrpt    5     783.110 ±    318.826  ops/s
```

The following on the branch:

```
Benchmark                                                          (keyCount)  (mappingDepthPercentage)  (mappingKeyPercentage)  (maxDepth)   Mode  Cnt      Score       Error  Units
i.z.m.m.merge.MergeBehvaiorBenchmark.overwriteDocument                    100                       N/A                     N/A         N/A  thrpt    5  24306.205 ± 12575.376  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.overwriteDocument                   1000                       N/A                     N/A         N/A  thrpt    5   1872.825 ±   129.838  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.overwriteDocument                  10000                       N/A                     N/A         N/A  thrpt    5    160.383 ±     4.419  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeDefaultBehavior         100                       N/A                     N/A         N/A  thrpt    5  14931.813 ±  1018.382  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeDefaultBehavior        1000                       N/A                     N/A         N/A  thrpt    5    797.232 ±   252.953  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeDefaultBehavior       10000                       N/A                     N/A         N/A  thrpt    5     74.744 ±    31.541  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeViaMappings             100                       N/A                     N/A         N/A  thrpt    5    740.062 ±   415.933  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeViaMappings            1000                       N/A                     N/A         N/A  thrpt    5      8.819 ±     3.588  ops/s
i.z.m.m.merge.MergeBehvaiorBenchmark.topLevelMergeViaMappings           10000                       N/A                     N/A         N/A  thrpt    5      0.081 ±     0.011  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                         0                       1           0  thrpt    5   7985.728 ±  4040.032  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                         0                       1           3  thrpt    5   7886.193 ±  3811.555  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                       0.5                       1           0  thrpt    5   8419.565 ±  5001.693  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                       0.5                       1           3  thrpt    5   8089.661 ±  4135.013  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                         1                       1           0  thrpt    5   8518.563 ±  4300.596  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             3                         1                       1           3  thrpt    5   6254.735 ±  1606.303  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                         0                       1           0  thrpt    5   7872.950 ±  3167.566  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                         0                       1           3  thrpt    5   7721.375 ±  2708.805  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                       0.5                       1           0  thrpt    5   7111.515 ±  4704.745  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                       0.5                       1           3  thrpt    5   2955.854 ±   551.514  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                         1                       1           0  thrpt    5   8188.934 ±  5769.265  ops/s
i.z.m.m.throughput.ExtractThroughputBenchmark.extractThroughput             5                         1                       1           3  thrpt    5   1035.832 ±    80.390  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                         0                       1           0  thrpt    5   4059.110 ±  1263.669  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                         0                       1           3  thrpt    5   3985.004 ±  3176.756  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                       0.5                       1           0  thrpt    5   3674.360 ±  2155.058  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                       0.5                       1           3  thrpt    5   4060.650 ±  2503.315  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                         1                       1           0  thrpt    5   4368.590 ±  2019.654  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 3                         1                       1           3  thrpt    5   3523.545 ±   994.066  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                         0                       1           0  thrpt    5   3919.122 ±  2123.348  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                         0                       1           3  thrpt    5   1642.928 ±   680.812  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                       0.5                       1           0  thrpt    5   4054.305 ±  2789.062  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                       0.5                       1           3  thrpt    5   1089.615 ±   467.818  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                         1                       1           0  thrpt    5   3876.070 ±  3862.413  ops/s
i.z.m.m.throughput.MergeThroughputBenchmark.mergeThroughput                 5                         1                       1           3  thrpt    5    639.216 ±    75.811  ops/s
```

The difference as you sad are significant (30-100 times slower :scream: ).

@menski any opinion on that?

**Comment by ThorbenLindhauer** [comment]
@Zelldon please see https://github.com/zeebe-io/zeebe/pull/1339/commits/7880edbdc3754915a172c5f49412cd0e4032b172 and https://github.com/zeebe-io/zeebe/issues/1360.

**Review by ChrisKujawa — APPROVED** [review]

**Pull request merged**
