### PR TITLE
fix(engine): update the key generator on replay

### LINKED ISSUE #8129: Two process instances with different process definitions share the same key
**Describe the bug**

While investigating an issue on the Operate, we came across a case where two process instances, with two different process definitions, share the same key. Not only is the process instance key the same, the record key is the same. However, the positions of the records are different.

Here are the records pulled from Operate:

```json
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 4.890227,
    "hits" : [
      {
        "_index" : "zeebe-record_process-instance_1.2.3_2021-11-02",
        "_type" : "_doc",
        "_id" : "48-1456937",
        "_score" : 4.890227,
        "_routing" : "48",
        "_source" : {
          "partitionId" : 48,
          "value" : {
            "version" : 2,
            "bpmnElementType" : "PROCESS",
            "bpmnProcessId" : "OrderOrchestrationNew",
            "processDefinitionKey" : 2251799813731929,
            "elementId" : "OrderOrchestrationNew",
            "processInstanceKey" : 108086391057176360,
            "flowScopeKey" : -1,
            "parentProcessInstanceKey" : -1,
            "parentElementInstanceKey" : -1
          },
          "key" : 108086391057176360,
          "sourceRecordPosition" : 1456910,
          "timestamp" : 1635849318977,
          "valueType" : "PROCESS_INSTANCE",
          "recordType" : "EVENT",
          "intent" : "ELEMENT_COMPLETED",
          "rejectionType" : "NULL_VAL",
          "rejectionReason" : "",
          "brokerVersion" : "1.2.3",
          "position" : 1456937
        }
      },
      {
        "_index" : "zeebe-record_process-instance_1.2.3_2021-11-02",
        "_type" : "_doc",
        "_id" : "48-1621008",
        "_score" : 4.890227,
        "_routing" : "48",
        "_source" : {
          "partitionId" : 48,
          "value" : {
            "version" : 2,
            "bpmnElementType" : "PROCESS",
            "bpmnProcessId" : "SingleLineNew",
            "processDefinitionKey" : 2251799813731931,
            "flowScopeKey" : -1,
            "parentProcessInstanceKey" : -1,
            "parentElementInstanceKey" : -1,
            "elementId" : "SingleLineNew",
            "processInstanceKey" : 108086391057176360
          },
          "key" : 108086391057176360,
          "sourceRecordPosition" : 1620977,
          "position" : 1621008,
          "timestamp" : 1635855215725,
          "valueType" : "PROCESS_INSTANCE",
          "recordType" : "EVENT",
          "intent" : "ELEMENT_COMPLETED",
          "rejectionType" : "NULL_VAL",
          "rejectionReason" : "",
          "brokerVersion" : "1.2.3"
        }
      }
    ]
  }
}
```

**To Reproduce**

Unclear

**Expected behavior**

Every entity should have a unique key! Keys should not be reused for different entities.

**Environment:**
 - OS: Camunda Cloud CCSaaS
 - Zeebe Version: 1.2.3
 - Configuration: Camunda Cloud CCSaaS

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

On replay, update the key generator with the replayed record's key. This fixes an issue where the follower would restart with a snapshot where nothing needed to be replayed, and would thus not update its generated key, leading to processing starting with the wrong key and duplicate keys, causing state inconsistencies.

## Related issues

closes #8129

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Please recreate against stable/1.2, as this is the PR that should be merged first. We can later port it to develop.

**Comment by Zelldon** [comment]
Working on another PR to backport the fix and tests. :runner:

**Review by saig0 — APPROVED** [review]
@Zelldon looks good :+1: Thanks :cake:

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
