### PR TITLE
ci: usage of correct release workflow for 8.6

### PR DESCRIPTION
**Pull request by megglos**
## Description

We need to use the workflow from the stable branch, instead of main. Also added dry run for 8.6

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Comment by megglos** [comment]
Test dry run https://github.com/camunda/camunda/actions/runs/11280436216

**Comment by megglos** [comment]
Needs https://github.com/camunda/camunda/pull/23333

**Review by tmetzke — APPROVED** [review]
🚀

**Comment by tmetzke** [comment]
Any idea where the [failing tests](https://github.com/camunda/camunda/actions/runs/11280435262/job/31373594349?pr=23330) are coming from and why they want to fetch an `8.6.1` Docker container?

**Comment by tmetzke** [comment]
> Any idea where the [failing tests](https://github.com/camunda/camunda/actions/runs/11280435262/job/31373594349?pr=23330) are coming from and why they want to fetch an `8.6.1` Docker container?

Found the problem: we had an 8.6.1 tag already (but no GH release). Deleted the tag, rerunning the test now. Automerge enabled.

**Pull request merged**
