### PR TITLE
Reorganize stream processor and engine tests

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Moved some tests around to make it easier to detect which need to be migrated for #10455 and to make it easier to create the new module and copy the tests, which are part of the StreamProcessor see #10130 

## Related issues

related to #10455 
related to #10130 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors retry

**Comment by Zelldon** [comment]
Weird

**Comment by Zelldon** [comment]
@oleschoenburg I added a fix which I also have observed in https://github.com/camunda/zeebe/issues/10526#issuecomment-1260510043 

I have seen when running `shouldPreserveOrderingOfWritesEvenWithRetries` that it sometimes can happen that the writing (retry loop) can take up to 3 seconds, where the timeout is 2 seconds. I think this is related to that we always copy again in the loop (which is not necessary)

Please have a another look at the PR.

**Comment by Zelldon** [comment]
@oleschoenburg I could also create a separate PR which we merge first, makes it easier to backport.

**Review by lenaschoenburg — COMMENTED** [review]
@Zelldon 
I think there's something wrong now :sweat_smile:: 
```
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.375 s <<< FAILURE! - in io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest
Error:  io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries  Time elapsed: 2.639 s  <<< FAILURE!
org.mockito.exceptions.verification.VerificationInOrderFailure: 

Verification in order failure:
logStreamBatchWriter.tryWrite();
Wanted 1 time:
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceTest.shouldPreserveOrderingOfWritesEvenWithRetries(ProcessingScheduleServiceTest.java:275)
But was 5001 times:
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
-> at io.camunda.zeebe.streamprocessor.ProcessingScheduleServiceImpl.lambda$toRunnable$5(ProcessingScheduleServiceImpl.java:165)
.....
```

:+1: for splitting the fix in a seperate PR.

**Comment by Zelldon** [comment]
Yeah I saw that sorry :see_no_evil: I'm on it. Will create a separate PR. :+1:

**Comment by Zelldon** [comment]
@oleschoenburg thanks for reviewing the other :) I rebased this one, could you accept again?

**Review by lenaschoenburg — APPROVED** [review]

**Comment by Zelldon** [comment]
\backport

**Pull request merged**
