### PR TITLE
chore(maven): migrate to new artifacts.camunda.com

### PR DESCRIPTION
**Pull request by cmur2**
## Description

As announced, we need to switch to the new URL for Artifactory.

## Related issues

Related to INFRA-3107

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
bors merge

**Comment by cmur2** [comment]
It can be merged if it's green (which seems to be the case except for some flaky tests). I'll rerun CI.

**Comment by npepinpe** [comment]
No worries, I checked already which is why I initially went ahead and started to merge.

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
One small question, does this need to be backported? Will the old URL get deprecated?

**Comment by cmur2** [comment]
> One small question, does this need to be backported? Will the old URL get deprecated?

Yes, we want to migrate all usages await from the old URL no matter where they are. This allows Camunda to save costs and maintenance effort. The old Nexus URL will stop working (timeline depends a bit on customers).

**Pull request merged**
