### PR TITLE
Allow unsupported BPMN elements in non executable pools

### LINKED ISSUE #9542: Allow unsupported BPMN elements in non executable pools
**Is your feature request related to a problem? Please describe.**

Customers following our BPMN methodology described also in Real-Life BPMN might create collaboration diagrams that contain executable and non-executable Pools (for example a model like in https://camunda.com/bpmn/examples/#bpmn-examples-four-eyes-principle). 

In https://github.com/camunda-community-hub/camunda-7-to-8-migration/issues/19 Stephan raised the problem that Zeebe rejects deployments containing unsupported elements, even if in a nonexecutable pool (e.g.  `Element: ConditionalEventDefinition_0lvmueg ERROR: Event definition of this type is not supported` ).

**Describe the solution you'd like**

Zeebe does not need to check elements in non-executable pools - as they are not executed and are ignored anyway. 
This would allow using all BPMN elements for documentation purposes.

### PR DESCRIPTION
**Pull request by skayliu**
## Description

Zeebe does not need to check elements in non-executable pools.

If there is only one non-executable process in a bpmn definition, it will be blocked by ["Must contain at least one executable process"](https://github.com/camunda/zeebe/blob/main/bpmn-model/src/main/java/io/camunda/zeebe/model/bpmn/validation/zeebe/DefinitionsValidator.java#L37)

If there are more the one process in a bpmn definition, only the executable pools will be deployed.

e.g. a definition with one non-executable pool and one executable pool, only the executeable process is deployed.

## Related issues

closes #9542 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [x] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by skayliu** [comment]
Hi, @saig0. Please take a moment to review this feature when you have time. Thanks. ❤️

**Comment by saig0** [comment]
@skayliu thank you for your contribution. :tada: We'll have a look at your PR in the next few days. :eyes:

**Review by saig0 — COMMENTED** [review]
@skayliu thank you for fixing the issue. :+1: 

The solution works in general but it is too specific. We should aim for a more general solution. Please have a look at my comments. :cake:

**Review by saig0 — CHANGES_REQUESTED** [review]
Please rebase the PR and apply the review hints. :cookie:

**Comment by skayliu** [comment]
Hi, @saig0, I've rebased to main and apply all the review hints. Please review again, thank you.

**Review by saig0 — APPROVED** [review]
@skayliu looks good. :+1: Thank you for your fast response. :zap: 

bors merge

**Comment by saig0** [comment]
bors merge

**Comment by skayliu** [comment]
Hi, @saig0 , Do i need rebase to main again?

**Comment by saig0** [comment]
bors merge

**Comment by saig0** [comment]
bors merge

**Pull request merged**
