### PR TITLE
ci: move operate stage 2 tests into nightly workflow to save runner resources

### PR DESCRIPTION
**Pull request by matt-whiteman**
## Description

Moved all the stage 2 tests into the nightly job since they take too long to run and hog the github runners. Tests will be moved back into the main CI as they are refactored.

## Related issues

related to #19186
related to https://github.com/camunda/operate/issues/6268

### CODE REVIEW

**Review by johanwelgemoed — APPROVED** [review]
LGTM :)

**Comment by megglos** [comment]
@matt-whiteman can we backport this to stable/8.5 as well?

**Comment by matt-whiteman** [comment]
@megglos We don't have the nightly job on 8.5 but I can certainly put something together to do that and move these tests

**Comment by matt-whiteman** [comment]
@megglos I created a PR for 8.5 that contains the nightly job and moving all the slow tests into it at https://github.com/camunda/zeebe/pull/17852

**Pull request merged**
