### PR TITLE
ci: fix optimize issue templates

### PR DESCRIPTION
**Pull request by misiekhardcore**
## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

related to #21168

### CODE REVIEW

**Review by RomanJRW — APPROVED** [review]

**Comment by cmur2** [comment]
@misiekhardcore ( @RomanJRW ) this PR is causing CI failures on `main` due to formatting issues, can you please follow up asap?

The failures in question:

* https://github.com/camunda/camunda/actions/runs/10400491288/job/28801149691
* https://github.com/camunda/camunda/actions/runs/10400238780/job/28800443592
* https://github.com/camunda/camunda/actions/runs/10400137463/job/28800170217

In general, I'd like to understand how Markdown with format issues is allowed to merged and is only detected on `main` (when it is too late) - why does the format checker (Maven spotless?) only run on `main`, anyone knows? @Zelldon 

We should have it run consistently also on PRs and merge queue to avoid this kind of situations where `main` became "tainted" and needs a fix asap.

**Comment by Zelldon** [comment]
Hm looks like no change was detected. I guess because it is limited to java files? 🤔 https://github.com/camunda/camunda/actions/runs/10400031108/job/28799871050

**Comment by cmur2** [comment]
> Hm looks like no change was detected. I guess because it is limited to java files? 🤔 https://github.com/camunda/camunda/actions/runs/10400031108/job/28799871050

That sounds plausible to me, so we have to extend https://github.com/camunda/camunda/blob/main/.github/actions/paths-filter/action.yml#L17-L22 to also care about "Markdown file changes" (new filter expression).

**Comment by cmur2** [comment]
I noticed this behavior a couple of times where Markdown formatting issues slipped through - also happened to me but was usually found in the merge queue already (annoying but prevented the merge).

**Comment by misiekhardcore** [comment]
My problem is that I don't know how to check the formatting locally, and in VSCode the formatter is formating MD files in a different manner than we expect.

**Comment by lenaschoenburg** [comment]
> My problem is that I don't know how to check the formatting locally

You can run `./mvnw spotless:apply`

**Comment by Zelldon** [comment]
Do you have maven installed?

You can use `mvn spotless:apply` to adjust the markdown files (apply the the right format.

And mvn spotless:check to run the checks

**Comment by misiekhardcore** [comment]
@Zelldon I have `mvn`. So I will try to use this command, but this feels like a inconvenience a bit, cause I had to turn off default formatters now in VSCode and have to run this manual command instead

**Comment by lenaschoenburg** [comment]
Feel free to add an exclusion for those files if you don't want consistent formatting: https://github.com/camunda/camunda/blob/91379d396a3b8c01dcf12ee1c736f1d321bd569e/pom.xml#L58-L64

**Comment by misiekhardcore** [comment]
@lenaschoenburg that's not a solution to the problem. We need a way to make the formatting work, otherwise what's the point of it

**Comment by lenaschoenburg** [comment]
> that's not a solution to the problem

It's a solution for the problem you formulated: "this feels like a inconvenience a bit"

>  We need a way to make the formatting work

Formatting works, with `./mvnw spotless:apply` or `./mvnw spotless:check`

**Comment by Zelldon** [comment]
Looks like others had the issue as well https://github.com/diffplug/spotless/discussions/1763 So VSCode seems to not have it supported yet.

Is there any chance for you to use Intellij? As this was the used IDE/Editor used when it was introduced, which comes with good support. Other than that I think the only option leaves with running spotless manually on terminal. 

We definitely need to make it part of the CI checks, so you also get feedback on new PRs.

**Comment by lenaschoenburg** [comment]
> Is there any chance for you to use Intellij? As this was the used IDE/Editor used when it was introduced, which comes with good support.

That only works for Java code, IntelliJ doesn't know how to format markdown files so that they match the spotless rules.
So a manual `./mvnw spotless:apply` is still required.

**Comment by Zelldon** [comment]
Maybe this helps https://github.com/diffplug/spotless/discussions/1763#discussioncomment-8798693 you can configure the on save option to run mvn spotless

**Comment by misiekhardcore** [comment]
@Zelldon @lenaschoenburg maybe running `mvn spotless:apply` in a pre-commit hook would do the trick?

**Comment by Zelldon** [comment]
No please no pre-commit hooks, this slows iteration and progress for everyone really down.

**Comment by lenaschoenburg** [comment]
Yeah, running `mvn spotless:apply` is hilariously slow so it can't be a pre-commit hook.

**Comment by misiekhardcore** [comment]
btw, the formatting will be fixed in [this PR](https://github.com/camunda/camunda/queue/main)

**Comment by misiekhardcore** [comment]
> Maybe this helps [diffplug/spotless#1763 (comment)](https://github.com/diffplug/spotless/discussions/1763#discussioncomment-8798693) you can configure the on save option to run mvn spotless

this seem to indeed run `mvn spotless:apply` on save. It does it in the background without much info that it does it, but it feels like an acceptable solution

**Pull request merged**
