### PR TITLE
[BACKPORT] chore(util): introduce StackdriverLayout

### LINKED ISSUE #4703: [BACKPORT] Improve Stackdriver Log4J2 layout to be spec compliant
**Description**

We will back port the updated Stackdriver Log4J2 layout to 0.23.x. While this isn't a bug fix, we deem it sufficiently useful for us to start using it in production as soon as possible. It would technically break semantic versioning but as we're pre 1.0, this is also alright.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR back ports #4685 for 0.23.x and will should be part of the patch release next Monday.

## Related issues

closes #4703 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by korthout — APPROVED** [review]
I just did a quick scan of the changes, looks the same and so LGTM. 

One question though: did you do a manual test for the backport?

**Comment by npepinpe** [comment]
Sorry, I could have mentioned I just cherry picked the commit, no conflicts or anything.

I didn't test it, I figured these changes are exactly the same and the whole layout is basically an addition. Do you see a reason to do additional testing there? I can gladly do it, or maybe you want to practice :wink:

**Comment by korthout** [comment]
I agree it's not likely that it won't work, but still. I like your idea, I'll do a practice run.

**Comment by npepinpe** [comment]
Ping me if you need anything. And pro tip, set DOCKER_BUILDKIT=1 before building the image, it's much faster :slightly_smiling_face:

**Comment by korthout** [comment]
Verified logs for servicename and serviceversion; as well as error reporting with servicename, serviceversion and source location.

**Review by korthout — APPROVED** [review]

**Comment by npepinpe** [comment]
bors retry

**Pull request merged**
