### PR TITLE
Use sortpom plugin to improve pom file formatting

### LINKED ISSUE #7923: Add sortpom to align pom element ordering
**Description**

In the [team meeting of 29th Sept 2021](https://confluence.camunda.com/display/ZEEBE/2021-07-29+Team+Meeting?focusedTaskId=6), the team agreed to apply [sortpom](https://github.com/Ekryd/sortpom/) to the zeebe project's pom files.

### PR DESCRIPTION
**Pull request by korthout**
## Description

This adds [Ekryd/sortpom](https://github.com/Ekryd/sortpom) to the zeebe project. The sortpom plugin will align pom file formatting. This will make sure we have consistency in our pom files and may help us avoid review discussions about pom file changes.

It is configured to sort on the `process-resources` maven lifecycle phase (before compile), and takes ~1 second in total to run on all submodules sequentially when the pom files are already sorted.

It is also added to the `checks` profile, so the formatting can be validated on CI builds.

The chosen configuration is the default provided with v3.0.0 of the sortpom plugin, that is [recommended_2008_06](https://github.com/Ekryd/sortpom/blob/master/sorter/src/main/resources/recommended_2008_06.xml) which was defined by the core maven developers.

Backup files have been disabled, since we already use git, which can also show local changes.

Note that the sortpom is unable to enforce a maximum characters per line length. See: https://github.com/Ekryd/sortpom/issues/38 and https://github.com/hunterhacker/jdom/issues/170

## Related issues

closes #7923 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Holy conflicts Batman! :smile: I guess merging the release branch caused all of these

**Review by npepinpe — APPROVED** [review]
:+1: 

The only one I really looked at was `parent/pom.xml`, as its our most complex one. I don't see any issues imo. The plugin seems well supported, I don't foresee issues in general - maybe one question would be if it'll work with Java 17? Other than that, looks fine.

I think it still doesn't solve the issues with the IDE's auto formatter, no? It seems to be mostly a maven plugin, so auto formatting your XML files in IntelliJ will mess it up? Not a blocker IMO as it's still an improvement.

**Comment by korthout** [comment]
>one question would be if it'll work with Java 17

Good point. Quickly tested locally:

```
$ jenv local 17
$ mvnd clean process-resources -Dfmt.skip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.220 s (Wall Clock)
[INFO] Finished at: 2021-10-05T16:01:57+02:00
[INFO] ------------------------------------------------------------------------
 ```
 
 >I think it still doesn't solve the issues with the IDE's auto formatter, no?
 
 That's correct. IDE should be disabled to format xml files perhaps? I just don't edit pom files in IntelliJ, it would anyways mess them up.

**Comment by korthout** [comment]
bors merge

**Pull request merged**
