### PR TITLE
Prototype - refactor(engine): cache parsed DMN graphs

### PR DESCRIPTION
**Pull request by megglos**
## Description

**Before caching:**

Result "io.camunda.zeebe.engine.perf.EngineSingleDmnTaskPerformanceTest.measureProcessExecutionTime":
  3.749 ±(99.9%) 0.025 ms/op [Average]
  (min, avg, max) = (2.946, 3.749, 12.911), stdev = 0.761
  CI (99.9%): [3.724, 3.774] (assumes normal distribution)

Result "io.camunda.zeebe.engine.perf.EngineParallelDmnTaskPerformanceTest.measureProcessExecutionTime":
  26.837 ±(99.9%) 0.057 ms/op [Average]
  (min, avg, max) = (24.374, 26.837, 50.751), stdev = 1.744
  CI (99.9%): [26.779, 26.894] (assumes normal distribution)

**With parsed Dmn cache**

Result "io.camunda.zeebe.engine.perf.EngineSingleDmnTaskPerformanceTest.measureProcessExecutionTime":
  0.950 ±(99.9%) 0.016 ms/op [Average]
  (min, avg, max) = (0.651, 0.950, 11.944), stdev = 0.498
  CI (99.9%): [0.934, 0.967] (assumes normal distribution)

Result "io.camunda.zeebe.engine.perf.EngineParallelDmnTaskPerformanceTest.measureProcessExecutionTime":
  3.445 ±(99.9%) 0.023 ms/op [Average]
  (min, avg, max) = (2.746, 3.445, 23.453), stdev = 0.707
  CI (99.9%): [3.421, 3.468] (assumes normal distribution)
  
Summary:
**Single DMN Task Process P99.9 latency went down by 75%/ 4 times faster**
**10 Parallel DMN Task Process P99.9 latency went down by 87%/ 7-8 times faster**

## Related issues

relates #8571

### CODE REVIEW

**Comment by megglos** [comment]
Adopted to using a configurable LRU cache from agrona, performs slightly worse compared to the map.

Result "io.camunda.zeebe.engine.perf.EngineSingleDmnTaskPerformanceTest.measureProcessExecutionTime":
  1.020 ±(99.9%) 0.020 ms/op [Average]
  (min, avg, max) = (0.675, 1.020, 13.166), stdev = 0.617
  CI (99.9%): [1.000, 1.041] (assumes normal distribution)
  
 Result "io.camunda.zeebe.engine.perf.EngineParallelDmnTaskPerformanceTest.measureProcessExecutionTime":
  3.624 ±(99.9%) 0.032 ms/op [Average]
  (min, avg, max) = (2.777, 3.624, 21.808), stdev = 0.964
  CI (99.9%): [3.592, 3.656] (assumes normal distribution)

**Comment by megglos** [comment]
Guava Cache based, comparable to the agrona LRU:

Result "io.camunda.zeebe.engine.perf.EngineSingleDmnTaskPerformanceTest.measureProcessExecutionTime":
  **1.007** ±(99.9%) 0.017 ms/op [Average]
  (min, avg, max) = (0.653, 1.007, 13.365), stdev = 0.511
  CI (99.9%): [0.990, 1.023] (assumes normal distribution)

Result "io.camunda.zeebe.engine.perf.EngineParallelDmnTaskPerformanceTest.measureProcessExecutionTime":
  **3.651** ±(99.9%) 0.047 ms/op [Average]
  (min, avg, max) = (2.815, 3.651, 66.892), stdev = 1.436
  CI (99.9%): [3.604, 3.698] (assumes normal distribution)

**Comment by megglos** [comment]
Caffeine based, slightly better than agrona LRU and Guava:

Result "io.camunda.zeebe.engine.perf.EngineSingleDmnTaskPerformanceTest.measureProcessExecutionTime":
  0.997 ±(99.9%) 0.016 ms/op [Average]
  (min, avg, max) = (0.655, 0.997, 14.775), stdev = 0.483
  CI (99.9%): [0.981, 1.013] (assumes normal distribution)

Result "io.camunda.zeebe.engine.perf.EngineParallelDmnTaskPerformanceTest.measureProcessExecutionTime":
  3.586 ±(99.9%) 0.030 ms/op [Average]
  (min, avg, max) = (2.755, 3.586, 26.650), stdev = 0.913
  CI (99.9%): [3.556, 3.616] (assumes normal distribution)

**Comment by megglos** [comment]
As the agrona `Long2ObjectHashMap` map is not allowing us to set a limit I tested three ways to get LRU behavior.
Best performing seems Caffeine but it also requires us to introduce a new dependency, I may rather create a follow-up for considering replacing all caches by Caffeine for better performance.

Guava and agrona LRU where comparable but also the cache is not really under pressure with the current jmh test setup reusing the same dmn for all dmn Tasks, we may extend that to use different models.

**Comment by megglos** [comment]
Sync with @remcowesterhoud :
- the impl needs to change => cache within the DbDecisionState similar to like it's done for DbProcessState
- we aim to backport this to 8.2/8.1
- jmh tests will be omited for backporting
- ZPA takes this over to make it production ready
- the agrona LRU cache seems a good pick for now allowing us to already have the capacity limit

**Comment by remcowesterhoud** [comment]
> the agrona LRU cache seems a good pick for now allowing us to already have the capacity limit

For some reason the Agrona LRU doesn't seem to support removing entries from the cache manually. I'll go with the Guava option instead, as we already have the dependency in place and the performance was similar to Agrona.

**Comment by megglos** [comment]
superseded by https://github.com/camunda/zeebe/pull/13831

**Pull request closed without merging**
