### PR TITLE
chore(clients/go): enable integration tests on Mac OS

### LINKED ISSUE #5806: Make Go client integration tests build on Mac OS
**Description**

I see that Go tests are not enabled on Mac OS: https://github.com/zeebe-io/zeebe/blob/425b2615be79cddbcb8faf439c5fc97a128687ff/clients/go/cmd/zbctl/main_test.go#L190-L194. But I think that we can try to enable on Mac OS

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

I've enabled integration tests of the go client on Mac OS. I tested it locally with MBP 2019, version: 10.15.7 (19H15).

## Related issues

closes #5806 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [X] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Assigning to @korthout since he's the only one of us with a Mac

**Review by korthout — APPROVED** [review]
Works on my machine (also 2019 macbook pro running macOS 10.15.7)

🍏 LGTM

**Comment by aivinog1** [comment]
@korthout Thanks for the review, this is ready for merge, waiting for bors r+ :)

**Comment by korthout** [comment]
sorry 😮  missed it

bors r+

**Pull request merged**
