### PR TITLE
style(github): added ref for existing customer's support

### PR DESCRIPTION
**Pull request by abbasadel**
## Description

Added a comment to direct Camunda's existing customers to use our customer support since some bugs has already know workaround. 
This will also help Zeebe teams prioritise bugs coming from the support team with detailed analysis

### CODE REVIEW

**Review by megglos — APPROVED** [review]
Thanks!

**Comment by megglos** [comment]
bors merge

**Comment by korthout** [comment]
@abbasadel I think this broke the template from showing up as an option on new issues:
Screenshot 2023-12-06 at 13 14 27

**Comment by megglos** [comment]
argh should have taken a closer look 🤦 , can you provide a fix @abbasadel and move the addition below the header of the template?

**Comment by abbasadel** [comment]
Thanks @korthout for catching this. The fix is here: https://github.com/camunda/zeebe/pull/15502

**Pull request merged**
