### PR TITLE
ci: add Optimize stable branch to renovate config

### PR DESCRIPTION
**Pull request by misiekhardcore**
## Checklist

- [ ] for CI changes:
  - [x] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Review by grlimacan — APPROVED** [review]
LGTM!

**Review by grlimacan — CHANGES_REQUESTED** [review]
There seems to be an issue with the renovate check

**Comment by misiekhardcore** [comment]
@grlimacan this is expected, we have to ignore it

**Review by grlimacan — APPROVED** [review]
If the renovate pipeline failure is ok, then LGTM

**Comment by cmur2** [comment]
Thanks for this change!

**Pull request merged**
