### PR TITLE
test: fix deadlock in stream processor tests

### LINKED ISSUE #14011: `StreamProcessorTest#shouldBlockProcessingIfSchedulingBlocks` sometimes blocks forever
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? Twice on bors, reproducible locally
- Does it block your work? No
- Do we suspect that it is a real failure? No

**Failures**

The test does not finish sometimes. Reproducible by running the test repeatedly.

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This test is broken since we enabled async scheduled tasks by default. It was actually behaving exactly as `shouldProcessEvenIfAsyncSchedulingBlocks` except that the assertion that `RecordProcessor#process` is not being called  would still pass most of the time because the invocation count is observed before the stream processor actor had the chance to run. When it occasionally fails because `RecordProcessor#process` was getting called fast enough, the test would fail but not close correctly because the processing actor is blocked waiting on a countdown latch that the test never decrements (because the assertion failed and the countdown only happens in the happy path).

I've first fixed the deadlock by ensuring that countdown latches are always decremented. Additionally, I suggest to simply remove the test case `shouldBlockProcessingIfSchedulingBlocks` because it tries to observe that a bug can occur when a non-default setting is used. IMO this does not add much value and I'd rather remove it instead of trying to extend `StreamPlatformExtension` to allow configuring `enableAsyncScheduledTasks`.

closes https://github.com/camunda/zeebe/issues/14011

### CODE REVIEW

**Comment by Zelldon** [comment]
> I've first fixed the deadlock by ensuring that countdown latches are always decremented. Additionally, I suggest to simply remove the test case shouldBlockProcessingIfSchedulingBlocks because it tries to observe that a bug can occur when a non-default setting is used. IMO this does not add much value and I'd rather remove it instead of trying to extend StreamPlatformExtension to allow configuring enableAsyncScheduledTasks.

Hey @oleschoenburg just that I understand this right. So per default we now have async scheduling? But it can be disabled? By whom? Is it an env var that can be set by users? Then I would argue that we should test every possible configuration. Otherwise we have blindspots, where people can run into issues, right? 
If is it not configurable for them then yes we can remove the test but also the rest of the code that allows sync executions or?

**Comment by oleschoenburg** [comment]
> So per default we now have async scheduling? But it can be disabled? By whom? Is it an env var that can be set by users?

That's correct,  `ZEEBE_BROKER_PROCESSING_ENABLEASYNCSCHEDULEDTASKS`. 

> Then I would argue that we should test every possible configuration. Otherwise we have blindspots, where people can run into issues, right?

I'd consider `shouldBlockProcessingIfSchedulingBlocks` an implementation detail because users have no control over scheduled tasks. They don't _wan't_ processing to be blocked. The configuration to disable async scheduled tasks was added as an escape hatch in case the feature is buggy and can't be fixed easily.

**Comment by Zelldon** [comment]
> The configuration to disable async scheduled tasks was added as an escape hatch in case the feature is buggy and can't be fixed easily.

How long we have it now running like this? When is the time we remove it?

**Review by ChrisKujawa — APPROVED** [review]
Yes I agree that the test might be not optimal, especially that we test something which should will not happen  (like processing does not happen).

I think it was added before as counter part to the async scheduling that we see ok it blocks on sync scheduling and not on async. 🤷🏼‍♂️ 

Still, I think we should test sync scheduling since we can enable it via configuration. Not sure whether we have tests for it, doesn't sound to me like it since you mentioned it is not possible to configure it.

**Comment by oleschoenburg** [comment]
> How long we have it now running like this?

Since https://github.com/camunda/zeebe/pull/13524

> When is the time we remove it?

I don't know. I don't think we have a policy on when to remove configuration flags.

> Not sure whether we have tests for it, doesn't sound to me like it since you mentioned it is not possible to configure it.

We have tests that verify that the configuration flag is parsed correctly. What I meant with "it's not possible to configure it" is that we don't have a way to set custom configuration for tests that make use of the `StreamPlatformExtension`.

> Still, I think we should test sync scheduling since we can enable it via configuration.

I've added a test that verifies that the `ExtendedProcessingScheduleServiceImpl` respects the configuration and runs tasks on the synchronous executor when sync execution is requested and `alwaysAsync` is false.

bors merge

**Pull request merged**
