### PR TITLE
chore(broker): Add methods to configuration objects that return Duration objects

### LINKED ISSUE #3842: Remove DurationUtil / change Interfaces from String to Duration
**Description**

The class `DurationUtil` is used throughout the code base. It should be removed. The parsing logic should be used only in the config parsing layer (maybe later to be removed altogether).

* Add methods to configuration objects that return a `Duration` instead of the string, e.g.
```
public final class BrokerCfg {
  //existing interface
  public String getStepTimeout() {..}
  public void String setStepTimeout() { // add parsing logic here}
  // new method to be added
  public void Duration getStepTimeoutAsDuration() {...}
}
```
* Make clients of the configuration objects use the `Duration`

### PR DESCRIPTION
**Pull request by pihme**
## Description

Adds methods to configuration objects that return `Duration` objects. These methods are the preferred way to read duration values from the configuration. 

## Related issues

closes #3842 

## Pull Request Checklist

- [ X ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ X ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ X ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by pihme** [comment]
@npepinpe : Any ideas, why Jenkins complained for the PR while Jenkins for the branch was happy?

https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/3842-Add-methods-to-cfg-to-get-Duration/

**Comment by npepinpe** [comment]
There's a known issue with the CI where sometimes many tests start timing out. Since many of our tests are based on timing due to the asynchronous nature of the software (e.g. expect X to happen within Y seconds), resource contention can mess with that. It's not 100% sure yet, but we're working with the infra team to figure out if it's only a CI issue or if it's a problem with our tests.

**Review by npepinpe — APPROVED** [review]
👍 looks good thanks!

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Pull request merged**
