### PR TITLE
build: use maven wrapper

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This adds [maven-wrapper](https://maven.apache.org/wrapper/) to our project. The idea is that there's a single source of truth for the maven version that should be used to build Zeebe.
This can have an impact on local development and CI.

Local development benefits because it ensures that all developers use the same maven version. Additionally, it allows us to accelerate the rollout of newer maven version. Maven releases seem to occur more often lately and Maven 4 is on the horizon. 

CI can also benefit. Currently we are using a `setup-maven` action to download and install a common version of maven on all CI jobs. This action is not the most reliable one (used to fail fairly often on some runners) and we have to remember to manually update the used maven version there. This PR removes the `setup-maven` usage and updates all CI jobs to go through the maven-wrapper.

### CODE REVIEW

**Review by korthout — APPROVED** [review]
LGTM 👍 

Note that I'll continue to locally use `mvnd` even when `mvnw` is provided, for as long as I can.

Please wait for other reviews before merging.

**Comment by oleschoenburg** [comment]
> Note that I'll continue to locally use mvnd even when mvnw is provided, for as long as I can.

Yep, same here. I think that's fine, the wrapper is still available then to double check if any weirdness might be related to maven versions.

**Comment by Zelldon** [comment]
Bors r+

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
