### PR TITLE
feat(client-java): support set variables when failing a job

### LINKED ISSUE #9404: I can set variables when failing a job
> Zeebe is amazing!!!
> 
> I want to migrate my previous java Camunda 7 External Task code to Zeebe Job Worker.  I'm missing the absolute "must" .variables(...) function in .newFailCommand and newThrowErrorCommand. I was able in Camunda 7 External Task to add (local/global) variables with handleFailure and handleBpmnError functions.

**Describe the solution you'd like**
I can set variables when sending a fail job command.

```
client.newFailCommand(...).variables(...) 
```

It should set the variables, similarly to the complete job command.

```
client.newCompleteCommand(...).variables(...)
```

The given variable should be set as local variables in the scope of the related task. As a result, the next activated job could access the variables.

If the command would set the variables globally then it would need to apply the output mappings of the related task. Applying output mappings could raise an incident and would make the job not activatable anymore.

### PR DESCRIPTION
**Pull request by skayliu**
## Description

Add support set variables when failing a job.

`client.newFailCommand(...).variables(...) `

## Related issues

closes #9404 

depends on #10701, #10702 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by saig0** [comment]
@skayliu thank you for your contribution. :tada: We'll have a look at your PR in the next few days. :eyes:

**Review by korthout — COMMENTED** [review]
Thanks @skayliu 🚀 

👍 These changes look good, but they can only compile after #10702 is merged

I'll await with approval until we have a green CI on this PR.

**Comment by korthout** [comment]
@skayliu You'll need to rebase this PR on top of `main` now that #10702 is merged

**Comment by skayliu** [comment]
@korthout, It's done.

**Review by korthout — APPROVED** [review]
Thanks @skayliu LGTM 🥇 

bors merge

**Pull request merged**
