### PR TITLE
feat(broker): trigger error event subprocess

### LINKED ISSUE #3498: Catch an error on an event subprocess
**Is your feature request related to a problem? Please describe.**
A job worker can throw an error when a business error (i.e. non-technical) occurs and the job can not be completed. This error should be handled in the workflow by catching it on an event subprocess.

**Describe the solution you'd like**
* the error event contains an `errorCode` (any string)
* the error is caught on the event subprocess if the error code in the BPMN is equal to the thrown error code
* the event subprocess can be inside the same scope as the service task or inside an upper scope, or at process level (root)

**Describe alternatives you've considered**
none

**Additional context**

requires #3497

### PR DESCRIPTION
**Pull request by saig0**
## Description

* an error event can be caught by an error event subprocess
* favor an error event subprocess over an error boundary event on an embedded subprocess
* extract validation logic from boundary event and event subprocess
* extract logic to trigger an event

## Related issues

closes #3498

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by miguelpires — CHANGES_REQUESTED** [review]
Looks good. Just a couple of small things

**Comment by saig0** [comment]
@MiguelPires, thank you for your review. I applied your hints. I removed the unused variable and removed the if statement because it is not necessary anymore (`catchEvent` can not be null and it throws an exception in the called method if it has no timer definition).

**Review by miguelpires — APPROVED** [review]

**Comment by saig0** [comment]
bors retry

**Pull request merged**
