### PR TITLE
feat: change claim for clusterId

### LINKED ISSUE #17632: Change claim used to check cluster id during SaaS M2M authorization
### Context

Action plan: https://docs.google.com/presentation/d/1gtApTY_FpP1OD8R-jYfF3uP72LeYrCv0aZ-ZNJrDshE/edit#slide=id.g2cc262d7565_0_0
Epic: https://github.com/camunda/product-hub/issues/2268

### Description

In Operate API when we authorize M2M token [we check `scope` claim to contain proper cluster id](https://github.com/camunda/zeebe/blob/03358a4f44c102f6e33b0b3ab711fc45c48725c0/operate/webapp/src/main/java/io/camunda/operate/webapp/security/oauth2/CCSaaSJwtAuthenticationTokenValidator.java#L53). We need to check another claim now: `https://camunda.com/clusterId`

### Steps to Test

https://github.com/camunda/zeebe/issues/17632#issuecomment-2078913792

### TODO

* Replace claim `scope` with `https://camunda.com/clusterId`

### Additional Information

* needs to be backported to all supported versions (8.2, 8.3, 8.4, 8.5)

---------------------------------------------------------------------------------------------

### Acceptance Criteria

- [ ] Checked if the specific data needs to be provided for the QA process

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered
- [ ] Cross-team dependencies have been considered

### PR DESCRIPTION
**Pull request by sdorokhova**
closes #17632

### CODE REVIEW

**Comment by sdorokhova** [comment]
Tested on DEV cluster by deploying Docker image from the branch `europe-docker.pkg.dev/camunda-saas-registry/operate/operate:8.5.0-17632`

**Review by ghost — COMMENTED** [review]
How can we test this, can you please add steps to test / run, to ticket ? Thank you.

**Comment by sdorokhova** [comment]
@mihail-ca described here: https://github.com/camunda/zeebe/issues/17632

**Review by johanwelgemoed — APPROVED** [review]
LGTM

**Pull request merged**
