### PR TITLE
ci: revert renovate config migration

### PR DESCRIPTION
**Pull request by misiekhardcore**
## Description

This PR reverts breaking changes to renovate config. These breaking changes were introduced by #21060 

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Review by cmur2 — APPROVED** [review]

**Comment by misiekhardcore** [comment]
@cmur2 will this merge with the `Renovate lint` failing?

**Comment by cmur2** [comment]
> @cmur2 will this merge with the `Renovate lint` failing?

Yes, since that is not a required status check so can be ignored - I did the same for my revert.

**Comment by cmur2** [comment]
Thanks!

**Comment by megglos** [comment]
Hey @cmur2 & @misiekhardcore 

We recently encountered that renovate updated to a SNAPSHOT dependency here
https://github.com/camunda/camunda/pull/21372

We wondered why a we actually have a rule against that https://github.com/camunda/camunda/blob/main/.github/renovate.json#L75-L80

Then we noticed we recently switched the matcher to [`matchPackagePrefixes`](https://github.com/camunda/camunda/commit/8ef9c1b79f60869d297120d9ebf54f055c3ab4ea#diff-f82f7d36a61d22f640c25bdb8b0435bf9cb38679d99d5f460753fa668ee7cdb3R78) from [`matchPackagePattern`](https://github.com/camunda/camunda/commit/19e7c6faee80cc2598096b9305cd3ee4cf51ac2d)
with the recent revert. Which thus didn't really revert to the state we had before all the config refactoring happened?

There is a new discussion on the renovate repo that they actually deprecated/removed the support for [`matchPackagePrefixes`](https://github.com/renovatebot/renovate/discussions/30891). May the config be broken now, can you please follow-up on this?

**Comment by misiekhardcore** [comment]
When I was reverting the config migration to the new structure, I reverted those changes manually (cause the original PR had more changes) and apparently I made a mistake there. I will open a PR fixing this

**Pull request merged**
