### PR TITLE
feat(backup/s3): add fileset metadata

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This changes the manifest schema to allow for attaching metadata to segment and journal files.

Previously manifests looked like this:
```json
{ 
 "snapshotFileNames": [
    "000143.log",
    "OPTIONS-000007",
    "000144.sst"
  ]
}
```

Now, with attached metadata, the structure looks like this:
```json
{ 
 "snapshotFiles": {
    "000143.log": {},
    "OPTIONS-000007": {},
    "000144.sst": {}
  }
}
```

To stay backwards compatible with 8.1, I implemented a custom deserializer that supports both schemes and added name aliases. Unfortunately, I couldn't find a more elegant solution than writing a custom deserializer.

Extracted from https://github.com/camunda/zeebe/pull/10940 to keep the PRs small.

### CODE REVIEW

**Comment by deepthidevaki** [comment]
@oleschoenburg This is marked as draft PR. Should I wait before reviewing?

**Comment by oleschoenburg** [comment]
Oops! No, it's ready for review.

**Review by deepthidevaki — APPROVED** [review]
Thanks. LGTM. Please check my comment before merging.

:question: Now the metadata about compression will be stored in each file. Is that right? This is because then we can selectively compress the files (depending on the file size for example).

**Comment by oleschoenburg** [comment]
> Now the metadata about compression will be stored in each file. Is that right? This is because then we can selectively compress the files (depending on the file size for example).

Yes, that's exactly right :+1:

**Comment by oleschoenburg** [comment]
> This is because then we can selectively compress the files (depending on the file size for example).

Additionally, we could also use it to store checksums for each file :eyes:

**Pull request merged**
