### PR TITLE
Remove withoutPayload method from Client API

### LINKED ISSUE #947: Remove the withoutPayload method from the ClientApi
see as reference https://github.com/zeebe-io/zeebe/issues/911

### PR DESCRIPTION
**Pull request by ChrisKujawa**
Removes the withoutPayload from the client api and uses instead the payload with a null value.

fixes zeebe-io/zeebe#947

### CODE REVIEW

**Comment by menski** [comment]
I rebased this branch on the latest develop to give it a better chance on Jenkins.

**Comment by saig0** [comment]
bors +r

**Review by saig0 — APPROVED** [review]

**Comment by menski** [comment]
bors retry

**Pull request merged**
