### PR TITLE
ci: add a code scanning job for snyk

### LINKED ISSUE #9245: Use Snyk to check for license issues or dependency vulnerabilities
**Description**

We should integrate Snyk into our CI to check for dependency vulnerabilities and licensing issues.

For licensing issues, refer to https://confluence.camunda.com/pages/viewpage.action?pageId=76485290 to create an appropriate policy.

For vulnerabilities, we want a check which fails when introducing vulnerabilities with `Medium` or higher vulnerabilities. To allow for exceptions when the vulnerability does not affect us, you can use a `.snyk` file which you can create/edit with the Snyk CLI.

We can use the [Snyk GitHub actions](https://github.com/snyk/actions) to help us out here, as they will be more flexible than the basic GitHub integration.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Adds a code quality jobs that triggers snyk and uploads the results to Github.

closes #9245

### CODE REVIEW

**Comment by oleschoenburg** [comment]
It honestly feels like snyk's action is not well thought out. There are two issues currently.
* Snyk thinks this is for the identity team and there appears to be no option to change that. I hope this won't mess with the snyk reports of the identity team!
> Testing /github/workspace...
Organization:      team-identity
Package manager:   maven
Target file:       pom.xml
Project name:      io.camunda:zeebe-bom
Open source:       no
Project path:      /github/workspace
Licenses:          enabled
* Scanning all projects produces sarif files that are rejected by github:

>  Warning: An error occurred checking the status of the delivery. Error: Code Scanning could not process the submitted SARIF file:
  rejecting SARIF, as there are more runs than allowed (40 > 15) It should still be processed in the background, but errors that occur during processing may not be reported.
  Analysis upload status is failed."

I don't see a way to work around either of these two issues.

**Comment by npepinpe** [comment]
Well that's a bummer. We can go with the normal GitHub integration, but I don't know how to make it work with the `.snyk` file from the repository :thinking:

**Comment by oleschoenburg** [comment]
And we wanted to use the `.snyk` file to ignore certain issues, right? I guess we can just do that on snyk.io for now?

**Comment by npepinpe** [comment]
It should also use our own team. We have a team-zeebe where get our reports and so on :thinking:

**Comment by oleschoenburg** [comment]
I did find https://github.com/marketplace/actions/sarif-multitool which supports merging multiple runs :sunglasses: 

Now, uploading the results to github works as expected: https://github.com/camunda/zeebe/pull/9301/checks?check_run_id=6322723129

**Comment by npepinpe** [comment]
Very nice! I think this is better than having to check in the Snyk dashboard imo

I think for the team, it's because we're in all the teams :smile: You might be able to overload the organization it picks up though using the args with `--org=team-zeebe`

**Comment by npepinpe** [comment]
There are some interesting notices: for example, this one https://github.com/camunda/zeebe/security/code-scanning/2160

Yes, SpotBugs has a license we don't want to add, however the dependency itself is always in the `provided` scope, so it's not actually included in the final artifact. I wouldn't want to ignore in general in case somebody changes the scope - I wonder why it doesn't work here (but the Snyk built-in GitHub integration actually detects that it's provided and doesn't flag it).

**Comment by oleschoenburg** [comment]
@npepinpe I finally got this working :tada: Do you already have a `.snyk` file lying around somewhere?

**Comment by oleschoenburg** [comment]
I think we could also just dismiss these alerts in GH instead of using a `.snyk` file? Not sure what makes more sense :thinking:

**Comment by npepinpe** [comment]
I don't know how visible it is when you dismiss the alerts. I liked the snyk file cause you then add the justification and open a PR, which means you're also sharing knowledge of the exception.

**Comment by npepinpe** [comment]
Can we reuse the merge sarif stuff with SpotBugs? Or maybe we're already doing this :thinking:

**Comment by oleschoenburg** [comment]
> Can we reuse the merge sarif stuff with SpotBugs? Or maybe we're already doing this

yeah I'm trying that out currently. 

> I don't have an example .snyk file, but maybe we could introduce one here with something?
Okay, I'll try to generate one then.

**Comment by npepinpe** [comment]
We can take a look at the licensing stuff tomorrow together. Not sure why it's not just picking up that they're provided dependencies. Hopefully they really are provided and this is a false positive :scream:

**Comment by oleschoenburg** [comment]
In the protocol module, spotbugs annotations are really provided. From the flattened pom:

```
    <dependency>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>spotbugs-annotations</artifactId>
      <version>4.7.0</version>
      <scope>provided</scope>
    </dependency>
```

I still can't get the ignore via `.snyk` working.

**Comment by oleschoenburg** [comment]
@npepinpe Explicitly marking the dependency as 'provided' does not suppress the snyk warning. I'm not sure what I'm doing wrong with the .snyk file either.

**Comment by npepinpe** [comment]
Hm, their GitHub integration (i.e. via the web UI, not using GitHub actions) can make that distinction, so I wonder what we're doing wrong here.

Looking at their GitHub, it looks like there is some issue with the dependency scopes and Maven: https://github.com/snyk/cli/issues/1574

Maybe the CLI is then not the right solution for us, and we should go back to the web UI. The downside of using that though:

- An extra tool to check (although we should check if they've improved the integration and maybe they can also now annotate PRs?)
- Ignore rules are not transparent anymore
- Unclear if the licensing issues will pick up the scopes properly still (should verify)

I'd be wary of adding an ignore rule right now via the `.snyk` file, because it doesn't seem like you can also specify the scope. So if we ignore `spotbugs-annotations` being LGPL because it's a false positive (as it's a provided dependency), but later someone deletes the `provided` - would Snyk still ignore it? Because we would want to fail a PR that would remove the scope or upgrade it to compile/runtime.

**Pull request closed without merging**
