### PR TITLE
fix(broker-core): close replication subscription when closing partition

### LINKED ISSUE #2436: When a follower becomes leader, it does not unsubscribe from the snapshot replication topic.
But it closes the executor (`StateReplication::close`) causing the following exception.
```
java.util.concurrent.RejectedExecutionException: Task io.atomix.cluster.messaging.impl.DefaultClusterEventService$InternalTopic$$Lambda$1293/950468340@253b2746 rejected from java.util.concurrent.ThreadPoolExecutor@2047076a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) ~[?:1.8.0_191]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:668) ~[?:1.8.0_191]
	at io.atomix.cluster.messaging.impl.DefaultClusterEventService$InternalTopic.lambda$subscribe$4(DefaultClusterEventService.java:440) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.DefaultClusterEventService$InternalSubscriber.apply(DefaultClusterEventService.java:578) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.DefaultClusterEventService$InternalSubscriber.apply(DefaultClusterEventService.java:545) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$registerHandler$29(NettyMessagingService.java:438) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.AbstractServerConnection.dispatch(AbstractServerConnection.java:40) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.LocalClientConnection.sendAsync(LocalClientConnection.java:35) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$sendAsync$2(NettyMessagingService.java:255) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.executeOnPooledConnection(NettyMessagingService.java:325) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.executeOnPooledConnection(NettyMessagingService.java:304) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAsync(NettyMessagingService.java:255) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.MessagingService.sendAsync(MessagingService.java:48) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.atomix.cluster.messaging.impl.DefaultClusterEventService.lambda$broadcast$0(DefaultClusterEventService.java:105) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_191]
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[?:1.8.0_191]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_191]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_191]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_191]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_191]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_191]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_191]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_191]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_191]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_191]
	at io.atomix.cluster.messaging.impl.DefaultClusterEventService.broadcast(DefaultClusterEventService.java:102) ~[atomix-cluster-3.2.0-20190430.073234-4.jar:?]
	at io.zeebe.broker.logstreams.state.StateReplication.replicate(StateReplication.java:51) ~[classes/:?]
```

### PR DESCRIPTION
**Pull request by saig0**
* when a partition is closed (e.g. a follower become the leader) then the subscription of the snapshot replication is closed

closes #2436

### CODE REVIEW

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Thanks for fixing this, please try to avoid the join call and make it more async as discussed with e.g. `whenComplete` etc.

**Review by ChrisKujawa — APPROVED** [review]

**Comment by Zelldon** [comment]
As discussed it would be safer to `#join`, so if we can't subscribe partition can't be installed. Otherwise we need to add more futures as return value on `#consume` and `#close` etc.

**Comment by saig0** [comment]
bors retry

**Pull request merged**
