### PR TITLE
fix(ci): use bash shell for maven run 

### LINKED ISSUE #10260: Detect duplicate test runs in GHA
**Description**

In our Jenkins pipeline, we had an extra step to detect duplicate test runs. This was added because we root caused corrupted test reports to being due to the same tests being ran twice in parallel. It would be useful to keep this check to ensure this never happens again, at least while we're running multiple test engines as well.

### PR DESCRIPTION
**Pull request by megglos**
## Description

Ensures a fail fast behavior as this includes [github setting](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference) `set -eo pipefail` which makes sure failures in a pipe chain are not lost and any maven test failure causes the build to fail.

## Related issues

closes #10260

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by megglos** [comment]
Provoked a failing test in the java client to verify the fix: https://github.com/camunda/zeebe/actions/runs/3090532047/jobs/4999459094

**Review by lenaschoenburg — APPROVED** [review]
:wrench: We could [set the default shell](https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs#setting-default-shell-and-working-directory) for the test workflow (and probably others) and then add a document that this is required for the `pipefail` behavior.

**Comment by megglos** [comment]
Provoked another failure with the recent changes of setting bash as default shell
https://github.com/camunda/zeebe/actions/runs/3090790514/jobs/5000049176

**Comment by megglos** [comment]
bors merge

**Pull request merged**
