### PR TITLE
ci(github): add new issues to ZDP/ZPA projects

### PR DESCRIPTION
**Pull request by megglos**
## Description

Adds new, reopened or transferred issues to the team's projects to be triaged.

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
Do we also want to add it to the ZPA board? Are they aware of this?

**Comment by megglos** [comment]
> Do we also want to add it to the ZPA board? Are they aware of this?

Good point, I pinged @abbasadel and will remove that for now, I will also check if I can add a condition to not add issues already assigned to e.g. the ZPA project already to the ZDP project. To avoid all new issues that might directly be associated with a project to end up in the ZDP project.

**Comment by abbasadel** [comment]
Looks good. 

In ZPA, we created Epic issues and sometimes split an issue into smaller tasks. 
Would be nice to exclude: 
- Any issue with a valid Epic value
- has label kind/task
- has an assignee already 

we can do that in a follow-up PR

**Review by abbasadel — APPROVED** [review]

**Comment by megglos** [comment]
I iterated over the workflow and changed the following:
 * only add to projects if not part of any project yet => this should avoid noise for issues already setup for one project during creation or when reopened
 * only add to project if not labeled: kind/task
 
I tested the GraphQL query via the GraphQL Explorer https://docs.github.com/en/graphql/overview/explorer
image

And also ran the workflow locally with some mocked event data with this command:
`act --container-architecture linux/amd64 -e issue.json -s GITHUB_TOKEN=*** -s PROJECT_ADMIN_TOKEN=*** issues -W .github/workflows/add-to-projects.yml`

with issue.json:
```
{
  "repository": {
    "name": "zeebe",
    "owner": {
      "name": "camunda"
    }
  },
  "issue": {
    "number": 14785
  }
}
```

Output of the project check:
```
[Assign new issues to the default projects/Add issue to ZDP/ZPA project if no project set yet]   🐳  docker cp src=/Users/megglos/.cache/act/octokit-graphql-action@v2.2.25/ dst=/var/run/act/actions/octokit-graphql-action@v2.2.25/
[Assign new issues to the default projects/Add issue to ZDP/ZPA project if no project set yet]   🐳  docker exec cmd=[node /var/run/act/actions/octokit-graphql-action@v2.2.25/dist/index.js] user= workdir=
| query getProjectCount($owner:String!, $repo:String!, $issue: Int!) {
|   repository(name: $repo, owner: $owner) {
|     issue: issue(number: $issue) {
|       projectsV2 {
|         totalCount
|       }
|     }
|   }
| }
|
| > mediaType: undefined
| > issue: 14785
| > repo: zeebe
| > owner: camunda
| < 200 623ms
[Assign new issues to the default projects/Add issue to ZDP/ZPA project if no project set yet]   ✅  Success - Main octokit/graphql-action@v2.2.25
[Assign new issues to the default projects/Add issue to ZDP/ZPA project if no project set yet]   ⚙  ::set-output:: data={
  "repository": {
    "issue": {
      "projectsV2": {
        "totalCount": 1
      }
    }
  }
}
[Assign new issues to the default projects/Add issue to ZDP/ZPA project if no project set yet] ⭐ Run Main echo "result=true" >> $GITHUB_OUTPUT
[Assign new issues to the default projects/Add issue to ZDP/ZPA project if no project set yet]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/has_project] user= workdir=
[Assign new issues to the default projects/Add issue to ZDP/ZPA project if no project set yet]   ✅  Success - Main echo "result=true" >> $GITHUB_OUTPUT
[Assign new issues to the default projects/Add issue to ZDP/ZPA project if no project set yet]   ⚙  ::set-output:: result=true
```

**Comment by megglos** [comment]
@abbasadel I would exclude:
> * Any issue with a valid Epic value
> * has an assignee already

for now, please follow-up if you see a need, thx!

**Comment by megglos** [comment]
bors merge

**Pull request merged**
