### PR TITLE
Update ElasticsearchClient and index templates for ES 7.12

### LINKED ISSUE #6868: Bulk request are deprecated
**Description**
Running a benchmark nowadays gives us endless logs of the elastic exporter which says that bulk request are deprecated. 

```
"request [POST http://elasticsearch-master:9200/_bulk] returned 1 warnings: [299 Elasticsearch-7.12.0-78722783c38caa25a70982b5b042074cde5d3b3a "[types removal] Specifying types in bulk requests is deprecated."]" 

```

Probably something we want to fix

Example
https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&authuser=1&project=zeebe-io&minLogLevel=0&expandAll=false&timestamp=2021-04-26T09:35:48.785880000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-stackdriver%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22broker%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-stackdriver%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster%22%0AjsonPayload.context.actor-name!%3D%22Broker-0-Exporter-3%22&scrollTimestamp=2021-04-26T09:33:50.113861000Z&pinnedLogId=m7cqp6g21p1lte&pinnedLogTimestamp=2021-04-26T09:33:50.113861Z

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR migrates the index templates from the legacy API to the current API. This notably changes the index template format, as well as the endpoint where they are PUT. Adds a first version to the template.

Removes deprecated type fields from bulk operations and the indexes themselves as well.

See https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html#_typeless_apis_in_7_0 regarding the removal of types and introduction of typeless APIs, and https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html about the new index template APIs (as opposed to the legacy ones at https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates-v1.html)

## Related issues

closes #6868

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
@menski - please delegate to someone more knowledgeable in ES on the Operate team

**Review by ralfpuchert — APPROVED** [review]
In Operate we use the [HighLevelRestClient](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high.html) which hides, for example, the current `put template` endpoint. So I needed to check the actual raw JSON request format. LGTM

**Review by korthout — APPROVED** [review]
LGTM 🎁

**Comment by korthout** [comment]
@npepinpe The build failed by the way (flakyness, but also actual test failures):
```
Failures: 

[2021-04-27T14:14:37.421Z] [ERROR] io.zeebe.exporter.ElasticsearchExporterAuthenticationIT.shouldExportRecords[basic authentication]

[2021-04-27T14:14:37.421Z] [ERROR]   Run 1: ElasticsearchExporterAuthenticationIT.shouldExportRecords:72->AbstractElasticsearchExporterIntegrationTestCase.assertIndexSettings:88 Expected number of replicas of index test-record_message-subscription_1.0.0-snapshot_2021-04-27 to be 0 but was 1

[2021-04-27T14:14:37.421Z] [ERROR]   Run 2: ElasticsearchExporterAuthenticationIT.shouldExportRecords:72->AbstractElasticsearchExporterIntegrationTestCase.assertIndexSettings:88 Expected number of replicas of index test-record_message-subscription_1.0.0-snapshot_2021-04-27 to be 0 but was 1

[2021-04-27T14:14:37.421Z] [ERROR]   Run 3: ElasticsearchExporterAuthenticationIT.shouldExportRecords:72->AbstractElasticsearchExporterIntegrationTestCase.assertIndexSettings:88 Expected number of replicas of index test-record_message-subscription_1.0.0-snapshot_2021-04-27 to be 0 but was 1

[2021-04-27T14:14:37.421Z] [ERROR]   Run 4: ElasticsearchExporterAuthenticationIT.shouldExportRecords:72->AbstractElasticsearchExporterIntegrationTestCase.assertIndexSettings:88 Expected number of replicas of index test-record_message-subscription_1.0.0-snapshot_2021-04-27 to be 0 but was 1
```

**Comment by npepinpe** [comment]
bors r-

I thought I'd checked and only the AdvertisedTest was flaky :thinking:

**Comment by npepinpe** [comment]
It seems we assert the number of replicas in tests after creating the index, and we expect them all to be 0 - however the default in 7.12 is 1 (see https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings).

It makes sense to me that we don't want replicas for any of them, nor do we want the query cache enabled - these are after all only used to be transformed into another model, so there's not much need for these settings (and having all primaries means a consistent data set).

I've fixed the values to be 0 on all index - not sure why we weren't doing it before. Possibly the default used to be 0.

**Comment by npepinpe** [comment]
@ralfpuchert - could you have a look at the last commit? I fixed the number of replicas to 0 (with my understanding being that we explicitly want all shards to be primary), and also disabled the query cache (I imagine it's not useful for us since we only want to ingest the data, not run many queries on those indexes). I'm asking since I think your team original made these modifications, so you probably know best what was the original intent.

**Review by ralfpuchert — APPROVED** [review]

**Comment by npepinpe** [comment]
bors retry

**Comment by npepinpe** [comment]
bors retry

**Comment by npepinpe** [comment]
bors retry

**Pull request merged**
