### PR TITLE
fix: set default encoding to UTF-8

### LINKED ISSUE #8579: Variable mapping replaces non-ascii characters with '?' in string values
**Describe the bug**

When using a simple variable mapping, non-ascii characters (eg. umlaute such as "ü") are replaced with '?'.

**To Reproduce**

1. Deploy this model: [non-ascii-mapping.bpmn](https://github.com/camunda-cloud/zeebe/files/7854611/non-ascii-mapping.bpmn.txt)
2. Start a process instance with a `source` variable: `{"source": "äüö"}`
3. After the mapping the variables will be `{"source": "äüö", "target": "???"}`

This is not reproducible with `1.2.9`. 

**Expected behavior**
Non-ascii characters are supported.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

* Sets the default encoding to UTF-8
* Switches the prod base image to `eclipse-temurin:17-jre-focal` which sets a system locale

## Related issues

closes #8579

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by oleschoenburg** [comment]
@Zelldon pointed out that we should also check if RocksDB is affected in any way. If that were the case, this PR is not enough to completely fix the issue and we'd have to ensure that the system locale is set correctly.

**Comment by oleschoenburg** [comment]
@Zelldon As far as I can tell, RocksDB is independent from system locale so this should be good to merge.

**Comment by Zelldon** [comment]
@oleschoenburg did you verified it somehow? Do you think it would matter if we just also add the LC.ALL=C.UTF-8 to the docker image?

**Review by ChrisKujawa — APPROVED** [review]
Thanks @oleschoenburg :rocket:

**Comment by oleschoenburg** [comment]
I'll manually backport the jvm arg commit to 1.2.

bors r+

**Comment by Zelldon** [comment]
Hm it seems the container went oom  :eyes:

**Comment by oleschoenburg** [comment]
Seems like a general issue with Jenkins right now, another unrelated PR had the same issue

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
