### PR TITLE
[Backport stable/8.1] Asynchronously prepare next segment to reduce peak write latency

### LINKED ISSUE #11444: Asynchronously prepare next segment to reduce peak write latency
In order to avoid spikes in our p95 and p99 latency due to segment creation, we should prototype creating (and pre-allocating) the next segment asynchronously. 

We can do this at various points in time. The easiest option is probably to trigger pre-creation whenever we need to create a new segment. Another, more advanced option, is to start pre-creating a segment when the writer has filled x% of the current segment.

# Support
- SUPPORT-15889

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Manual backport of https://github.com/camunda/zeebe/pull/11489 + https://github.com/camunda/zeebe/pull/11552 + https://github.com/camunda/zeebe/pull/11589

closes #11444

### CODE REVIEW

**Comment by oleschoenburg** [comment]
@deepthidevaki We could already backport the flaky test fixes here in this PR or we could do that later in a separate PR. Let me know if you have a preference.

**Comment by deepthidevaki** [comment]
>  We could already backport the flaky test fixes here in this PR or we could do that later in a separate PR. Let me know if you have a preference.

@oleschoenburg It would be better to backport it with this PR, so that we are not introducing flakiness in the meantime.

**Comment by oleschoenburg** [comment]
@deepthidevaki done :tada:

**Review by deepthidevaki — APPROVED** [review]
:100: 

bors merge

**Pull request merged**
