### PR TITLE
Publish GHA test results as report

### LINKED ISSUE #9035: GHA: Publish test reports
**Description**

It'd be nice to collect and publish the test results of running integration and unit tests from our GHA workflow so that developers can see exactly which tests are failing.

There are multiple actions that implement this:
1. https://github.com/marketplace/actions/publish-unit-test-results
2. https://github.com/marketplace/actions/surefire-report
3. https://github.com/marketplace/actions/junit-report-action

I've tried all three of them already. The first one is probably our best bet since it is the most feature complete. Two and three run into OOM for some of our tests.

follow-up of https://github.com/camunda/zeebe/pull/8968

### PR DESCRIPTION
**Pull request by korthout**
## Description

Publish GHA test results as report using https://github.com/EnricoMi/publish-unit-test-result-action.

This workflow is copied from [Zeebe Process Test](https://github.com/camunda/zeebe-process-test) where [this workflow](https://github.com/camunda/zeebe-process-test/blob/main/.github/workflows/publish-test-results.yml) has already been in use for some time. Some minor changes have been made to fit it to the zeebe repository.

## Related issues

closes #9035

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I don't want to get too much into bikeshedding but could we consider using `comment_mode: off`? I'd prefer to rely on the job summaries: https://github.com/EnricoMi/publish-unit-test-result-action#github-actions-job-summary

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]
Thanks for the changes @korthout! TIL you cannot comment on unchanged lines in a PR, so I will put the comments here.

❌ Currently, we are only publishing the test results in case of failure. We should change this to always publishing the results. This way we get a nice summary of the amount of tests we ran and the total time it took.

**Comment by remcowesterhoud** [comment]
@oleschoenburg Why do you not like the comments? Personally I feel it makes the test results a lot more visible. No one will look at the job summary of they have all passed successfully. But even if everything passed the summary still proved interesting information imo.

For example maybe something changed which causes our tests to not be ran anymore. The job will have succeeded but the summary will mention 0 tests have been passed. That's a good indicator that something is broken.

**Comment by oleschoenburg** [comment]
@remcowesterhoud Good points :+1: Let's just leave it on for now then.

**Comment by korthout** [comment]
Thanks for the review @remcowesterhoud. I've added a commit to resolve the issue, please have another look.

**Review by remcowesterhoud — APPROVED** [review]
Perfect, thanks!

**Comment by korthout** [comment]
🤞 bors merge

**Comment by korthout** [comment]
bors merge 🤞

**Comment by korthout** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
