### PR TITLE
Don't throw `BufferOverflowException` to trigger segment creation

### LINKED ISSUE #7606: Donot throw BufferOverflowException to trigger segment creation
Now when a segment is full the writer throws a BufferOverflowException which is caught by SegmentedJournalWriter and it creates a new segment. 

Using exception in an expected case is not ideal. We can indicate the error in another way. Returning `Either` would be an option.

Followup #6221

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Instead of throwing a `BufferOverFlowException` and catching it in the `SegmentedJournalWriter` we now return a `Either<SegmentFull, Integer>` to indicate if writing was successful. If creating a new segment does not resolve the error we throw the `SegmentFull` exception.

## Related issues

closes #7606 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
:tada: Looks good. Just some small comments.

**Review by deepthidevaki — APPROVED** [review]
:tada:

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
