### PR TITLE
Add content-type to OAuth request

### LINKED ISSUE #3536: Fail faster and more explicitly in credentials provider
**Current behavior** 
Currently, if an error occurs while request and appending oauth tokens to a request (in the Go client) that error is logged but not returned. I think the reasoning was trying to do the request without the token and, in the worst case, it would fail with an unauthenticated error. 

**Expected behavior**
However, it might make sense to return that error and wrap it with an unauthenticated error in the client instead of letting the request go through. Otherwise, the user will get an error that isn't fully representative of what actually happened (e.g., maybe the oauth endpoint is down or the timeout was set too low). I noticed this when testing timeouts because the returned error didn't actually wrap deadline exceeded one which was strange.

### PR DESCRIPTION
**Pull request by miguelpires**
Also improves error handling/wrapping

BREAKING CHANGE:
  * adds an error return type to the 'ApplyCredentials' method of the CredentialsProvider interface
  * unexports the noopCredentialsProvider implementation
## Description

The docs state that the content-type should be "application/x-www-form-urlencoded" (https://tools.ietf.org/html/rfc6749#page-42) but that doesn't work so it's set as "application/json"
## Related issues

closes #3536 

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
:fire: 

I didn't notice any test that we properly report the error when failing to refresh; can we add one?

**Comment by MiguelPires** [comment]
Unfortunately not in an ideal way. The error returned by gRPC doesn't wrap the original so I can't do `errors.Is(...)`. I can assert that the error message contains something like "deadline exceeded" or some errors message but that's it

**Comment by npepinpe** [comment]
Can we test that we're not doing this weird 2-requests type thing at least?

**Comment by MiguelPires** [comment]
No, because we're doing it. Even if the error occurs when request an access token, gRPC puts it into an UNAUTHENTICATED error. When that error is returned to the client, it's indistinguishable from a server-side one so do the usual stuff (try to update the token, etc)

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by MiguelPires** [comment]
The latest commit fixes the above mentioned issues:

Problem: A request was made even though getting an access token failed. This was because even though we returned an error, gRPC would wrap it with an UNAUTHENTICATED code. Since we retry errors with that code (to deal with the case where tokens become outdated and need to be refreshed), the creds provider would make another request to try to refresh the token. 
Solution: When the OAuth request fails, the creds provider returns an error with the gRPC CANCELED code, which then prevents gRPC from wrapping it in an UNAUTHENTICATED error. In turn, this prevents the creds provider from trying to refresh the token again.

**Pull request merged**
