### PR TITLE
Remove broken cache parts from smoke-test

### LINKED ISSUE #8265: Smoketest fails with versions missing for agrona
**Description**

Pull requests are seeing the following error failing the smoke tests:
>Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default) on project zeebe-protocol: Execution default of goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java failed: Plugin org.codehaus.mojo:exec-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:exec-maven-plugin:jar:3.0.0 -> uk.co.real-logic:sbe-tool:jar:1.25.0 -> org.agrona:agrona:jar:[1.13,1.14): No versions available for org.agrona:agrona:jar:[1.13,1.14) within specified range -> [Help 1]

### PR DESCRIPTION
**Pull request by korthout**
## Description

There seems to be an issue in the cached m2 folder that fails the Build
with Maven step because of a missing dependency. We should clear out the
cache and can remove this step after a successful pass on `develop`.

## Related issues

closes #8265 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by korthout** [comment]
@oleschoenburg Please have a look when you have some time. The idea is that this clears the cache on develop once it's merged. If there are issues with other pull requests, we can simply rebase. After some time we should be able to revert this change.

**Review by lenaschoenburg — APPROVED** [review]
Really surprising that there is no way to clear the cache manually. I wonder if it would make sense to additionally have a weekly job that clears the entire cache, just to be safe.

**Comment by korthout** [comment]
>Really surprising that there is no way to clear the cache manually.

It's their oldest still open feature request: https://github.com/actions/cache/issues/2 (this action is used internally by setup-java).

> I wonder if it would make sense to additionally have a weekly job that clears the entire cache, just to be safe.

That's an interesting idea. I'd be for this. However, I'm still not entirely sure how this cache works. They note that there is a maximum of 5GB of cache, after which it automatically evicts the earliest entries, and with the latest update this is increased to 10GB. We only use about 500MB though. What I don't yet know is whether it is one cache shared between all branches/pulls or a single one per repo. When we know that we could consider a strategy to evict the entire .m2/repository folder periodically.

**Comment by korthout** [comment]
I'll merge this for now to patch the problem. I'll also open an issue to improve the caching.

bors merge

**Comment by korthout** [comment]
It failed 😓 oops https://github.com/camunda-cloud/zeebe/actions/runs/1500608529

bors cancel

**Comment by oleschoenburg** [comment]
> What I don't yet know is whether it is one cache shared between all branches/pulls or a single one per repo

If I understand correctly, each branch has it's own cache. The cache of the default branch is shared. All caches summed up cannot exceed the 10GB limit. Based on https://github.com/actions/cache#cache-scopes and https://github.com/actions/cache#cache-limits

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
@oleschoenburg I've opened #8273 for the periodic eviction of the cache

**Pull request merged**
