### PR TITLE
chore(benchmark): remove obsolete files

### LINKED ISSUE #9066: Remove obsolete zbench folder
**Description**

This folder is obsolete: https://github.com/camunda/zeebe/blob/180f95473987e6c439b4ac00294ab1be8281bdae/benchmarks/project/zbench 

https://camunda.slack.com/archives/CSQ2E3BT4/p1649249014632819

> It can be deleted. We wanted to dogfeed and use the go client as well, but we have another project where we will do this, so for now we can go ahead and delete this

### PR DESCRIPTION
**Pull request by pihme**
## Description

Removes obsolete files

## Related issues

closes #9066

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:rocket:

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
bors merge

**Pull request merged**
