### PR TITLE
Migrate samples to gRPC client

### LINKED ISSUE #1454: Migrate samples to gRPC Java client

### PR DESCRIPTION
**Pull request by menski**
- removes topic subscription sample

closes #1454

### CODE REVIEW

**Comment by menski** [comment]
@saig0 the changes can already be reviewed. Merging is blocked by #1461.

**Review by saig0 — CHANGES_REQUESTED** [review]
I think the two pages `topic-create.md` and `topic-subscription-open.md` can be deleted.

**Comment by menski** [comment]
the files should now be deleted, sorry thought I deleted them already :thinking:

**Review by saig0 — APPROVED** [review]

**Pull request merged**
