### PR TITLE
style: apply formatting to 8.5 poms

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Formatting was broken, probably because the poms were changed when preparing for the next development iteration.

### CODE REVIEW

**Review by mustafadagher — APPROVED** [review]

**Comment by mustafadagher** [comment]
`Operate CI / run-tests / Test (pull_request)` keeps failing blocking the merge.

**Comment by Zelldon** [comment]
> `Operate CI / run-tests / Test (pull_request)` keeps failing blocking the merge.
> 
> Logs

@mustafadagher it shouldn't be the problem as they are not considered for the merge.

**Comment by Zelldon** [comment]
```
f2f9f, clock: SystemClock, configuration: {externalFunctionsEnabled: false}]
2024-04-05 04:52:21.665 [Broker-1] [zb-actors-0] [ZeebePartition-1] ERROR
      io.camunda.zeebe.broker.system - Failed to install partition 1
java.lang.IllegalStateException: Cannot upgrade to or from a pre-release version: UseOfPreReleaseVersion[from=8.5.0, to=8.5.1-SNAPSHOT]
	at io.camunda.zeebe.engine.state.migration.DbMigratorImpl.checkVersionCompatibility(DbMigratorImpl.java:112) ~[zeebe-workflow-engine-8.5.1-SNAPSHOT.jar:8.5.1-SNAPSHOT]
	at io.camunda.zeebe.engine.state.migration.DbMigratorImpl.runMigrations(DbMigratorImpl.java:78) ~[zeebe-workflow-engine-8.5.1-SNAPSHOT.jar:8.5.1-SNAPSHOT]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.MigrationTransitionStep.transitionTo(MigrationTransitionStep.java:52) ~[zeebe-broker-8.5.1-SNAPSHOT.jar:8.5.1-SNAPSHOT]
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionProcess.lambda$proceedWithTransition$1(PartitionTransitionProcess.java:94) ~[zeebe-broker-8.5.1-SNAPSHOT.jar:8.5.1-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.5.1-SNAPSHOT.jar:8.5.1-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.1-SNAPSHOT.jar:8.5.1-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.1-SNAPSHOT.jar:8.5.1-SNAPSHOT]
```

[Test results for [IT] QA Update Tests.zip](https://github.com/camunda/zeebe/files/14880109/Test.results.for.IT.QA.Update.Tests.zip)

**Comment by Zelldon** [comment]
Will be fixed with https://github.com/camunda/zeebe/pull/17318 thanks to @megglos and @oleschoenburg

**Pull request merged**
