### PR TITLE
fix(clients/go): fix JSON comparisons in zbctl tests

### LINKED ISSUE #6967: Diff in zbctl test output is incorrect
**Describe the bug**
In order to be able to compare `zbctl` command output against golden files, we ignore numbers since these could be unpredictable keys, positions or timestamps. We do this by changing all of them to the same dummy value before comparing. However, if the test fails for some reason, we print the diff with this dummy value which is misleading and may hide the cause of the failure. For instance, if the command being tested requires an argument and none is provided, the output should be "Error: requires at least 1 arg(s), only received 0" but the test output will be "Error: requires at least 1 arg(s), only received 1".

**To Reproduce**
Fail a test by removing a necessary argument.

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Fixes a couple of issues in the JSON comparisons:
* in case of failures, the generated diffs had incorrect numbers
* correctly ignores numbers (previously numbers were only considered equal if
they had the same number of digits)

## Related issues

closes #6967 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by MiguelPires** [comment]
@npepinpe I made some changes so the JSON tests are more robust. Previously, whitespace changes would be ignored but compacted command output would still fail if compared with a pretty-printed golden file. This reformats the JSON before comparing to avoid that as well. Sorry to be changing the PR after you approved but could you have another look?

**Review by npepinpe — APPROVED** [review]
:+1:

**Pull request merged**
