### PR TITLE
Add partition id to appender logs

### LINKED ISSUE #7875: Log message "Failed to append block" misses context
**Description**

Sometimes, especially one multiple leader changes after another, we see logs like: `Failed to append block with last event position 33678. This can happen during a leader change.`. [Example](https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2021-09-20T12:54:22.811729000Z&dateRangeStart=2021-09-20T12:13:26.797Z&dateRangeEnd=2021-09-20T14:13:26.797Z&project=camunda-cloud-240911&minLogLevel=0&customFacets=resource.labels.pod_name,jsonPayload.context.actor-name&limitCustomFacetWidth=false&advancedFilter=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22development-worker-1%22%0Aresource.labels.namespace_name%3D%22d248c2c3-59a6-4125-b467-f12d1c893f93-zeebe%22%0Aresource.labels.container_name%3D%22zeebe%22%0Alabels.%22k8s-pod%2Fstatefulset_kubernetes_io%2Fpod-name%22%3D%22zeebe-5%22&interval=JUMP_TO_TIME&scrollTimestamp=2021-09-20T12:54:21.993410000Z&pinnedLogId=75olagxd9xnhnic1&pinnedLogTimestamp=2021-09-20T12:54:21.993410Z)

The log message is missing context, like on which partition. It would be much easier to read if we see on which partition the append failed. Or add an context property like https://github.com/camunda-cloud/zeebe/issues/7859

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Add more context to log appender logs, to make it easier to detect when and for what the appending fails.

@npepinpe is it fine to backport this to 1.2?

## Related issues

closes https://github.com/camunda-cloud/zeebe/issues/7875

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
If it helps us fix bugs before the release definitely :ok_hand:

**Comment by deepthidevaki** [comment]
Why not add thread name to the filter? The same way actor name is displayed?

**Comment by Zelldon** [comment]
Yeah because the actor is then also displayed which doesn give me value :D but I see you didn't like it :D I think you're right it would be better if we have it in the context. I will work on this.

**Comment by deepthidevaki** [comment]
@Zelldon Can this be closed as this is addressed in #7885 ?

**Comment by Zelldon** [comment]
Yes @deepthidevaki :+1:

**Pull request closed without merging**
