### PR TITLE
Use JRE for production image

### LINKED ISSUE #8107: Use a smaller docker image for production
**Description**

By switching to `eclipse-temurin:17` as a base image for our docker images the size of our image increased by ~150MiB.
Because `eclipse-temurin` no longer distributes a jre variant we can try using `jlink` to generate a custom jre-like image.

```
jlink \
  --add-modules ALL-MODULE-PATH \
  --strip-debug \
  --no-man-pages \
  --no-header-files \
  --compress=2 \
  --output jre17-with-all-modules
```

See https://github.com/docker-library/docs/blob/master/eclipse-temurin/README.md#creating-a-jre-using-jlink

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Add a new build step that uses `jlink` to produce a JRE that can be used for production images.

## Related issues

closes #8107 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
- :question: What are the advantages of having the build stage and the JRE build stage separate? Just wondering
- :question: On the previous images, $JAVA_HOME was `/usr/local/openjdk-11` - any reason to switch it to `/opt/java/openjdk`? Is that because it's the path on the new Temurin builds? Just wondering as well :smile: 
- :question: If we're basing it off the new Temurin (i.e. from the path above), why debian and not ubuntu focal as a base image? Just wondering since the dev image (though we rarely use it tbh) will still be Temurin based.
- :wrench: Could we test this with some common community exporters? e.g. the https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/ and the https://github.com/camunda-community-hub/zeebe-kafka-exporter? As a smoke test that we can still load 3rd party code

**Comment by oleschoenburg** [comment]
> What are the advantages of having the build stage and the JRE build stage separate?

This way we can share the build stage between dev and prod images.

> On the previous images, $JAVA_HOME was /usr/local/openjdk-11 - any reason to switch it to /opt/java/openjdk?

/opt/java/openjdk is what eclipse-temurin uses.

>  we're basing it off the new Temurin (i.e. from the path above), why debian and not ubuntu focal as a base image

Good point, I guess there is not much difference and we should probably just use ubuntu focal.

> Could we test this with some common community exporters?

I'll try to test them today.

**Comment by oleschoenburg** [comment]
Both the Kafka and Hazelcast exporters are properly started by Zeebe.

**Review by npepinpe — APPROVED** [review]
Thanks for answering all my questions, looks good :+1:

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
