### PR TITLE
fix(gateway): use resource type provided in request instead of detecting

### LINKED ISSUE #1605: Duplicate "type" of BPMN file required
For deployment I have to do (c# - but it boils down to the protobuf definition):

           client.DeployWorkflow(new DeployWorkflowRequest
           {
               Workflows = {
                   new WorkflowRequestObject {
                       Name = "test.bpmn",
                       Type= WorkflowRequestObject.Types.ResourceType.Bpmn,
                       Definition= ByteString.CopyFrom(File.ReadAllBytes("test.bpmn"))
                   }
               }
           });

Now I have to define the name - and it has to have the ending ".bpmn" - otherwise I end up with an error

Status(StatusCode=Internal, Detail="Cannot resolve type of resource 'test'.")

Why is that? I have to define the type via enum as well. Shouldn't that be sufficient?

### PR DESCRIPTION
**Pull request by menski**
- gateway will check for resource type of request instead of always detecting
  the resource type again
- adds a new resource type FILE to gateway protocol which indicates that the
  gateway should determine the resource type based on the resource name

BREAKING CHANGE:
- gateway protocol resource type default value is now FILE instead of BPMN

closes #1605

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b933aac04f1f27e0886d03ba59d57e1421663cf1
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci, build**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b933aac04f1f27e0886d03ba59d57e1421663cf1
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci, build**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by menski** [comment]
@ThorbenLindhauer I removed the resource detection from the go client

**Review by ThorbenLindhauer — APPROVED** [review]

**Comment by ThorbenLindhauer** [comment]
bors retry

**Pull request merged**
