### PR TITLE
fix(snapshot): take snapshot after pending snapshot is added

### LINKED ISSUE #8212: When the creation of snapshots fails, the (internal) set of pending requests is not updated properly
**Describe the bug**
* The set [`FileBasedSnapshotStore#pendingSnapshots`](https://github.com/camunda-cloud/zeebe/blob/afba1c66efbe601dd014c3cb8cc191c557fcf870/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java#L67) contains failed pending snapshots who will never be removed from the set.
* This results in the set growing over time, especially, when the creation of snapshots fails often.

**To Reproduce**
1. Create a pending snapshot
2. Let the actual creation of the snapshot fail (here [`StateControllerImpl#takeSnapshot()`](https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/main/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImpl.java#L214))

**Observed Behavior**
* When the creation of the snapshot fails, then the [`#removePendingSnapshot()`](https://github.com/camunda-cloud/zeebe/blob/afba1c66efbe601dd014c3cb8cc191c557fcf870/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java#L368-L370) is called that does do anything.
* Afterward, the [`#addPendingSnapshot()`](https://github.com/camunda-cloud/zeebe/blob/afba1c66efbe601dd014c3cb8cc191c557fcf870/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedSnapshotStore.java#L372-L374) is called so that the pending snapshot is added to the set of pending snapshots.

**Expected behavior**
* The pending snapshot is removed from the set of pending snapshots properly.
* So that, it does not end up in a memory leak.

**Environment:**
 - Zeebe Version: 1.2.0

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

Ensure that adding a pending snapshot to the `FileBasedSnapshotStore#pendingSnapshots` happens before taking the actual snapshot.

## Related issues

closes #8212

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by romansmirnov** [comment]
@deepthidevaki, I did a deep dive into the actor scheduler, to get a better understanding of the difference between `#submit()` and `#run()` (the following is pretty simplified):
* `#run()`:
  * When calling `#run()` on the same actor, then the job is added to the `fastLaneJobs` as a first element
  * When calling `#run()` on a different actor, then the job is added at the end of the `submittedJobs` queue.
* `#submit()`: It always adds the job at the end of the `submittedJobs` queue.

While executing an `ActorTask`, jobs in the `fastLaneJobs` deque are executed first (but in the reverse they have been added to the deque). Afterward, when the `fastLaneJobs` deque is empty, the jobs within `submittedJobs` are executed in the order they have been added to the queue.

What happens now with the current implementation, in the case a transient snapshot is created:
* When `FileBasedSnapshotStore#addPendingSnapshot()` is called, a new job `x` is created to add the actual pending snapshot object and submitted to the queue by calling `#submit()`. In that case, the job ends up at the end of the `submittedJobs` queue.
* Subsequently, `FileBasedTransientSnapshot#take()` is being called, this submits a job `y` to take the actual snapshot by calling `#run()`. That way, the job `y` is added to the `fastLaneJobs` deque.

As a consequence, the job `y` is being executed before the job `x`. Hence, when the job `y` fails, the job `x` is still being executed and adds the failed pending snapshot to the set which is not expected in that scenario.

In the case of receiving snapshots (i.e., the Raft part), the set of pending snapshots is being updated accordingly, i.e., first it executes a job to add the pending snapshots to the set, and afterward, a job to apply the snapshot. The reason, therefore, is the actors are different between Raft and SnapshotStore/StateController.

However, I tried to find a fix that ensures that first the pending snapshots are added first and then everything else happens, in the case when the broker decides to take a snapshot. Therefore, I tested the following three approaches:

1. Call `#submit()` instead of `#run()` in [`FileBasedTransientSnapshot#take()`](https://github.com/camunda-cloud/zeebe/blob/efb11734897037b60b4addff814ecc7b26c421ca/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/FileBasedTransientSnapshot.java#L53):
```
@Override
public ActorFuture<Void> take(final Consumer<Path> takeSnapshot) {
  actor.submit(() -> takeInternal(takeSnapshot));
  return takenFuture;
}
```
But with that approach, the issue arises that the DB is closed before a snapshot is taken. Meaning, when taking a snapshot and closing the DB happens at the same time, taking a snapshot should happen first and then the DB should be closed. With changing it to `#submit()` this is not guaranteed anymore (see [`StateControllerTest#shouldCloseDbOnlyAfterTakingSnapshot`](https://github.com/camunda-cloud/zeebe/blob/efb11734897037b60b4addff814ecc7b26c421ca/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/StateControllerImplTest.java#L286-L298).

2. Add the pending snapshot directly in `FileBasedSnapshotStore#newTransientSnapshot()`
```
@Override
public Either<SnapshotException, TransientSnapshot> newTransientSnapshot(
    final long index,
    final long term,
    final long processedPosition,
    final long exportedPosition) {

  ...
  pendingSnapshots.add(newPendingSnapshot);
  ...
}
```

I think this solution works as long as we assume that the method `#newTransientSnapshot()` is executed by the correct actor. If this changes, it could be not that obvious that this implementation might cause problems.

3. Only call `#submit()` when it is another actor/thread, otherwise, just add the pending snapshot to the set:
```
private void addPendingSnapshot(final PersistableSnapshot pendingSnapshot) {
  final Runnable action = () -> pendingSnapshots.add(pendingSnapshot);

  if (!isCurrentActor()) {
    actor.submit(action);
  } else {
    action.run();
  }
}

private boolean isCurrentActor() {
  final var currentActorThread = ActorThread.current();

  if (currentActorThread != null) {
    final var task = currentActorThread.getCurrentTask();
    if (task != null) {
      return task.getActor() == this;
    }
  }

  return false;
}
```

So, if the execution is within the same actor context, then just do it, otherwise, submit a new job that will be executed by the expected actor.

What do you think? Do you see any downsides of this approach? Any other case to consider, that I missed?

**Comment by romansmirnov** [comment]
BTW, any idea how to test the fix? I couldn't find an appropriate way of testing it.

**Comment by deepthidevaki** [comment]
> While executing an ActorTask, jobs in the fastLaneJobs deque are executed first (but in the reverse they have been added to the deque). 

Ah. Good catch.

Your proposal 3 works. But I feel that it is not good to use this information with in the classes. 

Proposal 1 is also ok. It is not strictly necessary to close DB after snapshot is taken. We only want to ensure that they are not accessing DB concurrently. Since we cannot test concurrency easily, we test that it happens in this order. If we change this order, the worst thing that happen is that we might see error logs saying we cannot take snapshot because it is already closed while this is an expected case.


Alternatives I thought of:

1. Also use actor::submit in removePendingSnapshots. This will ensure that add and remove is called in the expected order. But this is a hacky solution because "take" happens before it is added to the pending snapshots.
2. Execute everything in `newTransientSnapshot` with in actor::run. No need to call actor::run when adding pending snapshots. So snapshot will be added to pendingSnapshot immediately after transient snapshot is created. So the new interface will be `ActorFuture<TransientSnapshot> newTransientSnapshot`. For me this seems to be a better solution, as it is not assuming much how this method is being called. (`newReceivedSnapshot` remains unchanged as it is called from Raft, making it async requires more refactoring in raft. )

**Comment by romansmirnov** [comment]
@deepthidevaki,

Thanks for your additional input. It's helpful to get your point of view.

I agree with you having the actor information/check in the `FileBasedSnapshotStore` is not the best way of doing it. But okay, maybe a few thoughts on the suggested alternatives:

Re 1- I agree that this is a hacky solution. I didn't consider this option further in previous thinking, because in my opinion, adding the pending snapshot to the set should happen before executing `take`. So basically, everything should happen in the right order, otherwise, someone might stumble over it when applying any changes to the current implementation, for example, if the set of pending snapshots should be used within `take`. But of course, currently, this problem does not exist, and we could take precautions by adding a comment at the specific places.

Re 2- Get your point, but would it potentially cause a concurrent modification, i.e., two threads (actor and raft) try to add a pending snapshot to the set? To my understanding, this is why currently `#submit()` is being called when adding a pending snapshot. Right?

I have the feeling that all the possible solutions have different downsides and we need just to decide what is okay for us (i.e., what can we accept) and what not 😃 I would still advocate for the solution proposed with this PR. Why? The change is very local, it does not require any other changes, it's clear what's happening (i.e., when a job is submitted and when not), and it's transparent that the `#add...()` method can be called from different threads/actors and that change/implementation ensures that the modification happens one-by-one subsequently.

What do you think?

**Comment by deepthidevaki** [comment]
> Re 2- Get your point, but would it potentially cause a concurrent modification, i.e., two threads (actor and raft) try to add a pending snapshot to the set?

No. My proposal is to execute `newTransientSnapshot` in actor::run. So it is guaranteed to be executed in the snapshot store actor. So there won't be any concurrent access. It would be something like the following:
```
public ActorFuture<TransientSnapshot> newTransientSnapshot(
      final long index,
      final long term,
      final long processedPosition,
      final long exportedPosition) {
    final CompletableActorFuture future = new CompletableActorFuture();
    actor.run(
        () -> {
          final var newSnapshotId =
              new FileBasedSnapshotMetadata(index, term, processedPosition, exportedPosition);

          ....
          
          
          final var newPendingSnapshot =
              new FileBasedTransientSnapshot(newSnapshotId, directory, this, actor);

          pendingSnapshots.add(newPendingSnapshot);

          future.complete(newPendingSnapshot);
        });

    return future;
  }
```

But as you said, this would need some more refactoring for all the callers of this method.

> I would still advocate for the solution proposed with this PR. Why? The change is very local, it does not require any other changes,

Agree that the required changes are minimal with this approach. We can then may be go with this approach and see if we can improve it later :+1:

**Comment by romansmirnov** [comment]
> No. My proposal is to execute newTransientSnapshot in actor::run. So it is guaranteed to be executed in the snapshot store actor. So there won't be any concurrent access. It would be something like the following:

Ah, I see. That means, `#newReceivedSnapshot()` and its usage of `addPendingSnapshot()` would remain as it is. Is my understanding correct?

**Comment by romansmirnov** [comment]
> Agree that the required changes are minimal with this approach. We can then may be go with this approach and see if we can improve it later 👍

If you don't mind, could you please then approve the PR? 😃

**Review by deepthidevaki — APPROVED** [review]
:+1: thanks

**Comment by romansmirnov** [comment]
bors merge

**Pull request merged**
