### PR TITLE
Migrate the process instance element instance

### LINKED ISSUE #15111: Migrate the process instance itself successfully
In the processor for the `ProcessInstanceMigration` command:

- look up the process instance, and the target process definition
- append a `ProcessInstance:ELEMENT_MIGRATED` event for the process instance with adjusted data 
  - `processDefinitionKey`: the key of the target process definition
  - `bpmnProcessId`: the BPMN ID of the target process definition
  - `version`: the version of the target process definition
  - `elementId`: changes to the mapped element ID (note that the mapping may define the sourceElementId and the targetElementId as equivalent, in which case it stays the same)

~~We cannot yet add a test case for this because there must be at least one active child element instance inside the process instance **and** we cannot yet migrate those.~~ EDIT: We could add a test case, and change it later

Blocked by:
- https://github.com/camunda/zeebe/issues/15107
- https://github.com/camunda/zeebe/issues/15110

### PR DESCRIPTION
**Pull request by korthout**
## Description

> [!WARNING]  
> This PR is based on https://github.com/camunda/zeebe/pull/15217. We should merge that first.

Migrates the process instance's element instance by appending an `ELEMENT_MIGRATED` event for it.

## Related issues

closes #15111

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by berkaycanbc — APPROVED** [review]
LGTM @korthout ! 🚀 

Your comments in the commits helped me a lot with my questions related to implementation. ❤️

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
Wow, the Integration tests took longer than the allowed 20min, but there were no failures.

bors retry

**Comment by korthout** [comment]
Hmm, same issue twice. Did I break something?

**Comment by korthout** [comment]
I can't figure out what went wrong.. The ITs simply take too long, but the logs don't indicate why. But in the CI of this pull request they take 7m only.

bors merge

**Comment by korthout** [comment]
Bors merges were likely failing due to https://github.com/camunda/zeebe/issues/15343

**Pull request merged**
