### PR TITLE
Release 8.0.0

### PR DESCRIPTION
**Pull request by pihme**
## Description

Merge release 8.0.0 back into main

### CODE REVIEW

**Comment by pihme** [comment]
Needs to wait for merge of #9062

**Comment by npepinpe** [comment]
Let me know if you'd like to me to take over here :+1:

**Comment by pihme** [comment]
> Let me know if you'd like to me to take over here 

@npepinpe  Ah, yes, that was the plan. Sorry for not communicating that clearer.

**Comment by npepinpe** [comment]
I rebased onto main to fix the conflicts, and had to regenerate the Go compatibility symbols as some code had been merged in between the release and now, and it wasn't reflected in the v8 renaming PR. I also had to add some new revapi ignored changes for the protocol, again due to a PR merged before the release but after the code freeze, which marked some changes as "breaking". The commit message describes more in detail what it is.

For the build, the GHA CI fails because of https://github.com/camunda/zeebe/pull/9060, and the Jenkins had a flaky test (but nothing new).

I think this is merge-able then. And if we missed something, we can fix it as it won't affect anything until the next release in October.

**Review by npepinpe — APPROVED** [review]

**Comment by pihme** [comment]
bors merge

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
