### PR TITLE
chore(dist): disable log4j shutdown hook

### LINKED ISSUE #3857: Disable Log4j shutdown hook for distribution
**Description**

In the official distribution, using `StandaloneBroker` and `StandaloneGateway`, we use log4j2 as our logging backend. By default log4j2 registers a shutdown hook to clean up after itself. The unfortunate side effect here is that we also have a shutdown hook, where we trigger the graceful shutdown of the broker/gateway.

As shutdown hooks run in parallel (? or at the very least the order does not seem guaranteed), a warning is printed during shutdown, and not everything is logged, which means we can missing errors occurring on shutdown.

**Proposal**

I would propose we disable the shutdown hook and manually shutdown log4j2 ourselves as part of our shutdown process to ensure we can log during shutdown.

This can be achieved by adding the attribute `shutdownHook="disable"` in the XML configuration, or setting the system property `-Dlog4j.shutdownHookEnabled=false` on start up.

To shutdown log4j manually in the `StandaloneBroker` and `StandaloneGateway` shutdown hooks, we can call `LogManager.shutdown()`.

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Shutdown log4j in our shutdown hooks so there is no race condition between zeebe and the log manager shutting down.

## Related issues

closes #3857 

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

Thanks!

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
