### PR TITLE
fix: c8run performance improvements for operate UI

### PR DESCRIPTION
**Pull request by jessesimpson36**
## Description

Operate UI is a little slow to update, and setting these env vars should help make things  a little faster.

```diff
+export CAMUNDA_OPERATE_IMPORTER_READERBACKOFF=1000
+export ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_DELAY=1
+export ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
```

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Review by drodriguez-305 — APPROVED** [review]

**Comment by jessesimpson36** [comment]
I noticed this patch causes a stacktrace to occur when deploying a model:

```
io.camunda.operate.exceptions.OperateRuntimeException: Exception occurred for alias [zeebe-record-process-instance], while obtaining next Zeebe records batch: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
	at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.readNextBatchByPositionAndPartition(ElasticsearchRecordsReader.java:324) ~[operate-importer-8.6.0.jar:8.6.0]
	at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.readAndScheduleNextBatch(ElasticsearchRecordsReader.java:175) ~[operate-importer-8.6.0.jar:8.6.0]
	at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.readAndScheduleNextBatch(ElasticsearchRecordsReader.java:151) ~[operate-importer-8.6.0.jar:8.6.0]
	at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.run(ElasticsearchRecordsReader.java:147) ~[operate-importer-8.6.0.jar:8.6.0]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.13.jar:6.1.13]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:178) ~[elasticsearch-7.17.24.jar:7.17.24]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2484) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2461) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2184) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
	at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.lambda$readNextBatchByPositionAndPartition$1(ElasticsearchRecordsReader.java:313) ~[operate-importer-8.6.0.jar:8.6.0]
	at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:178) ~[micrometer-core-1.13.4.jar:1.13.4]
	at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.withTimer(ElasticsearchRecordsReader.java:522) ~[operate-importer-8.6.0.jar:8.6.0]
	at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.readNextBatchByPositionAndPartition(ElasticsearchRecordsReader.java:313) ~[operate-importer-8.6.0.jar:8.6.0]
	... 10 more
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://localhost:9200], URI [/zeebe-record-process-instance/_search?routing=1&typed_keys=true&max_concurrent_shard_requests=5&request_cache=false&search_type=query_then_fetch&batched_reduce_size=512], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[{"type":"no_shard_available_action_exception","reason":"[jessesimpson-work][127.0.0.1:9300][indices:data/read/search[phase/query]]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":2,"index":"zeebe-record_process-instance_8.6.0_2024-10-10","node":"pidBfwcWRbKvbV-MHUwlNQ","reason":{"type":"no_shard_available_action_exception","reason":"[jessesimpson-work][127.0.0.1:9300][indices:data/read/search[phase/query]]"}}]},"status":503}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292) ~[elasticsearch-rest-client-8.13.4.jar:8.13.4]
		at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
		at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
		at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
		at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1367) ~[elasticsearch-rest-high-level-client-7.17.24.jar:8.13.4]
		at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.lambda$readNextBatchByPositionAndPartition$1(ElasticsearchRecordsReader.java:313) ~[operate-importer-8.6.0.jar:8.6.0]
		at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:178) ~[micrometer-core-1.13.4.jar:1.13.4]
		at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.withTimer(ElasticsearchRecordsReader.java:522) ~[operate-importer-8.6.0.jar:8.6.0]
		at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.readNextBatchByPositionAndPartition(ElasticsearchRecordsReader.java:313) ~[operate-importer-8.6.0.jar:8.6.0]
		at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.readAndScheduleNextBatch(ElasticsearchRecordsReader.java:175) ~[operate-importer-8.6.0.jar:8.6.0]
		at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.readAndScheduleNextBatch(ElasticsearchRecordsReader.java:151) ~[operate-importer-8.6.0.jar:8.6.0]
		at io.camunda.operate.zeebeimport.elasticsearch.ElasticsearchRecordsReader.run(ElasticsearchRecordsReader.java:147) ~[operate-importer-8.6.0.jar:8.6.0]
		at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.13.jar:6.1.13]
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
		at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

So I won't merge this until I understand what the stacktrace is about.

**Comment by jonathanlukas** [comment]
@jessesimpson36 in our docker distro, we just set the bulk size to 1:

https://github.com/camunda/camunda-platform/blob/main/docker-compose/camunda-8.6/docker-compose.yaml#L32

It could be related to the delay being too low and ES being flooded with requests.

**Comment by jessesimpson36** [comment]
The above error message doesn't appear to be present anymore, so I think we're safe to move forward with this change.

**Comment by jessesimpson36** [comment]
The suggestion for these edits were mentioned in slack by roman+felix. that's why I'm not just setting the bulk size to 1.

**Review by drodriguez-305 — APPROVED** [review]
LGTM

**Pull request merged**
