### PR TITLE
Add a job completion REST endpoint

### LINKED ISSUE #20080: Migrate the Complete Job gRPC API to REST
## Description

* The Camunda 8 REST API contains a job completion endpoint at `POST /v2/jobs/{jobKey}/completion` providing the same functionality as the [gRPC endpoint](https://docs.camunda.io/docs/apis-tools/zeebe-api/gateway-service/#completejob-rpc).
* The endpoint is featured in the OpenAPI description as (internally) [described](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.slfl0844trwy).
* The endpoint allows sending variables as JSON object.

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

Add an endpoint to the REST API for completing jobs.

## Related issues

closes #20080

### CODE REVIEW

**Comment by nicpuppa** [comment]
@tmetzke Job Activation tests are failing 👀

**Comment by tmetzke** [comment]
> @tmetzke Job Activation tests are failing 👀

Huh, that's not cool, I'll have a look

**Comment by nicpuppa** [comment]
Hey @tmetzke, can I take over this PR from you and ask you to review it after my updates ?

**Comment by tmetzke** [comment]
> Hey @tmetzke, can I take over this PR from you and ask you to review it after my updates ?

Sounds great but I think I can't review this because I opened it 😄

**Comment by nicpuppa** [comment]
> We can close this and you can create a new PR from the branch?

You can write comments, I just want to rebase it and adjust the code 👍

**Comment by tmetzke** [comment]
> > We can close this and you can create a new PR from the branch?
> 
> You can write comments, I just want to rebase it and adjust the code 👍

OK let's try that 👍

**Comment by nicpuppa** [comment]
I rebased this PR on main, and made some adjustment. Please @tmetzke have a look

**Comment by tmetzke** [comment]
The `JobControllerRoundRobinTest` currently is inherently flaky, the success of the test you fixed depends on the execution order of the tests. I will attempt to fix this with another commit.

**Comment by tmetzke** [comment]
Rebased again onto `main` and adjusted the round robin tests.

**Comment by nicpuppa** [comment]
What is going on ? 🤔

**Comment by tmetzke** [comment]
> What is going on ? 🤔

Looks like I missed the rest controller import in the test, let me have a look again

**Comment by nicpuppa** [comment]
> Looks like I missed the rest controller import in the test, let me have a look again

I can build the branch locally without problems

**Review by nicpuppa — APPROVED** [review]

**Pull request merged**
