### PR TITLE
Simplify REST data model

### LINKED ISSUE #19986: Simplify user task update data model
**Description**

The user task update REST endpoint uses a data model `UserTaskUpdateRequest` that nests another data model `Changeset` at attribute `changeset`.
The nested data model reference is consumed as an `allOf`, indicating that we extend
the original reference. However, we don't actually extend it except for adding more
description on top and making it nullable.

This can be straightened out by moving the description and nullable attributes to the
referenced data model directly and using it simply as an unaltered reference.

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

The user task update REST endpoint uses a data model that nests another data model. The nested data model reference is consumed as an `allOf`, indicating that we extend the original reference. However, we don't actually extend it execpt for adding more description on top and making it nullable.

This can be straightened out to moving the description and nullable attributes to the referenced data model directly and using it simply as an unaltered reference.

## Related issues

closes #19986

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:confused: This was painful to review not because of you, but for some reason the diff showed up as all the file was deleted and replaced, so I couldn't look at the specific changes :thinking:

**Comment by tmetzke** [comment]
> 😕 This was painful to review not because of you, but for some reason the diff showed up as all the file was deleted and replaced, so I couldn't look at the specific changes 🤔

Let me check, maybe it updated the line endings on Windows and that is why.

**Comment by tmetzke** [comment]
OK, that was actually it, yes, corrected it 👍

**Comment by tmetzke** [comment]
Meh, the generated client DTO for the changeset is a plain Java map now. We have to adjust the way we set attributes. Not a big deal though.

**Comment by tmetzke** [comment]
Rebased onto `main`, updated the new client user task command tests to consider a Java map, and successfully tested locally with `openapi-generator-maven-plugin` version `7.7.0`.

**Comment by tmetzke** [comment]
@npepinpe, just a quick checkup since I changed more things in the meantime

**Review by npepinpe — APPROVED** [review]
:+1:

**Pull request merged**
