### PR TITLE
Merge zbctl with the Go client

### LINKED ISSUE #1740: Merge zbctl into go client source tree
There is not real reason why we have `clients/go` and `clients/zbctl`. Instead zbctl should be merged into `clients/go`. We could reorganize the `clients/go` folder to follow the directory layout from https://github.com/golang-standards/project-layout

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Moves `zbctl` into the Go client's `cmd` dir and changes the previous `cmd` package in `zbctl` to a `commands` package to avoid confusion. This PR also renames `resources` to `testdata` to be more consistent with other Go projects. A follow-up issue #3383 with continue to make layout improvements in the client.

## Related issues

closes #1740 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:tada:

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
