### PR TITLE
[Backport 0.24] compact after exporters removed

### LINKED ISSUE #5105: Will not compact after exporters are removed
**Describe the bug**

Taking snapshot and compaction will not happen anymore after broker is reconfigured in way where no exporters are configured anymore.

**To Reproduce**

```java

  @Test
  public void shouldCompactWhenExporterHasBeenRemoved() {
    // given
    final Broker broker = clusteringRule.getBroker(0);
    ControllableExporter.updatePosition(true);
    fillSegments(broker, SEGMENT_COUNT);
    clusteringRule.getClock().addTime(SNAPSHOT_PERIOD);
    // create first snapshot with exporter positions
    final var firstSnapshot = clusteringRule.waitForSnapshotAtBroker(broker);

    // restart with no exporter
    final var brokerCfg = clusteringRule.getBrokerCfg(0);
    brokerCfg.setExporters(Map.of());
    clusteringRule.stopBroker(0);
    clusteringRule.startBroker(0);

    final var filledSegmentCount = SEGMENT_COUNT * 2;
    writeSegments(broker, filledSegmentCount);

    // when triggering new snapshot creation
    final var segmentsCount = getSegmentsCount(broker);
    clusteringRule.getClock().addTime(SNAPSHOT_PERIOD);
    final var secondSnapshot = clusteringRule.waitForSnapshotAtBroker(broker);

    // then
    assertThat(firstSnapshot).isNotEqualTo(secondSnapshot);
    await()
        .untilAsserted(
            () ->
                assertThat(getSegmentsCount(broker))
                    .describedAs("Expected less segments after a snapshot is taken")
                    .isLessThan(segmentsCount));
  }
```

**Expected behavior**

Snapshotting and compaction is doen without issues.

**Log/Stacktrace**

Following log indicates that no snapshots are taken.
```
21:40:04.444 [] [raft-server-0-raft-partition-partition-1] DEBUG io.atomix.storage.journal.SegmentedJournal - Created segment: JournalSegment{id=15, version=1, index=620}
21:40:04.447 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] WARN  io.zeebe.logstreams.snapshot - Failed to obtain a pending snapshot directory for position 617
```

**Environment:**
 - Zeebe Version: 0.24.0

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Backports https://github.com/zeebe-io/zeebe/pull/5106

## Related issues

closes #5105

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

**Review by korthout — APPROVED** [review]

**Comment by korthout** [comment]
Please also consider backport to 0.23

**Comment by Zelldon** [comment]
Yes im working on it... not that easy as the other thing 😅

**Comment by Zelldon** [comment]
Bors r+

**Comment by npepinpe** [comment]
bors retry

and succeed please :crossed_fingers:

**Pull request merged**
