### PR TITLE
chore(maven): add trailing slashes to new Artifactory URL

### PR DESCRIPTION
**Pull request by cmur2**
## Description

I got review feedback that it is recommended to have trailing slashes to the URL so I'm adding them for consistency.

## Related issues

Related to INFRA-3107

### CODE REVIEW

**Review by chaima-mnsr — APPROVED** [review]

**Comment by cmur2** [comment]
bors merge

**Comment by oleschoenburg** [comment]
bors retry

**Comment by cmur2** [comment]
bors retry

**Comment by cmur2** [comment]
bors retry

**Comment by oleschoenburg** [comment]
If this run also fails I can merge directly, no risk of merge conflicts here.

**Pull request merged**
