### PR TITLE
Update modeling docs

### LINKED ISSUE #4293: Docs out of date: Zeebe Modeller UI has changed
For example, in chapter 4.6.3. Timer Events, paragraph “Additional Resources” > “Using the BPMN modeler” there is a video tutorial that seems to refer to a previous Zeebe Modeler version, which offers the Timer Event in the palette.

See: https://forum.zeebe.io/t/cant-find-service-task-or-intermediate-timer-event-in-the-zeebe-modeler/870

### PR DESCRIPTION
**Pull request by pinussilvestrus**
## Description

The aligned palette and context pad layout, which was introduced with the v0.8.0 version of the Zeebe Modeler, followed to some confusion without much announcement around that (cf. https://github.com/zeebe-io/zeebe-modeler/issues/204).

That's why we decided to update the docs a bit to clarify some aspects (using the replace menu to model all task/event/gateway types). 

## Related issues

Related to zeebe-io/zeebe-modeler#204
Closes #4293 

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
@zeebe-io/modeling-dev and @zeebe-io/zeebe please feel free to look over the changes.

**Review by saig0 — APPROVED** [review]
Thanks a lot :+1:

**Comment by saig0** [comment]
bors retry

**Pull request merged**
