### PR TITLE
refactor: rename zeebe-client-java artifact

### LINKED ISSUE #26102: Rename the java client artifact
Redo https://github.com/camunda/camunda/issues/19482

* Rename the artifact from `zeebe-client-java` to `camunda-client-java`
* This will not be backward compatible, no mirroring of `zeebe-client-java` is required

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes https://github.com/camunda/camunda/issues/26102

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
👍 Changes make sense to me.
ℹ️ Always hard to say if all spots have been considered. We could try a release dry-run with a non-existing version. That should yield any references to the Zeebe client as those wouldn't exist and fail the Maven build.

**Comment by houssain-barouni** [comment]
> 👍 Changes make sense to me. ℹ️ Always hard to say if all spots have been considered. We could try a release dry-run with a non-existing version. That should yield any references to the Zeebe client as those wouldn't exist and fail the Maven build.

I run a dry run release on this branch here https://github.com/camunda/camunda/actions/runs/12349903781
Let's see how it goes

**Comment by houssain-barouni** [comment]
> > 👍 Changes make sense to me. ℹ️ Always hard to say if all spots have been considered. We could try a release dry-run with a non-existing version. That should yield any references to the Zeebe client as those wouldn't exist and fail the Maven build.
> 
> I ran a dry run release on this branch here https://github.com/camunda/camunda/actions/runs/12349903781 Let's see how it goes

Do you think I need to use a different version here https://github.com/camunda/camunda/blob/a0bbb78814bdf13009c087a6d2aee58e1b406af1/.github/workflows/camunda-platform-release-main-dry-run.yml#L22 @tmetzke ?

**Comment by tmetzke** [comment]
I think that version should be fine since we never released it so all components can only use what is built in the reactor.
However, I think you ran the release test on the main branch, didn't you? I think it needs to run on your branch here.

**Comment by houssain-barouni** [comment]
> I think that version should be fine since we never released it so all components can only use what is built in the reactor. However, I think you ran the release test on the main branch, didn't you? I think it needs to run on your branch here.

I am using the workflow from main, but I specified that I want to release this branch
image

**Pull request merged**
