### PR TITLE
test(qa): verify backup when partition is replicated

### LINKED ISSUE #10387: Add integration test for backup and restore
Test following scenarios:
- Cluster multiple partitions
    - [x] Backup can be taken, get status returns correct status and backup can be restored
    - [x] Backup is also triggered via inter partition messages.
- Cluster with multiple partitions and replication factor 3
    - [ ] After a leader change, get status of old backup returns correct status
    - [ ] After a leader change, new backup can be taken
    - [ ] ~After a leader change, a backup that is started by the previous broker but not completed is marked as failed~

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

- Verify backup when the partition is replicated.

## Related issues

closes #10387

### CODE REVIEW

**Review by lenaschoenburg — COMMENTED** [review]
Code looks good but I think to close #10387 we'd need an additional test case to verify that previously started backups will be marked as failed during startup. That might be difficult to test reliably though. Happy to discuss ideas or to just drop that test case from #10387 and test this somewhere else

**Comment by deepthidevaki** [comment]
> Code looks good but I think to close #10387 we'd need an additional test case to verify that previously started backups will be marked as failed during startup. That might be difficult to test reliably though. Happy to discuss ideas or to just drop that test case from #10387 and test this somewhere else.

:see_no_evil: Now I remember why I left the PR open without requesting review :smile: 

It was a difficult to test. One way to simulate failover with inprogress bakcup, was to mark the backup explicitly as inprogress after it is completed. But this was not possible without exposing internal format of S3BackupStore. Allowing custom backup stores would have been useful in this case. We are testing this in BackupService unit tests. May be that is enough. What do you think?

**Comment by oleschoenburg** [comment]
> We are testing this in BackupService unit tests. May be that is enough.

I agree then, that's enough.

> Allowing custom backup stores would have been useful in this case

Good point, would be nice to have a "local" backup store for testing that exposes a bit more knobs to create these scenarios for tests.

**Review by lenaschoenburg — APPROVED** [review]

**Comment by deepthidevaki** [comment]
bors merge

**Pull request merged**
