### PR TITLE
fix(engine): skip missing job when iterating state

### PR DESCRIPTION
**Pull request by npepinpe**
- when iterating over activatable or deadlines column family, skip entry and remove it if there is no corresponding job
- error is still logged as job missing

related to #2515

### CODE REVIEW

**Comment by npepinpe** [comment]
One small thing, I would argue here might be a good case for a custom exception, as I specifically want to only handle cases where the job is missing. I don't think here anything else throws `IllegalStateException`, but it would definitely safer, since we really only want to handle a special case.

**Comment by Zelldon** [comment]
With this unit test I can reproduce it:

```

  @Test
  public void shouldFailOnTimeoutJob() {
    // given
    final long key = 1L;
    final JobRecord jobRecord = newJobRecord();

    jobState.create(key, jobRecord);
    jobState.activate(key, jobRecord);
    jobState.complete(key, jobRecord.setDeadline(System.currentTimeMillis()));

    // when
    jobState.forEachTimedOutEntry(System.currentTimeMillis(), (jobKey, job) ->
    {
      // fails
      return true;
    });
  }
```

**Comment by npepinpe** [comment]
That's because you're changing the deadline on the complete call. If we always use the deadline which is set on the activate call then it passes.

But that's a good hint at what might be happening...except why only sometimes?

**Comment by Zelldon** [comment]
Yeah I know why this fails :sweat_smile: this was an example how we can prove that or find the issue :sweat_smile:

**Comment by Zelldon** [comment]
I think it is somehow related to the reprocessing where we activate the job again with a new deadline

**Comment by npepinpe** [comment]
One thing we could do for cleaning up is to use what is in the state as opposed to the given record. That should prevent those issues.

**Comment by npepinpe** [comment]
Anyway, good catch @Zelldon :+1:

**Comment by npepinpe** [comment]
Now that you mention it, it's super obvious; we use the `currentTimeMillis()` in `JobBatchActivateProcessor#collectJobsToActivate`, which isn't deterministic.

https://github.com/zeebe-io/zeebe/blob/f321aa55426a1240781b914b665b2e5342a9b5f2/engine/src/main/java/io/zeebe/engine/processor/workflow/job/JobBatchActivateProcessor.java#L123

**Comment by Zelldon** [comment]
I'm now able to reproduce this problem in an engine unit test

```
  @Test
  public void shouldTimeOutAfterReprocessing() {
    // given
    final long jobKey = ENGINE.createJob(jobType, PROCESS_ID).getKey();
    final long timeout = 10L;

    ENGINE.jobs().withType(jobType).withTimeout(timeout).activate();
    ENGINE.increaseTime(JobTimeoutTrigger.TIME_OUT_POLLING_INTERVAL);
    jobRecords(TIME_OUT).withRecordKey(jobKey).getFirst();

    final long jobKey2 = ENGINE.createJob(jobType, PROCESS_ID).getKey();
    ENGINE.jobs().withType(jobType).activate();
    ENGINE.job().withKey(jobKey).complete();

    // when
    ENGINE.reprocess();
    ENGINE.jobs().withType(jobType).activate();

    // then
    ENGINE.increaseTime(JobTimeoutTrigger.TIME_OUT_POLLING_INTERVAL);
    jobRecords(TIME_OUT).withRecordKey(jobKey2).getFirst();
  }
```

**Comment by npepinpe** [comment]
Closing in favor of #2772 which fixes the cause

**Pull request closed without merging**
