### PR TITLE
Increase maxInstanceDuration in Weekly Benchmarks

### LINKED ISSUE #16143: Increase maxInstanceDuration in Weekly Benchmarks
### Description

There was a test [failure](https://camunda.slack.com/archives/C013MEVQ4M9/p1706285282317609) in one of our weekly e2e tests. From the logs and metrics it looks like a starter applies a [backoff after 10 minutes](https://github.com/camunda/zeebe-e2e-test/blob/main/loadgen/src/main/java/io/camunda/zeebe/e2e/loadgen/starter/Starter.java#L27) but since the instance duration is set to [15 minutes by default](https://github.com/camunda/zeebe/blob/main/.github/workflows/e2e-testbench.yaml#L36), the test fails before the processing catches up.

For that reason, we would like to increase the instance duration to 40m to see if it is actually catching up with the processing.

### Proposed Solution
`maxInstanceDuration` needs to be added here as 40m: https://github.com/camunda/zeebe/blob/main/.github/workflows/weekly-e2e.yml#L79

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

There was a test failure in one of our weekly e2e tests. From the logs and metrics it looks like a load issue. At some point, workers were not able to activate and complete the job fast enough. But we did not observe anything abnormal with in Zeebe. Since this is not a performance test, we did not investigate this further. To handle such loads, the starter already applies a backoff after 10 minutes but since the instance duration is set to 15 minutes by default, the test fails before the processing catches up.

For that reason, we would like to increase the instance duration to 40m to see if it is actually catching up with the processing.

## Related issues

closes #16143 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
Thanks @berkaycanbc. I have updated the PR description to include a bit more details and reasoning behind this change.

**Comment by berkaycanbc** [comment]
commitlint is showing false positive, triggering merge.

bors merge

**Comment by berkaycanbc** [comment]
> This PR was included in a batch that successfully built, but then failed to merge into main. It will not be retried.
> 
> Additional information:
> 
> ```json
> {"message":"Changes must be made through the merge queue You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.","documentation_url":"https://docs.github.com/articles/about-protected-branches"}
> ```

@deepthidevaki any ideas?

**Comment by deepthidevaki** [comment]
> Changes must be made through the merge queue

No more bors. You can use merge via merge queue. Just click "Merge when ready".

**Pull request merged**
