### PR TITLE
feat: onboarded new centrilized plugin interceptor ZEES

### PR DESCRIPTION
**Pull request by igpetrov**
## Description

feat: onboarded new centrilized plugin interceptor

Separate PR for Zeebe Exporter ElasticSearch

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

Related to: https://github.com/camunda/camunda/issues/21563

### CODE REVIEW

**Review by megglos — APPROVED** [review]
LGTM!

**Comment by cmur2** [comment]
Hi, jumping in here because this PR is an interesting case for the CI. This PR apparently had green CI on the PR (otherwise it couldn't have been added to the merge queue). But in the merge queue [all Zeebe-related CI checks failed immediately](https://github.com/camunda/camunda/actions/runs/10770216642/job/29863138787) with Java compilation errors leading to a huge CI error spike that usually should be caught before the merge queue, but wasn't:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project zeebe-elasticsearch-exporter: Compilation failure
Error:  /runner/_work/camunda/camunda/zeebe/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchClient.java:[73,5] no suitable constructor found for ElasticsearchClient(io.camunda.zeebe.exporter.ElasticsearchExporterConfiguration,io.camunda.zeebe.exporter.BulkIndexRequest,org.elasticsearch.client.RestClient,io.camunda.zeebe.exporter.RecordIndexRouter,io.camunda.zeebe.exporter.TemplateReader,<nulltype>,io.micrometer.core.instrument.MeterRegistry)
Error:      constructor io.camunda.zeebe.exporter.ElasticsearchClient.ElasticsearchClient(io.camunda.zeebe.exporter.ElasticsearchExporterConfiguration,io.micrometer.core.instrument.MeterRegistry) is not applicable
Error:        (actual and formal argument lists differ in length)
Error:      constructor io.camunda.zeebe.exporter.ElasticsearchClient.ElasticsearchClient(io.camunda.zeebe.exporter.ElasticsearchExporterConfiguration,io.micrometer.core.instrument.MeterRegistry,org.elasticsearch.client.RestClient) is not applicable
Error:        (actual and formal argument lists differ in length)
Error:      constructor io.camunda.zeebe.exporter.ElasticsearchClient.ElasticsearchClient(io.camunda.zeebe.exporter.ElasticsearchExporterConfiguration,io.camunda.zeebe.exporter.BulkIndexRequest,org.elasticsearch.client.RestClient,io.camunda.zeebe.exporter.RecordIndexRouter,io.camunda.zeebe.exporter.TemplateReader,io.camunda.zeebe.exporter.ElasticsearchMetrics) is not applicable
Error:        (actual and formal argument lists differ in length)
Error:  -> [Help 1]
```

The spike today (usually we have < 5% failures here):

image

Anyone has any idea how this change could pass CI on the PR but failed so dramatically in the merge queue?

**Comment by igpetrov** [comment]
Hi @cmur2, there was a commit merged presumably on Friday that changed constructor API. I identified it 30 minutes ago and fixed it

**Comment by igpetrov** [comment]
Similar to this one https://github.com/camunda/camunda/pull/22012

**Pull request merged**
