### PR TITLE
ci(jenkins): removal of Jenkins ci and jobs

### LINKED ISSUE #9138: Remove Jenkins CI Pipeline leftovers
We can clean up our Jenkins configuration, for example the Jenkinsfile and various scripts in the `.ci` folder.
We'll have to be a bit careful since some of the scripts might be used for other Jenkins pipelines that we haven't replaced yet, such as the release builds or QA runs.

blocked by #9137

### PR DESCRIPTION
**Pull request by megglos**
## Description

Removes all Jenkins related setup except the github repository scan of the zeebe-io org as there are projects that make use of Jenkins still. With the release job being migrated to GHA with https://github.com/camunda/zeebe/issues/10992 and the 8.2.0-alpha3 as well as 8.0 and 8.1 patches being successfully published, this also removes the deprecated release job on Jenkins.

I already seeded the jenkins ci from this branch the outcome is as expected:
image

Given the [camunda org job setup is gone](https://github.com/camunda/zeebe/pull/11376/files#diff-0c2b5bccf4a2a4bc264fe1fae76a5b633068e747e59c90aa226c055dd473faba) by Jenkins seeding from main, I see no need for a backport, as Jenkins won't be building zeebe at all anymore.

## Related issues

closes #9138

### CODE REVIEW

**Comment by cmur2** [comment]
Thanks for the review request, I'll put it on my todo list for Monday :)

**Review by cmur2 — APPROVED** [review]
Looks good from my side. There are 2 follow-ups I see:

1. https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/ (and others like [zeeqs](https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeeqs/)) still exists from the time before migrating the repo to `camunda/zeebe` (or community hub) and should be deleted to free some space
1. there are a couple of credentials that Jenkins now provides but are unused by remaining jobs, e.g. `camunda-dockerhub` - if we have a fulll list of unused credentials, the Infra team could remove them from Jenkins as well as a cleanup

**Comment by megglos** [comment]
> Looks good from my side. There are 2 follow-ups I see:
> 
> 1. https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/ (and others like [zeeqs](https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeeqs/)) still exists from the time before migrating the repo to `camunda/zeebe` (or community hub) and should be deleted to free some space
> 2. there are a couple of credentials that Jenkins now provides but are unused by remaining jobs, e.g. `camunda-dockerhub` - if we have a fulll list of unused credentials, the Infra team could remove them from Jenkins as well as a cleanup

thanks for the feedback!
In terms of 1. what would be the best way to delete those leftovers?

**Review by lenaschoenburg — APPROVED** [review]
:tada: 

:wrench: If possible, please remove `Jenkinsfile` too.

**Comment by megglos** [comment]
> 🎉
> 
> 🔧 If possible, please remove `Jenkinsfile` too.

great catch, I actually wanted to 😅

**Comment by cmur2** [comment]
> In terms of 1. what would be the best way to delete those leftovers?

I think the [Orphaned Item Strategy](https://github.com/camunda/zeebe/blob/main/.ci/jobs/github_zeebe_io.dsl#L47-L51) on https://ci.zeebe.camunda.cloud/job/zeebe-io/configure is too lenient and thus keeps deleted repos (considered "items" on this level of the org) around.

I see we mostly set it 0 or 1 *days of item age* (not the number of items) in [camunda](https://github.com/search?q=org%3Acamunda+orphanedItemStrategy&type=code).

**Comment by megglos** [comment]
> 2\. there are a couple of credentials that Jenkins now provides but are unused by remaining jobs, e.g. `camunda-dockerhub` - if we have a fulll list of unused credentials, the Infra team could remove them from Jenkins as well as a cleanup
@cmur2 
sure, let's follow-up on that for sure! Can you record this as one of the infra tasks and poke me to collect those as input for the task?

**Comment by cmur2** [comment]
> > 2. there are a couple of credentials that Jenkins now provides but are unused by remaining jobs, e.g. `camunda-dockerhub` - if we have a fulll list of unused credentials, the Infra team could remove them from Jenkins as well as a cleanup
> > @cmur2
> > sure, let's follow-up on that for sure! Can you record this as one of the infra tasks and poke me to collect those as input for the task?

Ticket created in https://github.com/camunda/team-infrastructure/issues/305

**Pull request merged**
