### PR TITLE
fix(engine): pending snapshot is set after write position is received

### LINKED ISSUE #3348: Snapshots are marked as valid too early
**Describe the bug**

I was wondering about the following log statements, where it seems 
```
I 2019-11-09T14:58:23.060828483Z 2019-11-09 14:58:23.060 [partition-1-processor-snapshot-director] [zeebe-0.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Creation of snapshot for partition-1-processor took 520 ms.
 
I 2019-11-09T14:58:23.061013959Z 2019-11-09 14:58:23.060 [partition-1-processor-snapshot-director] [zeebe-0.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Snapshot is valid. Move snapshot from /usr/local/zeebe/data/partition-1/state/snapshots/tmp to /usr/local/zeebe/data/partition-1/state/snapshots/59283435983272.
 
I 2019-11-09T14:58:23.061447895Z 2019-11-09 14:58:23.061 [partition-1-processor-snapshot-director] [zeebe-0.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Ensure max snapshot count 3, will delete 1 snapshot(s).
 
I 2019-11-09T14:58:23.065046378Z 2019-11-09 14:58:23.064 [partition-1-processor-snapshot-director] [zeebe-0.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Purged snapshot /usr/local/zeebe/data/partition-1/state/snapshots/57470958050192
 
I 2019-11-09T14:58:23.065065429Z 2019-11-09 14:58:23.064 [partition-1-processor-snapshot-director] [zeebe-0.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Search for orphaned snapshots below oldest valid snapshot position 58072254702608
 
I 2019-11-09T14:58:23.065355436Z 2019-11-09 14:58:23.065 [partition-1-processor-snapshot-director] [zeebe-0.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Start replicating latest snapshot /usr/local/zeebe/data/partition-1/state/snapshots/59283435983272
 
I 2019-11-09T14:58:23.079498347Z 2019-11-09 14:58:23.079 [partition-1-processor-snapshot-director] [zeebe-0.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-1] DEBUG io.zeebe.logstreams.snapshot - Finished taking snapshot, need to wait until last written event position 59283436418616 is committed, current commit position is 59283436339344. After that snapshot can be marked as valid.
 
I 2019-11-09T14:58:23.926636683Z 2019-11-09 14:58:23.926 [partition-1-processor-snapshot-director] [zeebe-0.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-1] DEBUG io.zeebe.logstreams - Delete data from log stream until position '58072254702608' (address: '897904286032').
 
I 2019-11-09T14:58:24.051576611Z 2019-11-09 14:58:24.051 [partition-1-processor-snapshot-director] [zeebe-0.zeebe.long-running.svc.cluster.local:26501-zb-fs-workers-1] INFO  io.zeebe.logstreams - Deleted 2 segments from log storage (207 to 209).
 
I 2019-11-09T14:58:24.097057137Z 2019-11-09 14:58:24.096 [] [replication-5] DEBUG io.zeebe.logstreams.snapshot - Consume snapshot chunk 003720.sst
 
```

`Finished taking snapshot` was printed last and before it validates the snapshot which was before taken. But with a deeper look I found the real issue. The log statements before are related to the same snapshot. 

The `takeSnapshot` method sets the pending to true and takes the snapshot. It will update the lasWrittenPosition after the future is complete, but `onCommitCheck` is also called on each commit update.
```java
  private void takeSnapshot() {
    pendingSnapshot = true;
    createSnapshot(snapshotController::takeTempSnapshot);

    final ActorFuture<Long> lastWrittenPosition = streamProcessor.getLastWrittenPositionAsync();
    actor.runOnCompletion(
        lastWrittenPosition,
        (endPosition, error) -> {
          if (error == null) {
            final long commitPosition = logStream.getCommitPosition();
            lastWrittenEventPosition = endPosition;

            LOG.debug(LOG_MSG_WAIT_UNTIL_COMMITTED, endPosition, commitPosition);
            onCommitCheck();

          } else {
            pendingSnapshot = false;
            LOG.error(ERROR_MSG_ON_RESOLVE_WRITTEN_POS, error);
          }
        });
  }
```

This means the condition on the next commit change will directly become true, since the `lastWrittenEventPosition` is an old position (or for example 0 on start). 
```
  private void onCommitCheck() {
    final long currentCommitPosition = logStream.getCommitPosition();

    if (pendingSnapshot && currentCommitPosition >= lastWrittenEventPosition) {
      try {

        lastValidSnapshotPosition = lowerBoundSnapshotPosition;
        snapshotController.moveValidSnapshot(lowerBoundSnapshotPosition);
        snapshotController.replicateLatestSnapshot(actor::submit);

      } catch (Exception ex) {
        LOG.error(ERROR_MSG_MOVE_SNAPSHOT, ex);
      } finally {
        pendingSnapshot = false;
      }
    }
  }
```
This causes that we directly validate the snapshot on the next commit change and probably also delete data.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

 * it happend that snapshots are take and directly became valid because the pending flag was set to early

## Related issues

closes #3348 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by saig0 — COMMENTED** [review]
Setting `pendingSnapshot = true;` later solves the issue but now it could happen that `prepareTakingSnapshot()` takes a snapshot before the previous one is valid. Right?

**Comment by Zelldon** [comment]
Ah true. I had at first the lastWrittenPosition  as `Long`, which is reset like the pending. And a Null check in the onCommit method. Makes this probably more robust what do you think?

**Comment by saig0** [comment]
"Robust" is maybe not the right word for this code :rofl:  

But sounds good :+1: Looking forward to #3214 :rocket:

**Review by saig0 — APPROVED** [review]
bors r+

**Pull request merged**
