### PR TITLE
Build benchmark applications

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Benchmark application is now part of our build pipeline. It uses the latest version of Zeebe and the tags are changed to snapshot. As follow up I would like that we building the docker images automatically. See https://github.com/zeebe-io/zeebe/issues/5608

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 22d739c67f92ec6ef5c78539237200e41d1b211d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by pihme — APPROVED** [review]

**Pull request merged**
