### PR TITLE
refactor: reduce `ActorJob` size

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description
Reduces the size of `ActorJob` by removing unnecessary fields.

Before:
```
io.camunda.zeebe.scheduler.ActorJob object internals:
OFF  SZ                  TYPE DESCRIPTION                 VALUE
  0   8                       (object header: mark)       N/A
  8   4                       (object header: class)      N/A
 12   4   TaskSchedulingState ActorJob.schedulingState    N/A
 16   8                  long ActorJob.scheduledAt        N/A
 24   4                 Actor ActorJob.actor              N/A
 28   4             ActorTask ActorJob.task               N/A
 32   4           ActorThread ActorJob.actorThread        N/A
 36   4           Callable<?> ActorJob.callable           N/A
 40   4              Runnable ActorJob.runnable           N/A
 44   4                Object ActorJob.invocationResult   N/A
 48   4           ActorFuture ActorJob.resultFuture       N/A
 52   4     ActorSubscription ActorJob.subscription       N/A
Instance size: 56 bytes
Space losses: 0 bytes internal + 0 bytes external = 0 bytes total
```

After:
```
io.camunda.zeebe.scheduler.ActorJob object internals:
OFF  SZ                  TYPE DESCRIPTION                VALUE
  0   8                       (object header: mark)      N/A
  8   4                       (object header: class)     N/A
 12   4   TaskSchedulingState ActorJob.schedulingState   N/A
 16   8                  long ActorJob.scheduledAt       N/A
 24   4             ActorTask ActorJob.task              N/A
 28   4           Callable<?> ActorJob.callable          N/A
 32   4              Runnable ActorJob.runnable          N/A
 36   4           ActorFuture ActorJob.resultFuture      N/A
 40   4     ActorSubscription ActorJob.subscription      N/A
 44   4                       (object alignment gap)     
Instance size: 48 bytes
Space losses: 0 bytes internal + 4 bytes external = 4 bytes total
```

### CODE REVIEW

**Comment by npepinpe** [comment]
What's the impact of doing this? We don't have too many actors, so I assume it's not pure memory usage, but some other optimization (e.g. cache line usage - though I guess also not this one, since it was already fitting before).

**Comment by lenaschoenburg** [comment]
> What's the impact of doing this?

This is reducing the size of Actor**Job**, not actor tasks. Since we have a lot more of those, reducing the memory usage should have at least a minor impact. 
The other benefit is just reduced complexity because there's just fewer fields to keep track of.

**Comment by npepinpe** [comment]
> This is reducing the size of ActorJob, not actor tasks. Since we have a lot more of those, reducing the memory usage should have at least a minor impact.

:see_no_evil: Task, job, no way anyone could confuse the two right :smile:

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
