### PR TITLE
feat(topology): reject partition leave if it has no replica

### LINKED ISSUE #15728: Single member cannot leave a partition
If a partition has only one replica, attempting to leave from it must fail. Otherwise, it can accidentally result in data loss.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

To prevent accidental loss of data, we reject partition leave request if there is only one replica. This scenario would not happen if we use the scale request API. But it can happen when one uses the internal fine-grained api to join or leave individual partitions.

## Related issues

closes #15728

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Thanks :+1: 

Looks like you need some more tests though.

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors retry

**Pull request merged**
