### PR TITLE
chore(benchmarks, tests): Remove usage of the deprecated property and method

### LINKED ISSUE #5741: Remove usage BrokerContactPoint in benchmarks.
**Description**

This is a part of #2973 that I intentionally missed in the #5373. Needs to replace usage of `io.zeebe.client.ZeebeClientBuilder#brokerContactPoint` to `io.zeebe.client.ZeebeClientBuilder#gatewayAddress` and `io.zeebe.client.ClientProperties#BROKER_CONTACTPOINT` to `io.zeebe.client.ClientProperties#GATEWAY_ADDRESS` in the benchmarks since it depends on the current version of Java client.

P.S. There are some usages in tests, we should replace this too.

### PR DESCRIPTION
**Pull request by aivinog1**
## Related issues

closes #5741 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
Thanks @aivinog1 :tada:

**Comment by npepinpe** [comment]
bors retry

**Comment by npepinpe** [comment]
No worries, it's due to flaky tests which we're working on in different PRs :+1: Nothing you need to do from your side :slightly_smiling_face:

**Comment by aivinog1** [comment]
@npepinpe Ok, thanks :)

**Comment by npepinpe** [comment]
Oh wait, this time was worst, hm, seems bors didn't even wait for the build to go through :thinking: Looks like something weird with bors

**Comment by npepinpe** [comment]
bors retry

**Comment by aivinog1** [comment]
@npepinpe Maybe let's give a bors another shot? :)

**Comment by npepinpe** [comment]
bors retry

**Pull request merged**
