### PR TITLE
Fix state byte order

### LINKED ISSUE #1386: Create a central constant for the ByteOrder
Currently we use on the state management side every where `ByteOrder.Little_Endian`. We should use an own constant, so we could easily change the ordering and we are sure that use the right one.

See #1364

depends on #1195

### PR DESCRIPTION
**Pull request by ChrisKujawa**
closes #1386

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
bors r+

**Comment by Zelldon** [comment]
bors retry

**Pull request merged**
