### PR TITLE
Release 8.0.3

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR merges the release commits for 8.0.3.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by pihme — APPROVED** [review]

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
OK, this is pretty consistent. Wonder why it fails only when merging but not in its own CI :thinking:

**Comment by npepinpe** [comment]
bors try

**Comment by oleschoenburg** [comment]
@npepinpe Could it be that the new resource limits are being picked up by Jenkins but not the TCC changes? That'd explain why it's failing so consistently now.

**Comment by npepinpe** [comment]
But the new resource limits are on main, not on stable/8.0 or this branch :thinking:

**Comment by npepinpe** [comment]
You can see in the log output (https://ci.zeebe.camunda.cloud/job/camunda/job/zeebe/job/staging/386/consoleFull) that it picked up the podSpec with the correct resource limits (18 CPUs, etc.)

**Comment by npepinpe** [comment]
Doing a normal try seems to work...so why would merging fail so consistently? :thinking:

**Pull request merged**
