### PR TITLE
chore(broker): close and reopen logstream appender on role transition

### LINKED ISSUE #3966: Close appender immediately on becoming follower
**Description**

Currently we use a reference counting approach to keep track of the writers writing to the logstream. When those writers are not closed properly (#3965 ), appender and hence the dispatcher is not closed. When the node becomes leader again, it will then use the old dispatcher instead of creating a new one. This would cause it use the old positions instead of updating the positions by reading the latest log. Since only the leader is allowed to write, it would be better to close the appender and dispatcher immediately on becoming the follower. The writers that are using this dispatcher should handle the case when they are trying to write to the already closed dispatcher.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

- Exposed an api to open and close logstream appender. 
- On role transitions, always close the appender. Only on leader transition open appender.

Alternative solution is to close and reopen LogStream on role transitions. Opening a draft PR so that we can discuss the alternatives.

## Related issues

closes #3966

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by npepinpe** [comment]
What are the downsides of just closing the logstream on transitions? It would be simpler, wouldn't it?

**Comment by deepthidevaki** [comment]
Some minor problems that I saw
- On logstream start, it seek to end to update the commit position. Depending on the performance of seek, this might be an overhead.
- ZeebePartition registers a commitListener on raft. There is a potential race condition here during close and restart of logstream. There might be a case where the commit position is not updated.

**Comment by Zelldon** [comment]
I think logstream object should not be reused. If you close it you should throw it away. On transition you create a new one.

**Comment by deepthidevaki** [comment]
> I think logstream object should not be reused. If you close it you should throw it away. On transition you create a new one.

Yes. We have to create a new one, if we close the logstream.

**Comment by deepthidevaki** [comment]
I have also a version where we close logstream on transition. Here  https://github.com/zeebe-io/zeebe/commit/188678a5136dbace8cdf0f64c5211592f62fb882 is the potential case for missing notification on commit. I guess it is ok on the leader. Because leader will not start writing before logstream is opened. So nothing to commit until stream processor is up. But on transition to follower, there could be parallel writes and commits happening while logstream is opened. We also don't use commit position on followers now , so :woman_shrugging:

**Comment by deepthidevaki** [comment]
Added an ugly test for this https://github.com/zeebe-io/zeebe/pull/3976/commits/68242c83ec7b0f83e78de5fd4a45aa7be17830d0  @npepinpe Something like we discussed before -> force a leader change without restart.

**Comment by deepthidevaki** [comment]
Closing this in favor of #3995

**Pull request closed without merging**
