### PR TITLE
deps(renovate): add all 8.x stable branches as base

### PR DESCRIPTION
**Pull request by megglos**
## Description

Will make sure new 8.x stable branches are picked up.

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Thanks :+1: 
Did the old `matchBaseBranches` not work? :exploding_head:

**Comment by megglos** [comment]
> Thanks 👍 Did the old `matchBaseBranches` not work? 🤯

I fear so, the debug log also lacks the `\` to properly escape the `/`:
```
DEBUG: Repository config
{
...
    "packageRules": [
      {
        "matchBaseBranches": [
          "/^stable/.*"
        ],
        "matchUpdateTypes": [
          "major",
          "minor"
        ],
        "enabled": false
      }
    ],
...
```
the unescaped `/` should actually end the regex according to the renovate docs
https://docs.renovatebot.com/configuration-options/#basebranches

**Comment by megglos** [comment]
bors retry

**Comment by megglos** [comment]
bors retry

**Comment by megglos** [comment]
bors abort

**Comment by megglos** [comment]
bors merge

**Pull request merged**
