### PR TITLE
Migrate to atomix

### LINKED ISSUE #1874: Spike: Use atomix multi-raft protocol for zb-logstream
This spike should validate how a custom distributed primitive in atomix could look like for the zb-logstream, see https://atomix.io/docs/latest/user-manual/custom-primitives/overview/

The idea is to implement a primitive type Logstream, with the API `public long append(DirectBuffer bytes)` (some bytes), which returns the position the bytes where appended.

We can then run experiments to understand when the bytes are append to which node, what happens if raft discards entries and nodes are not available and so on.

In this step we will not implement stream processing for the logstream.

### LINKED ISSUE #1996: Replace zb-raft leader election with atomix leader election for stream processor management
Goal decouple stream processing from replication. At the moment stream processors use the raft replication also as leader election for starting and stopping of processing events. We should decouple this as the stream processors can run on every node which has the log locally. This is the first step needed to replace raft replication with atomix.

### LINKED ISSUE #2009: Use atomix for log replication
Write a distributed log primitive with append() interface.
 - logStorageAppender, instead of appending the events to logStorage, send the request to the distributed log.
 - When the events are committed, the primitive will notify a listener (logStorageAppender) which is running on all replicas. The listener can then actually writes the event to logStorage. The primitive does the replication and only notifies that the event is committed but doesn't write to the logstream. This way, we can make  changes to our codebase minimal. Later we can improve the primitive to write directly to logStorage.
- We will still use our raft leader election to start and stop stream-processors.  This step will decouple stream processor from having to run on the leader of log-partition. Later we can change the leader election to use atomix.

### LINKED ISSUE #2013: Gateway handles not initialized topology correctly
Sometimes the gateway will receive a request before it is aware of any broker. Before the migration to atomix we handled this by waiting for the first topology response from the cluster. With the change to atomix the gateway now listens to membership events, which means this strategy is not compatible anymore. We should check if we always handle the non-existence of a topology gracefully.

### LINKED ISSUE #2055: Use a custom partitioner for distributed log primitive
Now, any request to the distributed-log of partition "i" is internally mapped to a different partition, because atomix internally hashes the name of the primitive to find the partition. We can implement a [custom partitioner](https://atomix.io/docs/latest/user-manual/primitives/primitive-protocols/#protocol-partitioners) to solve this.

### LINKED ISSUE #2056: Make atomic partitions in sync with zeebe partitions
Zeebe and atomix may be distributing the partitions among the nodes differently even though the number of partitions and replication factor are the same. We can get which partitions an atomix node hosts and use this information to initialize zeebe partitions.

### LINKED ISSUE #2064: Improve distributed log implementation
- Remove the current event-listeners and write to the logstorage with in the primitive. 
- Handle errors, failures, recovery.
	- What to do when an append fails/timeout?
	- how to handle redundant append requests? 
	- Investigate other possible problems and failure scenarios.

### PR DESCRIPTION
**Pull request by menski**
closes #2009 
closes #1996 
closes #1874 
closes #2013
closes #2055 
closes #2056 
closes #2064

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]

**Comment by menski** [comment]
bors retry

**Pull request merged**
