### PR TITLE
Add record and intent for signal subcription

### LINKED ISSUE #11202: Create SignalSubscriptionRecord and SignalSubscriptionIntent
**Is your feature request related to a problem? Please describe.**

Introduce new `SignalSubscription` records, with intents: `CREATED`, `DELETED`

**Describe the solution you'd like**

- Only used to subscribe to signals, not used to track signal receiving

- The signal subscription record value should consist of:
  - `bpmnProcessId` - The id of the process in the bpmn model
  - `processDefinitionKey` - The key of the deployed process
  - `catchEventId` - The id of the signal catch event
  - `catchEventInstanceKey` - The key of the signal catch event instance (optional)
  - `signalName` - The name of the signal (taken from the name of the signal in the BPMN model)

- Like any other records, these should be exported. Please follow our [developer handbook entry on adding new records](https://github.com/camunda/zeebe/blob/main/docs/developer_handbook.md#how-to-create-a-new-record)

**Describe alternatives you've considered**
No.

**Additional context**

[Subscribe processes with top-level signal start events to signals #11195](https://github.com/camunda/zeebe/issues/11195)

### LINKED ISSUE #11208: Export signal subscription records to ElasticSearch
## Description

We should export signal subscription records to ElasticSearch by default. The elastic search index template should've been made as part of https://github.com/camunda/zeebe/issues/11202. We have to make sure we are exporting this record by default.

**Blocked by:**
https://github.com/camunda/zeebe/issues/11202

**Part of:**
[Subscribe processes with top-level signal start events to signals #11195](https://github.com/camunda/zeebe/issues/11195)

### PR DESCRIPTION
**Pull request by skayliu**
## Description

Add record, intent, stream and export to es for signal subscription.

## Related issues

closes #11202 
closes #11208 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by skayliu** [comment]
Hi, @korthout . Please take a moment to check this out. ❤️

**Comment by korthout** [comment]
Thanks @skayliu 🥇 That was quick! I'll make sure to review it in the coming days.

**Review by korthout — APPROVED** [review]
Great work @skayliu 👏  

👍 I have only a few small suggestions 

🔧 Please have a look and let me know if you agree. 

After that, we can merge this already 🚀

**Comment by lzgabel** [comment]
Done. 

Hi @korthout. Please check this out. :bow:

**Review by korthout — APPROVED** [review]
Thanks ❤️ 

LGTM 👍 

bors merge

**Pull request merged**
