### PR TITLE
Allow deploying benchmarks on stable VMs

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR modifies the benchmark setup and GitHub action to allow deploying benchmarks on stable VMs in the GKE cluster `zeebe-cluster`. This is part of an effort to merge our GKE clusters to reduce maintenance effort.

To run benchmarks on stable VMs, we need to specify a few things:

1. Zeebe brokers and gateways must have a toleration for the non-spot taint.
2. Zeebe brokers target a new node pool made of non-spot VMs.
3. Zeebe gateways specify an affinity for non-spot VMs.

Initially I wanted to implement this as a flag in the benchmark chart, but unfortunately since we need conditionally change the values pass to the dependency chart, this is not possible. Helm does not allow templating in the values file, so we cannot do something like `camunda-platform.zeebe.nodeSelector."cloud.google.com\/gke-nodepool": n2-standard-2-{{ .Values.stable-vms }}`. We really need to specify different values during install/update.

One additional caveat is the measurements do not deploy to stable nodes. If we want this, we would need to also add a checkout step to fetch the additional values file. I don't know if I can inject that to a reusable workflow - if it's possible, happy to do so.

The PR also adds a few additional things:

- The measure input is now a boolean flag - this means it's a checkbox in the form, which is nicer than writing true/false.
- There's now a job summary at the end of deployment which will print out the user supplied values, which is useful when debugging. Caveat is don't put anything secret in there :)

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by deepthidevaki** [comment]
> One additional caveat is the measurements do not deploy to stable nodes. If we want this, we would need to also add a checkout step to fetch the additional values file. 

Second run https://github.com/camunda/zeebe/actions/runs/5043415186 failed. Is it related to this?

**Review by deepthidevaki — APPROVED** [review]
Thanks :rocket:

**Comment by npepinpe** [comment]
For the record, here's a link to the third run: https://github.com/camunda/zeebe/actions/runs/5043631679

**Comment by npepinpe** [comment]
bors merge

**Comment by oleschoenburg** [comment]
@npepinpe What do you think about backporting this? It would help for older release benchmarks: https://github.com/camunda/zeebe/actions/runs/5201000953/jobs/9380686050

**Comment by npepinpe** [comment]
sounds good

**Comment by npepinpe** [comment]
Is it possible there's no benchmark action for 8.1 and 8.0?

**Pull request merged**
