### PR TITLE
chore(monitoring): add health metrics to dashboard

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

* add health status of each partition 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by Zelldon** [comment]
Do you have a screenshot of it ? :sweat_smile: would be nice if we can append these on a PR

**Comment by deepthidevaki** [comment]
Here it is
image

**Comment by deepthidevaki** [comment]
@Zelldon I updated the panel

image

**Comment by Zelldon** [comment]
Do you think the ready state panel makes still sense? Maxbe we can remove it

**Review by ChrisKujawa — APPROVED** [review]
Thanks 👍

**Comment by deepthidevaki** [comment]
> Do you think the ready state panel makes still sense? Maxbe we can remove it

I think it is still useful. A pod can be ready but unhealthy.

**Comment by deepthidevaki** [comment]
bors retry

**Pull request merged**
