### PR TITLE
chore(project): use golangci action

### LINKED ISSUE #5675: Using github.com/zeebe-io/zeebe/clients/go v0.25 provokes linter issues
**Description**

We use https://github.com/golangci/golangci-lint and after upgrading the zeebe go client to 0.25, the following warnings appeared (maybe something worth checking): 

`copylocks: func passes lock by value: github.com/zeebe-io/zeebe/clients/go/pkg/entities.Job contains github.com/zeebe-io/zeebe/clients/go/pkg/pb.ActivatedJob contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)`

Looks like the root cause is the definition of the handler:

`type JobHandler func(client JobClient, job entities.Job)`

as it is not a reference but a value copy

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Enables the Golangci Github action and fixes issues flagged by it.

## Related issues
closes #5675

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e1926df49312f995f9f2246d73599855af444248
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by npepinpe — CHANGES_REQUESTED** [review]
Looks good :+1: 

Looks like it introduced some non backwards compatible changes?

**Comment by MiguelPires** [comment]
Yes, the Job now has a pointer to `pb.ActivatedJob` instead of a copy of it. This was the cause of this warning `copylocks: func passes lock by value: github.com/zeebe-io/zeebe/clients/go/pkg/entities.Job contains github.com/zeebe-io/zeebe/clients/go/pkg/pb.ActivatedJob contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)`

**Review by npepinpe — APPROVED** [review]
:+1:

**Pull request merged**
