### PR TITLE
docs(reference): add hint on default port

### PR DESCRIPTION
**Pull request by jwulf**
I had to go hunting for the default value after hitting this page from Google. It's better UX for users to put it in place.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4835f276117f21a68042ca6de18af651d338fc6b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by npepinpe — COMMENTED** [review]
LGTM, can you please fix the commit message so that it matches our guidelines?

**Comment by jwulf** [comment]
How's that?

**Review by npepinpe — APPROVED** [review]
:100: :fire: :+1:

**Pull request merged**
