### PR TITLE
[BACKPORT] chore(broker): close and recreate logstream on role transition

### LINKED ISSUE #4698: Backport log stream close on transition to 0.22.x
**Description**

See https://github.com/zeebe-io/zeebe/issues/3920; this was fixed in 0.23 but never back ported, which we should have. The PR to back port is https://github.com/zeebe-io/zeebe/pull/3995.

### PR DESCRIPTION
**Pull request by deepthidevaki**
chore(logstream): remove reference counting on logstream writers
## Description

Backport #3995

## Related issues

closes #4698 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by npepinpe** [comment]
Did you change anything or just plain cherry pick? Is there anything particular I should check for?

**Comment by deepthidevaki** [comment]
There were many conflicts which I had to fix. Otherwise I didn't change anything.

**Review by npepinpe — COMMENTED** [review]
I'll run a benchmark but I expect it will just work :+1:

**Comment by npepinpe** [comment]
I ran the benchmark and ran into the beautiful "cannot apply index" case :slightly_smiling_face: We can look at it on Monday

**Comment by deepthidevaki** [comment]
It is fixed in 0.23.0 https://github.com/zeebe-io/zeebe/pull/4218

**Comment by npepinpe** [comment]
This should also have been back ported as well, no? :thinking:

**Review by npepinpe — APPROVED** [review]
As discussed, this was an error that was previously there :+1:

**Pull request merged**
