### PR TITLE
[WIP] Fix dependency download issues

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR attempts to fix the dependency download issues we've been having lately. Thanks to a blog post from [QuestDB](https://questdb.io/blog/maven-troubleshooting-open-source/), I came across a possible reason for the increased dependency resolving issues. It may be related to the Maven 3.9 upgrade. In Maven 3.9, the default transport for the resolver was switched from the old Wagon implementation to a native one. 

Turns out, the native one is missing any form of retry on failure: [Resolver transport-http should retry on failures](https://issues.apache.org/jira/browse/MRESOLVER-326).

Since the resolver (including its implementation) is bundled with Maven, I wasn't sure how to bump only its version. So until the next Maven release, I would propose switch back to the Wagon transport for now.

Additionally, we can the `-U` flag, as it may help with broken dependency downloads by enforcing checksumming (is that a word? :smile:) of downloaded dependencies, and may re-download broken ones.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Testing the fix:

- https://github.com/camunda/zeebe/actions/runs/4645623922
- https://github.com/camunda/zeebe/actions/runs/4645650878
- https://github.com/camunda/zeebe/actions/runs/4645654804
- https://github.com/camunda/zeebe/actions/runs/4645655253
- https://github.com/camunda/zeebe/actions/runs/4645655688
- https://github.com/camunda/zeebe/actions/runs/4645656062
- https://github.com/camunda/zeebe/actions/runs/4645656265
- https://github.com/camunda/zeebe/actions/runs/4645656506
- https://github.com/camunda/zeebe/actions/runs/4645656753
- https://github.com/camunda/zeebe/actions/runs/4645656982
- https://github.com/camunda/zeebe/actions/runs/4645657323

**Comment by npepinpe** [comment]
Did not work, still some issue with jacoco

**Comment by npepinpe** [comment]
Reduced the build to a single job and enabled debug logging to figure out exactly what's happening when it cannot download jacoco.

**Comment by npepinpe** [comment]
Some raw logs where it fails to download JaCoCo: https://pipelines.actions.githubusercontent.com/serviceHosts/f1883567-44d4-470f-99dd-f04eb01730fd/_apis/pipelines/1/runs/61501/signedlogcontent/2?urlExpires=2023-04-10T11%3A49%3A10.0030259Z&urlSigningMethod=HMACV1&urlSignature=ZCXoGm9HHoycMA%2FmIGMat9smjfSSeWZDJol9zsoTwo8%3D

**Comment by npepinpe** [comment]
From the logs we can see it's not actually using Wagon. Dun dun

> 2023-04-10T11:46:37.6000350Z [DEBUG] Using transporter HttpTransporter with priority 5.0 for https://repo.maven.apache.org/maven2

[The transport with priority 5 is the new native one](https://github.com/apache/maven-resolver/blob/28a4b0d06c31f9a533ad8c5d490783fbe51ddc5c/maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporterFactory.java#L49). [Wagon has a hard coded priority of -1.0f.](https://github.com/apache/maven-resolver/blob/28a4b0d06c31f9a533ad8c5d490783fbe51ddc5c/maven-resolver-transport-wagon/src/main/java/org/eclipse/aether/transport/wagon/WagonTransporterFactory.java#L46)

It's unclear why `MAVEN_ARGS` is ignored :thinking: 

If I set the args directly on invocation and not via `MAVEN_ARGS`, then the log becomes:

> [DEBUG] Using transporter WagonTransporter with priority 3.4028235E38 for https://repo.maven.apache.org/maven2
> [DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://repo.maven.apache.org/maven2

So it was never using Wagon in the previous tests.

**Comment by npepinpe** [comment]
I will have to re-run the tests now to see if it's more stable with wagon, as the previous tests was invalid.

**Comment by npepinpe** [comment]
Even with wagon, it still fails to fetch jacoco. The interesting thing is that it's _always_ jacoco, never some other dependency. Is there some weird CDN issue happening?

**Comment by npepinpe** [comment]
From the error, it seems implied that the repository connector says it cannot find jacoco at all. Not that it fails to download it. So the retry stuff may be a dead end, and it's more of a question as to why does it sometimes say it doesn't exist?

**Comment by remcowesterhoud** [comment]
I have no idea what the problem is but some things I noticed whilst looking into it:

- It is always Jacoco
- I've only seen it happen in the macOS smoke tests
- Downloading the dependency does not seem to be the issue. In the logs I can see that it downloads the dependencies it's complaining about:
```
agent runtime jar > 2023-04-11T12:32:46.2058460Z [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.agent/0.8.9/org.jacoco.agent-0.8.9-runtime.jar
...
core jar > [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.core/0.8.9/org.jacoco.core-0.8.9.jar
...
report jar > [INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.report/0.8.9/org.jacoco.report-0.8.9.jar
...
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.9:prepare-agent (coverage-initialize) on project zeebe-parent: Execution coverage-initialize of goal org.jacoco:jacoco-maven-plugin:0.8.9:prepare-agent failed: Plugin org.jacoco:jacoco-maven-plugin:0.8.9 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.jacoco:org.jacoco.agent:jar:runtime:0.8.9, org.jacoco:org.jacoco.core:jar:0.8.9, org.jacoco:org.jacoco.report:jar:0.8.9: Could not find artifact org.jacoco:org.jacoco.agent:jar:runtime:0.8.9 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by npepinpe** [comment]
Closing for now

**Pull request closed without merging**
