### PR TITLE
docs(bpmn-workflows): fix BPMN coverage links

### PR DESCRIPTION
**Pull request by saig0**
## Description

* fix links in the BPMN coverage sections

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]

**Comment by saig0** [comment]
bors retry

**Comment by saig0** [comment]
bors r+ 

:imp:

**Pull request merged**
