### PR TITLE
Fix timer scheduling

### LINKED ISSUE #10532: Timer creations will cause to schedule multiple Tasks
> Had a look together with @saig0 at the DueDateChecker, because I was wondering why so many Tasks are scheduled and same batches are written. We found out that timer creations can cause new task scheduling, even if already a task is scheduled. 
>
> See https://github.com/camunda/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/scheduled/DueDateChecker.java#L53 here the `checkerRunning` is not set. 
>
> Previously we used the `scheduledTimer` to indicate that already a timer is running. https://github.com/camunda/zeebe/blob/8.0.6/engine/src/main/java/io/camunda/zeebe/engine/processing/scheduled/DueDateChecker.java#L47
>
>This issue caused a load of scheduled timers, especially if we have many timer creations. This again caused many (and same timer Triggers per second), which caused a big backlog and high backpressure.
> I will run a benchmark to see how it behaves, but I think it can explain the high backpressure in the mixed benchmarks.
>
>_Originally posted by @Zelldon in https://github.com/camunda/zeebe/issues/10526#issuecomment-1260579282_

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

If we already scheduled a Task for a created Timer, we shouldn't schedule another Task on next timer creation. This PR fixes that.

The previous behavior could cause severe issues, like exponential increasing backlog if a lot of timers are created per second etc. see https://github.com/camunda/zeebe/issues/10532 and https://github.com/camunda/zeebe/issues/10526

## Related issues

closes https://github.com/camunda/zeebe/issues/10532

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by Zelldon** [comment]
I have run some benchmarks to compare the fix. I was not able yet to run the E2E tests, but I will do with a next release candidate.

### Benchmarks
Benchmarks only timers (rate 100 PI/s)

#### Timer Benchmark with bug

timer-bug

#### Timer Benchmark with fix

timer-fix

We can see that it is much more stable in the processing and fewer events are skipped. The backpressure is reduced by half.

#### Mixed Benchmark with bug

For that I used the medic cw 39 (and checked the begin of the benchmark). The begin of the mixed looks always okayisch later it shows higher backpressure. But we can see in the begin already issues with the latencies.

mixed-bug
mixed-latency-bug


#### Mixed Benchmark with fix

In the fixed mixed benchmark we see in general processing not much difference, but in the latency which looks much stable. I will run this benchmark for a while. After ca 5 hours the mixed often failed, so lets see. But I think we can already merge it.

mixed-fix
mixed-latency-fix

**Comment by Zelldon** [comment]
I retagged the docker image such that I can run the E2E tests and it looks great now

e2e

Previously:


e2e-before

**Review by saig0 — APPROVED** [review]
@Zelldon looks good. :+1:

**Comment by saig0** [comment]
bors merge

**Comment by Zelldon** [comment]
bors r+

NOW

**Pull request merged**
