### PR TITLE
[Backport 0.24] Control variable propagation of call activities with new attribute

### LINKED ISSUE #4860: Parallel multi-instance call activity cannot collect output
**Describe the bug**
The output of the multi-instance cannot be collected into the output collection, because its value is overwritten at the moment that one of its call activities completed. 

**To Reproduce**
Consider the following example:

With the following multi-instance configuration:

Create an instance of this workflow with variable `inputs` = `[1,2]`

When the multi-instance activates, the output collection variable is created as a nil values array (e.g. `[null,null]`). Whenever the first called workflow completes it offers all of its variables to the call activity which copies all these variables, which overwrites the output collection. Then at the end of this multi-instance body, its output is collected into this variable, but as soon as the next called workflow completes, its overwritten to the nil values array again.

**Expected behavior**
The outputs should just be collected correctly.

**Environment:**
 - OS: macOS 10.15.5
 - Zeebe Version: 0.23.3
 - Configuration: hazelcast exporter

### PR DESCRIPTION
**Pull request by saig0**
## Description

Backport of #5326

Additionally, I merged some BPMN related documentation from `develop`.  

## Related issues

closes #4860

### CODE REVIEW

**Review by korthout — APPROVED** [review]
LGTM 🎉

**Comment by saig0** [comment]
bors retry

**Pull request merged**
