### PR TITLE
fix(broker): fix race condition in exporter tests

### LINKED ISSUE #6029: ExporterDirectorTest(java-testrun).shouldUpdatePositionWhenInitialRecordsAreSkipped
**Summary**

- How often does the test fail? at least once
- Does it block your work? no
- Do we suspect that it is a real failure? doesn't look like it

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.lang.ArrayIndexOutOfBoundsException: Index 50 out of bounds for length 49
	at java.base/java.util.ArrayList.add(ArrayList.java:487)
	at java.base/java.util.ArrayList.add(ArrayList.java:499)
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.createContext(ZeebeTransactionDb.java:141)
	at io.zeebe.broker.exporter.stream.ExporterRule.getExportersState(ExporterRule.java:95)
	at io.zeebe.broker.exporter.stream.ExporterDirectorTest.shouldUpdatePositionWhenInitialRecordsAreSkipped(ExporterDirectorTest.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:157)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
</pre>
</details>

**Hypotheses**

Nothing, didn't investigate.

**Logs**

<details><summary>Logs</summary>
<pre>
10:42:42.905 [] [main] INFO  io.zeebe.test - Test started: shouldUpdatePositionWhenInitialRecordsAreSkipped(io.zeebe.broker.exporter.stream.ExporterDirectorTest)
10:42:47.993 [Broker-0-LogStream-1] [-zb-actors-0] DEBUG io.zeebe.logstreams - Configured log appender back pressure at partition 1 as AppenderVegasCfg{initialLimit=1024, maxConcurrency=32768, alphaLimit=0.7, betaLimit=0.95}. Window limiting is disabled
10:42:49.924 [exporter] [-zb-fs-workers-1] DEBUG io.zeebe.broker.exporter - Recovering exporter from snapshot
10:42:49.942 [Broker-0-LogStream-1] [-zb-actors-3] INFO  io.zeebe.logstreams - Close appender for log stream stream
10:42:49.945 [stream-write-buffer] [-zb-actors-6] DEBUG io.zeebe.dispatcher - Dispatcher closed
10:42:49.946 [Broker-0-LogStream-1] [-zb-actors-6] INFO  io.zeebe.logstreams - On closing logstream stream close 2 readers
10:42:49.946 [Broker-0-LogStream-1] [-zb-actors-6] INFO  io.zeebe.logstreams - Close log storage with name stream
10:42:49.972 [] [main] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers'
10:42:49.974 [] [main] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-actors'
10:42:49.977 [] [-zb-actors-1] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-actors': closed successfully
10:42:49.991 [exporter] [-zb-fs-workers-1] ERROR io.zeebe.util.actor - Uncaught exception in 'exporter' in phase 'STARTED'. Continuing with next job.
java.lang.IllegalStateException: Iterator is closed
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.seek(LogStreamReaderImpl.java:66) ~[zeebe-logstreams-0.26.0-SNAPSHOT.jar:0.26.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.seekToFirstEvent(LogStreamReaderImpl.java:76) ~[zeebe-logstreams-0.26.0-SNAPSHOT.jar:0.26.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamReaderImpl.seekToNextEvent(LogStreamReaderImpl.java:50) ~[zeebe-logstreams-0.26.0-SNAPSHOT.jar:0.26.0-SNAPSHOT]
	at io.zeebe.broker.exporter.stream.ExporterDirector.recoverFromSnapshot(ExporterDirector.java:192) ~[classes/:?]
	at io.zeebe.broker.exporter.stream.ExporterDirector.onActorStarted(ExporterDirector.java:148) ~[classes/:?]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.26.0-SNAPSHOT.jar:0.26.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.26.0-SNAPSHOT.jar:0.26.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-0.26.0-SNAPSHOT.jar:0.26.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-0.26.0-SNAPSHOT.jar:0.26.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-0.26.0-SNAPSHOT.jar:0.26.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-0.26.0-SNAPSHOT.jar:0.26.0-SNAPSHOT]
10:42:50.016 [] [-zb-fs-workers-1] DEBUG io.zeebe.util.actor - Closing actor thread ground '-zb-fs-workers': closed successfully
</pre>
</details>

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

I couldn't reproduce the test failure but looking at the stack trace and code, we can see that an IndexOutOfBounds exception is thrown when adding an element to a list. I think that a concurrent access caused two threads to pass the array size check with one index to spare and then one of them succeeded and the other tried to write out of bounds. The tests get the exporter states, which adds a context to the closeables list, shortly after it starts an ExporterDirector, which also adds a context to the closeables list asynchronously while starting. This PR fixes the race condition by making the tests wait until the ExporterDirector has started.

## Related issues

closes #6029 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by deepthidevaki — COMMENTED** [review]
Looks good. Does this mean that this concurrent access is a problem in production code as well? I see that `ZeebeTransactionDB:createContext` is called from multiple locations.

**Comment by MiguelPires** [comment]
Most of them happen on start up of different steps, which don't happen concurrently, or in tests. The StatePositionSupplier is the exception but that is called when taking snapshots so it's already synchronized. I actually initially leaned towards making the createContext thread-safe to avoid race-conditions in the future, if it's ever used in a different context. However, Nicolas pointed out that it would be using a different execution model than the one we usually use (actor model) and we should be converging towards one model instead of the opposite

**Comment by npepinpe** [comment]
That's a long term wish in my opinion, but the DB is currently not an actor (or managed by one). So we could make it synchronized to do a createContext for now, but I just wanted us to maybe think if we can already converge towards having a more message-passing approach. Hope that makes sense.

**Review by deepthidevaki — APPROVED** [review]
Thanks. Could you also update the commit message with a bit more details on why this change was needed?

**Pull request merged**
