### PR TITLE
New `AdminRequest` type to pause exporting

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Adds a new request type, `PAUSE_EXPORTING` and adds an optional broker id for all admin requests.

## Related issues

relates to #9630 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by oleschoenburg** [comment]
@deepthidevaki This triggers compatibility checks for our protocol:
```
Error:  Failed to execute goal org.revapi:revapi-maven-plugin:0.14.7:check (check) on project zeebe-protocol: The following API problems caused the build to fail:
Error:  java.field.constantValueChanged: field io.camunda.zeebe.protocol.record.AdminRequestDecoder.BLOCK_LENGTH: Constant field changed value from '3' to '5'.
Error:  java.field.constantValueChanged: field io.camunda.zeebe.protocol.record.AdminRequestEncoder.BLOCK_LENGTH: Constant field changed value from '3' to '5'.
Error:  java.field.enumConstantOrderChanged: field io.camunda.zeebe.protocol.record.AdminRequestType.NULL_VAL: The enum constant was defined on position 2 but is now on 3. The user code can break if it relies on the return value of the "ordinal()" method.
Error:  java.field.enumConstantOrderChanged: field io.camunda.zeebe.protocol.record.AdminRequestType.SBE_UNKNOWN: The enum constant was defined on position 1 but is now on 2. The user code can break if it relies on the return value of the "ordinal()" method.
```

If I understand correctly that means that older gateways will not be able to send admin requests to newer brokers. Do you know what our policy on this is?

**Comment by deepthidevaki** [comment]
@oleschoenburg As far as I know you can change the `protocol.version. Could you try that? And then you can add `sinceVersion` to the new field.

**Review by deepthidevaki — APPROVED** [review]
:tada: Great!

**Pull request merged**
