### PR TITLE
Don't use writer on reprocessing

### LINKED ISSUE #3686: Out of direct memory in the Engine
**Description**

died

First look at this metrics it looked like that back pressure never releases the requests correctly.
But it seem that the real problem is that the engine uses to much direct memory.

died-res

```
2020-01-16T10:41:09.659753939Z 2020-01-16 10:41:09.659 [Broker-0-StreamProcessor-2] [Broker-0-zb-actors-2] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
 I 
2020-01-16T10:41:09.659787894Z java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Unknown Source) ~[?:?]
	at java.nio.DirectByteBuffer.<init>(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.allocateDirect(Unknown Source) ~[?:?]
	at org.agrona.ExpandableDirectByteBuffer.ensureCapacity(ExpandableDirectByteBuffer.java:1128) ~[agrona-1.1.0.jar:1.1.0]
	at org.agrona.ExpandableDirectByteBuffer.putLong(ExpandableDirectByteBuffer.java:184) ~[agrona-1.1.0.jar:1.1.0]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.copyExistingEventToBuffer(LogStreamBatchWriterImpl.java:169) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.event(LogStreamBatchWriterImpl.java:82) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedCommandWriterImpl.appendRecord(TypedCommandWriterImpl.java:73) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedCommandWriterImpl.appendRecord(TypedCommandWriterImpl.java:62) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedStreamWriterImpl.appendFollowUpEvent(TypedStreamWriterImpl.java:63) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.UpdateVariableStreamWriter.onCreate(UpdateVariableStreamWriter.java:41) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.state.instance.VariablesState.setVariableLocal(VariablesState.java:167) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.state.instance.VariablesState.setVariablesLocalFromDocument(VariablesState.java:114) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.instance.CreateWorkflowInstanceProcessor.setVariablesFromDocument(CreateWorkflowInstanceProcessor.java:114) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.instance.CreateWorkflowInstanceProcessor.onCommand(CreateWorkflowInstanceProcessor.java:78) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:47) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:28) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:48) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$chooseOperationForEvent$5(ReProcessingStateMachine.java:277) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$processUntilDone$2(ReProcessingStateMachine.java:252) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:46) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 I 
2020-01-16T10:41:09.660027242Z 2020-01-16 10:41:09.659 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
 I 
2020-01-16T10:41:09.660031030Z java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Unknown Source) ~[?:?]
	at java.nio.DirectByteBuffer.<init>(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.allocateDirect(Unknown Source) ~[?:?]
	at org.agrona.ExpandableDirectByteBuffer.ensureCapacity(ExpandableDirectByteBuffer.java:1128) ~[agrona-1.1.0.jar:1.1.0]
	at org.agrona.ExpandableDirectByteBuffer.putLong(ExpandableDirectByteBuffer.java:184) ~[agrona-1.1.0.jar:1.1.0]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.copyExistingEventToBuffer(LogStreamBatchWriterImpl.java:169) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.event(LogStreamBatchWriterImpl.java:82) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedCommandWriterImpl.appendRecord(TypedCommandWriterImpl.java:73) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedCommandWriterImpl.appendRecord(TypedCommandWriterImpl.java:62) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedStreamWriterImpl.appendFollowUpEvent(TypedStreamWriterImpl.java:63) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.UpdateVariableStreamWriter.onCreate(UpdateVariableStreamWriter.java:41) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.state.instance.VariablesState.setVariableLocal(VariablesState.java:167) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.state.instance.VariablesState.setVariablesLocalFromDocument(VariablesState.java:114) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.instance.CreateWorkflowInstanceProcessor.setVariablesFromDocument(CreateWorkflowInstanceProcessor.java:114) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.instance.CreateWorkflowInstanceProcessor.onCommand(CreateWorkflowInstanceProcessor.java:78) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:47) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:28) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:48) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$chooseOperationForEvent$5(ReProcessingStateMachine.java:277) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$processUntilDone$2(ReProcessingStateMachine.java:252) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:46) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 I 
2020-01-16T10:41:09.746119850Z 2020-01-16 10:41:09.745 [Broker-0-StreamProcessor-3] [Broker-0-zb-actors-3] ERROR io.zeebe.util.actor - Actor failed in phase 'STARTED'. Continue with next job.
 I 
2020-01-16T10:41:09.746142302Z java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Unknown Source) ~[?:?]
	at java.nio.DirectByteBuffer.<init>(Unknown Source) ~[?:?]
	at java.nio.ByteBuffer.allocateDirect(Unknown Source) ~[?:?]
	at org.agrona.ExpandableDirectByteBuffer.ensureCapacity(ExpandableDirectByteBuffer.java:1128) ~[agrona-1.1.0.jar:1.1.0]
	at org.agrona.ExpandableDirectByteBuffer.putLong(ExpandableDirectByteBuffer.java:184) ~[agrona-1.1.0.jar:1.1.0]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.copyExistingEventToBuffer(LogStreamBatchWriterImpl.java:169) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.logstreams.impl.log.LogStreamBatchWriterImpl.event(LogStreamBatchWriterImpl.java:82) ~[zeebe-logstreams-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedCommandWriterImpl.appendRecord(TypedCommandWriterImpl.java:73) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedCommandWriterImpl.appendRecord(TypedCommandWriterImpl.java:62) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedStreamWriterImpl.appendFollowUpEvent(TypedStreamWriterImpl.java:63) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.UpdateVariableStreamWriter.onCreate(UpdateVariableStreamWriter.java:41) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.state.instance.VariablesState.setVariableLocal(VariablesState.java:167) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.state.instance.VariablesState.setVariablesLocalFromDocument(VariablesState.java:114) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.instance.CreateWorkflowInstanceProcessor.setVariablesFromDocument(CreateWorkflowInstanceProcessor.java:114) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.workflow.instance.CreateWorkflowInstanceProcessor.onCommand(CreateWorkflowInstanceProcessor.java:78) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.CommandProcessorImpl.processRecord(CommandProcessorImpl.java:47) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:28) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:48) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$chooseOperationForEvent$5(ReProcessingStateMachine.java:277) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:79) ~[zeebe-db-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.engine.processor.ReProcessingStateMachine.lambda$processUntilDone$2(ReProcessingStateMachine.java:252) ~[zeebe-workflow-engine-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.retry.EndlessRetryStrategy.run(EndlessRetryStrategy.java:46) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:115) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:195) [zeebe-util-0.23.0-SNAPSHOT.jar:0.23.0-SNAPSHOT]
 I 
2020-01-16T10:41:10.027598512Z Jan 16, 2020 10:41:10 AM org.elasticsearch.client.RestClient logResponse
 E 
```

Locally on one of my machines I can't run the engine tests, because it will go out of direct memory as well, might be a hint here as well...

_**Note:**_
Actually usage of direct memory in the engine is no longer necessary, since we migrated the log completely to atomix, which depends only on heap (byte arrays).

### PR DESCRIPTION
**Pull request by menski**
## Description

There were situations where the reprocessing was using a real log stream writer which just buffered but never flushed as we are only reprocessing. This fix tries to add a save guard (assert) to prevent this and fix two found issues in the deployment reprocessing and variable state listeners. 

## Related issues

closes #3686 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by menski** [comment]
There seems to be an issue with the test `JobTimeOutTest.shouldTimeOutAfterReprocessing:89 Failed to reprocess all events, only re-exported 0 but expected 54`. Not yet sure why, and I can't reproduce it locally until now.

**Comment by Zelldon** [comment]
Hey @menski and @npepinpe , thanks for taking a look into this issue. Cool that you found the cause of the deployment issue.
Yes, I also wanted to avoid writing on reprocessing and started with that yesterday, but had no time to finish this. This is the reason why I did as a quick fix the reset thing. Actually we already use NoopWriters on reprocessing, but the real writer is available in the context, which is probably the problem/bug that the listeners access it before.

I feel a bit uncomfortable with the `setDisabled` thing. Normally I like to avoid having test code in production code. Furthermore it seems to pollute the interface, but this is maybe just my opinion.


I did some changes here https://github.com/zeebe-io/zeebe/tree/3686-alternative based on you branch, where:

 * we initialize the writer in the Context with a NoopStreamWriter
 * the real writer is only set after the reprocessing
 * all life cycle listeners only access the writer `onRecovered` callback

So we have two guards. Even if the lifecycle listener access the writer before, it will use the NoopWriter. Even if we change the StreamProcessor code and set the writer before again, the listeners will access it later. So I hope this would be enough. We could also throw an exception in the NoopWriter if you want, to see this in our tests.

**Comment by npepinpe** [comment]
I would love that we explode early on if something tries to write during reprocessing - not sure about the impact in prod. Maybe an assert? Although that assumes good test coverage :see_no_evil:

**Comment by Zelldon** [comment]
>  An exception is probably safest. I'm not sure if it makes sense to add it to the NoopWriter though - the whole point of a Noop* is that you can use it without worrying about it.

If you want to have a exception then I would add a different writer, which reflects this also via his name.

> Maybe we just add that to the real one? Some kind of circuit breaker pattern? Could be a separate issue.

This was done in this PR, but as I said for me it looks not so nice to have this in the interface etc.

Did you checked my branch/changes?

**Comment by npepinpe** [comment]
Ah, realised I wrote on the commit itself.

Essentially I like your approach better than having a flag, but I'm still unsure about what to do with error reporting - do I want to know that a component is trying to write during the reprocessing (yes? maybe?), and what to do with that.

**Comment by Zelldon** [comment]
> Ah, realised I wrote on the commit itself.
>
> Essentially I like your approach better than having a flag, but I'm still unsure about what to do with error reporting - do I want to know that a component is trying to write during the reprocessing (yes? maybe?), and what to do with that.

With the Noop we avoid that something happens, even if he access it. But I get your point that you want to fail if someones does. Normally I tend or like more solutions which not give the possibility in the first place.

So say we have different solutions for this:

 * use the flag
 * use the NoopWriter
 * init the write with null and after reprocessing set the correct writer, so if someone access it before it will fail
 * init with a failing writer, which fails on append call - access before will also fail
 * remove the onOpen from the interface, no one can access the context before it was reprocessed
 * introduce a new interface which hides the writer and is given as parameter in the onOpen(OpenContext ctx)

I would tend then probably to one of the last two.

**Comment by Zelldon** [comment]
I removed the onOpen method completely on this branch https://github.com/zeebe-io/zeebe/tree/3686-alternative . WDYT? Should we go with this?

**Comment by menski** [comment]
closed in favor of #3714

**Pull request closed without merging**
