### PR TITLE
chore(broker): suppress position supplier log in snapshotstore

### LINKED ISSUE #3679: SnapshotStore prints negative partition Id
**Description**
For me it looks weird why we use here -1 also in the logs it is confusing
https://github.com/zeebe-io/zeebe/blob/develop/broker/src/main/java/io/zeebe/broker/clustering/atomix/storage/snapshot/DbSnapshotStore.java#L57

```
2020-01-16 06:49:50.302 [] [raft-partition-group-system-6] INFO  io.atomix.protocols.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=1, group=raft-partition}
2020-01-16 06:49:50.302 [] [raft-server-0-raft-partition-partition-2] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-2} - Transitioning to FOLLOWER
2020-01-16 06:49:50.327 [] [raft-server-0-raft-partition-partition-2] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-2} - Found leader 1
2020-01-16 06:50:39.781 [] [raft-server-0-raft-partition-partition-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - The last processed position for partition -1 is 101653287923896
2020-01-16 06:50:39.790 [] [raft-server-0-raft-partition-partition-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - The lowest exported position for partition -1 is 101653286925008
2020-01-16 06:50:39.810 [] [raft-server-0-raft-partition-partition-2] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/43567050-1-1579157436606-101653286925008, metadata=DbSnapshotMetadata{index=43567050, term=1, timestamp=2020-01-16 06:50:36,606, position=101653286925008}}
2020-01-16 06:51:29.220 [] [raft-partition-group-system-6] INFO  io.atomix.protocols.raft.partition.impl.RaftPartitionServer - Starting server for partition PartitionId{id=3, group=raft-partition}
2020-01-16 06:51:29.219 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to CANDIDATE
2020-01-16 06:51:29.222 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.protocols.raft.roles.CandidateRole - RaftServer{raft-partition-partition-1}{role=CANDIDATE} - Starting election
2020-01-16 06:51:29.241 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Transitioning to FOLLOWER
2020-01-16 06:51:29.262 [] [raft-server-0-raft-partition-partition-1] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-1} - Found leader 1
2020-01-16 06:53:06.331 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Transitioning to FOLLOWER
2020-01-16 06:53:06.338 [] [raft-server-0-raft-partition-partition-3] INFO  io.atomix.protocols.raft.impl.RaftContext - RaftServer{raft-partition-partition-3} - Found leader 2
2020-01-16 06:53:07.129 [] [raft-server-0-raft-partition-partition-3] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - The last processed position for partition -1 is 97968212337968
2020-01-16 06:53:07.129 [] [raft-server-0-raft-partition-partition-3] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - The lowest exported position for partition -1 is 97968208392440
2020-01-16 06:53:07.132 [] [raft-server-0-raft-partition-partition-3] DEBUG io.zeebe.broker.clustering.atomix.storage.snapshot.DbSnapshotStore - Committed new snapshot DbSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/3/snapshots/42011189-1-1579157432491-97968208392440, metadata=DbSnapshotMetadata{index=42011189, term=1, timestamp=2020-01-16 06:50:32,491, position=97968208392440}}
```

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

- uses a `NOPLogger` in `DbSnapshotStore`

## Related issues

closes #3679 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by npepinpe** [comment]
I know it's literally 1 line, but I figured if we have an issue for it we do a PR? :sweat_smile:

**Comment by Zelldon** [comment]
I think we should always do PR's, even if it one line.

**Comment by Zelldon** [comment]
Question on this default position supplier. Why it is necessary or who uses it normally it should be specific to a partition ?

**Comment by npepinpe** [comment]
It was previously used (read: before the refactor) in different places to get the latest positions from the snapshot. I can't remember now tbh, I just repurposed it here since we need this behaviour still.

Now, it's only used in the snapshot store and also on recovery to get the position at which we should start processing/exporting. I would say it's not necessary specify it for a partition, my guess is it was so we would know in the logs (before we had more context in the log messages). I think we could remove the partition as well and keep the message (and rely on the given `Logger` instance to have enough context).

**Comment by Zelldon** [comment]
Yes I think we should fix this somehow, it is confusing if you see a log message with partitionId -1. But this should be probably not be part of this

**Review by ChrisKujawa — APPROVED** [review]
thanks :ok_hand:

**Pull request merged**
