### PR TITLE
Release 1.0.0 alpha1

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Update develop to latest snapshot version

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00d3cf62ccde93acf70b2f7fad7a956a5ce764bb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 65c77382289fe6681f37dbe9c9c2bad0675d2860
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00d3cf62ccde93acf70b2f7fad7a956a5ce764bb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 65c77382289fe6681f37dbe9c9c2bad0675d2860
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 00d3cf62ccde93acf70b2f7fad7a956a5ce764bb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 65c77382289fe6681f37dbe9c9c2bad0675d2860
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by Zelldon** [comment]
I need an approval @npepinpe

**Review by npepinpe — APPROVED** [review]
1.0.0 :exploding_head:

**Pull request merged**
