### PR TITLE
Made RocksDB memory limit configurable

### LINKED ISSUE #6159: As an user I can configure the memory consumption of the state via one setting
**Description**

In the up coming PR which will migrate the RocksDB column Families to one column family and adds new configurations we are able to specify one setting for the memory usage of the state. This configuration/setting should be exposed to the user configuration under the experimental section.

See https://github.com/zeebe-io/zeebe/issues/4002#issuecomment-766616228

Follow up of https://github.com/zeebe-io/zeebe/issues/4002

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Related issues

closes #6159 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
bors r+

:tada:

**Comment by npepinpe** [comment]
bors r-

Oops, didn't see Deepthi was to review this as well, sorry

**Comment by Zelldon** [comment]
It was just to have one of your either you OR @deepthidevaki :smile:

**Pull request merged**
