### PR TITLE
Add release cycle and enterprise docs

### PR DESCRIPTION
**Pull request by menski**
## Description

Add documentation about the release cycle for Zeebe.

### CODE REVIEW

**Comment by menski** [comment]
Open questions, what about supported OS, i.e. only linux for Zeebe/Operate backend? Should we mention Kubernetes/Helm/Operator?

**Comment by menski** [comment]
remove EE but release cycle part should stay

**Comment by npepinpe** [comment]
Any blocker here?

**Comment by Zelldon** [comment]
Do we plan to merge this?

**Pull request merged**
