### PR TITLE
Probe components health when partition is probed

### LINKED ISSUE #4723: No fail over when stream process fails
**Describe the bug**

Running a benchmark with the latest version, I ran into an issue where on fail over, an inconsistency was detected in the log, resulting in the stream processor failing and closing the actor. However, the partition was not marked as unhealthy and no fail over occurred, resulting in no processing happening. All other actors seem to be up, just the stream processor is closed (I can see the AsyncSnapshotDirector attempting to call it for the latest position and failing with `Actor closed` for example).

**To Reproduce**

Get an inconsistent log (?) and make sure it fails when scanning. You can probably simulate that in a test easily, and have the stream processor fail on start.

**Expected behavior**

If we fail to start any leader service, we should step down, as no raft fail over will occur magically.

**Log/Stacktrace**

https://console.cloud.google.com/errors/COaIrJHbxtWuaw?service=zeebe&time=P1D&project=zeebe-io

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Expected that position '3380826456872376' of current event is higher then position '3387410641818784' of last event, but was not. Inconsistent log detected!
	at io.zeebe.engine.processor.ReProcessingStateMachine.scanLog(ReProcessingStateMachine.java:161) ~[zeebe-workflow-engine-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.engine.processor.ReProcessingStateMachine.startRecover(ReProcessingStateMachine.java:133) ~[zeebe-workflow-engine-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:116) ~[zeebe-workflow-engine-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version: 0.24.0-SNAPSHOT, 4274-use-mmap
 - Configuration: mmap storage enabled with replication

### PR DESCRIPTION
**Pull request by korthout**
## Description

When the BrokerHealthCheckService probes the ZeebePartitions for their
health, the ZeebePartition only reported its own health-status. However,
we cannot be sure that this status is updated when one of the components
fails. To make sure that the health check is correct, it is setup to be
bi-directional, so when probing, the partition should also probe its own
critical components.

Lastly, when this results in an UNHEALTHY state, the metrics should be
updated. So we call updateHealthStatus when the partitions own state is
HEALTHY, but its critical components are not.

## Related issues

closes #4723

### CODE REVIEW

**Comment by korthout** [comment]
I've also looked into why the ZeebePartition was unaware of the streamprocessor failing, while it is supposed to inform the ZeebePartition's CriticalComponentHealthMonitor when it fails. The reason for this is that the ZeebePartition's CriticalComponentHealthMonitor is not yet registered as the failure listener of the StreamProcessor when the failure occurs.

It's visible in the following logging (which I've produced with some additional log statements):

```
2020-06-18 18:16:28.598 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - [StreamProcessor]: Scheduling task to add failure listener (ComponentFailureListener) to StreamProcessor
2020-06-18 18:16:28.599 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - [StreamProcessor]: Is supposed to inform the CriticalComponentsHealthMonitor of ZeebePartition here, by calling failureListener.onFailure
2020-06-18 18:16:28.599 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] WARN  io.zeebe.logstreams - [StreamProcessor]: Unable to inform, failure listener is null...
2020-06-18 18:16:28.599 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] ERROR io.zeebe.logstreams - [StreamProcessor]: Actor Broker-0-StreamProcessor-1 failed in phase FAILED.
java.lang.IllegalStateException: This is the injected failure for testing purposes
	at io.zeebe.engine.processor.ReProcessingStateMachine.startRecover(ReProcessingStateMachine.java:135) ~[zeebe-workflow-engine-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:116) ~[zeebe-workflow-engine-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) ~[zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
2020-06-18 18:16:28.605 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-1] WARN  io.zeebe.logstreams - [StreamProcessor]: Trying to handle actor task failure: Unable to call failureListener.onFailure() because failureListener is null
2020-06-18 18:16:28.606 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 901 ms.
2020-06-18 18:16:28.606 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 11 steps in 2159 ms.
```

Here we see there are 2 attempts to call failureListener.onFailure(). At both moments the failureListener is null, even though the task to add the failure listener is already scheduled. That task is never executed because the actor is closed as soon as a failure occurs. If the actor would have executed the task to add the failure listener, we would have seen a log entry stating: `[StreamProcessor]: Failure listener (ComponentFailureListener) added to streamprocessor`

**Comment by korthout** [comment]
@deepthidevaki This change seems to make the integration test `BrokerMonitoringEndpointTest.shouldGetHealthStatus` unstable, but I'm unable to reproduce it locally. I need some help with this part.

**Comment by korthout** [comment]
@deepthidevaki After our work this morning on the flaky test, we've combined the onFailure and handleFailure methods of StreamProcessor and moved the initial healthCheckTick in the StreamProcessor to before completing the openFuture.

Injecting the failure (like in the original issue) now results in the following logging:

```
2020-06-19 12:01:16.666 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - Checking health of StreamProcessor
2020-06-19 12:01:16.666 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.zeebe.logstreams - everything healthy for the stream processor
2020-06-19 12:01:16.666 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-1] INFO  io.zeebe.broker.system - [CriticalComponentsHealthMonitor]: Calculated health: {Broker-0-StreamProcessor-1=HEALTHY, logStream=HEALTHY}
2020-06-19 12:01:16.663 [Broker-0-StreamProcessor-1] [Broker-0-zb-actors-0] ERROR io.zeebe.logstreams - Actor Broker-0-StreamProcessor-1 failed in phase STARTED.
java.lang.IllegalStateException: Muahahaha
	at io.zeebe.engine.processor.StreamProcessor.onActorStarted(StreamProcessor.java:108) ~[zeebe-workflow-engine-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:118) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:107) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:91) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:204) [zeebe-util-0.24.0-SNAPSHOT.jar:0.24.0-SNAPSHOT]
2020-06-19 12:01:16.673 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 partitions succeeded. Started 1 steps in 892 ms.
2020-06-19 12:01:16.673 [] [main] INFO  io.zeebe.broker.system - Bootstrap Broker-0 succeeded. Started 11 steps in 2072 ms.
2020-06-19 12:01:16.673 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.zeebe.broker.system - [CriticalComponentsHealthMonitor]: Calculated health: {Raft-1=HEALTHY, Broker-0-StreamProcessor-1=HEALTHY, logStream=HEALTHY}
2020-06-19 12:01:16.673 [Broker-0-HealthCheckService] [Broker-0-zb-actors-1] INFO  io.zeebe.broker.system - [CriticalComponentsHealthMonitor]: Calculated health: {Partition-1=HEALTHY}
2020-06-19 12:02:15.781 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] INFO  io.zeebe.broker.system - [CriticalComponentsHealthMonitor]: Calculated health: {Partition-1=HEALTHY}
2020-06-19 12:02:16.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.zeebe.logstreams - Checking health of StreamProcessor
2020-06-19 12:02:16.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] ERROR io.zeebe.logstreams - Actor closed!
2020-06-19 12:02:16.692 [Broker-0-ZeebePartition-1] [Broker-0-zb-actors-0] INFO  io.zeebe.broker.system - [CriticalComponentsHealthMonitor]: Calculated health: {Raft-1=HEALTHY, Broker-0-StreamProcessor-1=UNHEALTHY, logStream=HEALTHY}
2020-06-19 12:02:16.694 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] ERROR io.zeebe.broker.system - Partition-1 failed, marking it as unhealthy
2020-06-19 12:02:16.694 [Broker-0-HealthCheckService] [Broker-0-zb-actors-0] INFO  io.zeebe.broker.system - [CriticalComponentsHealthMonitor]: Calculated health: {Partition-1=UNHEALTHY}
```

Here we can see that the after failing, the actor is closed but because the failure listener is still null, the health monitor checking the stream processor is not informed about the stream processor becoming unhealthy. After 1 minute the CriticalComponentsHealthMonitor of the ZeebePartition probes its components, among them the StreamProcessor and discovers that the actor is closed and thus it has become unhealthy. 

I would like to consider whether we can improve this. Should we perhaps inform the failure listener of the current status, as soon as it registers?

**Comment by korthout** [comment]
@deepthidevaki I've rerun the pipeline about 10 times. There was only 1 build flaky, but this was because of another unstable test (already described here #4430). I think this integration test is no longer flaky.

**Review by deepthidevaki — APPROVED** [review]
:+1: Thanks for the documentation.

**Comment by korthout** [comment]
bors retry

**Comment by korthout** [comment]
bors retry

**Pull request merged**
