### PR TITLE
refactor: DraftTaskVariable

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

* Moves `DraftTaskVariableEntity` to `webapps-schema` module
* Moves `DraftTaskVariableTemplate` to `webapps-schema` module
* Ensure that the integration tests continues to create the (old) Tasklist schema so that the tests can run
* Ensure that Operate does not include Taskist indices in its health check

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

related to #24665

### CODE REVIEW

**Comment by romansmirnov** [comment]
@panagiotisgts, sorry for the noise. When I assigned this issue for review, the tests passed. When working on the next PR, I noticed a general bug that I fixed, but that again caused a test to fail. I will take care of it

**Comment by romansmirnov** [comment]
@panagiotisgts, this PR is now ready for review. I tried to break it down in smaller commits to allow an easy review as much as possible. The failing E2E test seems to be unrelated to the changes, I have made. Before this [commit](https://github.com/camunda/camunda/pull/24753#:~:text=test%3A%20replace%20property%20from%20mapping), the E2E tests succeed without issues.

**Review by panagiotisgts — APPROVED** [review]
LGTM

**Comment by romansmirnov** [comment]
Rebased branch with `main` to resolve merge conflicts and failing `CamundaExporterIT` test.

**Pull request merged**
