### PR TITLE
fix(ci): fix syntax in docker_zeebe.dsl

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

The job failed due to syntax error https://ci.zeebe.camunda.cloud/job/seed-job-zeebe/3281/console

### CODE REVIEW

**Review by megglos — APPROVED** [review]
LGTM!

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors merge

**Comment by megglos** [comment]
bors merge

**Comment by megglos** [comment]
bors merge

**Pull request merged**
