### PR TITLE
docs(reference): Clarify timeout is in ms

### LINKED ISSUE #3779: Clarify in gRPC doc that timeouts are in ms
**Description**

This issue is related to #3049. In that ticket, the method _timeout(long)_ was removed because it was unclear that the time shall be set in milliseconds. 

However, there are similar methods in the gRPC API. Worse yet, currently it is not clear that the values shall be specified in ms.

This ticket will clarify this in the documentation.

### PR DESCRIPTION
**Pull request by pihme**
## Description

Clarifies in documentation that timeouts are in ms.

## Related issues
closes #3779

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
bors r+

**Comment by Zelldon** [comment]
Why this was not added also in the `gateway.proto` file?

**Comment by pihme** [comment]
no reason, I wasn't aware of it

**Pull request merged**
