### PR TITLE
chore(exporter): include version in index names

### LINKED ISSUE #3785: Zeebe Elasticsearch index names contain version number
**Is your feature request related to a problem? Please describe.**

The Zeebe records exporter into elasticsearch have a strict type mapping. During the evolution of Zeebe this data schema might change. Do enable Zeebe to continue exporting without migration downtime we will include the Zeebe version into the schema index names.

**Describe the solution you'd like**

The Zeebe elasticsearch exporter creates schema templates that contain the Zeebe version and exports to them accordingly. There is no data migration needed when upgrading Zeebe.

**Describe alternatives you've considered**

- Having a dynamic schema in elasticsearch which would allow adding new fields, downside the type is guessed by Elasticsearch and it's not clear for a consumer which schema to expect
- Migrating data when upgrading Zeebe, still would require multiple indexes (i.e. different names) and additionally leads to longer downtime of a broker and decided when to upgrade data is complex a Zeebe exporters are distributed through the whole cluster

**Additional context**
- Broker version is already available https://github.com/zeebe-io/zeebe/blob/6de8795b208b5fc6c98be2af53dc63d9f68fbdbd/broker/src/main/java/io/zeebe/broker/Broker.java#L79
- We could add the version to the exporter context to make it available to exporters in general https://github.com/zeebe-io/zeebe/blob/6de8795b208b5fc6c98be2af53dc63d9f68fbdbd/broker/src/main/java/io/zeebe/broker/exporter/context/ExporterContext.java
- Encoding of the schema version should be in the same way as we did it in Operate
- We can discuss if we should include the version through a properties file instead of the implementation version https://github.com/zeebe-io/zeebe/blob/6de8795b208b5fc6c98be2af53dc63d9f68fbdbd/broker/src/main/java/io/zeebe/broker/Broker.java#L78, but we should do this in another issue

### PR DESCRIPTION
**Pull request by sdorokhova**
## Description

- all ELS indices contain Zeebe version in names
- new template/index name style: prefix_name_version[_date] (undescores!)

## Related issues

closes #3785 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c126cf3546f9e7098058d12171341bd8f3787c02
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci, build**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by sdorokhova** [comment]
LGTM failure is a known issue and fails on code, which were not affected by the PR

**Review by menski — CHANGES_REQUESTED** [review]
Looks good, just a small change request and the question why we switched to `_` as the delimiter in the index names? I would guess to make it simpler to split the index name into its parts as the version could contain a `-` itself?

**Comment by sdorokhova** [comment]
1. Regarding `_`. Yes, otherwise it becomes really tricky to correctly get the version. I was thinking of finding a substring starting from 1st digit, till next `-` (we could probably even ignore `alpha1` or `snapshot` part), but the use could configure the prefix containing both dashes and digits.
2. Regarding lower case, thank you for noticing! This was my intention, but I missed the usage part(

**Comment by sdorokhova** [comment]
@menski One more note, we actually must state in docs, that Zeebe index prefix must nor contain `_`. Do you think it's OK?

**Comment by menski** [comment]
> One more note, we actually must state in docs, that Zeebe index prefix must nor contain _. Do you think it's OK?

I think this is a good point and created #3865 for it

**Review by menski — APPROVED** [review]

**Pull request merged**
