### PR TITLE
chore(docker): extract JVM, Java version and base image into arguments

### PR DESCRIPTION
**Pull request by megglos**
## Description

Tiny improvement, just to remove the redundancy of repeated base image, java version and jvm strings.
Follow-up to https://github.com/camunda/zeebe/pull/11515 where I noticed the opportunity.

### CODE REVIEW

**Review by lenaschoenburg — COMMENTED** [review]
:question: Do we know if renovate can handle this? I'd be a shame to lose automatic base image upgrades because renovate can't deal with arguments in the base image name

**Comment by megglos** [comment]
> ❓ Do we know if renovate can handle this? I'd be a shame to lose automatic base image upgrades because renovate can't deal with arguments in the base image name

This test case seems relevant and should confirm renovate indeed supports multiple ARG s used anywhere in the FROM statement. I'm also up for manually verifying it to be absolutely sure.

**Review by lenaschoenburg — APPROVED** [review]
> This [test case](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/dockerfile/extract.spec.ts#L1050-L1083) seems relevant and should confirm renovate indeed supports multiple ARGs used anywhere in the FROM statement

Good find :+1: 
I'm personally okay with merging without testing manually

**Pull request merged**
