### PR TITLE
Interrupt flow scope when a terminate end event is reached

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

The terminate end event should mark its flow scope as interrupted when it's completed. Having an interrupted flow scope means other elements in this scope can no longer be activated or completed. Any ACTIVATE/COMPLETE command will be rejected.

If we do not interrupt the flowscope it is possible for the engine write a TERMINATE command as a result of the end event. It could then go on to process a COMPLETE command. This will not be rejected, and it will take outgoing sequence flows for this element. The TERMINATE will then be rejected as the element is no longer active. Since the flowscope now has an outgoing sequence flows it is considered to have active elements, it will not be terminated, as it should upon reaching a terminate end event.

Since the flow scope gets interrupted we will also have to change the logic in the processors of these possible flow scopes (`ProcessProcessor`, `SubProcessProcessors`, `EventSubProcessProcessor`). Here we need to verify that the scope was interrupted by a terminate end event, and if it is we need to make sure the scope gets completed, instead of terminated.

## Related issues

relates to #11121 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@koevskinikola As we discussed last week during the flaky test session I'll assign this review to you. Don't hesitate to reach out if anything is unclear. I'm happy to explain it 🙂

**Comment by remcowesterhoud** [comment]
I'm not having this PR close #11121 yet. I believe there is more flaky scenarios that are not covered by this bug fix

**Review by koevskinikola — COMMENTED** [review]
:+1: @remcowesterhoud, the changes look good to me, but I'd like to do a short call to ensure that I understood everything correctly.

:wrench: Should we re-enable the Escalation event Block builder within this PR since it was disabled [here](https://github.com/camunda/zeebe/pull/11166)? **=> Answered in [the previous comment](https://github.com/camunda/zeebe/pull/11178#issuecomment-1337577587).**

**Review by koevskinikola — APPROVED** [review]
:+1: Thanks for the explanation @remcowesterhoud. I have a better understanding on what is happening now.

LGTM :rocket: 

bors merge

**Pull request merged**
