### PR TITLE
feat(clients/zbctl) Added zbctl

### LINKED ISSUE #1263: Migrate zbctl to new go client
The zbctl will be moved to the zeebe repository and use the new client. All topic related stuff will be removed. We also have to adjust the release build to the new location of zbctl.

### PR DESCRIPTION
**Pull request by jsam**
closes #1263

### CODE REVIEW

**Comment by menski** [comment]
@sam I think this pull request now contains the Zeebe go client as vendored dependency. As far as I remember we wanted to not add it there. Is there a reason why it is now part of the vendor folder?

**Comment by jsam** [comment]
@menski strange ... I removed it again

**Comment by menski** [comment]
@jsam but if I run `dep ensure` it is added again :sob:

**Review by menski — APPROVED** [review]
bors r+

**Pull request merged**
