### PR TITLE
Make renovate bot ignore docker dependency

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

The docker project [doesn't play very well with go modules](https://github.com/moby/moby/issues/39302) due to the way they do versioning. As evidenced by PRs https://github.com/zeebe-io/zeebe/pull/3493 and https://github.com/zeebe-io/zeebe/pull/3492, the renovate bot gets confused by this and tries to update to versions which are actually from 2017. This PR makes the renovate bot ignore the this dependency and updates it manually to a recent version.

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
Hm, that's unfortunate. So we have to update these manually? :sweat:

**Comment by MiguelPires** [comment]
I think so =/ 

bors+

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
