### PR TITLE
feat(clients/java): JobWorker extending AutoClosable

### LINKED ISSUE #4837: Allow using JobWorker in a try-with-resources
**Is your feature request related to a problem? Please describe.**

I'd like to use `JobWorker` in a `try-with-resources` block, which is currently not possible even though `JobWorker` implements as `close` method.

**Describe the solution you'd like**

If `JobWorker` implements `AutoCloseable`, then I can create an instance as part of a `try-with-resources` so it can be safely closed once I'm done with it.

**Describe alternatives you've considered**

Close the worker in a finally block, which is fine but not ideal.

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

io.zeebe.client.api.worker.JobWorker now extending an java.lang.AutoCloseable interface.

## Related issues

closes #4837 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [x] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 96f5669e961ce58f227e52e6c61e51a937eb24c0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by npepinpe — CHANGES_REQUESTED** [review]
Hey @aivinog1, thanks for the contribution!

Two small things:

1. Could you annotate the `#close()` method in `JobWorker` with `@Override`?
1. Could you update the `JobWorkerCreator` example in the `zeebe-samples` module to use the worker in a try-with-resources?

Thanks!

**Comment by aivinog1** [comment]
@npepinpe Hi! I've fixed all review comments in https://github.com/zeebe-io/zeebe/pull/5296#pullrequestreview-484725528 :)

**Review by npepinpe — APPROVED** [review]
Thanks, looks good! You even updated the docs, which I forgot to mention :slightly_smiling_face: 

EDIT: Just letting the CI run before merging it, but I don't expect anything since the changes you added should have no effect there.

**Pull request merged**
