### PR TITLE
docs(getting started) Add new Getting Started tutorial to Zeebe docs

### LINKED ISSUE #2315: Add new "Getting Started" tutorial to Zeebe docs

### PR DESCRIPTION
**Pull request by wints**
Closes #2315 

Adds a new getting started tutorial to the Zeebe docs, which includes modeling, using the CLI, and visualizing what's happening.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a7bb43762ca32e93c946f4113ecb2759cfd5b9f9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by menski** [comment]
@wints what is the plan for the Java get started section, which currently still features the simple monitor? https://docs.zeebe.io/java-client/get-started.html

Also is the quickstart now obsolete? It kind of is a repetition of the same commands? 

On another note was the manual navigation at the end of every page intended, mdbook already has the feature with the arrows on the side to go to the previous/next page?

Btw gitcop complains because your commit message is missing the colon after the scope, i.e.
```
docs(getting started): Add new Getting Started tutorial to Zeebe docs
```

**Comment by wints** [comment]
Thanks for the review @menski:

• I plan to update the Java Getting Started screencasts and prerequisites to use Operate between now and the next release, but not before this initial Operate announcement. I will sync with Philipp here. 

• I kept the Quickstart in for now even though it's somewhat repetitive because I do think there's still a need for a "doing something with Zeebe + zbctl in 5 minutes" guide in the docs. I _also_ hope to add zbctl to the docs this quarter, and I expect that a zbctl docs entry can replace the Quickstart once it exists. 

• I know mdbook has the arrows on each page, but because of where these are / their visibility, I tend to overlook them, and I wanted to add some sort of pagination that was more visible since the tutorial needs to be completed in chronological order. 

• Typo on my part during the commit

Let me know if you have any questions here.

**Comment by menski** [comment]
@wints thanks for the explanation

**Review by menski — APPROVED** [review]

**Pull request merged**
