### PR TITLE
[Backport stable/8.1] fix: don't re-wrap runtime exceptions thrown inside a transaction

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Manual backport of https://github.com/camunda/zeebe/pull/11701

I had to resolve some conflicts in import paths and minor merge conflicts in `StreamPlatform`.

### CODE REVIEW

**Comment by Zelldon** [comment]
:x: I think the test from https://github.com/camunda/zeebe/pull/11701 can be backported as well

Meaning https://github.com/camunda/zeebe/pull/11701/commits/9499956dacd011f0fb07383333458dd2f9bd2b89 since the StreamPlatform is already available in StreamProcessorTest (I migrated that already in 8.1).

**Comment by oleschoenburg** [comment]
@Zelldon The test that you mentioned is already included here or am I missing something?

**Comment by Zelldon** [comment]
But later or? Am I getting crazy now?

**Comment by oleschoenburg** [comment]
This commit here:  3e8f659 is the cherry-pick of  9499956 which is the original commit containing the test.

**Review by ChrisKujawa — APPROVED** [review]
Yeah what I mean is when you opened the PR, this commit was not part of it right? Because I can remember you had a similar line that test can't be backported :sweat_smile: 

But doesn't matter it is fine, please go ahead :+1:

**Comment by oleschoenburg** [comment]
Ah okay, sorry I actually forgot about that :sweat_smile: 
Thanks for checking!

bors r+

**Pull request merged**
