### PR TITLE
feat(client-go): add support for backoff timeout for failed jobs in the Go client and zbctl

### LINKED ISSUE #5629: Clients can set an optional backoff time to the failed tasks.
**Is your feature request related to a problem? Please describe.**
This is the client's part of #164. The idea is that a client (Java/Go/Zbctl) can specify an optional backoff time when sending a JobFailed command. If a backoff time is set then the job will be available after the backoff time. Otherwise, the job will be available immediately (current behavior).

**Describe the solution you'd like**
Clients can set an optional backoff time.

**Describe alternatives you've considered**
We could split this task into three for different clients.

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

I've added mapping in the Go client and an additional flag that matches job backoff.

## Related issues

closes #5629 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by pihme — APPROVED** [review]
Thanks @aivinog1 for your contribution! Looking forward to seeing this in action.

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
@aivinog1 Yes, I do. The build failed because of an interface compatibility check which detected the change. 
I am currently investigating internally how to reset the compatibility check after the change. Might take a bit. I am not too familiar with the Go code and this part of the build pipeline, so a bit slow.

**Comment by pihme** [comment]
@aivinog1 Hope you don't mind that I simply added a commit, instead of forking your fork :-)

If you want to replicate the step, all that is needed is to run `cd clients/go && gocompat save ./...`

**Comment by pihme** [comment]
bors retry

**Comment by aivinog1** [comment]
Thanks @pihme :)

**Pull request merged**
