### PR TITLE
chore(ci): update GHA secrets to new Vault path

### PR DESCRIPTION
**Pull request by Langleu**
## Description

related to a [recent announcement](https://camunda.slack.com/archives/C03AEFWGJ9K/p1657524606321389) of restructuring Vault.

Secrets have already been copied over to: https://vault.int.camunda.com/ui/vault/secrets/secret/list/products/zeebe/ci/

## Related issues

related to [INFRA-3336](https://jira.camunda.com/browse/INFRA-3336)

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by maxdanilov — APPROVED** [review]

**Review by npepinpe — APPROVED** [review]

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
@Langleu One question, do we need to backport this? Will you delete these secrets in the next 6 months?

**Comment by Langleu** [comment]
Yes, we should backport it!
Secrets will be deleted shortly after every team has switched their secrets, which will be likely by the end of the week.

**Comment by Langleu** [comment]
bors retry

**Comment by npepinpe** [comment]
Well, duh, this won't be backported since GHA CI didn't exist on those branches. Ups :see_no_evil:

**Comment by Langleu** [comment]
Ah good to know.
In that case, I'll have a look at those two branches if they have any Vault usage still for the `common/github.com` path.

**Comment by npepinpe** [comment]
Thanks, that's very much appreciated :+1:

**Pull request merged**
