### PR TITLE
chore: add identity CI workflows

### PR DESCRIPTION
**Pull request by dlavrenuek**
## Description
Adds Identity checks to PRs and merge queue

## Related issues

closes https://github.com/camunda-cloud/identity/issues/2960

### CODE REVIEW

**Comment by cmur2** [comment]
After discussion with Ben the next steps are:

* I temporarily set the base of this PR to use `ck-search-ci` where Chris added the `java-unit-tests` job executing (nearly) all unit tests in the whole monorepo
* Ben will check if `identity-backend.yml` is already covered by the `java-unit-tests` job of `ci.yml` and thus can be deleted
* I pushed my changes to integrate `identity-frontend.yml` into the (unified) `ci.yml` meaning it will integrate smoothly with the merge queue and use central change detection

Depending on when https://github.com/camunda/camunda/pull/19436 gets merged we can either wait for that or rebase the changes again onto `main`.

**Comment by cmur2** [comment]
@Ben-Sheppard did you check if `identity-backend.yml` is already covered by the java-unit-tests job of `ci.yml` and thus can be deleted

There is a merge conflict on the `identity/client/yarn.lock` that needs resolving

**Comment by Ben-Sheppard** [comment]
Hey @cmur2 - sorry I didn't get back to you on that, having looked and as suggested, we don't run any ITs currently in the monorepo Identity so for now we can remove the backend yaml. I can handle that along with the conflicts :)

One question on the future, is it fair to say that there could eventually be a common IT based action (like we now have with unit tests)?

**Comment by cmur2** [comment]
> One question on the future, is it fair to say that there could eventually be a common IT based action (like we now have with unit tests)?

Yes that it fair to say! It makes sense in general to consolidate there unless special circumstances (very long runtimes, flakiness) prevent that for individual tests.

**Review by Ben-Sheppard — APPROVED** [review]

**Pull request merged**
