### PR TITLE
Add workflow key to variable record

### LINKED ISSUE #2115: Variable events should contain workflow key
A variable record should contain the workflow key, which allows aggregation of variable values based on workflows. 

For reference https://forum.zeebe.io/t/how-to-measure-mean-time-to-resolve-for-workflow/278/3

### PR DESCRIPTION
**Pull request by menski**
closes #2115

### CODE REVIEW

**Review by saig0 — COMMENTED** [review]
Do we have a test case to verify that the workflow key is set on the variable record?

**Comment by menski** [comment]
https://github.com/zeebe-io/zeebe/blob/eacc8e74b4b1ea9b8ba0a43278813959e96f8f9b/broker-core/src/test/java/io/zeebe/broker/workflow/variables/WorkflowInstanceVariableTypeTest.java

**Comment by saig0** [comment]
Ok, not the place where I expected it. Please add more test cases to verify that the workflow key is also set when a variable is added or updated within the workflow.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 90d1f611a69e664dc45a969d7e36d166548031d8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by menski** [comment]
@saig0 please have a look at the last commit

**Review by saig0 — APPROVED** [review]
:+1:

**Pull request merged**
