### PR TITLE
[Backport stable/8.2] Track executed migrations in a ColumnFamily

### PR DESCRIPTION
**Pull request by remcowesterhoud**
# Description
Backport of #13780  to `stable/8.2`.

relates to #13763  

---------

⚠️ Note I've added all ColumnFamilies that exist on the main branch. This is because we use the ordinal of the ColumnFamily. If the migrations CF gets a different ordinal on each stable version the change would not be backwards compatible.

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Thank @remcowesterhoud :+1:

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors retry

**Comment by remcowesterhoud** [comment]
bors cancel

Not getting a runner again :/

**Comment by oleschoenburg** [comment]
bors cancel

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
