### PR TITLE
[Backport] fix(exporters/elasticsearch-exporter): custom headers

### PR DESCRIPTION
**Pull request by saig0**
## Description

* service tasks with custom headers that contain a dot can lead to mapping failures in ES
* avoid mapping failures by disabling the index of custom headers for job and job batch records

## Related issues

backport of #4666 to `0.22`

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by saig0** [comment]
@sdorokhova, this PR change the `customHeaders` property in ES template for job and job batch records. 

Please check if this change can lead to any problems in Operate when applying the patch. Thank you :moon_cake:

**Comment by sdorokhova** [comment]
Hi @saig0 , tested with Operate 1.2.1. Looks fine!

**Review by korthout — APPROVED** [review]
LGTM

**Review by sdorokhova — APPROVED** [review]

**Comment by saig0** [comment]
```
[ERROR] Tests run: 16, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.305 s <<< FAILURE! - in io.zeebe.transport.impl.AtomixTransportTest
```

**Comment by saig0** [comment]
bors r+ 

please :moneybag:

**Comment by saig0** [comment]
No luck with the `AtomixTransportTest` :cloud_with_rain:

**Pull request merged**
