### PR TITLE
Document new development workflow

### LINKED ISSUE #957: Migrate development workflow to gitflow
- [x] merge all zeebe repositories into zeebe-io/zeebe
- [x] setup bors and gitcop for zeebe-io/zeebe
- [x] setup jenkins multi branch pipeline for zeebe-io/zeebe
- [x] reformat code with google formatter
- [x] add githook to check code on pre-commit
- [x] document development workflow in CONTRIBUTING.md
- [x] make `master` and `develop` branch protected

### PR DESCRIPTION
**Pull request by menski**
Update the contributing guidelines with the project structure, the development workflow and commit messages guidelines.

closes #957

### CODE REVIEW

**Review by ThorbenLindhauer — APPROVED** [review]

**Comment by ThorbenLindhauer** [comment]
bors retry

**Comment by ThorbenLindhauer** [comment]
bors retry

**Comment by menski** [comment]
bors retry

**Comment by menski** [comment]
bors retry

**Comment by menski** [comment]
bors retry

**Pull request merged**
