### PR TITLE
Separate Spring configuration per application-type

### LINKED ISSUE #7760: Phase out the monitoring configuration in favor of pure actuator configuration
**Description**

The old monitoring configuration from Zeebe is currently used to configure some parts of the Spring management server. This simply adds a layer of confusion, and in general users should configure the management server as defined by Spring, and we should remove the old monitoring configuration.

This would be a breaking change for some deployments, but the migration path is quite clear as currently there's little configuration on the Zeebe side.

This should be done before adding more features to our network transport (such as TLS) to avoid adding more "unused" configuration options to the existing `MonitoringCfg`.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

In the context of #7760, we will move all configuration of the monitoring server to Spring configuration. Before doing this, I would like to have a cleaner separation of gateway/broker Spring configuration.

In order to better separate the application specific Spring configuration for each artifact (i.e. broker, gateway), two new profiles
are introduced: gateway, and broker. Each profile is enabled programmatically in the respective Standalone* class of the artifact,
and will thus load the appropriate application-*.properties overrides for that application.

Doing this allows us to have a shared default application.properties, and overrides for each artifact (e.g. application-broker.properties for the broker, which takes precedence over application.properties, but is
overridden by external configuration such as config/application.yaml or environment variables).

This also mean we don't need to go and disable things in different artifacts that were part of the shared application.properties.

Furthermore, this still works with the environment profiles (i.e. prod, dev, and test) since you can activate more than one profile at a time.

## Related issues

related to #7760 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by korthout — CHANGES_REQUESTED** [review]
Generally LGTM, but I think you negated a boolean.

**Review by pihme — COMMENTED** [review]
Some questions and comments, please check

**Review by korthout — APPROVED** [review]
Thanks for the changes, LGTM 👍

**Review by pihme — APPROVED** [review]
One comment. Feel free to ignore

**Pull request merged**
