### PR TITLE
Introduce List storage for engine tests

### LINKED ISSUE #4240: Execution of StreamProcessorHealthTest takes to long
**Description**

I was wondering why this test `StreamProcessorHealthTest`takes so long. For example the test `shouldMarkUnhealthyWhenReprocessingRetryLoop` takes around 13 seconds. It seems that the update to the clock does not work as expected. Might be due to the `runUntilDone` endless loop.

### LINKED ISSUE #4242: StreamProcessorHealthTest#shouldMarkUnhealthyWhenReprocessingRetryLoop flaky
**Description**
Not reproducible locally on two different machines but often failing on the CI.

```

[INFO] No dependency problems found

[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.833 s <<< FAILURE! - in io.zeebe.engine.processor.StreamProcessorHealthTest

[ERROR] io.zeebe.engine.processor.StreamProcessorHealthTest.shouldMarkUnhealthyWhenReprocessingRetryLoop  Time elapsed: 10.786 s  <<< FAILURE!

org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:91)

	at io.zeebe.test.util.TestUtil$Invocation.until(TestUtil.java:64)

	at io.zeebe.test.util.TestUtil.waitUntil(TestUtil.java:36)

	at io.zeebe.engine.processor.StreamProcessorHealthTest.shouldMarkUnhealthyWhenReprocessingRetryLoop(StreamProcessorHealthTest.java:87)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)

	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

	at org.junit.runners.Suite.runChild(Suite.java:128)

	at org.junit.runners.Suite.runChild(Suite.java:27)

	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)

	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)

	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:119)

	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:87)

	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)

	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)

	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)

	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)

	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)



[INFO] 

[INFO] Results:

[INFO] 

[ERROR] Failures: 

[ERROR]   StreamProcessorHealthTest.shouldMarkUnhealthyWhenReprocessingRetryLoop:87 expected:<[tru]e> but was:<[fals]e>

[INFO] 

[ERROR] Tests run: 1054, Failures: 1, Errors: 0, Skipped: 0
```

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Replaces the AtomixLogStorage with an on heap ListStorage.
Most of the tests are by factor 2 faster then before.

For example variable.mappings tests before:

old

now:

improve

The engine test suite now runs on jenkins with around 1:50 min, before 02:39 min.

## Related issues

closes #4240 
closes #4242 

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by Zelldon** [comment]
@deepthidevaki part of this PR I refactored a bit the `StreamProcessorHealthTest` maybe you can have a look

**Comment by npepinpe** [comment]
Can we remove entirely dependency on Atomix from the engine forever? Next is removing it from LogStream :heart_eyes:

**Comment by Zelldon** [comment]
@npepinpe I tried but I needed the ZeebeEntry stuff but I think it is a step forward we can iterate/improve on that

**Comment by deepthidevaki** [comment]
> @deepthidevaki part of this PR I refactored a bit the `StreamProcessorHealthTest` maybe you can have a look

Looks good. Thanks :+1:

**Comment by Zelldon** [comment]
@npepinpe nevermind was able to remove the atomix dep :v:

**Comment by Zelldon** [comment]
@saig0 pingPong :ping_pong:

**Review by saig0 — APPROVED** [review]
Nice improvement :+1: Thanks!

**Pull request merged**
