### PR TITLE
test(github): add backport test file

### PR DESCRIPTION
**Pull request by korthout**
## Description

This PR exists to test our new GitHub actions workflow to automatically backport PRs to other branches.

## Related issues

Fixes the issues encountered in: https://github.com/zeebe-io/zeebe/pull/5818

### CODE REVIEW

**Comment by korthout** [comment]
@pihme please see https://github.com/zeebe-io/zeebe/pull/5818#issuecomment-726210155 first

**Review by pihme — CHANGES_REQUESTED** [review]
I think you picked the wrong target branch. It should be backport-demo and not develop.
(unless I missed something)

**Review by pihme — APPROVED** [review]
🍀

**Comment by pihme** [comment]
... the excitement is palpable ...

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by korthout** [comment]
bors retry

**Comment by korthout** [comment]
bors retry

**Pull request merged**
