### PR TITLE
Fixed a bug with line wrapping in zbctl status

### PR DESCRIPTION
**Pull request by jonathanlukas**
## Description

I came across a bug where the line wrapping was not done correctly when fetching `zbctl status`.

## Related issues

I have not created an issue, yet I can provide an example:

```
Cluster size: 3
Partitions count: 2
Replication factor: 3
Gateway version: 1.2.4
Brokers:
  Broker 0 - zeebe-0.zeebe-broker-service.fa669840-fd18-48d1-99b1-b251c5f37709-zeebe.svc.cluster.local:26501
    Version: 1.2.4
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy
  Broker 1 - zeebe-1.zeebe-broker-service.fa669840-fd18-48d1-99b1-b251c5f37709-zeebe.svc.cluster.local:26501
    Version: 1.2.4
    Partition 1 : Leader, Healthy
    Partition 2 : Leader, Healthy  Broker 2 - zeebe-2.zeebe-broker-service.fa669840-fd18-48d1-99b1-b251c5f37709-zeebe.svc.cluster.local:26501
    Version: 1.2.4
    Partition 1 : Follower, Healthy
    Partition 2 : Follower, Healthy

```
As you can see, the Broker 2 is not wrapped. This was because a line break was only done as long as the index for iterating Brokers or the index for iterating partitions was smaller than the amount of partitions -1.

My fix now compares the index of the Broker with the amount of brokers -1 and the index of the Partition with the amount of partitions -1.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by Zelldon** [comment]
Awesome @jonathanlukas thanks for your contribution I will take a look at it. I was as well wondering several times why this still happens :laughing:

**Comment by Zelldon** [comment]
@jonathanlukas so all tests are green looks good from my side, just need to adjust the commit message after that we can merge your PR :)

**Comment by jonathanlukas** [comment]
Alright 👍  is done. Thank you for the blueprint. And sorry I did not read the contribution guide in depth before 😅

**Review by ChrisKujawa — APPROVED** [review]
Awesome thanks @jonathanlukas no worries :) 

bors r+

**Pull request merged**
