### PR TITLE
Add monitor backup API endpoint

### LINKED ISSUE #9902: Implement monitor backup api in gateway
Depends on #9807 

- Define user interface
- Gateway sends backup status query to all partitions
- Gateway aggregates responses from all partitions and send the response to the user

Tasks:
- [x] #10288
- [ ] Implement actuator endpoint for backup status query

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR extends the backup management endpoint to add a monitoring API under `GET /{id}` (e.g. if the actuator is at `http://localhost:9600/actuator/backups`, then `GET http://localhost:9600/actuator/backups/{id}`).

At the moment we use the internal types provided by the broker client as the response types, but in the future this will be replaced by the OpenAPI generated types. As such, I didn't think it was necessary to create user facing types and write some mapping code, since we will scrape it and replace it. However, I understand that we don't know when that will done, so I'm open to doing it anyway for safety.

The acceptance tests were updated (and renamed to better reflect what they do), and as they overlap with the old `BackupIT` tests, those were deleted.

## Related issues

closes #9902 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
This PR is blocked by https://github.com/camunda/zeebe/pull/10411 - please review that first.

**Comment by npepinpe** [comment]
I'm confused why these changes would cause so many flaky tests that are unrelated to backups.

**Review by lenaschoenburg — APPROVED** [review]
Looks good to me :+1: 

I guess as long as we can change the return types in a backwards compatible manner we don't need to do any type conversion :shrug:

**Comment by npepinpe** [comment]
Right now they happen to match. So as long as we don't change them, :ok_hand: This means we should work on improving the API now and not in a year, as the longer we wait the higher the likelihood of us needing to change these internal types. That said, I did look at them, and while they're internal, they're only used for this specific use case, so the likelihood that we change them is probably quite low :smile:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
Guess it will time out again

**Comment by npepinpe** [comment]
Anyway one of the job failed since it couldn't fetch a dependency.

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
I will resolve the conflict and get this PR merged.

**Comment by deepthidevaki** [comment]
bors merge

**Pull request merged**
