### PR TITLE
deps(maven): bump elasticsearch from 7.17.10 to 8.7.1

### LINKED ISSUE #12859: Update Elasticsearch client to 8.7
Zeebe 8.3 is [supposed to](https://confluence.camunda.com/display/HAN/Camunda+8+Supported+Environments) support Elasticsearch 8.7+

The curator is no longer compatible with ES8, so we've added the ability to configure an ILM policy:
- https://github.com/camunda/zeebe/pull/12147
- https://github.com/camunda/zeebe/issues/12132

What is still left over is to update the Elasticsearch client to the latest 8.7 version.

This is not updated automatically, due to our [dependabot configuration](https://github.com/camunda/zeebe/blob/main/.github/dependabot.yml#L20C1-L23), so we'll need to update it manually:
- https://github.com/camunda/zeebe/pull/9308
- https://github.com/camunda/zeebe/pull/11563

Also see, the last dependabot PR for this: 
- https://github.com/camunda/zeebe/issues/9287

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Bumps Elasticsearch to 8.7.1. C8 should support ES8 starting from 8.3.

## Related issues

closes #12859 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by korthout** [comment]
❓ @remcowesterhoud Can you perform a manual test for this as well?

https://github.com/camunda/zeebe/issues/12859 mentions:
>manually test to see that we can export into ES 8.7 with it

I think this may be good to verify in addition to all our automated testing

**Review by korthout — APPROVED** [review]
LGTM 👍

**Comment by remcowesterhoud** [comment]
> ❓ @remcowesterhoud Can you perform a manual test for this as well?
> 
> 
> 
> https://github.com/camunda/zeebe/issues/12859 mentions:
> 
> >manually test to see that we can export into ES 8.7 with it
> 
> 
> 
> I think this may be good to verify in addition to all our automated testing

Isn't this exactly what our CI does though? It spins up an ES container and exports to it.
I can do it manually but it will be the same thing 😄

**Comment by korthout** [comment]
I guess you're right 😄 

bors merge

**Pull request merged**
