### PR TITLE
[Backport stable/8.2] Recover data written to wrong column families

### PR DESCRIPTION
**Pull request by korthout**
# Description
Backport of #16072 to `stable/8.2`.

relates to #15804

This pull request helps this version recover any data that may be lost by writing to wrong column families by previous accidental re-orderings of the Column Families.

It builds on the knowledge that we can no longer accidentally re-order the column families:
- #16131

I used the following command to backport these commits:

```sh
git cherry-pick -x 5022abe013..korthout-15804-recover-column-families
```

There was a conflict on 490181a1defc311fcaf1304a573435f57363eeec, please see the commit message for details.

Additionally, I had to add 5fa2a64 and 3b39ee9 to fix references for 8.2

~~More importantly, f3807c4e565d15db1fcee58474b29fda2947db66 copies the column families class from `main`. This should allow easier backporting in the future because the files are now the same. However, this was a difficult commit because many references had to be updated as they were referring to a column family that has been renamed on newer versions.~~

EDIT: I've removed that commit, in favor of keeping the column families as they were. This is much safer. There are tests in place that ensure we don't skew the column families again.

Lastly, 801d6ee and ef014f7 were needed to deal with a missing `count` method.

### CODE REVIEW

**Comment by korthout** [comment]
@nicpuppa @Zelldon Please have a look 🙇

While this backports the code, the number of changes are increasing. Please see the PR description for details.

**Review by nicpuppa — APPROVED** [review]
LGTM, thanks for the fantastic commit messages 👍

**Review by ChrisKujawa — APPROVED** [review]
Thanks @korthout I haven't gone into much detail. I reviewed it on the high-level and looks good to me. 

💭 One thing I thought was that we could have also add an update test to check the migration is done correctly, but nothing you have to do now. Maybe we can add this later.

**Comment by korthout** [comment]
>an update test to check the migration is done correctly

@Zelldon What do you mean exactly by this? 

Do you mean that this situation is resolved? That's what the `ColumnFamilyPrefixCorrectionMigrationTest` tests. What else could we test on updates? I believe most of the update tests verify specific properties, like being able to complete a previously activated job.

**Comment by Zelldon** [comment]
> > an update test to check the migration is done correctly
> 
> @Zelldon What do you mean exactly by this?
> 
> Do you mean that this situation is resolved? That's what the `ColumnFamilyPrefixCorrectionMigrationTest` tests. What else could we test on updates? I believe most of the update tests verify specific properties, like being able to complete a previously activated job.

Yes I felt the setup of the tests where quite hard/manual. I was thinking of a integration style of tests, with test containers. That tests this in a whole. Start with 8.1, create messages, signals, etc. Migrate. Check whether the columnfamilies are correctly migrated. 🤷🏼

**Pull request merged**
