### PR TITLE
Engine clean up packages

### PR DESCRIPTION
**Pull request by saig0**
## Description

* change package structure in the `engine`
* move SBE util into protocol package
* move duration util to its only usage in `broker`

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by saig0** [comment]
@korthout, this is my proposal for the new package structure.
The review is maybe easier if you check out the new structure instead of looking at the changes :sweat_smile:

**Review by korthout — APPROVED** [review]
@saig0 great work, this was reasonably easy to review, considering the size of the changes (~7000 lines in `less`). I think this is a big improvement over the previous package structure. I also like the clean-up of things (that I guess happened automatically) like:
```
-        new TypedRecordProcessor<JobRecord>() {
+        new TypedRecordProcessor<>() {
```
Sorry for keeping you waiting on this review for so long. I hope the conflicts are easily resolved.

**Comment by saig0** [comment]
:tada:

**Pull request merged**
