### PR TITLE
chore(broker): removed nested transaction calls

### LINKED ISSUE #2138: Remove nested transaction calls
After migrating to a transactional DB, we still have some calls leftover (e.g. in the `JobState`) which want to execute some things in a transaction, even though the whole process record runs in a transaction.

This isn't urgent, as we're not actually running nested transactions (even if it looks like it), but we should clean it up anyway.

### PR DESCRIPTION
**Pull request by miguelpires**
closes #2138

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:ok_hand:

**Review by npepinpe — CHANGES_REQUESTED** [review]
Please make sure that components accessing the states outside of stream processing are wrapping the access in a transaction.

**Comment by MiguelPires** [comment]
Hey @npepinpe, I addressed your comment. Please have a look when you can.

**Comment by npepinpe** [comment]
Really sorry but I'm thinking this issue is actually a bad idea, and we should keep writing our state operations (e.g. `createIncident` with transactions). Sorry :see_no_evil: ! We can discuss it in person if you want

**Pull request closed without merging**
