### PR TITLE
chore(bench): update benchmark folders

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Updates the long run and operate benchmark to the latest changes

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
How is the operate benchmark connecting to elastic? No exporter is configured? It looks like it was already the case, so I guess no harm done, but I don't get how their benchmark works at all then :sweat_smile:

**Comment by Zelldon** [comment]
Why do you think that? It is configured in the charts i think. For me it worked😅

**Comment by npepinpe** [comment]
Aaah, they use a different chart, true, my bad :see_no_evil:

**Pull request merged**
