### PR TITLE
Apply event sourcing to closing process message subscriptions 

### LINKED ISSUE #6200: Restore event subscriptions on replay
**Description**

The stream processor uses event subscriptions/triggers when a BPMN element can be triggered by an event. The subscriptions/triggers store which element instance should be triggered and if it can be triggered (or if another subscription of this element instance is already triggered).

* restore the event subscriptions on replay 

Reference:
* [ZEP: Boundary Event](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md#interrupting-timer-boundary-event)

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR introduces a new `ProcessMessageSubscriptionIntent.DELETING` intent which represents the closing state of the subscription, and removes the last state changes that occur in processing when closing the subscription. This is moved to a new applier, which is also processed on replay. One caveat, the command sent time is now also not deterministic as it's calculated in the applier, which will be addressed in #6364.

## Related issues

closes #6200 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
This PR includes https://github.com/camunda-cloud/zeebe/pull/6836 at the moment - please review this one first! Once done, you can already review this PR, which consists of the last 3 commits.

**Review by saig0 — APPROVED** [review]
Looks good :+1: 

We could write a test case to verify that the new `deleting` record is written and have the correct values (e.g. in `MessageCatchElementTest#shouldCloseProcessMessageSubscription`).

**Comment by npepinpe** [comment]
You're right, that's a big oversight on my part, sorry :see_no_evil:

**Pull request merged**
