### PR TITLE
Keep track of catch events in the Engine

### LINKED ISSUE #13410: Indicate the type of activated/completed/terminated catch events in Grafana
**Is your feature request related to a problem? Please describe.**
In the past weeks, there was a support case where it reports that the Engine is lagging behind while process new records. The incident was resolved afterwards. The incident was caused by a timer catch event that keeps generating multiple new records, so that the thread pool was busy with generating new records.

While investigating in Grafana, the team were able to observe a catch event was taking the CPU time but cannot see which type of catch event was causing the issue. Therefore, cannot root cause the issue without looking at other log resources.

**Describe the solution you'd like**
The type of events should be added to Grafana `General Overview -> Current Events` view. Every element instance should contains its own type

**Describe alternatives you've considered**
Alternative way to achieve the same goal is to look at export logs which takes more time and less accessible than Grafana.

**Additional context**
It is more precise if we have activation, completion and termination information of catch events in the view.

### LINKED ISSUE #13433: Keep track of event types in the Engine
**Is your feature request related to a problem? Please describe.**
As described in the issue #13410, we want to keep track of event types that triggered elements in Grafana. This is not possible without actually adding them to the job metric in the Engine.

**Describe the solution you'd like**
Update `ProcessEngineMetrics` class to event types for `element_instance_events_total` metric. Then, update their usages for activated/completed/terminated element instances.

**Describe alternatives you've considered**
As long as we want to show these metrics in Grafana, there is no a real alternative than keeping track of this metric in the Engine.

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

With this PR we can now have evidence of the event type in our dashboard.

## Related issues

closes #13433 
closes #13410 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by berkaycanbc — CHANGES_REQUESTED** [review]
Great job @nicpuppa! We even implemented it for other element types! 🚀 

I had one minor request.

🔧 Plus, it would be good if we update the issue description that mentions all element instances will now contain information that shows which event type triggered them.

**Comment by nicpuppa** [comment]
Thanks for the review @berkaycanbc, applied your suggestion 🚀 

I updated also the issue, feel free to update the description if you want more detail as you are the creator 🙇 

Please give another look 👀

**Review by berkaycanbc — APPROVED** [review]
LGTM! @nicpuppa

I also updated the title and description of #13433. 👍

**Comment by nicpuppa** [comment]
bors merge

**Pull request merged**
