### PR TITLE
refactor(broker): refactor snapshot director for readability

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

The chain of actions required to take a snapshot is difficult to understand because of the inability to compose actor futures. In this PR, we refactored it with a rudimentary way of composing actor futures. I hope it is more readable this way. We have applied a similar technique in `BackupService`.

There is no behavior change. With this change, it is easy to allow multiple ongoing snapshots. But to keep the behavior as it is, we still do not allow multiple ongoing snapshot.

For #11423 , we have to flush the journal before the snapshot is committed. With this PR, it is easy to add one step before committing snapshot.

### CODE REVIEW

**Comment by megglos** [comment]
@deepthidevaki given we aim for backporting #11423 should this get backported too?

**Comment by deepthidevaki** [comment]
> given we aim for backporting #11423 should this get backported too?

That's a good point. I hadn't thought about it. It would be safe to backport this as there is no behavior change. It would make it easier to backport #11423 if we backport this. But we can also do it with out this. @oleschoenburg please share your thoughts after you review this.

**Review by lenaschoenburg — APPROVED** [review]
Nice work @deepthidevaki, it really is much more readable and should be more robust :rocket:
I'm comfortable with backporting this too :+1:

**Comment by deepthidevaki** [comment]
Thanks. I will backport this to 8.1.

**Comment by deepthidevaki** [comment]
bors merge

**Pull request merged**
