### PR TITLE
fix: use thread-safe collection of snapshot stores

### LINKED ISSUE #14207: Zeebe partition can't find snapshot store
**Describe the bug**

During transition of a `ZeebePartition` we encounter the following NPE:

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.scheduler.ConcurrencyControl.createFuture()" because "this.concurrencyControl" is null
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.recover(StateControllerImpl.java:73) ~[zeebe-broker-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.ZeebeDbPartitionTransitionStep.recoverDb(ZeebeDbPartitionTransitionStep.java:70) ~[zeebe-broker-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.ZeebeDbPartitionTransitionStep.transitionTo(ZeebeDbPartitionTransitionStep.java:53) ~[zeebe-broker-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionProcess.lambda$proceedWithTransition$1(PartitionTransitionProcess.java:89) ~[zeebe-broker-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
```

This happens when the `StateController` was constructed without a `ConcurrencyControl` which _should_ be available in the `FileBasedSnapshotStoreFactory` because the raft partition creates it during startup.

The impact is a failed partition startup, resulting in an unhealthy broker and possibly to an unavailable partition.

**To Reproduce**
Start a cluster with many partitions, for example partitionCount=32, brokerCount=8, replicationFactor=3.

**Expected behavior**

No NPE and partition starts cleanly.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```

java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.scheduler.ConcurrencyControl.createFuture()" because "this.concurrencyControl" is null
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.recover(StateControllerImpl.java:73) ~[zeebe-broker-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.ZeebeDbPartitionTransitionStep.recoverDb(ZeebeDbPartitionTransitionStep.java:70) ~[zeebe-broker-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.broker.system.partitions.impl.steps.ZeebeDbPartitionTransitionStep.transitionTo(ZeebeDbPartitionTransitionStep.java:53) ~[zeebe-broker-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionProcess.lambda$proceedWithTransition$1(PartitionTransitionProcess.java:89) ~[zeebe-broker-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) ~[zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:109) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:204) [zeebe-scheduler-8.3.0-alpha5.jar:8.3.0-alpha5]

```

</p>
</details>

**Environment:**
- Zeebe Version: 8.3.0-alpha5

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Fixes #14207 by using a thread safe data structure to hold onto snapshot stores. This bug was introduced with #13819 but not noticed because it is probabilistic and depends on the number of partitions. Since we usually test with low partition count, the bug wasn't observed during QA.

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
Thanks for fixing it fast. It is probably not straightforward to add a regression test. Hopefully your ongoing refactoring can completely remove the map.

**Comment by oleschoenburg** [comment]
bors merge

**Comment by oleschoenburg** [comment]
bors cancel

Formatting error...

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
