### PR TITLE
Not retrigger Timer start events

### LINKED ISSUE #6515: Redeploying process model with Timer start event causes retriggering
**Describe the bug**

A workflow with timer start event and expression to schedule the timer, after 1 minute after deployment, will be rescheduled if we deploy the exact same deployment again. Tbh. I'm not sure whether we want to see this as a bug or "feature", but might be not the expected behavior.

chaosTimerStart

<sup>_Have been found via Chaos Day https://zeebe-io.github.io/zeebe-chaos/chaos_experiment/broker/processing/2021/02/23/cont-workflow-instance.html_</sup>

**To Reproduce**

Deploy a model, with timer start event and expression to schedule the timer in a duration, multiple times.

Example expression: `=now()+ duration("PT1M")`

**Expected behavior**

Not rescheduling the timer I would assume.

**Environment:**
 - OS: k8
 - Zeebe Version: 1.0.0-SNAPSHOT
 - Configuration: doesnt matter

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

 * introduce new property on the ProcessMetadata to mark a process as duplicate during deployment
   * Is useful to handle duplicates differently
   * Makes it possible to not recalculate whether a process is a duplicate
 * Do not recreate timer subscription on duplicate process 

## Related issues

closes #6515 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by saig0 — CHANGES_REQUESTED** [review]
In general, it looks good :+1: 

But if we introduce a new property `isDuplicate` then we should export the property and test that it is set correctly. Currently, the property is used but tested only indirectly by the timer start event. The property could be also useful for consumers of the stream.

Do you see a reason for hiding the property?

**Comment by Zelldon** [comment]
@saig0 also fine for me. I just thought it is not used for other cases and you maybe don't like :sweat_smile: which was the reason why we wouldn't export it :D

**Review by saig0 — APPROVED** [review]
Make sense. We don't need to do it immediately :+1: 

Please create a follow-up issue to expose the new property (in the record/export API and the client/gRPC API). Thanks :cake:

**Comment by Zelldon** [comment]
bors r+

I created https://github.com/camunda-cloud/zeebe/issues/6968

**Pull request merged**
