### PR TITLE
refactor(logstreams): avoid holding on to complete batch

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

Avoid holding a strong reference on the whole sequenced batch in the instrumented appender listener. This will ensure we don't hold onto the complete payload which could be tens or hundreds of megabytes, possibly leading to OOMs if we append too much too fast.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
@Zelldon - better even would be to build the required metadata when we're building the sequenced batch (so no iterating required at all), but then it's kind of coupling things together, and iterating over just to copy some enums is fairly cheap :shrug:

**Comment by Zelldon** [comment]
> @Zelldon - better even would be to build the required metadata when we're building the sequenced batch (so no iterating required at all), but then it's kind of coupling things together, and iterating over just to copy some enums is fairly cheap 🤷

Yeah that is what I meant when discussing it with you. I think I would prefer something like when we #append that we register some counter for some certain type/intent etc. And this is carried along with the records. As soon as the records are written/appened we can extract the metrics data and publish it.

**Comment by npepinpe** [comment]
Yeah, but isn't this coupling the result builder to the metrics here, since this is the only reason we're even keeping this data? I think we can merge this as sequenced batches won't have thousands and thousands of items, so iterating once to just grab a few fields is likely quite cheap, unless we have a good reason to do it at the source already :thinking:

**Review by ChrisKujawa — APPROVED** [review]
I think I would feel better if we calculate the metrics directly on creation of the batch, but lets see whether it is a problem. If so we know how to improve.

**Comment by npepinpe** [comment]
If we calculate them at creation but before writing, we risk counting commands we're not even writing though - e.g. cached commands, commands exceeding the batch, commands counted before a failure, etc. Add the multiple "result builder" sources that all need to do this tracking, refactoring the `pendingWrites` in the state machine to keep track of both entries and metadata, etc. I think it's more refactoring than you'd expect. But maybe I'm missing some easy way of doing it?

**Comment by npepinpe** [comment]
I'll merge as there's immediate value, and AFAIK refactoring to create the metadata at the source is time consuming due to all the changes that have to trickle down. If you want we can pair some time on this later to follow up, maybe you already had an idea of how it's not so much effort.

I was thinking you'd need to add the `LogAppendBatch` interface to the logstream module, then basically pass that around to your writer. The batch contains the entries and the metadata. It's basically your `RecordBatch` in the stream module. But when I tried it, it quickly became much more refactoring than I expected =/

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
