### PR TITLE
Migrate error boundary events

### LINKED ISSUE #21866: Migrate error boundary events
## Description
It should be possible to migrate tasks with error boundary events. Error catch event doesn't have a subscription record but its **static** error code stored in the catch event element itself. When an error is thrown, the error catch event is accessed through the process instance itself.

Given above, there is no need (or no way) to introduce a migration intent for error catch event. Consider the following example, where an active service tasks has an error boundary event attached. When migrating the process instance the error boundary event will be migrated to the target process **regardless of mapping instruction is provided for the error boundary element or not**. After the instance is migrated, **the error code will be updated** as in the target process since it is static value.

Screenshot 2024-09-06 at 13 23 27

Two things needs to be implemented:
- Add `BpmnEventType.ERROR` to supported boundary element types
- Verify a task can be migrated with a error boundary event

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description
It should be possible to migrate tasks with error boundary events. Error catch event doesn't have a subscription record but its **static** error code stored in the catch event element itself. When an error is thrown, the error catch event is accessed through the process instance itself.

Given above, there is no need (or no way) to introduce a migration intent for error catch event. Consider the following example, where an active service tasks has an error boundary event attached. When migrating the process instance the error boundary event will be migrated to the target process **regardless of mapping instruction is provided for the error boundary element or not**. After the instance is migrated, **the error code will be updated** as in the target process since it is static value.

Screenshot 2024-09-06 at 13 23 27

Two things needs to be implemented:
- Add `BpmnEventType.ERROR` to supported boundary element types
- Verify a task can be migrated with a error boundary event

## Related issues

closes #21866

### CODE REVIEW

**Review by koevskinikola — APPROVED** [review]
LGTM @berkaycanbc 👍

**Review by koevskinikola — CHANGES_REQUESTED** [review]
@berkaycanbc I just checked the CI results.

The `MigrateProcessInstanceRejectionTest.shouldRejectCommandWhenTheMigratedProcessInstanceHasATaskSubscribedToAnErrorBoundaryEvent` is failing, I'm guessing because error boundary events can be migrated now. 

So I guess we need to remove this test now.

**Comment by berkaycanbc** [comment]
@koevskinikola yes, missed that one. Removed the test now. ✅

**Review by koevskinikola — APPROVED** [review]
❌ @berkaycanbc there seems to be some more "migration rejection" test failures and some format violations as well.

However, it's clear that the main functionality of this PR is correct, so I'm pre-approving it. ✅

**Pull request merged**
