### PR TITLE
Fix NPE because of missing decisionId of failed decision evaluation

### LINKED ISSUE #9344: NPE: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "value" is null
**Describe the bug**

Looks similar to https://github.com/camunda/zeebe/issues/9269. It seems something in the decision evaluation is null, looks like the `.setFailedDecisionId` is failing. Happening on prod with Camunda 8.0.0.

Error group https://console.cloud.google.com/errors/detail/CKWO74bjv6a2owE;service=zeebe;time=P7D?project=camunda-cloud-240911

**To Reproduce**

Backup of logs and models can be found here https://drive.google.com/drive/u/0/folders/1WGHcsqwXDGFbGMBqrACaDfW_vjkVnMEQ

Log details https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22db0e535c-9198-4185-a526-c81f610969e8-zeebe%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22;timeRange=2022-05-10T10:59:04.524Z%2F2022-05-10T11:59:04.524Z;pinnedLogId=2022-05-10T11:28:34.524275289Z%2Fmtmd0orxighigvni;cursorTimestamp=2022-05-10T11:15:46.967095281Z?project=camunda-cloud-240911

**Expected behavior**
No NPE.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "value" is null

at io.camunda.zeebe.util.StringUtil.getBytes ( [io/camunda.zeebe.util/StringUtil.java:39](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util%2FStringUtil.java&line=39&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.StringUtil.getBytes ( [io/camunda.zeebe.util/StringUtil.java:35](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util%2FStringUtil.java&line=35&project=camunda-cloud-240911) )
at io.camunda.zeebe.msgpack.property.StringProperty.setValue ( [io/camunda.zeebe.msgpack.property/StringProperty.java:30](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.msgpack.property%2FStringProperty.java&line=30&project=camunda-cloud-240911) )
at io.camunda.zeebe.protocol.impl.record.value.decision.DecisionEvaluationRecord.setFailedDecisionId ( [io/camunda.zeebe.protocol.impl.record.value.decision/DecisionEvaluationRecord.java:247](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.protocol.impl.record.value.decision%2FDecisionEvaluationRecord.java&line=247&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.writeDecisionEvaluationEvent ( [io/camunda.zeebe.engine.processing.bpmn.behavior/BpmnDecisionBehavior.java:254](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn.behavior%2FBpmnDecisionBehavior.java&line=254&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.lambda$evaluateDecision$3 ( [io/camunda.zeebe.engine.processing.bpmn.behavior/BpmnDecisionBehavior.java:114](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn.behavior%2FBpmnDecisionBehavior.java&line=114&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.Either$Right.flatMap ( [io/camunda.zeebe.util/Either.java:366](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util%2FEither.java&line=366&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnDecisionBehavior.evaluateDecision ( [io/camunda.zeebe.engine.processing.bpmn.behavior/BpmnDecisionBehavior.java:109](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn.behavior%2FBpmnDecisionBehavior.java&line=109&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor$CalledDecisionBehavior.lambda$onActivate$0 ( [io/camunda.zeebe.engine.processing.bpmn.task/BusinessRuleTaskProcessor.java:89](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn.task%2FBusinessRuleTaskProcessor.java&line=89&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.Either$Right.flatMap ( [io/camunda.zeebe.util/Either.java:366](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util%2FEither.java&line=366&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor$CalledDecisionBehavior.onActivate ( [io/camunda.zeebe.engine.processing.bpmn.task/BusinessRuleTaskProcessor.java:89](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn.task%2FBusinessRuleTaskProcessor.java&line=89&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor.onActivate ( [io/camunda.zeebe.engine.processing.bpmn.task/BusinessRuleTaskProcessor.java:40](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn.task%2FBusinessRuleTaskProcessor.java&line=40&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.task.BusinessRuleTaskProcessor.onActivate ( [io/camunda.zeebe.engine.processing.bpmn.task/BusinessRuleTaskProcessor.java:21](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn.task%2FBusinessRuleTaskProcessor.java&line=21&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$2 ( [io/camunda.zeebe.engine.processing.bpmn/BpmnStreamProcessor.java:128](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn%2FBpmnStreamProcessor.java&line=128&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.Either$Right.ifRightOrLeft ( [io/camunda.zeebe.util/Either.java:381](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util%2FEither.java&line=381&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent ( [io/camunda.zeebe.engine.processing.bpmn/BpmnStreamProcessor.java:127](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn%2FBpmnStreamProcessor.java&line=127&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0 ( [io/camunda.zeebe.engine.processing.bpmn/BpmnStreamProcessor.java:110](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn%2FBpmnStreamProcessor.java&line=110&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.Either$Right.ifRightOrLeft ( [io/camunda.zeebe.util/Either.java:381](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util%2FEither.java&line=381&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord ( [io/camunda.zeebe.engine.processing.bpmn/BpmnStreamProcessor.java:107](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.bpmn%2FBpmnStreamProcessor.java&line=107&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.streamprocessor.TypedRecordProcessor.processRecord ( [io/camunda.zeebe.engine.processing.streamprocessor/TypedRecordProcessor.java:54](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.streamprocessor%2FTypedRecordProcessor.java&line=54&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.lambda$processInTransaction$3 ( [io/camunda.zeebe.engine.processing.streamprocessor/ProcessingStateMachine.java:300](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.streamprocessor%2FProcessingStateMachine.java&line=300&project=camunda-cloud-240911) )
at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run ( [io/camunda.zeebe.db.impl.rocksdb.transaction/ZeebeTransaction.java:84](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.db.impl.rocksdb.transaction%2FZeebeTransaction.java&line=84&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processInTransaction ( [io/camunda.zeebe.engine.processing.streamprocessor/ProcessingStateMachine.java:290](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.streamprocessor%2FProcessingStateMachine.java&line=290&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.processCommand ( [io/camunda.zeebe.engine.processing.streamprocessor/ProcessingStateMachine.java:253](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.streamprocessor%2FProcessingStateMachine.java&line=253&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.tryToReadNextRecord ( [io/camunda.zeebe.engine.processing.streamprocessor/ProcessingStateMachine.java:213](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.streamprocessor%2FProcessingStateMachine.java&line=213&project=camunda-cloud-240911) )
at io.camunda.zeebe.engine.processing.streamprocessor.ProcessingStateMachine.readNextRecord ( [io/camunda.zeebe.engine.processing.streamprocessor/ProcessingStateMachine.java:189](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.engine.processing.streamprocessor%2FProcessingStateMachine.java&line=189&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.sched.ActorJob.invoke ( [io/camunda.zeebe.util.sched/ActorJob.java:79](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorJob.java&line=79&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.sched.ActorJob.execute ( [io/camunda.zeebe.util.sched/ActorJob.java:44](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorJob.java&line=44&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.sched.ActorTask.execute ( [io/camunda.zeebe.util.sched/ActorTask.java:122](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorTask.java&line=122&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask ( [io/camunda.zeebe.util.sched/ActorThread.java:97](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorThread.java&line=97&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.sched.ActorThread.doWork ( [io/camunda.zeebe.util.sched/ActorThread.java:80](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorThread.java&line=80&project=camunda-cloud-240911) )
at io.camunda.zeebe.util.sched.ActorThread.run ( [io/camunda.zeebe.util.sched/ActorThread.java:189](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorThread.java&line=189&project=camunda-cloud-240911) )
```

</p>
</details>

**Environment:**
- OS: SaaS
- Zeebe Version: 8.0.0
- Configuration:

### PR DESCRIPTION
**Pull request by korthout**
## Description

When the decision evaluation fails, a DECISION_EVALUATION record with FAILED intent is written, containing relevant information about the failure. This includes the id of the decision that failed. However, in 2 cases it might happen that a `null` value would be used, which cannot be written into a record, leading to a NullPointerException (NPE).

Both NPEs can be avoided by not using `null`, but using reasonable defaults instead. In both cases, the id of the decision that was intended to be evaluated can be used as the replacement of this `null`.

While we were able to discover the NPEs' causes from the code and the stack traces, we were unable to reproduce the situation from a user's perspective. I've thus left out a regression test for it.

## Related issues

closes #9344 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [x] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by saig0 — DISMISSED** [review]
@korthout LGTM :+1:

**Comment by korthout** [comment]
@saig0 The merge failed because of test failures. I've adjusted the affected tests, please have another look

**Review by saig0 — APPROVED** [review]
@korthout :+1:

**Comment by korthout** [comment]
bors merge

**Pull request merged**
