### PR TITLE
feat: add execution count toggle

### LINKED ISSUE #19562: I can toggle the execution count badges in process instance details view
Depends on https://github.com/camunda/camunda/issues/19558

### User Story

```Gherkin
Scenario: As an Operate user
    Given I am in instance details view
    When The process instance has some executed elements
    Then I can toggle the visibility of execution count badges
```
### Designs
[Figma](https://www.figma.com/design/2iYV26UW5TwEhU4LooOCMF/Better-visualization-of-the-executed-path?node-id=1100-57276&t=MgdB8QPfonRNRNaw-1)

### Acceptance Criteria

- [x] There is a toggle button in the instance history header (see designs for label)
- [x] The visibility of the execution count badges can be toggled by clicking the button
- [x] By default the execution count badges are not visible and the button toggle state is _off_
- [x] The toggle state is not persisted when the user refreshes the page, the default state is active (toggled off)

### Definition of Ready - Checklist

- [x] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

### PR DESCRIPTION
**Pull request by pedesen**
## Description

- Add toggle
- Add e2e test for toggle
- Enable toggle in a visual regression test
- Update visual regression snapshots

## Related issues

closes #19562

### CODE REVIEW

**Review by vitorwtavares — APPROVED** [review]

**Comment by pedesen** [comment]
@gastonpillet01 Here's the docker image: `registry.camunda.cloud/team-operate/camunda-operate:branch-fe-19562-toggle-execution-count-badges`

**Review by gastonpillet01 — APPROVED** [review]
Execution count toggle correctly added

**Review by Szik — CHANGES_REQUESTED** [review]
Bildschirmfoto vom 2024-06-27 16-49-11

Toggle not visible with this "broken" path after the "Event based gateway"

**Comment by Szik** [comment]
after refreshing page, toggle is visible and works as expected. path from gateway still uncolored.

**Comment by pedesen** [comment]
@Szik I was not able to reproduce the missing toggle button. I assume it might be a browser cache issue.

The uncolored sequence flow after the event-based gateway seems to be an issue in Zeebe (see https://github.com/camunda/camunda/issues/13215)

**Review by Szik — APPROVED** [review]

**Pull request merged**
