### PR TITLE
fix: Get rid of ElasticsearchExceptionMapper #22522

### LINKED ISSUE #22522: Test is failing in SingleProcessReportHandlingIT
### Describe the bug

SingleProcessReportHandlingIT.databaseStatusExceptionIsMapped test is failing

### Environment observed:

- Optimize mode(s):
- Optimize version(s):
- Database(s) (Elasticsearch/OpenSearch):

### Breakdown

```[tasklist]
### Pull Requests
- [ ] https://github.com/camunda/camunda/pull/22531
```

## Bug Lifecycle

For managing the issue lifecycle, please use the workflow commands. You can see the available
commands by writing `/help` as a comment on this issue.

### QA Verification

Is this bug reproducible?

- [ ] Yes. If so:
  - [ ] The bug description is clear
  - [ ] The steps to reproduce are clear
  - [ ] The environments observed are correct and complete
- [ ] No

#### Engineering Review

- [ ] All code targeting the main branch has been reviewed by at least one Engineer
- [ ] The PR targeting the main branch has been approved by the reviewing Engineer
- [ ] If the API has changed, the API documentation is updated
- [ ] All other PRs (docs, controller etc.) in the breakdown have been approved

#### QA Review

- [ ] The change is implemented as described on all target environments/versions/modes
- [ ] The documentation changes are as expected

### Completion

- [ ] All Review stages are successfully completed
- [ ] All associated PRs are merged to the main branch(es) and stable branches
- [ ] The correct version labels are applied to the issue

### PR DESCRIPTION
**Pull request by oleksandr-kriuchenko-lohika**
## Description

Get rid of ElasticsearchExceptionMapper

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #22522

### CODE REVIEW

**Review by HeleneW-dot — CHANGES_REQUESTED** [review]
So the PR does what the commit says, but the linked ticket mentions test failures that this is supposed to fix: does this mean there are IT that need to have the OS failing tag removed in this PR? 
Requesting changes just to make sure the PR matches the ticket

**Comment by oleksandr-kriuchenko-lohika** [comment]
> So the PR does what the commit says, but the linked ticket mentions test failures that this is supposed to fix: does this mean there are IT that need to have the OS failing tag removed in this PR? Requesting changes just to make sure the PR matches the ticket

Thanks for reviewing @PHWaechtler ! Yes, it comes to be somewhat odd in a sense that we now create 2 tickets - one for C7 and one for C8. So originally the issue was found in C7 integration test as mentioned in the ticket description and there it is fixed and test is marked as passing. However now we try to backport it to C8 where ITs are removed which makes ticket description somewhat irrelevant, as it basically addresses IT which is now only in C7 though we still use it for testing code changes for C8 o_0

**Comment by PHWaechtler** [comment]
> > So the PR does what the commit says, but the linked ticket mentions test failures that this is supposed to fix: does this mean there are IT that need to have the OS failing tag removed in this PR? Requesting changes just to make sure the PR matches the ticket
> 
> Thanks for reviewing @PHWaechtler ! Yes, it comes to be somewhat odd in a sense that we now create 2 tickets - one for C7 and one for C8. So originally the issue was found in C7 integration test as mentioned in the ticket description and there it is fixed and test is marked as passing. However now we try to backport it to C8 where ITs are removed which makes ticket description somewhat irrelevant, as it basically addresses IT which is now only in C7 though we still use it for testing code changes for C8 o_0

aah gotcha, yes that makes sense 👍 Is there any QA required here? If so please add some testing notes as well to the ticket 🙏

**Review by HeleneW-dot — APPROVED** [review]

**Comment by oleksandr-kriuchenko-lohika** [comment]
> > > So the PR does what the commit says, but the linked ticket mentions test failures that this is supposed to fix: does this mean there are IT that need to have the OS failing tag removed in this PR? Requesting changes just to make sure the PR matches the ticket
> > 
> > 
> > Thanks for reviewing @PHWaechtler ! Yes, it comes to be somewhat odd in a sense that we now create 2 tickets - one for C7 and one for C8. So originally the issue was found in C7 integration test as mentioned in the ticket description and there it is fixed and test is marked as passing. However now we try to backport it to C8 where ITs are removed which makes ticket description somewhat irrelevant, as it basically addresses IT which is now only in C7 though we still use it for testing code changes for C8 o_0
> 
> aah gotcha, yes that makes sense 👍 Is there any QA required here? If so please add some testing notes as well to the ticket 🙏 And how come the changes here are different from the C7 PR? Maybe Im misunderstanding but I would have thought the same changes would then need applied in both.

Thanks @PHWaechtler ! Added a comment on testing to the ticket, our git commands seem to stopped doing this.

Regarding the corresponding changes for C7 - yes, they are bascially same https://github.com/camunda/camunda-optimize/pull/14307/files. I barely tracking them myself either now )

**Comment by PHWaechtler** [comment]
> > > So the PR does what the commit says, but the linked ticket mentions test failures that this is supposed to fix: does this mean there are IT that need to have the OS failing tag removed in this PR? Requesting changes just to make sure the PR matches the ticket
> > 
> > 
> > Thanks for reviewing @PHWaechtler ! Yes, it comes to be somewhat odd in a sense that we now create 2 tickets - one for C7 and one for C8. So originally the issue was found in C7 integration test as mentioned in the ticket description and there it is fixed and test is marked as passing. However now we try to backport it to C8 where ITs are removed which makes ticket description somewhat irrelevant, as it basically addresses IT which is now only in C7 though we still use it for testing code changes for C8 o_0
> 
> aah gotcha, yes that makes sense 👍 Is there any QA required here? If so please add some testing notes as well to the ticket 🙏 And how come the changes here are different from the C7 PR? Maybe Im misunderstanding but I would have thought the same changes would then need applied in both.

Oh right, I was looking at [this](https://github.com/camunda/camunda-optimize/pull/14312#pullrequestreview-2321558978)  one because its associated with [this](https://github.com/camunda/camunda-bpm-platform/issues/4648) ticket that sounded the same but looking now its different test casees 👍

**Pull request merged**
