### PR TITLE
feat: measure processing duration by valueType and intent

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

Draft PR to sync with @npepinpe on the metrics.

## Related issues

related #9862 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

Looks great! This adds more cardinality to the metrics, but I think it's still within reason as the values are limited.

As @Zelldon pointed out, we could also add metrics for every state in the `ProcessingStateMachine`, so also measuring the side effects, committing/rollback of the RocksDB transaction, etc. Feel free to do it here or as a follow up.

**Review by npepinpe — APPROVED** [review]
:+1:

**Review by npepinpe — APPROVED** [review]

**Comment by Zelldon** [comment]
@romansmirnov do we still need this?

**Comment by npepinpe** [comment]
I think it's very useful, and I would even like more granular metrics, such as the BPMN element type, as that would've been useful (for example) during the game day to see it's processing the multi instance body which is taking so much time.

I can check with our SREs about the whole cardinality thing. If @romansmirnov is too busy I'm happy to take this over

**Comment by Zelldon** [comment]
@npepinpe did you checked with SREs?

**Pull request closed without merging**
