### PR TITLE
[backport to 0.23] fix(flaky-test): Change boundaries of port ranges for each stage

### PR DESCRIPTION
**Pull request by pihme**
## Description

backport of #4841 to 0.23

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [X] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
:tada:

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
Closing this pull request; it seems be that this change is making matters worse in 0.23

**Pull request closed without merging**
