### PR TITLE
Release 8.1.0

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Merging the release branch back to the main branch. 

@deepthidevaki @oleschoenburg someone an idea how to enable the update tests?

This is not mentioned here

release

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by Zelldon** [comment]
I guess `protocol/ignored-changes.json` should be deleted ? :thinking:

**Comment by oleschoenburg** [comment]
> someone an idea how to enable the update tests?

Not sure what you mean, update tests are always running: https://github.com/camunda/zeebe/actions/runs/3179898264/jobs/5182865429

**Comment by Zelldon** [comment]
As I mentioned it is written in the user tasks so Idk it was confusing me :shrug: 

> Before opening a PR, in case we disabled the upgrade test suite due to backwards incompatible changes, make sure to re-enable it them here, and commit these changes. Now, create a PR for the release branch targeting this base branch, and assign someone from the Zeebe team to review it.

**Comment by oleschoenburg** [comment]
I'm pretty sure we can just ignore this, sounds like "in case we disabled the upgrade test suite due to backwards incompatible changes" is not something we did lately.

**Comment by Zelldon** [comment]
@oleschoenburg I rebased with main to resolve the conflicts

**Comment by oleschoenburg** [comment]
@Zelldon looks like there are some formatting issues at least: https://github.com/camunda/zeebe/actions/runs/3180846815/jobs/5184904296

**Comment by Zelldon** [comment]
Weird.

**Comment by Zelldon** [comment]
When building the project I see the following:
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.14.7:check (check) on project zeebe-protocol: The following API problems caused the build to fail:
[ERROR] java.annotation.attributeAdded: @interface io.camunda.zeebe.protocol.record.ImmutableProtocol: Attribute 'org.immutables.value.Value.Style' of annotation '@org.immutables.value.Value.Style(get = {"is*", "get*"}, jdkOnly = true, defaults = @org.immutables.value.Value.Immutable(lazyhash = true), validationMethod = org.immutables.value.Value.Style.ValidationMethod.NONE, clearBuilder = true, allowedClasspathAnnotations = {org.immutables.value.Generated.class, javax.annotation.ParametersAreNonnullByDefault.class, javax.annotation.concurrent.Immutable.class, edu.umd.cs.findbugs.annotations.SuppressFBWarnings.class, javax.annotation.concurrent.NotThreadSafe.class, javax.annotation.Nullable.class}, attributeBuilderDetection = true, deepImmutablesDetection = true, jacksonIntegration = false, depluralize = true, init = "with*")' is now explicitly set.
[ERROR] 
[ERROR] Consult the plugin output above for suggestions on how to ignore the found problems.
```
Any idea?

**Comment by npepinpe** [comment]
Yes we modified it, but we also added that to the ignored changes, as otherwise we couldn't have merged it...not sure why it's back. You can again add it to the ignored changes if it blocks you, it's not a problem.

**Comment by megglos** [comment]
How come the ignored changes file got deleted with https://github.com/camunda/zeebe/pull/10599/commits/ea7d0459ddb98fa00f5983283d9b3f4ef54b82e8 ?

**Comment by npepinpe** [comment]
It always is, as the changes are now part of the previous version it was being compared to. What might have happened is the version it's comparing to was not updated?

**Comment by npepinpe** [comment]
Actually it was. So now the checks should compare against 8.1, and the annotation wouldn't have been changed since the change is in 8.1...or so I would assume, but clearly somethings happening

**Comment by megglos** [comment]
actually the changes are not in the 8.1.0 release, as the commit that introduced them was only maerged to `main` with https://github.com/camunda/zeebe/pull/10520 .

Thus we would need to add the ignored file with this block then?
```
{
          "justification": "Allowed annotations were fixed to prevent indirect modifications via transitive dependencies, but will not affect existing usage",
          "code": "java.annotation.attributeAdded",
          "old": "@interface io.camunda.zeebe.protocol.record.ImmutableProtocol",
          "new": "@interface io.camunda.zeebe.protocol.record.ImmutableProtocol",
          "attribute": "allowedClasspathAnnotations",
          "value": "{org.immutables.value.Generated.class, javax.annotation.ParametersAreNonnullByDefault.class, javax.annotation.concurrent.Immutable.class, edu.umd.cs.findbugs.annotations.SuppressFBWarnings.class, javax.annotation.concurrent.NotThreadSafe.class, javax.annotation.Nullable.class}"
        }
```

**Comment by Zelldon** [comment]
> How come the ignored changes file got deleted with [ea7d045](https://github.com/camunda/zeebe/commit/ea7d0459ddb98fa00f5983283d9b3f4ef54b82e8) ?
> 
> Edit: Think I got it now, this file is used to describe things to ignore between last and next minor?

Is part of the release script, see https://github.com/camunda/zeebe/blob/main/.ci/scripts/release/compat-update-java.sh#L10

**Comment by Zelldon** [comment]
> 

Good catch @megglos :see_no_evil: So I add again such file right?

**Comment by npepinpe** [comment]
Ah yes, then it makes sense :)

**Comment by Zelldon** [comment]
Ok should be fixed now.

**Comment by Zelldon** [comment]
@oleschoenburg or @megglos can someone accept?

**Review by megglos — APPROVED** [review]
LGTM!

**Pull request merged**
