### PR TITLE
feat(broker): add TLS support to gateway

### LINKED ISSUE #2836: Add TLS support on the gateway
### Objective
The goal of this issue is to add TLS to the gateway. 

### Expected Behavior
There should be a section of the gateway's config where the user can enable/disable this feature (it should be disabled by default), specify a certificate chain file and a private key file.

### PR DESCRIPTION
**Pull request by miguelpires**
# Description
Enables TLS in the Gateway and changes config files to reflect the default configuration.

# Related issues
closes #2836 

# Pull Request Checklist

- [x] I have signed the Camunda CLA
- [x] I followed the [contributor guidelines](/CONTRIBUTING.md)
- [x] All commit messages match our [commit message guidelines](/CONTRIBUTING.md#commit-message-guidelines)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally

### CODE REVIEW

**Review by npepinpe — CHANGES_REQUESTED** [review]
:+1: 

One small thing, I'm not too fond of the tests which assert nothing but just pass if no exception is thrown (e.g. `shouldStartGatewayWithoutTls` and `shouldStartGatewayWithTls`). That's kind of the expected behaviour, so since we're already testing cases that would throw exceptions, I would say let's remove those tests for now, and we will have integration tests once the Java client supports TLS for this anyway.

**Comment by MiguelPires** [comment]
What's wrong with the tests that pass if no exception is thrown? Those tests validate that the happy paths work as expected.

**Comment by npepinpe** [comment]
No worries, questions are always good.

It's more of a rule of thumb that tests which assert nothing but that no exception is thrown are a bad idea. Sometimes it might make sense, but every time you should really think about what you're testing here.

In this case, for example, what are we testing? That the gateway can start? How do we know the gateway started correctly if we don't try to connect to it? What if none of the exceptions we explicitly throw (which I guess was what we're trying to test) are thrown, but some of the config passed to netty is wrong and on connection we wouldn't be able to connect?

But I think my main reason here is that these tests will become irrelevant once the Java client can connect using TLS, since we'll have integration tests testing which will test this and more.

**Comment by MiguelPires** [comment]
I see. I would say they validate that whatever is passed into the server builder is actually there and also well-formed (it will throw an exception if the private key isn't pkcs8, for instance) but that's not really testing code, more like testing that the test cert/key is ok. And yes I agree, they cover a small subset of what the integration tests will. Thank you, I'll make some adjustments then

**Comment by MiguelPires** [comment]
Thanks for the feedback @npepinpe. I fixed the issues you mentioned in the latest commit

**Review by npepinpe — APPROVED** [review]
:+1:

**Pull request merged**
