### PR TITLE
Get gateway version in Go client

### LINKED ISSUE #3691: Get gateway version in Go client
Related to #2981

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

* Adds a gateway version RPC to the protocol
* Adds the gateway version command in the Go client
* Refactors commands package by removing the redundant "_command" suffix

## Related issues

closes #3691 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

I'm guessing you will write the docs as a separate issue? Just remember to update the gRPC docs as well.

**Comment by MiguelPires** [comment]
Thanks.

bors r+

**Comment by MiguelPires** [comment]
bors retry

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
