### PR TITLE
Release 8.0.11

### PR DESCRIPTION
**Pull request by camundait**
Merge the release branch with stable. This pull request was created by Zeebe :rocket:.

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
bors r+

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
Hmm, this test failed twice in a row now
`EmbeddedSubProcessTest#shouldNotTriggerBoundaryEventWhenFlowscopeIsInterrupted`:
```
Expecting actual:
  ["eventSubProcessStartEvent"]
to contain exactly (and in same order):
  ["msgBoundary", "eventSubProcessStartEvent"]
but could not find the following elements:
  ["msgBoundary"]

	at io.camunda.zeebe.engine.processing.bpmn.subprocess.EmbeddedSubProcessTest.shouldNotTriggerBoundaryEventWhenFlowscopeIsInterrupted(EmbeddedSubProcessTest.java:663)
```

The test was introduced here: https://github.com/camunda/zeebe/pull/11216

**Comment by oleschoenburg** [comment]
@remcowesterhoud Could you take a quick look at the error above? I'm not sure if it's new or report worthy.

**Comment by remcowesterhoud** [comment]
@oleschoenburg I'm on FTO, but I can look next week if that's okay. I don't feel like looking through stacktraces on my phone 😄

**Comment by oleschoenburg** [comment]
@remcowesterhoud Oops sorry, nevermind!

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
