### PR TITLE
Remove closed components from health monitors

### LINKED ISSUE #6938: Partition incorrectly marked as unhealthy when broker is closing.
**Describe the bug**

A partition is detected as unhealthy when the broker is closing. It is expected behavior that all running services are closed, so it is not required to detect them as unhealthy. 

```
I 2021-05-03T00:01:54.354348Z Closing Broker-0 partitions [1/3]: partition 1 
D 2021-05-03T00:01:54.355210Z Closing Zeebe Partition 1. 
E 2021-05-03T00:01:54.357094Z ZeebePartition-1 failed, marking it as unhealthy 
```

It seems that the partition is not removed from the health monitor before it is closed.

**Expected behavior**

When the broker is being closed, all services are expected to be stopped. Hence they should not be marked as unhealthy.

**Environment:**
 - Zeebe Version:  1.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR introduces a new method `removeFailureListener` to the `HealthMonitorable` interface, and tries to ensure we always remove components/failure listeners from health monitors when the components are closed/discarded.

This also fixes the issue we had with ZeebePartition being marked as unhealthy when closing.

NOTE: there's still the issue of potential race condition, for example in ZeebePartition. See commit https://github.com/camunda-cloud/zeebe/commit/708a2897a47181e3231151570ae4dc0efca15dad for more. It's not ideal, and I'm happy to change this for something better :+1: 

## Related issues

closes #6938 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks. Small commits were really handy. :+1:

**Comment by npepinpe** [comment]
Thanks, sorry for all the tiny mistakes, I guess I was tired when I created this PR :s

**Comment by npepinpe** [comment]
I rebased, fixed conflicts, and applied your feedback. Sorry again for the silly mistakes :see_no_evil:

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
/backport

Backporting as it may cause conflicts in the future if we do more on the failure handling side (which I can imagine).

**Pull request merged**
