### PR TITLE
Refactor handle catch event migrations

### LINKED ISSUE #21924: Fix and refactor handle catch event migrations
## Description

During the implementation of https://github.com/camunda/camunda/issues/21862 we encountered with an issue where signal subscriptions with the same signal name cannot be re-subscribed (no mapping instruction provided for signal boundary event during the migration) within the same migration. Because in the state, we use `signal name` and `subscription key` (instance key of the element that the signal event belongs to) as the column key here:
https://github.com/camunda/camunda/blob/ebe00fc9390669a7d079d883b884dafe3a3eb315/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/signal/DbSignalSubscriptionState.java#L24-L69

In the migration processor, we first subscribe to events and then unsubscribe from them later. Since we run the subscribing first, when the signal name is the same, we override the existing signal subscription in the state which is a wrong behaviour. To fix this we can unsubscribe first and subscribe later.

As a part of this issue, we can do an overall refactoring for `handleCatchEvents()` method. The plan is to change the order of execution as follows:
1) Unsubscribe from process instance events that are not part of the provided mapping instruction
2) Subscribe to target process definition events that are not part of the provided mapping instruction
3) Migrate events that are provided in the mapping instruction

In that way, we do the separation by execution instead of per event type.

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

During the implementation of https://github.com/camunda/camunda/issues/21862 we encountered with an issue where signal subscriptions with the same signal name cannot be re-subscribed (no mapping instruction provided for signal boundary event during the migration) within the same migration. Because in the state, we use `signal name` and `subscription key` (instance key of the element that the signal event belongs to) as the column key here:
https://github.com/camunda/camunda/blob/ebe00fc9390669a7d079d883b884dafe3a3eb315/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/signal/DbSignalSubscriptionState.java#L24-L69

In the migration processor, we first subscribe to events and then unsubscribe from them later. Since we run the subscribing first, when the signal name is the same, we override the existing signal subscription in the state which is a wrong behaviour. To fix this we can unsubscribe first and subscribe later.

As a part of this issue, we can do an overall refactoring for `handleCatchEvents()` method. The plan is to change the order of execution as follows:
1) Unsubscribe from process instance events that are not part of the provided mapping instruction
2) Subscribe to target process definition events that are not part of the provided mapping instruction
3) Migrate events that are provided in the mapping instruction

In that way, we do the separation by execution instead of per event type.

## Related issues

closes #21924

### CODE REVIEW

**Comment by koevskinikola** [comment]
@berkaycanbc can you re-base the changes so it's easier to complete the review? There are also some merge conflicts since the initial PR has already been merged.

**Comment by berkaycanbc** [comment]
@koevskinikola resolved merge conflicts and rebased the branch ✅

**Review by koevskinikola — APPROVED** [review]
LGTM 👍

**Review by korthout — COMMENTED** [review]
Great job @berkaycanbc and @koevskinikola 👏 

👍 The refactoring greatly improved readability / understandability!

💭 I went back all the way to 96e1b895c043b4b6ffd9afaeb6638f1d9e57e664 to understand why we subscribed before unsubscribing. The reason was that we lacked information about which catch events to subscribe to after having unsubscribed from some. However, with the current solution this is covered quite elegantly:
- unsubscribe from all, except for those that are mapped and keep track of these to migrate later
- subscribe to all, except those that are mapped
- migrate the mapped ones that we tracked earlier

**Comment by berkaycanbc** [comment]
@korthout Additionally, after this refactoring and with the help of new feature [Optionally ordered command distribution](https://github.com/camunda/camunda/issues/21447) we can resolve the issue of re-subscribing to the same message name. Because we will be unsubscribing first and subscribing later to the same message name but this time one after another in the message subscription partition.

**Pull request merged**
