### PR TITLE
test: increase await assertion timeout in OpensearchExporterIT IndexSettingsTest to overcome flaky test runs

### LINKED ISSUE #17279: Flaky test `OpensearchExporterIT.shouldAddIndexLifecycleSettingsToExistingIndicesOnRerunWhenRetentionIsEnabled`
**Summary**

- How often does the test fail? [once](https://github.com/camunda/zeebe/actions/runs/8541686929/attempts/1#summary-23401588329)
- Does it block your work? no
- Do we suspect that it is a real failure? no, it's most probably due to the async nature of opensearch update policy functions

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
shouldAddIndexLifecycleSettingsToExistingIndicesOnRerunWhenRetentionIsEnabled (Flaky Test): io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest
org.awaitility.core.ConditionTimeoutException: 
Assertion condition defined as a Lambda expression in io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest [ISM policy should not be configured] 
Expecting an empty Optional but was containing value: IndexISMPolicyDto[policyId=zeebe-record-retention-policy] within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)
	at io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest.shouldAddIndexLifecycleSettingsToExistingIndicesOnRerunWhenRetentionIsEnabled(OpensearchExporterIT.java:299)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.AssertionError: [ISM policy should not be configured] 
Expecting an empty Optional but was containing value: IndexISMPolicyDto[policyId=zeebe-record-retention-policy]
	at io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest.assertHasNoISMPolicy(OpensearchExporterIT.java:428)
	at io.camunda.zeebe.exporter.opensearch.OpensearchExporterIT$IndexSettingsTest.lambda$shouldAddIndexLifecycleSettingsToExistingIndicesOnRerunWhenRetentionIsEnabled$0(OpensearchExporterIT.java:302)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details>

**Hypotheses**
it's most probably due to the async nature of opensearch update policy functions

**Logs**

https://productionresultssa7.blob.core.windows.net/actions-results/47e02c5d-1cf1-4033-adbb-3610e895ac89/workflow-job-run-65e11684-88a0-5014-4a3a-b5bb082dc98b/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-03T16%3A57%3A18Z&sig=QnN0pMP9k0QxAZyYQQZm2GnO7nLdjFvNE3nbQFVe%2BSw%3D&sp=r&spr=https&sr=b&st=2024-04-03T16%3A47%3A13Z&sv=2021-12-02
<details><summary>Logs</summary>
<pre>
LOGS
</pre>
</details>

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description
Increase await assertion timeout to overcome flaky test runs

Policy change is an asynchronous background process in opensearch, that's why we use awaits before asserts to reduce flaky results

## Related issues

closes #17279

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by megglos — APPROVED** [review]
👍

**Comment by mustafadagher** [comment]
While policy change is indeed asynchronous, and this change is trying to increase the timeout to avoid flakiness in test runs. this specific failure here, and the one that triggered that PR should never have happened.

It's failing at [this line](https://github.com/camunda/zeebe/blob/3b99b74d2390630c9b7aa8807065fd5f3bda4502/zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchExporterIT.java#L299), in the beginning of the test.
At this point above we are trying to create an index with `retention` initially **NOT** enabled. This assert is just making sure that this index has no lifecycle policy. which should always be the case. we are not adding or removing a policy at this point, so waiting can't help this failure.

I've been trying to reproduce this locally to see what might have been the problem, but unfortunately, I can't. it never fails locally!

CC: @megglos

**Comment by megglos** [comment]
> While policy change is indeed asynchronous, and this change is trying to increase the timeout to avoid flakiness in test runs. this specific failure here, and the one that triggered that PR should never have happened.
> 
> It's failing at [this line](https://github.com/camunda/zeebe/blob/3b99b74d2390630c9b7aa8807065fd5f3bda4502/zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchExporterIT.java#L299), in the beginning of the test. At this point above we are trying to create an index with `retention` initially **NOT** enabled. This assert is just making sure that this index has no lifecycle policy. which should always be the case. we are not adding or removing a policy at this point, so waiting can't help this failure.
> 
> I've been trying to reproduce this locally to see what might have been the problem, but unfortunately, I can't. it never fails locally!
> 
> CC: @megglos

hmm could it be that there are template leftovers from a previous test? meaning maybe we need to extend the cleanup to not just cleanup indices but also potentially existing templates

**Comment by mustafadagher** [comment]
> > While policy change is indeed asynchronous, and this change is trying to increase the timeout to avoid flakiness in test runs. this specific failure here, and the one that triggered that PR should never have happened.
> > It's failing at [this line](https://github.com/camunda/zeebe/blob/3b99b74d2390630c9b7aa8807065fd5f3bda4502/zeebe/exporters/opensearch-exporter/src/test/java/io/camunda/zeebe/exporter/opensearch/OpensearchExporterIT.java#L299), in the beginning of the test. At this point above we are trying to create an index with `retention` initially **NOT** enabled. This assert is just making sure that this index has no lifecycle policy. which should always be the case. we are not adding or removing a policy at this point, so waiting can't help this failure.
> > I've been trying to reproduce this locally to see what might have been the problem, but unfortunately, I can't. it never fails locally!
> > CC: @megglos
> 
> hmm could it be that there are template leftovers from a previous test? meaning maybe we need to extend the cleanup to not just cleanup indices but also potentially existing templates
> 
> Edit: however that should be overridden by the previous export

I made one try at expanding wildcards to all (open and closed) indices when deleting indices before each test. I'm not sure this is the problem though. it's just a guess.

This is also one other API where opensearch diverges from elasticsearch.

**Comment by mustafadagher** [comment]
should this be backported to 8.4, 8.5 too?
I don't see the need, except for consistency.

**Pull request merged**
