### PR TITLE
feat: gracefully shut down gRPC server

### LINKED ISSUE #16024: Respect quiet period before shutting down the gateway
**Description**

At the moment, the gateway will shutdown immediately when it receives a SIGTERM. This doesn't allow for graceful handling of client connections, often resulting in 502s if a load balancer is set up in front of the gateway.

We should instead respect a configurable quiet period when we receive a SIGTERM, and refusing new connections but giving a timeout for on-going ones to finish, before shutting down.

**Related**
[SUPPORT-20158](https://jira.camunda.com/browse/SUPPORT-20158)
[SUPPORT-20232](https://jira.camunda.com/browse/SUPPORT-20232)

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Uses the spring property `spring.lifecycle.timeout-per-shutdown-phase` to determine a timeout for graceful shutdown of the gRPC server in the gateway.
If the server can't be closed within this timeout, for example because there are open job streams, the server is closed forcefully instead, falling back to the old behavior.

closes #16024

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:rocket: 

This definitely fixes the issue we had in SaaS, but I'm wondering what's the behavior with embedded gateways? So if the gateway is accessing a different broker, then that should be fine, as that broker will shutdown and we'll detect it and close the request. But if it's an embedded gateway connecting to itself, it would just...hang until the request timeout? :thinking: I'm not 100% sure though, did you try it?

Still a marked improvement on current behavior!

:question: Also was wondering this timeout per phase...do you know how many phases we have at all? :thinking: What will be the real timeout in the end?

**Comment by oleschoenburg** [comment]
Embedded gateways are a bit weird now. On shutdown, the embedded gateway service is stopped after all of the partitions have already stopped. If the gateway was handling a user request or holding a job stream for a partition that the broker was leader for, then it can't respond with _new_ data because the partition is already shut down.
However, it's still useful for two cases: First it can still respond with existing data, for example when the client connection is especially slow or things get retried. Second it is still useful when the gateway is handling requests for remote partitions.

> ❓ Also was wondering this timeout per phase...do you know how many phases we have at all? 🤔 What will be the real timeout in the end?

I don't know how many phases there are. If I understand correctly, the way I've used this now is cheating a bit because the graceful shutdown is not managed by Spring. So there is no associated "phase" and Spring does not enforce this timeout.
I think the only place where we really use Spring's graceful shutdown is for the management and now REST API servers.

**Comment by megglos** [comment]
@oleschoenburg @npepinpe  in the issue[ it was mentioned this is planned to get backported to 8.4](https://github.com/camunda/zeebe/issues/16024#issuecomment-1914481178) did we decide against that?

**Comment by oleschoenburg** [comment]
Good catch, I just missed that. Let's try backporting then.

**Pull request merged**
