### PR TITLE
refactor: remove zbctl from Docker image

### LINKED ISSUE #13024: Remove zbctl from 8.3 images going forward
**Is your feature request related to a problem? Please describe.**
Many of the recently reported [CVEs](https://github.com/camunda/zeebe/issues/12649) were related to the `zbctl` in the docker image, which only used in debugging and troubleshooting of SaaS clusters.

**Describe the solution you'd like**
Remove `zbctl` from the docker images from 8.3 going forward. This would eliminate any CVEs reported on our docker images that are golang related.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR removes `zbctl` and its variants from the Docker image. This drastically reduce the image size, and also reduces the maintenance effort w.r.t to CVEs for our container images.

## Related issues

closes #13024 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
As per the issue, we're not back porting this.

**Comment by npepinpe** [comment]
Doing a `dive` of the image built:

image

**Comment by npepinpe** [comment]
Hm, I think we can probably skip building the Go client from now on in some of the Java only stages.

**Comment by npepinpe** [comment]
I guess we missed the alpha3 mark :)

**Review by megglos — APPROVED** [review]
LGTM! //CC @abbasadel

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
