### PR TITLE
fix(gateway): serialize access to StreamObserver

### LINKED ISSUE #14236: Prevent concurrent StreamObserver calls on the same instance
**Describe the bug**

When calling any of the `StreamObserver` methods (including `#onNext`) concurrently, the underlying stream will send garbled messages, and you end up with errors like 

```
java.lang.IllegalStateException: sendHeaders has already been called 
```

Or 

```
io.grpc.StatusRuntimeException: INTERNAL: Connection closed after GOAWAY. HTTP/2 error code: INTERNAL_ERROR, debug data: Stream 7 sent too many headers EOS: false
```

Reading the documentation, it's quite clearly stated in `StreamObserver.java`:

> Separate StreamObservers do not need to be synchronized together; incoming and outgoing directions are independent. Since individual StreamObservers are not thread-safe, if multiple threads will be writing to a StreamObserver concurrently, the application must synchronize calls.

In the `ClientStreamAdapter`, we call `onNext` using a thread pool executor, so concurrent calls are possible.

**To Reproduce**

Easily reproducible with [Camunda 8 Benchmark](https://github.com/camunda-community-hub/camunda-8-benchmark), since there we have a single client, so it's more likely for us to receive all the jobs.

**Expected behavior**

Calls to a `StreamObserver` are serialized. Either all consumers become an actor (what is the overhead there?), or we use gRPC's `SerializingExecutor` to wrap around our thread pool.

**Environment:**
- Zeebe Version: 8.3.0-alpha5, 8.3.0-alpha6

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes concurrent access to the same stream observer which results in broken streams. However, it uses an internal gRPC API which is likely to be made inaccessible in the future.

## Related issues

related to #14236 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
The idea is to merge this as a quick fix to unblock, and then work on a proper fix with more time.

**Review by ChrisKujawa — COMMENTED** [review]
:question: Does this mean we might have here now a performance issue? Sorry, I just reviewed via phone. Does this executor uses only one thread now?

**Comment by npepinpe** [comment]
You can review it Monday :smile: 

`SerializingExecutor` isn't a thread, it's just a queue which serializes a series of operations to some other executor. So the other executor is untouched and still does it's things in parallel, but any task submitted to the same `SerializingExecutor` instance is serialized.

**Comment by Zelldon** [comment]
Ah, now I see it. It is wrapping the other👌

**Review by ChrisKujawa — APPROVED** [review]
Thanks 👍🏼 Interesting class wasn't aware of https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/SerializingExecutor.java

**Comment by npepinpe** [comment]
It's not part of the public API, so long term we shouldn't rely on it, but it's an easy interim solution until we get something in (which is why this PR won't close the issue :smile:)

bors merge

**Pull request merged**
