### PR TITLE
Ignore netty-handler SNI vulnerability

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This also ignores netty-handler's disabled SNI by default. This is not of particular concern to us because SNI is in fact enabled. And even when disabled, we only serve a single virtual host per port - i.e. we only server one certificate per port - so there would be no possible confusion about serving the wrong certificate.

In the future, new global ignores can be added to the `.snyk` file. This is will also allow us to document our decisions to ignore certain vulnerabilities.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
:wrench: It'd be great to not add another top-level dotfile. It seems to be possible to move the .snyk file to another location, at least if snyk is called via the cli: https://github.com/keycloak/keycloak/blob/main/.github/snyk/.snyk https://github.com/keycloak/keycloak/blob/b356618cc2e00ef3ae37f515c1d4b3bdbcde3f62/.github/workflows/snyk.yml#L29

:wrench: Could you link to the relevant code where we enable hostname verification?

**Comment by npepinpe** [comment]
I thought it had to be at the root level for the GitHub integration (which is how we import our projects), but looking at the docs, I don't think it actually uses the policy file :disappointed: 

So I guess we can close this for now and keep using the UI. Or we can merge to try it, maybe it does work and I misunderstood the docs :thinking:

**Comment by npepinpe** [comment]
OK, it might work with GitHub, but then how would it pick up the file if it's in a different location? :thinking: And since it thinks we have different projects, do we need it in all these projects? :thinking:

**Comment by npepinpe** [comment]
Let's close this for now. I think we'll have more flexibility using GitHub actions, actually, to integrate Snyk, then using the built-in GitHub integration.

**Pull request closed without merging**
