### PR TITLE
[Backport stable/8.1] refactor(msgpack): require a hint for the number of declared properties

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Manual backport of https://github.com/camunda/zeebe/pull/15518.

Size hints needed to be adjusted.

### CODE REVIEW

**Review by lenaschoenburg — COMMENTED** [review]
Reviewed and adjusted size hints where records have different properties compared to main.

**Review by koevskinikola — APPROVED** [review]
LGTM :+1: 

bors merge

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
