### PR TITLE
fix(client): ensure that commands have not null response

### LINKED ISSUE #7630: Java client is returning null instead of empty objects
**Describe the bug**

We have several commands which should return an empty response like:

 * Fail job
 * Complete job
 * Cancel instance
 * Resolve incident 
 * etc. 
 
But instead of returning an object (which would be expected, since it is part of the interface) it is returning null.

The following fails:
```java
val failResponse = zeebeClient.newFailCommand(job.key)
            .retries(0)
            .errorMessage("This failed oops.")
            .send()
            .join()

assertThat(failResponse).isNotNull // fails
```

In C# we return an empty object instead, https://github.com/camunda-community-hub/zeebe-client-csharp/blob/master/Client/Impl/Commands/CompleteJobCommand.cs#L53

**To Reproduce**

The problem is in the `RetriableClientFutureImpl`, if there is no response mapper given then it will return null.

**Expected behavior**

An empty object and not null. 

**Environment:**
 - OS: all
 - Zeebe Version: 1.0.0+ 
 - Configuration: all

### PR DESCRIPTION
**Pull request by alexanderavdeev14**
## Description

Several commands in package `io.camunda.zeebe.client.api.command`  gave response of null when used with `.send().join()`. This was happening because some of the commands did not specified responseMapper while creating an instance of `io.camunda.zeebe.client.impl.RetriableClientFutureImpl`. These commands objects used the following overloaded constructor: 
```java 
public RetriableClientFutureImpl(
      final Predicate<Throwable> retryPredicate, final Consumer<StreamObserver<T>> retryAction) {
    this(brokerResponse -> null, retryPredicate, retryAction);
  }
```
This defines the responseMapper as having response of null. Obviously to fix the issue the commands need specify the exact response object. To do so I used the pattern that is applied in `io.camunda.zeebe.client.impl.command.CreateProcessInstanceCommandImpl`. 

The following steps I took to fix the issue for fail job command: 

1. Implement the response interface of a command
2. Create a constructor that has as input parameter the appropriate response class from `io.camunda.zeebe.gateway.protocol.GatewayOuterClass`.

```java
public class FailJobResponseImpl implements FailJobResponse {

  public FailJobResponseImpl(final GatewayOuterClass.FailJobResponse response) {}
}
```

3. Create future with responseMapper included
```java
 new RetriableClientFutureImpl<>(
                FailJobResponseImpl::new,
                retryPredicate,
                streamObserver -> send(request, streamObserver));
```

4. Write a unit test
```java
  @Test
  public void shouldNotHaveNullResponse() {
    // given
    final FailJobCommandStep1 command = client.newFailCommand(12);

    // when
    final FailJobResponse response =
        command.retries(0).errorMessage("This failed oops.").send().join();

    // then
    assertThat(response).isNotNull();
  }
```

I applied the same steps to the following commands classes in package `io.camunda.zeebe.client.impl.command`: 

- `CancelProcessInstanceCommandImpl`
- `CompleteJobCommandImpl`
- `FailJobCommandImpl`
- `JobUpdateRetriesCommandImpl`
- `ResolveIncidentCommandImpl`

I also saw that ThrowErrorCommandImpl do not specifies the responseMapper. But I cloud not find any response interface for the thorw error command. So I assumed that it is how it was intended. 

## Related issues

closes #7630 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [] The changes are backwards compatibility with previous versions **(Note: the reason to leave this unchecked is that users could potentially handle null responses)**
* [] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x ] There are unit/integration tests that verify all acceptance criterias of the issue
* [x ] New tests are written to ensure backwards compatibility with further versions
* [x ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
@Zelldon let me know if you don't have time for this

**Comment by Zelldon** [comment]
Yeah sorry @npepinpe  but I currently feel I have too much on my plate

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]
🚀 Thanks a lot for your contribution @alexanderavdeev14! You code looks fine there are however a few issues that need to be resolved before I can merge this. Please have a look at these.

1. We had some issue with our CLA bot. I think you signed the CLA before, unfortunately this seems to be lost. Please re-sign our CLA. You can do this here: https://cla-assistant.io/camunda-cloud/zeebe?pullRequest=8100
2. There were 3 checkstyle violations. Please fix these, you can verify your code against the checkstyle locally by running `mvn validate`.
```
[2021-11-08T08:54:36.528Z] [ERROR] src/test/java/io/camunda/zeebe/client/job/JobUpdateRetriesTest.java:[22,1] (imports) CustomImportOrder: Wrong lexicographical order for 'io.camunda.zeebe.client.api.response.ActivatedJob' import. Should be before 'io.camunda.zeebe.client.api.response.UpdateRetriesJobResponse'.
[2021-11-08T08:54:36.528Z] [ERROR] src/test/java/io/camunda/zeebe/client/job/CompleteJobTest.java:[21,1] (imports) CustomImportOrder: Wrong lexicographical order for 'io.camunda.zeebe.client.api.command.CompleteJobCommandStep1' import. Should be before 'io.camunda.zeebe.client.api.response.ActivatedJob'.
[2021-11-08T08:54:36.528Z] [ERROR] src/test/java/io/camunda/zeebe/client/job/FailJobTest.java:[22,1] (imports) CustomImportOrder: Wrong lexicographical order for 'io.camunda.zeebe.client.api.response.ActivatedJob' import. Should be before 'io.camunda.zeebe.client.api.response.FailJobResponse'.
```

**Comment by alexanderavdeev14** [comment]
Thank you very much for your review. @remcowesterhoud. No worries I just signed the CLA again. And I have rearranged the order of import statements such that it now passes `mvn validate`.

**Review by remcowesterhoud — APPROVED** [review]
Thank you for your changes!

**Comment by remcowesterhoud** [comment]
bors merge

**Pull request merged**
