### PR TITLE
Remove deferred records functionality

### LINKED ISSUE #6832: Remove deferred records functionality
**Description**

Deferred records is a legacy functionality used by the engine before event sourcing was fully implemented as proposed by [ZEP004-wf-stream-processing](https://github.com/zeebe-io/enhancements/blob/master/ZEP004-wf-stream-processing.md). It seems to no longer have a place in the engine and we should consider whether it can be removed.

### PR DESCRIPTION
**Pull request by pihme**
## Description

Removes `StoredRecord` and associated code and tests

## Related issues

closes #6832

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
:tada:

**Comment by Zelldon** [comment]
Just to get us all on the same page: For these kind of clean up I would use the `refactor` commit message title. Don't want to be nit picky just would like to have a consistent approach. I'm fine if we decided for cleanup instead of refactor. Refactor is mentioned here https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type which is why I use it normally. Any opinion thoughts  ? Maybe @korthout ?

**Comment by pihme** [comment]
Personally, I feel that refactoring doesn't quite cover it. I would like to have a category like "cleanup" for code removal and stuff like this. However, I don't want it so much to enter a serious discussion to defend it. So I am fine with refactor as well.

**Pull request merged**
