### PR TITLE
test: increment time continuously

### LINKED ISSUE #8475: Flaky test ExporterDirectorDistributionTest.shouldDistributeExporterPositions
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? I saw it now, I haven't seen it before, but I did not dig into the history to find out.
- Does it block your work? I had to tell bors to merge again
- Do we suspect that it is a real failure? I don't understand the stacktrace. It says that line 97 in the `ExporterDirectorDistributionTest` called `Constructor.newInstanceWithCaller(Constructor.java:499)`, but  [ExporterDirectorDistributionTest.java#L97](https://github.com/camunda-cloud/zeebe/blob/korthout-recreate-benchmark/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorDistributionTest.java#L97)
 is `assertThat(activeExporterState.getPosition(EXPORTER_ID_1)).isEqualTo(position);`

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>

[link to logs](https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1566/pipeline)

<pre>
[2021-12-24T09:27:11.162Z] [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.711 s <<< FAILURE! - in io.camunda.zeebe.broker.exporter.stream.ExporterDirectorDistributionTest
[2021-12-24T09:27:11.162Z] [ERROR] io.camunda.zeebe.broker.exporter.stream.ExporterDirectorDistributionTest.shouldDistributeExporterPositions  Time elapsed: 1.826 s  <<< FAILURE!
[2021-12-24T09:27:11.162Z] org.opentest4j.AssertionFailedError: 
[2021-12-24T09:27:11.162Z] 
[2021-12-24T09:27:11.162Z] expected: 1L
[2021-12-24T09:27:11.162Z]  but was: -1L
[2021-12-24T09:27:11.162Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-24T09:27:11.162Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2021-12-24T09:27:11.162Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-24T09:27:11.162Z] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2021-12-24T09:27:11.162Z] 	at io.camunda.zeebe.broker.exporter.stream.ExporterDirectorDistributionTest.shouldDistributeExporterPositions(ExporterDirectorDistributionTest.java:97)
[2021-12-24T09:27:11.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2021-12-24T09:27:11.162Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2021-12-24T09:27:11.162Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2021-12-24T09:27:11.162Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[2021-12-24T09:27:11.162Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[2021-12-24T09:27:11.162Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[2021-12-24T09:27:11.162Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[2021-12-24T09:27:11.162Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[2021-12-24T09:27:11.162Z] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[2021-12-24T09:27:11.162Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[2021-12-24T09:27:11.162Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
[2021-12-24T09:27:11.162Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
[2021-12-24T09:27:11.162Z] 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
[2021-12-24T09:27:11.162Z] 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
[2021-12-24T09:27:11.162Z] 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
[2021-12-24T09:27:11.163Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
[2021-12-24T09:27:11.163Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
[2021-12-24T09:27:11.163Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
[2021-12-24T09:27:11.163Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
[2021-12-24T09:27:11.163Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
[2021-12-24T09:27:11.163Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
[2021-12-24T09:27:11.163Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
[2021-12-24T09:27:11.163Z] 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
[2021-12-24T09:27:11.163Z] 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
[2021-12-24T09:27:11.163Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.lambda$execute$1(JUnitPlatformProvider.java:199)
[2021-12-24T09:27:11.163Z] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[2021-12-24T09:27:11.163Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:193)
[2021-12-24T09:27:11.163Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
[2021-12-24T09:27:11.163Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)
[2021-12-24T09:27:11.163Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
[2021-12-24T09:27:11.163Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
[2021-12-24T09:27:11.163Z] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
[2021-12-24T09:27:11.163Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
</pre>
</details>

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

In order to prevent for flakiness the time needs to be increased
everytime so we can retrigger the position distribution.

## Related issues

closes #8475 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
:rocket: 
I don't understand why the event is not received with the first clock increment though.

**Comment by Zelldon** [comment]
Thanks @deepthidevaki I think this is a good point I can take a deeper look again.

**Comment by Zelldon** [comment]
Hey @deepthidevaki I had a deeper look and I think I can explain it.

In our test we [start the exporters](https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorDistributionTest.java#L88) and [await the future](https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterRule.java#L108). The future we await is returned from submitting the Actor, https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java#L107. Here it becomes interesting. 

Taking a look at the actor scheduler, we can see that the future is complete after the starting phase is complete, which means `#onActorStarting` was called https://github.com/camunda-cloud/zeebe/blob/develop/util/src/main/java/io/camunda/zeebe/util/sched/ActorTask.java#L176

I was able to reproduce this via unit tests:

```java
  @Test
  public void shouldCompleteFutureBeforeStartedComplete() {
    // given
    final CountDownLatch latch = new CountDownLatch(1);
    final var scheduler = ActorScheduler.newActorScheduler().build();

    scheduler.start();

    // when
    final ActorFuture<Void> startedFuture =
        scheduler.submitActor(
            new Actor() {
              @Override
              protected void onActorStarted() {
                try {
                  latch.await();
                } catch (final InterruptedException e) {
                  e.printStackTrace();
                }
              }
            });

    // then
    startedFuture.join();
    assertThat(startedFuture).isDone();
    assertThat(latch.getCount()).isEqualTo(1);
  }
```

This test completes without issues.

The following test will never complete:

```java
  @Test
  public void shouldCompleteFutureBeforeStartingComplete() {
    // given
    final CountDownLatch latch = new CountDownLatch(1);
    final var scheduler = ActorScheduler.newActorScheduler().build();

    scheduler.start();

    // when
    final ActorFuture<Void> startedFuture =
        scheduler.submitActor(
            new Actor() {
              @Override
              protected void onActorStarting() {
                try {
                  latch.await();
                } catch (final InterruptedException e) {
                  e.printStackTrace();
                }
              }
            });

    // then
    startedFuture.join();
    assertThat(startedFuture).isDone();
    assertThat(latch.getCount()).isEqualTo(1);
  }
```

So to conclude we already complete the future after the starting phase, after that we [wait that the active exporter is in the exporting phase](https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorDistributionTest.java#L122-L126), but this doesn't mean that the passive exporter has completely set up. This means in our test we already [increment the time](https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/test/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirectorDistributionTest.java#L132), but the passive exporter [might not subscribed yet for the event (this happens in the #onActorStarted)](https://github.com/camunda-cloud/zeebe/blob/develop/broker/src/main/java/io/camunda/zeebe/broker/exporter/stream/ExporterDirector.java#L201) .

**Comment by deepthidevaki** [comment]
Got it! Thanks for looking into it :+1:

**Comment by npepinpe** [comment]
BTW great catch :muscle:

**Pull request merged**
