### PR TITLE
Use ManagedVolume instead of raw volume

### LINKED ISSUE #5847: Use ManagedVolume in DiskSpaceRecoveryITTest
**Description**

We should use ManagedVolume in the DiskSpaceRecoveryITTest to avoid having dangling volumes in case the JVM crashes. While these are tmpfs mounts and not persisted if the host restart, if the JVM crashes they are still dangling and may eat up the memory of the host. This is however only really a problem with repeated crashes on a local machine, and not really an issue in CI where our builds run on ephemeral nodes.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR replaces the Docker volume for a `ManagedVolume` which ensures no dangling volumes are left, and also cleans up the test a bit.

## Related issues

closes #5847 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
I mostly cleaned it up because I didn't understand it initially - if it's not more readable now feel free to reject those changes.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Looks good. But I think you also have to close the volume explicitly. When I ran the test locally, the volume created by it is still there after the test is completed.

**Comment by npepinpe** [comment]
Yes, it's still there, but the Ryuk container will reap it after a few seconds. The reason I can't close the volume is because it's still attached to the container; when closing the container, the command returns when it's stopped but not 100% guaranteed when it's really removed, so I don't have an accurate way to know when I can remove the volume.

At least this is what I saw when I tried it, but I can play around for 10-15 min, see if I can't figure out a way to do it

**Comment by npepinpe** [comment]
Well, not sure how I didn't get it to work initially, it just worked now, so... :man_shrugging: (and I did verify it doesn't throw anything, even if you don't close quietly...go figure)

**Review by deepthidevaki — APPROVED** [review]
Thanks.

**Pull request merged**
