### PR TITLE
chore(atomix): rm partition membership service

### LINKED ISSUE #4738: Remove PartitionMembershipService
**Description**

The partition membership service was used in atomix to detect configured partition groups, such that a new node can be part of this partition group. This is no longer used on our side, since we have static configuration furthermore it means that on the Gateway it always prints an error log.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
 @deepthidevaki as discussed

 PartitionGroupMembershipService was only used to detect new or other
 partition groups and to join them. This is no longer necessary since we
 use a static configuration.

## Related issues

closes #4738 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
LGTM. :+1: Two tests are failing which expects partition membership service.

**Comment by Zelldon** [comment]
@deepthidevaki thanks. I updated the PR and remove some more code.

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Pull request merged**
