### PR TITLE
Store commit index in meta store

### LINKED ISSUE #13790: Store commit index in raft MetaStore
Currently, on restart a partition's commitIndex is initialized to 0. This is perfectly fine, as we can reliably re-built the latest commitIndex from the quorum. 

In practice though, there can be disaster scenarios where data loss occur in one or more replica. In this cases there are chances that the replicas with data loss forms a quorum and overwrites data in the replica that actually has the correct latest data. We cannot 100% prevent data corruption or loss in case quorum of nodes lose their data. But we might be able to detect or prevent some inconsistencies.

The goal is to persist commitIndex in MetaStore. On restart a replica initialize commitIndex from the MetaStore. If the replicas with data loss forms a quorum, then the node with the latest committed data can detect this when it tries to overwrite its entries by the entries received from the new leader. This will still require manual intervention to recover, and might still result in some data loss. However, it is better than the current scenario, where we silently overwrite correct data.

Caveats: Writing commitIndex to MetaStore can add more I/O. Delayed and less frequent flushing would be acceptable in this case.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR enables storing and restoring the last known commit index in the Raft meta store. To avoid a I/O performance hit, we now explicitly flush the meta store where appropriate instead of writing it using `DSYNC`. In that sense, we don't explicitly flush the commit index update in the meta store, though it will get flushed by the OS or when the `lastFlushedIndex` is updated.

> **Note**
> I did not check if it's really required to flush when setting the term or vote, but kept the existing behavior as is. We can assess that here as well if you'd like, but setting the term/vote is not really in the hot path, so I didn't think it was critical.

No integrity improvements were done, as it's slightly outside of scope - we still don't do checksum verification or the likes on the meta store, and we can always restore from no meta store of course.

## Related issues

closes #13790 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
On hold until https://github.com/camunda/zeebe/issues/14699 is fixed

**Comment by deepthidevaki** [comment]
> I did not check if it's really required to flush when setting the term or vote, but kept the existing behavior as is.

It is necessary to flush the vote. I'm not sure about the term, but I would say that also. After a restart, if the term in the metastore and the term in the log does not match it would be a problem.

**Comment by npepinpe** [comment]
I'll keep the same behavior :+1:

**Comment by npepinpe** [comment]
Let's review tomorrow. This is mostly ready, but it has a few downsides:

1. Right now, we only detect inconsistencies if committed entries have a different term. Furthermore, we assume that if a node sends us an append request with `prevLogTerm == 0`, that this is the beginning of the log, so we just reset our log happily without checking the commit index :upside_down_face:
2. Flushing the meta store is now asynchronous. This means instead of detecting errors on write (due to `O_DATASYNC`), we detect errors on flush, and can't easily retry. Not that we retry meta store write errors anyway already, so... :shrug: 

I also had to fiddle a bit with the start/is-ready behavior, since it relies on commit listeners, but if you initialize the commit index to a higher index, then no listeners are ever called :smile:

**Comment by npepinpe** [comment]
Closing, it's too out of date at this point

**Pull request closed without merging**
