### PR TITLE
Wait for deployment distribution to prevent rejection

### PR DESCRIPTION
**Pull request by menski**
- sometimes test fail with a command rejection because the workflow is not
  deployed on all partitions

### CODE REVIEW

**Comment by menski** [comment]
This should prevent failures like 

```
Error
expected:<[EVENT]> but was:<[COMMAND_REJECTION]>

Stacktrace
org.junit.ComparisonFailure: expected:<[EVENT]> but was:<[COMMAND_REJECTION]>
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at io.zeebe.test.broker.protocol.clientapi.PartitionTestClient.createWorkflowInstance(PartitionTestClient.java:192)
at io.zeebe.test.broker.protocol.clientapi.PartitionTestClient.createWorkflowInstance(PartitionTestClient.java:183)
at io.zeebe.test.broker.protocol.clientapi.PartitionTestClient.createJob(PartitionTestClient.java:264)
at io.zeebe.test.broker.protocol.clientapi.PartitionTestClient.createJob(PartitionTestClient.java:247)
at io.zeebe.broker.exporter.ExporterManagerPartitionTest.createJob(ExporterManagerPartitionTest.java:77)
at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:559)
at io.zeebe.broker.exporter.ExporterManagerPartitionTest.shouldRunExporterForEveryPartition(ExporterManagerPartitionTest.java:62)

Log
12:43:48.705 [exporter] [0.0.0.0:40702-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter.test-exporter - {"key":-1,"position":4294967296,"timestamp":"2019-06-05T12:43:48.690Z","producerId":-1,"sourceRecordPosition":-1,"metadata":{"valueType":"WORKFLOW_INSTANCE_CREATION","intent":"CREATE","recordType":"COMMAND","partitionId":2,"rejectionType":"NULL_VAL","rejectionReason":""},"value":{"bpmnProcessId":"process","version":-1,"key":-1,"instanceKey":-1,"variables":{}}}
12:43:48.705 [exporter] [0.0.0.0:40702-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter.test-exporter - {"key":-1,"position":4294967448,"timestamp":"2019-06-05T12:43:48.698Z","producerId":2,"sourceRecordPosition":4294967296,"metadata":{"valueType":"WORKFLOW_INSTANCE_CREATION","intent":"CREATE","recordType":"COMMAND_REJECTION","partitionId":2,"rejectionType":"NOT_FOUND","rejectionReason":"Expected to find workflow definition with process ID 'process', but none found"},"value":{"bpmnProcessId":"process","version":-1,"key":-1,"instanceKey":-1,"variables":{}}}
```

**Review by miguelpires — APPROVED** [review]
bors r+

**Comment by menski** [comment]
it seems that this breaks the exporter manager test, I will fix it

**Comment by menski** [comment]
LOL https://github.com/zeebe-io/zeebe/blob/0e2a25870236859bfb3ef8046218a319ff9ba928/broker-core/src/test/java/io/zeebe/broker/exporter/ExporterManagerTest.java#L57

We override our recording exporter, makes sense that it does not work :woman_facepalming:

**Pull request merged**
