### PR TITLE
Refactors the DefaultClusterMembershipService tests and fixes flakiness

### LINKED ISSUE #7176: DefaultClusterMembershipServiceTest#testClusterService is flaky
**Summary**

- How often does the test fail? twice
- Does it block your work? no
- Do we suspect that it is a real failure? doubtful

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.lang.AssertionError: expected:<4> but was:<3>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at io.atomix.cluster.impl.DefaultClusterMembershipServiceTest.testClusterService(DefaultClusterMembershipServiceTest.java:185)
</pre>
</details>

**Logs**

<details><summary>Logs</summary>
<pre>
Standard Output
07:14:33.474 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
07:14:33.475 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Member activated: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:33.477 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
07:14:33.477 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
07:14:33.478 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
07:14:33.478 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Member activated: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:33.478 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
07:14:33.478 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
07:14:33.478 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
07:14:33.479 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Member activated: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:33.479 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
07:14:33.479 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
07:14:33.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=1, address=localhost:1, properties={}}
07:14:33.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=1, address=localhost:1, properties={}}
07:14:33.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=2, address=localhost:2, properties={}}
07:14:33.486 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=2, address=localhost:2, properties={}}
07:14:33.487 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=3, address=localhost:3, properties={}}
07:14:33.488 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=3, address=localhost:3, properties={}}
07:14:33.518 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:33.518 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:33.518 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:33.556 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:33.556 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:33.556 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:34.477 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:34.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:34.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:34.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:34.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:34.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:34.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:34.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:34.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:34.481 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:34.481 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:34.481 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:35.477 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:35.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:35.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:35.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:35.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:35.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:35.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:35.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:35.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:35.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:35.481 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:35.481 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:36.477 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:36.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:36.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:36.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:36.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:36.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:36.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:36.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:36.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:36.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:36.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:36.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:37.477 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:37.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:37.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:37.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:37.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:37.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:37.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:37.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:37.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:37.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:37.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:37.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:38.477 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:38.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:38.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:38.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:38.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:38.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:38.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:38.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:38.481 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:38.481 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:38.482 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:38.482 [] INFO  io.atomix.cluster.discovery.BootstrapDiscoveryProvider - Joined
07:14:38.482 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Member activated: Member{id=4, address=localhost:4, host=localhost, properties={}}
07:14:38.482 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:38.483 [] INFO  io.atomix.cluster.protocol.HeartbeatMembershipProtocol - Started
07:14:38.483 [] INFO  io.atomix.cluster.impl.DefaultClusterMembershipService - Started
07:14:38.483 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Sending heartbeat: Member{id=1, address=localhost:1, properties={}}
07:14:38.484 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Sending heartbeat: Member{id=2, address=localhost:2, properties={}}
07:14:38.484 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Sending heartbeat: Member{id=3, address=localhost:3, properties={}}
07:14:38.484 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=4, address=localhost:4, host=localhost, properties={}}
07:14:38.484 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=4, address=localhost:4, host=localhost, properties={}}
07:14:38.484 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=4, address=localhost:4, host=localhost, properties={}}
07:14:39.477 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:39.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:39.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Sending heartbeat: Member{id=4, address=localhost:4, host=localhost, properties={}}
07:14:39.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:39.478 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:39.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Received heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:39.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:39.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:39.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:39.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Sending heartbeat: Member{id=4, address=localhost:4, host=localhost, properties={}}
07:14:39.479 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:39.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Sending heartbeat: Member{id=4, address=localhost:4, host=localhost, properties={}}
07:14:39.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:39.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:39.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:39.480 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:39.481 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:39.483 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Received heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:39.485 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Sending heartbeat: Member{id=1, address=localhost:1, host=localhost, properties={}}
07:14:39.485 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Sending heartbeat: Member{id=2, address=localhost:2, host=localhost, properties={}}
07:14:39.485 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 4 - Sending heartbeat: Member{id=3, address=localhost:3, host=localhost, properties={}}
07:14:39.485 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 1 - Received heartbeat: Member{id=4, address=localhost:4, host=localhost, properties={}}
07:14:39.485 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 2 - Received heartbeat: Member{id=4, address=localhost:4, host=localhost, properties={}}
07:14:39.487 [] TRACE io.atomix.cluster.protocol.HeartbeatMembershipProtocol - 3 - Received heartbeat: Member{id=4, address=localhost:4, host=localhost, properties={}}
</pre>
</details>

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR's primary goal is to refactor the `DefaultClusterMembershipServiceTest`, and actually test that class and not indirectly the `HeartbeatGroupMembershipProtocol` class. Previously, it was mostly testing that behavior - this is not only already tested, but it's not even used in production with Zeebe.

Instead, we now test the class behavior, which is:

- Glue together the discovery protocol and the group membership protocol
- Report members accurately from these
- Keep track of its local member's reachability status
- Manage the lifecycle of the discovery service
- Listen to and forward group membership events

To do this, a new stub implementation of the `GroupMembershipProtocol` was introduced - this simplifies testing and removes any asynchronous behavior related to group events.

I also did a bit of drive-by refactoring, mostly removing dead code and updating classes to Zeebe conventions. I recommend you review commit by commit - the last few commits are the important ones, the rest is just small refactoring.

## Related issues

closes #7176 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
ping @MiguelPires

**Review by miguelpires — APPROVED** [review]
Sorry for the delay @npepinpe. I must've deleted the email notification for the review so I only noticed it this morning.

bors r+

**Comment by npepinpe** [comment]
No worries, it happens to me all the time :sweat_smile:

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
