### PR TITLE
chore(broker): set new defaults

### LINKED ISSUE #3014: Reduce the default logSementSize
**Is your feature request related to a problem? Please describe.**

I would propose to reduce the default logSegmentSize to a smaller number like 128 or 256 MB instead of 512 MB. 

**Benefits** of having smaller logSegmentSize:

 * more data can be deleted
 * finding of last position is faster

### More data can be deleted:

 We can only delete segments, which do not contain the last exported and processed position. For example say we have 3 segments, with our current default size (512 MB) and the last processed and exported position is located in segment 1. Then we are only able to delete segment 0.

If we have smaller segments then it depends where the position have been located before.
If it was on the top of the segment then there is no difference, but is it in the later half for example then we could delete more data if the log segment size is for example 256 MB.

### Last position can be found faster

Since https://github.com/zeebe-io/zeebe/issues/3006, we iterate only over the existing block in the last segment to find the last position. If the segments size is smaller then we have less data to read to find the last entry.

### Downsides

 We would have more metadata (for each file).
 Currently I'm unsure what else the downsides are.

**Describe the solution you'd like**
Change the default log segment size.

### LINKED ISSUE #3622: Reduce number of snapshot and snapshot duration
**Description**

- Max Snapshot should be 1
- Snapshot duration 5min
- Log Segment Size back to atomix default
- please update zeebe.cfg.toml accordingly 

Reason for this: #3573

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Sets new defaults for:
 * log segment size to 128 MB
 * snapshot interval to 5

Setting these values will improve the performance (related https://github.com/zeebe-io/zeebe/issues/4249) and makes possible that we can compact more in shorter time. Related also to https://github.com/zeebe-io/zeebe/issues/3014

|| **New Defaults** | **Base** |Comment|
|---|-----------------------|------------|--|
|general|general|base-general|The FNI's are almost doubled.|
|general2|general2|base-general2|50 Workflow instance completion per second more over the avg of 3 days.|
|Throughput|throughput|base-throughput|Here we can see again that the avg has almost doubled.|
|Snapshots|snapshots|base-snapshot|Looks like that we sometimes take no snapshots?|
|Resources|res|base-res| We had some restarts because we reached the memory limit.|
|Resources 2|res2|base-res2|The disk usage is by factor ~2 lower.|
|Atomix|atomix|base-atomix||
|Atomix|atomix2|base-atomix2|We can see that we use more segments|
|Processing|processing|base-processing|Looks like we had some problems on exporting or the metric is broken.|
|Latency|latency|base-latency|Latency has also improved here by factor ~2.|

## Related issues

closes #3622 
closes https://github.com/zeebe-io/zeebe/issues/3014

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [x] The change has been verified by a QA run
* [x] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:tada:

**Comment by npepinpe** [comment]
Seems stuck in the QA phase for the last 6 hours - can you have a look?

**Comment by Zelldon** [comment]
Yeah I needed to retry more then 20 incidents :D

**Comment by npepinpe** [comment]
That doesn't sound normal...?

**Comment by Zelldon** [comment]
There were dns issues in the cloud nothing to worry :thinking: :D

**Comment by Zelldon** [comment]
QA was green :+1:

**Comment by Zelldon** [comment]
bors r-

@npepinpe missed to adjust the config template will add it and then merge

**Comment by npepinpe** [comment]
Good point - also, how is the docs pulling these now? Is it manual? We might have to manually update the docs I guess.

**Comment by Zelldon** [comment]
@npepinpe yep unfortunately :sweat_smile:

**Pull request merged**
