### PR TITLE
[WIP] Protocol and protocol jackson improvements

### LINKED ISSUE #8837: Protocol Jackson improvements
**Description**

There are some existing issues with the current implementation of the `protocol-jackson` module. The main issues are:

1. For every type created in `protocol`, we need to add a corresponding type in `protocol-jackson`.
  1. This is error prone (as example, we already have missing types), and it's not so easy to add tests to guarantee this (though do-able)
  1. This adds unnecessary overhead for developers
1. The `Immutable` implementations are hidden - this was to reduce the API surface, but it turns out that this blocks, to some extent, interoperability with other tools and libraries, especially those operating by reflection (e.g. fixture/data generators)
1. Each of the types added in `protocol-jackson` need to also define how to deserialize nested types. This is also error prone and adds overhead for developers, and difficult to ensure via tests.
1. Copying into an immutable structure is a shallow copy, as Immutables doesn't recognize that, say, `JobRecordValue` is equivalent to `AbstractJobRecordValue`.

The proposed solution is:

- Annotate the existing types in the `protocol` module directly. These annotations are compile-time only, and as such, there is no extra dependency added to the module. 
- We combine all required annotations in a single one: `ZeebeProtocolValue` (or even just `ProtocolValue` - or suggest anything). This not only makes it easier to guarantee all types are correctly annotated, but also opens up the way for #8886 and other properties we would like to enforce in our protocol
- We would not add the Jackson bindings there, however, but instead keep `protocol-jackson` specifically to define a `ZeebeProtocolModule`, as is common with Jackson to define custom serialization.
- A new module will be created, `protocol-util`, which would add utilities to help using the protocol, notably make explicit the mapping of `ValueType`, `Intent`, and `T extends RecordValue`, and also keep track of the mapping between the interface types (e.g. `JobRecordValue`), their immutable counter part (e.g. `ImmutableJobRecordValue`), and their builders (e.g. `ImmutableJobRecordValue.Builder`). This is then used by the `protocol-jackson` module and any other module which wants this information (e.g. `protocol-test-util`).

This has several advantages:

1. Copying is now a deep copy, as you would expect
1. You can more easily use the `Immutable*` variants when you need to, and if you don't care about the serialization part, you can still use them
1. We can easily add a `ArchUnit` test which checks that the interface types are correctly annotated (which guarantees they will generate an immutable equivalent)
1. The mapping of `ValueType`, `Intent`, and values is made explicit - this can be further improved via #8886
1. It makes it very easy to add a random record generator once we have `protocol-util` and the immutable variants
1. The `protocol-jackson` module now is better defined - it's literally just a single Jackson module which you add to your object mapper and now knows how to deserialize the Zeebe protocol.
1. Having a random record factory which you can semi control (i.e. reusing `protocol-util`) makes it much easier to write exporter unit tests, where the data in the records isn't so important in most cases

See the draft PR for an idea of what it would look like.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR attempts to solve some of the issues we have with the current `protocol-jackson` implementation and how it works with the `protocol` module.

Some of the issues, in no particular order:

- Copying only makes shallow copies, which means the resulting objects are not truly immutable. This is a limitation of the library when working with types from an external module. That's solved when annotating the abstract types directly in the same module.
- There's some maintenance overhead due to the requirement of adding an equivalent `Abstract*` type in a different module. We can help ease maintenance here by adding [ArchUnit](https://www.archunit.org/) tests which can ensure that all interfaces under `io.camunda.protocol.record` are correctly annotated with `@ZeebeImmutableProtocol`. While we could do the same before, it was more complicated as there was not a clear indication that a type would be generated in the other module. And, gut feeling, annotating the type directly makes it less likely that developers will forget to do so, as opposed to having to add an additional type in another module.

The solution is to move the generation of the immutable values to the `protocol` module itself. While this widens the API considerably, it only does so by adding simple immutable classes, without any specific logic. Their API is directly tied to the abstract types we define, with some additions from the library itself. However, as mentioned when we adopted it, if we find they break too often, we can simply copy the generated code into our own project. These classes are tedious to create, but not particularly to maintain, I think.

Doing so has the advantage that we are less likely to forget to make a type immutable, we can more easily add ArchUnit tests to double check that, and we now have deep copies, taking any `Record<?>` implementation and converting it to a fully immutable value. While doing this, I changed the `Record#clone` method to `Record#copyOf` to align the naming, and also to reduce confusion with the standard Java `Object#clone()` method, as we didn't really follow its semantics I think - typically, clone creates a shallow copy of an object, but in our case we explicitly want deep copies. While that's not too bad, it's unexpected, and I don't really see the advantage of us reusing the built-in clone mechanism if we're just going to re-implement the method anyway.

Serialization now works by adding a new `ZeebeProtocolModule` to any `ObjectMapper`. This actually standardizes better with how Jackson work, allowing users to do something like:

```java
final String myJson; // assume it's assigned something
final ObjectMapper mapper = new ObjectMapper().registerModule(new ZeebeProtocolModule());
final Record<?> myRecord = mapper.deserialize(myJson, new TypeReference<Record<?>>(){});
```

> We could think of adding a built-in or constant reference to the `TypeReference<Record<?>>(){}`, as it's likely anyone wanting to deserialize a record will need to build it every time. So maybe `ZeebeProtocolModule.recordTypeReference()` which returns a constant `new TypeReference<Record<?>>(){}`? I don't think it's necessary, but it might be a nice convenience thing.

So you can use the abstract types when deserializing. Now, obviously equality may not always work if the implementations are different, but this is consistent with how Java defines equality, after all.

The module focuses on deserialization of the abstract protocol types. To do so, it first finds (only once, but lazily) the protocol abstract types annotated with `ZeebeImmutableProtocol` (open to name changes). It then checks for all the implementing classes of each, creating a mapping between abstract types and concrete types (something Jackson fully supports, and quite easily). This takes care of most of the deserialization logic, i.e. finding the right concrete type for an interface/abstract type.

To solve the issue with the `Record<T>` generic parameter, and also resolve the right intent class, we use annotation mixins. This allows you to tell Jackson that hey, if you see type `ImmutableRecord.Builder<T>`, then check the `RecordMixin` annotation and apply these to the matching fields. That way, we can tell it to resolve the type of the value and the intent to their proper types (even if they are abstract, e.g. `ErrorRecordValue`).

Finally, since immutable objects don't work well with Jackson (since it's more meant for beans), there's an annotation introspector which reuses the type mapping to tell Jackson to use the inner builder when deserializing the objects. It's the equivalent of annotating the types with `@JsonDeserialize(builder = ImmutableRecord.Builder)`. We can't reuse mix-ins here, since we would need one mix-in per builder class. The introspector lets us do that cheaply. The implementation reuses the type mappings we built which can look up in constant time the builder type, so it adds very little overhead to the overall deserialization process. Plus, for each type, the deserializer is only created once for Jackson.

All of this means there are some breaking changes, obviously. Removing the `Cloneable` interface from `Record` is one (including renaming `clone` to `copyOf`). Adding the immutable annotations is also flagged as one as revapi can't tell if they break the contract or not, but we can tell and they don't, of course. I realized our revapi configuration was not playing nicely with the `ignored-changes.json` file as described in the wiki, so I fixed that as well. To allow multiple configuration files and proper merging of the configuration, you simply need to give each extension a unique ID. Extensions of the same type with the same ID are then merged together. This can (and should) of course be extracted to a different PR, and the wiki should be updated.

## Related issues

closes #8837 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Comment by npepinpe** [comment]
@korthout it might make sense to have a look at it together, but I would also suggest checking out the branch, building it, and checking the resulting immutable values, as well as the example test in `protocol-jackson`, `ZeebeProtocolModuleTest`.

**Comment by npepinpe** [comment]
Kind of weird that the CodeQL warnings refer to files that don't exist anymore...

**Comment by npepinpe** [comment]
So Spotbugs is flagging a lot of possible nullable values, except...it's not true. You can see the code, and it's not possible to get a null value, though I guess it can't quite figure that out. I'm not sure why it cares, I've removed the annotations, so...not sure where it's getting that there is a non null check.

See this example flagged:

```java
public final Builder addEvaluatedInput(EvaluatedInputValue element) {
  if (element != null) element = convertToValueTypeio_camunda_zeebe_protocol_record_value_ImmutableEvaluatedInputValue(element);
  this.evaluatedInputs.add(ImmutableEvaluatedInputValue.builder().from(element));
  return this;
}

private static EvaluatedInputValue convertToValueTypeio_camunda_zeebe_protocol_record_value_ImmutableEvaluatedInputValue( EvaluatedInputValue value) {
  if (value == null) return null;
  return ImmutableEvaluatedInputValue.builder().from(value).build();
}
```

As you can tell, yes technically `convertToValueTypeio_camunda_zeebe_protocol_record_value_ImmutableEvaluatedInputValue` may return null. But in the case where it's called, it's only called with non-null values. So in these cases, it will definitely not return null. Yet Spotbugs flags this has a potential issue. I kind of get it, but it's all false positives here.

**Comment by npepinpe** [comment]
You may notice I started using the `SpotBugs` and `JCIP` (a subset of the JSR305) annotations. I'm happy to drop it for now, but as we do make use of SpotBugs, I wanted to play around with it. I like them, actually, but it's maybe something we want to discuss first - though again, we do use SpotBugs, so adding these annotations just leverages our existing tooling. But maybe we want to have some idea of how much we want to make use of them, and some best practices.

**Review by korthout — COMMENTED** [review]
Nice work @npepinpe. 🏆 

I've played around with it and the only thing that I could think of (which we currently don't support either) is the forward compatibility of the jackson module.

IMO, this will greatly improve the maintainability of the protocol module.

Consider the concept approved 👍

**Comment by npepinpe** [comment]
Can be closed, as everything was extracted into different PRs

**Pull request closed without merging**
