### PR TITLE
Don't write Job activated record

### LINKED ISSUE #2182: Do not write job activated record
At the moment when a job is activated two records are written, one for `ValueType.JOB + JobIntent.ACTIVATED` and one for `ValueType.JOB_BATCH + JobBatchIntent.ACTIVATED` which contains the job record in a list of activated jobs. The hypothesis is that the job record is not needed anymore. Validate if this is needed for recovery or anything else in the job state. Validate if this record is consumed by operate.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
 * The job activated record is no longer written to the log. It is already present in JobBatchRecord.
 * Job record is also not copied multiple times just wrapped without variables for state updates.
 * Fixed MetricExporter, since it relied on the Job.ACTIVATED event.
  * Fix several engine tests

I run a benchmark and saw no problems, only with the Job activation metrics, which I have fixed afterwards.

#### General

general
general2

#### Resources
res

#### Latency
latency
latency2

#### General

no-general
no-general2

#### Resources

no-res

#### Latency

no-latency
no-latency2

I set up a new benchmark with the metrics fix.

## Related issues

closes https://github.com/zeebe-io/zeebe/issues/2182

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [X] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
Nice. Thanks Chris :cake: 

Just one minor comment regarding a test.
Please add a note to the release announcements because it is kind of a user-facing change.

**Comment by Zelldon** [comment]
Ups github scrolled to slow then I mistakenly closed it sorry. Thanks for the review @saig0 

Latency metrics are also working now:
latency2

I will squash your commit and then merge if you accept again :sweat_smile: :grin:

**Comment by npepinpe** [comment]
Will this be flagged by the inconsistency detection? Could it break an update?

**Comment by Zelldon** [comment]
I think this will not be detected by our detection. I just tested it with 0.25.2 creating instances, activating jobs etc and then updating to my snapshot. No problems found. The thing is on the earlier version the event exist. The follow up event is tested, whether the source exist and has same key etc. But we will not detect whether we are still writing an event.

Maybe @saig0 can explain this better.

**Pull request merged**
