### PR TITLE
chore(broker-core): distribute topology through Java POJO

### LINKED ISSUE #1958: Use Java POJO to distribute atomix member properties
Every broker in the atomix cluster shares to types of information: static configuration and dynamic partition roles. To ease the distribution of these and being type safe we should use Java POJOs and de/serialize them to json for example.

The static configuration contains, i.e property `brokerInfo` contains
- node id
- partition count
- replication factor
- cluster size
- contact points for all APIs with
  - host (String)
  - port (int)

The dynamic configuration, i.e. property `partitionInfo` contains
- mapping between partition id (int) to partition role (enum: Leader/Follower)

The Broker and Gateway should use these pojos to read the information and update their topologies. For example member ship events without `brokerInfo` property can be ignored.

### PR DESCRIPTION
**Pull request by miguelpires**
Refactors the way how topology changes are propagated to use Java POJO. 

closes #1958

### CODE REVIEW

**Comment by menski** [comment]
@MiguelPires could you please fix the checkstyle warnings, thanks

**Comment by MiguelPires** [comment]
@menski done

**Review by menski — COMMENTED** [review]
The Client API Rule integration does not work with this change. I will look into it

**Comment by menski** [comment]
I will merge this for now. The biggest changes I made are that we try to reuse atomix as much as possible in the test suite, and also in the embedded gateway. There are still clustered tests which are flaky, will look into that as next step.

**Pull request merged**
