### PR TITLE
ci: automatically deploy benchmark starter and worker images

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This introduces jib for the starter and worker images and adds another job to our CI pipeline to deploy both images for new commits on main (similar to how we deploy camunda/zeebe:SNAPSHOT). The images are tagged with `latest` which I think is good enough for now.

I've also removed some of the old scripts that appear to be unused. As far as I can see, nothing was building and pushing new starter/worker images automatically. Having this automated now will help us in improving the starter/worker applications.

There are some behavior changes with the new images. Java properties must be set via `JAVA_TOOL_OPTIONS` instead of `JAVA_OPTIONS`. Once we start using the `latest` images for benchmarks, this will need to be adjusted: https://github.com/zeebe-io/benchmark-helm/blob/main/charts/zeebe-benchmark/templates/starter.yaml#L23

Successful test run: https://github.com/camunda/zeebe/actions/runs/4193260612/jobs/7269915671

relates to #11484

### CODE REVIEW

**Comment by npepinpe** [comment]
:( I use the release.sh script all the time as part of the release, or just to test out stuff, since it can build multiple branches/tags in parallel and push the image directly :sweat_smile:

**Comment by oleschoenburg** [comment]
> :( I use the release.sh script all the time as part of the release, or just to test out stuff, since it can build multiple branches/tags in parallel and push the image directly sweat_smile
> 
> It's possible the release process refers to it (the old text only, before we moved it to tasklist, did)

Oh, I wasn't aware :+1: I was under the impression that no one was actually releasing the benchmark images.

**Comment by npepinpe** [comment]
It used to be part of the release process, unless it's been removed. I haven't done in a release in a while, not since it's been migrated, so who knows.

**Comment by npepinpe** [comment]
How would I build the images for specific tags now?

**Comment by oleschoenburg** [comment]
> It used to be part of the release process, unless it's been removed. I haven't done in a release in a while, not since it's been migrated, so who knows.

It's not part of the release workflow and I also didn't come across a manual task for this when I did the last patch release. So I think this was actually lost somewhere along the way.

> How would I build the images for specific tags now?
By checking out the tag and then building the image with `jib` I guess. What's the use case here? Using the "right" starter/worker when benchmarking an older Zeebe release?

**Comment by npepinpe** [comment]
Using the right versions to benchmark older releases is one, but also if I fix things in the client or do anything (new API), and I want to test it out with a benchmark. I can still build everything manually but then I have to remember to retag it before pushing so as to not disrupt others.

**Comment by oleschoenburg** [comment]
>  I want to test it out with a benchmark. I can still build everything manually but then I have to remember to retag it before pushing so as to not disrupt others.

That's one thing I actually wanted to build too: creating benchmarks should build and use worker and starter images for the commit hash, just like we do with the normal Zeebe image. As long as it is tagged with the commit hash and not as latest, this won't disrupt others.

For releasing I'd extend the release workflow to also build and push images tagged for the release version.

**Comment by Zelldon** [comment]
> It's not part of the release workflow and I also didn't come across a manual task for this when I did the last patch release. So I think this was actually lost somewhere along the way.

I have to disagree here. It is part of the process https://github.com/zeebe-io/zeebe-engineering-processes/blob/f6d4acb4e4d4b996c6b7b7f06ffbed0caf909c4d/src/main/resources/release/post_release.bpmn#L108

**Comment by oleschoenburg** [comment]
:facepalm: Okay nevermind then. Sorry for the confusion and thanks for clarifying @Zelldon and @npepinpe

**Comment by Zelldon** [comment]
giphy

**Comment by npepinpe** [comment]
But I liked that we used jib! I don't think that's mutually exclusive :(

**Comment by Zelldon** [comment]
Agree in general I also would like to see the building and pushing the images in the benchmark workflows.

**Comment by oleschoenburg** [comment]
Alright, let me see if I can make it work. So we want jib + deploying for benchmarks + keeping the release script intact.

**Comment by oleschoenburg** [comment]
GitHub didn't let me reopen this so there's a new PR: https://github.com/camunda/zeebe/pull/11731

**Pull request closed without merging**
