### PR TITLE
chore(monitor): fix io panels

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Fixes the io panels in our camunda cloud setup, which were broken for a long time.
See discussion in https://github.com/camunda-cloud/monitoring/issues/242

Before:

broker

Fixed:

fixed

## Related issues

closes https://github.com/camunda-cloud/monitoring/issues/242

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by korthout — COMMENTED** [review]
Nice work. I just have 1 question: Do these changes impact functionality of our benchmark dashboard? If so, should we maybe make these changes on each specific board instead of in the main zeebe grafana definition.

**Comment by Zelldon** [comment]
@korthout no it still works with this version :)

**Review by korthout — APPROVED** [review]
@Zelldon In that case, please take this 🌮 LGTM

**Comment by Zelldon** [comment]
bors R+

**Pull request merged**
