### PR TITLE
docs(operate-user-guide): Add v1 Operate user guide to Zeebe docs

### LINKED ISSUE #2713: Create Operate user guide
Create an Operate user guide that goes beyond the functionality covered in the "Getting Started" guide.

### PR DESCRIPTION
**Pull request by wints**
closes #2713 

This simple user guide explains how to update variables, resolve incidents, and perform batch operations via selections.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 24967b194ad6bad0eb672fb47042868b16c6dbeb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8c4273d839f8a6f7d35583eed9bb6c310119272d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 557f4a7c59805b663b3063956751b9c9055ee2eb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by wints** [comment]
@jwulf I tagged you for review in case you have time to take a look this week. 

One note: I just left the "running in production" section blank for now and said we'd update it once there is a production-licensed Operate actually available. I think it's fine to punt on that for now.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 24967b194ad6bad0eb672fb47042868b16c6dbeb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8c4273d839f8a6f7d35583eed9bb6c310119272d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 0fd5e69dd73a0130446211dbf65971bfac94e098
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci, build**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 24967b194ad6bad0eb672fb47042868b16c6dbeb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8c4273d839f8a6f7d35583eed9bb6c310119272d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 24967b194ad6bad0eb672fb47042868b16c6dbeb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 8c4273d839f8a6f7d35583eed9bb6c310119272d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
