### PR TITLE
test: `PartitionRestoreServiceTest` does not block on taking a backup

### PR DESCRIPTION
**Pull request by lenaschoenburg**
We saw some unit tests timing out in `PartitionRestoreServiceTest`:

```
"ForkJoinPool-1-worker-1" #19 daemon prio=5 os_prio=0 cpu=1567.91ms elapsed=914.45s tid=0x00007facfca78b60 nid=0x15ab5 waiting on condition  [0x00007facb83df000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4.1/Native Method)
	- parking to wait for  <0x0000000511f04c68> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4.1/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.4.1/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.compensatedBlock(java.base@17.0.4.1/ForkJoinPool.java:3449)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.4.1/ForkJoinPool.java:3432)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.4.1/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.join(java.base@17.0.4.1/CompletableFuture.java:2117)
	at io.camunda.zeebe.restore.PartitionRestoreServiceTest.takeBackup(PartitionRestoreServiceTest.java:212)
	at io.camunda.zeebe.restore.PartitionRestoreServiceTest.shouldFailToRestoreWhenSnapshotIsCorrupted(PartitionRestoreServiceTest.java:182)
```

With these changes here we ensure that the test does not wait forever on a backup, instead setting a maximum of 30 seconds. Additionally, `TestRestorableBackupStore` now fails the future when a backup is marked as failed.

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
Thanks for looking into it. Just 2 points:
1. May be we can add `@Timeout` to the test. So even if we forget to add explicit timeout to new tests, it will timeout eventually.
2. TestSnapshotStore is not thread safe. Is it creating the issues? The backup future can be a volatile, and the map has to be concurrent map.

**Comment by oleschoenburg** [comment]
> TestSnapshotStore is not thread safe. Is it creating the issues?

This test uses `FileBasedSnapshotStore`, not `TestSnapshotStore`.

**Comment by deepthidevaki** [comment]
> > TestSnapshotStore is not thread safe. Is it creating the issues?
> 
> This test uses `FileBasedSnapshotStore`, not `TestSnapshotStore`.

Oops. Sorry, I meant `TestRestorableBackupStore`

**Review by deepthidevaki — APPROVED** [review]
:rocket: Thanks.

**Pull request merged**
