### PR TITLE
Add Operate Build step to merge queue

### LINKED ISSUE #17118: Add Operate build step to merge-queue
To at least cover whether the Operate code is still buildable after merging we should include Operate build to the merge queue.

This can be seen as a first step to make Operate CI part of the merge queue (after several improvements also from the Operate side related to reliability and performance of the CI have been done).

- [ ] Introduce a new workflow that only builds the Operate code basis
- [ ] Workflow needs to react on merge_group events
- [ ] Our merge queue needs to accept/wait for two events/jobs, right now it waits for test_summary only
  - [ ] We need to make sure that there exist one for Zeebe (test_summary) and one for Operate (later likely also one for Tasklist, etc.)
- [ ] tbd.

This is in the light of (recent) events, see [slack thread](https://camunda.slack.com/archives/C9B5270DA/p1711376024115889?thread_ts=1711375403.007319&cid=C9B5270DA)

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

A while ago we decided to leave the Operate CI out of the merge queue, as it was seen as not reliable and fast enough. This contains some risks, when merging several PRs together. Recently we made several changes how dependency are handled (and enforced). After merging some refactoring in the POM's several other PRs which have been merged failed on main, see related [slack thread](https://camunda.slack.com/archives/C9B5270DA/p1711376024115889?thread_ts=1711375403.007319&cid=C9B5270DA). 

As we want to avoid such and want to build a stable product we want to slowly integrate Operate CI into our merge queue, for now only the build process to at least make sure that we can build the code basis still after merging a PR, see related issue #17118 

> [!Important]
>
> Merge queues don't support any path filtering, this needs to be done later manually. 
> See related discussion  https://github.com/orgs/community/discussions/45899#discussioncomment-5643259

This PR adds a new workflow, that is triggered by the merge queue or manually. It specifies a new `operate-ci-test-summary` which we need to specify in our merge queue configuration.

Furthermore, the old test-summary in the Zeebe ci was renamed to make more clear what this test-summary references. We can discuss this whether this is really necessary.

## Related issues

closes #17118

### CODE REVIEW

**Comment by Zelldon** [comment]
As soon as this is merged we need to adjust the merge queue config

**Review by cmur2 — APPROVED** [review]
This makes a lot of sense to have more confidence when merging.

The Operate CI build step only takes around 10-15min so it is quite fast and should not prolong wait times in the merge queue.

**Comment by oleschoenburg** [comment]
@Zelldon you cannot merge this until you adjust the merge queue rules to wait for "zeebe-ci-test-summary" instead.

**Comment by Zelldon** [comment]
This is why I wanted your review 😅 thanks @oleschoenburg

**Comment by Zelldon** [comment]
As mentioned in [slack ](https://camunda.slack.com/archives/C05DH1F5TAR/p1712250281508679) I was not able to easily change this, as it hasn't been merged yet. 

I reverted the changes of the previous test summary, to get it merged. Afterwards I will adjust the protection rules.

**Pull request merged**
