### PR TITLE
Fix benchmark image setting

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Uses the new functionality from https://github.com/camunda-community-hub/camunda-cloud-helm/pull/162 to set the images per chart. Adjust the createBenchmark script such that it replaces all occurrences.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Thanks :+1: 

:wrench: I think we should also adjust the values for Operate by removing the `global.image.repository` key.

**Comment by Zelldon** [comment]
Hey @oleschoenburg thanks for the review! You're totally right. I though I have removed that already :shrug: Done :white_check_mark: 

bors r+

**Comment by Zelldon** [comment]
bors r+

giphy

**Pull request merged**
