### PR TITLE
Use array access when extracting job properties from ActivateJobsResponse

### LINKED ISSUE #6008: Automated QA stage script fails with error
**Description**

Running branch `release-0.26.0-rc1` with QA on and parent generation of `Zeebe 0.25.3`, I get the following error in the script:

```sh
# ...
[2020-12-14T16:27:16.394Z] + echo 'Waiting for result of https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/release-0.26.0-rc1/2/'
[2020-12-14T16:27:16.394Z] Waiting for result of https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/release-0.26.0-rc1/2/
[2020-12-14T16:27:16.394Z] + true
[2020-12-14T16:27:16.394Z] + clients/go/cmd/zbctl/dist/zbctl activate jobs https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/release-0.26.0-rc1/2/
[2020-12-14T16:27:26.374Z] ++ jq -r .key
[2020-12-14T16:27:26.374Z] jq: error (at <stdin>:1): Cannot index array with string "key"
```

See https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/release-0.26.0-rc1/2/pipeline for more.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes an issue in the QA script which was introduced after #5972, where the output of zbctl's `ActivateJobsResponse` was changed to be standard JSON and always return an array.

It also introduces a new flag which allows skipping the verify stage if you only want to run the QA stage, which can be quite useful for you're testing that in particular.

## Related issues

closes #6008 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Letting it run before I assign a reviewer.

**Review by pihme — APPROVED** [review]
lgtm

**Comment by npepinpe** [comment]
Don't think it worked, it's been running for 14 hours :sweat_smile:

**Comment by pihme** [comment]
I did resolve "Cannot resolve host" incidents on testbench. It should come through now.

**Comment by npepinpe** [comment]
It probably won't, looks like our Jenkins crashed - last time that meant some pods were stuck forever and never completed their jobs.

**Comment by pihme** [comment]
The QA stage is only in develop, it has not been backported to other branches

**Comment by npepinpe** [comment]
Ah, I was under the impression we also had it for 0.25, as it would be useful for patch releases too. Is anything blocking us from adding it to 0.25?

**Comment by pihme** [comment]
Nothing substantial. I am just a little bit weary/cautious about mixing different versions. We don't really have a concept for "test 0.25 with the 0.25 version of the chaos tests". But if it works it should be ok.

**Pull request merged**
