### PR TITLE
refactor: remove data migration from the code base

### LINKED ISSUE #18853: Remove migration code
We wont run Migration over 8.6, the code can be removes

Scope of the removal
- Creation Scripts
- Schema Startup
- Tests
- Migration routines/methods

### PR DESCRIPTION
**Pull request by nathansandi**
## Description

- Remove data Migration from the code base

## Related issues

closes https://github.com/camunda/camunda/issues/18853

### CODE REVIEW

**Review by houssain-barouni — COMMENTED** [review]
@nathansandi should we remove?
- migration script generation in `dist` https://github.com/camunda/camunda/blob/bae6c9423ed1d20a484a357c118872c4d4797db9/dist/pom.xml#L522-L525 
- tasklist migration init-container in SaaS

**Comment by nathansandi** [comment]
> @nathansandi should we remove?
> 
> * migration script generation in `dist` https://github.com/camunda/camunda/blob/bae6c9423ed1d20a484a357c118872c4d4797db9/dist/pom.xml#L522-L525
> * tasklist migration init-container in SaaS

Thanks to point this @houssain-barouni , I removed from the pom

**Comment by houssain-barouni** [comment]
> > @nathansandi should we remove?
> > 
> > * migration script generation in `dist` https://github.com/camunda/camunda/blob/bae6c9423ed1d20a484a357c118872c4d4797db9/dist/pom.xml#L522-L525
> > * tasklist migration init-container in SaaS
> 
> Thanks to point this @houssain-barouni , I removed from the pom

That actually means we need to remove this `initContainer` https://github.com/camunda-cloud/camunda-operator/blob/ae8299ca190c4f098fd2cae6f6d3b3b02b062546/templates/tasklist_deployment_importer_archiver.yaml#L24-L32
and only for clusters having version >=8.6 , we may need the help of controller team to make it configurable in the [go script](https://github.com/camunda-cloud/camunda-operator/blob/ae8299ca190c4f098fd2cae6f6d3b3b02b062546/pkg/apps/tasklist/resources/tasklist_deployment.go#L52)

**Comment by nathansandi** [comment]
> > > @nathansandi should we remove?
> > > 
> > > * migration script generation in `dist` https://github.com/camunda/camunda/blob/bae6c9423ed1d20a484a357c118872c4d4797db9/dist/pom.xml#L522-L525
> > > * tasklist migration init-container in SaaS
> > 
> > 
> > Thanks to point this @houssain-barouni , I removed from the pom
> 
> That actually means we need to remove this `initContainer` https://github.com/camunda-cloud/camunda-operator/blob/ae8299ca190c4f098fd2cae6f6d3b3b02b062546/templates/tasklist_deployment_importer_archiver.yaml#L24-L32 and only for clusters having version >=8.6 , we may need the help of controller team to make it configurable in the [go script](https://github.com/camunda-cloud/camunda-operator/blob/ae8299ca190c4f098fd2cae6f6d3b3b02b062546/pkg/apps/tasklist/resources/tasklist_deployment.go#L52)

Already requested this to controller team

**Pull request closed without merging**
