### PR TITLE
fix(exporters/elasticsearch-exporter): custom headers

### LINKED ISSUE #4640: elasticsearch mapper_parsing_exception - object mapping for [value.customHeaders.payload]
Zeebe broker 0.23.1, elasticsearch 6.7.1

Error I get in zeebe broker:
```
2020-05-30 06:27:53.874 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] WARN  io.zeebe.broker.exporter.elasticsearch - Failed to flush at least one bulk request ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=object mapping for [value.customHeaders.payload] tried to parse field [payload] as object, but found a concrete value]]
zeebe            | 2020-05-30 06:27:53.874 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-0] WARN  io.zeebe.broker.exporter.elasticsearch - Failed to flush bulk completely
zeebe            | 2020-05-30 06:27:54.295 [GatewayLongPollingJobHandler] [Broker-0-zb-actors-1] 
```

Reference: https://forum.zeebe.io/t/elastic-exported-tried-to-parse-field-payload-as-object-but-found-a-concrete-value/1296

### PR DESCRIPTION
**Pull request by saig0**
## Description

* service tasks with custom headers that contain a dot can lead to mapping failures in ES
* avoid mapping failures by disabling the index of custom headers for job and job batch records

## Related issues

closes #4640 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by saig0** [comment]
@sdorokhova, this PR change the `customHeaders` property in ES template for job and job batch records. Please check if this change can lead to any problems in Operate. Thank you :cookie:

**Review by korthout — APPROVED** [review]
LGTM

**Review by sdorokhova — APPROVED** [review]
Tested similar change on Operate 1.2.1. Should be fine on current version either!

**Comment by saig0** [comment]
@korthout , @sdorokhova : thank you for the fast review :cookie:

**Pull request merged**
