### PR TITLE
Validate user task dates on deployment 

### LINKED ISSUE #11809: User task due and follow-up dates are validated on deployment
## Description
For the user task due and follow-up date properties, users are able to set a static value or a static expression. When one of these options is used, the value of these date properties can be checked for a valid DateTime String during deployment. 

This will improve the UX since users will be made aware of a badly formatted DateTime String before any process instances are created.

## Acceptance criteria
- The [ZeebeRuntimeValidators](https://github.com/camunda/zeebe/blob/49bbcaf84b1bb89ac3c7a1406af79cddd8875f94/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/model/validation/ZeebeRuntimeValidators.java#L106-L125) asserts that a static value or a static expression provided for the following properties is a valid DateTime string.
  - `dueDate`
  - `followUpDate`

## Blocked by
- https://github.com/camunda/zeebe/issues/11796

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Check for a valid DateTime string during deployment when static values are provided for the user task `dueDate` and `followUpDate` properties.

:information_source: I decided to expand the `ZeebeExpressionValidator` class instead of creating a new (dedicated) validator class. The reason is that with the `ZeebeExpressionValidator` class, we can re-use this validation for other date-related properties in the future. A dedicated validator class would be limited to the `UserTask` element. We can still create a dedicated validator class in the future if we decide to support additional formats for dates in the `ZeebeTaskSchedule` element.

## Related issues

closes #11809 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criteria of the issue
* [x] New tests are written to ensure backward compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by koevskinikola** [comment]
@korthout I'm requesting a review from you since we discussed this topic in detail so you have the most context on what the requirements are.

**Review by korthout — APPROVED** [review]
Nice work @koevskinikola 🏅 

👍 I like how you expanded the `ZeebeExpressionValidator` class

🔧 Perhaps we could add an additional test to showcase what happens when an empty string literal is used `= ""` (or `null` in case you went for that direction in the other pull request).

**Comment by koevskinikola** [comment]
@korthout I added tests that cover this use-case in the [user task activation PR](https://github.com/camunda/zeebe/pull/11890/files#diff-20c63fef9cb2701aa864aebfd93d4d2fd3291069b9ac36f0492208f056ef0dd0R469-R510). Do you think we should explicitly test the `ZeebeExpressionValidator` class?

**Comment by korthout** [comment]
>Do you think we should explicitly test the ZeebeExpressionValidator class?

No, if it's already tested elsewhere, then there's no need for it :) Thanks for noting

**Comment by koevskinikola** [comment]
bors merge

**Pull request merged**
