### PR TITLE
Add code of conduct

### PR DESCRIPTION
**Pull request by menski**

### CODE REVIEW

**Comment by jsam** [comment]
We should sync this to be the same with https://github.com/zeebe-io/zbc-go/blob/master/CODE_OF_CONDUCT.md

**Comment by menski** [comment]
Yeah I agree that we should have the same code of conduct in all projects. :heart:

**Comment by menski** [comment]
TBD which email address do we announce as contact of the zeebe project. I personally don't like the info camunda address.

@DNCamunda is the info at zeebe.io address working and should we use it as public address?

**Comment by DNCamunda** [comment]
Agreed, I don’t think we should use the info@camunda.com<mailto:info@camunda.com> address and I just double checked and the info@zeebe.io<mailto:info@zeebe.io> works so I think it would make sense to move forward with it.

Thanks,
D

**Comment by menski** [comment]
I updated the email in this pull request to info zeebe.io.

We still should discuss which code of conduct to adopt or if we even want one.

**Comment by Zelldon** [comment]
If we use now info@zeebe.io we should also adjust the license headers.

**Comment by menski** [comment]
reminder for myself add link to code of conduct to docs or website

@meyerdan As far as I can tell there is no legal binding of the code of conduct, unless we reference it in any legal document like a customer contract

**Comment by menski** [comment]
Rust code of conduct https://www.rust-lang.org/en-US/conduct.html

**Comment by menski** [comment]
> If we use now info@zeebe.io we should also adjust the license headers.

As the copyright is attributed to the company Camunda and not the Zeebe project I would assume that it is also better to use a Camunda email address. Whereas the Code of Conduct is attributed to the Zeebe Project and not the Camunda company.

**Comment by Zelldon** [comment]
Yup you're right :)

**Comment by menski** [comment]
replaced by #476

**Pull request closed without merging**
