### PR TITLE
deps: upgrade react to v18

### PR DESCRIPTION
**Pull request by misiekhardcore**
## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

related to #21816

### CODE REVIEW

**Comment by misiekhardcore** [comment]
@OmranAbazid if you find some time, can you take a look at the failing tests? maybe you'll have an idea of what the problem is there

**Comment by misiekhardcore** [comment]
@OmranAbazid do you think that we can think of merging this when the PR conflicts are solved? I will rebase this branch with `main` and see if it still succeeds all the CI

**Review by OmranAbazid — APPROVED** [review]

**Comment by OmranAbazid** [comment]
@misiekhardcore The changes looks good to me. 
It is a good idea to check if there are any additional warnings in the terminal or browser console related to the upgrade (I do not remember that i checked that)
Also, let's run the e2e two to three times to ensure they are stable.
Afterward, feel free to merge the PR.

**Comment by misiekhardcore** [comment]
@OmranAbazid I played around and I haven't seen anything in the console that was introduced with this migration.
I will run the e2e 2-3 times and after that I am going to add this PR to the merge queue

**Pull request merged**
