### PR TITLE
chore(clients/go): fix set zbctl version and commit during build

### LINKED ISSUE #3647: zbctl build does not contain version information
**Describe the bug**

`zbctl version` shows `zbctl development (commit: HEAD)` for release build.

**To Reproduce**

Download `zbctl` from Zeebe 0.22.0 release and run `zbctl version`.

**Expected behavior**

`zbctl version` should print the version and hash of the released version, i.e. the 0.22.0 release `zbctl 0.22.0 (commit: 87e98789)`.

### PR DESCRIPTION
**Pull request by menski**
## Description

- allow to override the git hash in build script
- add test case to verify version is correctly set

## Related issues

closes #3647 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by miguelpires — APPROVED** [review]
bors r+

**Comment by MiguelPires** [comment]
bors retry

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
