### PR TITLE
Close topology client in clustering rule

### LINKED ISSUE #1253: The integration test suite leaks clients
During the integration test suite brokers or parts of it stay alive even after the test has ended

### PR DESCRIPTION
**Pull request by menski**
closes #1253

### CODE REVIEW

**Comment by Zelldon** [comment]
Ok all of the threads are killed after each test and also the garbage collections seems to work better, but there are still 80-100mb on the clustering tests which are not collected.

file

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
See my comment

**Review by ChrisKujawa — APPROVED** [review]

**Comment by Zelldon** [comment]
We decided to split this into another issue https://github.com/zeebe-io/zeebe/issues/1260

**Pull request merged**
