### PR TITLE
chore(ci): add template distribution podspec for stable agents on bors staging branch

### PR DESCRIPTION
**Pull request by cmur2**
## Description

Introduces a duplicated `distribution-template.yml` podspec as I didn't want to touch all usages yet.

Since bors cannot deal with the automated retriggering of Jenkins builds failed due to disconnected agents (due to e.g. https://issuetracker.google.com/issues/156556218), use a stable agent for these builds.

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
Thanks! I have one question, would the issue of dropped connections during a scaling event also affect the stable node pool? I assume so - so we might still get aborted builds in staging, right? But I imagine there's less scaling events so it should less likely.

**Comment by cmur2** [comment]
> Thanks! I have one question, would the issue of dropped connections during a scaling event also affect the stable node pool? I assume so - so we might still get aborted builds in staging, right? But I imagine there's less scaling events so it should less likely.

IIRC correctly it can affect any nodepool with autoscaling so yea, the stable one as well. This proposal here just reduces sources of errors (node preemptions) but can't guarantee completely stable builds - just "more stable". From the experience they are usually quite stable due to a low number of scaling events (also because just long-running jobs are here).

**Comment by cmur2** [comment]
bors +r

**Comment by cmur2** [comment]
Build at https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/staging/2606/consoleFull shows that the right annotation for bors' staging branch is used: `agents-n1-standard-32-netssd-stable` :slightly_smiling_face:

**Comment by npepinpe** [comment]
bors retry

**Comment by cmur2** [comment]
bors retry

**Pull request merged**
