### PR TITLE
Use new testing infrastructure with job stream integration tests

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR migrates the job push/stream integration tests to use the new testing infrastructure instead of the clustering rule.

Instead of verifying by fetching the underlying `SpringBrokerBridge`, then the `JobStreamClient` or the `JobStreamService` - bypassing the real UI - we now use the actuator for all verification. This means the old `JobStreamServiceAssert` and `JobStreamClientAssert` are replaced with a unified `JobStreamActuatorAssert`. The assertions themselves are pretty much the same though.

I also fixed a bug with the new test infrastructure - the Netty embedded server actually used a global event loop. This means when you closed one application (e.g. gateway, or one broker), it would close the loop for _all_ embedded servers, including that of the other apps. This is fixed in https://github.com/camunda/zeebe/commit/9755e9051f1b11e689fc5db706e81923c46b8d2b by configuring our own `ReactorResourceFactory`. While the Spring one can be configured via properties, the only property it accepts is the quiet shutdown period, so not very useful for us.

Anyhow, it's a big-ish PR, but I didn't see how to split it except artificially (such that you don't really see why everything is done unless you see the final result).

## Related issues

related to #13962

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Nice :+1: 
I gotta say, I'm a bit envious about the streams actuator and matching asserts, they look great :heart_eyes: 

bors merge

**Comment by oleschoenburg** [comment]
Whoops, looks like you need to fix some dependency issues @npepinpe

**Comment by npepinpe** [comment]
:see_no_evil:

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
