### PR TITLE
chore(clients/java): make grpc-netty is a compile dependency

### LINKED ISSUE #1998: Java client is missing dependency on gRPC implementation
```
Exception in thread "main" io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional channel service provider found. Try adding a dependency on the grpc-okhttp, grpc-netty, or grpc-netty-shaded artifact
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:60)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:37)
	at io.zeebe.client.impl.ZeebeClientImpl.buildChannel(ZeebeClientImpl.java:100)
	at io.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:71)
	at io.zeebe.client.impl.ZeebeClientBuilderImpl.build(ZeebeClientBuilderImpl.java:116)
```

### PR DESCRIPTION
**Pull request by menski**
closes #1998

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
How come this wasn't breaking before? It was a transitive dependency?

**Comment by menski** [comment]
In tests we often have the broker also as a dependency which has a dependency on grpc-netty, so we are missing a client test in isolation without the broker.

**Comment by menski** [comment]
bors retry

**Pull request merged**
