### PR TITLE
What would it look like if startup was synchronous?

### PR DESCRIPTION
**Pull request by pihme**
## Description

One thing I like to do when comparing programming or architectural styles is to implement the same thing in different styles side-by-side. Often this is not possible because it is too much effort. But in the case of the startup logic it is quite easy.

So what would the startup look like if it was just a plain old synchronous piece of code? If we strip away all the glue code and concurrency and future, what is the code actually doing? That's what this branch explores.

To me, Kotlin co-routines suddenly become very desirable.

(I didin't bother implementing the shutdown. By and large it will be even more straightforward than the startup)

### CODE REVIEW

**Comment by pihme** [comment]
@npepinpe FYI

**Comment by npepinpe** [comment]
As expected, synchronous programming is much simpler and more natural :smile: I'm not sure I get the coroutines though - you're still blocking the broker context anyway, so I don't think it gives you much advantage? Admittedly I'm not super familiar with co routines, but I imagine they're basically the same as green threads/fibers/virtual threads/whatever other languages call them :smile: The only advantage I see with coroutines would be with the partition transitions/startup - but for the broker's, it's probably not all that advantageous?

The biggest win from my pov here is that dependencies between steps are very clearly expressed via the constructors - no more implicit dependency through the context, no more dealing with potentially null values, etc. 

I did want to take some time at some point to see if we couldn't mix and match approaches. Why not have the building/bootstrap phase blocking, then use the created objects and pass them off to the asynchronous context? It would require you to be a bit careful when it comes to sharing state and the various execution contexts/layers, but I think it wouldn't be that difficult to do in a clear and obvious way.

(I did notice this example is missing logging and error handling, e.g. there's no clear indication of the progress, but I get that that's easy to add and only adds a bit of cruft)

**Comment by npepinpe** [comment]
Actually, I'd be very curious to explore this mix and match approach - essentially taking a page out of most dependency injection framework.

1. Build your object graph in a blocking way
1. Build your asynchronous contexts with their dependencies

I think the tricky part is correctly managing inter-dependencies when it comes to the lifecycle of these things, but with the right layers/contexts I think (keyword: think - I'd need to try it out) it can be done in a fairly easy-to-reason-about way.

**Comment by pihme** [comment]
I think this will be easier when everything has been Actorified. Right now there are some odd things like embedded gateway service which perform the start as part of the constructor.

**Pull request closed without merging**
