### PR TITLE
Add metrics for Batch processing

### LINKED ISSUE #11546: Add new metrics for Batch processing
**Description**

part of https://github.com/camunda/zeebe/issues/11416

With https://github.com/camunda/zeebe/issues/11416 we introduce a new feature called batch processing, which changes how much command we process at once. In order get better visibility we want to add additional metrics.

Potential metrics: 

- [x]  batch record count (how many we write as batch)
  - [x] Done via sequencer metrics
- [x]  batch size in bytes to write
  - [x] Done via sequencer metrics
- [x]  batch command count (how many commands we have processed)
  - [x] `stream_processor_batch_processing_commands`
- [x]  batch post commit tasks count
  - [x] Not possible, since this is part of the result implementation. But it is more interesting how long it tasks. So we just added a timer for that.
  - [x] `stream_processor_batch_processing_post_commit_tasks`
- [x]  batch limit (is adjusted when we reach the limit)
  - [x] We thought about it, but the problem is that we are in the hot path and the limit will change quickly back to the default. We might not notice due to our scrape interval. WE introduced a counter for retries `stream_processor_batch_processing_retry`
- [x]  time of batch processing (start of reading initial command - end when we detect no more command to process or reached limit) 
  - [x] `zeebe_stream_processor_batch_processing_duration`
- [x] Failed batch -> counted retries
- [x] How long does it take to run side effects? If it's too long, I might want to decrease the limit

A clear and concise description of what this issue is about.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Adds new metrics for batch processing:

> - [x]  batch record count (how many we write as batch)
>   - [x] Done via sequencer metrics 
> - [x]  batch size in bytes to write
>   - [x] Done via sequencer metrics #11512 
> - [x]  batch command count (how many commands we have processed)
>   - [x] `zeebe_stream_processor_batch_processing_commands`
> - [x]  batch post commit tasks count
>   - [x] Not easily possible, since this is part of the processing result implementation. In general, it is more interesting how long it takes. So we just added a timer for that the duration of the execution.
>   - [x] `stream_processor_batch_processing_post_commit_tasks`
> - [x]  batch limit (is adjusted when we reach the limit)
>   - [x] We thought about it, but the problem is that we are in the hot path and the limit will change quickly back to the default. We might not notice due to our scrape interval. We have introduced a counter for the retries `stream_processor_batch_processing_retry`
> - [x]  time of batch processing (start of reading initial command - end when we detect no more command to process or reached limit) 
>   - [x] `zeebe_stream_processor_batch_processing_duration`
> - [x] Failed batch -> similar to the counting the retries
> - [x] How long does it take to run side effects? If it's too long, I might want to decrease the limit
>   - [x] See above

New Panel added:

In Processing:

processing

In Latency:

latency

## Related issues

closes #11546 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project zeebe-stream-platform: Compilation failure
Error:  /runner/_work/zeebe/zeebe/stream-platform/src/main/java/io/camunda/zeebe/stream/impl/ProcessingStateMachine.java:[290,13] cannot find symbol
Error:    symbol:   variable processingBatchLimit
Error:    location: class io.camunda.zeebe.stream.impl.ProcessingStateMachine
```

**Comment by oleschoenburg** [comment]
I rebased on main.

bors r+

**Pull request merged**
