### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by korthout**
## Description

Merges the changes of release 1.3.0 into master as part of the release process.

Due to conflicts I had to merge master first into the `release-1.3.0` branch. I did this using:
```
git fetch
git checkout origin/release-1.3.0
git merge origin/master -Xours
```

### CODE REVIEW

**Comment by npepinpe** [comment]
Is it even feasible to review this? :thinking:

**Comment by Zelldon** [comment]
@npepinpe tbh I thought the same :sweat_smile:

**Comment by korthout** [comment]
You can try doing what I've described and see if the results match 😄

**Comment by korthout** [comment]
@npepinpe Well, someone should review this so we can merge it. I'm not sure how to improve things here further. Can you have a look perhaps?

**Comment by menski** [comment]
I would like to propose again delete `master`, and stick with `develop` only, and maybe rename `develop` to `main`. I know I'm the reason we have this procedure in the first place, but I would argue after many years, it is not working in the way it was intended.

**Comment by korthout** [comment]
I like removing `master`, I'm neutral about renaming `develop` to `main`.

We already have tags to shows the exact contents of specific versions, `stable` branches for further developments of specific versions and `develop` for our current progress. So I see no need for a `master` branch.

**Comment by npepinpe** [comment]
Dropping master and renaming develop to main sounds fine. I think the last time we discussed this, the argument for master was that people expect it to be the last stable release? Not sure we ever confirmed this though.

Looking at different projects, it seems like main/master often just points to the development head. See RocksDB, Netty, OpenSSL, etc., all projects which get a lot more eyeballs on them than ours.

So I think getting rid of master and renaming develop to main is the right step, we just need to update our build scripts for that.

**Comment by npepinpe** [comment]
So we can close this PR from my point of view.

**Comment by korthout** [comment]
Sounds good to me, please announce it in the next team meeting @npepinpe

**Pull request closed without merging**
