### PR TITLE
chore(zb-db): extract shared db state into DbContext

### LINKED ISSUE #2184: Introduce RocksDb context for shared state
Create a DbContext in ZeebeState creation and pass it into the createColumnFamilies in ZeebeDb and stored it in the TransactionalColumnFamily. Context contains transaction object, key/value buffers, keyViewBuffer/valueViewBuffer, prefixBuffer, key/value instances. The ColumnFamily interface provides methods with and without the DbContext. The ones without context used the one stored on creation.

### PR DESCRIPTION
**Pull request by menski**
closes #2184

### CODE REVIEW

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
I have one thing maybe we discuss this f2f

**Comment by menski** [comment]
@Zelldon please see my latest commit

**Review by ChrisKujawa — APPROVED** [review]
thanks :+1:

**Pull request merged**
