### PR TITLE
chore(broker): replaces old workflow instance create with new

### LINKED ISSUE #2088: Replace WorkflowInstanceRecord#CREATE by new record type
Should wire the `CreateWorkflowInstanceCommand` to the newly introduced record type (see #2087) on the gateway side.

Related to #1852

### PR DESCRIPTION
**Pull request by npepinpe**
- replaces usage of the old WorkflowInstanceRecord based CREATE command with the new WorkflowInstanceRecordCreation CREATE command in broker
- refactors PartitionTestClient and related to use normal record classes to send commands, versus manually specifying them with a map
- minor cleanup and refactoring of test utils
- updates gateway request mapping
- test utility improvements

closes #2088, #2090

### CODE REVIEW

**Comment by npepinpe** [comment]
This is a pretty big PR imo for something that's actually not a lot; it's mostly refactoring tests, test utilities, etc. The "production" code portion of it is actually quite small (e.g. having the gateway send the right command).

Updating the client command will be done in a follow up issue, removing all traces of the old `WorkflowInstanceIntent#CREATE`, and exporting to elastic as well.

**Review by miguelpires — APPROVED** [review]
Looks good. You can also add the new record to the elastic search exporter. Unless you prefer to do that when you update it for the workflow instance record

**Comment by npepinpe** [comment]
There is a follow up issue to do this #2091

**Pull request merged**
