### PR TITLE
fix(protocol): remove producer id from record

### LINKED ISSUE #2621: Remove producer id from record

### PR DESCRIPTION
**Pull request by saig0**
BREAKING CHANGE:
- remove 'producerId' from record

closes #2621

### CODE REVIEW

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
There are still some producerId occurrences in the code base sorry :sweat_smile: 

[file.txt](https://github.com/zeebe-io/zeebe/files/3305151/file.txt)

**Comment by saig0** [comment]
@Zelldon, actually, this wasn't part of the issue :sweat_smile: So, you want to remove the producer id entirely?

**Comment by Zelldon** [comment]
Ah you're right, but yes would make sense or not?

**Comment by saig0** [comment]
I guess yes. Since there is only one steam processor left which writes to the log, the id is not really useful.

**Comment by Zelldon** [comment]
Ok :+1: do you want a separate issue for this or are you ok with doing this right now?

**Comment by saig0** [comment]
I'll do it in this PR. Let's give me a bit more time ;)

**Comment by saig0** [comment]
@Zelldon, it's too much. I'll open a new PR.

**Review by ChrisKujawa — APPROVED** [review]

**Pull request merged**
