### PR TITLE
Lock protobuf definition

### LINKED ISSUE #2734: Add protolock check to CI to prevent incompatible protobuf changes
https://github.com/salesforce/proto-backwards-compat-maven-plugin

### PR DESCRIPTION
**Pull request by menski**
closes #2734

### CODE REVIEW

**Comment by menski** [comment]
Seems to fail on jenkins, I will investigate it after the team meeting.

**Comment by menski** [comment]
@Zelldon I misconfigured the protocol location. Should be ready for review now. :shipit:

**Review by ChrisKujawa — APPROVED** [review]
Works :+1: :1st_place_medal: 

bors r+

**Pull request merged**
