### PR TITLE
feat(zb-db): replace the reflection RocksDB seek method calls with calls the RocksDB API with `ByteBuffer`

### LINKED ISSUE #3959: Migrate to new RocksDB ByteBuffer API
**Description**

With the merge of https://github.com/facebook/rocksdb/pull/2283, the next release of `rocksdbjava` will provide `ByteBuffer` based access to the APIs, allowing us to get rid of, if not all, most of the reflection we had to use to avoid re-allocating new buffers every time.

We should go through every use case and update accordingly, avoiding allocating/copying buffers wherever applicable.

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

I've just replaced the seek method calls with the `ByteBuffer` API. I'm just wrapping it in the `ByteBuffer` type and calling the `ByteBuffer` API. I'm not sure about any other calls but I can't find any other opportunities to replace reflection calls with `ByteBuffer` API calls.

Also I think that we should benchmark this but I don't know how to do it properly 😅

## Related issues

#3959.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by Zelldon** [comment]
Hey @aivinog1 thanks for your contribution :+1: sorry that I not have responded yesterday to your issue comment.

I think it is not quite what we want to have here. For example [zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/transaction/ForeignKeyChecker.java](https://github.com/camunda/zeebe/pull/9525/files#diff-e284cab074f455c4b31e51a8118485ebd70c34c42c45f1370465e21ae6174d5c) L93 `iterator.seek(ByteBuffer.wrap(prefix, 0, prefixLength));` still uses the byteArrary.

As far as I remember correctly we wanted to use direct buffers in our key and value classes and then use the new ByteBuffer API to avoid extra copies between the JNI. This means we wanted to remove the byte array usage completely. Does this make sense to you? and yes we also need to do some benchmarking here after the changes.

Let's wait for @npepinpe, maybe I'm wrong. Be aware that he is currently on vacation so it might take a while.

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Hey @aivinog1 thanks for your contribution :+1: sorry that I not have responded yesterday to your issue comment.

I think it is not quite what we want to have here. For example [zb-db/src/main/java/io/camunda/zeebe/db/impl/rocksdb/transaction/ForeignKeyChecker.java](https://github.com/camunda/zeebe/pull/9525/files#diff-e284cab074f455c4b31e51a8118485ebd70c34c42c45f1370465e21ae6174d5c) L93 `iterator.seek(ByteBuffer.wrap(prefix, 0, prefixLength));` still uses the byteArrary.

As far as I remember correctly we wanted to use direct buffers in our key and value classes and then use the new ByteBuffer API to avoid extra copies between the JNI. This means we wanted to remove the byte array usage completely. Does this make sense to you? and yes we also need to do some benchmarking here after the changes.

Let's wait for @npepinpe, maybe I'm wrong. Be aware that he is currently on vacation so it might take a while.

**Comment by aivinog1** [comment]
Thanks, @Zelldon! But I think that just removing the reflection part of the code makes me feel better 😅 But you're right let's wait for @npepinpe.

**Comment by Zelldon** [comment]
Agree might be a good first step forward. :+1:

**Review by npepinpe — CHANGES_REQUESTED** [review]
Agreed. The original issue is to make complete use of the ByteBuffer API, and see if using direct buffers would improve performance since there would not be any JNI copy involved (AFAIK). RocksDB is a big chunk of the engine performance, so :crossed_fingers: 

Anyway, it's a good first step to get rid of the reflection - ideally we can get rid of all reflection one day.

:x: That said, please extract the creation of the buffers as variable declarations to highlight that we are creating an object instead of just passing them through, especially in the case of the `for` loop, e.g.:

```java
for (iterator.seek(ByteBuffer.wrap(prefixKey, 0, prefixLength));
```

Should be:

```java
final ByteBuffer bufferView = ByteBuffer.wrap(prefixKey, 0, prefixLength);
for (iterator.seek(bufferView);
```

**Comment by Zelldon** [comment]
@aivinog1 are you still interested in this PR and could you update it?

**Comment by aivinog1** [comment]
> @aivinog1 are you still interested in this PR and could you update it?

Hey, sorry, I was pretty busy :( Yep, I will update it ASAP

**Comment by aivinog1** [comment]
@Zelldon @npepinpe Done. Can you take a look at this, please? :)

**Comment by Zelldon** [comment]
Hey @aivinog1 thanks for updating the PR, as described before it is not really what we wanted to achieve with this issue, but since it is replacing at least the reflection I'm willing to merge it. 

I set up a benchmark and will see how it performs.

**Comment by Zelldon** [comment]
| Weekly benchmark | Current PR |
|---------------------------|-----------------|
|medic|bytebuffer|

Looks good from my side. At the begin there were some hickups where I was a bit unsure but it seems like infrastructure related. 

I think we can merge it then, thanks @aivinog1 

bors r+

**Review by ChrisKujawa — APPROVED** [review]
bors r+

**Comment by Zelldon** [comment]
@npepinpe I guess you have to accept

**Review by npepinpe — APPROVED** [review]
bors merge

**Comment by korthout** [comment]
bors merge

**Pull request merged**
