### PR TITLE
fix: Adapting the code since a bug fix from the opensearch

### PR DESCRIPTION
**Pull request by KarpovIvan**
java client (#13522)

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Review by grlimacan — APPROVED** [review]
LGTM!

**Comment by oleksandr-kriuchenko-lohika** [comment]
And Event* files as far as I understand are removed from monorepo, right?

**Comment by OmranAbazid** [comment]
> Should this also be merged to `master`?

This is already merged to master in the optimize repo. 

If you mean main, then I do not mind doing that as well

**Review by oleksandr-kriuchenko-lohika — APPROVED** [review]

**Comment by RomanJRW** [comment]
> This is already merged to master in the optimize repo.
> 
> If you mean main, then I do not mind merging directly to main.

I did mean master, I got confused. Please ignore 🙈

**Pull request merged**
