### PR TITLE
Fix CI build

### PR DESCRIPTION
**Pull request by miguelpires**
## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

Let's revert it for now

**Comment by Zelldon** [comment]
What is the issue?

**Comment by MiguelPires** [comment]
https://github.com/zeebe-io/zeebe/issues/3511#issuecomment-566531024

**Pull request merged**
