### PR TITLE
Enable priority election by default

### LINKED ISSUE #8236: Enable priority election by default
**Description**

By default priority election is disabled. I would propose to enable it by default. If we enable it now, we have enough time to test it before the next release. As of now, I don't see any risk in enabling it.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Switches two flags to enable priority election by default and updates the configuration template that we distribute.

## Related issues

closes #8236

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I'm wondering now if we should also mark it as non-experimental if it's on by default?

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Comment by deepthidevaki** [comment]
> I'm wondering now if we should also mark it as non-experimental if it's on by default?

Good question. /cc @menski or @npepinpe

**Comment by menski** [comment]
My personal opinion is that it seems this option has proven to be valuable and by switching it to the default I wouldn't see it anymore as an experimental flag.

**Comment by deepthidevaki** [comment]
Thanks @menski 

@oleschoenburg My suggestion is to merge this PR. And we can do another PR to move the flag to a non-experimental section. We don't have a non-experimental section for Raft yet. So this might need a bit of discussion where to add this flag.

**Pull request merged**
