### PR TITLE
Remove remainings of job and topic subscription

### LINKED ISSUE #1564: Remove topic and job subscription related from protocol
depends on #1560
depends on #1563
depends on #1377

### PR DESCRIPTION
**Pull request by ChrisKujawa**
* did also a bit clean up

closes #1564

### CODE REVIEW

**Comment by menski** [comment]
@Zelldon based on the Jenkins logs it seems that exporters are broken with this change. Could you please look into this? Thanks

**Comment by Zelldon** [comment]
@menski should be fixed now

**Comment by menski** [comment]
I don't really like the for loop in the lookup as we do that for every record on the stream. Why don't we use a static lookup and also remove the custom values there?

```
public class IntentTest {

  enum FooBar {
    ONE,
    TWO,
    THREE;

    static final FooBar[] VALUES = FooBar.values();

    short value() {
      return (short) ordinal();
    }

    static FooBar getValueFor(short value) {
      return VALUES[value];
    }
  }

  @Test
  public void test() {

    final FooBar one = FooBar.ONE;
    final FooBar two = FooBar.TWO;
    final FooBar three = FooBar.THREE;

    assertThat(FooBar.getValueFor(one.value())).isEqualTo(FooBar.ONE);
    assertThat(FooBar.getValueFor(two.value())).isEqualTo(FooBar.TWO);
    assertThat(FooBar.getValueFor(three.value())).isEqualTo(FooBar.THREE);
  }
}
```

**Comment by Zelldon** [comment]
I would really like to do that. I discussed that really often with @saig0 . He is against this approach to depend on the ordinals (i think because of backwards compatibility? Problems with ordering etc.) Anyhow I would like to remove the terrible switch cases.

**Comment by menski** [comment]
I'm not a Java expert but `ordinal()` and `values()` is defined in the Java spec so I would assume it is stable. I would still prefer a switch over the for loop.

**Comment by Zelldon** [comment]
> I'm not a Java expert but ordinal() and values() is defined in the Java spec so I would assume it is stable.

I'm not sure what you mean with this, but ordinal depends on the order of the Enum instances.

Switch case is harder to maintain then the for loop. But ok I will revert my changes.

**Comment by Zelldon** [comment]
@menski please see new commit

**Review by menski — APPROVED** [review]
bors r+

**Pull request merged**
