### PR TITLE
Replace LGTM with CodeQL

### LINKED ISSUE #8137: LGTM does not support Java 17
**Description**

LGTM does not support Java 17: https://lgtm.com/help/lgtm/java-extraction
This blocks us in upgrading modules to language level 17. There are multiple ways to go forward:

* Halt migration to Java 17.
* Disable LGTM temporarily
* Migrate to CodeQL

The first two options are suboptimal because LGTM appears to not be actively maintained anymore.

Migrating to [CodeQL](https://codeql.github.com) would be ideal because it offers superior integration with GitHub, for example issues found by CodeQL show up in the Security tab in GitHub. Integrating CodeQL seems fairly simple, there is an official action: https://github.com/github/codeql-action

relates to #8096

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Adjusts CodeQL to not check generated sources and removes the LGTM config file.

## Related issues

relates to #8144
closes #8137

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I've tested introducing a code quality issue and CodeQL correctly flagged it with severity 'note'.

@npepinpe I've removed the LGTM config file but we still have to disable the integration in the repository settings. I don't seem to have the permissions to do this.

**Comment by npepinpe** [comment]
@oleschoenburg where can I see what it flagged? I see only green builds of this action :thinking:

**Comment by oleschoenburg** [comment]
I removed the commit that introduced this to get it ready to merge and I didn't take a screenshot 🙃 Should I do it again so you can see it?

**Comment by npepinpe** [comment]
I believe you if you just tell me how it works :smile: Is it showing up as a review comment here, or under the line in particular, or you have to look at the action, or...?

**Comment by oleschoenburg** [comment]
It's showing up here: 
Screenshot 2021-11-05 at 09 39 41

Under "Code scanning results / CodeQL" it shows "1 new alert" but the checkmark is still green because the severity is 'note'

**Comment by oleschoenburg** [comment]
For higher severities it should look like this: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/triaging-code-scanning-alerts-in-pull-requests?learn=security_alerts&learnProduct=code-security#viewing-an-alert-on-your-pull-request

**Review by npepinpe — APPROVED** [review]
Looks good to me. Nice catch on the generated sources :+1: Though I wonder if we might want to apply only security queries on the generated code eventually. Not sure how flexible the action is.

**Comment by npepinpe** [comment]
Regarding permissions, I can look if I have them - if LGTM is set up at the org level though, then I won't be able to do anything about it :smile:

**Comment by npepinpe** [comment]
I don't have the permissions to change our LGTM integration, I guess that's something only @menski can do.

**Comment by npepinpe** [comment]
BTW, wouldn't this close #8144? What would close it?

**Comment by oleschoenburg** [comment]
You are right, it closes https://github.com/camunda-cloud/zeebe/issues/8137. As soon as @menski removes the LGTM integration this is done.

**Comment by menski** [comment]
I removed the LGTM integration from the GitHub org

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
