### PR TITLE
[Backport 8.1] Corrolate message directly with batch processing

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
Backports https://github.com/camunda/zeebe/pull/11549
Backports https://github.com/camunda/zeebe/pull/11805

## Related issues

closes https://github.com/camunda/zeebe/issues/11494

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
@Zelldon The CodeQL alert looks legit, maybe we should just fix that here.

**Comment by Zelldon** [comment]
:warning: 

Before we merge this, we should fix #11848 on main. If this is the case then we can backport the changes from this PR, from https://github.com/camunda/zeebe/pull/11805 and the fix of #11848 


\cc @oleschoenburg I will postpone the backporting until we have the fix. Otherwise, we have a bug in the next patch release, if we haven't fixed it before.

**Comment by Zelldon** [comment]
:warning: @oleschoenburg I will merge the other fix https://github.com/camunda/zeebe/pull/11805 into this backport PR, so we have both combined. 

Before we merge the backport to 8.1, I think it makes sense to first fix https://github.com/camunda/zeebe/issues/11848 on main. We can backport this fix as well, otherwise we have this bug related to publish message and direct correlation also on 8.1. Right now on 8.1 this issues is only for job completion and process instance creation with result.

**Comment by Zelldon** [comment]
Add https://github.com/camunda/zeebe/pull/11805 commits to this backport PR.

**Comment by Zelldon** [comment]
I updated this PR, had to fix some imports and removed some dead code. Maybe you can quickly check whether everything is fine before we merge it @oleschoenburg

**Review by lenaschoenburg — APPROVED** [review]
Looks good as far as I can tell :+1: 

bors r+

**Pull request merged**
