### PR TITLE
refactor(snapshots): Replace `Stream.toList` and the for each cycle to `Stream.forEachOrdered`

### LINKED ISSUE #12575: Improve the traversing of snapshot files
**Is your feature request related to a problem? Please describe.**

I think that it is not a good idea to collect snapshot files in the list. 
Check it here: https://github.com/camunda/zeebe/blob/02d1df8ac1b6f5484f1e9d4c1f19c8a5712176b1/snapshot/src/main/java/io/camunda/zeebe/snapshots/impl/SnapshotChecksum.java#L41. 
Because, after a while, the amount of snapshot files should grow. So, we could instead call the `.forEachOrdered` method to calculate the snapshot. I will provide the PR soon to see this in action and benchmark this.

**Describe the solution you'd like**
We should call `Stream.forEachOrdered` instead of collecting snapshots `File`s in the list.

**Describe alternatives you've considered**
We could use `Stream.forEach` but as I can understand the order is important, so we shouldn't do this.

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

I replaced the collection with a list and the for each cycle to the `Stream.forEactOrdered` call. It should reduce memory footprint and possibly improve latency, especially on a large number of snapshot files.

## Related issues

closes #12575 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by aivinog1** [comment]
Hello, reviewer! 
First of all, this should be benchmarked with a large number of snapshot files, so that we could see the difference in the memory and snapshot creation latency.
Then, it should be nice to backport this in the 8.0, 8.1, and 8.2 as well.

**Review by deepthidevaki — APPROVED** [review]
:rocket: Thanks @aivinog1 for your contribution. 

Since this is reasonable change irrespective of performance improvement, I'm merging this without running a benchmark. You would see a difference only with large number of snapshot files anyway.

bors r+

**Comment by deepthidevaki** [comment]
Smoke test failed.

bors retry

**Comment by deepthidevaki** [comment]
@aivinog1 backport workflow is running. Please assign it to me when the backport PRs are created.

**Comment by aivinog1** [comment]
> @aivinog1 backport workflow is running. Please assign it to me when the backport PRs are created.

@deepthidevaki It failed (I think because I drop my branch, but I just restored it now), could you restart the workflow, please? 🙂 Or check out what went wrong.

**Comment by deepthidevaki** [comment]
Let's try again.

/backport

**Pull request merged**
