### PR TITLE
Fix release pipeline after JDK 17 upgrade

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

This should unblock the release of 1.3.0-alpha1.

Adding `add-opens` is a workaround for [OSSRH-66257] and [NEXUS-26993]. Because we don't control the plugin ourselves and instead inherit it from camunda-release-parent we can't just add a dependency overwrite
as suggested in [OSSRH-66257].

[OSSRH-66257]: https://issues.sonatype.org/browse/OSSRH-66257
[NEXUS-26993]: https://issues.sonatype.org/browse/NEXUS-26993

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I haven't tested this yet but the comments on OSSRH-66257 suggest that this will work. Because the release job is built from develop I think there is no way to tests this on our Jenkins without merging to develop first. Correct me if I'm wrong here @npepinpe. If that's true I'd suggest to just merge this and retry the 1.3.0-alpha1 release.

**Comment by npepinpe** [comment]
Since the issue here is that one plugin, do you think we can just try running it? I understand it might fail because of missing variables, but maybe without this fix it won't even run at all?

**Review by npepinpe — COMMENTED** [review]
:question: Can you elaborate on why this workaround as opposed to the one which was to update the plugin's xstream dependency?

**Comment by oleschoenburg** [comment]
>Can you elaborate on why this workaround as opposed to the one which was to update the plugin's xstream dependency?

I briefly touched on this here: 

> Because we don't control the plugin ourselves and instead inherit it from camunda-release-parent we can't just add a dependency overwrite as suggested in OSSRH-66257.

but to elaborate: I wasn't able to upgrade the transitive dependency on xstream. Overwriting the version had no effect but maybe I just didn't find the right place to do this properly.

**Review by pihme — APPROVED** [review]
lgtm

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
