### PR TITLE
Add randomized test for dataloss scenario

### LINKED ISSUE #9837: Extend `RandomizedRaftTest` with snapshot and data loss operations
[Recent issues](https://github.com/camunda/zeebe/issues/9820) with snapshots have highlighted a need to improve test coverage. We can extend the `RandomizedRaftTest` by adding additional operations for taking snapshots and for losing data.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Add restart with dataloss to the set of input operations in randomized raft tests. The operations ensures that we can only inject data loss of one node at a time. It waits until the restarted node have recovered and caught up before proceeding with the other operations. 

This PR also adds additional verification to ensure that there is no dataloss, by keeping track of committed entries and verifying that it is not overwritten.

## Related issues

closes #9837

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:rocket: 

I have to admit I got a little stuck on the data loss check, and how just checking for inconsistencies (e.g. an entry with same index different terms) was enough to ensure we didn't have data loss. I don't really know where we would write out the thought process. Maybe it's also obvious to others, just not to me :sweat_smile: 

The only case I could imagine that wouldn't be caught is on complete cluster data loss, where we start again at 1,1, but we have other conditions which should prevent this from being successful.

**Comment by deepthidevaki** [comment]
> The only case I could imagine that wouldn't be caught is on complete cluster data loss, where we start again at 1,1, but we have other conditions which should prevent this from being successful.

I have updated to PR to keep track of checksum of the entries and use that to verify instead of term.

**Comment by deepthidevaki** [comment]
bors merge

**Comment by oleschoenburg** [comment]
bors r-

```
Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 33.903 s <<< FAILURE! - in io.atomix.raft.RandomizedRaftTest
Error:  io.atomix.raft.RandomizedRaftTest.consistencyTestAfterDataLoss(List,List, long)  Time elapsed: 1.753 s  <<< FAILURE!
```

https://github.com/camunda/zeebe/actions/runs/4165692793/jobs/7209049602

**Comment by deepthidevaki** [comment]
Merging this is blocked by https://github.com/camunda/zeebe/issues/11665

**Comment by deepthidevaki** [comment]
bors merge

**Pull request merged**
