### PR TITLE
refactor: replace Tasklist's Process Entity and Index

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

* Ensure that the old Tasklist Importer (8.6.0) continues to import to the "old" Tasklist Process Index
* Ensure that the old Tasklist Importer (8.7.0) imports to the harmonized Process Index (so that Tasklist ITs continues to run)
* Separate between `operateProcessIndex` and `tasklistProcessIndex` beans to ensure that the old backend gets the expected beans autowired with the expected configurations

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

related to #24665

### CODE REVIEW

**Comment by romansmirnov** [comment]
@panagiotisgts, after checking the `process-migration` runner, I think the (deprecated) `TasklistProcessIndex` - which is used by the 8.6 import processor - is actually not required. Could you confirm? If so, I could delete it.

**Comment by panagiotisgts** [comment]
@romansmirnov Correct, from 8.7 Tasklist will be based on the `operate-process` index and importing will be handled by Operate's 8.6 process importer.

**Comment by romansmirnov** [comment]
@panagiotisgts, thanks! Okay, then I will delete that `TasklistProcessIndex` - I somehow assumed it must continue to write in the old `tasklist-process` index to ensure the migration can happen. But I got it now. I will quickly adjust it.

**Comment by panagiotisgts** [comment]
The initial approach was to use the `tasklist-process` index to read records from, but since the two indices contain the same records, we decided to do the migration on the `operate-process` index alone and get rid of the Tasklist one.

**Comment by romansmirnov** [comment]
Deleted the `TasklistProcessIndex` and the entity in an additional commit. Locally, everything works. Let's see what the CI tells 😄

**Review by panagiotisgts — APPROVED** [review]
LGTM. I've just rerun the Operate E2E for sanity check, even though it has been flaky of late.

**Pull request merged**
