### PR TITLE
feat(broker): unify lifecycle of flow elements

### LINKED ISSUE #1939: Single lifecycle for all workflow elements
When processing a workflow instance, different flow nodes have different lifecycles; while this is more efficient in terms of event throughput on the logstream, it creates a more complicated mental model of the actual workflow processing, and introduces more points of failure in terms of cleanup (e.g. do not create garbage in the state db), initialization, etc. Additionally, this greatly simplifies the implementation of #1911, which is the trigger for this, and simplifies the event stream for third party consumers.

The goal here is to unify the lifecycle of all flow nodes in order to simplify the state machine that is our workflow engine.

The initial proposal is to use the following lifecycle:

lifecycle 4

Generally, each flow node would follow the same logic (and according to its type hierarchy, modify the step with additional business logic):

### ELEMENT_READY

Conceptually implies the token has reached the flow node, but it is not yet active; any steps that can fail *before* the business logic of the node is executed should be performed here (e.g. applying input mappings, extracting correlation keys, etc.)

### ELEMENT_ACTIVATED

Conceptually implies the token has reached the flow node successfully (i.e. not errors in the input mappings, for example), and the flow node is now active.

### EVENT_OCCURRED

This is an optional phase, as not every flow node can subscribe to events. For those that can (e.g. catch events, activities, event gateways, etc.) this would be published whenever the subscribed event has occurred, with the payload and flow node target transmitted as a deferred token to the element which subscribed to the event.

### ELEMENT_COMPLETING

Perform any post-activation steps, such as applying output mappings, unsubscribing from events, etc.

### ELEMENT_TERMINATING

Similar as above, but in the case of termination; for example, here activities would not apply output mappings.

### ELEMENT_COMPLETED

Cleanup phase (ensure no garbage left in state, unsubscribe from events, etc.), and take outgoing step.

### ELEMENT_TERMINATED

Cleanup phase as well, and propagate termination.

Each phase will most likely vary slightly depending on the flow node type, but ideally it should be similar enough that we can create an homologous handler hierarchy, and in that way have less point of failures when it comes to things such as unsubscribing from events, or leaving garbage records in the state db.

### PR DESCRIPTION
**Pull request by npepinpe**
- introduces a new event scope state which is used to communicate between workflow instance processing and other event processors
- new architecture for processing workflow instance: instead of defining element agnostic steps, we tie the processing to the lifecycle and element type, e.g. `ActivityElementReadyHandler` is the handler to use for an activity (or a sub-type) element during its `ELEMENT_READY` phase
- every flow node now creates an element instance with potentially its own variable/event scope
- update payload propagates its variables at the moment even if targeting a child element
- moves step guards to the actual handlers, since these should respect the lifecycle/type hierarchy

closes #1939

### CODE REVIEW

**Comment by npepinpe** [comment]
There is still a lot more work to be done after this PR to get everything in line, let's discuss it first and then I will write follow up issues.

**Review by menski — CHANGES_REQUESTED** [review]
In like the changes. One thing I would like to do before merging is getting rid of all these todo comments. Let us sit together and decide if we need an issue for them or which we can already resolve. Also I struggled to parse the meaning of the `boolean` return value of `handleState` while reviewing the code, maybe we can have a small discussion again how we could improve this.

**Review by menski — APPROVED** [review]

**Comment by menski** [comment]
bors retry

**Pull request merged**
