### PR TITLE
Fix flaky ProcessingScheduleServiceTest

### LINKED ISSUE #10306: Tasks scheduled via the ProcessingScheduleServiceImpl are sometimes not executed
**Describe the bug**

This issue came from working on the following PR https://github.com/camunda/zeebe/pull/10289. The test added in `ProcessingScheduleServiceTest` sometimes fails because the second scheduled task simply is not executed. It happens very seldom (1 out of 500 times more or less), and I haven't pin pointed yet where the cause is. I can confirm it's not related to the timer wheel, as the `TimerSubscription#onTimerExpired` is _always_ called. The question is why the actor job is not executed.

**To Reproduce**

Run `ProcessingScheduleServiceTest#shouldPreserveOrderingOfWritesEvenWithRetries` in a loop. It fails eventually where there is only one event on the log, because the second task never executed.

**Expected behavior**

All tasks are eventually executed.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

The timers need to be scheduled in a different order, otherwise, we get issues with the execution and the clock adjustment, see https://github.com/camunda/zeebe/issues/10306#issuecomment-1250895527

Enable the test again

## Related issues

closes https://github.com/camunda/zeebe/issues/10306

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by Zelldon** [comment]
@npepinpe do you remember how often it failed or how likely it was?

I run it now multiple times 
tests

**Review by npepinpe — APPROVED** [review]
:+1: 

I wonder how we could detect very long GC pauses on CI and report them, that'd probably be useful when dealing with flaky tests :thinking:

**Comment by Zelldon** [comment]
> I wonder how we could detect very long GC pauses on CI and report them, that'd probably be useful when dealing with flaky tests ￼

Maybe writing the gc log and also exporting that as an artifact? :thinking: :man_shrugging:

**Comment by oleschoenburg** [comment]
On the last merge, running unit tests for the dispatcher crashed the VM: 
[hs_err_pid1970.log](https://github.com/camunda/zeebe/files/9605118/hs_err_pid1970.log)

**Comment by Zelldon** [comment]
okaay :shrug: I haven't changed anything there.

**Comment by Zelldon** [comment]
See https://github.com/camunda/zeebe/issues/10407

bors r+

**Pull request merged**
