### PR TITLE
fix: do not complete multi-instance before all child element batches has been activated

### LINKED ISSUE #12918: NullPointerException in ActivateProcessInstanceBatchProcessor.createChildInstanceRecord
**Describe the bug**

NPE is thrown when creating instance of process with multiinstance and a large input collection. 

Instance is created:

```
2023-05-31 14:41:06.222  INFO 36794 --- [pool-6-thread-1] i.c.cloud.gameday.ProcessApplication     : Created process instances with large collection. [order-id: '7c7014f4-16fe-4609-9ef2-d017546416af']
```

But can't be executed. 
[It looks like the instance get banned.](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.namespace_name%3D%2229c46b01-ab7a-4b96-9262-10a28257dfe5-zeebe%22%0Aresource.labels.pod_name:%22zeebe-%22%0A-resource.labels.container_name%3D%22zeebe-analytics%22%0A-resource.labels.container_name%3D%22zeebe-gateway%22;timeRange=2023-05-31T11:29:31.241992Z%2F2023-05-31T13:36:09.546Z;pinnedLogId=2023-05-31T12:36:40.822878656Z%2F8qiahd3sixyvvbf4;cursorTimestamp=2023-05-31T12:36:40.822878656Z?project=camunda-saas-int-chaos)

**To Reproduce**

Follow https://github.com/camunda-cloud/game-day-cookbook/tree/main/mains/large-multi-instance and change 

```diff
--- a/mains/large-multi-instance/src/main/java/io/camunda/cloud/gameday/ProcessApplication.java
+++ b/mains/large-multi-instance/src/main/java/io/camunda/cloud/gameday/ProcessApplication.java
@@ -49,15 +49,15 @@ public class ProcessApplication implements CommandLineRunner {
   public void run(final String... args) {
     final var executor = Executors.newSingleThreadScheduledExecutor();
     executor.scheduleAtFixedRate(
            () -> createInstanceOfProcess(10), 1, 30, TimeUnit.SECONDS);

     executor.scheduleAtFixedRate(
         () -> {
-          final var orderId = createInstanceOfProcess(20_000);
+          final var orderId = createInstanceOfProcess(2_000_000);
           LOG.info("Created process instances with large collection. [order-id: '{}']", orderId);
 
-        }, 5, 15, TimeUnit.MINUTES);
+        }, 0, 15, TimeUnit.MINUTES);
   }

          final var orderId = createInstanceOfProcess(2_000_000);
```

**Expected behavior**

Correct batching and not failing of creating such instance, or if possible rejection.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.state.instance.ElementInstance.getValue()" because "parentElementInstance" is null
	at io.camunda.zeebe.engine.processing.processinstance.ActivateProcessInstanceBatchProcessor.createChildInstanceRecord(ActivateProcessInstanceBatchProcessor.java:66) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.engine.processing.processinstance.ActivateProcessInstanceBatchProcessor.processRecord(ActivateProcessInstanceBatchProcessor.java:45) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:142) ~[zeebe-workflow-engine-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:346) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$2(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:84) ~[zeebe-db-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:268) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:227) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.readNextRecord(ProcessingStateMachine.java:203) ~[zeebe-stream-platform-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:92) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) [zeebe-scheduler-8.2.5.jar:8.2.5]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) [zeebe-scheduler-8.2.5.jar:8.2.5]

```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version: 8.2.x
- Configuration: G3-S

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description
Right now, a multi-instance with a big input collection could be marked as completed mistakenly if a portion of it's child elements has been completed before one or some of the next batches has been activated. 
This results in `NullPointerException` when activated the `delayed` batches, because it can't find the parent anymore (as it has been prematurely completed)

In this fix, I'm introducing two new intents for the `ProcessInstanceBatch`: `ACTIVATING` and `ACTIVATED`

Once we start processing the multi-instance child elements, I write to the state that the `ProcessInstanceBatch` is `ACTIVATING`, and I only transition it to `ACTIVATED` once there are no more children to activate. I'm using these events then to signal this fact in the multi-instance body element instance state.

In the BpmnStateBehavior, I'm then changing the logic to reject completing a multi-instance body if its state indicates it's still `ACTIVATING`.

## Related issues

closes #12918

### CODE REVIEW

**Review by ana-vinogradova-camunda — COMMENTED** [review]
LGTM 🚀  Great work, thank you, @mustafadagher

**Review by ana-vinogradova-camunda — APPROVED** [review]

**Comment by megglos** [comment]
@mustafadagher what's blocking the merge?

**Comment by mustafadagher** [comment]
> @mustafadagher what's blocking the merge?
> 
> Edit: got it, the missing test, right?

Yes, I discussed it in two previous team meetings that I'd not feel confident merging this without a test, and testing it is very tricky. Today, I'm meeting with Nico and we shall try to have a go at it, and either hopefully come up with something or decide to take the risk and merge it as is.

**Comment by mustafadagher** [comment]
I believe the fix in https://github.com/camunda/camunda/pull/21442 also solves this problem. I will tentatively close this one after merging the other. We can then verify if it works using the suggestion form @Zelldon to reproduce using https://github.com/camunda-cloud/game-day-cookbook/tree/main/mains/large-multi-instance and change

**Comment by mustafadagher** [comment]
fixed in https://github.com/camunda/camunda/pull/21442

**Pull request closed without merging**
