### PR TITLE
ci: use 8 core runners to build operate and tasklist

### PR DESCRIPTION
**Pull request by lenaschoenburg**
There are more 4 core runners available and they should be fast enough.

### CODE REVIEW

**Comment by megglos** [comment]
the problem we have is 4 cores are already used by e2e up to a cap of 10 so effectively we may only have 10 runners as well as with the 16 core ones :/ It should be better on average at least
image

**Comment by Zelldon** [comment]
@megglos @oleschoenburg does something speak against using the aws runners? To better distribute our load?

**Comment by megglos** [comment]
> @megglos @oleschoenburg does something speak against using the aws runners? To better distribute our load?

happy to try

**Review by cmur2 — APPROVED** [review]
Based on what I read about the max parallelization possible due to the Maven module structure (probably less than 10, def not 16) this makes sense to me.

**Pull request merged**
