### PR TITLE
feat: enable export of process instance creation by default

### PR DESCRIPTION
**Pull request by menski**
## Description

To be able to track the usage of the start process anywhere feature in zeebe analytics we need to export the creation to elasticsearch.

## Related issues

related to https://github.com/camunda/zeebe-analytics/issues/73

### CODE REVIEW

**Review by pihme — APPROVED** [review]
lgtm :tada:

**Comment by remcowesterhoud** [comment]
@menski we have this documented in some places which we should also update since the default is changed:

- https://github.com/camunda/zeebe/blob/main/dist/src/main/config/broker.standalone.yaml.template#L557
- https://github.com/camunda/zeebe/blob/main/dist/src/main/config/broker.yaml.template#L494
- https://github.com/camunda/zeebe/blob/main/exporters/elasticsearch-exporter/README.md?plain=1#L197

**Comment by menski** [comment]
@remcowesterhoud thanks for pointing out, I will adjust these examples

**Pull request merged**
