### PR TITLE
Reduce NettyMessagingServiceTest duration by 3x

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR reduces the total time of the `NettyMessagingServiceTest` class from (locally) ~30s down to ~10s. It does so by grouping the tests in nested classes, which avoids having to start 5 or more service instances for every test when most tests use one or two service instances.

Based on/blocked by #14839.

## Related issues

related to #14837 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
The tests themselves are the same, just moved around, but the teardown/setup of the service instances has changed.

**Comment by npepinpe** [comment]
@rodrigo-lourenco-lopes let me know if you don't have time

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
Sorry for the delay, I hadn't noticed this in my inbox 😬 
This is a great improvement! LGTM 🙌

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
