### PR TITLE
chore(es-exporter): export JobRecordBatch

### LINKED ISSUE #1495: Add JobBatchRecord to Elasticsearch Exporter
Allow Elasticsearch Exporter to export `JobBatchRecord` records.

### PR DESCRIPTION
**Pull request by npepinpe**
closes #1495

### CODE REVIEW

**Comment by menski** [comment]
So this breaks the ZeebeObjectMapper tests, expected, which might break the deprecated topic subscription stuff. What about we create an own object mapper for the exporter. And just delete the ZeebeObjectMapper once we got rid of the old client?

**Comment by npepinpe** [comment]
Let's do that. It should be a small enough change I can do it today, but if you can't wait then go ahead and do it.

**Comment by menski** [comment]
I will fix it and merge it

**Review by menski — APPROVED** [review]
bors r+

**Pull request merged**
