### PR TITLE
chore(gateway): do not log resource exhausted on gateway

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
The log was flooded by the Gateway due to the Resource Exhausted exceptions/responses. This PR avoids to log theses exceptions.

### CODE REVIEW

**Comment by deepthidevaki** [comment]
There could be one problem if we remove this logging. If no jobs were activated the client's response doesn't have any information why jobs were not activated. Is it because there were no jobs available or the request was rejected due to backpressure? Logging it on the gateway would probably at least give some indication what is going on. What do you think?

**Comment by Zelldon** [comment]
Can we send then the failed request to the client? With other requests we do that right?

**Comment by deepthidevaki** [comment]
I agree that its quite annoying :smile: We cannot send it back to client like other requests because we retry the request with other partitions. We will have to collect errors from the responses from all partitions and send it back to the client. It would make it more complicated.

**Review by deepthidevaki — APPROVED** [review]
As we discussed, we can remove the logs for now. In future we can probably find a better way to convey what is happening if we didn't activate any jobs. :+1:

**Comment by Zelldon** [comment]
Thanks @deepthidevaki :+1:

**Comment by deepthidevaki** [comment]
bors retry

**Comment by Zelldon** [comment]
Bors r+

**Pull request merged**
