### PR TITLE
Move theme files

### PR DESCRIPTION
**Pull request by jwulf**
`mdbook serve` complains about the location of the theme files. This commit resolves its complaint.

### CODE REVIEW

**Comment by menski** [comment]
I guess you are using a newer version of mdbook. Could you check which version you have installed. In the CI we use a patched version to add some links to the source code inside the docs. We could think about updating to the latest mdbook version.

**Comment by npepinpe** [comment]
Can we close this PR? @jwulf

**Comment by menski** [comment]
I'm in the process of upgrading the docs to the latest mdbook version and will incorporate these changes.

**Comment by menski** [comment]
for reference #3345

**Pull request closed without merging**
