### PR TITLE
chore(spotless): adhere to formatting

### PR DESCRIPTION
**Pull request by megglos**
## Description

Noticed the errors on backport PRs, is there something off in the release commands? @npepinpe

### CODE REVIEW

**Comment by npepinpe** [comment]
Wouldn't we have noticed it in the release PR though? We couldn't have merged it, right?

**Review by npepinpe — APPROVED** [review]
:+1: 

bors merge

**Comment by npepinpe** [comment]
I still don't get how it would've gotten merged in the first place, though :thinking:

**Comment by npepinpe** [comment]
So the Java check job is taking > 20 minutes? :thinking:

**Comment by npepinpe** [comment]
Should we just merge this directly? It's blocking all the others.

**Comment by megglos** [comment]
shall we just merge this one manually to fix the CI for all pending ones?

**Comment by npepinpe** [comment]
I give you my blessing :pray:

**Pull request merged**
