### PR TITLE
[Backport 8.0] Trigger boundary events after an interrupting event subprocess is triggered

### PR DESCRIPTION
**Pull request by saig0**
## Description

Backport of #9175

## Related issues

relates to #6874

### CODE REVIEW

**Comment by saig0** [comment]
:eyes: The build failed because of flaky exporter tests.

**Comment by saig0** [comment]
@pihme please accept the PR :sweat_smile: It is a pure backport of the original PR.

**Comment by npepinpe** [comment]
Sorry, it looks like I forgot to backport the fixes :see_no_evil:

**Review by pihme — APPROVED** [review]
bors merge

**Comment by saig0** [comment]
bors merge

**Comment by saig0** [comment]
bors merge

**Pull request merged**
