### PR TITLE
Remove legacy transition logic

### LINKED ISSUE #7912: Remove old transition logic code
**Description**

Remove feature flag and old transition logic code.

### PR DESCRIPTION
**Pull request by pihme**
## Description

Removes legacy transition logic.

## Review hints
* There is one commit where I removed the tests for the old implementation. Let me know if you think I removed a valuable test case
* Maybe we merge everything but the last commit. I am on my laptop today and it feels like it doesn't have the same settings for rearranging code. And it looks like this made the commit more complex. I could also redo it on my other PC again
* I did try to go a bit further and get rid of `PartitionStartupAndTransitionContextImpl`, but this got complicated very fast. I would rather work on this in multiple future PRs and have some discussions before.

## Related issues

closes #7912 

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks. Looks good to me. :+1:

It formatted differently on my system. Please re-format it. Otherwise everything looks good.

**Comment by pihme** [comment]
@deepthidevaki Reformatted it on my main machine. Hope it is now in line with your formatting :-)

**Review by deepthidevaki — APPROVED** [review]
:rocket:

**Comment by pihme** [comment]
bors merge

**Pull request merged**
