### PR TITLE
refactor: use rest endpoint as default for QA tests

### LINKED ISSUE #22536: Replace zbctl usage in `zeebe-testbench` workflow with equivalent REST API call
Replace usage of zbctl in https://github.com/camunda/camunda/blob/main/.github/workflows/zeebe-testbench.yaml#L84
with:
```
      - name: Start Test
        shell: bash
        run: |
          token=$(curl --request POST ${ZEEBE_AUTHORIZATION_SERVER_URL} \
            --header 'Content-Type: application/x-www-form-urlencoded' \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "audience=zeebe.camunda.io" \
            --data-urlencode "client_id=${ZEEBE_CLIENT_ID}" \
            --data-urlencode "client_secret=${ZEEBE_CLIENT_SECRET}" \
            | jq -j ".access_token")

          variables=$(echo "${{ inputs.variables }}" | envsubst)

          curl -L -X POST "${ZEEBE_ADDRESS}/v2/process-instances" \
            -H "Authorization: Bearer ${token}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            --data-raw "{
              \"bpmnProcessId\": \"${{ inputs.processId }}\",
              \"variables\": $variables
            }"
        env:
          ZEEBE_CLIENT_SECRET: ${{ steps.secrets.outputs.TESTBENCH_PROD_CLIENT_SECRET }}
          ZEEBE_ADDRESS: ${{ steps.secrets.outputs.TESTBENCH_PROD_REST_ADDRESS }}
          ZEEBE_AUTHORIZATION_SERVER_URL: 'https://login.cloud.camunda.io/oauth/token'
          ZEEBE_CLIENT_ID: 'Jg9caDRuAWHchvM7JiaVlndL-qVFfp~0'
```
Once the testbench cluster is updated to 8.6.0.

### PR DESCRIPTION
**Pull request by nicpuppa**
## Related issues

closes #22536

### CODE REVIEW

**Comment by megglos** [comment]
will resolve https://github.com/camunda/camunda/issues/22536

**Review by megglos — APPROVED** [review]
LGTM! Weird that you couldn't use the http request action for the Start Test though 🤷

**Comment by nicpuppa** [comment]
@megglos there is an error in this action, even if the workflow runs successfully, the ZEEBE_IMAGE provided is wrong.

**Review by megglos — APPROVED** [review]
LGTM!

**Pull request merged**
