### PR TITLE
docs: update with new repository name

### LINKED ISSUE #18797: Zeebe source code refers to old repository name
**Description**

While working on #18206 @Zelldon and I realized that [replacing all usages](https://github.com/camunda/camunda/issues/18797) of the old URL https://github.com/camunda/zeebe leads to test failures in Zeebe due to assumed backwards incompatible changes (in Java annotations). We deferred this change as out-of-scope of the actual repository rename since it needs work by the Zeebe team to adjust the source code and the backwards compatibility checks for that.

Usages: https://github.com/search?q=repo%3Acamunda%2Fcamunda+%22github.com%2Fcamunda%2Fzeebe%22&type=code

Please remove all usages of `github.com/camunda/zeebe` and replace them with `github.com/camunda/camunda` in Zeebe source code.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR updates all references of the old repository name (`zeebe`) to the new repository name (`camunda`).

## Related issues

closes #18797

### CODE REVIEW

**Comment by Zelldon** [comment]
Last time we did this we got issues with api checks :)

**Comment by npepinpe** [comment]
I can fix that ezpz, but I think the PR can still be approved ;)

**Review by tmetzke — APPROVED** [review]
👍 A quick local check yielded the same 29 occurrences, good from my side
If we run into CI issues as @Zelldon mentioned, let's fix it afterward.

**Comment by npepinpe** [comment]
CI should break now, but honestly these are test annotations, so I don't think it would break anything 🤔

**Comment by tmetzke** [comment]
I'll add a comment to https://github.com/camunda/camunda/issues/18445 for the failing flaky test.

**Pull request merged**
