### PR TITLE
[Backport stable/8.0] Backport journal structural updates

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR backports the structural updates made to the journal in #9714, #9731, #9833, and #9834. This is to ease backporting further fixes to the journal, as the structure deviating so much caused major issues when backporting new fixes.

## Related issues

backports #9714
backports #9731
backports #9833
backports #9834

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
I will backport this to 1.3 after, as that should be much easier.

**Review by lenaschoenburg — APPROVED** [review]
I _think_ this looks good but I'm not really confident that my review was very thorough.

**Comment by npepinpe** [comment]
Since tests pass, the worst case scenario here would be having backported something that shouldn't have been backported.

I'm not aware of any changes that we did which could break compatibility in any way recently, so I think this is mostly safe. WDYT?

**Comment by oleschoenburg** [comment]
I agree, I think it's safe to merge this :+1:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
The old error where the JVM cannot fork :disappointed: 

bors r+

**Comment by npepinpe** [comment]
:drum: Will the backport succeed?

**Comment by npepinpe** [comment]
Lol only one commit failed to be cherry picked :shrug:

**Pull request merged**
