### PR TITLE
fix(clients/go): fix concurrency bug in cache access

### LINKED ISSUE #3161: Latent concurrency bug in cache access
**Describe the bug**
Currently the credentials cache implementation in the Go client only locks writes. However, a concurrent reads and writes can cause panics

**To Reproduce**
```
func TestConc(t *testing.T) {
	cachePath := copyCredentialsCacheGoldenFileToTempFile()
	cache, _ := NewOAuthYamlCredentialsCache(cachePath)
	goroutines := 1000000

	wg := sync.WaitGroup{}
	wg.Add(goroutines)

	for i := 0; i < goroutines; i++ {
		go func(i int) {
			wg.Done()
			if i%2 == 0 {
				err := cache.Update("randomKey", nil)
				if err != nil {
					panic(err)
				}
			} else {
				_ = cache.Get("randomKey")
			}
		}(i)
	}

	wg.Wait()
}
```

**Expected behavior**
Thread-safe access to cache

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: [e.g. 0.20.0]
 - Configuration: [e.g. exporters etc.]

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Fixes a concurrency bug in the Go client's caused by unsynchronized reads
## Related issues

closes #3161

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by MiguelPires** [comment]
bors +

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
