### PR TITLE
chore(broker): clarify ways to specify config file

### LINKED ISSUE #4976: Default settings ignored when using SPRING_CONFIG_LOCATION
**Describe the bug**

When using the environment variable `SPRING_CONFIG_LOCATION` then the internal configuration in `application.properties` is ignored. 

This is bad, because without the internal configuration, no metrics are available.

This is also bad, because at various places it is recommended to use this environment variable.

**Expected behavior**
Change documentation and examples to either not use this environment variable, or to explain how to use it properly

**Environment:**
 - Zeebe Version: > 0.23

### PR DESCRIPTION
**Pull request by pihme**
## Description

* Reduces instructions in config templates
* Clarifies instruction in documentation to also include the classpath when using `SPRING_CONFIG_LOCATION`

## Related issues

closes #4976

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [will be done after approval] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [X] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
Looks good :+1: 

Should we also mention the `SPRING_CONFIG_ADDITIONAL_LOCATION`? This is what I typically use instead of appending things to `SPRING_CONFIG_LOCATION`.

**Comment by pihme** [comment]
I'm fine either way. Let me know what you prefer.

**Comment by npepinpe** [comment]
I would recommend using `SPRING_CONFIG_ADDITIONAL_LOCATION` as the usual way of configuring Zeebe, unless you see any downsides that I'm unaware of with this.

**Comment by pihme** [comment]
So maybe I am overthinking this.

I would prefer to use naming conventions and use `application.yml` + `ENV_VARS` to configure Zeebe. I would rather not talk about the other ways that configuration could be passed in.

The one issue I have with using `SPRING_CONFIG_ADDITIONAL_LOCATION`, in particular, is when the user wants to configure a standalone gateway. If the user specifies `SPRING_CONFIG_ADDITIONAL_LOCATION=../mygatewayconfig.yml` then the resolution will be
* `../mygatewayconfig.yml` - gateway config; explicitly specified
* `application.yaml` - broker config; chosen due to Spring defaults
* `application.properties` - broker + gateway config; chosen due to Spring defaults

The bit I don't like is that when I specify an additional configuration, then all the default configurations still apply. And at least `application.yml` is a configuration for the broker. 

That currently doesn't do any harm if I want to overwrite it with a gateway configuration. But personally, I find it confusing.

But, as I said, maybe I am overthinking this. So I will follow your decision on the subject.

**Comment by npepinpe** [comment]
Regarding the gateway, imo the real solution here is to have a different deliverable. As for the rest, I would also always advise to modify the configuration via environment variables. But if a user wants to use configuration files, then they should do so via the additional location, as (and correct me if I'm wrong) if you use the standard `SPRING_CONFIG_LOCATION` then none of our defaults apply, resulting in missing actuator routes, for example.

If I understand correctly, your proposal would be to omit any mention of overwriting the config location (additional or not) and focus solely on environment variables? Given this, what would an experienced Spring user think of this? Would they try setting the config location? Then again, as an experienced Spring user they might know to use the additional location to avoid this. Could we add in the docs simply a note mentioning the dangers of overwriting the defaults, e.g.

> NOTE: if you wish to use a configuration file instead of environment variables, either overwrite the default `application.yaml` or specify an additional configuration file via `SPRING_CONFIG_ADDITIONAL_LOCATION`. Using `SPRING_CONFIG_LOCATION` has a downside of overwriting all application defaults, which may disable certain features. Use at your own risk.

**Comment by pihme** [comment]
I rephrased it. I hope it is clearer now.

Could you reread it again? Sorry to bother you, but it is just too hot now. I found two typos rereading it myself, but I guess there are more to be found  🙈

**Review by npepinpe — APPROVED** [review]
Looks great like this :+1:

**Pull request merged**
