### PR TITLE
fix(snapshot): do not include term when comparing snapshotId

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

#14509 had another consequence that since the term is reset, no new snapshots can be taken until the term increases to a higher value than the one before the backup. As a result, logs are not compacted and disk usage grows high. One can prevent this if they use the version with the bug fix when restoring from a backup. But if not, there is no easy way to recover from this once it has happened. Upgrading to version won't help recovering from it. So as a solution, I propose not to include "term" in the snapshot Id comparison. Term and index is fixed to the same log entry. So if one changes the other one also change. So it is enough to use index to order the snapshot ids. 

## Related issues

related #14509

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Exactly, so the node with the "older" snapshot would assume it has a newer one, and...I guess always reject new snapshots? Never take any? Not sure to be honest :thinking:

**Comment by deepthidevaki** [comment]
Yes. But isn't that the case even now when term is included in the comparison?

**Comment by npepinpe** [comment]
That's true :smile:

**Review by npepinpe — APPROVED** [review]
:+1: LGTM

**Pull request merged**
