### PR TITLE
feat: highlight executed compensation associations

### LINKED ISSUE #19567: I can see highlighted associations related to executed compensation events
### User Story

```Gherkin
Scenario: As an Operate user
    Given I am in instance details view
    When The process instance has an executed compensation event
    Then The related association will be highlighted with a blue color (same as for sequence flows)
```

image

### Designs
[Figma](https://www.figma.com/design/2iYV26UW5TwEhU4LooOCMF/Better-visualization-of-the-executed-path?node-id=1100-55763&t=MgdB8QPfonRNRNaw-1)

### Acceptance Criteria

- [ ] The association is highlighted when the related compensation event is in _completed_ state
- [ ] The association is **not** highlighted when the compensation event is in any other state (_running,_ _incident_, _canceled_, ...)
- [ ] The highlight color is aligned with the color of other executed elements
- [ ] Dark and light mode colors are considered

### Definition of Ready - Checklist

- [ ] The issue has a meaningful title, description, and testable acceptance criteria
- [ ] If documentation needs to be updated, an issue is created in the [camunda-docs](https://github.com/camunda/camunda-docs) repo, and the issue is added to our Operate project board.
- [ ] If HELM charts need to be updated, an issue is created in the [camunda-platform-heml](https://github.com/camunda/camunda-platform-helm) repo, and the issue is added to our Operate project board.
- [ ] Potential Security risks have been considered and added to the product-hub issue risk assessment
- [ ] Cross-team dependencies have been considered

Optional:
- [ ] Design input has been collected by the assignee
### :point_right: Handover Dev to QA 

- Handy resources: 
     BPMN/DMN models, plugins, scripts, REST API endpoints + example payload, etc : 
     
- Example projects:

- Versions to validate:
> Docker file : in case that it needed to be tested via docker share the version contain the fixed along with version of other services . 

- Release version ( in which version this fixed/feature will be released)

### PR DESCRIPTION
**Pull request by pedesen**
## Description

- Split up processInstance.mocks.ts into separate files for each mock (this causes the big changeset in the first commit)
- Add compensationAssociations to processInstanceDetailsDiagramStore (including test)
- Provide compensationAssociationIds to highlightedSequenceFlows prop of Diagram component
- Add visual regresstion test for a compensation process

## Related issues

closes #19567

### CODE REVIEW

**Review by vitorwtavares — APPROVED** [review]

**Comment by pedesen** [comment]
@gastonpillet01 Please use this docker image: `registry.camunda.cloud/team-operate/camunda-operate:branch-fe-19554-highlighted-compensation-associations`

**Comment by gastonpillet01** [comment]
@pedesen - I see a execution count badge with number 16 in the processes list when I filter by completed.
Is that the expected behaviour for compensation events?
image

**Comment by pedesen** [comment]
> I see a execution count badge with number 16 in the processes list when I filter by completed.
> Is that the expected behaviour for compensation events in this screen?
@gastonpillet01 This looks like a bug. I'll take a look tomorrow

**Comment by pedesen** [comment]
@gastonpillet01 It should be fixed now, could you check again?

**Review by gastonpillet01 — APPROVED** [review]
Executed compensation associations correctly highlighted.

**Comment by pedesen** [comment]
@Szik Please test using this image: `registry.camunda.cloud/team-operate/camunda-operate:branch-fe-19554-highlighted-compensation-associations`

**Review by Szik — APPROVED** [review]

**Pull request merged**
