### PR TITLE
chore(ci): restrict build history to 3 for every branch except master/develop/stage

### PR DESCRIPTION
**Pull request by hawky-4s-**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6e009a39b5f66136403c6d882e4ca4edd1660b5b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by npepinpe — CHANGES_REQUESTED** [review]
I guess the go changes were unintended?

**Comment by hawky-4s-** [comment]
Yeah, I am cleaning up the PR. Sorry, noticed it too late.

**Review by npepinpe — APPROVED** [review]

**Comment by hawky-4s-** [comment]
This change should be put on all branches if possible to restrict the disk usage.

**Pull request merged**
