### PR TITLE
Release 1.2.2

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR merges the commits related to the 1.2.2 release, notably preparing the branch for the next release.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by pihme — COMMENTED** [review]
Looks good for the most part.

The one file that bothers me is `.gocompat.json`. Since this is a Java release, I don't exactly see why this file needs to be changed. Or maybe it is a joint Java + Go release and the change is warranted? Or maybe nothing has changed and it is just reformatted differently?

Could you please check whether this change originated from the Java release?

**Comment by npepinpe** [comment]
Sorry, I was sick and then this completely slipped off my radar.

**Comment by npepinpe** [comment]
I compared a semantic difference between the two (i.e. load both as JSONObject and compare if they are the same, regardless of ordering), and it turns out they are. So it looks like it was just re-ordered, which is admittedly inconvenient for these PRs. I'll look into it, but I don't think it's a blocker for this now.

**Review by pihme — APPROVED** [review]

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
