### PR TITLE
refactor: replace camunda.operate.multiTenancy.enabled by camunda.security.multiTenancy.enabled

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

Replaces the use of `io.camunda.operate.property.MultiTenancyProperties` class by `io.camunda.security.configuration.MultiTenancyConfiguration`.

For backward compatibility `camunda.security.multiTenancy.enabled` property is set with `camunda.operate.multiTenancy.enabled` when Operate runs in Standalone mode. (this is done in https://github.com/camunda/camunda/pull/25684)

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

relates to https://github.com/camunda/camunda/issues/20455
depends on https://github.com/camunda/camunda/pull/25684

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
Looks good to me comparing it to similar recent changes regarding this.
An additional review from an Operate engineer would be helpful here though in my regard to check any Operate intricacies I may not be aware of.

**Comment by houssain-barouni** [comment]
> Looks good to me comparing it to similar recent changes regarding this. An additional review from an Operate engineer would be helpful here though in my regard to check any Operate intricacies I may not be aware of.

thanks for the review, I requested @camunda/operate-backend for a second review

**Review by sdorokhova — APPROVED** [review]
LGTM!
Timy thing: could you please adjust [this docker-compose](https://github.com/camunda/camunda/blob/a0bbb78814bdf13009c087a6d2aee58e1b406af1/operate/config/docker-compose.mt.yml#L141C26-L141C50) that our QA use to test multi-tenancy?

**Comment by houssain-barouni** [comment]
> LGTM! Timy thing: could you please adjust [this docker-compose](https://github.com/camunda/camunda/blob/a0bbb78814bdf13009c087a6d2aee58e1b406af1/operate/config/docker-compose.mt.yml#L141C26-L141C50) that our QA use to test multi-tenancy?

I see that the docker compose still uses 8.6.6 which does not contain the new parameter
anyway, 8.7 is backward compatible with the old parameter so it should continue to work

**Pull request merged**
