### PR TITLE
chore(project): final everywhere

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

As discussed in one of the the last team meeting, we go with finals everywhere.

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:tada:

**Comment by Zelldon** [comment]
Adding finals seem to break the actor scheduler. I will take a look tomorrow

**Comment by npepinpe** [comment]
Looks good, strange that the `LogStreamTest` is failing...I assume the Sonar stuff is because it flagged a lot of old code as new now?

**Review by npepinpe — APPROVED** [review]
I can reproduce the failing test on develop so looks good :+1:

**Pull request merged**
