### PR TITLE
 build: make optimize releasable from the monorepo

### PR DESCRIPTION
**Pull request by misiekhardcore**
## Description

This PR contains changes required to make Optimize releasable from the monorepo
Branch related to this PR is used as a "main" branch in the release configuration, so the changes can be tested without any interference with the repo main branch,

### CODE REVIEW

**Comment by OmranAbazid** [comment]
I suggest squashing this into two commits: one for the footer version change and one for the workflow changes

**Review by OmranAbazid — APPROVED** [review]
pre-approving, I think we also need @buccarel approval here.

**Comment by misiekhardcore** [comment]
@buccarel if you think it can be merged already to `migrate-optimize-in` then pleas merge it

**Review by buccarel — APPROVED** [review]
LGTM

**Pull request merged**
