### PR TITLE
fix(broker): fix OOM on restart

### LINKED ISSUE #4927: Back port to 0.23.x - OOM Error on restart
**Describe the bug**
The bug is described in in #4871

The bug fix needs to be ported to 0.23.x

### PR DESCRIPTION
**Pull request by pihme**
## Description

Back port bug fix for #4871 

## Related issues

closes #4927

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [X] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release annoncement

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Comment by Zelldon** [comment]
@pihme do we have pr's for the other versions? Maybe this solves the issue for https://github.com/zeebe-io/zeebe/pull/4937

**Comment by pihme** [comment]
@Zelldon PRs for develop and 0.24 are already merged; 0.23 is pending; No PRs for versions <0.23

**Comment by pihme** [comment]
bors retry

**Comment by Zelldon** [comment]
@pihme ok thanks then this will not solve our current issue :D

**Comment by Zelldon** [comment]
Bors r+

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7b1b435a966746a81e1c333ef90a549ba4813cc4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by pihme** [comment]
bors retry

**Pull request merged**
