### PR TITLE
fix(renovate): add missing colon to message prefix

### PR DESCRIPTION
**Pull request by megglos**
## Description

This was missing and violating https://github.com/camunda/zeebe/blob/main/CONTRIBUTING.md/#commit-message-header

## Related issues

relates to #14701

### CODE REVIEW

**Comment by megglos** [comment]
@rodrigo-lourenco-lopes commitlint was failing, I think this was the cause, see https://github.com/camunda/zeebe/actions/runs/6812932487/job/18526398704?pr=15108

**Comment by megglos** [comment]
alternatively we could ignore commit messages fro mrenovate like done for dependabot  🙈 
https://github.com/camunda/zeebe/blob/main/commitlint.config.js#L7

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
Thanks for the fix!

**Comment by rodrigo-lourenco-lopes** [comment]
bors merge

**Comment by megglos** [comment]
bors merge

**Pull request merged**
