### PR TITLE
feat(monitoring): add dashboard for daily medic check

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Add json file for [dashboard](https://grafana.dev.zeebe.io/d/AzsO1mUnk/zeebe-medic-benchmarks?orgId=1&refresh=30s).

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
Thanks :+1: 
:medal_military: :gift_heart:

**Comment by deepthidevaki** [comment]
bors merge

**Comment by Zelldon** [comment]
bors cancel

**Comment by Zelldon** [comment]
We first need https://github.com/camunda/zeebe/pull/11332 to get merged

**Pull request merged**
