### PR TITLE
Allow nullable variable in Protocol Jackson

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

I've followed by instructions here: https://immutables.github.io/immutable.html#nulls-in-collection.

1. Created new annotation to match situations where is needed nullable values in the collection.
2. Use annotation where is applicable.
3. Created test cases to verify the fix.

## Related issues

#9382 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
We've greatly changed protocol-jackson with 8.x to make it easier to maintain and more portable. The module doesn't include the immutable objects but instead just describes how to deserialize them (as they are serialized as beans). Keep in mind protocol-jackson is not yet part of the public API, as we're still figuring out the right API.

This change will have to be forward ported I assume. When forward porting, I would hope we can keep annotations to a minimum and instead we can maybe find a way through the style or general configuration.

**Comment by aivinog1** [comment]
Hey @npepinpe! The problem isn't exists on the 8.0.2 version, I've tested it :) 
So, I think, only tests will be forward ported, to be sure that we will not break it in the future :)

**Review by saig0 — APPROVED** [review]
@aivinog1 LGTM :+1: 
Thank you for proving a fix :cookie:

**Comment by aivinog1** [comment]
Hey @saig0! May I ask when this will be merged and released? :)

**Comment by oleschoenburg** [comment]
I think that was just a case of forgetting to:
bors merge

**Comment by oleschoenburg** [comment]
The backport action does not seem to work on PRs from forks anymore so we'll have to manually backport. /cc @saig0

**Comment by saig0** [comment]
@aivinog1 Oups :sweat_smile: Thanks for the reminder :+1:

**Pull request merged**
