### PR TITLE
Move GatewayStreamer ownership to engine

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR moves the generic `GatewayStreamer` API from the stream platform to the engine module, and flattens it into a `JobStreamer` API. This allows the engine to describe the contract that it needs in terms of job streaming capabilities. To align on this, the streamer is now passed directly via the `TypedRecordProcessorFactory` instead of in the more general stream platform builder, such that the platform is unaware of it.

In general, this greatly simplifies usage of the API, but more importantly it _moves ownership of this API to the ZPA team_. The ZDP team then provides adapters between this and the more generic `RemoteStream` API.

## Related issues

related to #12043

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by koevskinikola — COMMENTED** [review]
I did a quick review of the refactoring. It looks good, thanks for the ping!

**Review by deepthidevaki — APPROVED** [review]
:100: I like it. I think now we have a clearer separation between the platform and engine.

I have fixed the javadoc. Otherwise all looks good.

bors r+

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
Flaky test https://github.com/camunda/zeebe/issues/12130 

bors retry

**Pull request merged**
