### PR TITLE
[Forwards main]: Simplify log polling

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Forwards https://github.com/camunda/zeebe/pull/15229

Same as https://github.com/camunda/zeebe/pull/15283

### CODE REVIEW

**Comment by npepinpe** [comment]
One test fails with the following error: 

>  Caused by: org.springframework.boot.web.server.PortInUseException: Port 1198 is already in use

:thinking:

**Comment by Zelldon** [comment]
Same as https://github.com/camunda/zeebe/pull/15283#issuecomment-1821144420

**Comment by Zelldon** [comment]
@npepinpe can you check the PR if you have time

**Review by npepinpe — APPROVED** [review]
bors merge

Sorry, I did check it last time, I guess I only approved the other one =/

**Pull request merged**
