### PR TITLE
Fix dangling resources and potential flakiness

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes some flakiness around temporary directories not being deleted in the journal, by ensuring we always close all resources before a test ends.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
I'd also taken 10-15 minutes to write up a Junit extension for this closing stuff, but then I figured it's too much black magic and hard to handle properly (e.g. what gets closed first), so it feels a little overengineered imo. I'm not including it in the PR, but leaving it here in a comment for posterity in case anyone ever thinks it would be useful:

<details><summary>AutoClose.java</summary>

```java
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Zeebe Community License 1.1. You may not use this file
 * except in compliance with the Zeebe Community License 1.1.
 */
package io.camunda.zeebe.test.util.junit;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/** Fields annotated with this extension will be automatically closed once tests are finished. */
@Target({ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface AutoClose {}
```

</details>

<details><summary>AutoCloseExtension.java</summary>

```java
/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH under
 * one or more contributor license agreements. See the NOTICE file distributed
 * with this work for additional information regarding copyright ownership.
 * Licensed under the Zeebe Community License 1.1. You may not use this file
 * except in compliance with the Zeebe Community License 1.1.
 */
package io.camunda.zeebe.test.util.junit;

import static org.junit.platform.commons.util.AnnotationUtils.findAnnotatedFields;
import static org.junit.platform.commons.util.ReflectionUtils.makeAccessible;

import io.camunda.zeebe.util.VisibleForTesting;
import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.Collection;
import java.util.function.Predicate;
import org.agrona.CloseHelper;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.ExtensionContext.Namespace;
import org.junit.jupiter.api.extension.ExtensionContext.Store;
import org.junit.platform.commons.util.ReflectionUtils;

/**
 * A lightweight junit5 extension to help ensure your resources are closed automatically at the end
 * of a test.
 *
 * <p>To use, register the extension in your test class, e.g.
 *
 * <pre>{@code
 * @ExtendWith(AutoCloseExtension.class)
 * final class MyTest {
 *   @AutoClose private final MyCloseable = new MyCloseable();
 * }
 * }</pre>
 *
 * You can then annotate fields (both static and not) with the {@link AutoClose} extension. Doing so
 * will ensure this extension will call close on those fields at the end.
 *
 * <p>Any type can be marked as {@link AutoClose}, but only the following will get closed:
 *
 * <ul>
 *   <li>Types which implement {@link AutoCloseable}
 *   <li>Types implementing {@link Collection}
 *   <li>Arrays
 * </ul>
 *
 * For arrays and collections, the logic above holds recursively. For example, if you have a
 * collection of objects which all implement {@link AutoCloseable}, then these objects will be
 * closed individually. If your collection type directly implements {@link AutoCloseable}, then only
 * that object is closed. If your collection contains other collections which contain {@link
 * AutoCloseable}, then these nested {@link AutoCloseable} will be closed.
 *
 * <p>Static fields are closed after all tests are finished in a class. Instance fields are closed
 * after every test.
 */
public final class AutoCloseExtension implements BeforeEachCallback, BeforeAllCallback {
  @VisibleForTesting static final Namespace NAMESPACE = Namespace.create(AutoCloseExtension.class);

  @Override
  public void beforeAll(final ExtensionContext context) {
    storeStaticFields(context, context.getRequiredTestClass());
  }

  @Override
  public void beforeEach(final ExtensionContext context) {
    context
        .getRequiredTestInstances()
        .getAllInstances() //
        .forEach(instance -> storeInstanceFields(context, instance));
  }

  private void storeStaticFields(final ExtensionContext context, final Class<?> testClass) {
    storeFields(context, null, testClass, ReflectionUtils::isStatic);
  }

  private void storeInstanceFields(final ExtensionContext context, final Object instance) {
    storeFields(context, instance, instance.getClass(), ReflectionUtils::isNotStatic);
  }

  private void storeFields(
      final ExtensionContext context,
      final Object testInstance,
      final Class<?> testClass,
      final Predicate<Field> predicate) {
    final var store = context.getStore(NAMESPACE);
    final var annotatedFields = findAnnotatedFields(testClass, AutoClose.class, predicate);

    annotatedFields.forEach(
        field -> store.put(getStoreFieldKey(field), new CloseableField(testInstance, field)));
  }

  private String getStoreFieldKey(final Field field) {
    return field.getName() + "-" + (ReflectionUtils.isStatic(field) ? "static" : "instance");
  }

  private record CloseableField(Object testInstance, Field field)
      implements Store.CloseableResource {

    @Override
    public void close() throws Throwable {
      final Object value = makeAccessible(field).get(testInstance);
      closeObject(value);
    }

    private void closeObject(final Object value) {
      if (value instanceof AutoCloseable auto) {
        CloseHelper.quietClose(auto);
      } else if (value instanceof Collection<?> c) {
        c.forEach(this::closeObject);
      } else if (value.getClass().isArray()) {
        final var array = (Object[]) value;
        Arrays.stream(array).forEach(this::closeObject);
      }
    }
  }
}
```

</details>

**Review by lenaschoenburg — APPROVED** [review]
Thanks! I literally already had a branch open with changes to the reader test but you were faster and more thorough :rocket:

**Comment by npepinpe** [comment]
I ran into it and it seemed small enough to just fix it instead of bothering anyone about it :smile:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors retry

**Comment by deepthidevaki** [comment]
Should this be backported?

**Comment by npepinpe** [comment]
Oh, was async segment creation backported?

**Comment by deepthidevaki** [comment]
Not yet backported. But we are planning to. Is this depending on async creation?

**Comment by npepinpe** [comment]
Not per se, but it depends on another PR from Ole which was added due to async creation, where the tests were modified. So we should backport that one first. Do we have a place to track this maybe? So we can backport them in order.

**Pull request merged**
