### PR TITLE
chore(exporters/elasticsearch-exporter): add test cases for HTTPS connections

### LINKED ISSUE #1990: Export to a secure Elasticsearch cluster
Both #1992 and #1993 should be implemented for this to be closed. Maybe #1994 too, to be discussed.

AT:

- Zeebe can export to an Elasticsearch exporter over HTTPS

### PR DESCRIPTION
**Pull request by npepinpe**
closes #1990

### CODE REVIEW

**Comment by npepinpe** [comment]
A few (horrible) notes, mostly due to testing with self-signed certs (and most being solved if we ever manage to use `TestContainers`):

- The `allegro/embedded-elastic` library doesn't support a health check for Elastic using HTTPS, so there's a horrible try/catch to workaround that...
- The custom `trustStore` contains the Elastic certificate so that we can download the tar ball; I guess it would be nice to have the tar prepackaged in the image, but I think we use shared images for CI? For local dev machines this isn't a huge problem since typically you'd download it once per-reboot.
- Can't run directly from the IDE without specifying `javax.net.ssl.trustStore` and so on :man_shrugging:

**Comment by bsideup** [comment]
Hi @npepinpe!

> if we ever manage to use `TestContainers`

Anything we (Testcontainers) can help with? Do you have some blockers, or just need to find time to try it? 🤓

**Comment by npepinpe** [comment]
Hi @bsideup, thanks for offer! The biggest blocker for us is that we plan on moving our CI to a k8s orchestrated setup, and we aren't sure how well `TestContainers` will work with this (primarily based on this discussion https://github.com/testcontainers/testcontainers-java/issues/1135). Admittedly we haven't tried it yet either.

**Review by menski — APPROVED** [review]
bors r+ :closed_lock_with_key: :+1:

**Comment by bsideup** [comment]
@npepinpe Testcontainers does not support Kubernetes **API** but works absolutely fine if your build agents are orchestrated with k8s and expose Docker daemon (either with a socket mounted or docker-in-docker mode)

**Comment by menski** [comment]
bors retry

**Pull request merged**
