### PR TITLE
Symlink `.idea` folder for `zeebe` subfolder

### PR DESCRIPTION
**Pull request by korthout**
## Description

It's annoying to open the mono repo in IntelliJ when working only on Zeebe. I prefer to work in the `zeebe` subfolder. However, that means that all the shared idea settings are not available.

By symlinking the .idea folder users that open the zeebe subfolder in IntelliJ will have all the same settings as the mono repo, without having to duplicate the settings.

This change does not affect anyone that works from the mono repo in IntelliJ.

This PR adds a soft symlink created using:
```sh
cd zeebe
ln -s ../.idea .idea
```

## Related issues

None

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
It might not work with windows, but not sure whether Zeebe engineers use windows I think linux/mac is more common in this area. :)

So lets fix it if it turns to be an issue. LGTM 👍🏼 :shipit:

**Comment by nicpuppa** [comment]
> It might not work with windows, but not sure whether Zeebe engineers use windows I think linux/mac is more common in this area. :)
> 

@tmetzke 🙃

**Comment by tmetzke** [comment]
I am working with the mono repo, so 🤷 
I can give it a try with a new Zeebe-only workspace.

**Comment by mustafadagher** [comment]
Nice idea @korthout !
Did you try a scenario where you change the `editorconfig` or some other idea configs while you're on the zeebe subfolder. what would be the outcome?

**Comment by korthout** [comment]
>Did you try a scenario where you change the editorconfig or some other idea configs while you're on the zeebe subfolder. what would be the outcome?

@mustafadagher I haven't tested this, but I expect that it works just like the rest. In the Zeebe subfolder project, you'll have the exact same settings as in the mono repo.

**Comment by korthout** [comment]
Seems that our CI is unstable. Let's retry that once, otherwise I'll wait until it stabalizes.

**Pull request merged**
