### PR TITLE
feat(gateway) Enabled gateway to contact cluster in an async way 

### LINKED ISSUE #1124: Figure out how we want to test gateway
With the current setup, there is a lot of mocking involved. Maybe we can find a better strategy to do/improve testing there.

AC

* Come up with a strategy on how to test all endpoints on the gateway
* Current tests are adjusted to this strategy

### LINKED ISSUE #1164: The gateway should send async requests to brokers
At the moment the gateway blocks on the response future of it's broker requests.
https://github.com/zeebe-io/zeebe/blob/f29b68f0bd7f70c5ad7f68d4029ab755567a3900/gateway/src/main/java/io/zeebe/gateway/EndpointManager.java#L47

AT:
- the gateway uses async requests and completes the grpc call if the future is completed

### PR DESCRIPTION
**Pull request by jsam**
- use actor scheduler to send a response after the cluster request finished
- remove ZeebeFuture abstraction
- encapsulate ZeebeClient in ClusterClient to ease mocking tests
- remove custom mocks and use RecordingStreamObserver for verification
- Improved endpoint manager to use actor scheduler and contact cluster in an async way.
- Improved and simplified the way we test endpoints and response mapper

closes #1164 
closes #1124

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 7c61a6027f8dca33b37a437ea229e1cfe1d7d33b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5ec9550a79f36c516660a377b949b0e3ecae0d0f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by menski** [comment]
@jsam can you please fix the failing test cases and after that assign someone for review. Thanks.

**Comment by menski** [comment]
I extracted the change required in the request manager in #1217 and added a test case how we want to use the client from the gRPC gateway code. We will facilitate these changes in a following pull request which also addresses the testing issue #1124.

**Pull request closed without merging**
