### PR TITLE
Add topology operation for force reconfiguring a partition

### LINKED ISSUE #16226: Add `TopologyChangeOperation` to force configure partitions

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

To support orchestrating force removal of members from a partition, in this PR we add a new `PartitionForceReconfigureOperation`.  This operation takes the members of the new configuration as the input. After applying this operation, the members which are not in the configuration should not be part of the partition anymore. To reflect that, their state in the topology is updated by removing the partition. 

Unlike other operations, the member that applies this operation can update the state of another member because this is a "force" operation. This was not possible before because `TopologyChangeApplier` interface restricts that the member that applies the change can update only its own state. To allow updating states of other members, this interface is refactored to add two different types of applier - `ClusterOperationApplier` and `MemberOperationApplier`. All old operations implements `MemberOperationApplier`. 

## Related issues

closes #16226 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by deepthidevaki** [comment]
:bell: @npepinpe in case you missed the notification.

**Comment by npepinpe** [comment]
I'm in the middle of reviewing it :sweat_smile:

**Review by npepinpe — APPROVED** [review]
:rocket: 

Sorry it took so long, I'm still getting used to the new module. I would normally try to trace the execution of the operation, but that's not yet possible :upside_down_face:

**Comment by deepthidevaki** [comment]
> I would normally try to trace the execution of the operation, but that's not yet possible

:upside_down_face: Ya. Let me know if you would like to discuss before reviewing such PRs.

**Pull request merged**
