### PR TITLE
Refactor ElasticsearchClient unit tests

### LINKED ISSUE #9330: Refactor client's unit to focus on the client's reduced responsibilities

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR refactors the `ElasticsearchClient` unit tests to cover what the client is now responsible for: flushing and flushing logic, and communication with Elastic.

This removes one unit tests which was previously in `ElasticsearchClientIT`, and removes the `ElasticsearchExporterFlushTest`, which are now simply nested in `ElasticsearchClientTest`.

## Related issues

closes #9330 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
I think the CodeQL stuff can be ignored for this review as it's just repeating the existing alerts (for some reason) :thinking:

**Comment by npepinpe** [comment]
Now there's a flaky update test, but I don't see how this PR would have affected it.

**Review by saig0 — APPROVED** [review]
@npepinpe nice :+1: LGTM :rocket:

**Comment by saig0** [comment]
bors merge

**Comment by npepinpe** [comment]
Some flaky tests related to containers running out of memory :(

bors retry

**Comment by npepinpe** [comment]
Same issue again :(

Merging manually as bors is currently silent, and I'm pretty sure this PR did not affect the integration tests.

**Pull request merged**
