### PR TITLE
Deploy flattened POMs and reduce BOM to "public" modules

### LINKED ISSUE #8716: Deploy flattened POM for consumer modules
**Is your feature request related to a problem? Please describe.**

There are a few modules in the Zeebe project which are meant to be consumed by user's projects:

- `io.camunda:zeebe-client-java`
- `io.camunda:zeebe-bpmn-model`
- `io.camunda:zeebe-exporter-api`
- `io.camunda:zeebe-gateway-protocol-impl`
- `io.camunda:zeebe-protocol-jackson`

The projects are deployed as is, with their "development" POM - this POM includes development specific profiles, plugins, and relies on the centralized dependency management in `io.camunda:zeebe-parent` as well as properties substitution.

This causes a few problems:

1. Vulnerability issues introduced by transitive dependencies may re-appear in consumer's code. The Zeebe team scans these projects for security vulnerabilities, which are often remediated by updating transitive dependencies. The tools used to scan the whole project correctly resolve the dependencies to those specified in `io.camunda:zeebe-parent`, and thus assume there are no vulnerabilities. When a user introduces the library (such as `io.camunda:zeebe-client-java`) in their own project, however, without specifying versions for the transitive dependencies, these will get resolved based on the shortest path, which may be a version with security issues. While users should be expected to scan their own projects and fix vulnerability issues, this can still places an undue burden on them, and negates any effort we, the Zeebe team, did on that front.
2. There may be slight behavioral changes between the tests ran by the Zeebe team using specific versions of transitive dependencies and the actual dependencies automatically resolved in the user's project, which can cause unexpected behavior.

For both issues above, it's perfectly fine if these occur _when the user has explicitly overridden one of the dependency's versions_. But when that's not the case, then no such issues should appear in their projects.

**Describe the solution you'd like**

Use the [`flatten-maven-plugin`](https://www.mojohaus.org/flatten-maven-plugin/usage.html) to generate flat POMs for the projects above, and any other projects which is explicitly meant to be included in another project. This will not only trim down the POM to its minimum, making it often more readable, but it will solve both of the issues above.

**Describe alternatives you've considered**

We could fix the dependencies ourselves manually in the POM when security issues arise, however this sort of negates the benefits we gain from centralized dependency management and creates more busy work for the team.

**Additional context**

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR introduces the `flatten-maven-plugin`, which will flatten any hierarchy in a module's POM before it's deployed somewhere. The original POM will remain intact. The goal here is to simplify the integration of the modules in other people's projects, by making it more explicit which dependencies are pulled by the module, and which version they should be.

Additionally, the BOM is now reduced to only including these modules which were tailor explicitly to be consumed by third party projects. The goal with that is to make it explicit to users which modules they can safely rely on in their projects, and all the rest, so called internal modules, which may be renamed, changed, dropped, etc., and are only expected to be used in Zeebe. Note that they can still be imported in third party projects, but that is then at the user's risks.

## Related issues

closes #8716 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Comment by npepinpe** [comment]
I'm surprised this caused Spotbugs to flag something. I wonder why these changes would do that... :thinking:

**Comment by korthout** [comment]
> I'm surprised this caused Spotbugs to flag something. I wonder why these changes would do that... 🤔

Very strange indeed. I was able to reproduce it locally and did a quick git bisect run. It's clearly the commit that adds the flatten-pom plugin. I'm really not sure why this fails. Perhaps some dependency convergence?

```
git bisect good
e3f91e986b2f2a3f93f956cdfe1d18badf1acf4c is the first bad commit
commit e3f91e986b2f2a3f93f956cdfe1d18badf1acf4c
Author: Nicolas Pepin-Perreault <nicolas.pepin-perreault@camunda.com>
Date:   Wed Feb 23 19:02:41 2022 +0100

    build: flatten all POMs for deployment
```

**Comment by npepinpe** [comment]
But Spotbugs shouldn't pick up the flattened POM...right? I mean, I guess it does, but why? I thought the replacement of the POM was done during deploy? Possibly not...

**Comment by korthout** [comment]
The specific spotbugs match is already excluded by `feel/spotbugs/spotbugs-exclude.xml`, seems this is ignored now...

**Comment by korthout** [comment]
Found it! 🎉 

Please add this to `feel/pom.xml`

```xml
  <properties>
    <!-- ignore Spotbugs failures related to Scala classes -->
    <spotbugs.exclude>${basedir}/spotbugs/spotbugs-exclude.xml</spotbugs.exclude>
  </properties>
```

**Review by korthout — APPROVED** [review]
LGTM 👍 Nice work @npepinpe 🌵 

🔧 Considering that we discovered part of the problem because of the additional property set in `expression-language/pom.xml`, let's remove that `<spotbugs.exclude>${basedir}/spotbugs/spotbugs-exclude.xml</spotbugs.exclude>` line from there to simplify the spotbugs config. WDYT? Otherwise, I'd suggest to align the `feel/pom.xml` by adding the line there as well.

🔧 Since the BOM now nolonger contains versions of all zeebe modules, let's update the `bom/README.md`. It would also make sense to suggest here what this should be used for.

❓ You've mentioned that users should generally use the BOM to consume the modules, do you know of any places where we suggest this to users? AFAIK, docs.camunda.io does not refer to it. (e.g. https://docs.camunda.io/docs/apis-clients/java-client/).

❓ Should `protocol-jackson` be part of the BOM?

**Comment by korthout** [comment]
Sure I'll take it over.

>adding ${project.basedir} might make more sense

I agree 👍

**Comment by korthout** [comment]
@oleschoenburg Please have a look at the commits I've pushed. Feel free to ask any questions.

> I agree with documenting the BOM's read me, and also documenting how users should include Zeebe in their own project. Possibly in our main README? It doesn't seem to be documented anywhere, sadly, not even in the getting started. We seem to tell users to just import the client module directly.

I think the BOM's new README already helps a bit, but I agree with Nicolas that users should be instructed in other places as well. However, I don't think it's necessary to block this release. We can update the readmes as well after the upcoming alpha release.

**Comment by oleschoenburg** [comment]
@korthout Looks like there are still some formatting issues. I'll review this first thing tomorrow, in time for 1.4.0-alpha2.

**Comment by korthout** [comment]
Should be fixed now :)

**Review by lenaschoenburg — APPROVED** [review]
LGTM :+1: 

bors r+

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
