### PR TITLE
Update to Java 21

### LINKED ISSUE #13716: Upgrade to Java 21
**Description**

The next LTS release of Java, Java 21, is upcoming on September 19th. 

It comes with:

1. Project Loom ([virtual threads](https://openjdk.org/jeps/444), [structured concurrency](https://openjdk.org/jeps/453), [scoped values](https://openjdk.org/jeps/446), etc.)
2. [Record patterns](https://openjdk.org/jeps/440)
3. [Switch pattern matching](https://openjdk.org/jeps/433)
4. [Sequenced collections](https://openjdk.org/jeps/431)

It also includes a new flag to make generating dynamic AppCDS archives much easier: `-XX:+AutoCreateSharedArchive`

Note that this also implies upgrading `zeebe-process-test`, as it relies directly on some of our modules which are not fixed to lower Java versions. Further, Operate may also rely on some internal modules from Zeebe, so we will have to double check with them as well, and possibly keep some modules pinned to lower versions.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Updates the base image to `eclipse-temurin:21` and instructs maven to build with Java 21.
Some modules stay on Java 8 of course but these already have overrides in their maven poms.

Closes #13716

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:thought_balloon: I guess this will break any project depending directly on Zeebe modules? Like zeebe-process-test, or zdb, etc. ?

**Comment by oleschoenburg** [comment]
@remcowesterhoud What's the impact on zeebe-process-test? I'd assume it's a simple upgrade to use Java 21 there too.

@Zelldon For zdb it's presumably the same?

**Review by remcowesterhoud — APPROVED** [review]

**Comment by oleschoenburg** [comment]
bors merge

**Comment by oleschoenburg** [comment]
Issue while pulling from the github actions cache :disappointed: 

bors retry

**Pull request merged**
