### PR TITLE
Use script for generating modul list

### LINKED ISSUE #9271: GHA: Building the module list fails when adding new modules
As seen here: https://github.com/camunda/zeebe/pull/9258

When a new module was added and introduced as a dependency, maven refuses to return the list of modules because it needs to resolve the dependency but can't find it in the maven repository.

To fix this we could simply `mvn install` before asking maven for the module list, but since this issue (missing mvn install) has come up a number of times and it would slow down the entire pipeline by an additional minute or so, we can also look at other solutions:

* Just run `mvn install` first
* Introduce a new job that runs `mvn install` once and makes the built artifacts available to all other jobs, see https://github.com/camunda/zeebe/pull/9258#issuecomment-1114814421
* Don't ask maven for a list of modules, see https://github.com/camunda/zeebe/pull/9258#issuecomment-1114887800

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

See https://github.com/camunda/zeebe/pull/9368#issuecomment-1125904631

## Related issues

closes #9271 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — CHANGES_REQUESTED** [review]
Thanks for working on it @Zelldon 

We can't remove the `mvn install` from the unit test job because different jobs are isolated from each other and share nothing (unless explicitly via artifacts or such). So just adding it in the project-list job is enough.

**Comment by Zelldon** [comment]
> Thanks for working on it @Zelldon 
> 
> We can't remove the `mvn install` from the unit test job because different jobs are isolated from each other and share nothing (unless explicitly via artifacts or such). So just adding it in the project-list job is enough.

Not sure whether I get it right. They use the same m2 repo or not? The action are green btw? 🤔

**Comment by oleschoenburg** [comment]
> They use the same m2 repo or not?

No. They run on completely different nodes that don't share their local maven dependencies.

> The action are green btw?

Yes, but they would fail now when adding new modules etc. That's why we need an `mvn install` for **every job** in all workflows.

**Comment by Zelldon** [comment]
Hey @oleschoenburg (+ @npepinpe ) I tried an alternative via bash script, which iterates over the modules and checks also in each module whether there are sub-modules recursively and prints the correct name. With the path printed it also works with `-pl`. I tried it out.

```sh
#!/bin/bash

set -eou pipefail

# Reads from the pom.xml, of the current directory, the defined modules
function getModules() {
 local modules=$(cat pom.xml | grep "<module>" | sed 's/\s*<.*>\(.*\)<.*>/\1/')
 echo $modules

}

# Iterates over the given modules and prints all module names recursively
function iterateOverModules() {
  # keeping the root module name allows to print module names like atomix/cluster or qa/integration-tests
  local rootModuleName=$1
  local moduleList=$2

  for module in $moduleList;
  do
    cd "$module"
    innerModules=$(getModules)
    if [ -z "$innerModules" ]
    then
      echo "$rootModuleName/$module"
    else
      iterateOverModules "$rootModuleName/$module" "$innerModules"
    fi

   # Some modules contain slashs so we have to go back one step more
    if [[ "$module" == *"/"* ]]
    then
      cd ../..
    else
      cd ..
    fi
  done
}

rootModules=$(getModules)
iterateOverModules "" "$rootModules"
```

Prints:

```sh
$ ./script.sh 
/bom
/parent
/atomix/utils
/atomix/cluster
/broker
/protocol-test-util
/samples
/dist
/protocol
/bpmn-model
/logstreams
/engine
/transport
/util
/test-util
/dispatcher
/msgpack-core
/msgpack-value
/build-tools
/gateway-protocol
/gateway-protocol-impl
/gateway
/clients/java
/exporter-api
/exporter-test
/protocol-asserts
/exporters/elasticsearch-exporter
/protocol-impl
/protocol-jackson
/zb-db
/expression-language
/feel
/dmn
/snapshot
/journal
/qa/integration-tests
/qa/update-tests
/benchmarks/project
```

This would be much faster, but yeah bash script :grin:

**Comment by npepinpe** [comment]
So one opportunity we have here is to keep the new pipeline maintainable. The old one was grown without much care in that regards. That doesn't mean no bash, but we've already painfully learned that bash is a bit of a blocker to get all team members onboard.

What would it look like with the script? Where would it be stored, in the repo itself under some folder, or just pasted into the workflow?

**Comment by Zelldon** [comment]
Both is possible I think @npepinpe but I think I would create a script and call it in the workflow. To not overload the workflow wit too much details

**Comment by oleschoenburg** [comment]
For reference, `find -wholename "./*/pom.xml" -exec dirname {} \; | jq -cnR [inputs]` is what I used before switching to maven. I think that'd be short enough to keep in the workflow itself. It's also not something I'd expect to touch often, if at all.

**Comment by Zelldon** [comment]
Ok, I would propose we go with the script approach. 

To keep it simple I would go with @oleschoenburg script since I think adding a module that shouldn't be built is quite unlikely. If this case happens that we can also increase the build script, but then I would also ask why we add this to the repo if we don't want to build it. 


Regarding why script vs `mvn install`: 

Let's do an example calculation, where every developer (~8 in the Team) does at least two commits per day (create PR + follow up commit or just add more commits to existing PR).

This means each developer needs to wait 2 minutes more on a working day. Let's say we have around 200 working days in a year, which means 400 min ~ 6.66h in a year. 

If we now multiply this with the team members, this means the complete team waits 400 * 8 = 3200 min ~ 53h in a year. I think it is quite a lot compared to maintaining just a single line of bash code, where I doubt that the maintenance cost is so high.

Any voices against it @npepinpe @oleschoenburg ?

**Comment by oleschoenburg** [comment]
@Zelldon Thanks for summarizing. I agree with that approach :+1:

**Review by lenaschoenburg — APPROVED** [review]
Thanks @Zelldon LGTM :+1: 

:wrench: Could you update the PR title and description so that the merge commit message makes sense?

**Comment by Zelldon** [comment]
Bors r+

**Pull request merged**
