### PR TITLE
feat(clients/go): jobWorker can set tenantIds to activate jobs

### LINKED ISSUE #17167: go client jobWorkerBuilder can't set tenantIds
**Describe the bug**
go client jobWorkerBuilder can't set tenantIds, but ActivateJobsRequest needs TenantIds when zeebe enabled multi-tenancy.
relate https://github.com/camunda/zeebe/issues/15095 is closed, Do we have any plan on this feature?

**To Reproduce**

**Expected behavior**

**Log/Stacktrace**
`2024/03/28 14:17:35 Failed to activate jobs for worker 'default': rpc error: code = InvalidArgument desc = Expected to handle gRPC request ActivateJobs with tenant identifiers '[]', but no tenant identifiers were provided.`

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: windows11
- Zeebe Version: 8.4.5
- go-client: v8.4.5
- Configuration:

### PR DESCRIPTION
**Pull request by tsfans**
## Description
This is a small leftover of https://github.com/camunda/zeebe/pull/14946, we just need to add TenantIds method to allow JobWorkerBuilder set tenantIds, so jobWorker can activate specific tenant's jobs.

## Related issues
closes #17167

### CODE REVIEW

**Review by korthout — APPROVED** [review]
Thanks for the outstanding contribution @tsfans 🙌 

👍 Changes look good and align with what's already there for the job worker and how to set tenant IDs for the activate jobs command.

💭 I wonder whether there is a need to set the default tenant `<default>` as the default value for these requests, similar to the Java client. But we can also add this later if that need arises.

@megglos I'd like to see another approval before merging. Can you recommend someone?

**Comment by npepinpe** [comment]
> 💭 I wonder whether there is a need to set the default tenant <default> as the default value for these requests, similar to the Java client. But we can also add this later if that need arises.

AFAIK, if multi tenancy is enabled on the gateway, then it's required to have at least 1 tenant ID for the command. So if nothing is passed, then an error is returned. If it's not enabled, then the default tenant ID is added to the broker request.

If the user sends some tenant IDs _other than the default one_, but multi-tenancy is not enabled, then an error is also returned.

**Comment by tsfans** [comment]
I've added defaultTenantId for jobWorker, but it'll still return error when multi tenancy is enabled cuz not authorizedTenants provided.
Here comes another situation: i want control tenant-isolation myself instead of zeebe Identity.
now i'm using some tricks to do this:
- use grpc client interceptor to set request header: <authorized_tenants : "request_tenantId">
- use grpc server interceptor to getAuthorizedTenants from request headers, and configure it in zeebe
Can we add a feature to support this situation? 
I think it'll reduce usage cost, maybe i should start another issue to disscus this :)

**Comment by npepinpe** [comment]
You can create your own gRPC server interceptor for the gateway: https://docs.camunda.io/docs/self-managed/zeebe-deployment/zeebe-gateway/interceptors/

And more specifically, how to implement a tenant-providing interceptor: https://docs.camunda.io/docs/self-managed/zeebe-deployment/zeebe-gateway/interceptors/#implementing-a-tenant-providing-interceptor

It's a little bit more work, but it's there as an escape hatch since we can't predict all ways people would want to implement multi-tenancy.

**Review by korthout — APPROVED** [review]
Thanks again @tsfans and sorry for not noticing this earlier

👍 LGTM

🔧 There are some conflicts by now, sorry about that. Can you please resolve these by rebasing on `main`?

@npepinpe Is there anything blocking from your side?

**Comment by npepinpe** [comment]
No, all good. Just resolve conflicts and we're good to go :)

**Comment by korthout** [comment]
@tsfans There are [some linting errors](https://github.com/camunda/camunda/actions/runs/9220664143/job/26009355026?pr=17358) that must be resolved before we can merge this. Please have a look.

PS: Regarding the failing Operate and Tasklist CI, I've requested a look from the respective teams. You don't have to look into these.

**Comment by tsfans** [comment]
@korthout Regarding the failing Operate and Tasklist CI, maybe it failed cuz different checkout cmd, In `operate-ci-build-reusable.yml` it checkout branch direct from main, but in other workflow it checkout from the PR:
`/usr/bin/git checkout --progress --force refs/remotes/pull/17358/merge`

**Comment by korthout** [comment]
Regarding the failing Operate and Tasklist CI, we have a blocking limitation at this time:
- https://github.com/camunda/camunda/issues/19222

The workaround is for me to re-create your PR. Of course, I will credit you in that PR, as I don't want to take credit for your hard work. Are you okay with me taking this workaround @tsfans?

**Comment by tsfans** [comment]
> Regarding the failing Operate and Tasklist CI, we have a blocking limitation at this time:
> 
> * [CI: operate and tasklist CI not working on PRs from forks #19222](https://github.com/camunda/camunda/issues/19222)
> 
> The workaround is for me to re-create your PR. Of course, I will credit you in that PR, as I don't want to take credit for your hard work. Are you okay with me taking this workaround @tsfans?

Of course, please do it.

**Comment by korthout** [comment]
It took a bit long, but we finally merged your changes in #20075 🎉 

With that, I'll close this PR. Thanks again @tsfans for your great contribution 🙇

**Pull request closed without merging**
