### PR TITLE
Message TTL Checker goes idle when needed

### LINKED ISSUE #11958: MessageTTLChecker isn't idle for configured interval
**Describe the bug**

If there are messages buffered, but they are not yet expired, then the [checker will continue to reschedule itself immediately](https://github.com/camunda/zeebe/pull/11948/files/d7ca49c722cae0d5f1d2d856b9844a0e8d74faf7#r1127822340).

**To Reproduce**

- Publish several messages with a TTL in the future
- ? Notice that the TTL Checker is using up a lot of CPU 🤷 

**Expected behavior**

The Message TTL Checker should await the configured interval (default 1m) when it has visited all expired messages.

### PR DESCRIPTION
**Pull request by korthout**
## Description

This makes the Message TTL Checker go idle when all expired messages have been visited. 

It would not go idle but instead rescheduled immediately because of a bug in the MessageState method `visitMessagesWithDeadlineBeforeTimestamp`. This method has a contract that says that it returns true if the visitor stopped the visiting, and false if it stopped for another reason. This return value is used by the Checker to determine whether it should reschedule itself immediately or whether it should go idle instead.

The method did not function correctly. For details about the bug in the method, please refer to the commit messages.

Thanks again for catching this bug @Zelldon ❤️ 

## Related issues

closes #11958 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by korthout** [comment]
I force-pushed the last commit to trigger the CI. It was not running because the base was initially wrongly set to `main`, resulting in merge conflicts. After changing the base, the event that triggers the CI was not raised somehow. Force-pushing a re-commit of the last commit was enough to trigger the CI again.

**Review by lenaschoenburg — APPROVED** [review]
Great breakdown of the problem and fix, thanks @korthout :1st_place_medal:

**Comment by korthout** [comment]
I don't want to block the release any longer 😄 

bors merge

**Review by romansmirnov — APPROVED** [review]
Sorry for being late! LGTM! And nice catch!!

**Comment by korthout** [comment]
>Backport failed for main, because it was unable to cherry-pick the commit(s).

I've already manually cherry-picked these commits on top of:
- #11948

**Pull request merged**
