### PR TITLE
fix(dist): silence noisy info logs from ehcache

### LINKED ISSUE #15624: Disable Ehcache auto configuration
**Description**

It seems we have a transitive dependency to ehcache somewhere, which causes the autoconfiguration for it to kick in. AFAIK we don't use Ehcache anywhere, so we should disable the auto configuration.

Please do correct me if we've recently added it.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Closes #15624

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
So just to recap, Ehcache is used by Identity directly to cache...something (tokens? claims? :shrug:), but it doesn't load any unnecessary resources we don't care about (like starting 16 threads for ES for a client we'll never use, etc.).

**Comment by oleschoenburg** [comment]
Yep, it's caching tokens apparently: https://github.com/camunda-cloud/identity/blob/main/sdk-java/src/main/java/io/camunda/identity/sdk/cache/ClientTokenCache.java

So it's just part of using identity and spring is not involved here.

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
