### PR TITLE
chore(dist): output compact json logging

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

WIP

## Related issues

WIP

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by npepinpe** [comment]
Samples:

image

image


Starting as: `bin/broker | jq`

**Comment by npepinpe** [comment]
Without piping to jq each record is on its own line and compacted

**Comment by npepinpe** [comment]
Closing, didn't realize menski was working on this already

**Comment by falko** [comment]
Is there another PR for this or is it already implemented?

**Comment by npepinpe** [comment]
I think it's still on @menski's todo list

**Pull request closed without merging**
