### PR TITLE
Add code blocks to save actions

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
Add useBlocks option to the save action plugin,
such that it generates brackets for new code.

This is useful especially when generating equals/hashcode

See related slack thread https://camunda.slack.com/archives/C05DH1F5TAR/p1710928704042159?thread_ts=1710928203.030479&cid=C05DH1F5TAR

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
Wohooo 👍 🥳

**Comment by Zelldon** [comment]
@tmetzke I realized I had to do the same for Operate subfolder.

**Comment by oleschoenburg** [comment]
@Zelldon This file get's reformatted, reordered automatically for me. Does that happen for you too or is it something weird in my setup?

```diff
===================================================================
diff --git a/.idea/saveactions_settings.xml b/.idea/saveactions_settings.xml
--- a/.idea/saveactions_settings.xml	(revision Staged)
+++ b/.idea/saveactions_settings.xml	(date 1711023535372)
@@ -10,8 +10,8 @@
         <option value="fieldCanBeFinal" />
         <option value="localCanBeFinal" />
         <option value="missingOverrideAnnotation" />
-        <option value="unnecessaryThis" />
         <option value="useBlocks" />
+        <option value="unnecessaryThis" />
       </set>
     </option>
     <option name="configurationPath" value="" />
@@ -21,4 +21,4 @@
       </set>
     </option>
   </component>
-</project>
+</project>
\ No newline at end of file
```

**Comment by Zelldon** [comment]
🤔 didn't observed this yet. I have only sometimes these weird diff of the </project> or intellij getting nuts with opening Pom files (when I changed the dependencies around #17009) But I guess this is not related.

**Comment by oleschoenburg** [comment]
If I make the file read-only, IntelliJ complains: "Failed to save settings. Please restart IntelliJ IDEA"

**Pull request merged**
