### PR TITLE
Remove ZbMap

### LINKED ISSUE #1670: Remove ZbMap
Since #1573 the ZbMap is no longer used, we can remove it.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
closes #1670 

depends on #1573

### CODE REVIEW

**Comment by npepinpe** [comment]
+4 −11,811 :tada: 

Do we have an issue to remove everything related to state resources? Or should that just be included in #1676?

**Review by npepinpe — APPROVED** [review]

**Comment by Zelldon** [comment]
Yeah I think we can do this in #1676

**Comment by menski** [comment]
bors retry

**Comment by Zelldon** [comment]
bors retry

**Comment by menski** [comment]
bors retry

**Comment by Zelldon** [comment]
kaputt :cry:

**Comment by menski** [comment]
@Zelldon I think I didn't configured retry correctly for the new bot. Let's see what happens next

**Comment by Zelldon** [comment]
Ah ok. Yes lets see what happens :D Thanks @menski

**Pull request merged**
