### PR TITLE
Prefer replicating events instead of snapshots

### LINKED ISSUE #7784: Improve the heuristic on when to send a snapshot or events to a follower
When the leader replicates to a follower, it can either send the next event to be replicated or a snapshot at a later index if one exists. If the follower is lagging behind many events it is more efficient to send a snapshot and skip all the missing events. However if the follower is only lagging behind by a few events, replicating snapshot has more overhead. Now we always send the snapshot if the snapshot exists. Now that the follower is building its own state, replicating snapshot is wasteful because the state build by the follower will be thrown away and it has to restart from the new snapshot. 

This behavior was observed in one of our benchmark.
There are frequent snapshot replications:
image

Frequent re-installation of streamprocessor also leads to temporary increase in memory consumption:
image

Frequent replication of snapshot is not optimal if the snapshot is big. Hence we need a better heuristic on when to send a snapshot vs when to send the event even if a snapshot exists at a higher index.  A simple strategy can be to send the events if the number of events until the snapshot index is less than a threshold, else send the snapshot. A more complex strategy could be based on the size of snapshot vs size of missing events.
This also means we shouldn't compact the logs immediately after taking a snapshot, but wait until the followers are caught up with either the snapshot or the events. For safety, compact after a specific timeout even if followers are not caught up.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

This adds a threshold on number of events a follower can lag behind a leader to decide wether we should replicate events or a snapshot. This should save resources because replicating a low number of events should be more efficient than replicating a snapshot.
We can't always replicate events even if the lag is below the threshold because some events might not be available anymore due to log compaction. 

## Related issues

closes #7784 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by oleschoenburg** [comment]
There are a couple of tests that I'll need to adjust because they are assuming that we'd replicate snapshots in most cases.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
:rocket: 
Please see my comment on the new "condition" and the test to reproduce the error. Othwerise it looks good, just have some optional comments.

**Review by deepthidevaki — APPROVED** [review]
Great! :tada: 

Please see my comment before merging.

**Comment by oleschoenburg** [comment]
I'll run some benchmarks before merging to confirm that the current threshold of 100 is a sensible value.

**Comment by deepthidevaki** [comment]
Thanks @oleschoenburg for running the benchmark.
If the follower is lagging behind be ~10K events, then it is better to send the snapshot instead of the events. As you said it make sense to evaluate what would be a good threshold for it. 100 might be low, but 10K is too big.

**Pull request merged**
