### PR TITLE
Reject ResourceDelete command when resource is unknown

### LINKED ISSUE #9799: Reject resource delete command when resource does not exist
# Description
When we receive a resource deletion command containing a key of a resource we don't know, we should reject the command.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

When we can't find a resource with the given key we will reject the command.

## Related issues

closes #9799

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@berkaycanbc Thanks for wanting to review this 🚀 Here you can find some information about how we do code reviews https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews

**Review by berkaycanbc — CHANGES_REQUESTED** [review]
:+1: Clean and easy to follow with separated commits. Thanks! :rocket:

:wrench: I suggested only minor changes for possible typo.

**Comment by remcowesterhoud** [comment]
Thanks @berkaycanbc, I have applied your suggestions. Please have another look!

**Review by berkaycanbc — APPROVED** [review]
@remcowesterhoud Approved!

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors retry

**Comment by remcowesterhoud** [comment]
bors retry

**Pull request merged**
