### PR TITLE
docs: add REST controller dev guide

### LINKED ISSUE #20444: Provide a REST controller implementation guide
**Description**

Provide a developer guide for REST controllers to enable all teams to provide API endpoints efficiently.
The guide should cover a high-level list to easily take away as well as more detailed instructions per step to consider.
The guide should touch all required tasks end-to-end, from endpoint design to implementation, testing, and documentation.

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

Adds a developer guide for adding REST controllers end-to-end.

## Related issues

closes #20444

### CODE REVIEW

**Review by houssain-barouni — APPROVED** [review]
LGTM. Thanks for this complete guide

**Review by remcowesterhoud — APPROVED** [review]
Very well written @tmetzke, I'll try it out soon!

🔧 It would be nice to reference this page in the [developer handbook](https://github.com/camunda/camunda/blob/main/zeebe/docs/developer_handbook.md).

**Comment by tmetzke** [comment]
> Very well written @tmetzke, I'll try it out soon!
> 
> 🔧 It would be nice to reference this page in the [developer handbook](https://github.com/camunda/camunda/blob/main/zeebe/docs/developer_handbook.md).

https://github.com/camunda/camunda/pull/20469 👍

**Comment by tmetzke** [comment]
I need to fix the Markdown file, it's not adhering to our style configuration. Too bad the `Java Checks` CI is not running here in the PR because then I would have known earlier 😄

**Review by nathansandi — APPROVED** [review]

**Pull request merged**
