### PR TITLE
Preparation for writting StreamProcessor tests in Engine module

### PR DESCRIPTION
**Pull request by ChrisKujawa**
* all current used records implement RecordValue interfaces, this is the first step to unify the parallel hierarchy
     * `toJson` and `customHeaders` is currently not implement and will throw an unsupported exception
     * after we implemented this part we can delete the exporter record value implementations and export the internally used record values
 * create a new EngineRule in the engine module, which installs the engine (all record processors) and exports records to the RecordingExporter
    * new tests can now use the engine rule and the recording exporter - this should make it easy to migrate test from broker to engine module 
       * the new test will directly write commands on the stream and process them
        * no need for request-response or starting a broker

  * we use in the BpmnStepContext  directly the key, intent and RecordValue instead of using the TypedRecord
      * with this change it is easier to call the BpmnStepProcessor from the ResolveIncidentProcessor
and we do not need to implement a new TypedRecord partially because we have not all information's

Todo's:

  * migrating all processing related tests to the engine module https://github.com/zeebe-io/zeebe/issues/2461
  * remove MockTypedRecord, implements currently also partially the Record interface (part of https://github.com/zeebe-io/zeebe/issues/2461)
  * implement the missing `#toJson` and `#customHeaders` https://github.com/zeebe-io/zeebe/issues/2551
  * remove the exporter RecordValue implementations https://github.com/zeebe-io/zeebe/issues/2550
  * move the RecordValue interfaces to the protocol module (https://github.com/zeebe-io/zeebe/issues/2549) - currently it looks a bit weird since the gateway etc needs some information (ResourceType), which are part of the exporter-api module.
  

related to https://github.com/zeebe-io/zeebe/issues/2461

### CODE REVIEW

**Review by menski — APPROVED** [review]
LGTM, can you please create an issue to move `ResourceType` to the protocol. We should have our Enums in one place.

bors r+

**Comment by Zelldon** [comment]
I thought this would be part of #2549

**Comment by menski** [comment]
Okay fine for me. :+1:

**Comment by Zelldon** [comment]
Bors r+

**Pull request merged**
