### PR TITLE
Improve `equals` implementation of atomix requests

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Follows up-stream PR https://github.com/atomix/atomix/pull/1051, and resolves three CodeQL warnings.

### CODE REVIEW

**Review by ChrisKujawa — COMMENTED** [review]
Hey @oleschoenburg thanks for the changes makes totally sense to me! What do you think about completely regenerate the equals methods by intellij ? So they follow our codestyle rules https://github.com/camunda-cloud/zeebe/wiki/Code-Style#equalshashcode-implementations

BTW your build failed in a randomized test, I think it is unrelated to your changes, I opened an issue for it https://github.com/camunda-cloud/zeebe/issues/8328

**Comment by oleschoenburg** [comment]
> What do you think about completely regenerate the equals methods by intellij

That's a good point, it makes sense consistency wise (though I have to admit that I prefer the "atomix style" equals). 

While trying this out I also noticed that equals and hashCode of `ConfigureRequest` don't match. equals checks the timestamp field, hashCode does not. That breaks the contract of hashCode which is bad.

**Comment by Zelldon** [comment]
You can always bring up such topics in the team meeting if you see a benefit over certain topics and we can discuss it there.

Yes this is not optimal I agree. I think this is in several places in the old atomix code base. Might be worth to check other places.

**Review by ChrisKujawa — APPROVED** [review]
Thanks ole 👍🚀

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
