### PR TITLE
[BACKPORT 0.24] Centralize gRPC error mapping

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR backports #5524 to 0.24, which centralizes gRPC error mapping.  There was a single merge conflict as a new dependency was added in the `parent/pom.xml` (`protobuf-common`), but nothing special.

## Related issues

related to #5237 
backports #5524 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by Zelldon** [comment]
Tests are failing please take a look at this :)

**Comment by npepinpe** [comment]
Uh, wasn't expecting this to break the upgrade tests :thinking:

**Comment by npepinpe** [comment]
Wait, aren't the upgrade tests with snapshot disabled on 0.24? Why is it trying to run it? :thinking:

**Comment by Zelldon** [comment]
:man_shrugging: why is the debug exporter on?

**Comment by npepinpe** [comment]
Because we read the logs to figure out the state of the processes :see_no_evil: I'd like to propose a solution to fix this, but it's not currently something that would be necessary for GA. I'll write it up anyway - in the mean time though, this is what we have. Either that or we use an Elastic node from which we can pull the JSON...either way it's still a pain to rehydrate and get records out.

**Comment by Zelldon** [comment]
Hazelcast exporter :100:

**Comment by npepinpe** [comment]
Not an official exporter :sweat_smile: I'd be happy to have another official, lightweight exporter though - whether it's Hazelcast or something dumber like using shared memory or a unix socket or files, etc.

**Comment by Zelldon** [comment]
You can make it official right :sweat_smile:

**Comment by npepinpe** [comment]
I'd like something dumber - give me the dumbest exporter that isn't /dev/null :fire:

**Comment by Zelldon** [comment]
How about a static map of records, which you can access in your jvm :D

**Comment by npepinpe** [comment]
We have that with the HTTP exporter, but its like the debug exporter, it doesn't move the position =/

**Comment by Zelldon** [comment]
If you write plain to the file why it is different than the debug exporter? You also need to re-read and deserialize it right?

**Comment by npepinpe** [comment]
Yeah that part doesn't go away - for the serde I'd like to propose something like I did with https://github.com/zeebe-io/zeebe-protocol-immutables. And you're right, maybe we could just configure the debug exporter to acknowledge the position once it's printed it out, why not?

**Comment by Zelldon** [comment]
:+1:

**Comment by npepinpe** [comment]
I found the issue - the stable/0.24 was broken, so it's not this PR which introduced that. I had to backport some release scripts when I released 0.24.5, and one thing it did was bump the backwards compat version from 0.23.0 to 0.24.5. The UpgradeTest before were expecting a snapshot to be taken on close which is true in 0.23.0 but not in 0.24.5. So now that they run from 0.24.5 to 0.24.6-SNAPSHOT, there was never any snapshot. So I backported the changes needed to make this.

**Comment by npepinpe** [comment]
I will revert those changes and keep comparing against 0.23.0 - that's to avoid pulling in more changes in this PR...and as I will also backport another PR which will rewrite the upgrade tests, I'd rather not do the same work twice.

**Comment by npepinpe** [comment]
ping @Zelldon like I mentioned, I will fix the upgrade tests and backport this tomorrow, so I would rather not add more to this PR now and we will keep comparing against 0.23.0 for now if that's alright.

**Comment by Zelldon** [comment]
I hope you dont forget about it 😅 maybe you xan create an issue for it

**Review by ChrisKujawa — APPROVED** [review]

**Pull request merged**
