### PR TITLE
fix(topology): updating the topology file should truncate previous data

### PR DESCRIPTION
**Pull request by lenaschoenburg**
While chaos testing, we saw on multiple occasions that the `.topology.meta` file contained corrupted content. The cause for this was that while updating the file, we didn't truncate previous data. Depending on previous and updated data, we'd get nonsense data or (at best) an exception during deserialization.

I added the `TRUNCATE_EXISTING` option to truncate the file in b9e09c4b02a0db7125d6c494e5c8cbc4cca49187. To test this reliably (not every update corrupted the file in such a way that it was easily detectable), I've added a simple property test that generates more or less valid `ClusterTopology`s, writes the first one, updates and then checks if the file content is as expected. Without adding the `TRUNCATE_EXISTING` flag, this test fails quickly.

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
:rocket: Great catch.

**Comment by oleschoenburg** [comment]
bors merge

**Comment by oleschoenburg** [comment]
bors merge

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
