### PR TITLE
chore(broker): remove output behavior support in IO mappings

### LINKED ISSUE #1878: Remove output behavior of mappings
Since we switched to the new variable concept, the output behavior (MERGE, OVERWRITE, NONE) doesn't make sense anymore. The job payload is always merged (based on the output mappings). The variables can't be overwritten by the payload because they are stored in the scopes. Ignoring the payload is an edge case and maybe nobody really needs this.

AT:
* remove `outputBehavior` from BPMN model API and related I/O mapping in the broker
* remove `outputBehavior` from the documentation

### PR DESCRIPTION
**Pull request by npepinpe**
closes #1878

### CODE REVIEW

**Comment by npepinpe** [comment]
tbh I wasn't sure if this is a feature or chore, since it's removing a feature (i.e. user facing) :sweat_smile:

**Comment by menski** [comment]
@npepinpe there is also the possibility to mark breaking changes in chore commit messages by using the keyword `BREAKING CHANGE`, see this commit https://github.com/zeebe-io/zeebe/commit/9fbaccb5965b211db6716ee8b2e1a81741708aa6 for example and the result in the changelog https://github.com/zeebe-io/zeebe/blob/develop/CHANGELOG.md#0130-2018-11-06

**Review by ChrisKujawa — APPROVED** [review]
Looks good. Could you add the BREAKING CHANGE to one of the commits as suggested by @menski

**Pull request merged**
