### PR TITLE
Restructure journal module

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR mostly restructures the journal module to better reflect its usage. Instead of the main API in the root package and everything else under the `file` package, we now have:

```
root <--- journal API and common classes meant to be consumed outside
  |
  |-- file <--- persistence layer, i.e. segmented journal implementation
  |-- record <-- record (de)serialization and manipulation
  |-- util <-- internal utilities (only ChecksumGenerator for now)
```

We could alternatively think about moving `file`, `record`, and `util` under a `impl` package as well to clearly indicate these aren't meant to be used outside of the module. This came out of #7607.

## Related issues

related to #7607

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Ah, code scanning never works when you point to another branch than main, true.

**Comment by npepinpe** [comment]
Please review #9833 first

**Review by lenaschoenburg — APPROVED** [review]
LGTM! 

Good idea to backport this :+1:

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
