### PR TITLE
Use System time for metrics

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

For most metrics, it doesn't make sense to use the ActorClock, since it is pinned between actor executions. To get an accurate view we have to use System time here.

Pointed out here https://github.com/camunda-cloud/zeebe/issues/7955#issuecomment-940731599

I run a benchmark to compare the numbers:

With the actor clock we see quite low numbers for processing and commit latency
latencybug

With the fix we can see much more accurate numbers
latencyfix

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by Zelldon** [comment]
I updated this PR as discussed @npepinpe in most cases we now use Prometheus Timer

**Review by npepinpe — APPROVED** [review]
Looks good, but I thought you mentioned we couldn't do this for every case? Is another PR upcoming?

**Comment by Zelldon** [comment]
@npepinpe we probably want to backport this?

**Comment by npepinpe** [comment]
To 1.2, yes.

**Comment by Zelldon** [comment]
/backport

@korthout @pihme thanks for this bot :heart:

**Pull request merged**
