### PR TITLE
fix(protocol): prevent NullPointerException in BpmnElementType

### LINKED ISSUE #8141: Potential NPE in BpmnElementType.getElementTypeName
**Describe the bug**
There is a potential NullpointerException in the method `BpmnElementType.getElementTypeName` when called on enum elements that actually have no corresponding element type name.

**To Reproduce**
invoke `BpmnElementType.MULTI_INSTANCE_BODY.getElementTypeName()` and you get a NPE

**Expected behavior**
the Optional returned should just be empty

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
"java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.camunda.zeebe.protocol.record.value.BpmnElementType.getElementTypeName(BpmnElementType.java:68)
```

</p>
</details>

**Environment:**
 - Zeebe Version: >1.1.2

### PR DESCRIPTION
**Pull request by megglos**
## Description

As the elementTypeName field can be null use Optional.ofNullable in the getter.

## Related issues

closes #8141

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by korthout — APPROVED** [review]
Thanks for the fix @megglos 💐 
This change makes perfect sense 🎉 

🙃 nothing blocking, but please consider the following before merging (you can simply inform [bors](https://bors.tech/documentation/) when you're ready):
- your commit message title doesn't comply with our [commit message guidelines](https://github.com/camunda-cloud/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines), specifically `bpmn elements` should probably be `protocol`.
- perhaps the pull request title could have a more meaningful name

**Comment by megglos** [comment]
@korthout thanks for the feedback adjusted the commit message as well as the title, is the latter now more clear?

**Comment by korthout** [comment]
@megglos thanks! 👍 (we try not make the PR titles more human readable and avoid the commit type prefix, but at the same time we are not consistent with this ourselves, so don't worry about it 😆)

**Comment by korthout** [comment]
bors merge

**Pull request merged**
