### PR TITLE
New default back pressure algorithm

### LINKED ISSUE #5113: Set fixed limit as default back pressure configuration
**Is your feature request related to a problem? Please describe.**

The current default back pressure configuration uses the Vegas algorithm with an initial limit of 20. What this means is it will poorly handle initial bursts, and may result in a poor first user experience - it's also generally quite pessimistic and more difficult to configure/explain to users.

See: 

- https://github.com/zeebe-io/zeebe/issues/4765
- https://github.com/zeebe-io/zeebe/issues/3367
- https://forum.zeebe.io/t/resource-exhausted-reached-maximum-capacity-of-requests-handled/731

**Describe the solution you'd like**

After discussing it with @deepthidevaki and @menski, the current proposal would be to switch to a fixed limit, with a default limit configured based on the Camunda Cloud Development Cluster (single node, single partition) machine for a relatively low maximum command latency target, say 1s, during a stress test.

**Describe alternatives you've considered**

Using AIMD as default - while more adaptive, the downside here is that AIMD, under duress, will lower the limit lower than it really needs to. However it's also quite easy to explain to users, so could be a viable alternative.

### LINKED ISSUE #5257: Documentation shows different backpressure algorithm name
**Describe the bug**

Backpressure algorithm "FixedLimit" has an different enum then it is documented in the configuration.

It is documented in the configuration as:

```
  # The algorithm configures which algorithm to use for the backpressure.
      # It should be one of vegas, aimd, fixedLimit, gradient, or gradient2.
      # This setting can also be overridden using the environment variable ZEEBE_BROKER_BACKPRESSURE_ALGORITHM
      # algorithm: "vegas"
```

But if you use 

```
  - name: ZEEBE_BROKER_BACKPRESSURE_ALGORITHM
    value: "fixedLimit"
```

Then you get

```
{"severity":"INFO","logging.googleapis.com/sourceLocation":{"function":"logMessage","file":"ConditionEvaluationReportLoggingListener.java","line":136},"message":"\n\nError starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.","serviceContext":{"service":"zeebe-broker","version":"zell-fixed-300-single-part-100-workflows"},"context":{"threadId":1,"threadPriority":5,"loggerName":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener","threadName":"main"},"timestampSeconds":1598620848,"timestampNanos":765074000,"logger":"org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener","thread":"main"}
{"severity":"ERROR","logging.googleapis.com/sourceLocation":{"function":"report","file":"LoggingFailureAnalysisReporter.java","line":40},"message":"\n\n***************************\nAPPLICATION FAILED TO START\n***************************\n\nDescription:\n\nFailed to bind properties under 'zeebe.broker.backpressure' to io.zeebe.broker.system.configuration.backpressure.BackpressureCfg:\n\n    Property: zeebe.broker.backpressure.algorithm\n    Value: fixedLimit\n    Origin: System Environment Property \"ZEEBE_BROKER_BACKPRESSURE_ALGORITHM\"\n    Reason: No enum constant io.zeebe.broker.system.configuration.backpressure.BackpressureCfg.LimitAlgorithm.FIXEDLIMIT\n\nAction:\n\nUpdate your application's configuration\n","serviceContext":{"service":"zeebe-broker","version":"zell-fixed-300-single-part-100-workflows"},"context":{"threadId":1,"threadPriority":5,"loggerName":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","threadName":"main","reportLocation":{"functionName":"report","filePath":"LoggingFailureAnalysisReporter.java","lineNumber":40}},"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","timestampSeconds":1598620848,"timestampNanos":770094000,"logger":"org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter","thread":"main"}
```

See here for example https://github.com/zeebe-io/zeebe/blob/develop/broker/src/main/java/io/zeebe/broker/transport/backpressure/PartitionAwareRequestLimiter.java#L60

**To Reproduce**

Use "fixedLimit" as algorithm.

**Expected behavior**
It works.

**Environment:**
 - OS: k8s
 - Zeebe Version: snapshot

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Fixes the mismatch between documentation and implementation of the back pressure algorithm "fixed".

Sets "fixed" as new default back pressure algorithm. Evaluated with one partition and different limits to find an appropriate value, see this comment https://github.com/zeebe-io/zeebe/issues/5113#issuecomment-682679016 .

As last evaluation I did a benchmark with three partitions and our usual load of 300 workflow instances per seconds and 12 workers.

|Name | Base | Fixed Limit |
|---------|--------|-----------------------|
|General| base-300wf-3p-general | fixed-300wf-3p-general |
| Latency | base-300wf-3p-latency | fixed-300wf-3p-latency |

We can see that the throughput is a bit lower then usual, but we reduced the latency by factor two. Normally the workflow instance execution time was between 2.5 - 5 seconds, with the fixed limit it is between 1 to 2.5 seconds. Furthermore the command and event processing latency is normally between 250 to 500 ms now it is between 100 to 250 ms.

## Related issues

closes https://github.com/zeebe-io/zeebe/issues/5257
closes https://github.com/zeebe-io/zeebe/issues/5113

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by deepthidevaki** [comment]
Thanks @Zelldon for evaluating with different limits. We thought that vegas is too conservative, so we expected that evaluating with a fixedLimit would allows us to find a higher limit value. Reducing the limit to 10 would not solve the problem encountered by first time users. Wdyt @menski @npepinpe ?

**Comment by Zelldon** [comment]
Ok @deepthidevaki feel free to close this if this doesn't fit. I think at least we should fix the doc and implementation mismatch for the fixedLimit algorithm.

**Comment by deepthidevaki** [comment]
Sure @Zelldon. I will take care of it.

**Comment by menski** [comment]
I think the limit should be higher then 10, gut feeling would be 100. I don't think it's important if the limit works well for constant throughput scenarios, but that it handles the getting started experience well, i.e. a burst or similar.

**Comment by deepthidevaki** [comment]
@menski,  zell has evaluated with limit 100, but the processing latency is very high then. https://github.com/zeebe-io/zeebe/issues/5113#issuecomment-682679016

**Comment by npepinpe** [comment]
What about AIMD as default  with a higher initial limit (e.g. 100) and target RTT (e.g. 3s)?

**Comment by menski** [comment]
> @menski, zell has evaluated with limit 100, but the processing latency is very high then. [#5113 (comment)](https://github.com/zeebe-io/zeebe/issues/5113#issuecomment-682679016)

Yes I think this is expected, but in this case we are pushing around 20 instances per second through the system. This is not what I expect from a getting started scenario. That's when you are reaching production use cases and have to think about the right back pressure algorithm imho. But maybe @npepinpe idea works better for getting startet and transition to production.

**Comment by deepthidevaki** [comment]
AIMD is not good for handling bursts, unless it is configured with a high 'minLimit'. During bursts, it aggressively reduces the limit upto minLimit (which default is 1, I think). May be a minLimit of 50 or higher might work.

**Comment by npepinpe** [comment]
Let's keep the ball rolling - should we close this and move back to the issue? I see @menski self-assigned, does this mean you take it over?

**Comment by deepthidevaki** [comment]
@npepinpe First part of this PR fixes #5257. It should be merged no matter what we chose for default algorithm.

**Comment by menski** [comment]
I split out the first part and finished it in PR #5317. I will close this PR  for now, until we decided what is the algorithm and config we want to use as default.

**Pull request closed without merging**
