### PR TITLE
[BACKPORT] fix(broker): use logstream name for health monitoring

### LINKED ISSUE #4840: Backport fix 4815 to 0.23
**Description**

Backport PR https://github.com/zeebe-io/zeebe/pull/4815 for the issue #4618 to 0.23

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

* Use consistent name for logstream component

## Related issues

closes #4840 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by korthout — APPROVED** [review]
LGTM, but do note that the builds have failed.

**Comment by deepthidevaki** [comment]
> LGTM, but do note that the builds have failed.

Flaky tests. I think they are already fixed in develop.

**Comment by korthout** [comment]
> > LGTM, but do note that the builds have failed.
> 
> Flaky tests. I think they are already fixed in develop.

You can retry the builds in Jenkins if you want to make sure your build can get green

**Comment by deepthidevaki** [comment]
bors retry

**Pull request merged**
