### PR TITLE
feat(broker): parallel multi-instance sub-process and receive task

### LINKED ISSUE #2846: Deploy workflow with parallel multi-instance sub-process
**Is your feature request related to a problem? Please describe.**
I want to use parallel multi-instance on a sub-process to execute it for each element of a collection.

**Describe the solution you'd like**
* when the sub-process is entered, it creates one instance of each element in the collection
* when all instances are completed, the sub-process is left

Same as for service tasks #2845.

requires #2845

### PR DESCRIPTION
**Pull request by saig0**
## Description

* adding support for parallel multi-instance sub-process and receive task
* mainly added test cases to verify the behavior

## Related issues

closes #2846 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
Looks good! :birthday: 

Just some questions:

1. Is it useful to have sub process tests where we check different inner elements are instantiated? Is it not enough to just check that they are started, when all are completed the body completes, and on termination all are terminated properly?
1. I think by removing the service task tests we don't have a test checking that completing all service tasks completes the MI body?
1. There's no test where we explicitly check that the variable records we create have the correct scope key. I think those tests might still pass if we changed the implementation to write the variables on the global scope, since we just check the order of the variable record creations?

**Comment by saig0** [comment]
1) Generally yes. However, it could happen that the combination with the multi-instances doesn't work even if all separated parts work. So, I would like to test it.
2) It is still tested.
3) I applied your hints. Please have a second look :eyes:

**Review by npepinpe — APPROVED** [review]
:+1: :tada: 

Yes, about 2. it was me failing to parse the PR view and thinking the file had been deleted, my bad :see_no_evil:

**Pull request merged**
