### PR TITLE
[Backport 0.24] Remove workflow related data from state when it is not used

### LINKED ISSUE #4957: Variable state is not cleaned up if an event is triggered
**Description**

When an event (timer/error) is triggered for a workflow instance then it inserts data in the variable state. This data is not removed when the workflow instance is completed/terminated. 

As a result, the RocksDB state and the snapshot size grows over time and can finally lead to out-of-disc-space.

### LINKED ISSUE #4959: Event Scope State is not cleaned up when the message start event subscription is closed
**Description**

When a workflow with a message start event is deployed then a new message start event subscription is opened for every message start event. This subscriptions are closed when a new version of the workflow is deployed (i.e. same BPMN process id). But these subscriptions are not removed from the event scope instance state. 

As a result, the RocksDB state and the snapshot size grows over time (for every new deployment) and can finally lead to out-of-disc-space.

### PR DESCRIPTION
**Pull request by saig0**
## Description

* backport of #4963 to `0.24` 

## Related issues

closes #4957
closes #4959

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release annoncement

### CODE REVIEW

**Comment by Zelldon** [comment]
Please add me as a reviewer after the first PR is done and merged.

**Review by ChrisKujawa — APPROVED** [review]
:+1: bors r+

**Comment by Zelldon** [comment]
@npepinpe can we please add this to the next pathc release.

**Comment by npepinpe** [comment]
You mean for the 0.24.2?

**Pull request merged**
