### PR TITLE
Switch engine to the more generic camunda security configuration

### LINKED ISSUE #25373: Unify authorizations configuration properties across components
### Description
[Slack discussion (internal)](https://camunda.slack.com/archives/C06UYJMMETZ/p1732633196982989) 

Currently, multiple properties exist to enable authorizations, which can create confusion for users and require additional setup.

For example, the following properties exist today:
- Operate: `camunda.operate.identity.resourcePermissionsEnabled`
- Tasklist: `camunda.tasklist.identity.resourcePermissionsEnabled`
- V2 REST api: `camunda.security.authorizations.enabled`
- Zeebe Broker: `zeebe.broker.experimental.engine.authorization.enableAuthorization`

### Goals

- Use a single parameter such as `camunda.security.authorizations.enabled` across all components wherever possible.
- Backward Compatibility: Retain support for legacy properties (`camunda.operate.identity.resourcePermissionsEnabled`, `camunda.tasklist.identity.resourcePermissionsEnabled`) for customers migrating from older versions.
- Explore the feasibility of unifying Zeebe-specific broker parameters with the generic Camunda configuration.
- Update https://github.com/camunda/camunda-platform-helm/pull/2593, to set the unique parameter in helm charts

### Notes:
- this can be extended to multi-tenancy enabler parameters

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Zeebe didn't align with the configuration to enable/disable authorizations with the rest of the components. As a result users would have to enable authorizations multiple times. With this PR we align Zeebe by giving it access to the generic security configurations.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #25373

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@npepinpe In the first commit I've touched some ZDP parts in this PR. Could you assign someone to review the first commit?

**Comment by remcowesterhoud** [comment]
@houssain-barouni I notice in the [ServiceSecurityConfiguration](https://github.com/camunda/camunda/blob/main/dist/src/main/java/io/camunda/application/commons/service/ServiceSecurityConfiguration.java#L22) we have an annotation `@ConditionalOnRestGatewayEnabled`. Do you think this is still valid? If Zeebe also uses this configuration I feel it should be enabled when Rest is disabled as well, considering we still have gRPC.

**Comment by houssain-barouni** [comment]
> @houssain-barouni I notice in the [ServiceSecurityConfiguration](https://github.com/camunda/camunda/blob/main/dist/src/main/java/io/camunda/application/commons/service/ServiceSecurityConfiguration.java#L22) we have an annotation `@ConditionalOnRestGatewayEnabled`. Do you think this is still valid? If Zeebe also uses this configuration I feel it should be enabled when Rest is disabled as well, considering we still have gRPC.

You’re absolutely right! We actually need it for the broker.

However, I would still apply @ConditionalOnRestGatewayEnabled to the [authorizationChecker](https://github.com/camunda/camunda/blob/5181c238c15d15fdb0e45b0fa5f017507e88e81a/dist/src/main/java/io/camunda/application/commons/service/ServiceSecurityConfiguration.java#L33-L37) bean, as it is only used by the gateway when REST is enabled. This happens via the [services module](https://github.com/camunda/camunda/blob/5181c238c15d15fdb0e45b0fa5f017507e88e81a/dist/src/main/java/io/camunda/application/commons/service/CamundaServicesConfiguration.java#L61), which is only enabled when REST is active. Additionally, the bean requires access to Elasticsearch or RDBMS.

**Review by npepinpe — APPROVED** [review]
:+1: From my side, but admittedly I lack context to review the actually important parts :smile:

**Comment by houssain-barouni** [comment]
> @houssain-barouni I notice in the [ServiceSecurityConfiguration](https://github.com/camunda/camunda/blob/main/dist/src/main/java/io/camunda/application/commons/service/ServiceSecurityConfiguration.java#L22) we have an annotation `@ConditionalOnRestGatewayEnabled`. Do you think this is still valid? If Zeebe also uses this configuration I feel it should be enabled when Rest is disabled as well, considering we still have gRPC.

@remcowesterhoud I did that in a separate pull request https://github.com/camunda/camunda/pull/25609

**Review by houssain-barouni — APPROVED** [review]
🚀 thanks @remcowesterhoud for taking care of this

**Pull request merged**
