### PR TITLE
fix: exclude operate folder from license plugin

### PR DESCRIPTION
**Pull request by cmur2**
## Description

This PR is a preparation for the merge of Operate source code into this repo. As [discovered](https://camunda.slack.com/archives/C06HTSPD5AP/p1709720579737679?thread_ts=1709713323.576829&cid=C06HTSPD5AP) in the [simulated merge test](https://github.com/camunda/zeebe/pull/16716) the Zeebe license plugin will complain when the Operate source code is added.

Roman found a fix in https://github.com/camunda/zeebe/pull/16716/commits/df6c4405554f168cba48f8b1f517f2714b79fd3d which we want to already include in this repository (outside of the simulated merge test PR) as preparation for the merge.

## Related issues

Related to https://github.com/camunda/team-infrastructure/issues/616

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Fine by me but I'm wondering if we shouldn't rather make Operate work with the license plugin?

**Comment by cmur2** [comment]
> Fine by me but I'm wondering if we shouldn't rather make Operate work with the license plugin?

I'm just the messenger and not subject matter expert on the licensing questions and how they are enforced - maybe @romansmirnov knows the answer?

**Comment by romansmirnov** [comment]
@oleschoenburg, the license plugin works with Operate. Just that Operate has a different license header. The license check failed - if - I am not wrong - in the Zeebe Root "module" which contains all subfolders including the operate subfolder. If I am not mistaken, then the plugin just goes through all subfolders of that module and checks the license headers. It also did that for the operate subfolder where it failed.

**Comment by cmur2** [comment]
@oleschoenburg is that answer from Roman fine for you? If so, I'd go ahead with the merge (we can also later revisit this topic in case we find a better solution)

**Pull request merged**
