### PR TITLE
Run CodeQL GHA job on selfhosted runner

### LINKED ISSUE #9590: CodeQL build step is slow
**Description**

In some runs of the Code Quality workflow, the CodeQL job's step `Build` takes exceptionally long. The build step runs `mvn -B -T1C -DskipTests -DskipChecks install`.

For example, [here](https://github.com/camunda/zeebe/runs/7021659541?check_suite_focus=true) it took 22 min.
image

### PR DESCRIPTION
**Pull request by korthout**
## Description

The CodeQL job takes very long. By running it on a self-hosted runner with more CPUs than the default GHA runner, we can speed up this job.

## Related issues

closes #9590

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by korthout** [comment]
Seems this doesn't work yet. See [this run](https://github.com/camunda/zeebe/runs/7024300279?check_suite_focus=true).

**Comment by oleschoenburg** [comment]
@korthout I don't think this will work, the nexus cache is only meant for jobs that run on our self-hosted runners. Since the codeql job takes such a long time, moving to one of our smaller 8cpu self-hosted runners might be a good idea though...

**Comment by korthout** [comment]
>the nexus cache is only meant for jobs that run on our self-hosted runners

Ah okay, I missed that.

>moving to one of our smaller 8cpu self-hosted runners

That sounds like an overkill for just building a maven artifact.

**Comment by korthout** [comment]
Failing IT is a flaky test: `CompleteProcessInstanceAfterLeaderChangeTest.shouldCompleteProcessInstanceAfterLeaderChangeWithSnapshot`.

CodeQL job took 11min (same as IT job) 🎉

**Review by lenaschoenburg — APPROVED** [review]
Love it, thanks @korthout! :+1:

**Comment by korthout** [comment]
@oleschoenburg Merged by bors in 15 min after your request 🎉

**Pull request merged**
