### PR TITLE
feat: initialize identity even when authorizations are disabled

### LINKED ISSUE #25700: [General][Engine] create default user independently from authorizations enabled
### Description
Currently, when the single application starts we [initialise Identity with a default user](https://github.com/camunda/camunda/blob/main/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/user/IdentitySetupInitializer.java) however this is only run when authorizations are enabled. 

The creation of a user should be independent of authorizations being enabled.

### Acceptance criteria
- [ ] When the single application is started, the demo user is created (with role)

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This changes the identity initialization to _always_ run, even when authorizations are disabled. This is so that Identity can always see the default user and role.

:thought_balloon: Initially the issue was just about creating the default user and role. We now also include the role's wildcard permissions and the default tenant.

closes #25700

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@koevskinikola Do you have capacity to review this?

**Comment by koevskinikola** [comment]
@remcowesterhoud not today. Is tomorrow (12.12.2024) okay?

**Comment by remcowesterhoud** [comment]
I won't get around to this today either, so that's fine with me. @lenaschoenburg hope you're fine with it too 😄

**Comment by koevskinikola** [comment]
@lenaschoenburg @remcowesterhoud FYI to avoid duplicate reviews, I'll start reviewing this PR now.

**Review by koevskinikola — APPROVED** [review]
LGTM @lenaschoenburg  🎉

**Comment by lenaschoenburg** [comment]
Thanks for the review! I rebased to resolve conflicts with the new configurable default user creation.

**Comment by lenaschoenburg** [comment]
In combination with https://github.com/camunda/camunda/commit/768a1980461f2d0edc6e90220be55ad5dea4de2f, this breaks the `ReplayStateTest` because a restart will again write `IdentitySetup/Initialize` which then generates a new key to write `IdentitySetup/Initialized`.
I'm not sure what to do about this, I guess we need to re-introduce a duplication check somewhere? cc @remcowesterhoud and @koevskinikola

**Comment by remcowesterhoud** [comment]
> In combination with [768a198](https://github.com/camunda/camunda/commit/768a1980461f2d0edc6e90220be55ad5dea4de2f), this breaks the `ReplayStateTest` because a restart will again write `IdentitySetup/Initialize` which then generates a new key to write `IdentitySetup/Initialized`. I'm not sure what to do about this, I guess we need to re-introduce a duplication check somewhere? cc @remcowesterhoud and @koevskinikola

Can we somehow detect if the `auth-basic` or `auth-oidc` profile is set? If we can we could use this to determine whether this initializer should run.

**Comment by lenaschoenburg** [comment]
> Can we somehow detect if the auth-basic or auth-oidc profile is set? If we can we could use this to determine whether this initializer should run.

I don't think so, we want to keep Spring out of the engine.

**Comment by remcowesterhoud** [comment]
> > Can we somehow detect if the auth-basic or auth-oidc profile is set? If we can we could use this to determine whether this initializer should run.
> 
> I don't think so, we want to keep Spring out of the engine.

If we can set a property depending on the profile we could use it to set a config option which we could access in the engine. Idk if that's possible though, let me see.

**Comment by lenaschoenburg** [comment]
Sure but is that really the right direction? I'd rather not disable this in tests, otherwise bugs such as https://github.com/camunda/camunda/pull/25752 become really difficult to spot before they get released.

**Comment by lenaschoenburg** [comment]
Or reintroduce the checks that prevent the `IdentitySetupInitializeProcessor` generates new keys if it is not needed?

**Comment by remcowesterhoud** [comment]
You'd still be writing the records. It's pretty annoying having do consider those records in every single test case we have. Personally I still feel disabling it depending on the profile is the way to go

**Comment by lenaschoenburg** [comment]
> It's pretty annoying having do consider those records in every single test case we have

That's true. It's partially solved now because `EngineRule` awaits the setup and resets the `RecordingExporter`

**Comment by lenaschoenburg** [comment]
@remcowesterhoud d18b41f6230702b99cc334a6ff123765a03f118c contains the necessary changes to reject the `Initialize` command when all of the default entities already exist. That way we don't always generate new keys.

**Review by remcowesterhoud — APPROVED** [review]
Seems like a decent solution to me without having to duplicate it all in the initializer 👍

**Pull request merged**
