### PR TITLE
feat(dist): Remove the `-xms` parameter

### LINKED ISSUE #12416: Remove the default un-overridable `-Xms128m` value
**Is your feature request related to a problem? Please describe.**
It is hard to tune the JVM if I cannot override the default `-Xms128m`. I can't override it via `JAVA_OPTS` because it is used at first, and then goes explicit `-Xms128m` (and finally applied):
```
exec "$JAVACMD" $JAVA_OPTS -Xms128m -XX:+ExitOnOutOfMemoryError -Dfile.encoding=UTF-8...
```

**Describe the solution you'd like**
I would like to move all JVM options into the default Docker environment variable (`JAVA_OPTS`) so that users could override it easily (`-Xms` included).

**Describe alternatives you've considered**
We could just remove `-Xms128m` from the default options, but I can't predict the consequences.

**Additional context**
See the details [here](https://camunda-platform.slack.com/archives/C6WGNHV2A/p1681141205701259).
I would like to see the changes backported in 8.0, 8.1, 8.2 as well 🙂

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

Removing the default un-overridable `-xms` param.

## Related issues

closes #12416 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by Zelldon** [comment]
Thanks @aivinog1 I will run a benchmark to verify that nothing breaks with our charts or docker setup :)

**Comment by aivinog1** [comment]
@Zelldon It seems to be that the macos build was timeout 🤔 
May you retry this one? I don't see any clear issue, how could I break Maven's performance 😅 
Also, in the future we could [add timings](https://stackoverflow.com/a/49494561/11112760), to figure out where time was spent :)

**Review by ChrisKujawa — APPROVED** [review]
Benchmarks look good to me

General:
xms

Memory

Base left - xms change on the right

mm

Thanks @aivinog1

**Comment by aivinog1** [comment]
@Zelldon Can you please add the 8.2 version to the backport as well? 
Thank you 🙂

P.S. Backport PRs aren't created as well 🤔

**Comment by aivinog1** [comment]
> P.S. Backport PRs aren't created as well 🤔
@Zelldon I think that you should approve that: https://github.com/camunda/zeebe/actions/runs/4744405818

**Comment by remcowesterhoud** [comment]
Oops, we missed the 8.2 label.

/backport

**Pull request merged**
