### PR TITLE
Remove internal temporary variables store

### LINKED ISSUE #6982: Remove temporary variables
**Description**
Remove all usages of temporary variables in order to unify the usage and simplify the engine. 

Temporary variables are used internally to store variables (of jobs or messages) until they are used to apply the variable output mappings of the event scope.

In some places, the usage was replaced already by storing the variables in the event trigger.

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Removed the usage of temporary variables. Temporary variables are used internally to store variables (of jobs or messages) until they are used to apply the variable output mappings of the event scope.

They have been replaced with local variables or event triggers.

## Related issues

closes #6982 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by saig0 — CHANGES_REQUESTED** [review]
@remcowesterhoud thank you for the refactoring :+1: It is a big improvement and removes some complicated code :wastebasket: 

I've some minor issues but nothing major. Please have a look.

**Review by saig0 — CHANGES_REQUESTED** [review]
@remcowesterhoud thanks for applying the hints. We're almost done. 

I've some minor suggestions. Please have a look :cake:

**Comment by remcowesterhoud** [comment]
@saig0 Thanks again for the review 😄 

As discussed I've fixed them all apart from writing the triggered event.

**Review by saig0 — APPROVED** [review]
@remcowesterhoud thanks. It looks very good now :tada: 

I propose to create a follow-up PR to write `ProcessEvent: triggered`. I think we could write the event when processing the `complete` command of the start event (after applying the output mappings). What do you think?

Since the PR is done, we should also talk about https://github.com/camunda-cloud/zeebe/pull/7916#discussion_r722887100 (in a meeting).

BTW: we should inform the team about the change (e.g. in the team meeting).

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
@saig0 About writing the `ProcessEvent: Triggered` in the complete of the start event. I feel like this would not be in line with all the other events. Correct me if I'm wrong but I think the usual order is:
`TRIGGERING -> ACTIVATING -> ACTIVATED -> TRIGGERED -> COMPLETING -> COMPLETED`

If we implement your proposal it would become a different for event sub process start events:
`TRIGGERING -> ACTIVATING -> ACTIVATED -> COMPLETING -> TRIGGERED -> COMPLETED`

Wouldn't this cause confusion?

**Pull request merged**
