### PR TITLE
add test for compaction when exporter is slow

### LINKED ISSUE #4371: Add integration tests to verify not exported events are not compacted
**Description**

#4350 is because we were compacting non exported events. We are still missing an integration test for it.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

- Verify that not exported events are not compacted

## Related issue

closes #4371

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
With the latest version of the test, do we need to write more segments once we stop exporting? Writing a few records would be enough, no? Just thinking out loud :thinking: 

Also, how complicated would it be to test that if we start exporting again, then we would compact properly again? :sweat_smile:

**Comment by deepthidevaki** [comment]
> With the latest version of the test, do we need to write more segments once we stop exporting? Writing a few records would be enough, no? Just thinking out loud thinking
> 

We have to make sure the last processed position is in the next segment. Otherwise, it will anyway not compact that segment. So we are not really testing this particular case.

> Also, how complicated would it be to test that if we start exporting again, then we would compact properly again? sweat_smile

I have added that to the test. Adding a new test for that seems to be redundant. So I extended the current one.

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by npepinpe** [comment]
I guess merging is blocked until we merge https://github.com/zeebe-io/zeebe/pull/4374

**Comment by npepinpe** [comment]
Sorry, thought it was already a single commit :sweat_smile:

**Comment by deepthidevaki** [comment]
:) I will rebase and merge.

**Comment by deepthidevaki** [comment]
bors retry

**Comment by deepthidevaki** [comment]
bors retry

**Comment by Zelldon** [comment]
@deepthidevaki @npepinpe should we backport this then as well? This is actually part of a bug fix right?

**Comment by deepthidevaki** [comment]
I don't know. At the time of this PR we were not actively backporting everything. Also this is only adding a test. On the otherhand it will be easy to backport.

**Pull request merged**
