### PR TITLE
Add git pre-commit script to check formatting and style

### PR DESCRIPTION
**Pull request by menski**
This adds a small maven plugin `github-hooks` which installs and updates a git pre-commit script in the `initialize` phase of the zeebe-root module. After that on every commit which changed java files a minimal maven run is executed to validate the license header, code format and style.

### CODE REVIEW

**Comment by npepinpe** [comment]
Looks good, the only worry I have is about running maven offline, which is a little hidden and I don't know if it'll be obvious that it fails due to missing dependencies, but I guess everyone should have the dependencies pretty much up to date in their environment usually, so shouldn't be an issue.

**Review by npepinpe — APPROVED** [review]

**Comment by menski** [comment]
My reasoning was if they run maven once to install the hook they basically should have the checker dependencies. I'm also fine with removing the offline flag, it is probably only a speed improvement on the first run of a day.

**Comment by npepinpe** [comment]
Leave it for now, I'm not even sure if it'd be a problem, if it happens we can remove it.

**Comment by menski** [comment]
bors retry

**Pull request merged**
