### PR TITLE
ci: rename shared library function

### PR DESCRIPTION
**Pull request by cmur2**
## Description

Related to https://github.com/camunda/jenkins-global-shared-library/pull/196

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
Can this be merged already?

**Comment by cmur2** [comment]
> Can this be merged already?

@npepinpe jup, I just logged in to see whether it is green - it is, so it can be merged!

**Comment by cmur2** [comment]
bors merge

**Comment by cmur2** [comment]
bors retry

**Pull request merged**
