### PR TITLE
feat: add listener event type property to JobRecord

### LINKED ISSUE #19589: Add `jobListenerEventType` property to JobRecord for Execution and Task Listeners jobs
## Description:
Enhance the `JobRecord` class in the Zeebe workflow engine to include a new property that specifies the event type for jobs of kind `EXECUTION_LISTENER` and `TASK_LISTENER`. This enhancement will provide detailed context on the type of event associated with these listener jobs, facilitating better processing and handling within the workflow engine and other tools (e.g. Operate).

### Task details:
1. **Introduce a new enum `JobListenerEventType`**:
   - Define values: 
     - `UNDEFINED` - default
     - `START` - for start EL
     - `END` - for end EL
> Note: values  for user task listeners we can defined later

2. **Add a new property `jobListenerEventTypeProp` to the `JobRecord` class and `JobRecordValue` interface**:
   - Use the `EnumProperty<JobListenerEventType>` type.
   - Integrate this property within the `JobRecord` class alongside existing properties.
   - Update relevant methods to handle the new property, including getters and setters.

3. **Configuration files update:**:
   - Update the Elasticsearch/OpenSearch exporter configuration files, to include and expose the `jobListenerEventType` property: 
     - zeebe-record-job-template.json
     - zeebe-record-job-batch-template.json

4. **Testing**:
   - Write unit tests to verify the correct handling and assignment of the `jobListenerEventTypeProp` property.

### Benefits:
- Provides enhanced context and specificity for `execution` and `task listener` jobs.
- Facilitates improved processing and debugging of listener events within the Zeebe and Operate applications.

### PR DESCRIPTION
**Pull request by ce-dmelnych**
## Description
This PR enhances the `JobRecord` class by adding a new property that specifies the event type for jobs of kind `EXECUTION_LISTENER` and adjusts it for the future usage of `TASK_LISTENER`. This enhancement aims to provide context on the type of event associated with these listener jobs, facilitating better processing and handling within the workflow engine and other services like Operate.

### Key changes
1. Introduce a new enum `JobListenerEventType`:
   - Defined values: `UNSPECIFIED`, `START`, `END`.
   - Added JavaDocs for each value to describe its purpose and usage.

2. Add a new property to the `JobRecord` class and `JobRecordValue` interface:
   - Added a method `JobListenerEventType getJobListenerEventType()` to `JobRecordValue` interface.
   - Integrated `jobListenerEventTypeProp` property within the `JobRecord` class alongside existing properties.

3. Update the Elasticsearch/OpenSearch exporters configuration files, to include and expose the `jobListenerEventType` property:
   - zeebe-record-job-template.json
   - zeebe-record-job-batch-template.json

4. Testing:
   - Updated unit tests to verify the correct handling and assignment of the `listenerEventTypeProp` property.

### Benefits
- Provides enhanced context and specificity for execution listener jobs.
- Facilitates improved processing and debugging of listener events within the Zeebe workflow engine.

## Related issues

closes #19589

### CODE REVIEW

**Review by tmetzke — COMMENTED** [review]
👍 The changes look good to me.
❓ I have a general question though: do we need a second enum for this? We now have `ExecutionListenerEventType` and the new `ListenerEventType`. Isn't having one of them enough?

**Comment by ce-dmelnych** [comment]
> 👍 The changes look good to me. ❓ I have a general question though: do we need a second enum for this? We now have `ExecutionListenerEventType` and the new `ListenerEventType`. Isn't having one of them enough?

Yeah, nice catch @tmetzke, and both lay on the same level in the `io.camunda.zeebe.protocol.record.value` package.
So, looks like we can have only  `io.camunda.zeebe.protocol.record.value. ListenerEventType` and enhance it later with the types that will be used by User Task listener jobs.

I'll try to simplify it)

**Review by tmetzke — APPROVED** [review]
Looks good to me 👍 
@saig0, feel free to add any feedback from your end still 🙂

**Comment by ce-dmelnych** [comment]
> 👍 The changes look good to me. ❓ I have a general question though: do we need a second enum for this? We now have `ExecutionListenerEventType` and the new `ListenerEventType`. Isn't having one of them enough?

@tmetzke,

I've consolidated the `ExecutionListenerEventType` enum into the `ListenerEventType` enum. 
And now, in `io.camunda.zeebe.engine.processing.deployment.model.element.ExecutionListener`, we are using the `ZeebeExecutionListenerEventType` enum from the `zeebe/bpmn-model` module used .

I have some doubts about whether this approach is fully acceptable, as I haven't seen similar solutions within the `io.camunda.zeebe.engine.processing.deployment.model.element` package.

Hmm, what do you think, is it ok?
probably we will have a similar situation for user task listeners later.

**Comment by tmetzke** [comment]
> > 👍 The changes look good to me. ❓ I have a general question though: do we need a second enum for this? We now have `ExecutionListenerEventType` and the new `ListenerEventType`. Isn't having one of them enough?
> 
> @tmetzke,
> 
> I've consolidated the `ExecutionListenerEventType` enum into the `ListenerEventType` enum. And now, in `io.camunda.zeebe.engine.processing.deployment.model.element.ExecutionListener`, we are using the `ZeebeExecutionListenerEventType` enum from the `zeebe/bpmn-model` module used .
> 
> I have some doubts about whether this approach is fully acceptable, as I haven't seen similar solutions within the `io.camunda.zeebe.engine.processing.deployment.model.element` package.
> 
> Hmm, what do you think, is it ok? probably we will have a similar situation for user task listeners later.

Alternatively, you could use the `ListenerEventType` enum in the model code directly as well. No further transformation would be required later on in the processing.

**Comment by ce-dmelnych** [comment]
> > > 👍 The changes look good to me. ❓ I have a general question though: do we need a second enum for this? We now have `ExecutionListenerEventType` and the new `ListenerEventType`. Isn't having one of them enough?
> > 
> > 
> > @tmetzke,
> > I've consolidated the `ExecutionListenerEventType` enum into the `ListenerEventType` enum. And now, in `io.camunda.zeebe.engine.processing.deployment.model.element.ExecutionListener`, we are using the `ZeebeExecutionListenerEventType` enum from the `zeebe/bpmn-model` module used .
> > I have some doubts about whether this approach is fully acceptable, as I haven't seen similar solutions within the `io.camunda.zeebe.engine.processing.deployment.model.element` package.
> > Hmm, what do you think, is it ok? probably we will have a similar situation for user task listeners later.
> 
> Alternatively, you could use the `ListenerEventType` enum in the model code directly as well. No further transformation would be required later on in the processing.

Yep, I also thought about it, but it would be less clear why the `eventType` property in `ExecutionListener` could later have values like `CREATE` or `ASSIGN`.)

**Comment by tmetzke** [comment]
> > Alternatively, you could use the `ListenerEventType` enum in the model code directly as well. No further transformation would be required later on in the processing.
> 
> Yep, I also thought about it, but it would be less clear why the `eventType` property in `ExecutionListener` model could later have values like `CREATE` or `ASSIGN`.)

Yeah, might be less clear. I am personally fine with the two enums to 
1. Have a clear scope for the modeling phase (only start and end are possible).
2. Have one overall enum for all possible listener states in the processing phase. The correct modeling has been checked before already.

**Comment by ce-dmelnych** [comment]
> Yeah, might be less clear. I am personally fine with the two enums to
> 
> 1. Have a clear scope for the modeling phase (only start and end are possible).
> 2. Have one overall enum for all possible listener states in the processing phase. The correct modeling has been checked before already.

Got it!
Let's wait to see what @saig0 suggests also)

**Review by saig0 — APPROVED** [review]
@ce-dmelnych looks good. :+1: 

I have a suggestion for a different enum name. Please have a look. :cookie:

**Review by houssain-barouni — APPROVED** [review]

**Pull request merged**
