### PR TITLE
Add broker configuration for batch processing

### LINKED ISSUE #11545: Add broker configuration for batch processing
**Description**

part of https://github.com/camunda/zeebe/issues/11416

Add additional (new) configuration for changing the `processingBatchLimit` in the StreamProcessor. Made available via https://github.com/camunda/zeebe/pull/11527

* Per default this value should be set to `100`, currently done in the StreamProcessorContext.
* Add note that if setting to `1` it will work as previous processing.
* Potentially we need to add a new config object for processing in general (?)

### PR DESCRIPTION
**Pull request by lenaschoenburg**
closes #11545

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
