### PR TITLE
chore(ci): use consistent spacing for CI pipeline files

### PR DESCRIPTION
**Pull request by cmur2**
## Description

Use consistent spacing for CI pipeline files:
- currently there is a mixture (inside the same file) between 2 and 4 spaces
- I personally have no preference what to use but 4 seems more common

### CODE REVIEW

**Comment by Zelldon** [comment]
Thanks @cmur2 I formatted the files based on your proposed editorconfig

**Review by ChrisKujawa — APPROVED** [review]
bors r+

**Comment by cmur2** [comment]
> Thanks @cmur2 I formatted the files based on your proposed editorconfig

Thanks @Zelldon for your time and effort for this, I'm very grateful!

**Pull request merged**
