### PR TITLE
feat(clients/java): change DEFAULT_JOB_WORKER_NAME property value

### LINKED ISSUE #3231: Change name to property "zeebe.client.job.worker"
Looking at class ClientProperties in the io.zeebe.client package, it specifies several properties. I'm referring to this one:

/** @see ZeebeClientBuilder#defaultJobWorkerName(String) */
  public static final String DEFAULT_JOB_WORKER_NAME = "zeebe.client.job.worker";

IMHO it should be renamed to somenthing likke:

"zeebe.client.job.workerName" or a more hierarchical  one (more future proof) like "zeebe.client.job.worker.name"

### PR DESCRIPTION
**Pull request by spulci**
It closes #3231 . 
**Please note that I can build just the submodule clients/java locally (with tests)** I've got issues building the entire project actually.

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
Thank you :+1:

**Comment by Zelldon** [comment]
@saig0 can we merge this?

**Comment by saig0** [comment]
Yes! I forgot to trigger bors :see_no_evil:

**Comment by saig0** [comment]
bors retry

**Comment by saig0** [comment]
bors r+ 

:imp:

**Pull request merged**
