### PR TITLE
test: use always CamundaExporter

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

In integration tests, we should make sure to always use the CamundaExporter to get early feedback.

### Current state:

 * With creating and writing the treePath in the engine #25501 
 * And exporting the tree path https://github.com/camunda/camunda/pull/25531

We should be able to run all IT with the CamundaExporter

### Old

Most API tests were running already \cc @tmetzke 

#### User tasks

@panagiotisgts @romansmirnov Regarding the user task tests I see the following errors:

```
5:15:40.465 [Broker-0] [Exporter-1] [zb-fs-workers-1] WARN  io.camunda.exporter.store.ElasticsearchBatchRequest - Bulk request execution failed. BulkResponseItem: {"index":{"_id":"2251799813685261","_index":"tasklist-task-8.5.0_","status":400,"error":{"type":"strict_dynamic_mapping_exception","reason":"[1:72] mapping set to strict, dynamic introduction of [join] within [_doc] is not allowed"}}}. Cause: [1:72] mapping set to strict, dynamic introduction of [join] within [_doc] is not allowed.
15:15:40.466 [Broker-0] [Exporter-1] [zb-fs-workers-1] WARN  io.camunda.zeebe.broker.exporter.camundaExporter - Error on exporting record with key 2251799813685261
io.camunda.zeebe.exporter.api.ExporterException: Operation failed: [1:72] mapping set to strict, dynamic introduction of [join] within [_doc] is not allowed
	at io.camunda.exporter.CamundaExporter.flush(CamundaExporter.java:196) ~[classes/:?]
	at io.camunda.exporter.CamundaExporter.export(CamundaExporter.java:152) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$export$5(ExporterContainer.java:245) ~[classes/:?]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:59) ~[classes/:?]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:35) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:244) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:222) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.RecordExporter.export(RecordExporter.java:78) ~[classes/:?]
	at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:85) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [classes/:?]
Caused by: io.camunda.exporter.exceptions.PersistenceException: Operation failed: [1:72] mapping set to strict, dynamic introduction of [join] within [_doc] is not allowed
	at io.camunda.exporter.store.ElasticsearchBatchRequest.execute(ElasticsearchBatchRequest.java:239) ~[classes/:?]
	at io.camunda.exporter.store.ElasticsearchBatchRequest.execute(ElasticsearchBatchRequest.java:217) ~[classes/:?]
	at io.camunda.exporter.store.ExporterBatchWriter.flush(ExporterBatchWriter.java:76) ~[classes/:?]
	at io.camunda.exporter.CamundaExporter.flush(CamundaExporter.java:193) ~[classes/:?]
	... 14 more
```

Looks like the the schema creation failed? Is it because there some old schemas in tasklist?! 

#### TreePath

Is failing because treePaths are null

```
 @Test
  void shouldQueryFlowNodeInstanceByTreePath() {
    // given
    final var treePath = flowNodeInstance.getTreePath();
    // when
    final var result =
        zeebeClient.newFlownodeInstanceQuery().filter(f -> f.treePath(treePath)).send().join();

    // then
    assertThat(result.items().size()).isEqualTo(1);
    assertThat(result.items().getFirst().getTreePath()).isEqualTo(treePath);
  }

```

Query returns 20 elements. @tmetzke @sdorokhova  I guess makes sense as we don't have yet the changes for the scope key?

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Comment by mustafadagher** [comment]
I think the error is because importer is still running and creating an older version of the schema. if we disable the importer, more issues will appear as well.
Some of these issue might be related to this https://github.com/camunda/camunda/issues/24736

**Comment by Zelldon** [comment]
Discussed with @romansmirnov the user task issues as well. Exactly is as you mentioned @mustafadagher that we have a schema created by (tasklist?), which might be outdated and break the exporting.

**Comment by panagiotisgts** [comment]
Shouldn't the Exporter's Schema Manager run and apply the diffs? In my local testing scenarios, the diffs were applied correctly (at least a couple of days ago).

I used to run Tasklist to generate the initial schema and use the data generator for test data and then run the CamundaExporter to extend the indices with the new fields. Then run the Exporter/Migration service for the required scenarios I wanted. For Tasklist's modified indices only new fields are added and should be able to do the update successfully.

**Comment by ChrisKujawa** [comment]
Yesterday, discussed with @romansmirnov 

```
io.camunda.zeebe.exporter.api.ExporterException: Operation failed: [1:72] mapping set to strict, dynamic introduction of [join] within [_doc] is not allowed
	at io.camunda.exporter.CamundaExporter.flush(CamundaExporter.java:196) ~[classes/:?]
	at io.camunda.exporter.CamundaExporter.export(CamundaExporter.java:152) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.lambda$export$5(ExporterContainer.java:245) ~[classes/:?]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runCheckedWithClassLoader(ThreadContextUtil.java:59) ~[classes/:?]
	at io.camunda.zeebe.util.jar.ThreadContextUtil.runWithClassLoader(ThreadContextUtil.java:35) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:244) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:222) ~[classes/:?]
	at io.camunda.zeebe.broker.exporter.stream.RecordExporter.export(RecordExporter.java:78) ~[classes/:?]
	at io.camunda.zeebe.scheduler.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:85) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:42) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [classes/:?]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [classes/:?]
Caused by: io.camunda.exporter.exceptions.PersistenceException: Operation failed: [1:72] mapping set to strict, dynamic introduction of [join] within [_doc] is not allowed
	at io.camunda.exporter.store.ElasticsearchBatchRequest.execute(ElasticsearchBatchRequest.java:239) ~[classes/:?]
	at io.camunda.exporter.store.ElasticsearchBatchRequest.execute(ElasticsearchBatchRequest.java:217) ~[classes/:?]
	at io.camunda.exporter.store.ExporterBatchWriter.flush(ExporterBatchWriter.java:76) ~[classes/:?]
	at io.camunda.exporter.CamundaExporter.flush(CamundaExporter.java:193) ~[classes/:?]
	... 14 more
```

Should go away soon, as we make use of the webapps-schema classes and templates in Tasklist soon, so we should avoid the conflicts soon.

**Review by mustafadagher — APPROVED** [review]

**Pull request merged**
