### PR TITLE
[Forwards 8.3]: Refactor long polling

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Forwards https://github.com/camunda/zeebe/pull/15229

There were some merge conflicts, mainly because of the timeout added to the handler and the cancel handler for the observer. I hope I didn't break anything 😅

### CODE REVIEW

**Comment by npepinpe** [comment]
I think it breaks the test to cancel the activate jobs command :thinking: Not that it's a robust test in the first place :smile:

**Comment by Zelldon** [comment]
@npepinpe the problem was the registering of the onCancelHandler, as you described some week ago that this is not allowed.

**Comment by Zelldon** [comment]
Tests are green now ✅ 🚀

**Comment by Zelldon** [comment]
@npepinpe would be nice to get it merged.

**Review by npepinpe — APPROVED** [review]
:rocket:

**Comment by Zelldon** [comment]
Bors r+

**Pull request merged**
