### PR TITLE
feat: add scope parameter to zeebe client oauth credentials

### LINKED ISSUE #15391: Allow setting `scope` parameter for OAuth2 authentication
**Is your feature request related to a problem? Please describe.**
To add support for authentication via [Microsoft Entra ID (Azure AD) and generic OpenID Connect](https://github.com/camunda/product-hub/issues/739) it is required to set the `scope` parameter in the token request, see [Microsoft Entra ID docs](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret). Currently the Zeebe java client does not support setting the `scope` parameter.

**Describe the solution you'd like**
The Zeebe client supports setting the `scope` parameter in the token request (for example in https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/impl/oauth/OAuthCredentialsProvider.java#L125)

**Describe alternatives you've considered**
Use Identity-sdk which supports creating auth tokens.

**Additional context**
- When using Microsoft Entra ID, the scope parameter has to contain the client api in a specific format, for example `scope=4393964b-2273-4b23-94fa-98c3d2396b1e/.default`
- The additional parameter has to also be integrated into [`spring-zeebe`](https://github.com/camunda-community-hub/spring-zeebe) since it is used by Connectors

### PR DESCRIPTION
**Pull request by dlavrenuek**
## Description

Adds a new `scope` parameter to OAuth2 credentials request to support authorization via Microsoft Entra ID. The scopes can be set via a new environment variable `ZEEBE_CLIENT_SCOPE`

## Related issues

Relates to #15391

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by dlavrenuek** [comment]
I have added the new optional `ZEEBE_CLIENT_SCOPE` parameter to both the java and go clients. While I can start `go` tests, it fails for Java with an error class GatewayGrpc is not found in https://github.com/camunda/zeebe/blob/main/gateway-protocol-impl/src/test/java/io/camunda/zeebe/gateway/protocol/ServiceConfigTest.java#L54

**Comment by megglos** [comment]
> I have added the new optional `ZEEBE_CLIENT_SCOPE` parameter to both the java and go clients. While I can start `go` tests, it fails for Java with an error class GatewayGrpc is not found in https://github.com/camunda/zeebe/blob/main/gateway-protocol-impl/src/test/java/io/camunda/zeebe/gateway/protocol/ServiceConfigTest.java#L54.
> 
> The Zeebe team should add documentation where appropriate

The `GatewayGrpc` class is generated, can you try running a full maven build on the project via cmdline?

**Review by megglos — APPROVED** [review]
Looks good code-wise to me!

❓ Multiple scopes would be provided by separting them via space into the scope param?

In terms of docs this is only relevant for SM, right?

**Comment by dlavrenuek** [comment]
@megglos 

>❓ Multiple scopes would be provided by separting them via space into the scope param?

Yes, it's according to OAuth2 standard. The go implementation uses a library that you pass an array of scopes as you can see [here](https://github.com/camunda/zeebe/pull/15404/files#diff-c756e738c78991d60f8450296782594a21e75dbccb5dc41e1c96379115a34e73R136), but these are then just concatenated with a white space in the request.

Bildschirmfoto 2023-11-29 um 15 23 35


> In terms of docs this is only relevant for SM, right?

Yes

**Comment by megglos** [comment]
bors merge

**Comment by megglos** [comment]
bors retry

**Comment by megglos** [comment]
flaky performance test 🙄 
```
EngineLargeStatePerformanceTest.shouldProcessWithinExpectedDeviation:144 Expected reference score is "450.000" got "518.896", deviation "15.310%" exceeds maximum allowed deviation "15.000%"
```

**Comment by megglos** [comment]
bors merge

**Pull request merged**
