### PR TITLE
feat(broker): allow process with multiple start events

### LINKED ISSUE #3317: Support workflows with multiple start events
**Is your feature request related to a problem? Please describe.**
I want to deploy a workflow that has one none start event and one or more timer/message start events. 

**Describe the solution you'd like**
When a workflow instance is created via CREATE command or call activity then the instance starts at the none start event. 

When one of the events is triggered (e.g. a message is correlated) then the instance starts at the corresponding timer/message start event.

**Additional context**
Example BPMN:

image

### PR DESCRIPTION
**Pull request by saig0**
## Description

* allow processes with one none start event and other start events (e.g. timer, message)
* adjust validation for start events
* clean up workflow instance test

## Related issues

closes #3317 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

Looks great, nothing to add, thanks for this!

**Comment by Zelldon** [comment]
What is the state of this?

**Comment by npepinpe** [comment]
I can make sure to merge it, codewise it's done, I guess we just need to fix merge conflicts

**Comment by npepinpe** [comment]
Hm, wouldn't failure detection essentially test this? If we had a way to cause the heart beat to not be sent without actually shutting down the node, then we could test this more explicitly maybe?

**Comment by saig0** [comment]
bors retry

**Pull request merged**
