### PR TITLE
Adds cluster filter variable to Zeebe Grafana dashboards

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR adds the cluster filter variable to the Zeebe Grafana dashboard. This is necessary to support a deployment where we have a single Grafana, but access various Zeebe deployments across multiple Kubernetes clusters.

The changes are simply adding a new variable, making sure all other variables filter on it, and making sure all queries in each dashboard use the cluster filter.

## Related issues

related to zeebe-io/infra#8

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
Thanks :tada: 

:question: I assume filtering based on the cluster would not create any issues in our SaaS. They use the same dashboard, right?

**Comment by npepinpe** [comment]
It's a good question. The cluster label should be present as well, but it should have only one value in SaaS.

**Comment by npepinpe** [comment]
You raise a good point though. What if there is no cluster label? :thinking:

**Comment by deepthidevaki** [comment]
> You raise a good point though. What if there is no cluster label, for those not running on k8s? thinking Actually, what happens now if there is no `namespace` label?

I think it can work with non-existing labels. Besides, the dashboard is not designed for general purpose production. So as long as it works for our benchmarks and SaaS, it would be fine.

**Comment by npepinpe** [comment]
Then it will definitely work in SaaS, the cluster label is present as well.

bors merge

**Pull request merged**
