### PR TITLE
ProcessInstanceCreationCommand with startinstructions in Go client

### LINKED ISSUE #9399: Extend the Go Client's CreateProcessInstance API with start instructions
The Go client should implement the extended CreateProcessInstance API with start instructions.

Specifically, we'll need to add start instructions to the CreateInstanceCommandStep3, the API depends on the design choices made in https://github.com/camunda/zeebe/issues/9388. Let's be inspired by #9398.

Blocked by https://github.com/camunda/zeebe/issues/9388, https://github.com/camunda/zeebe/issues/9396

### PR DESCRIPTION
**Pull request by pihme**
## Description
Adds `startBeforeElement` methods to Go client

## Related issues

closes #9399

## Definition of Done

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [X] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by saig0 — COMMENTED** [review]
@pihme thank you for extending the Go client :+1: 

Looks good :rocket: 
But the Go build is [failing](https://github.com/camunda/zeebe/runs/6832160402?check_suite_focus=true#step:3:27):
```
Error: method parameter `elementId` should be `elementID` (golint)
```

**Comment by pihme** [comment]
@saig0 I know. That's why the PR is still in draft. I still need to put a little more work into it.

**Review by saig0 — APPROVED** [review]
@pihme LGTM :+1:

**Comment by saig0** [comment]
bors merge

**Pull request merged**
