### PR TITLE
Add more metrics to track startup time

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Add new metrics for
* Raft server startup and bootstrap time
* Number of log segments
* Number of files in a snapshot
* Streamprocessor recovery/reprocessing time
* Time taken to open the journal

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

**Comment by deepthidevaki** [comment]
New metrics are visualised as follows:

image

image

image

**Review by miguelpires — CHANGES_REQUESTED** [review]
A few comments:

* most of these metrics are durations of events that only happen once in the lifetime of a broker. I think it's worth discussing if it makes sense to represent them as metrics. The same could be achieved with a log statement right? I guess the information would be less accessible but on the other hand, using the log would preserve previous startup times, whereas a metric will only show the latest one. 
* in the "streamprocessor recovery time", the first bar seems strange. The value is around 4min which is about half of the last value, but it's the first bar is a fraction of the last bar. What's going on there?
* this is not as important but reading a duration like "5.15 min" is misleading since it looks like 5m15s but is actually 5m9s. Ideally, we show the durations as minutes and second but I assume this is a bit complicated to achieve. Maybe we can just settle for rounding the values to a single decimal place, so 1.2 instead of 1.171. We can lose the rest without losing valuable information and it would make it cleaner and easier to parse

**Comment by deepthidevaki** [comment]
> A few comments:
> 
>     * most of these metrics are durations of events that only happen once in the lifetime of a broker. I think it's worth discussing if it makes sense to represent them as metrics. The same could be achieved with a log statement right? I guess the information would be less accessible but on the other hand, using the log would preserve previous startup times, whereas a metric will only show the latest one.

In the visualization it shows only the last metric. But the history will be kept and you can get the value for specific times at any time later. 
I also thought initially metrics are not needed. But now I think looking at the metrics is easier than reading the logs. We can compare different versions, how it varies after each restart etc. Also we are already logging these information - we already log cluster bootstrap time, added raft server startup time in this PR, if you enable debug logging for journal you can calculate the time taken to open the journal.

> 
>     * in the "streamprocessor recovery time", the first bar seems strange. The value is around 4min which is about half of the last value, but it's the first bar is a fraction of the last bar. What's going on there?

It is probably fixable by pinning the lowest value to 0. These graphs usually calculates these values automatically. I will see if I can change it.
> 
>     * this is not as important but reading a duration like "5.15 min" is misleading since it looks like 5m15s but is actually 5m9s. Ideally, we show the durations as minutes and second but I assume this is a bit complicated to achieve. Maybe we can just settle for rounding the values to a single decimal place, so 1.2 instead of 1.171. We can lose the rest without losing valuable information and it would make it cleaner and easier to parse

I will adjust the decimal place. I don't think we can change the display to "5m15s". It is calculated automatically.

**Comment by MiguelPires** [comment]
I see your point. I agree, there's value in being able to easily compare metrics between versions, after restarts, etc. Cool, then it's just a matter of setting the min of the bars to 0 and rounding the durations to the first decimal place. Otherwise, looks good

**Comment by deepthidevaki** [comment]
@MiguelPires I have update the dashboard. Changed min value to 0, changed the display unit to duration instead of time.

**Comment by MiguelPires** [comment]
Do you have a screenshot of the new version?

**Comment by deepthidevaki** [comment]
image

**Review by miguelpires — APPROVED** [review]
Very nice, thank you :+1:

**Pull request merged**
