### PR TITLE
Replace role change with state time line and leader table with topology table

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR replaces the leader table at the top with a topology table, and the Raft role change graph with a state timeline of the role changes.

> **Note** The role change timeline displays horribly when there are too many data points, but it looks great if you filter per namespace, so I think it's an acceptable improvement over the simple graph.

### Topology table

Before:

image

After:

image

### Raft role state timeline

Before:

image

After:

image

You can view it live here: https://grafana.dev.zeebe.io/goto/k12ltpJVz?orgId=1

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
I definitely like the new Topology panel :+1: 

I'm not sure about the raft "Role changes over time" one though because short transitions appear to be less visible than before. Compare the old visualization:
image

to the new one 
image

I'm okay with merging anyway but wanted to point this out in case you or someone else finds this important. I think this is also something @deepthidevaki mentioned somewhere before.

**Comment by npepinpe** [comment]
It's definitely more sensitive yo the interval rate. We can play with the min step to get more accurate visualization as well.

**Comment by npepinpe** [comment]
So you're right. If you zoom in, the transition is present, but as you Zoom out you miss out on smaller/shorter transitions. Note that they're there, but they're so small when zoomed out that they're not visible. It could be that a more contrasting color scheme would show them.

When you view only that graph, but for the same time frame you mentioned:

image

So I just discovered you can also add borders to the boxes! What about this variant?

image

**Comment by Zelldon** [comment]
How about keeping it somewhere, if we need to dig deeper? Could also be a separate dashboard if you think this fits better. I agree that the visualization in general is better from the new panels, but I also have to admit that I might want to see on certain error cases all details. If we see that we don't use it for a longer time I guess we can delete it without issues, but right now this is a panel where I always look at.

**Comment by npepinpe** [comment]
As far as I can tell, it's just a matter of drilling down. By adding borders, you can clearly see when elections occurred, and then zoom in to see the very short lived ones. I think we have all the information there.

That said, there's no harm in keeping the old one just in case, so I'll add it back tomorrow.

**Comment by npepinpe** [comment]
Updated with latest changes.

Role changes:

image


And topology was updated to have same color scheme (contrasting):

image

**Review by lenaschoenburg — CHANGES_REQUESTED** [review]

**Comment by npepinpe** [comment]
Yeah, this is what I get for grabbing whatever Grafana gives me. I wish there was an easier way. The UIDs btw are now almost always added, this is the 3rd time this happened to me automatically without me touching anything :shrug:

**Comment by npepinpe** [comment]
Woo, merge conflicts :smile:

**Comment by npepinpe** [comment]
Next time with such minor change request, would be cool to approve so I wouldn't run into this ;)

**Review by lenaschoenburg — APPROVED** [review]

**Comment by npepinpe** [comment]
Fixing merge conflicts with this is impossible to do confidently :smile: Each commit has 28 conflicts :disappointed:

**Comment by npepinpe** [comment]
I've never hated editing Grafana dashboards so much

**Comment by Zelldon** [comment]
> I've never hated editing Grafana dashboards so much

Totally with you. There must be a better way right? Is there a tool we don't know ? :sweat_smile: I guess with smaller dashboards it would be also easier.

**Comment by npepinpe** [comment]
In the end I just went panel by panel, because Grafana just changes way too many things for no clear reason, sometimes only to change them back again :roll_eyes:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
@Zelldon - closes I found is https://grafana.com/blog/2020/02/26/how-to-configure-grafana-as-code/ where you write your dashboard using code. I don't know if that's so much better :sweat_smile:

**Pull request merged**
