### PR TITLE
C8AS: merge Operate code up until commit 4628c1d23eef253ecd41f1ebfd9e665dd85ea07d

### PR DESCRIPTION
**Pull request by cmur2**
## Description

This PR merges the Operate code basis into the Zeebe repo

> [!Note]
> Everything up until https://github.com/camunda/operate/commit/4628c1d23eef253ecd41f1ebfd9e665dd85ea07d is included from Operate.

### Details

The following commands have been executed:
```
git clone [git@github.com](mailto:git@github.com):camunda/zeebe.git
cd zeebe
git checkout main
git remote add operate-upstream [git@github.com](mailto:git@github.com):camunda/operate.git
git checkout -b c8as-merge
git merge --allow-unrelated-histories operate-upstream/master
```

There were some git merge conflicts resolved:

 * `.editorconfig` - Use the one from Zeebe, then remove section related to “[{*.dsl,*.groovy,Jenkinsfile*}]”
 * `.github/pull_request_template.md`  - Use the one from Zeebe
 * `.github/renovate.json` - Use the one from Zeebe
 * `.gitignore` - Use the one from Zeebe, then append those 3 lines to it: .vscode, .eslintcache, els-snapshots
 * README.md - Use the one from Zeebe. Additionally, create ./operate/README.md with contents from Operate’s README
 * pom.xml - Use the one from Zeebe

The following git patches have been applied:

-  https://github.com/camunda/zeebe/pull/16716/commits/2a7c75be0e7fb6905fa470225b4ec4c1841508b8 (add '-f operate' in Operate CI mvn commands)
- https://github.com/camunda/zeebe/pull/16716/commits/070a4593726497f636f3f23e49dab9eff0603699 (fix E2E tests by removing ‘-f operate’ from mvn)
- https://github.com/camunda/zeebe/pull/16716/commits/0924f783ed0cb8ddec64c83aba12bf835e71cc71 (removes Operate preview-env deploy workflows)

## Related issues

Related to https://github.com/camunda/team-infrastructure/issues/616

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
:rocket:

**Comment by megglos** [comment]
image

**Comment by megglos** [comment]
Alt Text

**Comment by korthout** [comment]
Welcome Operate! 🎉

**Review by houssain-barouni — APPROVED** [review]

**Comment by lzgabel** [comment]
🥳

**Pull request merged**
