### PR TITLE
build: add missing upgrade plan

### PR DESCRIPTION
**Pull request by misiekhardcore**
## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Review by matthewBearCamunda — APPROVED** [review]

**Comment by misiekhardcore** [comment]
@matthewBearCamunda I don't know what's going on here but schema integrity is failing due to a missing 8.6.1 artifact 🤔

**Comment by misiekhardcore** [comment]
@grlimacan I have created this PR but now I am not sure if its needed. It is failing some Cis anyway

**Comment by grlimacan** [comment]
Obsolete with #23168

**Comment by grlimacan** [comment]
Obsolete with https://github.com/camunda/camunda/issues/23168

**Pull request closed without merging**
