### PR TITLE
Add blacklisting panel

### LINKED ISSUE #8263: Show blacklisting in the Grafana Dashboard
**Is your feature request related to a problem? Please describe.**
Came up in a recent [incident review ](https://docs.google.com/document/d/1E03kB3UCfM3l8X0xU7RjzqvOnX8dk4GtKAmH5-_vY60/edit) that it would be nice to see whether instances are blacklisted or not, maybe also the rate of blacklisting.

I realized that we added a while ago the metrics for that, but never added this to the dashboard, see https://github.com/camunda-cloud/zeebe/pull/6715. 

**Describe the solution you'd like**

Either show a graph of blacklisted instance count or just some indication whether instances are blacklisted.

I had yesterday a **hard time**  to find a good visualization, since the count is only exported if there was a new blacklisted instance. If the pod is restarted the metric is not exported. _It might make sense to refill the metric on restart_ OR we need to work with it, but this would mean we can only show limited data, see below.

**Example A - Show an indication that instances are blacklisted**

gauge-blacklisted
gauge-blacklisted-general

In general I like this, since it shows directly whether there is something wrong.
The problem here is if the time frame is smaller (were no instances are blacklisted) than this indication is green. :-1: 

**Example B - Graph**

Showing a graph is not that fruitful, since as described above the metric is not always exported. 
graph-blacklisted

Showing zero for null values
graph-zero-blacklisted

**Example C - Rate**

The rate of such metric is also not really useful, since the change is too rare.

graph-rate-blacklisted

**Example D - Table**
table-blacklisted

Other alternative would be to show in a table the recent count, but this is also very limited (to the time frame) and other

**Describe alternatives you've considered**.

Ideally we would export the metric always, this would simplify things enormous. Then we can choose better one or more of the possible visualization from above.

**Additional context**

Blacklisting always shows that something problematic happened in the process execution (processing). An exception was thrown during the execution, which mostly an indication of a bug. 

I would like to find a good way how we can visualize it and hope someone has some comments, opinion or ideas.

\cc @pihme

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
Add new panels to show blacklisted process instances, in order to avoid searching the whole log for errors.

One panel was added in the general section, so we can directly see whether there are any blacklisted instances in this namespace.

blacklisted

If there are any blacklisted instances, the `None` will change to the actual count in $${\color{red}red}$$

If we want to dig deeper we can take a look at the panel in the processing section which groups by namespace AND partition and shows it as graph so we can clearly see when it increased for a certain partition.

blacklisted-proc

In order show a real example I tried it on INT, which shows us `3953a05c-7c20-41fb-8231-ec283dd2138b-zeebe` with three blacklisted instances. This is BTW a Zeebe cluster from our team on int :sweat_smile: 

blacklisted-proc-int

## Related issues

closes #8263 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Fantastic :heart_eyes: :tada:

bors r+

**Comment by oleschoenburg** [comment]
Whoops, giving @koevskinikola a chance to review too:

bors r-

**Review by koevskinikola — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
