### PR TITLE
Ensure we only generate positive long-typed properties with generated records

### LINKED ISSUE #9317: Refactor ProtocolFactory to only generate positive values for objects of type long
**Description**

The records generated by the protocol factory currently generated random long values. Since the factory is most likely going to be used for exporter related tests, this can break some things down, as we often expect these values to be timestamps. Negative values are invalid for timestamps.

It would have been better if these types carried that kind of information (e.g. instead of longs, we use `Instant`), but this is an acceptable workaround as we don't dramatically reduce the range of values.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR ensures long-typed properties of generated records are always positive. This is a simple workaround, as many of the properties of type long are actually timestamps, or are expected to behave like timestamps. Since other parts will expect these to be positive, at the very least, we can do that here.

NOTE: I added some state in the test, but only use it in the new tests. #9322 will refactor existing tests to use it, so no need to do that here too.

## Related issues

closes #9317 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
The flaky test should be fixed via [this PR ](https://github.com/camunda/zeebe/pull/9313)

**Review by korthout — APPROVED** [review]
LGTM 👍 

Please note that it is common for our records to contain `-1` as a long value, e.g. command keys. Implementations of the exporter API should be aware of this because this non-negative randomizer seems to imply otherwise. 🔧 Perhaps a note about this is warranted with the test cases, to make sure these are not read as requirements.

**Comment by npepinpe** [comment]
That's a good point. This seemed like the safer workaround in my opinion, as it's more likely we forget to add an exception for timestamps than for keys. The factory is not meant anyway to generate all possible records, but rather generate complete ones. If we ever do use it as a means to find test cases (e.g. property based tests) then we probably want something smarter than what we have here.

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
