### PR TITLE
Release fixes

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Release 1.4.0-alpha1 had some issues which required some code changes. These changes should be merged back to develop.

1. The `dmn` artifact was renamed to `zeebe-dmn`. In this update some dependencies were missed.
2. The pipeline failed near the end because some of the go binaries weren't installed at the expected location. By changing this it now fails immediately after the installation if this went wrong. 
3. `go-bindata` is available on the PATH, so there's no need to use the `GOPATH`.

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@npepinpe We did some fixes in the 1.4.0-alpha1 release. I've cherry-picked them to a separate branch so they can be merged back to develop. If this is not the right way to do it please let me know!

**Review by npepinpe — APPROVED** [review]
:tada: 

bors merge

**Pull request merged**
