### PR TITLE
Add id attribute for userTaskForm

### LINKED ISSUE #8153: UserTaskForm should have a default unique id
**Describe the bug**

UserTaskForm should have a default unique id when use bpmn-model API
```
<extensionElements>
      <ns0:userTaskForm>{}</ns0:userTaskForm>
</extensionElements>
```

**To Reproduce**

Code:
```
BpmnModelInstance done = Bpmn.createProcess("user-task-process").startEvent("start").userTask("user-task-id")
        .zeebeUserTaskForm("{}").endEvent("end-id").done();
```

xml:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:ns0="http://camunda.org/schema/zeebe/1.0" id="definitions_6bf3fa67-9bdd-441a-9ee0-1f1ea9d4c4ba" targetNamespace="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL">
  <process id="user-task-process">
    <extensionElements>
      <ns0:userTaskForm>{}</ns0:userTaskForm>
    </extensionElements>
    <startEvent id="start" name="start">
      <outgoing>sequenceFlow_6acfba8a-f75a-4825-8109-8ee8ff441fd9</outgoing>
    </startEvent>
    <userTask id="user-task-id" name="user-task-id">
      <extensionElements>
        <ns0:formDefinition formKey="camunda-forms:bpmn:null"/>
      </extensionElements>
      <incoming>sequenceFlow_6acfba8a-f75a-4825-8109-8ee8ff441fd9</incoming>
      <outgoing>sequenceFlow_63d889fd-ef40-4714-b93d-2cbe44b1e483</outgoing>
    </userTask>
    <sequenceFlow id="sequenceFlow_6acfba8a-f75a-4825-8109-8ee8ff441fd9" sourceRef="start" targetRef="user-task-id"/>
    <endEvent id="end-id" name="end-id">
      <incoming>sequenceFlow_63d889fd-ef40-4714-b93d-2cbe44b1e483</incoming>
    </endEvent>
    <sequenceFlow id="sequenceFlow_63d889fd-ef40-4714-b93d-2cbe44b1e483" sourceRef="user-task-id" targetRef="end-id"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_bb4eff62-c7c8-40dd-9c9f-1b56b1b8423f">
    <bpmndi:BPMNPlane bpmnElement="user-task-process" id="BPMNPlane_e1978e34-f4cb-4175-a21e-3290503da002">
      <bpmndi:BPMNShape bpmnElement="start" id="BPMNShape_90438cb7-2e3c-445a-a9cd-cd141a79aa94">
        <dc:Bounds height="36.0" width="36.0" x="100.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="user-task-id" id="BPMNShape_1982614c-1a9a-495f-9544-030b947ab533">
        <dc:Bounds height="80.0" width="100.0" x="186.0" y="78.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_6acfba8a-f75a-4825-8109-8ee8ff441fd9" id="BPMNEdge_412cb8a5-66ac-481b-a86a-5f9a8b06e680">
        <di:waypoint x="136.0" y="118.0"/>
        <di:waypoint x="186.0" y="118.0"/>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape bpmnElement="end-id" id="BPMNShape_9919d544-b42f-4976-9900-33a688d8b7f1">
        <dc:Bounds height="36.0" width="36.0" x="336.0" y="100.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sequenceFlow_63d889fd-ef40-4714-b93d-2cbe44b1e483" id="BPMNEdge_0fe199dc-5528-4409-bc4c-31f29687b4a4">
        <di:waypoint x="286.0" y="118.0"/>
        <di:waypoint x="336.0" y="118.0"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>

```

**Expected behavior**

UserTaskForm should have a default unique id.

### PR DESCRIPTION
**Pull request by lzgabel**
## Description

Add default id attribute for userTaskForm.

## Related issues
closes #8153 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [x] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by korthout — COMMENTED** [review]
Thanks @Lzgabel for this fix! 🚀 

The change itself looks good, but I'd prefer to also add a test case to [UserTaskBuilderTest](https://github.com/camunda-cloud/zeebe/blob/develop/bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/builder/UserTaskBuilderTest.java) for this change. 

Can you please add it?

**Comment by Lzgabel** [comment]
> Can you please add it?

Done. Can you review it?

**Review by korthout — APPROVED** [review]
Thanks @Lzgabel

LGTM 🎉 

bors merge

**Comment by korthout** [comment]
@Lzgabel It seems there is a formatting problem:

```

Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.17.3:check (spotless-check) on project zeebe-bpmn-model: The following files had format violations:
    src/test/java/io/camunda/zeebe/model/bpmn/builder/UserTaskBuilderTest.java
        @@ -94,8 +94,8 @@
         ············.endEvent()
         ············.done();
         
        -····final·Collection<ZeebeUserTaskForm>·zeebeUserTaskForms·=·instance
        -········.getModelElementsByType(ZeebeUserTaskForm.class);
        +····final·Collection<ZeebeUserTaskForm>·zeebeUserTaskForms·=
        +········instance.getModelElementsByType(ZeebeUserTaskForm.class);
         
         ····assertThat(zeebeUserTaskForms).hasSize(1);
         ····final·ZeebeUserTaskForm·zeebeUserTaskForm·=·zeebeUserTaskForms.iterator().next();
Run 'mvn spotless:apply' to fix these violations.
```

Please fix the problem by following the suggestion above: `mvn spotless:apply`

**Comment by Lzgabel** [comment]
> @Lzgabel It seems there is a formatting problem

Done, my bad.

**Comment by korthout** [comment]
bors retry

**Comment by korthout** [comment]
@Lzgabel I'm sorry to say, but there are test failures:

Running: `mvn test -pl :zeebe-bpmn-model`

Results:
```
[ERROR] Failures:
[ERROR]   BpmnDiTest.testBpmnPane:106
Expecting actual not to be null
[ERROR]   BpmnDiTest.testDiagramElementTypes:164
Expecting actual not to be null
[ERROR]   FlowNodeTest.testUpdateIncomingOutgoingChildElements:66
Expecting actual:
  []
to contain exactly (and in same order):
  [io.camunda.zeebe.model.bpmn.impl.instance.SequenceFlowImpl@70e889e9]
but could not find the following elements:
  [io.camunda.zeebe.model.bpmn.impl.instance.SequenceFlowImpl@70e889e9]

[ERROR]   ZeebeUserTaskFormTest>AbstractModelElementInstanceTest.testAttributes:138
Actual and expected should have same size but actual size is:
  0
while expected size is:
  1
Actual was:
  []
Expected was:
  [org.camunda.bpm.model.xml.impl.type.attribute.StringAttribute@f4cfd90]
[ERROR] Errors:
[ERROR]   BpmnDiTest.shouldNotRemoveBpmElementReference:184 NullPointer Cannot invoke "i...
[ERROR]   BpmnDiTest.testBpmnEdge:153 NullPointer Cannot invoke "io.camunda.zeebe.model....
[ERROR]   BpmnDiTest.testBpmnLabel:142 NullPointer Cannot invoke "io.camunda.zeebe.model...
[ERROR]   BpmnDiTest.testBpmnShape:129 NullPointer Cannot invoke "io.camunda.zeebe.model...
[ERROR] Tests run: 964, Failures: 4, Errors: 4, Skipped: 0
```

**Comment by Lzgabel** [comment]
> @Lzgabel I'm sorry to say, but there are test failures:

@korthout I'm sorry to hear that, but it seems that I haven't changed the code, should I need to rebase ?

**Comment by korthout** [comment]
bors cancel

**Comment by korthout** [comment]
bors cancel

**Comment by Lzgabel** [comment]
> @Lzgabel I'm sorry to say, but there are test failures:

@korthout I'm very sorry that my negligence led to two build failures. I adjusted the parent class  of `ZeebeUserTaskForm` from `BaseElement` to `BpmnModelElementInstance` , and modified some test cases, and passed the test. 

image

**Comment by korthout** [comment]
No worries @Lzgabel, happy to see you're actively fixing these issues. I'll take a look at it tomorrow 🙂

**Review by korthout — CHANGES_REQUESTED** [review]
I like to start by saying that I really like this change. Great job 🎖️ 

The main difficulty is that it is a breaking change and so revapi fails its API check. You can see this error by running: `mvn verify -pl :zeebe-bpmn-model`.
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.14.5:check (check) on project zeebe-bpmn-model: The following API problems caused the build to fail:
[ERROR] java.class.noLongerInheritsFromClass: class io.camunda.zeebe.model.bpmn.impl.instance.zeebe.ZeebeUserTaskFormImpl: Class no longer inherits from 'io.camunda.zeebe.model.bpmn.impl.instance.BaseElementImpl'.
[ERROR]
[ERROR] Consult the plugin output above for suggestions on how to ignore the found problems.
```

However, we can accept this breaking change. Users would generally not assign an instance of `ZeebeUserTaskForm` in a variable with type `BaseElement` or `BaseElementImpl`, but rather use the `ZeebeUserTaskForm` type. Additionally, the available methods on `BaseElement` are likely unused for such instances.

To allow the breaking change you'll need to explicitly ignore this change by adding the json snippet from the logged error to the configuration in `bpmn-model/revapi.json`. Just run the maven command above and it provides what you need. Let me know if you need help with resolving this.

Lastly, please have a look at my comments, those are not blocking but might be worth to consider. After that we should be able to get this merged.

Thanks again for the work on this. It's really appreciated 🙇

**Review by korthout — COMMENTED** [review]
LGTM 💯  Thanks so much @Lzgabel 🥇 

Seems we're having some problems with our [CLA bot](https://github.com/camunda-cloud/zeebe/blob/develop/CONTRIBUTING.md#contributor-license-agreement). You should've been asked to sign this when you opened the pull request. We're investigating what's going wrong here and I'll get back to you as soon as I can. I apologize for the inconvenience, but I can't merge this PR until this problem is resolved. 🙇

**Comment by korthout** [comment]
> Maybe because I've signed CLA in `spring-zeebe` project before ？

Perhaps, but unlikely, could you try navigating to https://cla-assistant.io/camunda-cloud/zeebe?pullRequest=8154 and tell me what it shows?

**Comment by Lzgabel** [comment]
> Perhaps, but unlikely, could you try navigating to https://cla-assistant.io/camunda-cloud/zeebe?pullRequest=8154 and tell me what it shows?

Oops!

image

**Comment by Lzgabel** [comment]
> Perhaps, but unlikely, could you try navigating to https://cla-assistant.io/camunda-cloud/zeebe?pullRequest=8154 and tell me what it shows?

Hi @korthout,  I've siged the CLA.

image

**Comment by korthout** [comment]
Hi @Lzgabel, we've re-configured the CLA for this organization and triggered a re-check of all pull requests. That may take some time, so let's wait for that.

**Review by korthout — APPROVED** [review]
Sorry for the long wait. Here we go! 🚀 

bors merge

**Comment by oleschoenburg** [comment]
just two flaky tests,
bors retry

**Comment by korthout** [comment]
Manually backported to `stable/1.2` with #8183 because backport-action doesn't run on external contributions. Backport to `stable/1.1` can be done automatically by labeling that pull request.

**Pull request merged**
