### PR TITLE
Backport preserving flaky test output to 8.0

### LINKED ISSUE #10637: Backport fix to preserve output of flaky test runs to `stable/8.0`
With https://github.com/camunda/zeebe/issues/10009 done, we should also backport https://github.com/camunda/zeebe/pull/10520 to the `stable/8.0` branch, otherwise we won't have good information to diagnose flaky tests on that branch.

Unfortunately, backporting is not trivial because of dependency convergence issues. https://github.com/camunda/zeebe/pull/10520 requires surefire 3.0.0-M7 but 8.0 is on 3.0.0-M5. Just backporting https://github.com/camunda/zeebe/pull/9049 too is not enough, the maven plugin versions have drifted quite far and there are other changes to our POMs.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR backports preserving the flaky test output for 8.0.

## Related issues

closes #10637

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
So Snyk reports policy violations, and indeed that kind of make sense with our build-tools module.

That said, AFAIK, build-tools is only used in the test scope, and as an additional dependency for some plugins. It's not actually part of our published artifact.

EPL is a weak copyleft license, so AFAIK it should be fine to have it only in the test scope (i.e. we're not shipping it, and it won't infect the final product either even if "linked"). I don't really see a way around this since the Maven dependencies are licensed as EPL :shrug: 

It would be good though if I could get a second pair of eyes to confirm this.

**Comment by npepinpe** [comment]
@oleschoenburg - ignore the license thing for now (though of course your input is welcome). I'd like to hear @megglos's take on that anyway before we merge. That said, we can review the rest anyway. Thanks in advance!

**Comment by megglos** [comment]
> So Snyk reports policy violations, and indeed that kind of make sense with our build-tools module.
> 
> That said, AFAIK, build-tools is only used in the test scope, and as an additional dependency for some plugins. It's not actually part of our published artifact.
> 
> EPL is a weak copyleft license, so AFAIK it should be fine to have it only in the test scope (i.e. we're not shipping it, and it won't infect the final product either even if "linked"). I don't really see a way around this since the Maven dependencies are licensed as EPL 🤷 As they're transitive dependencies, it's possible we could also exclude them from this module for now, though I'm not sure if that would have a wider impact on other plugins.
> 
> It would be good though if I could get a second pair of eyes to confirm this.

From my perspective there shouldn't be a need to exclude them given they are used for a plugin only as you stated and not shipping it anyway as part of our product + given that we publish our sources anyway

**Review by megglos — APPROVED** [review]
LGTM! Thanks for taking care of good ol 8.0! Apologies for the delay!

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
