### PR TITLE
Remove unused exporter clear service

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Did some houskeeping, like removing unused class and fixed a wrong log statement.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
Thanks @Zelldon :wastebasket: 

Do we have the logic of the `ExporterClearStateService` somewhere else? :sweat_smile: 

Please adjust the PR title to reflect the changes :stuck_out_tongue:

**Comment by Zelldon** [comment]
Yes in the Director. What would be the title ? 😅

**Comment by saig0** [comment]
Maybe, something like "Remove unused exporter service" :thinking:

**Comment by Zelldon** [comment]
Which then not shows the other change 😃 I properly need to create separate prs for every change😅😬

**Comment by Zelldon** [comment]
Or do you meant the commit message?

**Comment by saig0** [comment]
> Or do you meant the commit message?

No. Just the title of the PR. It will be shown in the release changelog. 

> I properly need to create separate prs for every change

Please not :see_no_evil: Let's keep it simple.

**Comment by Zelldon** [comment]
@saig0 thanks

bors r+

**Pull request merged**
