### PR TITLE
Set default stream timeout and enable stream as default in benchmarks

### LINKED ISSUE #13914: Integrate job worker streaming and metrics into benchmarks
## Description

To ensure the stability of the new job push/streaming feature, we should integrate it into our long running benchmarks. This means updating the `Worker` application with the following features:

- [x] Configuration to enable streaming (i.e. call `JobWorkerBuilder#enableStreaming`)
- [x] Configuration for the stream timeout (default to 8 hours)

Let's enable streaming by default in future benchmarks as well to root out as many errors as possible, and because this is our desired end state. If we see it's too buggy, we can roll it back.

> **Note**
> When I prototyped this, I hit a bunch of performance issues with the `Worker` application itself. I don't know if this will happen again, but be wary of it.

Once https://github.com/camunda/zeebe/pull/13818 is merged, we should also:

- [x] Migrate `Worker` to use Micrometer + Prometheus (possibly migrate the `Starter` if it makes sense, since they share some code)
- [x] Enable job worker metrics
- [ ] Update the dashboard to visualize the job worker metrics

### PR DESCRIPTION
**Pull request by rodrigo-lourenco-lopes**
## Description

This PR enables streaming as default in all benchmarks (can be changed in application.conf) and sets the default stream timeout as 8 hours.

## Related issues

related #13914

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Hopefully the branch name is not too long for the benchmark :x

**Review by npepinpe — APPROVED** [review]
:+1: 

Let's check a benchmark run first though before merging

**Comment by npepinpe** [comment]
@rodrigo-lourenco-lopes - the branch name is too long for the benchmark action. Can you run a benchmark for this yourself?

**Comment by rodrigo-lourenco-lopes** [comment]
> @rodrigo-lourenco-lopes - the branch name is too long for the benchmark action. Can you run a benchmark for this yourself?

https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=rl-enable-stream&var-pod=All&var-partition=All

**Comment by npepinpe** [comment]
Looks like the starter/worker are crash looping :thinking:

**Comment by rodrigo-lourenco-lopes** [comment]
> Looks like the starter/worker are crash looping 🤔

I had renamed the configuration method getter without changing the value name of isStreamEnabled, now it's fixed.

https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=rl-enable-streaming&var-pod=All&var-partition=All

Also, I run this benchmark adding the configuration `--set worker.streamEnabled=true`, does the workflow need this additional configuration, or are these configurations in the workflow only necessary if we want to override the values in `application.conf`?

**Comment by npepinpe** [comment]
They're only necessary if you want to override the defaults :+1: 

I see 3 benchmarks now. Which is which?

**Comment by rodrigo-lourenco-lopes** [comment]
> They're only necessary if you want to override the defaults 👍
> 
> I see 3 benchmarks now. Which is which?

It was the `rl-enable-streaming`

**Comment by npepinpe** [comment]
Let's sync about the benchmarks tomorrow. As a follow up - nothing here is a blocker, I think it's clear we can merge this :+1: 

I see:

- rl-enable-streaming
- rl-enable-streaming2
- rl-enable-streaming3

The first one has similar performance to our benchmarks, a little less back pressure. The second one has amazing performance, with p50 < 800ms, and p99 < 1.5s. The third one has better performance than the first and medic, but not than the second.

I'm very curious as to why the second is going so well :smile: 

Also, from what I can see, we get some restarts: workers sometimes restart, and so do gateways. Perhaps with more work, we're now tipping gateways over more. We should double check that as a follow up.

**Pull request merged**
