### PR TITLE
#7903 add SfvChecksum file logic to read and write SfvFiles

### LINKED ISSUE #7903: Implement snapshot checksum using SFV files
**Description**

We've had a few issues where snapshots are corrupted. One of the biggest issue however, is that we only keep a global checksum for the whole directory. The checksum is calculated as the checksum of a continuous byte stream of `fileName` and `fileContents` for each file.

This has a downside that you don't know if the corruption is due to a missing file, to an additional file, or which file was corrupted. It also means your checksum computation is tied to the order in which files are fed to the checksum computation.

To circumvent this, I propose we use an existing file format, the [SFV format](https://en.wikipedia.org/wiki/Simple_file_verification). This is essentially a manifest file, where each line is a pair of file name and checksum for that file.

This would allow us to pinpoint what is the exact cause of the corruption - which file was it, was a file missing, was a file added, etc. This will also mean we're not tied to the file ordering, since it doesn't matter anymore in which order we read the files.

### PR DESCRIPTION
**Pull request by nitram509**
## Description

Introduced SfvChecksum class, to improve the ability to detect broken snapshots.

## Related issues

closes #7903

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [/] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [/] There are unit/integration tests that verify all acceptance criterias of the issue
* [/] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks again for your contribution. :rocket: 

Looks good to me. Please see my comments. Once you fix the build issues, I will trigger the CI pipeline again.

**Comment by nitram509** [comment]
@deepthidevaki thank you for your feedback.
I did incorporate your recommendation into my latest commits.
May I ask for a review again?

Also, IF you're fine with my PR, may I ask to add the label "hacktoberfest-accepted" to this PR?
According to the rules, this would count then. Thank you in advance.

**Review by deepthidevaki — CHANGES_REQUESTED** [review]
Thanks for the changes. :+1:
The build still fails because of missing license files.
Please run `mvn  com.mycila:license-maven-plugin:format` and commit the changes. 

Also please cleanup the commit messages according to our [commit message guidelines](https://github.com/camunda-cloud/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)

The PR looks good otherwise. As soon as the build errors are fixed and ci pipeline runs successfully, we can merge it.

**Comment by deepthidevaki** [comment]
Sorry @nitram509 The build still fails. Please run `mvn clean install -DskipTests` and fix all errors before pushing.

```
[2021-10-19T07:04:37.340Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2:check (validate-java) on project zeebe-snapshots: You have 12 Checkstyle violations. -> [Help 1]
```

**Comment by deepthidevaki** [comment]
@nitram509 I have triggered the CI pipeline now. Build and Tests are success :+1:

Regarding the commits, it is ok to loose the commit history for the commits added in this PR. So you can  `git rebase --soft <base_commit>` and add new commits with the correct format. You can decide how you want to split into multiple commits. But ensure that each commit follows the guidelines. Could you do that?

**Review by deepthidevaki — APPROVED** [review]
Great! :tada: Thanks @nitram509 for your contribution.

Please check https://camunda.com/hacktoberfest2021/ to know what needs to be done as part of the hacktoberfest

**Pull request merged**
