### PR TITLE
docs(kubernetes): fix typo

### PR DESCRIPTION
**Pull request by habil**
typo fix

## Related issues

closes #

## Definition of Done

Documentation: 
* [ x ] The documentation is updated  ( installing helm)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 5e88a674cd0dad801e1213338a96465ea4cc0e2c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by saig0 — APPROVED** [review]
Thanks @habil :cookie:

**Comment by saig0** [comment]
@habil please rename the commit message to `docs(kubernetes): fix typo` to follow the commit message guide lines :)

**Comment by habil** [comment]
@saig0 Hello, title changed 👍

**Comment by saig0** [comment]
Super :cake:

**Pull request merged**
