### PR TITLE
Stop iterating jobs if job batch reached max capacity

### LINKED ISSUE #2185: Stop iterating during job activation once truncated flag is true
Currently, when activating jobs, we try to fit as many jobs as possible into a single `JobBatchRecord`. When we can't, but the caller requested more jobs, we set a truncated flag true; however, the `remainingAmount` is still positive, and we never decrement it again, leading to us iterating over the whole job state.

We should stop when `remainingAmount` is not positive or truncated is true.

### PR DESCRIPTION
**Pull request by menski**
closes #2185

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
I tried coming up with a test that doesn't mock the iteration, so it's a bit closer to the actual code being run, but it does rely on the fact that we call `JobState#visitJob` (which needs to be changed from private to package-private) on every iteration, which then calls the callback.

```java
/*
 * Zeebe Broker Core
 * Copyright © 2017 camunda services GmbH (info@camunda.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.zeebe.broker.job;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import io.zeebe.broker.logstreams.processor.TypedRecord;
import io.zeebe.broker.logstreams.processor.TypedResponseWriter;
import io.zeebe.broker.logstreams.processor.TypedStreamWriter;
import io.zeebe.broker.util.MockTypedRecord;
import io.zeebe.broker.util.ZeebeStateRule;
import io.zeebe.protocol.clientapi.VarDataEncodingEncoder;
import io.zeebe.protocol.impl.record.RecordMetadata;
import io.zeebe.protocol.impl.record.value.job.JobBatchRecord;
import io.zeebe.protocol.impl.record.value.job.JobRecord;
import java.time.Duration;
import java.util.function.BiFunction;
import java.util.stream.IntStream;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.Spy;
import org.mockito.junit.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.StrictStubs.class)
public class JobBatchActivateProcessorTest {
  @ClassRule public static ZeebeStateRule zeebeState = new ZeebeStateRule();

  @Mock TypedStreamWriter streamWriter;
  @Mock TypedResponseWriter responseWriter;
  @Spy JobState jobState = zeebeState.getZeebeState().getJobState();

  private JobBatchActivateProcessor processor;
  private JobRecord jobRecord;

  @Before
  public void setUp() {
    jobRecord = new JobRecord();
    processor =
        new JobBatchActivateProcessor(
            jobState,
            zeebeState
                .getZeebeState()
                .getWorkflowState()
                .getElementInstanceState()
                .getVariablesState());
    when(streamWriter.getKeyGenerator()).thenReturn(zeebeState.getZeebeState().getKeyGenerator());
  }

  @Test
  public void stopIteratingAfterAmount() {
    // given
    final String type = "testTask";
    final int expectedIterations = 10;
    final TypedRecord<JobBatchRecord> record =
        newRecord(expectedIterations, type, VarDataEncodingEncoder.lengthMaxValue());
    createJobs(expectedIterations, type);
    createJobs(1, "other-" + type);

    // when
    processor.processRecord(record, responseWriter, streamWriter);

    // then
    verify(jobState, times(expectedIterations)).visitJob(anyLong(), any());
  }

  @Test
  public void stopIteratingOnTruncation() {
    // given
    final String type = "testTask";
    final int expectedIterations = 3;
    final int maxValueLength = expectedIterations * jobRecord.getLength() - 1;
    final TypedRecord<JobBatchRecord> record = newRecord(10, type, maxValueLength);
    createJobs(expectedIterations + 1, type);
    createJobs(1, "other-" + type);

    // when
    processor.processRecord(record, responseWriter, streamWriter);

    // then
    verify(jobState, times(expectedIterations)).visitJob(anyLong(), any());
  }

  private void createJobs(int amount, String type) {
    IntStream.range(0, amount).forEach(i -> createJob(type));
  }

  private void createJob(String type) {
    final JobRecord job = new JobRecord().setType(type);
    final long key = zeebeState.getZeebeState().getKeyGenerator().nextKey();
    jobState.create(key, job);
  }

  private TypedRecord<JobBatchRecord> newRecord(int amount, String type, int maxValueLength) {
    final JobBatchRecord record =
        new JobBatchRecord()
            .setAmount(amount)
            .setType(type)
            .setWorker("testWorker")
            .setTimeout(Duration.ofSeconds(1).toMillis());
    return new MockTypedRecord<JobBatchRecord>(-1, new RecordMetadata(), record) {
      @Override
      public int getMaxValueLength() {
        return maxValueLength;
      }
    };
  }
}
```

Not sure if it's really better...

**Comment by menski** [comment]
I prefer your test over mine and didn't come up with something better, so I replaced it. Anything else?

**Review by npepinpe — APPROVED** [review]

**Pull request merged**
