### PR TITLE
Go package name/import fix for issue #1687

### LINKED ISSUE #1687: Go client package name
Go client package name is quite confusing, as it has different name from last directory in import.

The example from https://github.com/zeebe-io/zeebe-get-started-go-client/blob/master/example-4/main.go gave me quite a spike in WTF/minute, when "github.com/zeebe-io/zeebe/clients/go" were imported, but package name in that directory is zbc. One would expect it to be "go".

In go community such discord between package name and it's directory is usually frowned upon and generally okay only for "main" package, which is a special case in itself.

I agree, that "go" is not a suitable name for zeebe go client package, but moving api.go and client.go into /zbc subdirectory however breaking existing code, is the only option to preserve sanity.

For immediate remedy you can make symlinks from root directory, so existing clients won't break, but notify deprecation of inconsistent import naming.

### PR DESCRIPTION
**Pull request by iamtakingiteasy**
Relocated go packge "zbc" to from a "github.com/zeebe-io/zeebe/clients/go"
to "github.com/zeebe-io/zeebe/clients/go/zbc" directory, while keeping
symlinks for existing code, however existing import should be deprecated.

closes #1687 

For developers interested in migration, here is a sample automation:

    find . -name '*.go' -print -exec sed 's|"github.com/zeebe-io/zeebe/clients/go"|"github.com/zeebe-io/zeebe/clients/go/zbc"|' -i "{}" \;

Which will recursively scan *.go files from current directory and downwards, looking for strings matching import string "github.com/zeebe-io/zeebe/clients/go" and replacing them with "github.com/zeebe-io/zeebe/clients/go/zbc"

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a94afefe21b089d2454a7eb0a9f351d747457987
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by iamtakingiteasy** [comment]
Is there a way to know what is failing? "Details" link require some http basic authentication.

And `make install-deps test` in clients/go/ directory passes.

**Comment by menski** [comment]
Hi @iamtakingiteasy,

thanks for raising this issue and providing a PR. You can ignore the test failures, which are related to unstable java tests. The go test suite is green.

I will try to have a look at this later today. At the current state we are also okay with breaking existing code, so we do not have to maintain backward compatibility.

Cheers,
Sebastian

**Comment by iamtakingiteasy** [comment]
@menski 

> At the current state we are also okay with breaking existing code, so we do not have to maintain backward compatibility.

Should i remove symlinks from commit then?

**Comment by menski** [comment]
Yes I think we do not need them

**Comment by iamtakingiteasy** [comment]
Here is matching PR for examples: https://github.com/zeebe-io/zeebe-get-started-go-client/pull/1

**Review by menski — APPROVED** [review]
Thanks for this contribution, it is very much appreciated. If you have any other feedback regarding the go client please let us know.

bors r+

**Comment by iamtakingiteasy** [comment]
Sure. For other thing that bogged me next to package naming i made a related PR: https://github.com/zeebe-io/zeebe/pull/1689

**Pull request merged**
