### PR TITLE
ci: use correct images for running testbench

### PR DESCRIPTION
**Pull request by lenaschoenburg**
This changes the workflow to no longer rely on the `build-push-docker-gcr` action. I didn't properly root cause it but while we were using `build-push-docker-gcr`, inputs were lost which caused testbench to use wrong images for 8.0 and 8.1.

Testbench is broken right now (unlucky coincidence) but you can see a successful start here: https://github.com/camunda/zeebe/actions/runs/4304581988

Compared to a earlier run on main where we can see that the wrong images were being used: https://github.com/camunda/zeebe/actions/runs/4299081589/jobs/7493921068#step:5:17

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
:clap: Thanks @oleschoenburg . Inlining action is also better, because we had problems before due to different versions in stable branch :+1: 

May be we can also add the image tag to the success message posted to slack. This way we can catch such errors faster. Message is pre-defined in the process model. Wdyt?

**Comment by deepthidevaki** [comment]
bors merge

**Comment by oleschoenburg** [comment]
> May be we can also add the image tag to the success message posted to slack. This way we can catch such errors faster. Message is pre-defined in the process model. Wdyt?

That sounds really useful :+1:

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
