### PR TITLE
refactor: Snapshot Variable

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

* Creates a `SnaphotTaskVariableEntity` and `SnapshotTaskVariableTemplate` in the `webapps-schema` module
* Replaces Tasklist's `TaskVariableEntity` and `TaskVariableTemplate` accordingly

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

related to #24665

### CODE REVIEW

**Comment by panagiotisgts** [comment]
This change breaks the joined index format of `tasklist-task` that we are currently going with that includes process and task variables in it. Is that something that was discussed/taken decision upon? AFAIK we yet do not have a clear implementation plan for _Search Tasks by Variables_, that's related to these indices.

**Comment by romansmirnov** [comment]
> This change is related to the joined index format of tasklist-task that we are currently going with that includes process and task variables in it. Is that something that was discussed/taken decision upon? AFAIK we yet do not have a clear implementation plan for Search Tasks by Variables, that's related to these indices and whether we should keep this separate index.

This is a separate discussion and concerns only the Camunda v2 API. Additionally, in the v2 API, snapshotting of variables won't happen anymore and will not be used for user task search.

The Tasklist v1 API will remain the same, meaning that when a user task is completed, it will snapshot the current variables and store them in the `tasklist-task-variable` index. Also, the v1 implementation of Search Task by variables will remain the same, and by that, it will keep using the `tasklist-task-variable` index.

**Comment by romansmirnov** [comment]
Rebased with `main` to resolve merged conflicts.

**Comment by romansmirnov** [comment]
> Additionally, in the v2 API, snapshotting of variables won't happen anymore and will not be used for user task search.

(I was not correct.) Probably it will still be required to ensure that Tasklist v1 behaves correctly. But I would tackle it as a separate topic to adjust the `camunda-exporter`.

**Comment by romansmirnov** [comment]
Rebased with `main` to resolve merge conflicts, @panagiotisgts (or someone from @camunda/hto-backend) would be great to get a review?

**Review by panagiotisgts — APPROVED** [review]
LGTM. I'll just run the E2E CI job because a case failing is regarding these variables just for a check.

**Pull request merged**
