### PR TITLE
feat(broker): add HTTP metrics endpoint

### LINKED ISSUE #2144: Expose metrics over HTTP
To simplify prometheus scraping there should be an option do expose metrics over HTTP instead of a file

### PR DESCRIPTION
**Pull request by menski**
- by default disabled
- can be enabled by setting metrics.enableHttpServer = true

closes #2144

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
Looks good. One thing: 

Do we need a test which tests the endpoint, whether the metrics are published properly?

**Comment by menski** [comment]
You mean that the endpoint returns the metrics on a GET request?

**Comment by Zelldon** [comment]
Yes

**Comment by menski** [comment]
Good point, I will add a test for that

**Comment by menski** [comment]
@Zelldon I added a test, please have a look if it is enough

**Review by ChrisKujawa — APPROVED** [review]
bors r+

**Pull request merged**
