### PR TITLE
Zeebe model support for user task assignment definitions

### LINKED ISSUE #8053: Support modeling assignments in zeebe-bpmn-model
## Description
A new BPMN extension element should be introduced to allow defining assignments for user tasks.

- a user task can have 0 or 1 assignment defininitions (i.e. denoted as `zeebe:assignmentDefinition` inside the `bpmn:extensionElements` of a `bpmn:userTask`)
- an assignment definition specifies an assignee and/or candidate groups (i.e. denoted as `candidateGroups`)
- an assignee is defined as a string containing a static values (e.g. `x`), or a Zeebe-formatted FEEL expression (i.e. prefixed by `= `) where the expression should evaluate to a string
- candidate groups are defined as a string containing a comma-separated list of values (e.g. `x,y,z`), or a Zeebe-formatted FEEL expression (i.e. prefixed by `= `) where the expression should evaluate to a list of strings.

## Examples

```xml
<!-- A user task can have an assignee, specified as static value -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <zeebe:assignmentDefinition assignee="frodo" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
<!-- A user task can have an assignee, specified as expression -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <zeebe:assignmentDefinition assignee="= ring.bearer" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
<!-- A user task can have candidateGroups, specified as comma-separated list of values -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <zeebe:assignmentDefinition candidateGroups="elves, men, dwarfs, hobbits" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
<!-- A user task can have candidateGroups, specified as expression -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
   <!--
     expression produces bracket formatted list which differs from static value
     example expression evaluates to: ["elves", "men", "dwarfs", "hobbits"]
   -->
  <zeebe:assignmentDefinition candidateGroups="= distinct values(fellowship.belongsTo)"/>
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
 
<!-- A user task can have an assignee and candidateGroups simultaneously -->
<bpmn:userTask id="Activity_0l1dt75" name="Cast ring into the fire">
 <bpmn:extensionElements>
  <zeebe:assignmentDefinition
      assignee="= ring.bearer" 
      candidateGroups="elves, men, dwarfs, hobbits" />
 </bpmn:extensionElements>
 <bpmn:incoming>Flow_0ytpx7p</bpmn:incoming>
</bpmn:userTask>
```

### PR DESCRIPTION
**Pull request by korthout**
## Description

Adds assignment definitions to the bpmn-model module. 

Specifically, it adds support for `assignee` and `candidateGroups` as attributes of the extension element `AssignmentDefinition`, including methods to construct these using the bpmn builders.

## Related issues

closes #8053 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
@korthout great work :tada: 

I like the tests for the builder. But the test class grows too much :sweat_smile:

**Comment by korthout** [comment]
> I like the tests for the builder. But the test class grows too much 😅

An idea is to split up this class into separate tests for the individual builders (e.g. [these tests](https://github.com/camunda-cloud/zeebe/blob/af157c14b32b201ed9dc421aaf3416aeb579ad51/bpmn-model/src/test/java/io/camunda/zeebe/model/bpmn/builder/ProcessBuilderTest.java#L2141-L2194) could then move to a `UserTaskBuilderTest` class.

@saig0 What do you think? Should we do that?

**Comment by saig0** [comment]
> An idea is to split up this class into separate tests for the individual builders (e.g. these tests could then move to a UserTaskBuilderTest class.

Sounds good :+1:

**Comment by korthout** [comment]
bors merge

**Pull request merged**
