### PR TITLE
feat: use new license properties to display license tag

### PR DESCRIPTION
**Pull request by misiekhardcore**
## Description

This PR updates the C# library, and uses new license properties in the `ui-configuration` API to show the license tag in the page header

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

related to https://github.com/camunda/camunda/issues/20639

### CODE REVIEW

**Review by OmranAbazid — APPROVED** [review]
pre-approving.
I noticed that "Optimize Run Java checks" pipeline is showing license related errors

**Comment by misiekhardcore** [comment]
@OmranAbazid I think I need to wait for the backend PR to be merged and then rebase to `main`. For now I outbranched from @matthewBearCamunda's PR to be able to work on it. I'll keep it open until it can be rebased

**Comment by RomanJRW** [comment]
Relevant comment: https://github.com/camunda/camunda/issues/20639#issuecomment-2307101610

**Pull request merged**
