### PR TITLE
chore: remove C7 IT workflows since we will comment them out eventually

### PR DESCRIPTION
**Pull request by HeleneW-dot**
## Description
remove C7 IT workflows

### CODE REVIEW

**Review by buccarel — APPROVED** [review]
If those git errors are expected, this looks good. I'm approving it

**Comment by PHWaechtler** [comment]
> > If those git errors are expected, this looks good. I'm approving it
> 
> which git errors?

@buccarel can you elaborate? If there are new errors in this PR we'll need to fix them before merging

**Comment by PHWaechtler** [comment]
> > > If those git errors are expected, this looks good. I'm approving it
> > 
> > 
> > @buccarel which git errors?
> 
> if I click on the "files" tab, I see the following:
> 
> image

@buccarel Gotcha, adjusted please re review

**Review by buccarel — APPROVED** [review]
🚀

**Pull request merged**
