### PR TITLE
Fix start message subscription closing bugs

### LINKED ISSUE #2265: Deployment distribution and closing MessageSubscriptions can end in NullPointerException
### Scenario:

 * Start Broker with 3 partitions
 * Create a deployment
 * One of the partitions is for what ever reason delayed and will take a bit longer to start,
   the distribution is retried later for this delayed partition
  * Create second deployment with the same workflow, distribution works for this deployment
 * On deployment `CREATED`  processing on the delayed partition an NPE is thrown

### Problem:

The `DeploymentCreatedProcessor` calculates based on the workflow version the version before and tries to close open message subscriptions. Since the first deployment does not arrived yet, this deployment is not in the state and will return `null`.

```java

  private void closeExistingMessageStartEventSubscriptions(
      WorkflowState workflowState, Workflow workflowRecord, TypedStreamWriter streamWriter) {
    final int previousVersion = workflowRecord.getVersion() - 1;
    final long previousWorkflowKey =
        workflowState
            .getWorkflowByProcessIdAndVersion(workflowRecord.getBpmnProcessId(), previousVersion)
            .getKey();
    ...
  }
```

```
10:50:21.843 [partition-2] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.raft - Taking transition Transition{raftTranisiton=TO_LEADER, term=1} from state CANDIDATE
10:50:21.847 [zb-stream-processor] [0.0.0.0:25675-zb-actors-1] DEBUG io.zeebe.broker.workflow.repository - Deployment pushed to partition 1 (node id: 0).
10:50:21.848 [management-request-handler] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Got deployment push request for deployment 2.
10:50:21.848 [management-request-handler] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Deployment CREATE command was written on partition 1
10:50:21.856 [partition-2] [0.0.0.0:25675-zb-actors-1] DEBUG io.zeebe.raft - Initial event for term 1 was appended on position 4294967296
10:50:21.856 [partition-2] [0.0.0.0:25675-zb-actors-1] DEBUG io.zeebe.raft - Transitioned to state LEADER in term 1
10:50:21.856 [partition-2] [0.0.0.0:25675-zb-actors-1] DEBUG io.zeebe.broker.clustering - Removing follower partition service for partition PartitionInfo{partitionId=2, replicationFactor=1}
10:50:21.856 [partition-2] [0.0.0.0:25675-zb-actors-1] DEBUG io.zeebe.broker.clustering - Installing partition service for PartitionInfo{partitionId=2, replicationFactor=1}. Replication factor reached, got 1/1.
10:50:21.857 [partition-2] [0.0.0.0:25675-zb-actors-1] DEBUG io.zeebe.raft - Initial event for term 1 was committed on position 4294967296
10:50:21.857 [topology] [0.0.0.0:25675-zb-actors-1] DEBUG io.zeebe.broker.clustering - Updating partition information for partition PartitionInfo{partitionId=2, replicationFactor=1} on Node{nodeId=0, clientApi=0.0.0.0:25675, managementApi=0.0.0.0:25676, replicationApi=0.0.0.0:25677, subscriptionApi=0.0.0.0:25678} with state LEADER
10:50:21.857 [zb-stream-processor] [0.0.0.0:25675-zb-actors-1] INFO io.zeebe.logstreams - Recovering partition 2 from snapshot at position -1
10:50:21.866 [zb-stream-processor] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Deployment pushed to partition 1 (node id: 0).
10:50:21.866 [zb-stream-processor] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Deployment pushed to partition 2 (node id: 0).
10:50:21.866 [management-request-handler] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Got deployment push request for deployment 4.
10:50:21.866 [management-request-handler] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Got deployment push request for deployment 4.
10:50:21.866 [management-request-handler] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Deployment CREATE command was written on partition 2
10:50:21.866 [management-request-handler] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Deployment CREATE command was written on partition 1
10:50:21.871 [zb-stream-processor] [0.0.0.0:25675-zb-actors-0] DEBUG io.zeebe.broker.workflow.repository - Deployment pushed to all partitions successfully.
10:50:21.872 [exporter] [0.0.0.0:25675-zb-actors-0] INFO io.zeebe.logstreams - Recovering partition 2 from snapshot at position -1
10:50:21.876 [exporter] [0.0.0.0:25675-zb-actors-0] INFO io.zeebe.processor - Start scanning the log for error events.
10:50:22.184 [zb-stream-processor] [0.0.0.0:25675-zb-actors-1] INFO io.zeebe.processor - Start scanning the log for error events.
10:50:22.197 [zb-stream-processor] [0.0.0.0:25675-zb-actors-1] ERROR io.zeebe.processor - Expected to successfully process event 'LoggedEvent [type=0, version=0, streamId=2, position=4294969576, key=4, timestamp=1553680222197, sourceEventPosition=4294967392, producerId=2]' with processor 'zb-stream-processor', but caught an exception. Skip this event.
java.lang.NullPointerException: null
at io.zeebe.broker.workflow.processor.deployment.DeploymentCreatedProcessor.closeExistingMessageStartEventSubscriptions(DeploymentCreatedProcessor.java:71) ~[classes/:?]
at io.zeebe.broker.workflow.processor.deployment.DeploymentCreatedProcessor.processRecord(DeploymentCreatedProcessor.java:59) ~[classes/:?]
at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:36) ~[classes/:?]
at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[classes/:?]
at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:196) ~[classes/:?]
at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:77) ~[classes/:?]
at io.zeebe.logstreams.processor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:202) ~[classes/:?]
at io.zeebe.logstreams.processor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:179) ~[classes/:?]
at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [classes/:?]
at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [classes/:?]
at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
10:50:22.208 [zb-stream-processor] [0.0.0.0:25675-zb-actors-1] ERROR io.zeebe.broker.workflow - Expected to process event 'TypedEventImpl{metadata=RecordMetadata{recordType=EVENT, intentValue=255, intent=CREATED, requestStreamId=-2147483648, requestId=-1, valueType=DEPLOYMENT}, value={"resources":[{"resourceType":"BPMN_XML","resourceName":"process.bpmn","resource":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxkZWZpbml0aW9ucyB4bWxuczpicG1uZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvREkiIHhtbG5zOmRjPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9ERC8yMDEwMDUyNC9EQyIgeG1sbnM6ZGk9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0RELzIwMTAwNTI0L0RJIiBpZD0iZGVmaW5pdGlvbnNfODk2ZDAwMzItYjIyZC00NzkxLTg4NWYtNmIyMWQyZDFhYTZjIiB0YXJnZXROYW1lc3BhY2U9Imh0dHA6Ly93d3cub21nLm9yZy9zcGVjL0JQTU4vMjAxMDA1MjQvTU9ERUwiIHhtbG5zPSJodHRwOi8vd3d3Lm9tZy5vcmcvc3BlYy9CUE1OLzIwMTAwNTI0L01PREVMIj4KICA8cHJvY2VzcyBpZD0icHJvY2VzcyIgaXNFeGVjdXRhYmxlPSJ0cnVlIj4KICAgIDxzdGFydEV2ZW50IGlkPSJzdGFydEV2ZW50X2VhNGQ0ODY0LWQzNTctNDg4OC04ZGJjLTJjYjRjNTVmNWUwYSI+CiAgICAgIDxvdXRnb2luZz5zZXF1ZW5jZUZsb3dfOWQxMWUxZTEtZDRmMy00ZjlhLTkxNzctZjYzMjVmZGRmNDA1PC9vdXRnb2luZz4KICAgIDwvc3RhcnRFdmVudD4KICAgIDxlbmRFdmVudCBpZD0iZW5kRXZlbnRfZjNhYzZjOTAtY2Q2My00ZTc2LTlmY2YtNWU3MWMwNTQ0MGFjIj4KICAgICAgPGluY29taW5nPnNlcXVlbmNlRmxvd185ZDExZTFlMS1kNGYzLTRmOWEtOTE3Ny1mNjMyNWZkZGY0MDU8L2luY29taW5nPgogICAgPC9lbmRFdmVudD4KICAgIDxzZXF1ZW5jZUZsb3cgaWQ9InNlcXVlbmNlRmxvd185ZDExZTFlMS1kNGYzLTRmOWEtOTE3Ny1mNjMyNWZkZGY0MDUiIHNvdXJjZVJlZj0ic3RhcnRFdmVudF9lYTRkNDg2NC1kMzU3LTQ4ODgtOGRiYy0yY2I0YzU1ZjVlMGEiIHRhcmdldFJlZj0iZW5kRXZlbnRfZjNhYzZjOTAtY2Q2My00ZTc2LTlmY2YtNWU3MWMwNTQ0MGFjIi8+CiAgPC9wcm9jZXNzPgogIDxicG1uZGk6QlBNTkRpYWdyYW0gaWQ9IkJQTU5EaWFncmFtX2JiY2RhN2ViLTk3MDQtNGZjYi04ZjI3LTAyMzQ3YWU3ZDA4NiI+CiAgICA8YnBtbmRpOkJQTU5QbGFuZSBicG1uRWxlbWVudD0icHJvY2VzcyIgaWQ9IkJQTU5QbGFuZV9kMjE2ZDI3OS0yY2Y4LTQyMDAtYjUzMC02MmVhZjMyYjQzOGEiPgogICAgICA8YnBtbmRpOkJQTU5TaGFwZSBicG1uRWxlbWVudD0ic3RhcnRFdmVudF9lYTRkNDg2NC1kMzU3LTQ4ODgtOGRiYy0yY2I0YzU1ZjVlMGEiIGlkPSJCUE1OU2hhcGVfN2YyNjYzODUtYjAyNi00NGQ4LTgyZjUtNTZmZjBjNmQyZTRiIj4KICAgICAgICA8ZGM6Qm91bmRzIGhlaWdodD0iMzYuMCIgd2lkdGg9IjM2LjAiIHg9IjEwMC4wIiB5PSIxMDAuMCIvPgogICAgICA8L2JwbW5kaTpCUE1OU2hhcGU+CiAgICAgIDxicG1uZGk6QlBNTlNoYXBlIGJwbW5FbGVtZW50PSJlbmRFdmVudF9mM2FjNmM5MC1jZDYzLTRlNzYtOWZjZi01ZTcxYzA1NDQwYWMiIGlkPSJCUE1OU2hhcGVfYWExZWY1YzUtMWI0Mi00MDM0LWE2YWUtNDFiMWE0NWI1YjZhIj4KICAgICAgICA8ZGM6Qm91bmRzIGhlaWdodD0iMzYuMCIgd2lkdGg9IjM2LjAiIHg9IjE4Ni4wIiB5PSIxMDAuMCIvPgogICAgICA8L2JwbW5kaTpCUE1OU2hhcGU+CiAgICAgIDxicG1uZGk6QlBNTkVkZ2UgYnBtbkVsZW1lbnQ9InNlcXVlbmNlRmxvd185ZDExZTFlMS1kNGYzLTRmOWEtOTE3Ny1mNjMyNWZkZGY0MDUiIGlkPSJCUE1ORWRnZV9iZGEyYzgxMC0zOWNlLTQxNmEtYjc3Ni02ZmRlMmM3MDFlOWEiPgogICAgICAgIDxkaTp3YXlwb2ludCB4PSIxMzYuMCIgeT0iMTE4LjAiLz4KICAgICAgICA8ZGk6d2F5cG9pbnQgeD0iMTg2LjAiIHk9IjExOC4wIi8+CiAgICAgIDwvYnBtbmRpOkJQTU5FZGdlPgogICAgPC9icG1uZGk6QlBNTlBsYW5lPgogIDwvYnBtbmRpOkJQTU5EaWFncmFtPgo8L2RlZmluaXRpb25zPgo="}],"workflows":[{"bpmnProcessId":"process","version":2,"workflowKey":3,"resourceName":"process.bpmn"}]"resourceType":[packed value (length=9)]}}' without errors, but exception occurred with message 'null' .
java.lang.NullPointerException: null
at io.zeebe.broker.workflow.processor.deployment.DeploymentCreatedProcessor.closeExistingMessageStartEventSubscriptions(DeploymentCreatedProcessor.java:71) ~[classes/:?]
at io.zeebe.broker.workflow.processor.deployment.DeploymentCreatedProcessor.processRecord(DeploymentCreatedProcessor.java:59) ~[classes/:?]
at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:36) ~[classes/:?]
at io.zeebe.broker.logstreams.processor.TypedRecordProcessor.processRecord(TypedRecordProcessor.java:56) ~[classes/:?]
at io.zeebe.broker.logstreams.processor.TypedStreamProcessor$DelegatingEventProcessor.processEvent(TypedStreamProcessor.java:196) ~[classes/:?]
at io.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:77) ~[classes/:?]
at io.zeebe.logstreams.processor.ProcessingStateMachine.processEvent(ProcessingStateMachine.java:202) ~[classes/:?]
at io.zeebe.logstreams.processor.ProcessingStateMachine.readNextEvent(ProcessingStateMachine.java:179) ~[classes/:?]
at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:87) [classes/:?]
at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:53) [classes/:?]
at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:189) [classes/:?]
at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:154) [classes/:?]
at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:135) [classes/:?]
at io.zeebe.util.sched.ActorThread.run(ActorThread.java:112) [classes/:?]
```

### PR DESCRIPTION
**Pull request by miguelpires**
This PR fixes two issues because they're in the same place

closes #2265, #2156

### CODE REVIEW

**Comment by Zelldon** [comment]
I think we need to do some more work here because:

* If the newer deployment is the first one, then we should open a subscription and not fail on closing a non existing subscription.
 * If then the old deployment arrives we should not close the newer subscription and also not open a subscription for this old deployment.

I think the last part is missing `not open a subscription for this old deployment.`

Sorry for the intervene :sweat_smile:

**Review by menski — APPROVED** [review]
bors r+

**Comment by Zelldon** [comment]
So we do this in a follow up issue? :sweat_smile:

**Comment by MiguelPires** [comment]
I think it might be better to have a follow-up issue because there are more changes required. What we need is like you said to not open subscriptions for outdated deployments and also close all "old" subscriptions. Imagine you deploy version 1, version 3 and then version 2: I think it makes sense that while processing version 3 you have to close version 1's subscription (right now, we only close the previous) and then while processing the outdated version you should essentially see it's outdated and not do anything. Essentially, the whole thing needs to be refactored which seems like a little outside the scope of these issue. I'll create a new issue

**Comment by menski** [comment]
@MiguelPires could you please create the follow up issue. thanks

**Comment by MiguelPires** [comment]
Follow-up issue: https://github.com/zeebe-io/zeebe/issues/2288

**Pull request merged**
