### PR TITLE
feat: change dropdown to combobox (migration target process selection)

### PR DESCRIPTION
**Pull request by pedesen**
## Description

:heavy_check_mark:  This replaces the dropdown component by a combobox for target process selection in instance migration mode.

image

:x: Unfortunately it's currently not possible for the target flow node selection due to a known issue in Carbon, which traps comboboxes and menus inside scrollable containers (see https://github.com/camunda/operate/issues/5799 for details). While there are workarounds by specifying the direction the combobox is opening, this is not possible here due to the very limited space.

image

## Related issues

related to https://github.com/camunda/operate/issues/5799

### CODE REVIEW

**Review by vitorwtavares — APPROVED** [review]

**Comment by pedesen** [comment]
@gastonpillet01 Please check locally using this image name: `registry.camunda.cloud/team-operate/camunda-operate:branch-fe-5799-migration-target-combobox`. For now I only changed the combobox in the header (see PR description).

**Review by gastonpillet01 — APPROVED** [review]
It's a shame that it can't also be done in the comboboxes on the panel below due to Carbon :(
Anyway I approve this PR since it works wonders! Good job Paddy!!

**Comment by pedesen** [comment]
> It's a shame that it can't also be done in the comboboxes on the panel below due to Carbon :( Anyway I approve this PR since it works wonders! Good job Paddy!!

Yes, I would love to have that too. We need to figure out how much time we want to invest into this. Maybe we can convince the Carbon team to solve this, or solve it together with them...

But having it for the target process selection is a win already.

**Comment by pedesen** [comment]
@Szik Please test locally using this image name `registry.camunda.cloud/team-operate/camunda-operate:branch-fe-5799-migration-target-combobox`

**Review by Szik — APPROVED** [review]

**Pull request merged**
