### PR TITLE
test(broker-core): add test case with multiple partitions for message

### LINKED ISSUE #1083: Verify the partition assignment of message subscriptions
AT:
* verify that two message subscriptions with the same correlation-key are created on the same partition
* verify that this works also after restart / recovery

### PR DESCRIPTION
**Pull request by saig0**
closes #1083

### CODE REVIEW

**Review by ThorbenLindhauer — APPROVED** [review]

**Comment by ThorbenLindhauer** [comment]
bors retry

**Comment by saig0** [comment]
bors retry

**Pull request merged**
