### PR TITLE
Document FlowNodeInstanceState

### PR DESCRIPTION
**Pull request by tobiasschaefer**
## Description

Document the enum values in FlowNodeInstanceState because ACTIVE may be clear but the difference between COMPLETED and TERMINATED needs documentation.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

-

### CODE REVIEW

**Comment by korthout** [comment]
@saig0 This relates to camunda process test, could you have a look?

**Review by saig0 — APPROVED** [review]
@tobiasschaefer thank you for your contribution. :tada: 

The new JavaDoc is nice to have but not necessary. Eventually, we will replace the classes in the `client` package with the Camunda client's query API.

**Comment by saig0** [comment]
@tobiasschaefer Unfortunately, we have an [issue](https://github.com/camunda/camunda/issues/19222) with accepting contributions because of a problem in our CI pipelines. :see_no_evil:

I'm sorry to say but we can't merge your PR.

**Comment by korthout** [comment]
@saig0 You can apply the workaround mentioned in https://github.com/camunda/camunda/issues/19222

**Comment by tobiasschaefer** [comment]
Hi @saig0 ,

I only just noticed that my changes are "only" in testing/camunda-process-test-java/src/main/java/io/camunda/process/test/impl/client/FlowNodeInstanceState.java, so in a very specific place. I had falsely assumed that this was a central place.

Therefore my PR is of less priority. I'll leave it up to you to apply the workaround or ignore it.

**Pull request closed without merging**
