### PR TITLE
ci: Enable test execution for camunda-process-test-java

### PR DESCRIPTION
**Pull request by saig0**
## Description

We reduced the test execution time for the module `testing/camunda-process-test-java`. Let's remove the ignore and run the
 tests.

### CODE REVIEW

**Comment by saig0** [comment]
The tests were executed successfully in 8 seconds ([ref](https://github.com/camunda/camunda/actions/runs/9656621797/job/26634445525#step:8:5720)). :rocket:

**Comment by Zelldon** [comment]
> The tests were executed successfully in 8 seconds ([ref](https://github.com/camunda/camunda/actions/runs/9656621797/job/26634445525#step:8:5720)). 🚀

Amazing :)

**Comment by Zelldon** [comment]
How did you do it? :)

**Review by ChrisKujawa — APPROVED** [review]
🚀

**Comment by saig0** [comment]
> How did you do it? :)

@Zelldon I followed your advice. :wink: I morphed the integration tests into unit tests by using mocks. Concrete: I avoid starting Docker containers but use mocks for the containers ([ref](https://github.com/camunda/camunda/pull/19656/commits/3f08bd7599c959ce460cddaabcbb98c5055f5383)).

**Comment by Zelldon** [comment]
> > How did you do it? :)
> 
> @Zelldon I followed your advice. 😉 I morphed the integration tests into unit tests by using mocks. Concrete: I avoid starting Docker containers but use mocks for the containers ([ref](https://github.com/camunda/camunda/pull/19656/commits/3f08bd7599c959ce460cddaabcbb98c5055f5383)).

Awesome! 🚀  I love it when plans work out 😆 But I guess we just need one or two real integration tests that still check that everything can start :) (Not sure whether you still have this)

**Comment by saig0** [comment]
> But I guess we just need one or two real integration tests that still check that everything can start :)

@zelldon yes. :+1: I have one integration test with the postfix "IT". :wink: We might move these integration tests into a general QA module.

**Pull request merged**
