### PR TITLE
chore(broker): Keep records of active long polling requests

### LINKED ISSUE #4822: Merge PR4681 to develop
**Description**

The bugfix #4681 needs to be merged into current development branch.

### PR DESCRIPTION
**Pull request by pihme**
## Description

Merge PR4681 into develop

## Related issues

closes #4822

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by pihme** [comment]
@korthout Added you as reviewer, because you did some refactoring recently and I want to make sure that my merge fits to your refactoring

**Comment by pihme** [comment]
Benchmark is running (namespace pihme-4822) and looking good

**Review by korthout — APPROVED** [review]
LGTM 👍 
Changes in #4660 focussed on `Gateway` class rather than the `ActivateJobsHandler`. The changes to that class were practically only extract interface and a small change to the constructors.

**Comment by Zelldon** [comment]
@pihme Is there anything which is different to the previous PR which I should check? Bbecause I dont want to do the review again :sweat_smile:

**Comment by pihme** [comment]
@Zelldon There was a refactoring of the `ActivateJobsHandler` and the introduction of the "RoundRobinActivateJobsHandler`. This happened on develop as part of another issue.

This lead to the code being split differently between `LongPollingActivateJobsHandler`and "RoundRobinActivateJobsHandler` than in the previous release.

**Review by ChrisKujawa — APPROVED** [review]
I think it looks ok I did scan over the changes but made not a detailed review as I already did for https://github.com/zeebe-io/zeebe/pull/4681

Do you think it makes sense to run a new benchmark since we had changes in between like the refactoring you mentioned?

**Comment by pihme** [comment]
I did run a benchmark, everything looked good

**Comment by pihme** [comment]
bors retry

**Pull request merged**
