### PR TITLE
Improve logging

### LINKED ISSUE #7145: Improve snapshot commit and corruption reporting
**Description**

This came out of https://github.com/camunda-cloud/zeebe/issues/7136 - the logging around when/how we commit snapshots, and how we we report errors, was a bit confusing.

In no particular order:

- When we finish replicating (but haven't validated yet), we write that the snapshot is valid. This is misleading, since we haven't actually checked the integrity of the snapshot.
- When committing a new snapshot, we just say "Created snapshot", which is also misleading as it's unclear whether this is a committed snapshot or not, whether it's been validated, etc.
- When a snapshot is corrupted, we log a warning at start up, but it's unclear how to recover from it. It's also unclear if there's anything to be done - for example, we also warn when we find partial snapshots, but will just delete them if there is another non corrupted snapshot present (as that's still safe to do).

We should be clearer in all these points, and the logs should help guide operators (and ourselves) on what needs to be done.

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

* Improved log messages
* Remove some duplicated logs
* Changed some logs to trace

With this PR the logs on the leader when taking a snapshot is as follows:
```
D 2021-05-31T09:46:25.325267Z Broker-2-SnapshotStore-1 Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/1/pending/408095-1-1413852-1413500.  Broker-2-SnapshotStore-1
I 2021-05-31T09:46:25.386284Z Broker-2-SnapshotDirector-1 Finished taking temporary snapshot, need to wait until last written event position 1414267 is committed, current commit position is 1413834. After that snapshot will be committed.  Broker-2-SnapshotDirector-1
I 2021-05-31T09:46:25.509406Z Broker-2-SnapshotStore-1 Committed new snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/408095-1-1413852-1413500, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/408095-1-1413852-1413500.checksum, checksum=771660498, metadata=FileBasedSnapshotMetadata{index=408095, term=1, processedPosition=1413852, exporterPosition=1413500}}  Broker-2-SnapshotStore-1
D 2021-05-31T09:46:25.510787Z Broker-2-SnapshotStore-1 Deleting previous snapshot 142629-1-495701-494710  Broker-2-SnapshotStore-1
D 2021-05-31T09:46:25.515182Z Broker-2-DeletionService-1 Compacting Atomix log up to index 408095  Broker-2-DeletionService-1
D 2021-05-31T09:46:25.515266Z Broker-2-SnapshotStore-1 New snapshot 408095-1-1413852-1413500 was persisted. Start replicating.  Broker-2-SnapshotStore-1
D 2021-05-31T09:46:25.526633Z raft-partition-partition-1 - Deleting log up from 136375 up to 382447 (removing 19 segments)  
D 2021-05-31T09:46:25.532030Z Broker-2-SnapshotDirector-1 Current commit position 1414290 >= 1414267, snapshot 408095-1-1413852-1413500 is valid and has been persisted.  Broker-2-SnapshotDirector-1
D 2021-05-31T09:46:27.891380Z Created segment: JournalSegment{id=31, index=410066}  

```
New logs on the follower when receiving a snapshot:
```
D 2021-05-31T09:46:25.532935Z Started receiving new snapshot FileBasedSnapshotMetadata{index=408095, term=1, processedPosition=1413852, exporterPosition=1413500} with 8 chunks.  
D 2021-05-31T09:46:25.548359Z Received all snapshot chunks (8/8) of snapshot 408095-1-1413852-1413500. Committing snapshot.  
I 2021-05-31T09:46:25.570591Z Broker-1-SnapshotStore-1 Committed new snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/408095-1-1413852-1413500, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/408095-1-1413852-1413500.checksum, checksum=771660498, metadata=FileBasedSnapshotMetadata{index=408095, term=1, processedPosition=1413852, exporterPosition=1413500}}  Broker-1-SnapshotStore-1
D 2021-05-31T09:46:25.571814Z Broker-1-SnapshotStore-1 Deleting previous snapshot 142629-1-495701-494710  Broker-1-SnapshotStore-1
D 2021-05-31T09:46:25.576494Z Broker-1-DeletionService-1 Compacting Atomix log up to index 408095  Broker-1-DeletionService-1
I 2021-05-31T09:46:25.576612Z RaftServer{raft-partition-partition-1}{role=FOLLOWER} - Delete existing log (lastIndex '323917') and replace with received snapshot (index '408095')  
```

Old logs:
```
D 2021-05-31T07:42:10.022527Z Based on lowest exporter position '1318110348' and last processed position '1318111856', determined '1318110348' as snapshot position. 
D 2021-05-31T07:42:10.023538Z Taking temporary snapshot into /usr/local/zeebe/data/raft-partition/partitions/1/pending/447467168-21-1318111856-1318110348. 
D 2021-05-31T07:42:10.075404Z Created pending snapshot for Broker-0-StreamProcessor-1 
I 2021-05-31T07:42:10.075812Z Finished taking snapshot, need to wait until last written event position 1318112064 is committed, current commit position is 1318111856. After that snapshot can be marked as valid. 
D 2021-05-31T07:42:10.128173Z Purging snapshots older than FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/447467168-21-1318111856-1318110348, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/447467168-21-1318111856-1318110348.checksum, checksum=2863940347, metadata=FileBasedSnapshotMetadata{index=447467168, term=21, processedPosition=1318111856, exporterPosition=1318110348}} 
D 2021-05-31T07:42:10.128427Z Deleting snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/447191739-21-1317296900-1317295700, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/447191739-21-1317296900-1317295700.checksum, checksum=3208231844, metadata=FileBasedSnapshotMetadata{index=447191739, term=21, processedPosition=1317296900, exporterPosition=1317295700}} 
D 2021-05-31T07:42:10.130423Z Search for orphaned snapshots below oldest valid snapshot with index FileBasedSnapshotMetadata{index=447467168, term=21, processedPosition=1318111856, exporterPosition=1318110348} in /usr/local/zeebe/data/raft-partition/partitions/1/pending 
D 2021-05-31T07:42:10.130927Z Compacting Atomix log up to index 447467168 
D 2021-05-31T07:42:10.130960Z New snapshot 447467168-21-1318111856-1318110348 was persisted. Start replicating. 
D 2021-05-31T07:42:10.135840Z raft-partition-partition-1 - Deleting log up from 447189444 up to 447445514 (removing 16 segments) 
D 2021-05-31T07:42:10.141338Z Created new snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/447467168-21-1318111856-1318110348, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/447467168-21-1318111856-1318110348.checksum, checksum=2863940347, metadata=FileBasedSnapshotMetadata{index=447467168, term=21, processedPosition=1318111856, exporterPosition=1318110348}} 
D 2021-05-31T07:42:10.141620Z Aborting transient snapshot FileBasedTransientSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/pending/447191739-21-1317296900-1317295700, checksum=3208231844, snapshotStore=io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore@627a5eb9, metadata=FileBasedSnapshotMetadata{index=447191739, term=21, processedPosition=1317296900, exporterPosition=1317295700}} 
I 2021-05-31T07:42:10.141838Z Current commit position 1318112065 >= 1318112064, snapshot 447467168-21-1318111856-1318110348 is valid and has been persisted. 
```

```
D 2021-05-31T07:39:04.652828Z Consume snapshot snapshotChunk 087847.sst of snapshot 447691219-15-1317123897-1317122946 
D 2021-05-31T07:39:04.654241Z Waiting for more snapshot chunks of snapshot 447691219-15-1317123897-1317122946, currently have 1/8 
D 2021-05-31T07:39:04.655738Z Consume snapshot snapshotChunk 087848.log of snapshot 447691219-15-1317123897-1317122946 
D 2021-05-31T07:39:04.656438Z Waiting for more snapshot chunks of snapshot 447691219-15-1317123897-1317122946, currently have 2/8 
D 2021-05-31T07:39:04.659520Z Consume snapshot snapshotChunk 087849.sst of snapshot 447691219-15-1317123897-1317122946 
D 2021-05-31T07:39:04.660956Z Waiting for more snapshot chunks of snapshot 447691219-15-1317123897-1317122946, currently have 3/8 
D 2021-05-31T07:39:04.661851Z Consume snapshot snapshotChunk 087850.log of snapshot 447691219-15-1317123897-1317122946 
D 2021-05-31T07:39:04.662246Z Waiting for more snapshot chunks of snapshot 447691219-15-1317123897-1317122946, currently have 4/8 
D 2021-05-31T07:39:04.663139Z Consume snapshot snapshotChunk 087852.sst of snapshot 447691219-15-1317123897-1317122946 
D 2021-05-31T07:39:04.663527Z Waiting for more snapshot chunks of snapshot 447691219-15-1317123897-1317122946, currently have 5/8 
D 2021-05-31T07:39:04.663901Z Consume snapshot snapshotChunk CURRENT of snapshot 447691219-15-1317123897-1317122946 
D 2021-05-31T07:39:04.664244Z Waiting for more snapshot chunks of snapshot 447691219-15-1317123897-1317122946, currently have 6/8 
D 2021-05-31T07:39:04.670394Z Consume snapshot snapshotChunk MANIFEST-072790 of snapshot 447691219-15-1317123897-1317122946 
D 2021-05-31T07:39:04.671852Z Waiting for more snapshot chunks of snapshot 447691219-15-1317123897-1317122946, currently have 7/8 
D 2021-05-31T07:39:04.672248Z Consume snapshot snapshotChunk OPTIONS-072793 of snapshot 447691219-15-1317123897-1317122946 
D 2021-05-31T07:39:04.672561Z Received all snapshot chunks (8/8), snapshot 447691219-15-1317123897-1317122946 is valid 
D 2021-05-31T07:39:04.697304Z Purging snapshots older than FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/447691219-15-1317123897-1317122946, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/447691219-15-1317123897-1317122946.checksum, checksum=4166507939, metadata=FileBasedSnapshotMetadata{index=447691219, term=15, processedPosition=1317123897, exporterPosition=1317122946}} 
D 2021-05-31T07:39:04.697681Z Deleting snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/447409604-15-1316304185-1316302802, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/447409604-15-1316304185-1316302802.checksum, checksum=4013793646, metadata=FileBasedSnapshotMetadata{index=447409604, term=15, processedPosition=1316304185, exporterPosition=1316302802}} 
D 2021-05-31T07:39:04.699496Z Search for orphaned snapshots below oldest valid snapshot with index FileBasedSnapshotMetadata{index=447691219, term=15, processedPosition=1317123897, exporterPosition=1317122946} in /usr/local/zeebe/data/raft-partition/partitions/2/pending 
D 2021-05-31T07:39:04.699874Z Compacting Atomix log up to index 447691219 
D 2021-05-31T07:39:04.699875Z Created new snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/447691219-15-1317123897-1317122946, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/2/snapshots/447691219-15-1317123897-1317122946.checksum, checksum=4166507939, metadata=FileBasedSnapshotMetadata{index=447691219, term=15, processedPosition=1317123897, exporterPosition=1317122946}} 
D 2021-05-31T07:39:04.700078Z DELETE dir /usr/local/zeebe/data/raft-partition/partitions/2/pending/447409604-15-1316304185-1316302802-279 
D 2021-05-31T07:39:04.700345Z raft-partition-partition-2 - Deleting log up from 447406264 up to 447667920 (removing 16 segments)
```
## Related issues

closes #7145 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Thanks! Some notes:

How come every line (or almost) ends with the actor name again? :thinking: 

> I 2021-05-31T09:46:25.509406Z Broker-2-SnapshotStore-1 Committed new snapshot FileBasedSnapshot{directory=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/408095-1-1413852-1413500, checksumFile=/usr/local/zeebe/data/raft-partition/partitions/1/snapshots/408095-1-1413852-1413500.checksum, checksum=771660498, metadata=FileBasedSnapshotMetadata{index=408095, term=1, processedPosition=1413852, exporterPosition=1413500}}  Broker-2-SnapshotStore-1

As this is info, it's probably fine to not log the whole `FileBasedSnapshot{...}` but rather just put the ID? Or just the metadata, I guess. If we think the rest is useful, we can add it as a separate trace/debug log.

Then the order of events is a bit confusing for me: we say that we committed the new snapshot, and then that we persisted it, and then even later that it's now valid and persisted. Wasn't it already persisted? What's the difference between committed and persisted? What does valid mean here that committed/persisted doesn't imply? I know this seems like nitpicking, because it's obvious to us now, but I feel it may not be in the future and for others :sweat_smile: 

So for example, this line:

> D 2021-05-31T09:46:25.515266Z Broker-2-SnapshotStore-1 New snapshot 408095-1-1413852-1413500 was persisted. Start replicating.  Broker-2-SnapshotStore-1

Could be rephrased to avoid confusion:

> D 2021-05-31T09:46:25.515266Z Broker-2-SnapshotStore-1 Start replicating newly persisted snapshot 408095-1-1413852-1413500

Similarly:

> D 2021-05-31T09:46:25.515182Z Broker-2-DeletionService-1 Compacting Atomix log up to index 408095

To:

> D 2021-05-31T09:46:25.515182Z Broker-2-DeletionService-1 Schedule log compaction up to index 408095

And finally:

> D 2021-05-31T09:46:25.532030Z Broker-2-SnapshotDirector-1 Current commit position 1414290 >= 1414267, snapshot 408095-1-1413852-1413500 is valid and has been persisted. 

This has nothing really to do with the commit position, it just signals the success of the persisting. Which is interesting in a sense - should we log info here (the real trigger for persisting), or just would log it in the persist method? Logging it in the persist method centralizes that information for all use cases (replication, local snapshots, etc.), but doesn't convey context of why it was triggered, which logging it at the call site does. But then you have to make sure to log it at all call sites.

I don't know really which is the best option, but I can say having both is a little confusing. Maybe we can reword this? Maybe we pull up this log statement to before calling `pendingSnapshot.persist()` as:

> D 2021-05-31T09:46:25.532030Z Broker-2-SnapshotDirector-1 Current commit position 1414290 >= 1414267, persisting temporary snapshot 408095-1-1413852-1413500...

The `persist` operation itself will log the result. wdyt?

**Comment by deepthidevaki** [comment]
The actor names at end are just something Stackdriver does. I had added it as a custome field. In the actual logs there are no actor names at the end.  See the following logs from a local run.

I updated the messages based on your comment. One think I'm not sure is - after moving the message "Current commit position 44 >= 44, snapshot has been persisted", there is no log in AsyncSnapshotDirector which indicates that control is back in the director and it is ready to take next snapshot. But this should be ok.

```
2021-06-02 08:52:48.427 [Broker-0-SnapshotStore-1] [Broker-0-zb-fs-workers-1] DEBUG
      io.camunda.zeebe.logstreams.snapshot - Taking temporary snapshot into /home/deepthi/work/zeebe-io/zeebe/data/raft-partition/partitions/1/pending/46-4-43-9223372036854775807.
2021-06-02 08:52:48.517 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] INFO 
      io.camunda.zeebe.logstreams.snapshot - Finished taking temporary snapshot, need to wait until last written event position 44 is committed, current commit position is 44. After that snapshot will be committed.
2021-06-02 08:52:48.517 [Broker-0-SnapshotDirector-1] [Broker-0-zb-fs-workers-1] DEBUG
      io.camunda.zeebe.logstreams.snapshot - Current commit position 44 >= 44, committing snapshot FileBasedTransientSnapshot{directory=/home/deepthi/work/zeebe-io/zeebe/data/raft-partition/partitions/1/pending/46-4-43-9223372036854775807, checksum=102791379, metadata=FileBasedSnapshotMetadata{index=46, term=4, processedPosition=43, exporterPosition=9223372036854775807}}.
2021-06-02 08:52:48.531 [Broker-0-SnapshotStore-1] [Broker-0-zb-fs-workers-1] INFO 
      io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Committed new snapshot 46-4-43-9223372036854775807
2021-06-02 08:52:48.531 [Broker-0-SnapshotStore-1] [Broker-0-zb-fs-workers-1] DEBUG
      io.camunda.zeebe.snapshots.impl.FileBasedSnapshotStore - Deleting previous snapshot 44-4-41-9223372036854775807
2021-06-02 08:52:48.533 [Broker-0-SnapshotStore-1] [Broker-0-zb-fs-workers-1] DEBUG
      io.camunda.zeebe.logstreams.snapshot - Start replicating new snapshot 46-4-43-9223372036854775807
2021-06-02 08:52:48.533 [Broker-0-DeletionService-1] [Broker-0-zb-actors-0] DEBUG
      io.camunda.zeebe.broker.logstreams.delete - Scheduling log compaction up to index 46
2021-06-02 08:52:48.533 [] [raft-server-0-raft-partition-partition-1] DEBUG
      io.camunda.zeebe.journal.file.SegmentedJournal - No segments can be deleted with index < 46 (first log index: 1)
```

**Comment by npepinpe** [comment]
Yeah, I understand...as I mentioned, I also considered if it might be better to have the callers of `persist()` log info around it, and have `persist()` log nothing (except maybe debug/trace), but report its state properly (success or failure), and the caller should log it. It means we need to make sure we log it at every call site, but it might make more sense anyway, no? It also gives more context as to why the snapshot was persisted...

On the other hand, if it's centralized in the store, then you only do it once and forget about it - and you might have access to more store/snapshot specific info. I'm really on the fence here, and could use another opinion. I think I lean slightly more towards having it logged at the caller, but I don't have a really strong argument for it I think.

**Comment by deepthidevaki** [comment]
> On the other hand, if it's centralized in the store, then you only do it once and forget about it - and you might have access to more store/snapshot specific info. I'm really on the fence here, and could use another opinion. I think I lean slightly more towards having it logged at the caller, but I don't have a really strong argument for it I think.

I tried to log at the caller. But there are three different locations where a snapshot can be committed. So I would say it is better to log in FileBasedSnapshotStore when a snapshot is committed so that the log messages are consistent. We can log the trigger in the caller to indicate why a snapshot is being committed - whether it is a new snapshot taken, new snapshot received via state replication, or new snapshot received via raft catchup.

**Review by npepinpe — APPROVED** [review]

**Review by miguelpires — APPROVED** [review]

**Pull request merged**
