### PR TITLE
feat(exporters/elasticsearch): add start instructions to PI creation

### LINKED ISSUE #9405: Expand Elastic Search exporter for ProcessInstanceCreation record
Specifically, we'll need to expand the [template of ProcessInstanceCreation record](https://github.com/camunda/zeebe/blob/main/exporters/elasticsearch-exporter/src/main/resources/zeebe-record-process-instance-creation-template.json)) with the start instructions. 

Blocked by #9388

### LINKED ISSUE #9406: Update metrics exporter for start process instance anywhere
The metrics exporter needs to distinguish between process instances started at the root start event and process instances started at other elements. This will allow us to see whether the feature is actively being used in Grafana.

Blocked by #9390 
Possibly blocked by #9397 and #9398 for testing

### PR DESCRIPTION
**Pull request by pihme**
## Description

Add start instructions to PI creation ElasticSearch index template

## Related issues

closes #9405 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@pihme It seems like a test is failing as a result of your change, please have a look at this first and then reassign me for review

**Review by remcowesterhoud — CHANGES_REQUESTED** [review]
@pihme It seems like a test is failing as a result of your change, please have a look at this first and then reassign me for review

**Review by remcowesterhoud — APPROVED** [review]
bors merge

**Comment by remcowesterhoud** [comment]
I literally just mentioned there is a code freeze 🤦 

bors cancel

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors merge

**Pull request merged**
