### PR TITLE
Fix flaky authorization ITs

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Adds logging to failed requests so we can hopefully pinpoint why this is flaky.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Review by cmur2 — DISMISSED** [review]
Pro-forma approval since I don't know anything about the code ^^

**Comment by remcowesterhoud** [comment]
I might not even need to merge it because it already failed on this PR so I can check the logging 🚀

**Comment by cmur2** [comment]
> I might not even need to merge it because it already failed on this PR so I can check the logging 🚀

I dismissed my own review then since there is no time pressure right now and if the PR should get merged, there is time for a proper review 👍🏼

**Comment by remcowesterhoud** [comment]
Not entirely sure why it was flaky. But we were reusing some classes. I stopped reusing them and it now ran 3 times without failure 🤷

**Review by nicpuppa — APPROVED** [review]
❓ Did you understand why reusing the broker for example resolve the flakiness ? I tried to understand but I failed

**Comment by remcowesterhoud** [comment]
> ❓ Did you understand why reusing the broker for example resolve the flakiness ? I tried to understand but I failed

No clue. It was a wild attempt that seems to have worked out. I noticed in one of the logs at some point that it mentioned something about not being able to export to the `CamundaExporter` right at the beginning of the test, before doing anything. This made me believe there may have been some interference between test cases. But I don't have a satisfying explanation for this.

**Pull request merged**
