### PR TITLE
ci: delete optimize workflows from stable/8.6

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

Optimize uses `stable/optimize-8.6` branch for 8.6 releasing, so I am removing the optimize workflows to save some costs.

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Comment by cmur2** [comment]
Makes sense to me as long as the Optimize team is aware (I see they are pinged for review) and agree 👍🏼

**Comment by misiekhardcore** [comment]
We can also remove all the files in `.github/optimize` as they were only used in the workflows that were deleted.
Also these actions can be deleted:
- `.github/actions/compose`
- `.github/actions/docker-logs`
- `.github/actions/execute-healthcheck-and-push-image`
- `.github/actions/login-registry`
- `.github/actions/generate-changelog`
- `.github/actions/git-environment`

**Review by misiekhardcore — COMMENTED** [review]
We can also remove all the files in `.github/optimize` as they were only used in the workflows that were deleted.
Also these actions can be deleted:
- `.github/actions/compose`
- `.github/actions/docker-logs`
- `.github/actions/execute-healthcheck-and-push-image`
- `.github/actions/login-registry`
- `.github/actions/generate-changelog`
- `.github/actions/git-environment`

**Comment by houssain-barouni** [comment]
> We can also remove all the files in `.github/optimize` as they were only used in the workflows that were deleted. Also these actions can be deleted:
> 
> * `.github/actions/compose`
> * `.github/actions/docker-logs`
> * `.github/actions/execute-healthcheck-and-push-image`
> * `.github/actions/login-registry`
> * `.github/actions/generate-changelog`
> * `.github/actions/git-environment`

@misiekhardcore I did the clean-up, but I believe these files wouldn’t have caused any harm if we had kept them.

**Comment by misiekhardcore** [comment]
@houssain-barouni yeah, they do not cause any harm, but its good to remove them if they are not used

**Review by misiekhardcore — APPROVED** [review]

**Pull request merged**
