### PR TITLE
Build ad-hoc test image when running locally

### LINKED ISSUE #7249: Ci current-test docker image blocks local development
**Description**

I had several times in the past that I wanted to run IT test locally, which depend on a zeebe docker image with the tag `current-test`. This can happen for example if you run the golang IT tests, elasticsearch IT tests or upgrade tests. 

I'm wondering why we did it like this and whether it would be possible to reference the SNAPSHOT tag. I can image that can build at the begin the docker image with the SNAPSHOT tag (and not publish it) then use it in our IT tests (this should work since it uses it from the local registry) and then if all tests are green we can publish the tag (on develop only of course). 

With that we could still run the tests locally at least? This would make it easier to just run IT tests and reproduce issues like this: https://github.com/camunda-cloud/zeebe/issues/7161 

But maybe this doesn't make any sense :shrug: since normally you want to have you local changes in the build. Is there anyway we could improve here? I would like to not always build an docker image by hand before I can run these kind of tests.

### PR DESCRIPTION
**Pull request by npepinpe**
## Related issues

closes #7249 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
@Zelldon - this is just a prototype, so the review here is more to see that it solves your problem, not about the code or anything :smile:

**Comment by npepinpe** [comment]
BTW the path to the Dockerfile is hare coded for my machine, so you'd have to change that. And we'd need to figure out how to get the path in a generic way, but otherwise we can test it for now.

**Review by ChrisKujawa — APPROVED** [review]
Yeah looks like it could work nice. Thanks :+1: would be interesting how the separate step affects our general build time. 

Do you think it make sense to separate/split our Dockerfile, it seems to grow more and more. We could have one for build prod/release and one for us for testing and debug (like benchmarks) or? I mean it is nice that we get it working with the FROM clauses but it feels that is harder to understand, especially if we add more.

**Comment by npepinpe** [comment]
I'm not aware that you can "import" or "include" a Dockerfile into another one. If we split it, we will end up with some duplication, no? I wouldn't want to test images that diverge too much from production. But I get your point, it's getting more complex - plus, if you use standard Docker (without BuildKit), it always builds ALL stages, regardless of which ones you really need, which is pretty annoying. You can just use BuildKit to work around that, but yeah...

**Comment by npepinpe** [comment]
Btw, did you try it out? Did it solve your issues without introducing new ones? :sweat_smile:

**Comment by Zelldon** [comment]
> Btw, did you try it out? Did it solve your issues without introducing new ones? sweat_smile

Haven't tried it I just reviewed it and it look liked it :D I can try it in the next days if you want me to do

**Comment by npepinpe** [comment]
Closing for now, we won't merge it as is anyway. I'd still like to try it out at some point though if it can simplify local development.

**Pull request closed without merging**
