### PR TITLE
Move QA test utilities to their own module

### LINKED ISSUE #10089: Add new utility module specifically for QA tests
**Description**

The QA module (and sub-modules) are meant to test the overall project as whole. They pull in most of it as dependencies, but should never be pulled in themselves. This allows us to test the project holistically (can you even say that? :smile:).

We currently have a `zeebe-test-util` module which is in used in various places in the project, including in the QA tests. In there, there are a few utilities which are specifically only used for QA. The downside here is that these QA-specific utilities are included in other sub-modules, and this could eventually introduce cyclical dependencies depending on the kind of utilities we wish to use.

For QA specific utilities, this is limitation is more of a burden than anything. I would propose we create a new module for QA utilities, move any existing ones there (such as QoL extensions to Testcontainers, actuator related utilities, etc.), and we can later expand and add new ones there as well (e.g. helpers when using `zeebe-process-test`, `zeebe-test-container`, etc.).

EDIT: It's also not straight-forward to just move them to a QA module, as we have both `zeebe-qa-update-tests` and `zeebe-qa-integration-tests`, and the utilities are used in both, and adding a dependency between them wouldn't make much sense (but is possible if we think it's worth avoiding adding a new module).

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR introduces a new module, `zeebe-qa-util`, under the `zeebe-qa` umbrella module. The module is located at `qa/util/pom.xml`. QA utilities from the `test-util` module were moved there as well. No real changes were done other than move things around. 

## Related issues

closes #10089 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
:rocket:

**Comment by npepinpe** [comment]
I would backport this to at least 8.0 as well to avoid issues backporting more things in the future. Let me know if you disagree

**Comment by npepinpe** [comment]
bors merge

**Comment by Zelldon** [comment]
makes sense to me

**Comment by npepinpe** [comment]
Opted to backport only to 8.0. More changes are necessary for 1.3, and we'll only be backporting for the next month, so :crossed_fingers: Let me know if you disagree :+1:

**Pull request merged**
