### PR TITLE
Fixed to run docker as non root container

### LINKED ISSUE #3584: Docker Containers shouldn't run as Root
**Describe the bug**
Today, our docker containers are running as root user.
This might cause problems in some platforms and in general it is a bad practice.

**To Reproduce**
Steps to reproduce the behavior

If possible add a minimal reproducer code sample
Reported by a community user using the Zeebe Helm Charts. Anyone else running in a managed environment will face the same problem, no matter if they are using helm or manually deploying our containers. 
https://github.com/zeebe-io/zeebe-cluster-helm/pull/7

**Expected behavior**

Run all containers as non root users

**Environment:**
 - OS: Kubernetes
 - Zeebe Version: [e.g. 0.22.0-alpha2]
 - Configuration: HELM charts

### PR DESCRIPTION
**Pull request by coolpalani**
## Description

I've created a user and group called zeebe with uid & gid 1000. As a process, we're able to run zeebe as non root container and full fill pod security polices in kubernetes and Openshift as well.

## Related issues

closes #3584

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 161ebbc4cbfcc7fe8615bf1a9daab1384dbdfcd1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by menski** [comment]
Hi @coolpalani,

thanks for providing this fix. Could you share with us where you tested the image with the proposed changes, i.e. which environments with which configurations. This way we can identify the remaining environment we want to test before merging.

**Comment by coolpalani** [comment]
@menski 
This was deployed with pod security policy and tested in Kubernetes v1.17.4 cluster at rancher v2.3.6 orchestration platform.
sample restricted pod security policy here https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/restricted-psp.yaml which was used.

**Comment by menski** [comment]
Hi @coolpalani,

sorry for the delay, in the mean time we also refactor the docker image to being multi-stage build. Therefor your branch has now some conflicts. Are you interested in fixing them? Otherwise I will do this myself. Just let me know. Thanks again for your help.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 161ebbc4cbfcc7fe8615bf1a9daab1384dbdfcd1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by coolpalani** [comment]
@menski 
I've resolved the conflicts. Review the changes and let me know your comments.

**Comment by menski** [comment]
Hi @coolpalani,

thanks for resolving the conflicts. I checked the image and think it looks good. I have one question left, as the image does create a Zeebe user, but not set's it as default the container by default still starts as `root` user if not another user is specified. Is that intentionally from your side?

**Review by menski — APPROVED** [review]
Thanks for the clarification and thanks again for you contribution :+1:

**Pull request merged**
