### PR TITLE
Introduce interval variable to Grafana Dashboards

### LINKED ISSUE #11567: Adjust grafana dashboard to always use same rate interval
**Description**

All over in our grafana dashboard we use different rate intervals, sometimes 30s sometimes 1m. Mostly because we don't know better in the past. Ideally I would like to see an introduction of a new variable which we use in all places. 

As default value we potentially would use `$__rate_interval` (@oleschoenburg me recently teached about). 

One StackOverflow post summaries this pretty good:

> Prometheus periodically fetches data from your application. Grafana periodically fetches Data from Prometheus. Grafana does not know, how often Prometheus polls your application for data. Grafana will estimate this time by looking at the data. The $__interval variable expands to the duration between two data points in the graph. (Note that this is only true for small time ranges and high resolution as the intended use case for $__interval is reducing the number of data points when the time range is wide. See [Approximate Calculation of $__interval](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__interval).)
> 
> If the time-distance between every two data points in each series is 15 seconds, it does not make sense to use anything less than [15s] as interval in the rate function. The rate function works best with at least 4 data points. Therefore [1m] would be much better than anything betweeen [15s] and [1m]. This is what $__rate_interval tries to achieve: guessing a minimal sensible interval for the rate function.
>
> https://stackoverflow.com/a/72374057/2165134

Ideally it makes sense to also set the prometheus scrape interval in the grafana configuration, so the calculation works better (since grafana assumes it is 15seconds). See this post https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/

**Why is this interesting:**

1. We have use everywhere the same rate interval which makes the graphs comparable
2. If you reduce the time interval to a short time frame the dashboard doesn't break, as shown [here](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/#:~:text=The%20result%20is%20very%20disappointing%3A%20%E2%80%9CNo%20data%E2%80%9D!%20The) 
3. We can play around with different interval more easily if we have a variable used everywhere

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

A new interval variable allows being used of range vectors in order to change rate function dynamically.

Defaults to `$__rate_interval`, [which is provided by grafana](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/) (but needs to be configured). 
It estimates a good time duration based on the Prometheus scrape
interval, where at least four data points are included in the range
vectors.

Since it might be necessary to configure it in Grafana (it defaults to
30s?) It makes sense to provide some other possible values, which can be
used by customers or us in SaaS where this configuration might be
different or is not applicable.

The variable allows that all panels use the same time duration, and
are comparable.

All three dashboards have been updated. You can as an example take a look at https://grafana.dev.zeebe.io/d/1231232143/test-interval-zeebe?orgId=1&refresh=10s&var-DS_PROMETHEUS=Prometheus&var-cluster=All&var-namespace=medic-y-2023-cw-17-88574eb-benchmark&var-pod=All&var-partition=All&var-interval=$__rate_interval 

Example sed, which has been used:

```
$ sed -i 's/[[0-9]+[ms]]/[$interval]/g' zeebe-overview.json
```

## Related issues

closes https://github.com/camunda/zeebe/issues/11567

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Thanks for tackling this @Zelldon :+1: 

I'm not convinced that having an `interval` drop-down is a good approach though. For one, some of the panels looks a bit funny:
image

I'd rather just use `$__rate_interval` everywhere. As you said, it relies on a configuration value in Grafana but I think that's manageable? At least `$__rate_interval` should be better than the hardcoded `1m` everywhere. I've also checked out [popular grafana dashboards](https://grafana.com/grafana/dashboards/) and none of them had interval drop-downs.

I'm approving anyhow since I don't want to block this from merging.

**Comment by Zelldon** [comment]
> I'd rather just use $__rate_interval everywhere. As you said, it relies on a configuration value in Grafana but I think that's manageable? At least $__rate_interval should be better than the hardcoded 1m everywhere. I've also checked out [popular grafana dashboards](https://grafana.com/grafana/dashboards/) and none of them had interval drop-downs.

**Comment by Zelldon** [comment]
Would be interested in @npepinpe or @megglos opinions on this.

**Comment by npepinpe** [comment]
I would lean towards just using `$__rate_interval`, mostly because I don't understand what the problem is if different deployments have different values for them. What breaks when the deployment of Grafana changes the interval? Which metrics would not work/look confusing?

**Comment by Zelldon** [comment]
The problem is just if you have a higher scrape interval and not configured grafana probably then you might up in range vectors with not enough data points. This means graphs with latencies etc might show no data.

If you both want me to remove it I can do that.

**Comment by Zelldon** [comment]
Thanks both. I think I agree with you that it might be to overpowered/engineered, so I will follow yagni.

* I removed the variable again
* Set rate_interval everywhere
* Removed the interval reference from the panel title to avoid confusion.

**Pull request merged**
