### PR TITLE
Fix backwards compatibility of ProcessInstanceModificationRecordValue

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

The changes in https://github.com/camunda/zeebe/pull/10779 renamed a method. We had discussed this before in the team and decided it was fine, however revapi doesn't like it. Because of this the backport failed. I'm not entirely sure why the regular merge did not have any problems.
This PR restored this method and deprecates it.

## Related issues

Related to https://github.com/camunda/zeebe/pull/10779

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
The change needs to be back ported, but I will have to cherry-pick this manually as I cannot add it to the previous backport PR.

**Review by korthout — CHANGES_REQUESTED** [review]
As discussed f2f, we should not deprecate these methods, but just remove them. To do that, you'll need to appease rev-api. 

It did not fail on the `main` branch because it looked back at `8.1.0`, while this change was 'added' in `8.1.2` as a bug fix. 

We'll need to adjust our release process somehow to update the [backwards-compatible-value](https://github.com/camunda/zeebe/blob/b73753d778856809d01807a18288ccc95556fa38/parent/pom.xml#L150) appropriately.

**Review by korthout — APPROVED** [review]
LGTM 💯 

❓ Do we need to inform users about this change somehow?

**Comment by remcowesterhoud** [comment]
> Do we need to inform users about this change somehow?

I would say no. As we had discussed it is a very recent change with data that is not relevant for users to consume.

bors merge

**Pull request merged**
