### PR TITLE
chore(benchmark): enable starters to create workflow with results

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Enable benchmark starters to create workflow with await results. This would enable us to better monitor overall workflow latency as observed by a client. 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
imo I would propose to have a separate application which inherits and modifies the `Starter`, but this is also fine and tbh it's just the benchmark App, so I don't care that much. I would also propose if we do refactoring that we just refactor the benchmark app in general to something we're more used to, like a Spring Boot app, so I wouldn't put too much effort right now.

From my side it looks good and useful :+1:

**Review by npepinpe — APPROVED** [review]

**Review by ChrisKujawa — APPROVED** [review]
Did you tried it? What was the behavior then?

**Comment by deepthidevaki** [comment]
Here is the request latency from grpc client metrics. The lower latencies are for the requests with errors.

image

**Comment by Zelldon** [comment]
Thanks @deepthidevaki :+1:

**Pull request merged**
