### PR TITLE
ci: remove unused CI files introduced by Optimize

### PR DESCRIPTION
**Pull request by buccarel**
This PR removes the entries in the .ci/ directory that were introduced by the optimize merge.
The files that were there before optimize have been left untouched.

### CODE REVIEW

**Review by HeleneW-dot — APPROVED** [review]
Lgtm as far as removing all the c7 stuff, are we sure we dont need the files in `c8saas` and `c8sm`? What do these files do? There are also failing Optimize Helm Chart Integration tests, can you please check if those are related

**Review by HeleneW-dot — CHANGES_REQUESTED** [review]
Meant to request changes see the comment above

**Comment by buccarel** [comment]
> Lgtm as far as removing all the c7 stuff, are we sure we dont need the files in `c8saas` and `c8sm`? What do these files do? There are also failing Optimize Helm Chart Integration tests, can you please check if those are related

I believe those files are under the deployment-preview directory, which is something that is not supposed to stay in the monorepo: preview environments will be added later with this https://github.com/camunda/camunda/issues/17684

**Comment by PHWaechtler** [comment]
> > Lgtm as far as removing all the c7 stuff, are we sure we dont need the files in `c8saas` and `c8sm`? What do these files do? There are also failing Optimize Helm Chart Integration tests, can you please check if those are related
> 
> I believe those files are under the deployment-preview directory, which is something that is not supposed to stay in the monorepo: preview environments will be added later with this #17684

Makes sense 

> About the helm chart failures, I don't really know. They don't seem to look for any file under `.ci/`. Am I missing anything?

Are these tests also failing on the merge PR? This PR is removing files from a directory named Helm-charts. Some of the errors look like something is misconfigured or missing: `Input required and not supplied: $***name***``, some errors look like an incorrect command: `Error: flags cannot be placed before plugin name: -n`. The workflow files looks to have been introduced by Michal, maybe he is more familiar with the errors?

**Review by HeleneW-dot — CHANGES_REQUESTED** [review]
Another question I noticed while looking into workflow removal - this isnt removing podSpecs/clusterTests. Is there. a reason for that?

**Comment by misiekhardcore** [comment]
I can see that `.github/workflows/optimize-preview-env-deploy.yml` is still referencing files in `.ci`. Should we also delete/modify this workflow?

**Review by misiekhardcore — APPROVED** [review]

**Comment by buccarel** [comment]
> I can see that `.github/workflows/optimize-preview-env-deploy.yml` is still referencing files in `.ci`.

I think that file shall be removed, yeah. Thanks for spotting it.

> Should we also delete/modify this workflow? Also there is a `.github/workflows/optimize-backend-linting.yml` workflow which also points to that directory, maybe it also need an update or maybe we need to remove it if there is a monorepo linter.

Yes, we don't need to lint that anymore. The directory .ci that is left in the repo does not belong to Optimize. Thanks

Will go ahead and address these comments, thanks

**Review by HeleneW-dot — APPROVED** [review]
LGTM if the rest of the pipelines wont fail (with new errors)

**Pull request merged**
