### PR TITLE
[Backport stable/8.0] fix(raft): handle exceptions on partition server init

### PR DESCRIPTION
**Pull request by megglos**
# Description
Backport of #10450 to `stable/8.0`.

### CODE REVIEW

**Comment by Zelldon** [comment]
Test failed with:

```
[ERROR] io.camunda.zeebe.broker.bootstrap.PartitionManagerStepTest$StartupBehavior.shouldHandleSyncFailOfStart  Time elapsed: 1.048 s  <<< ERROR!

[2022-09-26T15:40:33.736Z] java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Actor scheduler is not running

[2022-09-26T15:40:33.736Z] 	at io.camunda.zeebe.util.sched.future.TestActorFuture.get(TestActorFuture.java:133)

[2022-09-26T15:40:33.736Z] 	at io.camunda.zeebe.util.sched.future.TestActorFuture.get(TestActorFuture.java:141)

[2022-09-26T15:40:33.736Z] 	at org.assertj.core.internal.Futures.assertFailedWithin(Futures.java:118)

[2022-09-26T15:40:33.736Z] 	at org.assertj.core.api.AbstractFutureAssert.internalFailsWithin(AbstractFutureAssert.java:446)

[2022-09-26T15:40:33.736Z] 	at org.assertj.core.api.AbstractFutureAssert.failsWithin(AbstractFutureAssert.java:402)

[2022-09-26T15:40:33.736Z] 	at io.camunda.zeebe.broker.bootstrap.PartitionManagerStepTest$StartupBehavior.shouldHandleSyncFailOfStart(PartitionManagerStepTest.java:155)

[2022-09-26T15:40:33.736Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2022-09-26T15:40:33.736Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[2022-09-26T15:40:33.736Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2022-09-26T15:40:33.736Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[2022-09-26T15:40:33.736Z] 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)

[2022-09-26T15:40:33.736Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)

[2022-09-26T15:40:33.736Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)

[2022-09-26T15:40:33.736Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)

[2022-09-26T15:40:33.736Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)

[2022-09-26T15:40:33.736Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)

[2022-09-26T15:40:33.736Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)

[2022-09-26T15:40:33.736Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)

[2022-09-26T15:40:33.736Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:155)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)

[2022-09-26T15:40:33.737Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)

[2022-09-26T15:40:33.745Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:155)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:129)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)

[2022-09-26T15:40:33.746Z] 	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[2022-09-26T15:40:33.746Z] Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Actor scheduler is not running

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)

[2022-09-26T15:40:33.746Z] 	... 5 more

[2022-09-26T15:40:33.746Z] Caused by: java.lang.IllegalStateException: Actor scheduler is not running

[2022-09-26T15:40:33.746Z] 	at io.camunda.zeebe.util.sched.ActorScheduler.checkRunningState(ActorScheduler.java:72)

[2022-09-26T15:40:33.746Z] 	at io.camunda.zeebe.util.sched.ActorScheduler.submitActor(ActorScheduler.java:33)

[2022-09-26T15:40:33.746Z] 	at io.camunda.zeebe.broker.partitioning.PartitionManagerImpl.start(PartitionManagerImpl.java:124)

[2022-09-26T15:40:33.746Z] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)

[2022-09-26T15:40:33.746Z] 	... 6 more

[2022-09-26T15:40:33.746Z] 
```

@megglos can you take a look?

**Comment by megglos** [comment]
bors merge

**Comment by Zelldon** [comment]
@megglos did you changed the last commit? :thinking: Do we need to change this on main as well?

**Comment by megglos** [comment]
yeah, shall I put it into a separate commit? the assertion needed adjustment due to slightly different future behaviour

**Comment by Zelldon** [comment]
@megglos makes it easier to review and spot, because right now it was not clear to me what changed :see_no_evil: So general rule of thumb is in the team to add extra commits and if review is done you can squash if you want

**Review by ChrisKujawa — APPROVED** [review]
:+1:

**Comment by oleschoenburg** [comment]
bors merge

**Comment by oleschoenburg** [comment]
bors merge

**Comment by oleschoenburg** [comment]
bors r-

This needs some changes before we can merge

**Comment by oleschoenburg** [comment]
Ugh, I cancelled the wrong PR, my bad. This is ready to merge, https://github.com/camunda/zeebe/pull/10624 wasn't.

**Comment by oleschoenburg** [comment]
bors merge

**Pull request merged**
