### PR TITLE
Migrate to new io.camunda.zeebe package and groupId

### LINKED ISSUE #6873: Adjust group id and packages the new io.camunda domain
**Description**

All maven artifacts should be using the `io.camunda` prefix, i.e `io.zeebe.engine` becomes `io.camunda.zeebe.engine`

### PR DESCRIPTION
**Pull request by menski**
## Description

- Move everything from io.zeebe to io.camunda.zeebe
- Disable sonarcloud from CI pipeline until its associated with new package id
- Copies some client creation code from test container into the test classes in IT and update tests, until test container is released with new package ids

## Related issues

closes #6873 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
Let's create a follow up issue to keep track of all things we need to do after:

1. Update getting started guides
2. Reenable SonarCloud
3. ???

**Comment by menski** [comment]
Sonar Cloud: #6927
Getting Started Guides: #6928

**Review by npepinpe — CHANGES_REQUESTED** [review]
It looks like .ci/scripts/docker/prepare.sh still pulls from groupId io.zeebe? Otherwise I couldn't find anything, but it's so much stuff that I can't guarantee I didn't miss anything.

**Review by npepinpe — APPROVED** [review]

**Pull request merged**
