### PR TITLE
Migrate to go modules

### LINKED ISSUE #3390: Migrate to Go modules
**Description**

Migrate the Go client to gomod.

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

MIgrates to go modules. This PR depends on the zbctl merge PR and on the layout changes PR.

## Related issues

closes #3390

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:tada:

**Comment by MiguelPires** [comment]
bors retry

**Comment by MiguelPires** [comment]
Bors r+

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
