### PR TITLE
Re-enable nightly QA trigger on develop

### LINKED ISSUE #6900: Re-enable nightly QA run on develop
**Description**

As soon as camunda cloud generation for `1.0.0` is available, we need to upgrade the `Testbench 1.x Prod` cluster to that version and re-enable the nightly QA run on develop. After that, we should also remove the `nightly-qa-run` branch.

The nightly QA run was disabled on develop due to breaking changes in the client protocol. Instead, the nightly run was moved to the `nightly-qa-run` branch (branched from the parent commit of the breaking change).

### PR DESCRIPTION
**Pull request by korthout**
## Description

In order to run the nightly QA run against develop (and future stable branches), this re-adds the cron trigger that runs it.

## Related issues

closes #6900

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by korthout** [comment]
@npepinpe do we want to enable nightly QA runs against `release-1.0.0` branch as well?

**Review by npepinpe — APPROVED** [review]
bors r+

Please backport :)

**Comment by korthout** [comment]
>Please backport :)

It requires a bit more, because `release-1.0.0` branch is not one of the branches this is enabled for. I'll create a separate PR.

**Comment by npepinpe** [comment]
Ah, right. Hm, no then it's fine, we will build 1.0 Monday anyway so I don't expect much divergence. No worries, leave it as is.

**Comment by korthout** [comment]
Sure no problem. As soon as `stable/1.0.0` exists, it will run there anyways

**Comment by korthout** [comment]
@npepinpe It can't hurt to test the backport bot with this one

**Comment by korthout** [comment]
Failed due to: 
```
Verify / Test (Java) / shouldRestoreStateAtEachStepInExecution[TestDataRecord{processSeed=5688390484059413195, executionPathSeed=-3760879499967994381}] – ReplayStateRandomizedPropertyTest(java-testrun)
```

This is unrelated to this change (although interesting) - linked #6923 

bors retry

**Comment by npepinpe** [comment]
bors retry

**Pull request merged**
