### PR TITLE
Wait for correct amount of completed workflow instances in test

### PR DESCRIPTION
**Pull request by menski**

### CODE REVIEW

**Comment by menski** [comment]
Should prevent test failures like:
```
[2019-06-05T12:46:30.199Z] [ERROR] shouldActivateJobsFromWorkflow(io.zeebe.broker.engine.job.ActivateJobsTest)  Time elapsed: 5.421 s  <<< FAILURE!
[2019-06-05T12:46:30.199Z] java.lang.AssertionError: 
[2019-06-05T12:46:30.199Z] 
[2019-06-05T12:46:30.199Z] Expecting:
[2019-06-05T12:46:30.199Z]   <[2251799813685346L,
[2019-06-05T12:46:30.199Z]     2251799813685349L,
[2019-06-05T12:46:30.199Z]     2251799813685353L,
[2019-06-05T12:46:30.199Z]     2251799813685357L,
[2019-06-05T12:46:30.199Z]     2251799813685361L,
[2019-06-05T12:46:30.199Z]     2251799813685366L]>
[2019-06-05T12:46:30.199Z] to contain only:
[2019-06-05T12:46:30.199Z]   <[2251799813685346L,
[2019-06-05T12:46:30.199Z]     2251799813685349L,
[2019-06-05T12:46:30.199Z]     2251799813685353L,
[2019-06-05T12:46:30.199Z]     2251799813685357L,
[2019-06-05T12:46:30.199Z]     2251799813685361L,
[2019-06-05T12:46:30.199Z]     2251799813685366L,
[2019-06-05T12:46:30.199Z]     2251799813685373L,
[2019-06-05T12:46:30.199Z]     2251799813685380L,
[2019-06-05T12:46:30.199Z]     2251799813685387L,
[2019-06-05T12:46:30.200Z]     2251799813685393L]>
[2019-06-05T12:46:30.200Z] but could not find the following elements:
[2019-06-05T12:46:30.200Z]   <[2251799813685373L, 2251799813685380L, 2251799813685387L, 2251799813685393L]>
[2019-06-05T12:46:30.200Z] 
[2019-06-05T12:46:30.200Z] 	at io.zeebe.broker.engine.job.ActivateJobsTest.shouldActivateJobsFromWorkflow(ActivateJobsTest.java:362)
```

**Review by miguelpires — APPROVED** [review]
bors +

**Comment by menski** [comment]
bors retry

**Pull request merged**
