### PR TITLE
Speed up state controller recovery from existing snapshot

### LINKED ISSUE #13775: Improve ZeebePartition recovery time with large state
**Description**

We had an incident where the liveness probes failed after 45s due to large state. This is a cluster with 3 partitions, each with a RocksDB state of over 7GB. For each partition, it took about 10 seconds purely to open the DB, which includes copying the snapshot and opening the DB. Furthermore, it seems like each partition was recovered sequentially and not in parallel, from the logs, but I haven't verified that.

The goal here would be to try and either optimize the recovery time, or have it not be w.r.t the size of the state (ideally the second one).

One issue which might be the biggest culprit in this case is this one: https://github.com/camunda/zeebe/issues/5682

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR greatly improves the state recovery time from an existing snapshot, especially when the state grows to be very large. This is done by leveraging RocksDB checkpoint capabilities, which create hard-links for the immutable SST files if the source and target directories are on the same filesystem. This has the additional benefit of reducing disk space usage in most cases.

> **Note**
> When the `runtime` and `snapshot` directories are not on the same filesystem, this will end up doing a normal copy, which is as fast as the previous solution.

## Related issues

closes #13775 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
Blocked by #13937

**Comment by npepinpe** [comment]
Result of the performance test on its first "failing" run:

> Expected reference score is "0.550" got "9.866", deviation "1693.783%" exceeds maximum allowed deviation "20.000%"

:sunglasses:

**Comment by npepinpe** [comment]
So I ran some tests locally, and anecdotally, we see a recovery time of:

| Size in GB | Recovery time seconds (approx) | Recover ops/s (approx) |
|------------|--------------------------------|------------------------|
| 0.512 | 0.1 | 10 |
| 4 | 0.1 | 10 |
| 8 | 0.285 | 3.5 |
| 16 | 0.420 | 2.37 |


Operations per second
Recover time (s) based on state size

**Comment by npepinpe** [comment]
So it's not quite linear, unfortunately. I will do more benchmarks until I find out the point where it is definitely "too" slow, i.e. > 1 second to recover.

**Review by ChrisKujawa — APPROVED** [review]
Great stuff @npepinpe 🚀 
giphy

**Comment by npepinpe** [comment]
bors merge

**Pull request merged**
