### PR TITLE
Export process instance modification records by default

### LINKED ISSUE #9992: Export modification records to ElasticSearch
## Description

We want to export the modification record to ElasticSearch (ES). Consumers of ES can use the records to track, for example, the usage of the modification API.

The ES template for the modification record was already added with #9804. But the records are not exported by default.

We want to export the modification record by default to track the usage in Zeebe Analytics (https://github.com/camunda/zeebe-analytics/issues/83).

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

Changes the default export configuration of process instance modification records to true.

## Related issues

closes #9992

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [x] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
@remcowesterhoud LTGM :+1:

**Comment by saig0** [comment]
@remcowesterhoud please also update the following configuration: [broker.standalone.yaml.template](https://github.com/camunda/zeebe/blob/main/dist/src/main/config/broker.standalone.yaml.template#L558)

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors retry

**Pull request merged**
