### PR TITLE
Add new interface for variables/variable command step

### LINKED ISSUE #13491: Create new interface `CommandWithVariablesCommandStep` for generalize `CommandWithVariables` behaviour
**Is your feature request related to a problem? Please describe.**
As suggested in this [comment](https://github.com/camunda/zeebe/pull/13442#pullrequestreview-1528396630) create an interface to store all the variables/variable method related to `CommandWithVariables`

**Describe the solution you'd like**
Create a new interface `CommandWithVariablesCommandStep`, with these new interface you don't need to define every time the same methods for every commands

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

Create a new interface `CommandWithVariablesCommandStep` to store all the variables/variable step. Every command step that want to expose those APIs needs to extends this new interface. This help us in the future to easily expose variables/variable step without code duplication

## Related issues

closes #13491 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by nicpuppa** [comment]
@remcowesterhoud your suggestion seems not working due to java type erasure for generics, I was thinking about another solution. But I don't get a valid one! I'm open to other suggestions

**Comment by remcowesterhoud** [comment]
Hmm revapi is failing so that means it's not as backwards compatible as we thought. It breaks binary compatibility. So I guess we can't make this change 😞

**Comment by nicpuppa** [comment]
I'm assuming that we can close this PR, what do you think @remcowesterhoud ?

**Comment by remcowesterhoud** [comment]
Yeah let's close this for now.

**Pull request closed without merging**
