### PR TITLE
Resolve flaky `EngineErrorHandlingTest.shouldNotBanInstanceOnJobCommand`

### LINKED ISSUE #13054: Flaky EngineErrorHandlingTest.shouldNotBanInstanceOnJobCommand
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? No
- Do we suspect that it is a real failure?

**Failures**

```
Expecting actual:
  [1L, 2L]
to contain exactly (and in same order):
  [1L, 2L]
but could not find the following elements:
  [2L]
```

**Hypotheses**

**Logs**

https://github.com/camunda/zeebe/actions/runs/5241076389/jobs/9462704317

[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/11720019/Test.results.for.unit.tests.2.zip)

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

This test was using `Mockito` to verify that the `dumpProcessorRef` was called twice before asserting that list of `processedInstances`.

Unfortunately `Mockito` is not good with threading. The `processRecord` method is called in a separate thread from the assertion. As soon as the method is called twice the assertion is true and we continue asserting the list. However, because `processRecord` is in the different thread it may not have executed the method yet. This means the list will not contain both of the expected elements at time of the assertion.

 We can completely remove the spy. By waiting for 2 `COMPLETE_ELEMENT` commands instead we know that the call to `processRecord()` is finished before we start doing assertions.

The assertion failure showed this quite nicely:

```
Expecting actual:
  [1L, 2L]
to contain exactly (and in same order):
  [1L, 2L]
but could not find the following elements:
  [2L]
```

The actual and expected are the exact same, yet it mentions it cannot find one of the elements. This is the result of the thread finishing and filling the list with the second element before the failure message was properly created.

## Related issues

closes #13054 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by berkaycanbc — APPROVED** [review]
Very good improvement! 🚀 This will save us much more build times.

**Comment by remcowesterhoud** [comment]
@berkaycanbc Feel free to just merge the PR if you don't request any changes 😉 Saves me the time of going back here to write bors merge

**Comment by remcowesterhoud** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
bors retry

**Pull request merged**
