### PR TITLE
Raise decision evaluation error incident

### LINKED ISSUE #8095: Create an incident if the evaluation of a decision fails
**Description**

If a business rule task is activated and the evaluation of a decision fails (e.g. missing variables, unexpected variable type, etc.) then we should create an incident. It should signal the user/operator that there is an issue in the DMN resource or the process instance context.

* create an incident if the evaluation of the decision fails
  * create a new error type `DECISION_EVALUATION_ERROR` 
  * the failure message should mention the id of the evaluated decision and include the message from the DMN engine
* if the incident is resolved then we should evaluate the decision again (with the current variables)
  * if the evaluation fails again then we should create a new incident 

blocked by #8080

### PR DESCRIPTION
**Pull request by korthout**
## Description

During development, it was helpful to raise the incident when the evaluation failed with the CALLED_ELEMENT_ERROR type. This made it possible to quickly test that the incident was created and could be resolved. Also in Operate, which already knows the CALLED_ELEMENT_ERROR. Now, we want to differentiate the failure to evaluate a known (deployed) decision from the failure to evaluate an unknown (undeployed) decision. 

This introduces a new `DECISION_EVALUATION_ERROR` error type for incidents. This new type is used in case a business rule task referring to a deployed decision fails to evaluate. 

A similar change was made to introduce `CALLED_DECISION_ERROR` in #8795.

## Related issues

closes #8095

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Comment by korthout** [comment]
@remcowesterhoud Please have a look 🙇 Let me know if anything is unclear

**Review by remcowesterhoud — APPROVED** [review]
@korthout LGTM 🚀 

I did notice Philipp mentioned something in the issue:

>Note that the input mappings of the business rule task are applied again when an incident is resolved. The mappings could override variables that were changed to resolve the incident. We should mention the behavior in the docs.

Should the docs be updated with this PR, or is this a separate thing?

**Comment by korthout** [comment]
> Should the docs be updated with this PR, or is this a separate thing?

The current docs for the [business rule task](https://docs.camunda.io/docs/components/modeler/bpmn/business-rule-tasks/) still only document the job worker behavior. We'll update these docs with https://github.com/camunda-cloud/camunda-cloud-documentation/issues/421 to also deal with the called decision behavior. I'll make sure to add a note to that issue about this.

**Comment by korthout** [comment]
bors merge

**Pull request merged**
