### PR TITLE
ci(docker): build and push amd64 and arm64 SNAPSHOT image

### LINKED ISSUE #11079: Build and deploy SNAPSHOT docker images for amd64/arm64
**Description**
With #11000 adding support for building arm64 images and #11020 verifying their functionality in place, the `deploy-docker-snapshot` job of the GHA ci workflow can be adjusted to build and deploy linux/amd64 & linux/arm64 images.

### PR DESCRIPTION
**Pull request by megglos**
## Description

Can only fully test by merge 🙃, but given the docker-checks are fine we should be good.

## Related issues

closes #11079

### CODE REVIEW

**Comment by npepinpe** [comment]
> Can only test by merge

My favorite kind of tests - in production

production tests

**Comment by megglos** [comment]
hm seems like the arm64 smoke test timed out, unrelated to these changes though, will look into it separately

**Review by npepinpe — APPROVED** [review]
:rocket: 

I guess still no tests, but as it's only snapshot, I don't see the harm. Hopefully no one is running snapshot in production...though now that I say it out loud, I'm suddenly not so sure :smile: 

Though since the arm64 images are new, it shouldn't disrupt anyone, and hopefully anyone looking to move to them would test it out before!

**Comment by megglos** [comment]
> 🚀
> 
> I guess still no tests, but as it's only snapshot, I don't see the harm. Hopefully no one is running snapshot in production...though now that I say it out loud, I'm suddenly not so sure 😄

not sure I follow, as of now we have the smoke tests for arm64 images in place with #11040, what we lack is:
- testing the exact image that actually gets pushed here but that applies to amd64 as well
- running all tests on arm64, [which is currently out of scope](https://github.com/camunda/product-hub/issues/222) for only offering arm64 for development purposes => need to make sure to communicate that properly

is there anything I'm missing? 😅

**Comment by npepinpe** [comment]
Hm, so we test the arm64 image with the `ContainerSmokeTest`? Isn't that running on a `ubuntu-latest` runner, which is amd64? Maybe I missed this, but then the emulation kicks in during the test because only the arm64 image is available? That's clever if so - I thought we were still missing the last step of using the arm64 node. Maybe it should be more explicit that we ONLY build the image for arch to ensure that emulation kicks in - though admittedly this is temporary, and eventually we'll run this on an arm64 node so that documentation is not necessary.

**Comment by megglos** [comment]
looks good on dockerhub:
```
docker manifest inspect camunda/zeebe:SNAPSHOT
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1996,
         "digest": "sha256:79c2ca0e075e38fa3373eab5febe40cc3612d0135dc4e4720e11a270f14772a7",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1996,
         "digest": "sha256:f5f84d8ad5525815ebe16adcd0c2d538da8ffb0efd581a18939b909c485137d2",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by megglos** [comment]
locally fine on macOS arm64
```
➜  zeebe git:(meg-11079-snapshot-multi-arch-image) ✗ docker run -it --entrypoint /bin/bash camunda/zeebe:SNAPSHOT                                                                                                                                                                                                                      gke_zeebe-io_europe-west1-b_zeebe-cluster
Unable to find image 'camunda/zeebe:SNAPSHOT' locally
SNAPSHOT: Pulling from camunda/zeebe
4e7e0215f4ad: Already exists
47b12f4cab5d: Already exists
640e1d5c7cb2: Already exists
46e091c75a4f: Already exists
1469aa4b7061: Pull complete
3ed2bc2da5d7: Pull complete
19c2b8699c6b: Pull complete
fc9d559908a3: Pull complete
Digest: sha256:4a2d902d76e2b16a2918d4959c90d35cb759d45fb925294f756b043015faeaa0
Status: Downloaded newer image for camunda/zeebe:SNAPSHOT
root@323f488edb44:/usr/local/zeebe# uname -a
Linux 323f488edb44 5.15.68-0-virt #1-Alpine SMP Fri, 16 Sep 2022 06:29:31 +0000 aarch64 aarch64 aarch64 GNU/Linu
```

**Comment by npepinpe** [comment]
:rocket:

**Pull request merged**
