### PR TITLE
Fixes wrong source record position due incomplete writer reset

### LINKED ISSUE #5420: The source record position may point to a wrong record
**Describe the bug**
A record can have a source record position. If the record is produced by the stream processing then it points to the record that was processed. Otherwise, the source record position is less than 0. This allows the see the causality.  

Currently, there are some records that have a source record position but that are not produced by processing the record.

**To Reproduce**
1. Verify that the job command with the intent "TIME_OUT" has a source record position (which is not correct)

**Expected behavior**
The source record position is not set if the record was not produced by the processing of another record.

**Log/Stacktrace**

**Environment:**
 - OS: [e.g. Linux]
 - Zeebe Version: 0.23.6, 0.24.3. 0.25.0-SNAPSHOT
 - Configuration: [e.g. exporters etc.]

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes resetting the `TypedRecordWriterImpl` - previously, reset would reset the wrapped log writer, but neither the in-memory metadata nor the source record position, which caused some records written outside of the stream processor to have the wrong source record position.

The reset method now resets its whole state, and also the job time outs also reset the writer every time, not just when the flush failed.

I added regression tests for processors which use the `TypedRecordWriterImpl` outside of the `StreamProcessor`/`ProcessingStateMachine`.

## Related issues

closes #5420 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
Thanks @npepinpe 

I think we wanted to add a comment on the actor usage in the process or at least create a follow up issue to fix the handling of the writers?

**Comment by npepinpe** [comment]
I didn't add the comment because it there isn't a specific place to do so - maybe the class header? Regarding a follow up, I wanted to talk to @saig0 first as to whether or not we want to do it as part of clean up, but I can already write the issue :+1:

**Comment by npepinpe** [comment]
bors retry

**Pull request merged**
