### PR TITLE
Remove 'index' which makes for a bad doc link

### PR DESCRIPTION
**Pull request by cjolivier01**
## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
Hi! For us to accept this PR, you would need to sign the CLA as per the bot's comment.

If that's an issue, we unfortunately cannot accept it.

**Comment by cjolivier01** [comment]
> Hi! For us to accept this PR, you would need to sign the CLA as per the bot's comment.
> 
> If that's an issue, we unfortunately cannot accept it.

sorry, been having some issues with my github config... fixing

**Comment by cjolivier01** [comment]
> Hi! For us to accept this PR, you would need to sign the CLA as per the bot's comment.
> 
> If that's an issue, we unfortunately cannot accept it.

I don't know, I have signed it and when I click the sign thing, it recognizes that I signed it (grayed out because already signed), but it doesn't remove the thing here saying I haven't signed it. Meh. I guess close this if you want.

**Comment by npepinpe** [comment]
You would have to recommit the changes with the right email. It still marks the other commits as from a different user, that's the main thing =/

**Pull request closed without merging**
