### PR TITLE
Align BPMN documentation section 

### PR DESCRIPTION
**Pull request by saig0**
## Description

* introduction: fix image path
* introduction: update Java version to 11
* basic: remove performance section
* bpmn-workflows: align BPMN sections
* bpmn-modeler: remove BPMN modeler sections

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1: 

I like the new BPMN page structures. Maybe mention it at the next team meeting so we always keep this format

**Comment by saig0** [comment]
bors retry

**Pull request merged**
