### PR TITLE
Extend Either/EitherAssert capabilities

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR extends `Either` by adding a new API, `Either#getOrElse(R)`. This allows to extract the right value of the `Either` or returning a fallback. I did not add any tests as the implementation is incredibly simple, and I can't foresee ever getting more complex, but do challenge this.

It also extends the related `EitherAssert` by adding a new adding new `left` and `right` extraction capabilities. So you can now assert something like:

```java
EitherAssert.assertThat(either).left().isEqualTo(1);
EitherAssert.assertThat(instantEither)
	.right()
	.asInstanceOf(InstanceOfAssertFactories.INSTANT)
	.isBetween(today, tomorrow);
```

Note that calling `EitherAssert#right()` will, under the hood, still call `EitherAssert#isRight()`.

This PR is related to #5525 and is extracted from the bigger spike in #8491. You can review how it's used there, specifically in the `JobBatchCollectorTest`. As such, this is marked for backporting, since we'll backport the complete fix for #5525.

## Related issues

related to #5525 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Review by korthout — APPROVED** [review]
👍 Thanks @npepinpe! I really like the changes 🚀 Please consider my comments before merging. All comments are suggestions and don't block merging this.

🔧 I agree that `getOrElse` doesn't really need a test with such a simple implementation. But, to be fair all other methods have tests (even `get`) so I would appreciate one. It should be really straightforward to add. 

🔧  It makes me wonder whether some tests for the EitherAssert are warranted, because it's implementation is not straightforward. Did you generate these or implement them yourself?

❓ We discussed that it was unclear which EitherAssert to use (Zeebe has 2 classes with that name). Can you add some javadoc to the EitherAssert in the test sources of `util` that clarify that it should only be used within that module? Or do you think we should simply remove that class entirely? Alternatively, we could make it an inner class of the EitherTest class. Feel free to do what feels right.

**Comment by npepinpe** [comment]
> 🔧 I agree that `getOrElse` doesn't really need a test with such a simple implementation. But, to be fair all other methods have tests (even `get`) so I would appreciate one. It should be really straightforward to add. 

No problemo muchacho :ok_hand: 

> 🔧  It makes me wonder whether some tests for the EitherAssert are warranted, because it's implementation is not straightforward. Did you generate these or implement them yourself?

100% organic hand written, fresh assertions, sir. I think you're right, it might be getting to a point where having tests would be good.

> ❓ We discussed that it was unclear which EitherAssert to use (Zeebe has 2 classes with that name). Can you add some javadoc to the EitherAssert in the test sources of `util` that clarify that it should only be used within that module? Or do you think we should simply remove that class entirely? Alternatively, we could make it an inner class of the EitherTest class. Feel free to do what feels right.

I'm unsure how useful it is to add it for a single test class. It might make more sense to use plain asserts, or make it an inner class, as you mentioned, but I didn't really look into it. Let me have a look and we'll see.

**Comment by npepinpe** [comment]
I removed the `util`'s `EitherAssert`. It was actually used in the broker tests as well :smile: Replacing its usage in the `EitherTest` was really simple, which goes to show maybe it wasn't all that necessary.

**Comment by korthout** [comment]
Thanks @npepinpe 🙇  Looks great!

**Pull request merged**
