### PR TITLE
Release 0.26.0 alpha1

### PR DESCRIPTION
**Pull request by korthout**
## Description

According to [Performing-a-Release](https://github.com/zeebe-io/zeebe/wiki/Performing-a-Release#merge-release-to-develop-only), we need to merge the changes from the release back to develop.

> If the release is done the changes should be merged to develop (master only for minor releases).
> 
> You can use the following commands:
> 
> ```
> git checkout release-0.X.0-alphaZ
> git pull origin release-0.X.0-alphaZ
> ```
> In case we disabled the upgrade test suite due to backwards incompatible changes, make sure to re-enable it them here.
> 
> Commit any pending changes (e.g. enabling upgrade tests) to the release branch
> 
> ```
> git checkout develop
> git pull origin develop
> git merge --no-ff release-0.X.0-alphaZ
> git push origin develop
> 
> git push origin :release-0.X.0-alphaZ
> ```

Since, we don't want to push on develop directly, I've created a PR for this.

## Related issues

NA

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 737483b044c972fa7e19218692ecb564daafb24e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 00532c00380a425bc79244eb323b33fc98ec99c0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by npepinpe** [comment]
Wait, do we actually want to merge back the alpha branch? Is this useful at all? :thinking:

**Comment by korthout** [comment]
> Wait, do we actually want to merge back the alpha branch? Is this useful at all? 🤔

I doubt it, but the guide said so. I'm happy to change the guide accordingly

**Comment by npepinpe** [comment]
I see no advantage - the only diverging commits would be the maven release ones, and we wouldn't care about those, so I'd happily remove it from the guide.

**Comment by korthout** [comment]
I'll close this PR then and update the guide

**Pull request closed without merging**
