### PR TITLE
Fix NPE on sendCorrelateCommand() side-effect

### LINKED ISSUE #9860: NPE as MessagePublishProcessor tried to sendCorrelateCommand
**Describe the bug**

A NullPointerException (NPE) was thrown while the `MessagePublishProcessor` tried to send the `CORRELATE` command. Specifically the [`flush`](https://github.com/camunda/zeebe/blob/bbbb0d3e8455efa051edde4a20e3152bc5e3636d/engine/src/main/java/io/camunda/zeebe/engine/processing/message/MessagePublishProcessor.java#L193) failed.

**To Reproduce**

Unknown.

**Expected behavior**

Correlate command should be sent without an NPE.

**Log/Stacktrace**

[Full logs](https://drive.google.com/drive/folders/1vSP4GjEkMATh2ZaP84291E_M3-mCcmjp) (internal document)

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: java.lang.NullPointerException
	at io.camunda.zeebe.streamprocessor.DirectProcessingResult.executePostCommitTasks(DirectProcessingResult.java:69) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.ProcessingStateMachine.lambda$executeSideEffects$11(ProcessingStateMachine.java:442) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:36) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.retry.AbortableRetryStrategy.run(AbortableRetryStrategy.java:44) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:99) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:120) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at io.camunda.zeebe.broker.transport.commandapi.CommandResponseWriterImpl.tryWriteResponse(CommandResponseWriterImpl.java:99) ~[zeebe-broker-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.TypedResponseWriterImpl.flush(TypedResponseWriterImpl.java:114) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.engine.processing.message.MessagePublishProcessor.sendCorrelateCommand(MessagePublishProcessor.java:193) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at io.camunda.zeebe.streamprocessor.DirectProcessingResult.executePostCommitTasks(DirectProcessingResult.java:67) ~[zeebe-workflow-engine-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	... 9 more 
```

</p>
</details>

**Environment:**
- `ultrachaos`
- bbbb0d3e8455efa051edde4a20e3152bc5e3636d
- [reported error](https://console.cloud.google.com/errors/detail/CObOnMPDzIuWNA;service=zeebe;time=P7D?project=camunda-cloud-240911)

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

With the engine abstraction topic the response writer is already getting flushed in the `executeSideEffects()` method of the `ProcessingStateMachine`. Flushing a second time here causes NullPointerExceptions.

## Related issues

closes #9860

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by korthout — CHANGES_REQUESTED** [review]
❌ Please add a test case

**Comment by remcowesterhoud** [comment]
I don't know how to test this further than the tests we already have. The existing test cases should already cover this as there is no change in functionality.

**Comment by remcowesterhoud** [comment]
@korthout The NPE that occurred was swallowed and didn't blow up anything. It was an actor that crashed without any impact. Happy to discuss it F2F if it helps.

**Review by korthout — APPROVED** [review]
After discussing F2F, it's clear that the exception is swallowed by the actor. So even if it's reproducible, it's not assertable.

The problem is that any of the side effects could potentially fail (although they shouldn't) and there is no feedback mechanism. Note that we can't roll back the command when we're executing the side effects for it, because some side effects may have already been executed **and** side effects can't be rolled back.

💡 We could verify that no exceptions are thrown in the side effects execution during tests to avoid this situation in the future. @Zelldon is that something we should consider in the engine abstraction topic?

Anyways LGTM 👍

**Comment by remcowesterhoud** [comment]
bors merge

**Pull request merged**
