### PR TITLE
feat(client): Added simple golang client with health check

### LINKED ISSUE #1091: Implement the health/topology request from the go rpc client
#### AT

- Client can execute the health/topology request
- Have concept for running this in the CI
  - Ideas:
     - Parallel test step in Jenkins file to java/jmh
     - Use maven to build distro first (pre-step)
     - start distro as background process `dist/target/zeebe-broker/bin/broker &`
     - run test suite, would be cool if we don't have to restart broker in between but is not blocker

### PR DESCRIPTION
**Pull request by jsam**
I've looked into the topic on vendor folder again and even though we can lock transient dependencies in - we should still commit dependencies into the repository. Reasoning behind this is that Go does not have a central repository (and company behind it) which could give us a guarantee that versioned dependencies would not change (and always be there, accessible) - therefore we have 2 options:

1.  (recommended) Commit the vendor folder into the repository.
2. Backup/fork all dependencies (versions and transients) which we use, and use those in Gopkg.toml file.

This PR, has 3 commits:

- Golang client with testing which will spawn a broker on before starting a testing suite, and stopping the broker after the suite is complete
- Vendor folder with all dependencies which are currently used
- Jenkinsfile editing

There is also a Makefile which we can use to easy integrate test runner into our current CI setup.

closes #1091

### CODE REVIEW

**Comment by menski** [comment]
Sorry the PR was closed because the target branch was deleted during the merge

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c25e2bf927ed074491b77f6da0fedbb53ac77a4f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, ci**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by menski — APPROVED** [review]

**Comment by menski** [comment]
follow up issue to install golang in the CI image #1158

bors r+

**Comment by menski** [comment]
bors retry

**Comment by menski** [comment]
There was already a build failing because of bind exceptions. I now isolated the go build inside an own container. At the moment this means that we have to rebuild the distro before running the go tests. With #1158 I will try to copy the artifacts from the install step to the go container.

bors r+

**Pull request merged**
