### PR TITLE
Update docs to support latest mdbook version

### PR DESCRIPTION
**Pull request by menski**
## Description

- move and update theme to latest mdbook version
- add github url for link in docs
- add commit preprocessor
  - preprocessor requires python3 and git binary
  - if git command fails the preprocessors skips execution to not break book pipeline
  - replaces {{commit}} template with current commit hash of HEAD reference

### CODE REVIEW

**Review by saig0 — CHANGES_REQUESTED** [review]
:+1: 

It seems that some links are broken and some images are not displayed (e.g. http://localhost:3000/bpmn-workflows/service-tasks/service-tasks.html#additional-resources)  :sweat_smile: 

Please update the `docs/README.md`.

What do you think about enabling the collapsing of the navigation? In the `book.toml` : 
```
[output.html.fold]
enable = true
level = 0
```

**Comment by Zelldon** [comment]
> What do you think about enabling the collapsing of the navigation? In the book.toml :

Would love this :heart_eyes:

**Comment by saig0** [comment]
The links point to `README.html` like `[Basics chapter](/basics/README.html)` are broken. Otherwise, it looks good :+1:

**Comment by menski** [comment]
I renamed all `README.md` files to `index.md` and removed the `README.html` suffixes from the links the docs. This breaks the easy browsing of the on GitHub but this was never a recommend way to read the docs so I'm fine with it. We also now have link checks enabled on CI, even for external links and the docs are build during the normal pipeline to immediately find dead links. Per default external link checking is disabled locally as it increases the build duration.

**Review by saig0 — APPROVED** [review]
:tada:

**Pull request merged**
