### PR TITLE
feat(gateway): expose a GRPC health endpoint

### LINKED ISSUE #7635: Support GRPC Health Checking Protocol in Gateway
**Is your feature request related to a problem? Please describe.**
If I have to use a Load balancer(gRPC enabled Application Load Balancers enables gRPC workloads with end to end HTTP/2 support) with Gateway , i am not able to do that because we need a health check URI that supports gRPC status code.
Original discussion - https://forum.camunda.io/t/grpc-health-check-for-gateway/2416

**Describe the solution you'd like**
Gateway GRPC service should support [GRPC Health Checking Protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md)

**Describe alternatives you've considered**
Nginx for load balancing Gateway service.

**Additional context**
Gateway should provide a gRPC endpoint which can be queried for health check

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

I've created a GRPC health endpoint, that based on a gateway status.

## Related issues

closes #7635 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [X] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [X] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by ankit-joinwal** [comment]
Hi @aivinog1 , how soon can we expect this to be merged and available to general public?

**Review by npepinpe — CHANGES_REQUESTED** [review]
:rocket: Thanks @aivinog1!

Some notes:

- :x: Can we extract the whole state management from the `Gateway` class into a service object? Keep the responsibility of the gateway class low. So maybe we can have a new `health` package in the gateway, e.g. `io.camunda.gateway.health`, which has two classes: the `Status` enum, and the `GatewayHealthManager`. The manager can take care of centralizing the health status management (i.e. it's a central point to call `setStatus` and `getStatus` in a thread safe way), and it also manages the instance of the `HealthStatusManager`, only exposing/delegating the call to `BindableService getHealthService()` of the `HealthStatusManager`. Here's a quick sketch:

<details><summary>GatewayHealthManager.java</summary>

```java
@ThreadSafe
public final class GatewayHealthManager {
  private static final Set<String> MONITORED_SERVICES =
      Set.of(GatewayGrpc.SERVICE_NAME, HealthStatusManager.SERVICE_NAME_ALL_SERVICES);

  private final HealthStatusManager statusManager;
  private final AtomicReference<Status> status = new AtomicReference<>();

  public GatewayHealthManager() {
    this(new HealthStatusManager());
  }

  public GatewayHealthManager(final HealthStatusManager statusManager) {
    this.statusManager = statusManager;
    setStatus(Status.INITIAL);
  }

  /**
   * This method returns the latest health status for the gateway, and is thread safe.
   *
   * @return the current health status
   */
  public Status getStatus() {
    return status.get();
  }

  /**
   * This method sets the health status in a thread safe way.
   *
   * @param status the new health status of the gateway
   */
  public void setStatus(final Status status) {
    final var oldStatus = this.status.getAndAccumulate(status, this::computeStatus);

    if (oldStatus != Status.SHUTDOWN && oldStatus != status) {
      updateGrpcHealthStatus(status);
    }
  }

  private Status computeStatus(final Status currentStatus, final Status newStatus) {
    if (currentStatus == Status.SHUTDOWN) {
      return Status.SHUTDOWN;
    }

    return newStatus;
  }

  public BindableService getHealthService() {
    return statusManager.getHealthService();
  }

  private void updateGrpcHealthStatus(final Status status) {
    switch (status) {
      case RUNNING:
        setGrpcHealthStatus(ServingStatus.SERVING);
        break;
      case SHUTDOWN:
        statusManager.enterTerminalState();
        break;
      case INITIAL:
      case STARTING:
      default:
        setGrpcHealthStatus(ServingStatus.NOT_SERVING);
        break;
    }
  }

  private void setGrpcHealthStatus(final ServingStatus servingStatus) {
    MONITORED_SERVICES.forEach(service -> statusManager.setStatus(service, servingStatus));
  }
}
```

</details>

The goal here is to reduce the responsibilities of the `Gateway` class, how much it has to manage, and reduce cognitive load on the developer by putting all the "health" stuff in a separate class, exposing a very small API (`getStatus`, `setStatus`, and `getHealthService` for now).

- :wrench: With the above class, we could more easily add unit tests to also test the other paths. Right now you can't really do that in the acceptance test since the server is running when it's started, so you can't really assert anything else. But you could unit test the other paths with this separate class.

- :wrench: Then there's some small cosmetic changes we could do after this in the `Gateway` class, but we can do that in a follow up to keep the scope small here.

**Comment by npepinpe** [comment]
I pushed an example of the changes here: https://github.com/camunda-cloud/zeebe/tree/aivinog1/7737-grpc-health-check

I didn't test it, so maybe it doesn't even compile :sweat_smile: , but you could diff and see what I referred in my comments to get an idea in case I wasn't clear.

**Review by npepinpe — CHANGES_REQUESTED** [review]
Generally looks good :+1: 

:x: There's one small build issue: there's a used undeclared dependency.

```
[2021-10-18T15:35:39.436Z] [WARNING] Used undeclared dependencies found:
[2021-10-18T15:35:39.436Z] [WARNING]    com.google.code.findbugs:jsr305:jar:3.0.2:compile
```

:thought_balloon: There's also another thing, this health status is now equivalent to the startup probe available with the Spring management server. That's OK, but if people use it with a load balancer, than they might expect it to line up with the readiness probe instead. Anyway, that's a bit out of scope here and this is a good start.

**Review by npepinpe — COMMENTED** [review]
Code looks good, let's wait until the build runs

**Review by npepinpe — APPROVED** [review]
:tada: 

Please rebase into logic commits (i.e. maybe squash your code review commits where it makes sense) and then we can merge

**Pull request merged**
