### PR TITLE
Create unit test for JMH engine performance test

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

This PR contains several smaller pieces which are put together in order to make it possible to run our new engine JMH benchmark within our CI.

### ListLogstorage adjustment

We did a smaller refactoring in order to improve the performance of the log storage on larger state and to reduce the footprint (we enabled resetting the log in between).

### Imporvement of the JMH Benchmark

We refactored the JMH benchmark, to make the test more reliable, reducing actor threads, setting heap settings, reset the log between runs, and add better logging.

### New Junit test

Add new unit test which allows to execute JMH benchmark and verifies expected result, accepts deviation of 10%
performance loss or improvement. This number was chosen based on earlier acceptance criteria discussed with PM, and because tests aren't reliable enough to always produce the exact same result.

Junit test was designed based on https://www.retit.de/continuous-benchmarking-with-jmh-and-junit-2/

Test is only executed if explicitly enabled

### New CI job

We added a new maven profile and CI job which is executed next to our other CI jobs on our self-managed nodes. It will occupied a whole node, in order to reduce the influence of other workloads. 

We used several executions of the CI job to find good and reference values for our unit test.

### CODE REVIEW

**Comment by Zelldon** [comment]
@oleschoenburg I set it to 850 now, 4/5 tests run threw. 

* https://github.com/camunda/zeebe/actions/runs/5282951794
* https://github.com/camunda/zeebe/actions/runs/5282951989
* https://github.com/camunda/zeebe/actions/runs/5282952180
* https://github.com/camunda/zeebe/actions/runs/5282952337
* https://github.com/camunda/zeebe/actions/runs/5282952466/jobs/9558545674 -> failed with JMHEnginePerformanceTest.runJmhBenchmark:37->assertDeviationWithin:56 Expected reference score is '850.00' got '594.10', deviation 30.106% exceeds maximum allowed deviation 10.000%

WTF. I'm thinking about repeating the runs, like three times and if it fails only once then it is fine or something like that :thinking:

**Comment by Zelldon** [comment]
Just for posterity:
We played around with several score points and found several things to improve and to make it more stable, at the end we picked ~450 which worked for several reruns.

**Review by lenaschoenburg — APPROVED** [review]
Thanks @Zelldon 👍

Looks like there are merge conflicts now but hopefully easy to resolve?

**Comment by Zelldon** [comment]
I have set the reference value to 450 (from 455) and increased the deviation since we have seen several failures between 11 and 12 %. I think this is still an ok value to test against and allow. The JMH are not 100% reproducible/deterministic with an exact value, which is why we have this deviation. After using this several reruns were green.

**Comment by Zelldon** [comment]
Bors r+

**Comment by Zelldon** [comment]
Bors r+

**Comment by Zelldon** [comment]
Bors r+

**Pull request merged**
