### PR TITLE
Chained variable lookup

### PR DESCRIPTION
**Pull request by pihme**
## Description

* Allows to chain variable lookups
* applies refactoring to make the code more readable

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Review by korthout — APPROVED** [review]
I'm sorry this had to wait so long before being reviewed, but I finally got around to it.

I have no other comments than this: 👍 Nice work, this is gonna be super useful in future changes!

LGTM 🚀

**Comment by pihme** [comment]
bors merge

**Comment by pihme** [comment]
@korthout Could you babysit the merge if it doesn't go through immediately? (I am off work tomorrow)

**Comment by korthout** [comment]
> Build failed:
> 
> * [Smoke tests on macos-latest](https://github.com/camunda/zeebe/runs/6118831498?check_suite_focus=true)

Failed because `Setup JDK 17` timed out after 20 min. It got stuck at 99% somehow. Not sure if there's anything that we need to do about that. In any case, it's unrelated to this PR. So I'll continue the merge.

bors merge

**Pull request merged**
