### PR TITLE
docs: remove dependencies list creation from Optimize C8

### PR DESCRIPTION
**Pull request by misiekhardcore**
## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

related to https://github.com/camunda/camunda-optimize/issues/14139

### CODE REVIEW

**Review by RomanJRW — APPROVED** [review]

**Comment by RomanJRW** [comment]
approve, but lots of failed CI - presumably unrelated

**Comment by misiekhardcore** [comment]
@RomanJRW I am not sure if some of those failing tests aren't a real thing, they are complaining about some missing ES dependency

**Comment by RomanJRW** [comment]
@misiekhardcore - not sure why it reports like this, but can you first try to delete this from the `util` pom which is the parent of the one you deleted:

```
<modules>
        <module>dependency-doc-creation</module> <--- DELETE THIS LINE
        <module>optimize-commons</module>
    </modules>
```

**Comment by RomanJRW** [comment]
FYI @buccarel

**Pull request merged**
