### PR TITLE
Upgrade Zeebe Test Container to 1.0.0

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR backports the upgrade of Zeebe Test Container to 1.0.0 for 0.24. There is no backport for 0.23 as that version will soon be phased out, and the back port is not a simple cherry pick.

I had to make some adjustments when cherry picking, so please review again - I also fixed some flakiness which I ran into (see https://github.com/zeebe-io/zeebe/issues/4632), for which I'll open another PR for develop.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by korthout — APPROVED** [review]
LGTM 🎉

**Comment by korthout** [comment]
Please remember to update the release doc

**Comment by npepinpe** [comment]
Do you think this should go in the release announcement? It's purely internal after all

**Comment by korthout** [comment]
Yeah sorry, I wrote it and immediately thought: Oops! 

Please ignore it .

**Comment by npepinpe** [comment]
I'll back port the correct flaky fix from the other PR :)

**Review by korthout — APPROVED** [review]
LGTM! 🎉

**Comment by npepinpe** [comment]
Why is SonarCloud complaining about stuff that I didn't change, and comparing it with develop when I'm building against stable/0.24? :thinking:

**Pull request merged**
