### PR TITLE
Add versioning to Event Appliers

### PR DESCRIPTION
**Pull request by remcowesterhoud**
## Description

This PR introduces versioning in our Event Appliers. This is required for generalised distribution. The problem here is that the `Deployment.CREATED` applier writes a deployment record to the state. This used to be deleted by the `Deployment.FULLY_DISTRIBUTED` event.
With generalised distribution we still write the `Deployment.CREATED` events, however we no longer have the `Deployment.FULLY_DISTRIBUTED` event. This means the state would never get cleared again.

To circumvent this we need to have a way to determine whether or not we want to write to the state or not. This can be done by versioning our event appliers. It works by registering an applier with a specific version. When applying an event we will always use the latest version that doesn't exceed the version the broker had at the time of writing the event.

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@saig0 Would you mind reviewing this one? It's quite a structural change so I'd like your opinion on this. I've more or less paired on it together with @korthout so it's good to have another set of eyes go over this.

**Comment by remcowesterhoud** [comment]
There is an alternative to this approach which doesn't rely on the Broker version. We could introduce a version on the record itself. When writing the record we can use the latest version of the record. During replay we will also have this version available. With it we can decide which applier we'll have to use.

**Comment by remcowesterhoud** [comment]
Also, please don't merge this yet :)

**Comment by remcowesterhoud** [comment]
Thanks! There is no rush since I've shifted my focus to a different topic

**Review by saig0 — COMMENTED** [review]
@remcowesterhoud looks good so far. :+1: 

I just have a few minor comments. But nothing major.

**Pull request closed without merging**
