### PR TITLE
Make resource deletion tenant-aware

### LINKED ISSUE #14279: Support multi-tenancy for Resource Deletion
### Description

Resource deletion is tenant-aware.

```[tasklist]
### AC
- [x] The `ResourceDeletionProcessor` is able to lookup resources using authorized tenant IDs.
- [x] Unit tests are added for tenant-aware resource deletion.
- [x] QA tests are added for tenant-aware resource deletion.
- [x] Re-enable the tests in the engine's `TenantAwareTimerStartEventTest`
- [ ] https://github.com/camunda/camunda-docs/issues/2845
```

### Additional context

* Please see [comment](https://github.com/camunda/zeebe/issues/13279#issuecomment-1721349923) on `ElementInstanceState` before implementing.
* We must also re-enable the tests in the `TenantAwareTimerStartEventTest`

### PR DESCRIPTION
**Pull request by koevskinikola**
## Description

Ensure that resources are only deleted for authorized tenants.

## Related issues

closes #14279 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [x] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [x] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by koevskinikola** [comment]
:information_source: Note that to delete a resource, a `tenantId` must be provided as the data in the states is structured in a way that a `tenantId` must be used for look-ups. 

With https://github.com/camunda/zeebe/pull/14928/commits/a3993d56f24553837e0a0e86ece962e56793fc16 I'm using the user's `authorized tenants` to determine if the user is assigned to a tenant authorized to delete a resource with the provided `resourceKey`.  This is done to improve the UX and avoid requiring the user/gRPC client to provide the `tenantId` of the resource they want to delete.

Note as well that I'm not passing the `authorized tenants` to the appropriate states (Process, Decision, Form), and instead implement all the logic inside the `ResourceDeletionProcessor`. The reason is that we want to keep this behavior specific to Resource Deletion, and not expose it widely through the "resource" states (Process, Decision, Form) since we would be exposing a lot of (tenant inference) "magic" this way.

**Comment by koevskinikola** [comment]
@remcowesterhoud have a look at [this comment](https://github.com/camunda/zeebe/pull/14928#issuecomment-1790261268) before starting the review. I'm curious what you think about points 3. and 4.

**Comment by remcowesterhoud** [comment]
I didn't do a full review yet, but here the response to your comment:

> Commit https://github.com/camunda/zeebe/commit/4817b909eb66e0057f66e03f715c2761db847f37 sets the ResourceDeletionRecord#tenantId property after the resource is found. This is done so that the follow-up events contain the tenant-ownership information. This way, the ResourceDeletionRecord exported events are consistent with the rest of the TenantOwned records.

I would question the need of the `ResourceDeletionRecord` to be `TenantOwned`. It has a `tenantId` property on it now, but it's never used. As long as we can access the authorised tenants that's all the information we'll need here. Now we have a difference in our followup events to be consistent with other records, because of an interface we don't use.

 
> Commit https://github.com/camunda/zeebe/commit/f0edf4cf1d1749175e2d3826c52bd8c97645d73b optimizes the resource look-up after the command is distributed. Since we already found the resource before the command was distributed, we don't need to use the authorized tenants to look-up the resource across tenants again. We can instead read the tenantId from the command record, which we already set.

I suppose this optimisation is the reason for making the record `TenantOwned` as it's the only place we use the tenant property. 

It's a difficult question. I like the optimisation, but I wonder if it validates making a non-tenant related record `TenantOwned`. Especially as this also causes the tenant to behave different from all other records. For all records the default is `<default>` for this record it's an empty string. I could see this causing confusion later on.

**Review by remcowesterhoud — APPROVED** [review]
@koevskinikola Have a look at the comment I left. I'll leave the decision of what you want to do with it up to you.

Overall the PR looks good and should work fine 👍

**Comment by koevskinikola** [comment]
> I would question the need of the `ResourceDeletionRecord` to be `TenantOwned`.

Semantically it makes sense, resources are owned by tenants, and `DeploymentRecord`s are `TenantOwned` as well. It makes sense logically for deletion-related records to be the same, although the `tenantId` here is not required.


> I suppose this optimisation is the reason for making the record TenantOwned as it's the only place we use the tenant property.

@remcowesterhoud not really. The `ResourceDeletionRecord` was already `TenantOwned` and the `tenantId` property was already added in the ES and OS index templates in `8.3`. AFAIK we can't revert this change now, as it will be a breaking one. So I decided since we already have the `tenantId` property, we can already use it.

**Comment by koevskinikola** [comment]
As the `ResourceDeletionRecord` was already `TenantOwned` and the `tenantId` property was already added in the ES and OS index templates in `8.3`, it would be risky to remove these changes and create a breaking change for users. So I'm merging this PR as it is.

bors merge

**Pull request merged**
