### PR TITLE
docs(clients): add section on other clients

### PR DESCRIPTION
**Pull request by jwulf**
## Description

Added section with community-supported client libs.

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
I like it :+1: 

What do you think about moving also the Java and Go sections into one section for all clients?

For example:
```
7. Clients 
    Officially supported clients: Java, Go
    Community driven clients: C#, JavaScript, ...

7.1. Java Client
7.2. Go Client
7.3. C# Client
7.4. ...
```

**Comment by jwulf** [comment]
> What do you think about moving also the Java and Go sections into one section for all clients?

Great idea!

**Comment by saig0** [comment]
Looks good :+1: But now, we have some **broker links**. Please have a look at the link checker's output.

**Comment by saig0** [comment]
Thanks :+1:

**Pull request merged**
