### PR TITLE
Include bpmnProcessId as part of exported variable records

### LINKED ISSUE #8181: Include bpmnProcessId as part of exported variable records
**Is your feature request related to a problem? Please describe.**
When importing variable records and converting them to Optimize variables, we have to fetch the definition from ES to extract the `bpmnProcessId` in order to route it to the correct Optimize index. This can be expensive, and results in retries if the process hasn't been been exported by zeebe/imported by Optimize. Furthermore, if the process has been exported but the record is no longer available (cleaned up), then the import gets stuck, as seen in a recent support issue.

**Describe the solution you'd like**
If the `bpmnProcessId` (like how it is included on the incident records for example) was included as part of the exported variable record, we could improve the performance of import by removing the fetch, and also guard against the possibility of the import getting stuck. If we have the key, Optimize is resilient enough to continue the import even if that process never can be imported.

**Describe alternatives you've considered**
The current implementation sort of is our alternative, but it is not ideal. The performance hit is somewhat acceptable, but the import blocking issue is more awkward for us to work around. With some refactoring, skipping this data import after x retries could potentially avoid the skip but also exposes the risk of missing data that the user would expect in Optimize

**Additional context**
Raised as a result of investigation from https://jira.camunda.com/browse/SUPPORT-12111

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR adds a new `bpmnProcessId` property to all `VariableRecordValue` instances. This property is set during processing before the record is written in all cases. However, it is not stored in the state, but only persisted in the log, much like the `VariableRecordValue#getProcessInstanceKey` property.

Doing this allows consumers of the exported record stream to index variables over a process' ID. This use case  is mostly for users who want to aggregate variables over a specific process without having to care about its version (and thus the unique keys for each process/version pair). See the linked issue for more.

NOTE: a small thing jumped out, which is that variables now have a few properties which are really only used for the consumers of the exported stream. I don't expect we add more of these, but if we do, at some point we might want to revise our approach instead of just tacking on the property over each record.

NOTE: the `bpmnProcessId` has an empty string as default value. While we should ensure it's always set in newer versions, I assumed for backwards compatibility this is necessary. Let me know if that's not the case, maybe I forgot how the message pack decoding works.

## Related issues

closes #8181 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

### CODE REVIEW

**Review by remcowesterhoud — APPROVED** [review]
> NOTE: the bpmnProcessId has an empty string as default value. While we should ensure it's always set in newer versions, I assumed for backwards compatibility this is necessary. Let me know if that's not the case, maybe I forgot how the message pack decoding works.

I don't know either 😅 Having this can't hurt. LGTM 🚀

**Comment by npepinpe** [comment]
I took the opportunity to update the test I modified to use Junit 5, as we want to eventually migrate all our tests to Junit 5, and it was simple enough to do so here.

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors r+

Again the broken cache thing...

**Pull request merged**
