### PR TITLE
[Backport 1.3] Trigger boundary events only if the flow scope is active

### PR DESCRIPTION
**Pull request by saig0**
## Description

Backport of #9281

Only one additional change compared to the origin PR for downgrading the test code to Java 11.

## Related issues

relates to #9233

### CODE REVIEW

**Comment by saig0** [comment]
bors merge

**Review by korthout — APPROVED** [review]
LGTM ☕

**Comment by saig0** [comment]
bors merge

**Comment by saig0** [comment]
bors merge

**Comment by saig0** [comment]
bors merge

**Comment by saig0** [comment]
bors merge

**Comment by saig0** [comment]
bors merge

**Pull request merged**
