### PR TITLE
Nightly build with QA Run

### PR DESCRIPTION
**Pull request by pihme**
## Description

Fixes the conditions to run QA stage during nightly builds

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [X] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: eabc5a6934b5ed241cb3e46528abf2dbbc33d7fe
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3feb153463bce9a0c9ac9bf6eb6f2ad0631df72a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 45e508005eeabd6999b38d88556403dcfbb71300
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 024f5d456d79275aaf28ca1751c83c005cb6c5b8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c81f1ad94d00a4ed6f60483b0673f000e154a1af
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by pihme** [comment]
Commit history is pretty messy. I will clean it up after review. Some of the commits were in order to be able to test it.

See here for one build which did work: https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/pihme-nightly-build/9/pipeline

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: eabc5a6934b5ed241cb3e46528abf2dbbc33d7fe
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3feb153463bce9a0c9ac9bf6eb6f2ad0631df72a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 45e508005eeabd6999b38d88556403dcfbb71300
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 024f5d456d79275aaf28ca1751c83c005cb6c5b8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c81f1ad94d00a4ed6f60483b0673f000e154a1af
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a90a3368046b022d1af4347dc947104df518d316
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 6b71fb520bacd4c155fef2d00bf898aee0b527c9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by npepinpe — APPROVED** [review]
Looks good :+1: 

I guess we now run all commits on develop on stable, which is probably fine, if a little more expensive.

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
@npepinpe With these changes the build always seems to be stuck in the post phase. Any idea why this could happen?

https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/zeebe-io%2Fzeebe/detail/pihme-nightly-build/14/pipeline

**Comment by pihme** [comment]
bors retry

**Comment by pihme** [comment]
bors retry

**Pull request merged**
