### PR TITLE
Align deployment rejection message for DMN resources

### LINKED ISSUE #8806: Align deployment rejection message for DMN resources
**Describe the bug**

If I deploy an invalid DMN resource then the deployment is rejected. The rejection message may look like the following example:

```
/bin/zbctl deploy ~/IdeaProjects/zeebe/engine/src/test/resources/processes/invalid_process.bpmn ~/IdeaProjects/zeebe/dmn/src/test/resources/decision-table-with-invalid-expression.dmn
Error: rpc error: code = InvalidArgument desc = Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'/home/philipp/IdeaProjects/zeebe/engine/src/test/resources/processes/invalid_process.bpmn': - Element: process
    - ERROR: Must have at least one start event

FEEL unary-tests: failed to parse expression '"blue': Expected (negation | positiveUnaryTests | anyInput):1:1, found "\"blue"
```

The rejection message for BPMN and DMN looks different. The rejection contains the failure message of the DMN but it is missing the related deployment resource. Without the resource, it could be hard to identify the failure.

**To Reproduce**

Deploy the following resources from the Zeebe repo.

```
/bin/zbctl deploy ~/IdeaProjects/zeebe/engine/src/test/resources/processes/invalid_process.bpmn ~/IdeaProjects/zeebe/dmn/src/test/resources/decision-table-with-invalid-expression.dmn
```

**Expected behavior**

The rejection message for DMN resources contains the name of the resource. Similar to the message for BPMN resources.

```
Error: rpc error: code = InvalidArgument desc = Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
'/home/philipp/IdeaProjects/zeebe/engine/src/test/resources/processes/invalid_process.bpmn': - Element: process
    - ERROR: Must have at least one start event

'~/IdeaProjects/zeebe/dmn/src/test/resources/decision-table-with-invalid-expression.dmn': FEEL unary-tests: failed to parse expression '"blue': Expected (negation | positiveUnaryTests | anyInput):1:1, found "\"blue"
```

**Log/Stacktrace**

None.

**Environment:**
- OS: 
- Zeebe Version: `1.4.0-alpha1`
- Configuration:

### PR DESCRIPTION
**Pull request by berkaycanbc**
## Description

Included the resource name in the rejection message of DMN validation error. Also, updated the related test to verify the expected behaviour.

## Related issues

closes #8806

### CODE REVIEW

**Review by megglos — APPROVED** [review]
I love quick fixes and I cannot lie! [Commitlint isn't happy with the scope](https://github.com/camunda/zeebe/actions/runs/8691401069/job/23833590815?pr=17475), pre-approving so you can merge after resolving it.

**Comment by megglos** [comment]
@berkaycanbc I consider the scope of this change to be fine to get backported till 8.4 as this would help the web modeler team https://github.com/camunda/zeebe/issues/8806#issuecomment-2060522606

**Comment by berkaycanbc** [comment]
@megglos the Tasklist CI test summary looks stuck in progress. Is it a known issue or is there a way to skip it?

**Comment by megglos** [comment]
@berkaycanbc right now we are lbocked by an operate issue, see https://camunda.slack.com/archives/C06HTSPD5AP/p1713341499813309

fix is incoming https://github.com/camunda/zeebe/pull/17539

**Comment by megglos** [comment]
@berkaycanbc can you please rebase once https://github.com/camunda/zeebe/pull/17539 is merged ?

**Comment by berkaycanbc** [comment]
> @berkaycanbc right now we are lbocked by an operate issue, see https://camunda.slack.com/archives/C06HTSPD5AP/p1713341499813309
> 
> fix is incoming #17539


@megglos okay, thanks.

> @berkaycanbc can you please rebase once #17539 is merged ?

Yes!

**Pull request merged**
