### PR TITLE
docs(/docs): fixed hyperlink linking to markdown guide

### PR DESCRIPTION
**Pull request by haardikdharma10**
## Description

When going through the README.md of docs folder, I came across this hyperlink which links to a 404 page. The problem was in the URL and I've made the necessary change. A minor issue but it needed to be fixed:)

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
Thanks @haardikdharma10 for your contribution!

**Comment by haardikdharma10** [comment]
@Zelldon, I wonder what's the problem with this PR? 🤔

**Comment by Zelldon** [comment]
We have currently some pipeline issues. I will merge this manually for now.

**Pull request merged**
