### PR TITLE
Adjust default config and delay log compaction to prevent too frequent snapshot replication

### PR DESCRIPTION
**Pull request by lenaschoenburg**

### CODE REVIEW

**Comment by korthout** [comment]
@oleschoenburg This benchmark has [reported an error](https://console.cloud.google.com/errors/detail/CJu5_-Xi2tPIzwE;service=zeebe;time=P7D?project=zeebe-io)

**Comment by Zelldon** [comment]
@oleschoenburg can I remove the benchmark? Or is it expected to run over the next weeks?

**Comment by oleschoenburg** [comment]
Sorry, forgot about that. Both running benchmarks can be stopped @Zelldon 🙏

**Comment by Zelldon** [comment]
Hey no worries @oleschoenburg ! I just found `pr-11234-benchmark`

**Pull request closed without merging**
