### PR TITLE
Subscribe processes with top-level signal start events to signals

### LINKED ISSUE #11195: Subscribe processes with top-level signal start events to signals
When a new process with top-level signal start events is deployed, we need to subscribe that process to signals. 

The engine can create subscriptions for signals using a new `SignalSubscription` record. This `SignalSubscription` must be `CREATED` when the process is deployed. If that process is a new version of an already existing process, this `SignalSubscription` must be `DELETED` for that older version of the process.

We will only subscribe to top-level signal start events in the Deployment Partition (i.e. `partitionId: 1`). It may be possible to also subscribe on other partitions, but that is a stretch-goal as we are not yet sure whether this has further complications.

Previously existing processes should not be able to contain top-level signal start events. There is no need to process already deployed processes additionally.

- [x] Introduce new `SignalSubscription` records, with intents: `CREATED`, `DELETED`
	- Only used to subscribe to signals, not used to track signal receiving
	- The signal subscription record value should consist of:
		- `bpmnProcessId` - The id of the process in the bpmn model
		- `processDefinitionKey` - The key of the deployed process
		- `catchEventId` - The id of the signal catch event
		- `catchEventInstanceKey` - The key of the signal catch event instance (optional)
		- `signalName` - The name of the signal (taken from the name of the signal in the BPMN model)
	- Like any other records, these should be exported. Please follow our [developer handbook entry on adding new records](https://github.com/camunda/zeebe/blob/main/docs/developer_handbook.md#how-to-create-a-new-record)
- [x] Adjust the `DeploymentCreateProcessor` to subscribe to new top-level signal start events
	- If the deployed process contains a top-level signal start event:
		- Write `SignalSubscription:CREATED`
			- Event applier for `SignalSubscription:CREATED` puts subscription in `DbSignalSubscriptionState`
			- `DbSignalSubscriptionState` should have methods:
				- `visitBySignalName` (should provide parameter that informs whether this is a top-level start event or not)
				- `visitStartEventSubscriptionsByProcessDefinitionKey` (only visits the subscriptions for top-level start events)
				- `visitByElementInstanceKey` (only visits the subscriptions for catch events existing in process instances; won't be used in this stage yet)
- [x] Don't allow top-level signal start events to act as none start event
	- Change `ExecutableCatchEvent.isNone()` implementation
		- Requires adjustment of `CatchEventTransformer` to transform signal catch events

### LINKED ISSUE #11197: Unsubscribe older versions of processes from signals when a new version is deployed
Once we can subscribe processes to top-level signal start events, we also need to unsubscribe them again when they are replaced by newer versions.

- [ ] Adjust the `DeploymentCreateProcessor` to unsubscribe for signals of the previous version of the deployed process
	- uses `DbSignalSubscriptionState.visitStartEventSubscriptionsByProcessDefinitionKey ` to find these subscriptions (only the ones for top-level start events should be used)
	- Write `SignalSubscription:DELETED`
		- Event applier for `SignalStartEventSubscription:DELETED` removes the subscription from DbSignalSubscriptionState

Blocked by
- #11195

### LINKED ISSUE #11209: Create signal subscription record when deployed a process with top-level signal start events
## Description

 If the deployed process contains a top-level signal start event:
 * Write `SignalSubscription:CREATED`
   
   * Event applier for `SignalSubscription:CREATED` puts subscription in `DbSignalSubscriptionState`
   * `DbSignalSubscriptionState` should have methods:
     
     * `visitBySignalName` (should provide parameter that informs whether this is a top-level start event or not)
     * `visitStartEventSubscriptionsByProcessDefinitionKey` (only visits the subscriptions for top-level start events)
     * `visitByElementInstanceKey` (only visits the subscriptions for catch events existing in process instances; won't be used in this stage yet)
     
**Stretch Goal**

Support Signal name as an expression.

By default, the signal name is a static value. This adds value to most users. Expression support for the signal name can be added later. As in other places, this would simply require the value to be prefixed with the expression marker =. See stage 4.

**Blocked by:**
https://github.com/camunda/zeebe/issues/11202
https://github.com/camunda/zeebe/pull/11224

**Part of:**
[Subscribe processes with top-level signal start events to signals #11195](https://github.com/camunda/zeebe/issues/11195)

### PR DESCRIPTION
**Pull request by skayliu**
## Description

 If the deployed process contains a top-level signal start event:
 * Write `SignalSubscription:CREATED`
   
   * Event applier for `SignalSubscription:CREATED` puts subscription in `DbSignalSubscriptionState`
   * `DbSignalSubscriptionState` should have methods:
     
     * `visitBySignalName` (should provide parameter that informs whether this is a top-level start event or not)
     * `visitStartEventSubscriptionsByProcessDefinitionKey` (only visits the subscriptions for top-level start events)
     * `visitByElementInstanceKey` (only visits the subscriptions for catch events existing in process instances; won't be used in this stage yet)  (**will be added in next PR**)
     
Change `ExecutableCatchEvent.isNone()` implementation
   * Requires adjustment of `CatchEventTransformer` to transform signal catch events
    
**Stretch Goal**

Support signal name as an expression.

By default, the signal name is a static value. This adds value to most users. Expression support for the signal name can be added later. As in other places, this would simply require the value to be prefixed with the expression marker =. See stage 4.

## Related issues

closes #11209 
closes #11195 
closes #11197 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by skayliu** [comment]
Hi, @korthout ,please take your time to check this out. thank you.

**Comment by korthout** [comment]
Thanks for another significant contribution, @skayliu 🚀 

I will have a look at this in the upcoming days.

**Review by korthout — COMMENTED** [review]
👏 Amazing contribution @skayliu 

👍 I love that it already allows signal names as expressions

💭 I noticed a few things that we should keep in mind in the future, but they don't have to be worked on right now.

🔧 I've made a few tiny suggestions. Please have a look at these before we merge the pull request.

💭 Lastly, thanks for splitting up the pull request into multiple commits. 79c13c0a806eb3bf74a7b02137262de6386255c5 contains some considerations, but still this was a massive commit to review in one go. If you want to make the review easier, please attempt to split such large commits into smaller/easier-to-review pieces. This would also allow providing more details about why you made certain implementation choices. For example that many of the choices are made to mirror exactly how messages work.

**Comment by skayliu** [comment]
Hi, @korthout, I've applied the reiview hints and splited commits into smaller pieces, hope it will be easier to review, Thank you. :heart:

**Review by korthout — APPROVED** [review]
This is amazing! Well done @skayliu 👏 

Splitting up the commits like this makes it much easier to review 🙇 Thanks!

👍 LGTM

bors merge

**Comment by lzgabel** [comment]
Hi @korthout. @skayliu. 

❓ Why do we need to support signal names as expressions for signal start events? Can you provide a few usage scenarios? As far as I'm concerned, it doesn't make much sense. 🤔 

---

image


If I set the signal name as an expression, I have to provide the corresponding variable for evaluation during deploy mode, is this expected? Or will we support the feature of providing context variables when deploying the model?

**Comment by korthout** [comment]
👍 That's a great question @lzgabel 

Short answer, there are not many/good use cases at this time.

It is correct that, at deployment time, no variables context exists to evaluate the expression. So, users can't use variables when defining the top-level signal start event's signal name expression. But, like top-level **message** start events, this name can be defined as an expression.

There aren't many use cases for this, but it allows a more dynamic definition of the name by using FEEL. Perhaps there are easier ways to express something without variables in FEEL than writing the resulting string (`= "ABC" + "DEF"`), but I do not have a good example.

For now, the real use cases are very limited, but with the introduction of [expression contexts](https://github.com/camunda/zeebe/issues/11459), FEEL expressions become more powerful, and we may find good usages for them.

**Comment by skayliu** [comment]
@lzgabel @korthout 
i.e. we set the top-level signal name  as `=  "signal_" + string(now())`, if we change the bpmn and deploy it again, we can find the differents. it's kind of version thing.

before:
```
{
    "partitionId":1,
    "value":{
        "bpmnProcessId":"Process_0k1nnh5",
        "processDefinitionKey":2251799813685474,
        "signalName":"signal_2023-03-09T21:59:33.384@Asia/Shanghai",
        "catchEventId":"StartEvent_1",
        "catchEventInstanceKey":-1
    },
    "key":2251799813685480,
    "timestamp":1678370410088,
    "recordType":"EVENT",
    "valueType":"SIGNAL_SUBSCRIPTION",
    "brokerVersion":"8.2.0",
    "sourceRecordPosition":611,
    "intent":"CREATED",
    "rejectionType":"NULL_VAL",
    "rejectionReason":"",
    "position":614
}
```

after:
```
{
    "partitionId":1,
    "value":{
        "bpmnProcessId":"Process_0k1nnh5",
        "processDefinitionKey":2251799813685481,
        "signalName":"signal_2023-03-09T22:00:58.863@Asia/Shanghai",
        "catchEventId":"StartEvent_1",
        "catchEventInstanceKey":-1
    },
    "key":2251799813685483,
    "timestamp":1678370458863,
    "recordType":"EVENT",
    "valueType":"SIGNAL_SUBSCRIPTION",
    "brokerVersion":"8.2.0",
    "sourceRecordPosition":615,
    "intent":"CREATED",
    "rejectionType":"NULL_VAL",
    "rejectionReason":"",
    "position":620
}
```

**Comment by lzgabel** [comment]
> i.e. we set the top-level signal name as =  "signal_" + string(now()), if we change the bpmn and deploy it again, we can find the differents. it's kind of version thing.

Personally, I don't think this scene makes much sense.

**Comment by skayliu** [comment]
> > i.e. we set the top-level signal name as =  "signal_" + string(now()), if we change the bpmn and deploy it again, we can find the differents. it's kind of version thing.
> 
> Personally, I don't think this scene makes much sense.

You may think it's another signal name now,  v1 & v2 could be both running.

**Comment by lzgabel** [comment]
> > > i.e. we set the top-level signal name as =  "signal_" + string(now()), if we change the bpmn and deploy it again, we can find the differents. it's kind of version thing.
> > 
> > 
> > Personally, I don't think this scene makes much sense.
> 
> You may think it's another signal name now, v1 & v2 could be both running.

❓ Do you mean that if the `signalName` of signal start events with same `processId` is different, there will be scenarios where v1 and v2 run at the same time?

🤔  If I remember correctly, the old version of the `signal-subscription` is canceled if the `processId` is the same.

**Comment by skayliu** [comment]
Yes, my bad, the v1 is `deleted`

```
{
    "partitionId":1,
    "value":{
        "bpmnProcessId":"Process_0k1nnh5",
        "processDefinitionKey":2251799813685474,
        "signalName":"signal_2023-03-09T21:59:33.384@Asia/Shanghai",
        "catchEventId":"StartEvent_1",
        "catchEventInstanceKey":-1
    },
    "key":2251799813685480,
    "timestamp":1678370458863,
    "recordType":"EVENT",
    "valueType":"SIGNAL_SUBSCRIPTION",
    "brokerVersion":"8.2.0",
    "sourceRecordPosition":615,
    "intent":"DELETED",
    "rejectionType":"NULL_VAL",
    "rejectionReason":"",
    "position":619
}
```

**Comment by skayliu** [comment]
Another i.e. in web modeler , there is a organization `A` with code `org001`, At first we set the top-level signal name as `=  "org" + orgcode()`, the `orgcode()` can get current login user's org code,  one day with the Organization Adjustment  the organization  `A`'s code need to changed to `org002` without change or add new BPMN file,  just make a lillte adjustment and republish the bpmn file, we can shift the signal name to 'org002'

**Comment by korthout** [comment]
> i.e. we set the top-level signal name as =  "signal_" + string(now()), if we change the bpmn and deploy it again, we can find the differents. it could be kind of version or tenant thing.

This is a possibility, but you already discovered this is limited to the last deployed version only (unless the BPMN Process ID is also changed). It's very questionable whether this is a useful case. IMO, it's too complicated to be used well.

The best use case is likely focussed on static signal names built from FEEL expressions: `= "my_string" + "my_other_string"`. Dynamic results would always suffer from process versioning.

Just to note, this functionality also exists for Message Start Event, and it suffers from the same use case problem. IMO, we can move forward with the same functionality simply for consistency. If we decide to remove this functionality at some point, then we can do so for both Message Start Events and Signal Start Events at the same time. We can check with users/customers before dropping such functionality.

**Pull request merged**
