### PR TITLE
[Backport stable/8.4] fix: opensearch exporter - update ISM policy for existing indices when retention config changes on rerun

### PR DESCRIPTION
**Pull request by mustafadagher**
# Description
Backport of #17187 to `stable/8.4`.

relates to #17186

### CODE REVIEW

**Review by megglos — APPROVED** [review]
Approving, assuming no real changes besides class path movement?

**Comment by megglos** [comment]
@mustafadagher we could add backport labels for the others here?

**Comment by mustafadagher** [comment]
> @mustafadagher we could add backport labels for the others here?

based on experience with the previous ones, I don't think it will help. I will have to do them manually anyways!

**Comment by megglos** [comment]
Follow-up @mustafadagher found retention support for opensearch was only present in 8.4  https://github.com/camunda/zeebe/issues/13203 no further backporting needed 😌

**Pull request merged**
