### PR TITLE
feat: directly write to log storage without appender actor

### LINKED ISSUE #17548: Let the `Sequencer` write directly to the raft thread
Essentially we inline the `LogStorageAppenderImpl` into the `Sequencer`. This simplifies the `Sequencer` because it doesn't have to keep a queue and consumers, and completely removes the `LogStorageAppenderImpl`.

The `LogStorageAppenderMetrics` will remain as is. Some `Sequencer` metrics will be removed as they are no longer relevant.

This change should not result in different runtime behavior.

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Removes the `LogStorageAppender`. This actor was responsible for reading from the `Sequencer` queue, getting a permit from `AppenderFlowControl` and then writing to the log storage.

Instead we now have the Sequencer doing both of these things directly. This removes complexity and a potential source of latency.

## Related issues

closes #17548

### CODE REVIEW

**Comment by npepinpe** [comment]
If I read this correctly, this removes the sequencer limit? I mean, we have the rate limiters which do this, but this is an elastic limit right? So there is no more hard limit (unless you configure one)? 

I think the configuration for that is currently totally undocumented, so it would be good to make it "proper" configuration if we go this way.

But generally a good idea :+1:

**Comment by deepthidevaki** [comment]
Would this solve https://github.com/camunda/zeebe/issues/14003? :eyes:

**Comment by npepinpe** [comment]
I assume you can still run into the limit :sweat_smile: We still need some form of limit to not overwhelm the Raft thread

**Comment by oleschoenburg** [comment]
> If I read this correctly, this removes the sequencer limit? I mean, we have the rate limiters which do this, but this is an elastic limit right? So there is no more hard limit (unless you configure one)?

That's right, yeah. In my mind the sequencer limit had not much use though, it was just to prevent unbounded growth of the queue in case the log storage appender is not able to keep up. 

Improving the observability of the AppenderFlowContro and making it easier to configure is something in scope of https://github.com/camunda/zeebe/issues/17547 :+1:

**Comment by oleschoenburg** [comment]
I've added some more visibility here: https://github.com/camunda/zeebe/pull/17604

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
LGTM! Thanks for the changes 🚀

**Pull request merged**
