### PR TITLE
ci: strip first letters from paths

### LINKED ISSUE #9437: GHA: Artifact export on job failure fails due to module directory name usage
**Describe the bug**

It seems due to going back to module paths with #9368  we introduce a new failure on exporting the artifacts

```
Run actions/upload-artifact@v3
  with:
    name: Unit test results for ./atomix/cluster
    path: **/target/surefire-reports/
  **/hs_err_*.log
  
    retention-days: 7
    if-no-files-found: warn
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.[3](https://github.com/camunda/zeebe/runs/6527368042?check_suite_focus=true#step:6:3)-7/x6[4](https://github.com/camunda/zeebe/runs/6527368042?check_suite_focus=true#step:6:4)
With the provided path, there will be [9](https://github.com/camunda/zeebe/runs/6527368042?check_suite_focus=true#step:6:9)3 files uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Error: Artifact name is not valid: Unit test results for ./atomix/cluster. Contains the following character:  Forward slash /
          
Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /
          
These characters are not allowed in the artifact name due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.
```
See https://github.com/camunda/zeebe/runs/6527368042?check_suite_focus=true

**To Reproduce**

Lets a job fail.

**Expected behavior**

No issues on exporting artifacts.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Removes the `./` from the paths, to avoid failing on archive the artifacts as shown here https://github.com/camunda/zeebe/issues/9437

@oleschoenburg I'm wondering whether `atomix/cluster` might be still an issue here? :thinking: 

## Related issues

closes #9437 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Perfect, thanks @Zelldon :+1:

**Comment by oleschoenburg** [comment]
> I'm wondering whether atomix/cluster might be still an issue here?

In what sense? It's one of the projects where we want to run tests, right?

**Comment by Zelldon** [comment]
@oleschoenburg what I mean is that it contains `/` in the name

**Comment by oleschoenburg** [comment]
@Zelldon Oh, right :facepalm: Looks like there's no good function to replace a `/`: https://docs.github.com/en/actions/learn-github-actions/expressions#functions

**Review by lenaschoenburg — APPROVED** [review]
Let's go with this :+1: 

bors r+

**Pull request merged**
