### PR TITLE
chore(exporter-api): adds test utilities for exporter authors

### LINKED ISSUE #1789: Add test utilities for exporters
Goal is to provide test utilities to facilitate the development of exporters.

1. Provide mock implementations of `io.zeebe.exporter.context.*` interfaces which are controllable/inspectable.
1. Provide an easy to generate records for testing.

### PR DESCRIPTION
**Pull request by npepinpe**
closes #1789

### CODE REVIEW

**Comment by npepinpe** [comment]
One thing I was wondering is if it might not make more sense to put all these utilities into `zb-test-util` (or `zb-test`? not sure what is supposed to be the difference).

**Review by menski — CHANGES_REQUESTED** [review]
lgtm but I would prefer that we use these classes somewhere in our code base before merging. Otherwise it could happen that we forget about them similar to the zeebe-test module. Would it be possible to use them in the elasticsearch exporter?

> zb-test-util (or zb-test? not sure what is supposed to be the difference)

`zb-test-util` are utils we use to write tests in the Zeebe project itself. Whereas `zeebe-test` are test utils provided for external extension developers. As you aim for external developers I think it would fit into the `zeebe-test` module.

**Comment by npepinpe** [comment]
I would put it in `zb-test` then, and add some `ElasticSearchExporter` tests using them. Adding everything to the `zb-test` modules also opens up more dependencies (i.e. can use jackson), so I can also add `MockRecord`, `MockRecordMetadata`, etc.

**Review by menski — APPROVED** [review]

**Comment by menski** [comment]
As discussed, I like the improvements to the testing of exporters. I already approved the pull request but feel free to continue refactoring and documenting. You can then merge it your self without needing further review from me.

**Comment by npepinpe** [comment]
So this doesn't contain abstracting away the integration test, since imo I'm not sure it's the right approach. I'd rather provide a flexible integration test rule that users can use piecemeal; subclassing a test class just seems like calling for trouble.

I think in general a good refactor of our test utils would benefit anyone who tries to use them; it's kind of a pain to configure an embedded broker at the moment, for example if you start your external system as an outer rule of the `ZeebeTestRule`, how do you inject the exporter config? Anyhow, I'll merge for now and do the integration stuff later.

**Pull request merged**
