### PR TITLE
chore(protocol): IncidentRecord return ErrorType instead of String

### LINKED ISSUE #2627: IncidentRecordValue#getErrorType should return enum
see https://github.com/zeebe-io/zeebe/issues/2616

### PR DESCRIPTION
**Pull request by miguelpires**
BREAKING CHANGE: IncidentRecord#getErrorType now returns ErrorType
instead of String

closes #2627

### CODE REVIEW

**Comment by menski** [comment]
@MiguelPires small hint regarding the commit message. To let the `BREAKING CHANGE` show up in our changelog automatically please use the `fix` commit message type instead of `chore`. Also please format the message that `BREAKING CHANGE:` is on a single line. Thanks

```
fix(broker): IncidentRecord return ErrorType instead of String

BREAKING CHANGE: 
- IncidentRecord#getErrorType now returns ErrorType instead of String
```

**Comment by MiguelPires** [comment]
Sure, I'll fix that. Thanks for letting me know

**Review by npepinpe — DISMISSED** [review]
:+1:

**Comment by MiguelPires** [comment]
Fixed the merge conflicts

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
