### PR TITLE
feat(broker): add gateway version command

### LINKED ISSUE #2981: Broker version via API
Ruby, Elixir, and Elm are famous for helpful error messages.

At the moment, users get cryptic error messages due to client protocol mismatches. 

For example, if you run a 0.15 client against a 0.20.0 broker and try to use the old query API, it blows up and it is not clear why. An example error message:

```
Error: 12 UNIMPLEMENTED: Method not found: gateway_protocol.Gateway/ListWorkflows
```
Seen in the wild: https://zeebe-io.slack.com/archives/CKRHB068Z/p1565629750001000

Is there a way that we can do something like that to inform the user, or return back the broker version so that we can program the client to inform the user of the likely cause? E.g:

```
This client targets the 0.20.0 broker, and the broker is running 0.22. Check for an updated client lib version.
```

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Implements the gateway version rpc in the Gateway.

## Related issues

closes #2981 

## Pull Request Checklist

- [ ] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [ ] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [ ] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
