### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by korthout**
## Description

Merges the release branch back in to develop as part of the release procedure.

### CODE REVIEW

**Comment by korthout** [comment]
Commit c8ba2fa was actually not released, as it was merged onto the release-1.3.0 branch after the release was build

**Comment by korthout** [comment]
@Zelldon might make sense if you have a look whether it's okay to merge it like this

**Comment by Zelldon** [comment]
@korthout can we take a look at it together tomorrow? I'm a bit confused why there a so many changes if we want to merged it into develop, shouldn't most of theses changes not already in their?

**Review by ChrisKujawa — APPROVED** [review]
Thanks for the discussion :heart: (seems to be a github issue) git doesn't show these changes

**Comment by korthout** [comment]
Yes, interesting situation. But as we discussed, merging this `git checkout origin/develop && git merge origin/release-1.3.0` results in ``` 43 files changed, 70 insertions(+), 71 deletions(-)```. Those include only pom file updates bumping the development version and go client version changes.

bors merge

**Pull request merged**
