### PR TITLE
add definition of ready to PR template

### PR DESCRIPTION
**Pull request by korthout**
## Description

During the `PR Reviews` sharpen the axe session, the group discussed ideas on how to improve the pull request process. This first session specifically discussed improvements to benefit the reviewer. This PR adds a checklist to help author's to improve their pull requests.

The main ideas of this checklist are discussed in our wiki page on [Pull Requests and Code Reviews](https://github.com/camunda-cloud/zeebe/wiki/Pull-Requests-and-Code-Reviews). That page should be considered part of this PR.

## Related issues

NA

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [x] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by korthout** [comment]
@saig0 please have a look (please also consider https://github.com/camunda-cloud/zeebe/wiki/Pull-Requests-and-Code-Reviews as part of this PR)

**Review by saig0 — APPROVED** [review]
LGTM :cookie: 

Since the PR description is growing, it would be nice to remove the  `Definition of Ready` and `Definition of Done` sections from the final (merge) commit to avoid noise in the commit history.

**Comment by korthout** [comment]
@saig0 Good idea, we could use the `cut_body_after` configuration option from bors for this:
> A marker in the PR description that indicates boilerplate that does not belong in the commit message.

See: https://bors.tech/documentation/ (in the reference tab)

**Comment by korthout** [comment]
bors merge

**Pull request merged**
