### PR TITLE
chore(broker): remove duplicate variable state remove

### LINKED ISSUE #2066: Variable scope is removed twice
When removing an element instance:
https://github.com/zeebe-io/zeebe/blob/f3c41078bd061a7d93aea61b138306de2f034481/broker-core/src/main/java/io/zeebe/broker/workflow/state/ElementInstanceState.java#L159

When terminating an element instance:
https://github.com/zeebe-io/zeebe/blob/f3c41078bd061a7d93aea61b138306de2f034481/broker-core/src/main/java/io/zeebe/broker/workflow/processor/handlers/AbstractTerminalStateHandler.java#L44

Probably the later is not required

### PR DESCRIPTION
**Pull request by menski**
closes #2066

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
Is it 10000% faster now? 😮 

Also I think it's fine for now, but at some point we should enforce how entities are related together (e.g. we delete an instance and remove its variables, but then remove event scopes explicitly separately)

**Comment by menski** [comment]
I agree that we can improve here a lot. And no it's not faster just removed one of the pillars in the flamegraph.

**Comment by menski** [comment]
bors retry

**Pull request merged**
