### PR TITLE
Remove unused atomix configuration options

### PR DESCRIPTION
**Pull request by ChrisKujawa**
# Description

During cleaning up my last PR I saw that we have a lot of dead code and possibilities of how to configure atomix, which is actually not used.

Removes unused atomix configuration options, like configuration via files etc.

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
You have no idea how happy I am to see things like PolymorphicConfigMapper be removed :joy: 

I'm surprised we didn't get rid entirely of the `com.typesafe.config` dependency? Is `io.atomix.utils.config.ConfigMapper` still used anywhere? :thinking:

**Comment by Zelldon** [comment]
@npepinpe happy that you like it :laughing: 

It was somehow used in the util. But I will properly delete this also soon.

**Comment by Zelldon** [comment]
Bors r+

**Pull request merged**
