### PR TITLE
perf(sequencer): Optimize isEntryValid method for improved performance

### LINKED ISSUE #19225: `Sequencer#isEntryValid` is slow because it has to calculate the full record size
This method checks that record value and metadata don't have size 0. This validation was copied over from the dispatcher.
The method shows up in profiling because calculating the length of `UnifiedRecordValue` is a fairly expensive operation. The length is calculated by recursively walking the object graph until we find primitive types such as `long`.

We should be able to remove this checks because `RecordMetadata` can never have length 1 and `UnifiedRecordValue` also offers an optimized `isEmpty` method.

### PR DESCRIPTION
**Pull request by jawaharbabus**
## Description
This pull request addresses the performance issue raised in #19225 by optimizing the `isEntryValid` method in the `Sequencer` class.

## Changes

- Replaced the `getLength() > 0` check for `UnifiedRecordValue` with the more efficient `isEmpty()` method.
- Removing the `getLength() > 0` check for `RecordMetadata`.

## Performance Improvements

Before optimization, the `isEntryValid` method was a performance bottleneck due to the expensive calculation of the record size. By using the optimized `isEmpty()` method, the method's execution time has been significantly reduced.

Please refer to the profiler screenshots (before and after the changes)

image

closes #19225

### CODE REVIEW

**Review by mustafadagher — APPROVED** [review]
Thanks for the contribution! LGTM, but I think it'd be good for @lenaschoenburg to take a quick look too!

Please fix the following before merging:
❌ Please fix the [failing unit tests](https://github.com/camunda/camunda/actions/runs/9473746715?pr=19286)
❌  Please fix the commit message to match the [Commit Message Guidelines](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#commit-message-guidelines) (remove the scope)

**Review by mustafadagher — CHANGES_REQUESTED** [review]
Thanks for the contribution! LGTM, but I think it'd be good for @lenaschoenburg to take a quick look too!

Please fix the following before merging:
❌ Please fix the [failing unit tests](https://github.com/camunda/camunda/actions/runs/9473746715?pr=19286)
❌ Please fix the commit message to match the [Commit Message Guidelines](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#commit-message-guidelines) (remove the scope)

**Comment by jawaharbabugit** [comment]
@mustafadagher The unit tests have failed with the error "Error: Found duplicate test runs!," which is likely an issue with the CI/CD pipeline configuration or test runner setup, rather than being directly related to the changes that I have made.

**Comment by mustafadagher** [comment]
> @mustafadagher The unit tests have failed with the error "Error: Found duplicate test runs!," which is likely an issue with the CI/CD pipeline configuration or test runner setup, rather than being directly related to the changes that I have made.

Hi @jawaharbabugit , I think we might be looking at different things. But please scroll down more in the summary details and click on `Load summary` for some of the other testing steps. There are errors like the following and more.

Screenshot 2024-06-13 at 09 59 11
Screenshot 2024-06-13 at 09 59 27

**Comment by npepinpe** [comment]
The failing AsymmetricNetworkPartitionIT looks like a flake since it fails in the set up :thinking: 

But the `LogStorageAppenderTest` look like real failure (even if they have poor error messages :sweat_smile:)

**Pull request closed without merging**
