### PR TITLE
fix(clients/java): updated javadoc

### LINKED ISSUE #2211: Update outdated javadoc for update retries
The javadoc claims that an incident is automatically resolved, which is not true anymore. We should replace this with a description that the incident still has to be resolved.

https://github.com/zeebe-io/zeebe/blob/7dcc5b7cd5744af5e2dbe1a594d29e5a3f6b5627/clients/java/src/main/java/io/zeebe/client/ZeebeClient.java#L225-L226

### PR DESCRIPTION
**Pull request by miguelpires**
closes #2211

### CODE REVIEW

**Review by menski — CHANGES_REQUESTED** [review]
Can we please change *subscription* to *worker* as this is also outdated. Also it would be nice to link to the method the user can use to resolve an incident.

**Comment by menski** [comment]
Also as this is a `fix` commit, it would be an improvement for the changelog if the message is a bit more descriptive, i.e. *clarify outdated update job retries java doc*.

**Comment by MiguelPires** [comment]
Sure, I'll change the commit message when I squash

**Review by menski — APPROVED** [review]

**Pull request merged**
