### PR TITLE
Fix revapi appearing in distribution dependencies

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes a mistake where the prepare-offline profile will include revapi to all modules as a dependency, but did not specify it was in scope test, resulting in it appearing in the distribution. There is another PR which will apply this fix (and more) to develop and the stable/1.0 branch already, but we need to include this fix for the upcoming release.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by korthout — APPROVED** [review]
Nice find!

LGTM 👍 

EDIT: do you want to forward port this to develop?

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
No, as I mentioned, there's already another PR with this fix targeting develop.

**Comment by npepinpe** [comment]
Why is bors not doing anything? :thinking:

**Comment by npepinpe** [comment]
bors merge

**Comment by korthout** [comment]
> Why is bors not doing anything? 🤔

I'm not sure, but Jenkins had problems receiving webhooks from github around the same time. Might be related. Let's keep an eye open whether it happens again.

**Pull request merged**
