### PR TITLE
Remove `zeebe-test` from BOM

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Remove `zeebe-test` from the BOM but keep using it internally.

As it's now used internally only, we can remove the deprecation annotations, remove unused code and remove the check for backwards compatibility.

## Related issues

relates to #8030

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
Looks good. I'd like to go one step further however and remove it entirely.

AFAIK, the only remaining things used are the exporter related testing utilities (used by the Elasticsearch Exporter). 

I see the EmbeddedBrokerRule is still there, and the ClientRule, but I think both are still only used indirectly by the exporter testing utilities, correct?

We can of course do that as a follow up issue :slightly_smiling_face:

**Comment by oleschoenburg** [comment]
Yeah, `ClientRule` and `EmbeddedBrokerRule` are only used in `ExporterIntegrationRule` which in turn is used by the elasticsearch module and the protocol-jackson modules. If we wouldn't use it in protocol-jackson we could just move everything from zeebe-test to the elasticsearch module which would make sense.

**Comment by npepinpe** [comment]
It can be a follow up issue. I think the protocol Jackson test isn't ideal anyway and we could find an alternative.

**Pull request merged**
