### PR TITLE
Fix RaftMember.Type backwards compatibility 

### LINKED ISSUE #4309: Removing BOOTSTRAP from RaftMember.Type broke backwards compatibility
**Describe the bug**

Due to removing the bootstrap logic and better partition distribution in #4298 we removed `BOOTSTRAP` from the `RaftMember.Type` enum. The problem is that this is persisted as raft configuration to disk, which means if you update from 0.23.0 to SNAPSHOT the cluster, will not start since the enum counts have changed.

This was reported by @sdorokhova on slack.

> svetlana  17:36
> Hi colleagues,
> I'm now working on test that runs Zeebe 0.23.0, generates some data and then runs SNAPSHOT Zeebe (in docker) on the same data folder. The latter is failing with:
> Invalid ordinal for enum "io.atomix.raft.cluster.RaftMember$Type": 4

**To Reproduce**
Start a 0.23.0 cluster, stop it and start a snapshot version cluster.

**Expected behavior**
No problems on starting snapshot version with old data.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

 * Brings back the `RaftMember.Type.BOOTSTRAP` to ensure backwards compatibility. (@deepthidevaki your part)
 * enable upgrade tests and add logging for tests (@MiguelPires your part to review)

I assigned you both since it is a broader scope. I still need to fix the upgrade test for the gw.

## Related issues

closes #4309

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by Zelldon** [comment]
@MiguelPires I ignore the OldGatewayTest for now, since it takes a bit longer to fix this issue. I created a separate issue to fix this https://github.com/zeebe-io/zeebe/issues/4314

**Review by deepthidevaki — COMMENTED** [review]
Would it be better if we just check for type BOOTSTRAP in `DefaultRaftMember` where ever we write to type? Otherwise it is not easy to verify if we have missed any place to set it to ACTIVE. 
``` java
setType(Type type) {
  if(type == BOOTSTRAP) {
     this.type = ACTIVE;
  } else {
      this.type = type
  }
}
```
Also I am wondering if it possible to persist the new config without bootstrap so that eventually we can remove that type.

**Comment by Zelldon** [comment]
@deepthidevaki we should not set this type anymore and we don't currently. But it can be still persistent on disk and that is why we need to check it. It can only appear on start up, so it should not be a huge deal. Would be nice to remove it at someday but Idk if this is possible since it can always happen that a user has an older version.

**Comment by Zelldon** [comment]
As discussed @deepthidevaki I intercept the setting of the `RaftMember.Type` on the `DefaultRaftMember`. I kept the check on the bootstrap etc, feels for me safer since it seems kryo can create the members directly without calling the setter. But we can discuss this if you want to remove this.

**Comment by deepthidevaki** [comment]
> I kept the check on the bootstrap etc, feels for me safer since it seems kryo can create the members directly without calling the setter.

:+1: We can keep the check although we are always rebuilding the in memory state after reading the configuration from disk.

**Comment by Zelldon** [comment]
Thanks @deepthidevaki :+1:

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Pull request merged**
