### PR TITLE
feat(clients/zbctl): publish messages with JSON file as variables

### PR DESCRIPTION
**Pull request by Sijoma**
## Description

This allows to pass in a file path to the variables flag of the publish message command. The command first checks if its a JSON string. If it is not, it checks whether it is a file path. It's a bit cumbersome to surface the correct error to the user in this case. It is either an invalid file / file path or invalid json. 

Another approach would be to use a second flag specifically for the file name. That was also a bit weird if the user uses both flags. Should one override the other flag or should they get merged somehow? I left this solution commented out so that it can also be reviewed. 

## Related issues

/relates to https://github.com/camunda-cloud/zeebe/issues/1422

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
Please remove the commented out code :slightly_smiling_face:

**Review by npepinpe — APPROVED** [review]
Looks good. Just two suggestions, no blockers. Let me know if you agree and I can take a second look.

:question: One small question - the test doesn't really verify that the variables are actually sent, right? I mean, I guess the other one didn't either, but still :smile:

**Review by npepinpe — APPROVED** [review]
It's fine, I understand previous tests didn't, and it's not so easy from the outside to verify this. The way I would go about it is deploying a process with a message start event which will create a job with the variables it received from the message. In the test you can then activate that job and verify it.

But I'm accepting it for now even without it, we can add it later. Although feel free to add it if you want :smile:

**Comment by npepinpe** [comment]
Is it ready for merging?

**Comment by Sijoma** [comment]
bors merge

**Pull request merged**
