### PR TITLE
Add spring-boot-dependencies as import scope in dependencies management

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR adds `spring-boot-dependencies` as a `import` scoped dependencies in `parent/pom.xml`, and remove explicit Spring dependencies (including the Tomcat one). This is to ensure dependencies used directly and only by Spring are kept in sync, which should avoid issues like #5707 where we try to update a dependency that is not yet supported by our Spring Boot version.

This PR also removes explicit Jackson dependencies as we already import the Jackson BOM as well.

## Related issues

related to #5707 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
I requested a review from both @cmur2 and @menski as I'm not very familiar with maven, so whichever of you can confirm that this change won't lock in users importing our own modules to certain versions used by Spring and so, that'd be nice - or if you can think of anything dangerous about doing this, please tell me :+1:

**Comment by cmur2** [comment]
I think I cannot oversee the implications of this change for the Maven project. Thanks for the politely explained (via PM) request :)

**Comment by npepinpe** [comment]
Thanks for answering anyway, no worries, it's quite possible I wasn't clear. Let's see what menski has to say

**Review by pihme — APPROVED** [review]

**Pull request merged**
