### PR TITLE
feat(bpmn-model): support conditional events

### LINKED ISSUE #11340: I can deploy a process definition with conditional events
**Is your feature request related to a problem? Please describe.**
As a user, I can deploy a process definition with conditional events.

image

**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Additional context**
* The condition of a `conditional start event` must be unique within a given process definition, i.e. a process definition cannot have multiple `conditional start events` with the same condition. If two or more `conditional start events` contain the same condition, the engine will reject the deployment process definition.
* The condition of a `conditional start event for event subprocess` must be unique within a given process definition, i.e. a process definition cannot have multiple `conditional start event for event subprocess` with the same condition. If two or more `conditional start event for event subprocess` contain the same condition, the engine will reject the deployment process definition.

### PR DESCRIPTION
**Pull request by lzgabel**
## Description
As a user, I can deploy a process definition with conditional events.

image

## Related issues
closes #11340

## Definition of Done

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by remcowesterhoud — COMMENTED** [review]
I haven't looked at the code yet. Let's focus on the breakdown first before we start implementing 😄

**Comment by remcowesterhoud** [comment]
I will convert this to a draft PR as I keep getting notifications about it. I will have a look at you comment in the breakdown soon 🙂

**Comment by remcowesterhoud** [comment]
@lzgabel Thanks again for this contribution ❤️ 

As you mentioned you don't have time to do a full task breakdown for the conditional events topic. I discussed with the team today and we have a bunch big topics coming with a higher priority for us. Therefore, we don't have the capacity to create the task breakdown at this moment either.

Without a task breakdown we don't see this event getting implemented short-term. Because of this I don't think it's a good idea to merge this PR, as it will allow deployments of processes with this event that is unsupported. As a result I'm afraid I'm going to have to close this PR until we actually find the capacity to implement this fully.

I'm very sorry for this, we truly appreciate all your contributions 🙇

**Comment by lzgabel** [comment]
Hi @remcowesterhoud . It doesn't matter, don't worry for now, I will continue to create the task breakdown when I have time. I will give feedback to the team in time to avoid external contributions from disrupting the roadmap. Thanks. ❤️

**Pull request closed without merging**
