### PR TITLE
test(bpmn-model): add more validation tests for message catch element

### LINKED ISSUE #1063: Add test cases in the model API for message related elements
* test when parsing and validation of intermediate message catch event and receive task

### PR DESCRIPTION
**Pull request by saig0**
closes #1063

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 656787a68c28709abfd15f7dbe8b5c97bbadf92f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by saig0** [comment]
@menski , what is wrong about the commit message?

**Comment by menski** [comment]
@saig0 this commit https://github.com/zeebe-io/zeebe/commit/656787a68c28709abfd15f7dbe8b5c97bbadf92f has missing a white space between `:` and the message

**Review by menski — APPROVED** [review]
bors r+

**Pull request merged**
