### PR TITLE
Move cluster cfg error handling

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Another controversial topic (maybe). @oleschoenburg and I stumbled over it during adding a new config for the batch processing and were wondering why the config error handling is not in the corresponding classes. This would make it more self-contained (and we thought it is easier to find and test).

@npepinpe would be interested in your opinion since you were also working in the space for a bit. If you agree we can do that also for the other configs.

**What the PR does:**

Moves the cluster parameter handling to the ClusterCfg, and out of the `SystemContext`. This makes it more self-contained and encapsulated.

## Related issues

closes #

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
My main objection to this is that the configuration classes are mutable, and I can't guarantee we always call `init`, but I guess the current code isn't that much safer.

I would like in general that we move to having immutable configuration classes in the modules themselves, and all "mutable", YAML instantiated config in the distribution module. In that sense, validation would be done in the immutable, module-specific configuration as well. This would also allow us to make use of Spring annotations and expressions more freely in the distribution module, and cleanly separate user instantiated (which is a public API in a way) configuration from the modules themselves, allowing us to more easily refactor these as we please.

Anyway, I'm fine with this change, it's a step in the right direction overall :+1:

**Review by lenaschoenburg — APPROVED** [review]

**Comment by npepinpe** [comment]
Any update on this?

**Comment by Zelldon** [comment]
Yes is on my todo list. I started last week already several times to update it, but I have been quite busy unfortunately. I hope I can do it this week.

**Comment by npepinpe** [comment]
If you have too much stuff going on, let me know, maybe I can take over

**Review by npepinpe — APPROVED** [review]
:rocket:

**Comment by Zelldon** [comment]
Bors r+

**Pull request merged**
