### PR TITLE
Upgrade to JDK 17 containers for CI

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

This PR will upgrade the containers that are used during CI to JDK 17.

## Related issues

closes #8029

### CODE REVIEW

**Review by korthout — APPROVED** [review]
Nice work! LGTM 🎉  But please consider my comments

**Review by korthout — APPROVED** [review]
👍 Thanks @oleschoenburg I see no real problems with this, but I might not oversee everything on this one. @npepinpe can you also have a look?

**Review by npepinpe — CHANGES_REQUESTED** [review]
The release seems to be using a different pod spec which is still on Java 11. We can either update that, or look into having it reuse the same pod spec we use for the other jobs. See https://github.com/camunda-cloud/zeebe/blob/develop/.ci/pipelines/release_zeebe.groovy.

I'm totally fine if you want to separate that into another PR of course.

**Review by npepinpe — APPROVED** [review]
:+1:

**Pull request merged**
