### PR TITLE
refactor: remove variable cleanup mode

### PR DESCRIPTION
**Pull request by HeleneW-dot**
## Description
Removes `variable` cleanup mode from Optimize C8.
This config is not mentioned in camunda-operator or camunda-platform-helm.

Please also review the follow up [docs PR.](https://github.com/camunda/camunda-docs/pull/4184)

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

related to [OPT#13211](https://github.com/camunda/camunda/issues/33560)

### CODE REVIEW

**Review by RomanJRW — CHANGES_REQUESTED** [review]
I didn't actually review this - but why are we removing this? I don't see this as a C7 feature, and can even imagine some customers in SM using this configuration in C8

**Comment by PHWaechtler** [comment]
> I didn't actually review this - but why are we removing this? I don't see this as a C7 feature, and can even imagine some customers in SM using this configuration in C8

This came from the removal tasks initially synced with Omran when we started working on the fork, I was informed this is not a C8 feature since in C8 we always clean up all instance data. Is this supposed to be available in C8?

**Comment by PHWaechtler** [comment]
> > a C8 feature since in C8 we always clean up all instance data
> 
> Is this not only true in SaaS? I can imagine SM customers using the variable cleanup

The info I had was that its C7 only, but I'm following up to see if there was a specific source for that or if there was a misalignment somewhere. If its C8 too we can close this pr.

**Comment by PHWaechtler** [comment]
> > > a C8 feature since in C8 we always clean up all instance data
> > 
> > 
> > Is this not only true in SaaS? I can imagine SM customers using the variable cleanup
> 
> The info I had was that its C7 only, but I'm following up to see if there was a specific source for that or if there was a misalignment somewhere. If its C8 too we can close this pr.

@RomanJRW [This](https://docs.google.com/spreadsheets/d/1MF_LUb5NFqx8kreYsxXLK3LM2KGXndun5LplUK0EZ6s/edit?gid=0#gid=0) is the sheet this info came from (see line 100), I will ping tobias to ask if thats outdated/incorrect.

**Comment by RomanJRW** [comment]
@PHWaechtler - Sure, sounds good. Note that if we proceed with deleting, I think it would also need to be something we communicate in the upgrade guide as it would be a breaking change for anyone using it 👍. Please ensure Tobias is aware of this when making this decision

**Comment by PHWaechtler** [comment]
Closing as we will keep this in C8. C8 feature sheet updated accordingly [here](https://docs.google.com/spreadsheets/d/1MF_LUb5NFqx8kreYsxXLK3LM2KGXndun5LplUK0EZ6s/edit?gid=0#gid=0). I think the same will apply to the process data cleanup config (line 99)

**Pull request closed without merging**
