### PR TITLE
Lower log level of component unhealthy message to warning

### LINKED ISSUE #5540: ZeebePartition-3 failed, marking it as unhealthy
**Describe the bug**
Observed as error in production logs.

**Expected behavior**
Should be logged at most as warning

**Log/Stacktrace**
https://console.cloud.google.com/errors/COLeu9btrqXoDw?service=zeebe&time=P7D&project=camunda-cloud-240911
https://console.cloud.google.com/errors/CLHr_6rOjdftngE?service=zeebe&time=P7D&project=camunda-cloud-240911

**Environment:**
Camunda Cloud / Prod / 0.24.2, 0.24.3

### PR DESCRIPTION
**Pull request by korthout**
## Description

This is an expected and potentially self-recoverable event, and should
therefore be logged at warn level instead of error.

## Related issues

closes #5540 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
:+1:

bors r+

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
bors merge

**Comment by korthout** [comment]
bors merge

**Pull request merged**
