### PR TITLE
Fix race condition between cancel and activate

### LINKED ISSUE #2784: Race condition between cancel and activate job commands
There exists a race condition between canceling and activating a job which can lead to a exception and endless loop in the job timeout processor.

```
10:15:17.816 [exporter] [0.0.0.0:26501-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter.debug-log - {
  "key" : 2251799813702419,
  "position" : 25770926768,
  "timestamp" : 1562074900169,
  "recordType" : "COMMAND",
  "intent" : "CANCEL",
  "partitionId" : 1,
  "valueType" : "JOB",
  "rejectionType" : "NULL_VAL",
  "rejectionReason" : "",
  "sourceRecordPosition" : 25770898648,
  "value" : {
    "errorMessage" : "",
    "workflowKey" : 2251799813686157,
    "bpmnProcessId" : "eventBasedGatewayProcess",
    "customHeaders" : { },
    "worker" : "operate",
    "retries" : 3,
    "elementId" : "timerTask",
    "workflowDefinitionVersion" : 1,
    "deadline" : 1562074880244,
    "type" : "timerTask",
    "workflowInstanceKey" : 2251799813689517,
    "elementInstanceKey" : 2251799813702364,
    "variables" : { }
  }
}

10:15:18.271 [exporter] [0.0.0.0:26501-zb-fs-workers-0] DEBUG io.zeebe.broker.exporter.debug-log - {
  "key" : 2251799813702419,
  "position" : 25770991272,
  "timestamp" : 1562074900201,
  "recordType" : "EVENT",
  "intent" : "ACTIVATED",
  "partitionId" : 1,
  "valueType" : "JOB",
  "rejectionType" : "NULL_VAL",
  "rejectionReason" : "",
  "sourceRecordPosition" : 25770924144,
  "value" : {
    "errorMessage" : "",
    "workflowKey" : 2251799813686157,
    "bpmnProcessId" : "eventBasedGatewayProcess",
    "customHeaders" : { },
    "worker" : "operate",
    "retries" : 3,
    "elementId" : "timerTask",
    "workflowDefinitionVersion" : 1,
    "deadline" : 1562074905169,
    "type" : "timerTask",
    "workflowInstanceKey" : 2251799813689517,
    "elementInstanceKey" : 2251799813702364,
    "variables" : {
      "clientId" : "4"
    }
  }
}
```

First the cancel command was written, and then the job was activated again before the cancel was processed. The state contains now the a record with the new deadline of the activated job `1562074905169`. But when the cancel command will be processed it tries to delete a job with the old deadline of the cancel command `1562074880244` which does not exist anymore but it misses the new deadline entry. Next time the timeout processor iterates over the state it finds the orphaned deadline entry and tries to load the job from the state which does not exist anymore as it was deleted during the cancellation.

To fix this we should builds something more reliable:
1. We should try to implement something which deletes all entries for a job key from the deadlines column family no matter the deadline in the job record.
2. When the timeout processor is missing a job it should not hard fail, but instead log a warning but continue and delete the orphan entry, as there is no was to recover from it and it's no serious problem if the job does not exist anymore.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
* cancel processor uses current state instead of written value
 * state will clean up and not fail if detects a missing job
 * add new possibility to write tests
   * we can now write batch of records (atomically)
   * we can write this batch before the engine starts to trigger reprocessing

I decided against iterating over column family on delete/cancel job, since this will cause some performance issues if we have many jobs.

closes #2784

### CODE REVIEW

**Review by saig0 — CHANGES_REQUESTED** [review]
I like it :+1: 

Just one point: 3 classes are not used `Single/-RecordSequence(s)`. They can be deleted.

**Comment by Zelldon** [comment]
Oh yes sorry forgot to delete them.

**Comment by Zelldon** [comment]
@saig0 removed the files

**Review by saig0 — APPROVED** [review]
bors r+

**Pull request merged**
