### PR TITLE
Simplify ArrayValue and fix job stream aggregation

### LINKED ISSUE #14773: Job streams not aggregate correctly on gateway
**Describe the bug**

It would seem aggregate of job streams is failing on the gateway due to our usage of `ArrayProperty` (and underlying `ArrayValue`). The implementation of `equals` and `hashCode` for these is not consistent since it relies on the last modification being reflected in their internal buffer, which is not always the case.

**To Reproduce**

Start a cluster of one gateway, one broker. Create two job streams/workers with the exact same parameters. You will see two client streams on the gateway - which is correct - but each will have a different server stream ID, which is incorrect.

**Expected behavior**

Logically equivalent client streams are aggregated on the gateway.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes job stream aggregation and simplifies our MsgPack `ArrayValue` implementation.

It fixes several issue with the `ArrayValue` implementation:

1. Reading from it is fully immutable, including iteration
2. `equals` and `hashCode` are consistent/deterministic
3. Greatly simplified code which uses basic data structures

### "Garbage-free" implementation

`ArrayValue` worked by keeping an internal, expandable byte buffer. Whenever a new item was added to the array, it was reusing the same `innerValue` - think of it like an in-memory buffer for the next added value. So if you had an `ArrayValue` of integers, then the `innerValue` would be one pre-allocated instance of `IntegerValue` which would get reused. Every time you called `add`, it would do two things:

1. If the current `innerValue` was set, it would serialize it using a `MsgPackWriter` to its internal byte buffer at the current index. _This is how you could use the iterator to decide where to insert elements in the array, a feature we seldom used_. To do so, it might have to shift left or right the existing elements in order to make some space.
2. It would then reset the current `innerValue`, increment the element count, and return the `innerValue` so you could then modify it.

One important thing to note - when modifying the `innerValue`, that change was not immediately reflected on the `ArrayValue` internal byte buffer. It was only reflected if `add`, `write`, or `iterator` was called - at which point we'd do a so called `flush` operation and write the `innerValue` (and again, possibly shift elements around to make space) to the internal buffer.

When you would call `iterator`, then, we always had to first `flush` the `innerValue`, then reset some internal iteration state, and then since the iteration state is just part of `ArrayValue`, we'd return `this`. Calling `next` and so on would then modify the internal state (including `innerValue` and where you could insert/remove elements from in the internal buffer), and as such as not immutable.

That said, iterating was purely garbage free, so long as you didn't add or remove any elements. Adding/removing elements was obviously not garbage free since you had to write them back to the buffer, which would sometimes need to be grown to accommodate the immediate serialization.

> **Note**
> Since we only kept the serialized values in memory, the memory footprint of an `ArrayValue` with 100 integers was typically lighter than keeping, say 100 `IntegerValue` instances in memory due to the boxing overhead. That said, there was a trade-off on reading since you had to deserialize every time, which could be non-negligible for things like more complex values.

### Proposal

The proposal is to allow a little bit of garbage, but greatly simplify how the `ArrayValue` works, as well as making it fully read-immutable **and** fixing comparison of array values (yes, comparison didn't work, which was a bit of a surprise since `equals` is generally well implemented on almost all base values).

First, we get rid of the internal buffer and the reusable `innerValue`. Instead, we'll use a dumb `ArrayList` and allocate new inner values (e.g. `new IntegerValue`) via a given factory. 

> **Note**
> We can mitigate garbage here by either using a factory which pools objects, or using `ReusableObjectList` as well - though that one had some bugs, which is why I omitted it here :upside_down_face: 

This means the memory footprint is now slightly higher - every instance has some overhead, plus the overhead of the `ArrayList` itself. However, this has some nice properties:

- We can make `ArrayValue` a `RandomAccess` collection, and easily implement `size`, `isEmpty`, `get(index)`, `add(index)`, etc. 
- We can get garbage-free iteration by using a dumb `for (int i = 0; i < array.size(); i++)` and the `get(index)` method.

Unfortunately calling `iterator` (or using with an enhanced for-loop) on `ArrayValue` is likely not garbage free, though I suspect that the JIT will eventually perform scalar replacement for basic cases. I haven't verified this because I suck at JIT visualization, but it would be a nice time to start ;) Just looking at the byte code it's quite clear we're allocating, versus the C-like for-each loop which is obviously not.

You can still use the `iterator` of course for the additional protection against concurrent modification - but if you're sure, and you have a large array, then the dumb C-like for-each loop will be slightly faster typically (based on old JMH benchmark - I'd have to recreate/rerun these to see if that's still true in Java 21).

### :warning: Downside

**One big caveat here**: there were some use cases where we assumed (correctly or incorrectly?) that adding an element an `ArrayValue` would effectively copy it. Basically, whenever you called add, or iterator, etc., it would serialize anything from the `innerValue` and put it in the internal buffer. That was creating a copy of the value (and possibly growing the buffer), which made it "safer" transparently reuse the `innerValue`. With this change, in some cases, you would have to think if you need a copy of the `innerValue`'s actual value, and if so manually copy them.

For example, when adding jobs to the `JobBatchRecord#getJobs` property, we would pass the same buffer (into which we had previously copied the job) to the `ArrayValue`. Since it would serialize it to the internal buffer, it was effectively a new copy. Now that we would use just a new instance of `JobRecord`, it wouldn't, so it's a bit of a behavior change. Nothing crazy though.

## Related issues

closes #14773
related to #14624 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
See https://github.com/camunda/zeebe/pull/14737 for benchmarks. Performance seems comparable if we ignore the regression introduced after CW41.

**Review by lenaschoenburg — COMMENTED** [review]
The `ArrayValue` changes make sense to me.

> One big caveat here: there were some use cases where we assumed (correctly or incorrectly?) that adding an element an ArrayValue would effectively copy it

I find this a bit concerning too. I've tried to go over usages of `add` to see if I could find anything that is unsafe. I didn't find anything but think that it is somewhat difficult to _really_ make sure that this is the case. For example, look at `EventScopeInstance#addInterruptingElementId` and try to proof that this is safe... :thinking: 

Everything that is written to an `add`ed element must be immutable until the `ArrayValue` is serialized. It seems to be very easy to make a mistake. Overall this is not really new - we always had memory safety bugs caused by reusing buffers etc.

@npepinpe The tests are failing, please take a look.

**Comment by npepinpe** [comment]
> Everything that is written to an added element must be immutable until the ArrayValue is serialized. It seems to be very easy to make a mistake. Overall this is not really new - we always had memory safety bugs caused by reusing buffers etc.

The thing is, this was already sort of the case, since you didn't really know when it would be flushed (or serialized to the inner buffer) =/

**Comment by npepinpe** [comment]
Usage of `UnmodifiableCollectionView`, while a nice utility, is not compatible with `equals` and `hashCode`. It was also only marginally useful here, so :shrug:

**Review by lenaschoenburg — APPROVED** [review]
:rocket:

**Pull request merged**
