### PR TITLE
refactor: use foreign keys for deployments

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

Uses `DbForeignKey` in `DbDeploymentState`.

relates to #8930

### CODE REVIEW

**Comment by oleschoenburg** [comment]
Hey @Zelldon, I had a quick chat with @pihme where he pointed out that [this](https://github.com/camunda-cloud/zeebe/pull/8940#issuecomment-1073826850) is probably still necessary because the list of pending deployments might become outdated and point to deployments that no longer exist in `ZbColumnFamilies.DEPLOYMENT_RAW` due to (very hand-wavey) network partitions/lost or duplicate network messages between partions. Do you happen to know if this can still happen or if there were any changes that make this code unnecessary?

**Comment by Zelldon** [comment]
Hey @oleschoenburg sorry for the delay.

> Hey @Zelldon, I had a quick chat with @pihme where he pointed out that this is probably still necessary because the list of pending deployments might become outdated and point to deployments that no longer exist in ZbColumnFamilies.DEPLOYMENT_RAW due to (very hand-wavy) network partitions/lost or duplicate network messages between partions. Do you happen to know if this can still happen or if there were any changes that make this code unnecessary?

I'm not 100% sure whether I can follow this argument sorry :see_no_evil: So this method is called here https://github.com/camunda-cloud/zeebe/blob/main/engine/src/main/java/io/camunda/zeebe/engine/processing/deployment/distribute/DeploymentRedistributor.java#L37 we make sure to redistribute the deployments. Everything works with commands-events (which are processed after another). This is also the case even for network partitions. The deployment distribution is so long retried until we received an ack and can delete the pending, which means there must never be the case that the deployment is missing here. As far as I remember at least. It has been a while that I worked on this code.

What would it mean if you add your reference check here? How does the failure handling look like? We fail the processing right?

**Comment by oleschoenburg** [comment]
> which means there must never be the case that the deployment is missing here. As far as I remember at least. It has been a while that I worked on this code

So in your mind the test `shouldNotFailOnMissingDeploymentInState` is not necessary but you don't remember why it was added in the first place? In that case I'd be a bit hesitant to just remove the test and add the foreign key checks. I don't want to break anything and we can always do it later.

**Comment by Zelldon** [comment]
The test was added to make sure that we dont fail in that case since this was the way we wanted to handle it at that point in time I would guess. But i assume this is no longer true right?

**Comment by Zelldon** [comment]
Isn't this the point of adding such checks? :sweat_smile: That we want to detect this and handle it somehow? Or didn't we thought about handling? I think this was the question I asked last week, what happens currently if some of these checks fail? What should happen? i think you mentioned it will blacklist? For deployment case it will potentially loop in the replay.

**Comment by Zelldon** [comment]
@oleschoenburg maybe create a separate issue for this case so we (or the engine team) can discuss and think about it properly

**Comment by oleschoenburg** [comment]
Okay, I'm closing this for now. I've created a follow-up issue: https://github.com/camunda-cloud/zeebe/issues/8957

**Pull request closed without merging**
