### PR TITLE
Do not take snapshots after shutdown was requested

### LINKED ISSUE #7188: Failed to take snapshot because RocksDb is shutting down
**Describe the bug**
Taking a snapshot in middle of shutting down resulted in: `io.camunda.zeebe.db.ZeebeDbException: Failed to take snapshot in path /usr/local/zeebe/data/raft-partition/partitions/1/pending/270685-24-270663-270664.`. We can prevent this by looking at the exception's status and ignore it if it's due to a shutdown being in progress.

**Log/Stacktrace**
https://console.cloud.google.com/errors/CNON5Mv1u8qCiQE?service=zeebe&time=P7D&refresh=off&project=camunda-cloud-240911

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.db.ZeebeDbException: Failed to take snapshot in path /usr/local/zeebe/data/raft-partition/partitions/1/pending/270685-24-270663-270664.
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.createSnapshot(ZeebeTransactionDb.java:131) ~[zeebe-db-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.broker.system.partitions.impl.StateControllerImpl.lambda$takeSnapshot$0(StateControllerImpl.java:178) ~[zeebe-broker-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.takeInternal(FileBasedTransientSnapshot.java:67) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.snapshots.impl.FileBasedTransientSnapshot.lambda$take$0(FileBasedTransientSnapshot.java:53) ~[zeebe-snapshots-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:73) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
	at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
Caused by: org.rocksdb.RocksDBException: ShutdownInProgress
	at org.rocksdb.Checkpoint.createCheckpoint(Native Method) ~[rocksdbjni-6.19.3.jar:?]
	at org.rocksdb.Checkpoint.createCheckpoint(Checkpoint.java:51) ~[rocksdbjni-6.19.3.jar:?]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransactionDb.createSnapshot(ZeebeTransactionDb.java:128) ~[zeebe-db-1.0.0.jar:1.0.0]
	... 9 more
```

</p>
</details>

**Environment:**
 - OS: 
 - Zeebe Version: 
 - Configuration:

### PR DESCRIPTION
**Pull request by pihme**
## Description

The change sets the db to null right away, so that any concurrent calls thereafter have no access to the database while it is closing.

It is not completely safe yet. The database could be set to 'null` between checking for `null` in line 187 and using the reference in line 194. 

## Related issues

related to #7188 

## Definition of Done
Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — COMMENTED** [review]
As you pointed out, this reduces the rate of incidence of the bug but doesn't completely fix it. Since taking a snapshot may happen on a different thread, it could even be that `db` is already null when the check is done on line 187, but the value read is outdated. IIRC, the state controller is called from the AsyncSnapshotDirector and from the ZeebePartition, both of which are actors, and as such executed at times on different threads. It could be that we should make the state controller an actor as well, though that would widen the scope of this PR.

:question: Do you think that the race condition you highlighted is not likely enough/important enough to warrant spending more time, or do you see value in immediately mitigating it with the idea that we'll come back and fix it properly later? If it's the latter, then we shouldn't close the issue by merging this PR, as it's not really fixed. I personally would opt to fix it properly, but I'd like to hear your thoughts.

**Comment by pihme** [comment]
> question Do you think that the race condition you highlighted is not likely enough/important enough to warrant spending more time, or do you see value in immediately mitigating it with the idea that we'll come back and fix it properly later?

I think it is an improvement over status quo. I also hope that with the other work we are doing and that Chris is doing this error won't be able to occur anymore, because we have better control over the shutdown sequence.

But I am also fine with leaving the issue open and revisiting it later.

**Review by npepinpe — APPROVED** [review]
:+1: 

Let's merge this for now, but remove the `closes` from the PR description as I wouldn't close the issue yet.

**Comment by npepinpe** [comment]
It looks like we never backported this in the end?  /cc @pihme

**Comment by pihme** [comment]
Seems like it slipped through, yes.

**Pull request merged**
