### PR TITLE
ci: use non-preemptible runners for jobs with highest disconnect rate

### PR DESCRIPTION
**Pull request by cmur2**
## Description

**Observation:** Over the last 7 days we have around 1500-2000 GHA jobs in this monorepo running on self-hosted runners, with around 1-1.5% disconnect rate (aka runners disconnects for whatever reason before job is finished):

image

This triggers the related [alert](https://github.com/camunda/camunda/wiki/CI-Runbooks#selfhosted-runner-high-disconnect-rate) very frequently.

Those disconnects happen very often for the same 3 GHA jobs and nearly never for other jobs on self-hosted runners:

image

It is unclear yet what these 3 GHA jobs have in common (if anything) that makes them experience higher disconnect rates. One hypothesis is that those jobs have longer runtimes than the others → more likely to experience node preemption.

**Experiment:** This PR starts the experiment of switching these 3 (Edit: only 2) GHA jobs to use non-preemptible runners (more expensive, less likely to disconnect?). We can monitor whether this reduces the disconnect rate and if so decide whether we are fine with the additional financial cost. Needs https://github.com/camunda/infra-core/pull/8566

"[IT] Zeebe QA - Integration Tests" was not moved to stable runners yet since that (for some reason) proved unreliable in the merge queue repeatedly.

## Checklist

- [x] for CI changes:
  - [x] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Comment by cmur2** [comment]
I noticed we don't have [non-preemptible variants of the `gcp-perf-core` runners](https://confluence.camunda.com/display/HAN/Github+Actions+Self-Hosted+Runners), I'd need to create them first if we want to go ahead with this experiment.

**Review by maxdanilov — APPROVED** [review]

**Comment by cmur2** [comment]
https://github.com/camunda/infra-core/pull/8566 was merged to `prod` and afterwards the pending jobs of this PR got immediately picked up by the new `longrunning` runners for `gcp-core-perf` type, so this PR is now fully green. I'll document the availability of the new runners and go ahead with the experiment here, by merging.

**Comment by cmur2** [comment]
Collecting insights on how the experiment is going:

* https://github.com/camunda/camunda/actions/runs/11724329531/job/32658036664 used a stable runner but still got terminated

**Comment by cmur2** [comment]
This PR was merged on 2024-11-07 so we have now a couple of days of new data. I ran the numbers comparing the average disconnect rate between 2024-10-15 and 2024-11-06 (before the experiment started) and 2024-11-07 and now (after the experiment started):

* `selfhosted_runner_disconnect_rate_before` is ~1.2%
* `selfhosted_runner_disconnect_rate_after` is ~0.5%

This is looking like the experiment makes a positive impact (but does not fully remove all error sources) on the disconnect rate. I will check in next week when more data is available.

<details>
```sql
WITH a AS (
  SELECT COUNT(*) as number_of_all_runners_before
  FROM `ci-30-162810.prod_ci_analytics.build_status_v2`
  WHERE report_time >= TIMESTAMP('2024-10-15') AND report_time <= TIMESTAMP('2024-11-06') AND ci_url="https://github.com/camunda/camunda" AND NOT STARTS_WITH(runner_name, "github ")
), b AS (
  SELECT COUNT(*) as number_of_disconnected_runners_before
  FROM `ci-30-162810.prod_ci_analytics.build_status_v2`
  WHERE report_time >= TIMESTAMP('2024-10-15') AND report_time <= TIMESTAMP('2024-11-06') AND ci_url="https://github.com/camunda/camunda" AND NOT STARTS_WITH(runner_name, "github ") AND build_status="aborted"
), c AS (
  SELECT COUNT(*) as number_of_all_runners_after
  FROM `ci-30-162810.prod_ci_analytics.build_status_v2`
  WHERE report_time >= TIMESTAMP('2024-11-07') AND report_time <= TIMESTAMP('2024-11-30') AND ci_url="https://github.com/camunda/camunda" AND NOT STARTS_WITH(runner_name, "github ")
), d AS (
  SELECT COUNT(*) as number_of_disconnected_runners_after
  FROM `ci-30-162810.prod_ci_analytics.build_status_v2`
  WHERE report_time >= TIMESTAMP('2024-11-07') AND report_time <= TIMESTAMP('2024-11-30') AND ci_url="https://github.com/camunda/camunda" AND NOT STARTS_WITH(runner_name, "github ") AND build_status="aborted"
)
SELECT
  SAFE_DIVIDE(b.number_of_disconnected_runners_before, a.number_of_all_runners_before) as selfhosted_runner_disconnect_rate_before,
  SAFE_DIVIDE(d.number_of_disconnected_runners_after, c.number_of_all_runners_after) as selfhosted_runner_disconnect_rate_after
FROM a,b,c,d
```
</details>

**Comment by cmur2** [comment]
I re-ran the query from this https://github.com/camunda/camunda/pull/24370#issuecomment-2476705428 again with more data after the experiment started:

* `selfhosted_runner_disconnect_rate_before` is ~1.2%
* `selfhosted_runner_disconnect_rate_after` is ~0.3%

Another confirmation that the experiment is successful. I will next backport this change also to `stable*` branches switching the preemptible self-hosted runners of affected GHA jobs to stable ones (this should get the total disconnect rate over the whole repo down even more).

**Pull request merged**
