### PR TITLE
fix(broker-core): close gateway before service containers

### LINKED ISSUE #1518: Can't close Gateway with ongoing requests
### Scenario:
 
 * Start a Broker with embedded Gateway
 * Create a Job
 * Create new Worker
 * Stop the broker with the Gateway
 * -> Deadlock Gateway can't be closed

```java
    clientRule.getJobClient().newCreateCommand().jobType("test").send().join();
    final RecordingJobHandler jobHandler = new RecordingJobHandler();
    clientRule.getJobClient().newWorker().jobType("test").handler(jobHandler).open();
    brokerRule.stopBroker();
```

If we remove line 2 and 3 it works.

### PR DESCRIPTION
**Pull request by miguelpires**
The gateway was being closed after the service containers so it would hang since these would never terminate. I separated the gateway's resource releasing delegate from the others, so we could close it before the service containers.
closes #1518

### CODE REVIEW

**Review by menski — CHANGES_REQUESTED** [review]
I think the fix is valid, but the test is not convincing. If I remove the code changes the test still passes on my machine. As in this case the broker request will timeout. After the fix the broker request normally is immediately rejected. In both cases a client exception is thrown.

In an ideal scenario we would be able to write a test where we can check that a pending request is successfully finished after graceful shutdown of the broker. But this is not trivial and requires a lot synchronization, which might not even possible.

I would also like to discuss a different solution approach, where we express the dependencies of the gateway using the service container, i.e. client API, maybe logstream, to let the service container figure out the correct order.

I will schedule a meeting for tomorrow to discuss this issue.

**Comment by npepinpe** [comment]
I'm not 100% sure that expressing the dependency of the gateway/broker here using the service container is the best idea, although it's a "cleaner" one. At the very least if we do we should be consistent and do the same for all the delegated resources (though that feels like abusing the service container).

It's definitely easier to test though, that's true.

**Comment by menski** [comment]
I pushed a proposal for a different test approach to this branch, see commit https://github.com/zeebe-io/zeebe/commit/aee74ac593e6fb344aecba22f8bef72b651a7890. It should check that a request will be completed before the broker is close.

**Review by menski — APPROVED** [review]

**Pull request merged**
