### PR TITLE
docs(clients/java): improve description of correlation key

### PR DESCRIPTION
**Pull request by falko**
...in order to avoid confusion of the API for first-time users.

## Description

Improve the JavaDoc of newPublishMessageCommand().correlationKey()

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by saig0** [comment]
Thank you, Falko :+1: 

Currently, the build complains the formatting of the file:

```
[ERROR] Found 1 non-complying files, failing build
[ERROR] To fix formatting errors, run "mvn com.coveo:fmt-maven-plugin:format"
[ERROR] Non complying file: /home/jenkins/agent/workspace/zeebe-io_zeebe_PR-3579/clients/java/src/main/java/io/zeebe/client/api/command/PublishMessageCommandStep1.java
``` 

Please run `mvn clean install -DskipTests` and update the PR.

**Comment by falko** [comment]
Formatting should be fixed now

**Review by saig0 — APPROVED** [review]
:+1: Thanks!

bors r+

**Comment by saig0** [comment]
bors retry

**Pull request merged**
