### PR TITLE
[Backport stable/8.0] Communicate success response for fail job with retry backoff 

### LINKED ISSUE #10612: FailJob with retry backoff response is not communicated to client
**Describe the bug**

This bug only exists on 8.0.x and 1.3.x, as it was already fixed in:
- https://github.com/camunda/zeebe/pull/9389

Specifically, the response writer's flush is overwritten. So the response is not communicated. This was fixed in a7195f7750670e41ac0e42da8d170ffedfed9757.

**To Reproduce**

Use the new java client (> 8.1) or the nodejs client to fail a job with a retry backoff that exceeds the gateway-broker request timeout. Notice that the client's request is responded with a timeout exceeded error.

**Expected behavior**

The FailJob request should be responded to immediately with a successful response.

### PR DESCRIPTION
**Pull request by korthout**
## Description

Fixes a bug in `8.0` already fixed in `8.1+`: 
- #10612 

When a user tries to [fail a job](https://docs.camunda.io/docs/apis-tools/grpc/#failjob-rpc) with retries backoff exceeding the gateway request timeout, then that request is not responded to. The job was already correctly failed, but the response was not sent. This happened because the response writer's flush is overwritten.

This bug was already fixed in a7195f7 but was never backported to 8.0.

Cherrypicking happened without conflicts.

## Testing
This bug cannot be tested with code because it requires a newer client, i.e. one that supports failing a job with a retry backoff. Failing a job with a retry backoff was added in Zeebe 8.0, but only in [8.1 of the java client](https://github.com/camunda/zeebe/commit/78f67ef0d2fb1070e2a7b37d7ab47a46a7f782d6).

So, to reproduce the bug and test the bug fix, we need to do so manually.

### Manual reproduction
- run Zeebe broker `8.0.13`
- activate a job:
```sh
$ zbctl --insecure deploy resource ~/bpmn/one_servicetask.bpmn
{
  "key":  "2251799813685250",
  "deployments":  [
    {
      "process":  {
        "bpmnProcessId":  "onetask",
        "version":  1,
        "processDefinitionKey":  "2251799813685249",
        "resourceName":  "/Users/korthout/bpmn/one_servicetask.bpmn"
      }
    }
  ]
}

$ zbctl --insecure create instance onetask
{
  "processDefinitionKey":  "2251799813685249",
  "bpmnProcessId":  "onetask",
  "version":  1,
  "processInstanceKey":  "2251799813685251"
}

$ zbctl --insecure activate jobs task
{
  "jobs":  [
    {
      "key":  "2251799813685256",
      "type":  "task",
      "processInstanceKey":  "2251799813685251",
      "bpmnProcessId":  "onetask",
      "processDefinitionVersion":  1,
      "processDefinitionKey":  "2251799813685249",
      "elementId":  "Activity_0q59ktq",
      "elementInstanceKey":  "2251799813685255",
      "customHeaders":  "{}",
      "worker":  "zbctl",
      "retries":  3,
      "deadline":  "1681897403707",
      "variables":  "{}"
    }
  ]
}
```
- fail the job with retry backoff (30s) exceeding the gateway request timeout (15s) using zbctl 8.2.1 
```sh
$ zbctl --insecure fail job 2251799813685256 --retryBackoff 30s --retries 2
Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
- notice the Error in the response (this response was sent after 15s, i.e. the gateway request timed out)

### Manual bugfix test
- run Zeebe broker at 9b8124393b
- activate a job:
```sh
$ zbctl --insecure deploy resource ~/bpmn/one_servicetask.bpmn
{
  "key":  "2251799813685250",
  "deployments":  [
    {
      "process":  {
        "bpmnProcessId":  "onetask",
        "version":  1,
        "processDefinitionKey":  "2251799813685249",
        "resourceName":  "/Users/korthout/bpmn/one_servicetask.bpmn"
      }
    }
  ]
}

$ zbctl --insecure create instance onetask
{
  "processDefinitionKey":  "2251799813685249",
  "bpmnProcessId":  "onetask",
  "version":  1,
  "processInstanceKey":  "2251799813685251"
}

$ zbctl --insecure activate jobs task
{
  "jobs":  [
    {
      "key":  "2251799813685256",
      "type":  "task",
      "processInstanceKey":  "2251799813685251",
      "bpmnProcessId":  "onetask",
      "processDefinitionVersion":  1,
      "processDefinitionKey":  "2251799813685249",
      "elementId":  "Activity_0q59ktq",
      "elementInstanceKey":  "2251799813685255",
      "customHeaders":  "{}",
      "worker":  "zbctl",
      "retries":  3,
      "deadline":  "1681897403707",
      "variables":  "{}"
    }
  ]
}
```
- fail the job with retry backoff (30s) exceeding the gateway request timeout (15s) using zbctl 8.2.1 
```sh
$ zbctl --insecure fail job 2251799813685256 --retryBackoff 30s --retries 2
Failed job with key '2251799813685256' and set remaining retries to '2' and variables '{}' with retry backoff '30s'
```
- notice that the response is now sent correctly (and immediately)

## Related issues

closes #10612 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by saig0 — APPROVED** [review]
@korthout LGTM. :rocket: 

bors merge

**Comment by korthout** [comment]
Known flaky test:
- https://github.com/camunda/zeebe/issues/11844

bors merge

**Comment by korthout** [comment]
Same flaky test...

bors merge

**Comment by saig0** [comment]
bors merge

**Pull request merged**
