### PR TITLE
refactor : replace org.json by jakarta.json

### LINKED ISSUE #17660: Replace org.json by jakarta.json
### Description
Replace `org.json:json` usage by the standard `jakarta.json-api` library

### PR DESCRIPTION
**Pull request by ashishbania**
Replace org.json by jakarta.json closes #17660

## Description
The changes are to address the org.json removal from the app

## Related issues

closes # 17660

### CODE REVIEW

**Comment by houssain-barouni** [comment]
Hi @ashishbania , thank you for your contribution, really appreciated.
Can you please follow the commit message guidelines as explained [here](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#commit-message-header) ?
Thank you,

**Comment by ashishbania** [comment]
> Hi @ashishbania , thank you for your contribution, really appreciated. Can you please follow the commit message guidelines as explained [here](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#commit-message-header) ? Thank you,

Thanks! I have followed the commit guidelines and made further commits adhering to them.

**Comment by ashishbania** [comment]
> > Hi @ashishbania , thank you for your contribution, really appreciated. Can you please follow the commit message guidelines as explained [here](https://github.com/camunda/camunda/blob/main/CONTRIBUTING.md#commit-message-header) ? Thank you,
> 
> Thanks! I have followed the commit guidelines and made further commits adhering to them.

Hi @houssain-barouni Please review the PR.

**Comment by houssain-barouni** [comment]
Hi @ashishbania can you please solve the conflicting files, so that the CI gets triggered ?

**Review by houssain-barouni — COMMENTED** [review]
Merge conflicts resolution required

**Comment by ashishbania** [comment]
> Hi @ashishbania can you please solve the conflicting files, so that the CI gets triggered ?

HI, @houssain-barouni I will address this tonight and attempt CI.

**Comment by ashishbania** [comment]
> Merge conflicts resolution required

Addressed the conflicts now.

**Comment by houssain-barouni** [comment]
Hello @ashishbania,

The source code for Operate and Tasklist was recently made public. However, the CI pipelines are not yet ready for external contributions, meaning we cannot properly run the CIs of pull requests made from forks. For more details, please see #19222.

As a workaround, I can create another pull request on your behalf with the same changes. I will reference your pull request and credit you for the external contribution.

Please let me know if this is acceptable. Apologies for the inconvenience.

**Comment by ashishbania** [comment]
> Hello @ashishbania,
> 
> The source code for Operate and Tasklist was recently made public. However, the CI pipelines are not yet ready for external contributions, meaning we cannot properly run the CIs of pull requests made from forks. For more details, please see #19222.
> 
> As a workaround, I can create another pull request on your behalf with the same changes. I will reference your pull request and credit you for the external contribution.
> 
> Please let me know if this is acceptable. Apologies for the inconvenience.

Please go ahead @houssain-barouni .

**Comment by houssain-barouni** [comment]
A new pull request containing these changes + some updates is created https://github.com/camunda/camunda/pull/19279

**Pull request closed without merging**
