### PR TITLE
Release 8.4.0

### PR DESCRIPTION
**Pull request by camundait**
Merge the release branch with main. This pull request was created by Zeebe :rocket:.

### CODE REVIEW

**Comment by oleschoenburg** [comment]
I think the target branch should have been stable/8.4 not main.

**Comment by deepthidevaki** [comment]
> I think the target branch should have been stable/8.4 not main.

No this must to main. The snapshot version is set to 8.5.0-SNAPSHOT.

**Review by deepthidevaki — APPROVED** [review]
bors r+

**Comment by deepthidevaki** [comment]
The build fails because there is a backward incomatible change to protocol that was added after the code-freeze. 

```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.15.0:check (check) on project zeebe-protocol: The following API problems caused the build to fail:
[ERROR] java.method.returnTypeChanged: method java.lang.String io.camunda.zeebe.protocol.record.value.CompensationSubscriptionRecordValue::getCompensableActivityScopeId(): The return type changed from 'long' to  'java.lang.String'.
[ERROR] java.method.removed: method io.camunda.zeebe.protocol.record.value.ImmutableCompensationSubscriptionRecordValue.Builder io.camunda.zeebe.protocol.record.value.ImmutableCompensationSubscriptionRecordValue.Builder::withCompensableActivityScopeId(long): Method was removed.
[ERROR] java.method.returnTypeChanged: method java.lang.String io.camunda.zeebe.protocol.record.value.ImmutableCompensationSubscriptionRecordValue::getCompensableActivityScopeId(): The return type changed from 'long' to  'java.lang.String'.
[ERROR] java.method.removed: method io.camunda.zeebe.protocol.record.value.ImmutableCompensationSubscriptionRecordValue io.camunda.zeebe.protocol.record.value.ImmutableCompensationSubscriptionRecordValue::withCompensableActivityScopeId(long): Method was removed.
```

@nicpuppa I think https://github.com/camunda/zeebe/commit/21feedf0ec80e375df7593438a198caaeec2bde7 is causing the issue. Can you check it? If it is ok to break compatibility for this version (for example, this feature was not released as part of 8.4), we can configure revapi to ignore this.

**Comment by nicpuppa** [comment]
> @nicpuppa I think [21feedf](https://github.com/camunda/zeebe/commit/21feedf0ec80e375df7593438a198caaeec2bde7) is causing the issue. Can you check it? If it is ok to break compatibility for this version (for example, if this feature was not released as part of 8.4), we can configure revapi to ignore this.

Hey @deepthidevaki sorry for the late reply, I didn't see it. This feature is not released yet, I'm wondering why I didn't have this error before

**Comment by deepthidevaki** [comment]
>  I'm wondering why I didn't get this error before

It was checking the compatibility with 8.3 so far. Since this is a new one added after 8.3, it did not fail the check. But now it was added in 8.4, but changed after the code-freeze. 

If it is not released in 8.4, we can safely ignore this breaking change. To pass the build, there are ways to tell revapi to ignore this breaking change. Can you check documentation of revapi on how to do it? Please check `revapi.json` in `protocol` module for reference.

> What are the next steps?

Push a commit to this branch that ignores this breaking change in revapi. Once the built passes, we can merge this branch.

**Comment by nicpuppa** [comment]
I pushed a commit with revapi extensions updated, can you have a look @deepthidevaki ? 👀 🚀

**Comment by deepthidevaki** [comment]
Thanks @nicpuppa . Now the build fails because of a flaky test. So I will merge this PR.

**Comment by deepthidevaki** [comment]
bors merge

**Pull request merged**
