### PR TITLE
ci: yarn install mutex on all yarn 1.x usages

### PR DESCRIPTION
**Pull request by megglos**
## Description

Yarn 1.x doesn't seem to play well with concurrent processes accessing the same cache. See https://github.com/yarnpkg/yarn/issues/2629#issuecomment-480535595 .

I didn't touch the identity frontend as this uses the new yarn >2.x, which according to https://yarnpkg.com/configuration/yarnrc  doesn't have concurrency issues "The cache is deemed to be relatively safe to be shared by multiple projects, even when multiple Yarn instances run at the same time on different projects. "

With now having 4 frontend modules with yarn 1.x which potentially build in parallel on multi-threaded maven builds, I noticed cache file issues e.g. here https://github.com/camunda/camunda/actions/runs/12480775858/job/34832175681 or here 
https://github.com/camunda/camunda/actions/runs/12475426337/job/34818808394

Effectively the QA workflow fails since last week because of such issues https://github.com/camunda/camunda/actions/workflows/zeebe-qa-testbench.yaml?query=branch%3Amain

```
[INFO] error Error: ENOTEMPTY: directory not empty, rmdir '/home/runner/.cache/yarn/v6/npm-lodash-4.17.21-679591c564c3bffaae8454cf0b3df370c3d6911c-integrity/node_modules/lodash'
```

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

closes #

### CODE REVIEW

**Comment by megglos** [comment]
Testrun https://github.com/camunda/camunda/actions/runs/12482238300

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
Thanks for the changes 🙌 
Lets see the test run 👀 
So this only lets each build access the cache one at a time?

**Comment by megglos** [comment]
> Thanks for the changes 🙌 Lets see the test run 👀 So this only lets each build access the cache one at a time?

Exactly, it makes sure there is only one concurrent [yarn install running (which potentially modifies the cache)](https://classic.yarnpkg.com/lang/en/docs/cli/#toc-concurrency-and-mutex).

**Comment by cmur2** [comment]
Related to https://github.com/camunda/camunda/issues/26327

**Comment by cmur2** [comment]
/backport

I'm not 100% sure we need to backport this but I'll try for consistency.

**Pull request merged**
