### PR TITLE
fix: change local address to use localhost instead of machine name to solve tests failing locally on MacOS

### LINKED ISSUE #18871: `NettyMessagingServiceCompressionTest` tests fail to run locally
**Summary**

The tests fail locally with the following error if run from intellij
```
java.util.concurrent.CompletionException: io.atomix.cluster.messaging.MessagingException$ConnectionClosed: Channel [id: 0x289446b0] for address Mustafas-MacBook-Pro.local:1026 was closed unexpectedly before the request was handled

Caused by: io.atomix.cluster.messaging.MessagingException$ConnectionClosed: Channel [id: 0x289446b0] for address Mustafas-MacBook-Pro.local:1026 was closed unexpectedly before the request was handled
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$bootstrapClient$40(NettyMessagingService.java:772)
```

and if run from mvn, the build gets stuck forever until manually canceled

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description
change local address to use localhost instead of machine name to solve tests failing locally on MacOS

## Related issues

closes #18871

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:thought_balloon: Possibly in general using `InetAddress.getLocalHost()` as the default host in `Address` is wrong, and we should instead default to `localhost`. Not a blocker here, just a thought. wdyt @oleschoenburg ?

I think we can go ahead and merge to unblock, but we may want to fix it at the root as well, if you feel confident ;) Otherwise we can merge and ZDP can fix at the root :+1:

**Comment by mustafadagher** [comment]
> 💭 Possibly in general using `InetAddress.getLocalHost()` as the default host in `Address` is wrong, and we should instead default to `localhost`. Not a blocker here, just a thought. wdyt @oleschoenburg ?
> 
> I think we can go ahead and merge to unblock, but we may want to fix it at the root as well, if you feel confident ;) Otherwise we can merge and ZDP can fix at the root 👍

I can possibly change it, but could you explain a bit more why is it wrong to be used there?

**Comment by npepinpe** [comment]
AFAIK, InetAddress#getLocalHost will query the kernel for the hostname, which may not be resolvable (see Ole's example). It may be a better default behavior to just always use localhost or the loopback address as default. But looking at the code again, it looks like we are already doing that in a way - if we failed to resolve the local host, we would fallback to loopback. So either getLocalHost doesn't actually try to resolve as documented, or something else is going on...

**Comment by mustafadagher** [comment]
I added this to the merge queue now, we can continue to improve the rest of the functionality in another PR.

**Pull request merged**
