### PR TITLE
[Backport stable/8.1] deps(maven): bump testcontainers-bom from 1.17.6 to 1.18.0

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Backport of #12251 to get rid of the AWS SDK v1

### CODE REVIEW

**Comment by npepinpe** [comment]
Seems like network issues again :thinking:

**Review by npepinpe — APPROVED** [review]
:+1:

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
bors merge

**Comment by npepinpe** [comment]
I don't think the issue is the concurrency. I noticed on stable/8.1 we have errors with the private registry, but haven't had time to look into it. That said, it could be the error is a red herring. 

```
 {"message":"error with private registry proxying: unable to retag temporary image","code":500}
```

The private registry is a pull through cache, so you shouldn't be able to modify images directly on it, hence the error. But I don't really get why this would be happening, and why only on 8.1. Another PR for that branch had the same problem :thinking:

**Comment by oleschoenburg** [comment]
The first time this PR passes CI is when I increase concurrency to 4 though :thinking: 

Do you want to look into this together? I'm not sure where to start here.

**Comment by npepinpe** [comment]
Sure. If it temporarily fixes it, we can increase it again, and delegate the issue to them. It's also weird how it affects only one branch. What exactly is trying to retag an image here? 

It could also be an issue on their side? For all I know, they might have their own pull through cache on their side, or they might be trying to do stuff with the private registry :shrug:

**Comment by npepinpe** [comment]
In the other PR where this was failing, normal CI was passing, but merging was not :shrug:

**Pull request merged**
