### PR TITLE
docs(all): remove documentation after migration to new repo

### LINKED ISSUE #5575: Remove documentation after migration to new location
**Description**

As part of the documentation consolidation all documentation will be moved to another repository. Therefore, documentation in this repository shall be removed.

### PR DESCRIPTION
**Pull request by pihme**
## Description

Removes documentation and build steps related to it.

## Related issues

closes #5575 

## Definition of Done

Code changes:
* [X] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [X] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [X] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by menski** [comment]
We still have to clarify what should happen with https://docs.zeebe.io. But one thing we could do here, is instead of deleting the `docs/src/.htaccess` file, we could add a wildcard redirect to the new docs URL so people with old URLs at least can easily discover the new URL.

What do you think @pihme and @npepinpe? I'm happy to help with the Apache syntax for the redirect URL.

**Comment by pihme** [comment]
@menski I would rather upload this as a static file to the web server. I don't see much added value in pushing the redirect as part of the build and would rather simplify the build pipeline instead.

**Review by npepinpe — CHANGES_REQUESTED** [review]
Could you migrate all the BPMN files to the correct Google Drive folder (https://drive.google.com/drive/folders/1PSo7T8H14T6rs0y0leXiq2WySqx82Bcs?usp=sharing)? It's not ideal for these kind of files, but we can figure a better solution in the long term. Those should be the only files that are only present in the media-src folder.

EDIT: actually @saig0 suggested keeping them in our Git repo since it's better for maintenance and collab. We could keep the docs folder with just the bpmns under? Or rename docs to docs-media? wdyt @saig0 ?

**Comment by pihme** [comment]
@npepinpe / @saig0 Just let me know where you want to keep the files

**Comment by saig0** [comment]
@npepinpe I don't want to keep the BPMNs in our repo. They should be moved to the new cloud docs repo. For example, next to the generated images in the BPMN sections.

**Comment by npepinpe** [comment]
I'm not familiar with the new repo structure - we should ask @urbanisierung if there's anything planned for this yet, otherwise we can come up with an arrangement.

**Comment by pihme** [comment]
Added all files from media-src to new repo

**Review by npepinpe — APPROVED** [review]
Thanks :tada:

**Comment by saig0** [comment]
FYI: New PR that will add docs for `0.25`.

**Comment by pihme** [comment]
@menski friendly reminder :-)

**Comment by pihme** [comment]
Force pushed new version after rebase and to account for PR #5534

**Comment by saig0** [comment]
Let's wait until the docs for `0.25.0` are published :sweat_smile:

**Comment by npepinpe** [comment]
afaik it's been released now (@MiguelPires correct me if I'm wrong, but I guess we released the new docs when releasing 0.25?), so we could go ahead with this. Was the new upgrade doc migrated as well (referring to this https://docs.zeebe.io/operations/upgrade.html)?

**Comment by pihme** [comment]
@npepinpe Yes, the upgrade guide was migrated but has not been merged or published.

**Comment by pihme** [comment]
Anyways, I see no issue with pushing this because part of the change set is that the build step to publish documentation is also removed. So whatever is published now stays published.

**Pull request merged**
