### PR TITLE
refactor(qa): migrate management endpoint to new infra

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR migrates integration tests for various actuator endpoints to the new testing infrastructure.

## Related issues

related to #14377 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by rodrigo-lourenco-lopes — APPROVED** [review]
LGTM! Thanks 🙌

**Comment by rodrigo-lourenco-lopes** [comment]
bors merge

**Comment by megglos** [comment]
@rodrigo-lourenco-lopes please check if the flaky tests are changed ones and/or known flakes

**Comment by rodrigo-lourenco-lopes** [comment]
bors retry

**Comment by oleschoenburg** [comment]
@rodrigo-lourenco-lopes there's no sense in retrying, the java checks are failing because of dependency problems: https://github.com/camunda/zeebe/actions/runs/6340802700/job/17223025073

**Comment by rodrigo-lourenco-lopes** [comment]
bors merge

**Comment by rodrigo-lourenco-lopes** [comment]
bors retry

**Comment by rodrigo-lourenco-lopes** [comment]
bors retry

**Comment by npepinpe** [comment]
Thanks @rodrigo-lourenco-lopes, I'll look into it. Sorry for the inconvenience :sweat_smile:

**Comment by npepinpe** [comment]
So it looks to me like sometimes rebalancing simply doesn't result in the expected state. You can see that it calls it properly, but then 2 is elected leader of partition 1 and partition 2 again :thinking:

**Comment by npepinpe** [comment]
bors merge

**Comment by npepinpe** [comment]
bors r+

The test node disconnected in the middle :shrug:

**Pull request merged**
