### PR TITLE
Correctly detect if Epoll is available

### LINKED ISSUE #6247: Can't build executable broker on Mac OS
**Description**

I packaged projects successfully on Mac OS, in the process of running, get the following error:

```
java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:80) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:51) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:150) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[netty-common-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[netty-transport-4.1.58.Final.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:112) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:99) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:76) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.initEventLoopGroup(NettyMessagingService.java:317) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.start(NettyMessagingService.java:244) ~[atomix-cluster-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.Broker.commandApiTransportStep(Broker.java:284) ~[zeebe-broker-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.Broker.lambda$initStart$1(Broker.java:209) ~[zeebe-broker-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.lambda$startStepByStep$2(StartProcess.java:63) ~[zeebe-broker-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.startStepByStep(StartProcess.java:61) ~[zeebe-broker-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.takeDuration(StartProcess.java:92) ~[zeebe-broker-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.bootstrap.StartProcess.start(StartProcess.java:46) ~[zeebe-broker-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.Broker.internalStart(Broker.java:180) ~[zeebe-broker-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.util.LogUtil.doWithMDC(LogUtil.java:21) ~[zeebe-util-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.Broker.start(Broker.java:160) ~[zeebe-broker-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at io.zeebe.broker.StandaloneBroker.run(StandaloneBroker.java:60) ~[zeebe-distribution-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.2.jar:2.4.2]
	at io.zeebe.broker.StandaloneBroker.main(StandaloneBroker.java:47) [zeebe-distribution-0.27.0-SNAPSHOT.jar:0.27.0-SNAPSHOT]
Caused by: java.lang.ExceptionInInitializerError
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	... 29 more
Caused by: java.lang.IllegalStateException: Only supported on Linux
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:244) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.Native.<clinit>(Native.java:69) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39) ~[netty-transport-native-epoll-4.1.58.Final-linux-x86_64.jar:4.1.58.Final]
	... 29 more
```

Related topic in the forum: https://forum.zeebe.io/t/source-code-package-success-run-failure/1984/2

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR fixes Epoll detection in `NettyMessagingService`, which prevents the broker from running correctly on non-Linux OSes. There are no automated tests as we don't have the infrastructure to run tests on multiple platforms.

## Related issues

closes #6247 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
This was broken on the 14th, so after the 0.26 release, so nothing to backport.

**Comment by npepinpe** [comment]
@korthout and @pihme can you quickly confirm the broker starts correctly on Mac and Windows? Thanks!

**Comment by korthout** [comment]
@npepinpe verified problem and fix on macOS

```
git fetch
git checkout 6247-netty-transport-fix
git checkout head^
mvn clean install
./dist/target/zeebe-broker/bin/broker
ERROR
git checkout 6247-netty-transport-fix
mvn clean install
./dist/target/zeebe-broker/bin/broker
SUCCESS
```

**Review by pihme — APPROVED** [review]
Starts and shuts down properly on Windows.

**Review by deepthidevaki — APPROVED** [review]
LGTM :+1:

**Comment by npepinpe** [comment]
So my mistake, this needs to be backported because whatever broke it on the 14th, was then later backported to the 0.26 branch.

**Pull request merged**
