### PR TITLE
Replace go-bindata with go's embed FS

### LINKED ISSUE #6034: Remove go-bindata after Go1. 16
**Description**

Go 1.16 will have native support for embedding files so, after updating, we can use that and remove go-bindata as a dependency.
https://tip.golang.org/doc/go1.16

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

Took some slack time to complete this quick win: replaces usage of go-bindata, an external tool dependency, with the built-in capabilities of the go compiler using `go:embed` and the
embedFS.

The version file is embedded at build time into the binary, much like when we used go-bindata, and read back as a package field.

## Related issues

closes #6034 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by korthout — APPROVED** [review]
Thanks @npepinpe 

LGTM 👍 

❓ Should the vendoring be updated?

**Comment by npepinpe** [comment]
The tool was not previously vendored, as there's no easy way to vendor tools apart from dependencies. So AFAIK nothing to be done there.

**Comment by npepinpe** [comment]
bors r+

Weird that bors is not retrying it.

**Comment by rodrigo-lourenco-lopes** [comment]
bors retry

**Comment by korthout** [comment]
This one crashed Bors yesterday. @npepinpe check the [history](https://bors-camunda.zeebe.camunda.cloud/repositories/2/log) and go back to yesterday evening.

Should we retry this?

**Comment by korthout** [comment]
@npepinpe missed opportunity to call this branch `remove-goblindata`

**Comment by npepinpe** [comment]
rebased, let's see if that works

bors r+

**Pull request merged**
