### PR TITLE
refactor: rename decision instance fields

### PR DESCRIPTION
**Pull request by houssain-barouni**
## Description

- rename `DecisionInstance` fields, in client and service module, as following:
  - `decisionKey` -> `decisionDefinitionKey`
  - `dmnDecisionId` -> `decisionDefinitionId`
  - `dmnDecisionName` -> `decisionDefinitionName`
  - `decisionVersion` -> `decisionDefinitionVersion`
  - `decisionKey` -> `decisionDefinitionKey`
  - `decisionType` -> `decisionDefinitionType`
- rename `DecisionInstanceTypeEnum` to  `DecisionDefinitionTypeEnum`
- remove the use of protocol enums in client interface => create `DecisionDefinitionType` and `DecisionInstanceType` enums in client model, and add mapping to/from protocol enums

## Checklist

- [ ] for CI changes:
  - [ ] structural/foundational changes signed off by [CI DRI](https://github.com/cmur2)
  - [ ] [ci.yml](https://github.com/camunda/camunda/blob/main/.github/workflows/ci.yml) modifications comply with ["Unified CI" requirements](https://github.com/camunda/camunda/wiki/CI-&-Automation#workflow-inclusion-criteria)

## Related issues

relates to https://github.com/camunda/camunda/issues/22716

### CODE REVIEW

**Comment by nicpuppa** [comment]
❓ If we are dealing with a `decision instance` object, should the fields related to it be named `decisionInstance*`. Same as we have `processDefinition*` and `processInstance*` ?

cc @tmetzke

**Comment by tmetzke** [comment]
> ❓ If we are dealing with a `decision instance` object, should the fields related to it be named `decisionInstance*` ? Same as we have `processDefinition*` and `processInstance*
> 
> cc @tmetzke

Only `key` and `id` fields necessarily, so it's easy to see what this refers to (itself or another entity). Anything else could have no prefix at all if it is a property of the decision instance itself, e.g. an evaluation result or whatever.

**Comment by mihail-ca** [comment]
> ❓ If we are dealing with a `decision instance` object, should the fields related to it be named `decisionInstance*` ? Same as we have `processDefinition*` and `processInstance*
> 
> cc @tmetzke

FYI it is explained here: [Naming Conventions](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.vy58f5kwk0b4)

**Comment by nicpuppa** [comment]
> FYI it is explained here: [Naming Conventions](https://docs.google.com/document/d/1rS989EESojWRrCMLH7Nscy1UppbgOanvzVeOljCc_iA/edit#heading=h.vy58f5kwk0b4)

Ok, so looking at the Naming convention. The proposal is fine then. Because the `id` and the `key` are coming from the decision definition

**Review by nicpuppa — APPROVED** [review]

**Comment by tmetzke** [comment]
@houssain-barouni, does this need a rebase due to the changes the RDBMS stream merged (I think on Friday)?

**Comment by houssain-barouni** [comment]
> @houssain-barouni, does this need a rebase due to the changes the RDBMS stream merged (I think on Friday)?

Yes, I am on it

**Pull request merged**
