### PR TITLE
Enable new transition steps

### LINKED ISSUE #7515: Improve Follower-Leader transition performance
**Description**

This is part of the [ZEP 0007](https://github.com/zeebe-io/enhancements/blob/master/ZEP007-build-state-on-followers.md)

Main goal of this ZEP is to reduce the time the new Leader needs to start processing. We want to reduce the impact on process instance execution latency, which a fail-over has.

This can be shown in the with the following Seq Diagram

The ZEP targets the range the ZeebePartition is called with the Leader Role event until the StreamProcessor starts processing. 

Part of this issue is to stop recreating the runtime folder from the last snapshot, ideally we also stop to recreate the Database object and reuse it from the Follower. **Important:** We need to make sure that we still reset the runtime db on transition from Leader to follower.

Blocked by https://github.com/camunda-cloud/zeebe/issues/7513

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

* Enable new transition steps
* Fix some bugs in the new transition
* Some refactoring and cleanups
* Fix tests that failed after enabling the new transition

This PR does not yet delete the old code. This will be done in a followup.

## Related issues

closes #7515 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by deepthidevaki** [comment]
@pihme It might help to review this PR commit by commit.

**Review by pihme — APPROVED** [review]
Looks great! :tada: 

:thought_balloon: The one thing I keep thinking about is that it  would be safer to have one instance of the steps per partition. The steps are intended to be stateless, but this is not yet well documented. Sharing the steps across partitions only adds risk that something gets messed up. 

But this is more a topic for follow up development. Would love to hear your thoughts. Especially after your changes to the `StreamProcessorTransitionStep`.

**Comment by deepthidevaki** [comment]
Thanks for the fast review. @pihme 

> thought_balloon The one thing I keep thinking about is that it would be safer to have one instance of the steps per partition. The steps are intended to be stateless, but this is not yet well documented. Sharing the steps across partitions only adds risk that something gets messed up.
> 
> But this is more a topic for follow up development. Would love to hear your thoughts. Especially after your changes to the `StreamProcessorTransitionStep`.

Not sharing the instances across partition is a good idea. That might also help us to do some more things in the steps - such as what to do if previous transition failed. That would probably address your concerns that you raised in the previous PR. What would happen if Leader to Follower transition fails. As a result the step transition from Leader to Candidate skipping the intermediate transition Leader -> Follower -> Candidate.

**Comment by Zelldon** [comment]
bors cancel

**Comment by Zelldon** [comment]
I feel this PR causes an CI timeout, seems some IT test get stuck.

**Comment by deepthidevaki** [comment]
Then we can cancel bors for this PR. I will take a look next week.

**Comment by pihme** [comment]
bors retry

**Comment by npepinpe** [comment]
Strange, it seemed stuck but the process wasn't do anything. A quick `top` on the container revealed it was just idling? :thinking:

**Comment by deepthidevaki** [comment]
> Strange, it seemed stuck but the process wasn't do anything. A quick `top` on the container revealed it was just idling? thinking
> 
> EDIT: ah, just the saw the commit sweat_smile

The test was stuck at that future, although I couldn't find out what failed. Now I added timeout to the future join. I hope now the test will fail fast and it will be easier to see why the future never completed.

**Comment by deepthidevaki** [comment]
The test was passing on the branch. Let me try merging again.

bors r+

**Comment by pihme** [comment]
bors retry

**Comment by Zelldon** [comment]
bors r- 

I would prefer that we fix the IT test or the bug, if there is one hiding before we merge that again and affect all others.

**Comment by Zelldon** [comment]
Or are we sure that we not introduced that with that PR ? @deepthidevaki @pihme if so I'm sorry

**Comment by pihme** [comment]
Started three builds to try and figure out whether any flaky test is more flaky: https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/dd-use-new-transition/

**Comment by deepthidevaki** [comment]
Doesn't seem to be related to this PR. Tests unrelated to this PR (like AtomixTransportTest) are flaky.

**Comment by pihme** [comment]
I agree with Deepthi. I don't think it's related to the changes. However, I have been wrong in these matters before.

**Comment by deepthidevaki** [comment]
Merge of another PR also fails due to unrelated IT tests. https://ci.zeebe.camunda.cloud/blue/organizations/jenkins/camunda-cloud%2Fzeebe/detail/staging/1094/tests

**Comment by deepthidevaki** [comment]
I'm going to try merging again and see if there are any repeatedly failing tests. 

bors r+

**Comment by deepthidevaki** [comment]
Fix for flaky AtomixTransportTest https://github.com/camunda-cloud/zeebe/pull/7863

**Pull request merged**
