### PR TITLE
refactor: move zeebe java client from zeebe sub-folder

### LINKED ISSUE #19480: Move the java client from `zeebe` sub-folder to the root
Move the actual `zeebe java client` from `zeebe` sub-folder into a new `/client` folder at root level

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

In order to make the java client more generic, we need to move the zeebe java client from the zeebe sub-folder into a new folder under the root

## Related issues

closes #19480

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
👍 Looks good to me, make it move 🚚📦

**Comment by tmetzke** [comment]
@nicpupp, the Spring SDK build is actually broken, that is why the merge doesn't work 🙂

**Comment by tmetzke** [comment]
@nicpuppa, the Spring SDK build is actually broken, that is why the merge doesn't work 🙂

**Comment by nicpuppa** [comment]
> @nicpuppa, the Spring SDK build is actually broken, that is why the merge doesn't work 🙂

Mmmmm, why was not triggered in the actual PR but only in the Merge Queue ? Let me check

**Pull request merged**
