### PR TITLE
chore(ci): send slack notification for chaos tests

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Sends notification to slack instead of mails for changed Zeebe Chaos build status.

### CODE REVIEW

**Comment by Zelldon** [comment]
Hey @cmur2 I just copied your work from the other pipelines. I hope this works also on this pipline or do I need something else?

**Review by cmur2 — APPROVED** [review]
It should work as well and doesn't need any other configuration in the pipeline (similar to the `emailext` instruction) :+1:

**Comment by Zelldon** [comment]
Awesome thanks @cmur2

**Pull request merged**
