### PR TITLE
fix(qa/util): do not wait forever for cluster startup

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Some qa tests are timing out. The reason is not known because the logs are not available when it timesout. But the assumption is that it waits for the cluster startup. To interrupt the waiting, we add an arbitrary limit of 3 minutes for the cluster startup. This helps to collect the logs and root cause it.

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
Bors r+ 

:+1:

**Comment by deepthidevaki** [comment]
This didn't help. IT tests still timed-out.

```
[[IT] QA Integration Tests](https://github.com/camunda/zeebe/actions/runs/6929554263/job/18847485812)
The job running on runner actions-runner-amd64-16-lcj48-f77xh has exceeded the maximum execution time of 20 minutes.
```

**Comment by npepinpe** [comment]
The missing logs on time out will be fixed via #14781

**Comment by deepthidevaki** [comment]
With Nicolas' PR #14781 we can now see the logs from the timed out jobs. Investigating one such failure #15343 it is not stuck on startup. This PR is not improving the situation. So I'm closing this.

**Pull request closed without merging**
