### PR TITLE
Close actor scheduler in ClusteringRule

### LINKED ISSUE #7841: JVM crashs in CI Builds
**Description**

It seems that we have again some SIGSEG issues, which causes to crash the JVM in our CI.

It downloaded the test errors zip from the following build https://ci.zeebe.camunda.cloud/job/camunda-cloud/job/zeebe/job/develop/821/ 
```
$ unzip test-errors-it.zip 
Archive:  test-errors-it.zip
  inflating: qa/integration-tests/hs_err_pid6859.log  
  inflating: qa/integration-tests/hs_err_pid6860.log  
$ cd qa/integration-tests/
$ ll
total 8
-rw-r--r-- 1 zell users 3144 Sep 16 15:13 hs_err_pid6859.log
-rw-r--r-- 1 zell users  396 Sep 16 15:10 hs_err_pid6860.log
$ cat hs_err_pid6860.log 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1975573435, pid=6860, tid=57545
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.10+9) (build 11.0.10+9)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.10+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [librocksdbjni4887027544215651946.so+0x395435][zell integration-tests/ cluster: tf-jx-precise-humpback ns:jx]$ 
```

```
$ cat hs_err_pid6859.log 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8e41d86821, pid=6859, tid=61320
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.10+9) (build 11.0.10+9)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.10+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x82821]
[timeout occurred during error reporting in step "printing problematic frame"] after 30 s.
# Core dump will be written. Default location: /core.%e.6859.%t
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -XX:+UseContainerSupport -XX:MaxRAMPercentage=8 -XX:MaxDirectMemorySize=4g -Djava.net.preferIPv4Stack=true --module-path=/home/jenkins/agent/workspace/camunda-cloud_zeebe_develop/qa/integration-tests/target/zeebe-qa-integration-tests-1.2.0-SNAPSHOT.jar --patch-module=zeebe.qa.integration.tests=/home/jenkins/agent/workspace/camunda-cloud_zeebe_develop/qa/integration-tests/target/test-classes --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.client=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.client.command=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.client.multipartition=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.clustering=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.clustering.topology=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.gateway=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.health=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.network=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.smoke=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.startup=ALL-UNNAMED --add-exports=zeebe.qa.integration.tests/io.camunda.zeebe.it.system=ALL-UNNAMED --add-modules=zeebe.qa.integration.tests --add-reads=zeebe.qa.integration.tests=ALL-UNNAMED org.apache.maven.surefire.booter.ForkedBooter /home/jenkins/agent/workspace/camunda-cloud_zeebe_develop/qa/integration-tests/target/surefire 2021-09-16T15-01-45_695-jvmRun1 surefire7038759527328167887tmp surefire_115532971887761201284tmp

Host: 
[timeout occurred during error reporting in step "printing summary machine and OS info"] after 30 s.
Time: Thu Sep 16 15:12:57 2021 UTC elapsed time: 401.604736 seconds (0d 0h 6m 41s)

---------------  T H R E A D  ---------------

Current thread (0x00007f8c4420c800):  JavaThread "Broker-2-zb-fs-workers-0" daemon [_thread_in_native, id=61320, stack(0x00007f8c07cbb000,0x00007f8c07dbc000)]

Stack: [0x00007f8c07cbb000,0x00007f8c07dbc000],  sp=0x00007f8c07db88b0,  free space=1014k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x82821]
------ Timeout during error reporting after 120 s. ------
```

[test-errors-it.zip](https://github.com/camunda-cloud/zeebe/files/7183048/test-errors-it.zip)

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description

Previously the actor scheduler and the system context were not cleaned up, which causes problems on running the QA tests, since we using class rules which keep references to all existing actor schedulers.

See related comment https://github.com/camunda-cloud/zeebe/issues/7841#issuecomment-921799977

## Related issues

closes #7841 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by Zelldon** [comment]
Looks better now:


threads-improve

**Comment by Zelldon** [comment]
Who ever is first @deepthidevaki @npepinpe @pihme this should help us to make our builds more stable again

**Review by npepinpe — APPROVED** [review]
:+1: 

We should also do a sweep of other schedulers in the tests I guess. I wonder if there's a good way to quickly scan for left over resources after tests :thinking:

**Comment by Zelldon** [comment]
I checked the embedded broker rules at least.

**Comment by Zelldon** [comment]
bors p=10-

**Comment by Zelldon** [comment]
bors p=10

**Comment by Zelldon** [comment]
bors cancel

**Review by pihme — APPROVED** [review]
bors merge

**Pull request merged**
