### PR TITLE
feat(clients/java): add create job request

### LINKED ISSUE #1261: I can create a job with the java client

### PR DESCRIPTION
**Pull request by menski**
closes #1261

### CODE REVIEW

**Comment by menski** [comment]
I rebased the change against develop and adjusted it to the test environment and exception changes. @Zelldon I feel free to merge after approval

**Review by ChrisKujawa — APPROVED** [review]

**Comment by menski** [comment]
There is a strange compilation error on merge, I will look into it.

**Comment by menski** [comment]
bors retry

**Pull request merged**
