### PR TITLE
[Backport] Zip test results and keep reports for flaky tests

### PR DESCRIPTION
**Pull request by saig0**
## Description

* backport of #4850 to `0.23`
* store dump files if JVM crashes
* align changes from develop branch

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

**Comment by saig0** [comment]
I noticed some changes in `upload` and `Post` stages compared to `0.24`. It seems that they are not executed on branch `0.24`. Maybe, there is missing something?

**Comment by saig0** [comment]
Need to adjust the `jenkinsfile` again to include the error report files.

**Comment by saig0** [comment]
@pihme, can you have a look please?

**Review by pihme — APPROVED** [review]
Looks good to me.

**Pull request merged**
