### PR TITLE
Single variable API for Complete Job command

### LINKED ISSUE #13040: As a Zeebe Java user, I want to complete a Job with a single variable
**Is your feature request related to a problem? Please describe.**
As a programmer writing Zeebe Job Handlers, I want to complete a job returning only a single variable value.

The `newCompleteCommand` offers only a parameter `.variables()` where I have to wrap the value in a Map beforehand.

This is overhead.

**Describe the solution you'd like**
`client.newCompleteCommand(job).variable("name", value)...`

**Describe alternatives you've considered**
Promote the Java feature with `Map.of("name", value)` giving examples in the docs and Zeebe examples. 

Older programmers, that learned Java with versions older than 8 are not aware of this shortcut.

**Additional context**
It came up in a migration Workshop with a customer.

### PR DESCRIPTION
**Pull request by nicpuppa**
## Description

Add a new API to `newCompleteJob()` command to allow user to provide a single variable. This reduce overhead and improve the user experience 

## Related issues

closes #13040 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Other teams:
If the change impacts another team an issue has been created for this team, explaining what they need to do to support this change.
- [ ] [Operate](https://github.com/camunda/operate/issues)
- [ ] [Tasklist](https://github.com/camunda/tasklist/issues)
- [ ] [Web Modeler](https://github.com/camunda/web-modeler/issues)
- [ ] [Desktop Modeler](https://github.com/camunda/camunda-modeler/issues)
- [ ] [Optimize](https://github.com/camunda/camunda-optimize/issues)

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by remcowesterhoud** [comment]
@nicpuppa I haven't looked at the code yet, will do that now. I already noticed the backport labels. As this is a new feature we don't need to backport this. We only backport bug fixes.

**Comment by nicpuppa** [comment]
> @nicpuppa I haven't looked at the code yet, will do that now. I already noticed the backport labels. As this is a new feature we don't need to backport this. We only backport bug fixes.

Ok, got it! Thank you

**Review by remcowesterhoud — APPROVED** [review]
Great work @nicpuppa 🚀 

💭 We have 5 commands that can have variables currently. For all of these we need to specify all methods of the `CommandWithVariables` class on the interface. It's quite easy to make this more generic.

That would involve creating a new interface (e.g. `CommandWithVariablesCommandStep`). If we put the methods on there we only have to extend this interface in the actual command steps.

A pro would be that we don't have these methods defined 5 times. A con is that the javadoc is no longer command specific.

This is just a brain dump I had, WDYT? Might be worth asking the rest of the team if they have an opinion on it.

In any case there's no real urgency to change this now so feel free to merge it as-is.

**Comment by nicpuppa** [comment]
> Great work @nicpuppa 🚀
> 
> 💭 We have 5 commands that can have variables currently. For all of these we need to specify all methods of the `CommandWithVariables` class on the interface. It's quite easy to make this more generic.
> 
> That would involve creating a new interface (e.g. `CommandWithVariablesCommandStep`). If we put the methods on there we only have to extend this interface in the actual command steps.
> 
> A pro would be that we don't have these methods defined 5 times. A con is that the javadoc is no longer command specific.
> 
> This is just a brain dump I had, WDYT? Might be worth asking the rest of the team if they have an opinion on it.
> 
> In any case there's no real urgency to change this now so feel free to merge it as-is.

Thank you for the review @remcowesterhoud! I think it's a nice idea 🔥, but since it's a client library I think it's better to have a more specific javadoc (even if in this case it's very very simple). I agree with you to share this with @korthout @koevskinikola @berkaycanbc, let us know your opinion! 👀

**Comment by nicpuppa** [comment]
bors merge

**Comment by remcowesterhoud** [comment]
> 💭 On that same note, can we perhaps use CommandWithVariables for CreateProcessInstanceCommandImpl, EvaluateDecisionCommandImpl, and such?

I am pretty sure @nicpuppa did this in the PRs for the other commands 🎉 

> I wondered whether it could lead to any backward compatibility issues, e.g. someone stored the result of one of these methods in a local variable of a specific type. But I don't see any problems.

I shortly tested it in our code. Everything compiled as expected, which makes sense as the methods return the same things and are available on the same interface.


@nicpuppa What do you want to do? Do you want to improve this straightaway and use it in the PRs for the other commands? Alternatively, we could get those merged and change create an issue to change improve this later.

**Comment by nicpuppa** [comment]
> I am pretty sure @nicpuppa did this in the PRs for the other commands 🎉

True
 
> @nicpuppa What do you want to do? Do you want to improve this straightaway and use it in the PRs for the other commands? Alternatively, we could get those merged and change create an issue to change improve this later.

Since I am already on another issue I prefer to merge the other PRs, create an issue to improve those commands and then work on it later. It is ok for you ?

**Comment by remcowesterhoud** [comment]
> Since I am already on another issue I prefer to merge the other PRs, create an issue to improve those commands and then work on it later. It is ok for you ?

Fine with me

**Pull request merged**
