### PR TITLE
[Backport 0.25] Avoid deployment distribution on reprocessing

### LINKED ISSUE #3124: Deployments are re-distributed during reprocessing
**Description**

During reprocessing of partition 1, the deployments are pushed to other partitions again. While it doesn't lead to any incorrect state, there is room for improvement.

```
11:59:09.987 [partition-1-processor] INFO  io.zeebe.processor - Processor starts reprocessing, until last source event position 1095222022840 
11:59:10.117 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813685250 
11:59:10.689 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813688855 
11:59:25.087 [partition-1-processor] WARN  io.zeebe.broker.workflow.repository - Failed to receive deployment response for partitions [3] (topic 'deployment-response-2251799813685250'). Retrying 
11:59:25.827 [partition-1-processor] WARN  io.zeebe.broker.workflow.repository - Failed to receive deployment response for partitions [3] (topic 'deployment-response-2251799813688855'). Retrying 
11:59:45.177 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813685250 
11:59:45.178 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Deployment 2251799813685250 pushed to all partitions successfully. 
11:59:45.178 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813688855 
11:59:45.178 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Deployment 2251799813688855 pushed to all partitions successfully. 
11:59:45.178 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813685250 
11:59:45.179 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813688855 
11:59:52.288 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813685250 
11:59:53.033 [partition-1-processor] DEBUG io.zeebe.broker.workflow.repository - Receiving deployment response on topic deployment-response-2251799813688855 
12:00:50.550 [partition-1-processor] INFO  io.zeebe.processor - Processor finished reprocessing at event position 1095222022840
```

### PR DESCRIPTION
**Pull request by saig0**
## Description

Backport of #5758

## Related issues

closes #3124

### CODE REVIEW

**Comment by Zelldon** [comment]
I think this is an allowed backport right ? @npepinpe

**Comment by npepinpe** [comment]
I think so, but my one concern would be that we drop the filtering out of the distributed records - could that have an impact? I expect not because now we won't be writing them during reprocessing, so whatever's on the log should be fixed (as in, immutable), right? And this won't change how we do processing...so it should be fine.

**Review by ChrisKujawa — APPROVED** [review]
thanks @saig0  we discussed it yesterday and the consensus was it is not a problem right?! Not 100% sure anymore :laughing:

**Comment by saig0** [comment]
Yes. It is not a problem :sweat_smile: No behavior is changed. Removing the filter is okay because it was just added for the case that a `Distributed` record was written on reprocessing.

**Pull request merged**
