### PR TITLE
ci: skip summary action on property tests

### LINKED ISSUE #16604: CI runs out of heap when analyzing Propery Test
**Summary**

- How often does the test fail? very often

The actual test seems to have passed. But the step `Analyze Test Runs` fails due to out of heap. 

```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

### PR DESCRIPTION
**Pull request by megglos**
## Description

It currently runs into a limitation due to the amount of data. See https://github.com/test-summary/action/issues/45 .

## Related issues

closes #16604

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Thanks! I consider the test summary an optional nice-to-have so totally makes sense to disable it here :+1:

**Comment by megglos** [comment]
I added backport labels to have this aligned across stable branches and potentially stabilize the CI of those too.

**Comment by megglos** [comment]
😢

**Comment by megglos** [comment]
actually this is not used in <8.4 🎉 we only have the duplicate check there https://github.com/camunda/zeebe/blob/stable/8.4/.github/actions/check-duplicate-tests/action.yml

**Pull request merged**
