### PR TITLE
chore(dist): corrected setting

### LINKED ISSUE #2382: Incorrect setting name in zeebe config
In the [zeebe config file](https://github.com/zeebe-io/zeebe/blob/71c589746e50bfbdee2b5317f7ad8dfc9acf1266/dist/src/main/config/zeebe.cfg.toml#L202), the default setting for defaultLogSegmentSize is specified as:
```
# The default size of data segments.
# defaultSegmentSize = "512M"
```
Since this setting is incorrectly named, it will have no effect on the system. Should be renamed to [defaultLogSegmentSize](https://github.com/zeebe-io/zeebe/blob/71c589746e50bfbdee2b5317f7ad8dfc9acf1266/broker-core/src/main/java/io/zeebe/broker/system/configuration/DataCfg.java#L30).

### PR DESCRIPTION
**Pull request by miguelpires**
closes #2382

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
