### PR TITLE
Documentation: Fixes to the guide on how to run Zeebe on Kubernetes

### PR DESCRIPTION
**Pull request by andreypanin**
## Description

This pull request corrects the documentation related to running of Zeebe on Kubernetes.

## Related issues

None.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [x] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fd7c9c7ff0a7d8d5dd8d7ed08d5038c96a31cddd
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Review by ChrisKujawa — CHANGES_REQUESTED** [review]
Thanks @andreypanin for your contribution.

Please follow our [Commit guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines). After that I can merge it.

**Comment by jwulf** [comment]
Hi @andreypanin, do you need help with changing the commit log message?

**Comment by pihme** [comment]
@Zelldon / @jwulf  Do we still track this PR? I tihnk it would be easier to add the changes to the new documentation repo.

See also #5577

**Comment by npepinpe** [comment]
Reopened on the new doc repo.

**Pull request closed without merging**
