### PR TITLE
chore(ci): build and test Go in parallel stage

### LINKED ISSUE #3511: Can we move go build and tests into parallel stage
**Description**
We currently running `java build -> go build -> go tests -> other tests in parallel stage`. Could we move the go build and tests in the parallel stage?

### PR DESCRIPTION
**Pull request by miguelpires**
## Description

Moves the Go build and test into the parallel stage.

## Related issues

closes #3511

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by ChrisKujawa — APPROVED** [review]
awesome thanks :tada: :+1:

**Comment by MiguelPires** [comment]
bors retry

**Pull request merged**
