### PR TITLE
chore(atomix): remove multicast and broadcast

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
Removes unused features like multi cast and broadcast service.

## Related issues

closes 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
:tada: 

I didn't review thoroughly, since it's primarily removing code. Is there a part in particular where you had to do changes that you're unsure of?

Also let's wait for the tests to finish before merging, just in case :slightly_smiling_face:

**Comment by Zelldon** [comment]
@npepinpe actually just configuration changes which I'm always unsure in Atomix :laughing:

**Comment by npepinpe** [comment]
I don't think we serialize the general Atomix config though, so it should be fine? We can verify that by upgrading an existing cluster with rolling upgrade and see :man_shrugging:

**Comment by npepinpe** [comment]
Seems there's some broken tests :thinking:

**Comment by Zelldon** [comment]
@npepinpe yeah I have to fix the AtomixConfig test, missed that.

**Pull request merged**
