### PR TITLE
chore(clients/java): merge workflow and job clients to zeebeclient

### LINKED ISSUE #1715: Merge Job and Workflow Client in the Java client impl
After #1648 the jobs are more coupled with workflow execution, then before. Maybe we can discuss if it is still necessary to have the an JobClient and WorkflowClient. Maybe it makes sense to merge the Job- and WorkflowClient into one (move the methods into the ZeebeClient), like it is done in the go client.

For the job workers it is still possible to have an trimmed client interface, which only contains fail and complete job commands. (like it is done in the go client)

### PR DESCRIPTION
**Pull request by deepthidevaki**
* move workflowClient and jobClient methods to zeebeClient
 * update samples
 * update tests

closes #1715

### CODE REVIEW

**Review by saig0 — CHANGES_REQUESTED** [review]
Looks good :+1:  Please update the docs too. For example, I have found the old structure in the Java Get-Started.

**Comment by deepthidevaki** [comment]
Updated docs.

**Review by saig0 — APPROVED** [review]

**Comment by menski** [comment]
bors retry

**Pull request merged**
