### PR TITLE
Allow secure inter-cluster messaging between brokers and other nodes

### LINKED ISSUE #5272: Allow to configure TLS for internal traffic between brokers and gateway
**Is your feature request related to a problem? Please describe.**

Per default the internal traffic between brokers and also from broker to gateways is unencrypted. As a user I want to be able to configure transport layer security for this communication in case I want to deploy my broker cluster in an untrusted environment like an open cloud.

**Describe the solution you'd like**

As a user I can configure the brokers and gateway to use TLS for the internal communication.

**Describe alternatives you've considered**

None

**Additional context**

It is expected that this might have an impact on performance. We have to revert this PR https://github.com/zeebe-io/zeebe/pull/5233 which removed TLS from Atomix.

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR allows brokers to configure TLS for encrypted messaging between them and other nodes in the cluster. The security configuration is added directly to the network configuration, as it wasn't considered a useful case to have different configuration for different APIs. This can be changed later, but for simplicity we omitted it here.

TLS can be enabled on the brokers between nodes by setting `zeebe.broker.network.security.enabled=true`. If true, a certificate and a private key must be provided. These can be provided as `zeebe.broker.network.security.certificateChainPath` and `zeebe.broker.network.security.privateKeyPath`, respectively, and should point to readable files relative to the broker's working directory. The `certificateChainPath` must be either a X.509 certificate, or a certificate chain - that is, the certificate, followed by its chain of trust. This can be useful if you don't expect the certificate itself to be trusted by default on the other nodes, but one member of its chain is. The private key must then be the private key of the certificate itself.

This configuration is a bit verbose but done on purpose - that is, to align it with the gateway's security configuration, and to be forwards compatible with future planned transport changes.

The whole thing works with self signed certificates - however, if you wish to use one, then you must ensure all nodes are configured with the same self signed certificates. This is by design - the certificate chain you configure a broker with will be implicitly trusted by itself, so if another broker identifies with the same self signed certificate, it will trust it.

The broker will fail to start if `zeebe.broker.network.security.enabled=true`, and:

- the certificate chain and/or private key is not configured
- the certificate chain and/or private is not a readable file
- the private key does not match the certificate
- the certificate is not a X.509 certificate or certificate chain

## Related issues

closes #5272 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [x] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by npepinpe** [comment]
Documentation will follow in https://github.com/camunda-cloud/camunda-cloud-documentation/issues/399

**Comment by npepinpe** [comment]
@Zelldon - please review https://github.com/camunda-cloud/zeebe/pull/8019 first

**Comment by Zelldon** [comment]
> Sonar flagged that both the gateway's SecurityCfg and the broker's SecurityCfg are the same. Which is true ￼ But semantically it wouldn't make sense to pull in the SecurityCfg of the gateway as the NetworkCfg#security for the broker I think. And the gateway cannot have a dependency on the broker, so the other way is equally wrong.
> 
> We don't really have a solution yet for shared configuration settings, and I wasn't really sure if I wanted to open a discussion on that right now. Let me know what you think.

Config module ? :shrug:

**Review by ChrisKujawa — APPROVED** [review]
Thanks @npepinpe looks good :) small questions

**Review by ChrisKujawa — APPROVED** [review]
i like the additional changes thanks :100: :+1:

**Pull request merged**
