### PR TITLE
Send current checkpoint id with inter-partition commands

### LINKED ISSUE #9810: Send current checkpointId with all remote commands
Every message send between partitions must encode the current checkpointId at the sender. 

Depends on #9720 #9625 #9721

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

The sender implements a `CheckpointListener`, updating an internalfield whenever a new checkpoint is created. For all commands, the current checkpoint id is sent along.

The sender is no longer thread-safe. Calls of the listener and the send methods must be linearized by the stream processor, otherwise commands could be sent with stale checkpoint ids.

## Related issues

closes #9810 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Review by deepthidevaki — APPROVED** [review]
Great! What is missing is for the sender registering as the checkpoint listener. But we have to do in the "put it all together" issue after all components are implemented.

**Comment by oleschoenburg** [comment]
Yep, there was just nothing where it could have registered yet so I've left that open for later.

bors r+

**Comment by oleschoenburg** [comment]
bors retry

**Comment by oleschoenburg** [comment]
@deepthidevaki The test is still failing here: https://github.com/camunda/zeebe/runs/7519818303?check_suite_focus=true

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
