### PR TITLE
Always create snapshots

### LINKED ISSUE #4017: Take snapshots even when no processing occurs
**Description**

While reviewing #3962 (https://github.com/zeebe-io/zeebe/pull/3962#discussion_r390148228) we discussed the possibility of taking snapshots like clockwork every X minutes, regardless of whether we processed or exported anything.

The main motivation here is to solve the current issue we have when no processing is done but we are exporting (e.g. exporters were behind), and to reduce complexity (no need to keep track of any state, just take a snapshot at a particular interval).

While this is very tempting, I'd like to consider the worst case scenario here if we were to do this naively. For example, if we have a very large state, this could be quite expensive for no reason, as we're not only snapshotting the current state, but also replicating it, potentially uselessly.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
## Description
To simplify the snapshot process and also include exporter changes we now take 
Snapshots **always**, there is no comparison of the latest position.

This means we do not check the position of the last snapshot:
  * on normal snapshot taking
  * on enforcing snapshot on close  
  * after restart, snapshot can be taken with the same position

There where tests which tested that this is not happing (which is btw interesting how they can verify that) now we verify that we are able to create a snapshot. The changes simplifies a bit the `AsyncSnapshotDirector`. 

Actually I wanted to remove completely the **StreamProcessor** reference. For that we would need to introduce again some suppliers for example, which provides us the last processed position and written position. We still need these positions to determine whether the snapshot is valid or not.

## Related issues

closes #4017

## Pull Request Checklist

- [X] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [X] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [X] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by npepinpe** [comment]
If we were to move this to the broker, there is a commit position listener that we can use, so that would also help us be notified when the snapshot is now valid. But we can do this in a follow up issue as well.

**Review by npepinpe — APPROVED** [review]
:tada:

**Comment by Zelldon** [comment]
> If we were to move this to the broker, there is a commit position listener that we can use, so that would also help us be notified when the snapshot is now valid.

The more major problem is that we need the last written position. But we can abstract this away. I will do it in a follow up issue.

**Comment by Zelldon** [comment]
@npepinpe I rewrote the AsyncSnapshotting test

The test highly depend on implementation details and where likely to fail when implementation changed.
I think we should avoid these kind of tests and try to write more tests which only verifies the result and behavior, but not how it produces this result.

 Since we used the mockito verification api it also happens that these kind of these where often flaky.

Let me know what you think

**Review by npepinpe — COMMENTED** [review]
I agree with you, mocking too much is something we should avoid. As we're rewriting this, can we also add a test to ensure that we will close the director even if `streamProcessor.getLastProcessedPositionAsync()` or `logStream().getCommitPosition()` fail? We've been bitten in the past by dependent things not closing properly in some cases.

Also, do you think we should add a case that even if we fail to take a snapshot (e.g. the above calls also fail), the next time we try to take a snapshot it can succeed? The only reason this would fail that I can think of, is that the actors are closed, at which point the director will never succeed...but maybe I'm forgetting a case?

Some other tests seem to failing - if you have to refactor me and feel the need for another review, feel free to request it again. Otherwise I trust you :+1:

**Comment by Zelldon** [comment]
Thanks @npepinpe . I added some more tests for the cases you mentioned. I think it make sense that we ensure that even a failure we can take snapshots again. Since the snapshot not really holds resources I'm not 100% sure how important it is to have the other tests but I added some an verify that the director is really closed. 

I had to fix some other tests which also depend on the TestStorage. I have the feeling that this is not optimal since we test more the test implementation and not the real one.

**Comment by npepinpe** [comment]
> I had to fix some other tests which also depend on the TestStorage. I have the feeling that this is not optimal since we test more the test implementation and not the real one.

Agreed - but that's probably a result of a design flaw more than a test issue. If the `AsyncSnapshotDirector` test relies so much on the implementation of `SnapshotStorage`, maybe then it's too coupled to it?

**Review by npepinpe — APPROVED** [review]
:+1: 

Looks good, thanks! Happy to reduce the number of tests relying on Mockito verifications :muscle:

**Comment by Zelldon** [comment]
> Agreed - but that's probably a result of a design flaw more than a test issue. 

Yes, totally. Not only the director is the problem also somehow the storage maybe we can try to abstract the atomix stuff more away such that we can also use the storage which we use in production in our tests.

**Pull request merged**
