### PR TITLE
fix(clients/java): dont break cause chain

### LINKED ISSUE #1655: Improve exception handling (aka not swallow root causes)
I am currently stuck with an exception I get at

```
Exception in thread "main" io.zeebe.client.cmd.ClientException: io exception
   at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52)
   at 
```

I have no idea what the problem is. And I found that the root cause exception is not re-thrown here, making it hard for me to investigate: 

https://github.com/zeebe-io/zeebe/blob/develop/clients/java/src/main/java/io/zeebe/client/impl/ZeebeClientFutureImpl.java#L52

I think we should NEVER swallow root causes but always pass them on. 

For the very concrete problem at hand I ask via Slack - this is not part of this issue for me.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
closes #1655

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]

**Comment by menski** [comment]
@Zelldon and @npepinpe do you think this change actually improves the situation? I personally don't see any advantage in having the same exception message 3 times, with the gRPC internals stack.

Example for creating a instance of a not deployed workflow.
```
Exception in thread "main" io.zeebe.client.cmd.ClientException: Command (CREATE) was rejected. It has an invalid value. Workflow is not deployed
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:52)
	at io.zeebe.example.workflow.WorkflowDeployer.main(WorkflowDeployer.java:32)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: INTERNAL: Command (CREATE) was rejected. It has an invalid value. Workflow is not deployed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.zeebe.client.impl.ZeebeClientFutureImpl.join(ZeebeClientFutureImpl.java:47)
	... 1 more
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Command (CREATE) was rejected. It has an invalid value. Workflow is not deployed
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by npepinpe** [comment]
In that case yes, it doesn't improve much, but take Bernd's example, where we put the status message but not the cause. "io exception" is completely useless (which you could argue is due to a bad error message), but now at least with the stack trace it might be a bit better to pinpoint where it came from.

Admittedly it might also get lost in all these grpc callbacks...

**Comment by Zelldon** [comment]
For me it is definitely an improvement to see `Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:25500` instead of simply `ClientException: io exception`, which I also had some times in my examples.

I mean io exception can be everything. :sweat_smile: but nobody knows :man_shrugging: 

> I would argue that we still should improve this behavior on client side.

Yes totally agree. This PR was not intended to completely solve this issue.

**Pull request merged**
