### PR TITLE
fix(gtw/jobs): ignore notifications if already scheduled

### LINKED ISSUE #8267: Too many workers can break cluster performance
**Describe the bug**

Run a new [Chaos Day](https://zeebe-io.github.io/zeebe-chaos/2021/11/24/Worker-count-should-not-impact-performance) were I observed the following:

With three Broker, three partition, one starter (300 pi/s) and 16 workers

worker-16-p3-300-general-reproduce

We can observe that the throughput drops after a short period of time. We are not able to complete more process instances, but still new instances are created. 

Looks like it is related to https://github.com/camunda-cloud/zeebe/issues/7955 and https://github.com/camunda-cloud/zeebe/issues/8244

**To Reproduce**

For more details about the setup please take a look at the [Chaos Day Summary](https://zeebe-io.github.io/zeebe-chaos/2021/11/24/Worker-count-should-not-impact-performance) and the resource files:
[16-workers.zip](https://github.com/camunda-cloud/zeebe/files/7595668/16-workers.zip)

**Expected behavior**

We can complete the 300 instances without such issues.

**Log/Stacktrace**

There is nothing visible in the [gateway logs,](https://console.cloud.google.com/logs/viewer?interval=JUMP_TO_TIME&authuser=0&organizationId=669107107215&project=zeebe-io&rif_reserved&minLogLevel=0&expandAll=false&timestamp=2021-11-24T09:34:00.887000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22zell-worker-16%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fcomponent%3D%22gateway%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22zell-worker-16%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fmanaged-by%3D%22Helm%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22zeebe-cluster-helm%22&scrollTimestamp=2021-11-24T09:30:02.353389908Z&dateRangeStart=2021-11-24T08:34:00.887Z&dateRangeEnd=2021-11-24T10:34:00.887Z&pinnedLogId=3iex35gg4zhvoepf&pinnedLogTimestamp=2021-11-24T09:30:02.353389908Z)

log

**Analysis**

I started a small analysis, took a heap dump and created a flame graph with async profiler.

Based on the metrics we can see that the gateway is working on their limit (2 CPU)

cpu

In the gateway threads we can see that they are idle, this is also visible in the flame graph. 
[flame.zip](https://github.com/camunda-cloud/zeebe/files/7595719/flame.zip)

flame

Since we know that instance creation still works, we expect that the long polling handler might have some issues.

Taking a look at the code and the heap dump we found this:

heap

The pending requests seems to be empty, but the requests which should be repeated are at 38 and all objects are the same. It looks like this is not cleaned up correctly. Currently I'm not sure whether this is a problem or not. It should be removed here https://github.com/camunda-cloud/zeebe/blob/b0fec6391814ff7a6f575086520115dccdbe5930/gateway/src/main/java/io/camunda/zeebe/gateway/impl/job/InFlightLongPollingActivateJobsRequestsState.java#L94-L103

I think it makes sense to investigate that further.

**Environment:**
 - OS: 
 - Zeebe Version: 1.3.0-SNAPSHOT
 - Configuration: see above

### PR DESCRIPTION
**Pull request by romansmirnov**
## Description

* Ignore incoming notifications if a notification is already scheduled/running for the given job type
* Changes the type from `HashMap` to `ConcurrentHashMap` of field `LongPollingActivateJobsHandler#jobTypeState` because it is accessed by different threads
  * Actor Thread who does reads and updates to the map
  * "Netty Threads" who notifies the gateway when newly jobs are available

## Related issues

closes #8267 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by romansmirnov** [comment]
@deepthidevaki, can you please review this PR? In the case, you can't make it this week anymore, then please let me know.

Regarding a unit test to cover that scenario, I tried different approaches to write a working unit test but did not succeed. If you see any option, how to write a test case, therefore, then please let me know. I am happy to receive your ideas.

**Review by deepthidevaki — COMMENTED** [review]
LGTM :rocket: 
I cannot think of a way to test it other than what we already discussed. Since the existing  Long polling tests works, we can assume that it did not break the existing behavior. That would be enough.

Before merging this PR:
1. Could you update the commit message to include a small test describing the reasoning behind these changes. Basically what you have added in the PR description.
2. Have you already run a benchmark to ensure that this fixed the issue?

**Comment by romansmirnov** [comment]
@deepthidevaki,

Thanks for your review.

> Could you update the commit message to include a small test describing the reasoning behind these changes. Basically what you have added in the PR description.

Will do!

> Have you already run a benchmark to ensure that this fixed the issue?

Yes, I run the benchmark today and last week, it's documented in the issue itself: https://github.com/camunda-cloud/zeebe/issues/8267#issuecomment-985802005

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Pull request merged**
