### PR TITLE
fix(logstreams): stop snapshot from being replicated during deletion

### LINKED ISSUE #2633: Potential race condition in DefaultRestoreInfoRequestHandler
If snapshot is being deleted while the handler is calculating the number of chunks in the snapshot, it can return an incorrect number of chunks in the response. Probably not harmful because, when it later recieves `SnapshotRestoreRequest` the snapshot will be already deleted and the other node will restart the restore operation. But, it will be better to handle this case in the `DefaultRestoreInfoRequestHandler` itself.

### PR DESCRIPTION
**Pull request by miguelpires**
closes #2633

### CODE REVIEW

**Review by saig0 — COMMENTED** [review]
First of all, I'm not familiar with `RestoreInfoRequestHandler` and what is it used for. So, I don't know if the changed behavior is correct.

However, I would like to challenge the way how the concurrent access of the snapshot controller is synchronized. I think it a bit overpowered to use a LOCK file to synchronize the access between two threads in the same JVM. I would recommend that the snapshot controller provides an async method that can be used by the distributed log.

**Comment by npepinpe** [comment]
We're discussing the PR at 10 over a Zoom call, feel free to join; I also don't think a lock file is the right mechanism here, it's only useful to synchronize between different processes, it was just an example of the top off my head in the issue comment.

**Review by npepinpe — CHANGES_REQUESTED** [review]
To rework as discussed; just putting it here so it doesn't look like work stopped on this.

**Review by npepinpe — APPROVED** [review]
:+1: 

Rebase and bors it

**Pull request merged**
