### PR TITLE
[Backport stable/8.2] deps(maven): bump testcontainers-bom from 1.17.6 to 1.18.0

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Backport of https://github.com/camunda/zeebe/pull/12251 to get rid of the AWS SDK v1

### CODE REVIEW

**Comment by npepinpe** [comment]
@dependabot rebase

**Comment by npepinpe** [comment]
@dependabot rebase

**Comment by npepinpe** [comment]
Lol this is not a dependabot PR :smile:

**Comment by npepinpe** [comment]
olebot rebase

**Comment by oleschoenburg** [comment]
:robot: 

bors r+

**Review by npepinpe — APPROVED** [review]
:+1:

**Pull request merged**
