### PR TITLE
chore(broker): fix environment variable

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Fix environment variable names

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by npepinpe — CHANGES_REQUESTED** [review]
Thanks for the quick work :slightly_smiling_face: 

To be safe, can we add tests for these, as we do for the other config tests? I know this is tedious, sorry :see_no_evil:

**Review by npepinpe — APPROVED** [review]
Thanks :+1:

**Comment by deepthidevaki** [comment]
bors retry

**Pull request merged**
