### PR TITLE
Introduce a simple Either type to the expression processor

### LINKED ISSUE #4279: Introduce Either type to the expression processor
**Is your feature request related to a problem? Please describe.**
When the ExpressionProcessor fails evaluating an expression, it currently informs the caller of one of its `evaluateX..Expression` methods in different ways. In some methods, the expression processor raises an incident itself and the caller is informed of this by returning an empty optional. In others, an exception is thrown so that the caller can decide how to deal with the situation. In the cases where an exception is thrown, we throw a RuntimeException and hope that the caller catches this.

**Describe the solution you'd like**
Introduce a simple Either type to the expression processor to force callers to consider both the successful and the failed evaluation cases. 

**Describe alternatives you've considered**
- continue using exceptions, but we feel that either results in a clearer API for callers and enforces dealing with the failure case
- convert exceptions to checked exceptions, but we feel strongly about checked exceptions
- introduce vavr.io's Either, but we don't want to add such a dependency at this time

### PR DESCRIPTION
**Pull request by korthout**
## Description

This PR introduces a simple Either type (Left and Right) and applies it to the expression processor in places where exceptions were thrown.

TODO: 
- [x] write a simple Either implementation for Right and Left
- [x] test the Either implementation
- [x] apply it to the expression processor (specifically interval evaluation for timers)

closes #4279

### CODE REVIEW

**Comment by npepinpe** [comment]
If that's OK, I'll probably ask some questions as well, but don't count it as a review, I'm more curious than anything :)

**Comment by korthout** [comment]
@npepinpe much appreciated

**Review by saig0 — APPROVED** [review]
I like it :+1: 

It is a good start. I'm looking forward to introducing the either type in more places and from end-to-end.

I can also imagine more functions on the either type like `flatMap()`, `ifRight()` or `ifRightOrLeft()`.

**Comment by korthout** [comment]
bors retry

**Comment by korthout** [comment]
bors retry

**Pull request merged**
