### PR TITLE
docs(links): fix client links

### LINKED ISSUE #5784: Link to Java client and Go client docs in the README is broken
**Description**

In the readme, these links are broken: https://github.com/zeebe-io/zeebe/blob/460fe55c83c5120d42763bff260f063afcef40a2/README.md#L43-L44

### PR DESCRIPTION
**Pull request by aivinog1**
## Description

I've fixed links to clients.

## Related issues

closes #5784 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Review by npepinpe — APPROVED** [review]
Thanks @aivinog1!

**Comment by aivinog1** [comment]
@npepinpe Hi, can you retrigger this, please? 🙂

**Comment by npepinpe** [comment]
bors retry

Yeah, seems the build aborted, but not due to failure.

**Comment by aivinog1** [comment]
@npepinpe Hi, let's try to build again? :)

**Comment by npepinpe** [comment]
bors retry

**Pull request merged**
