### PR TITLE
Allow negative offsets for ControlledActorClock

### PR DESCRIPTION
**Pull request by lenaschoenburg**
## Description

follow up for https://github.com/camunda-cloud/zeebe/pull/8180#issuecomment-964318841

## Definition of Ready

Please check the items that apply, before requesting a review.

You can find more details about these items in our wiki page about [Pull Requests and Code Reviews](https://github.com/camunda-cloud/zeebe/wiki/Pull-Requests-and-Code-Reviews).

* [ ] I've reviewed my own code
* [ ] I've written a clear changelist description
* [ ] I've narrowly scoped my changes
* [ ] I've separated structural from behavioural changes
-->

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/0.25`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by oleschoenburg** [comment]
@npepinpe I've tested this manually but let me know if you think we should have tests for the `ControlledActorClock`

**Review by npepinpe — APPROVED** [review]
:+1: 

I think it's fine as is for now. When manipulating time, it means most likely that users will do so one test at a time (otherwise it'd be too flaky/difficult to control), so I don't expect much concurrent usage or anything that would require tests. Let me know if you think otherwise though, I would also accept tests of course :smile:

**Comment by oleschoenburg** [comment]
bors merge

**Comment by oleschoenburg** [comment]
bors retry

**Pull request merged**
