### PR TITLE
[Backport stable/8.4] feat: makes job timeout resolution configurable

### PR DESCRIPTION
**Pull request by mustafadagher**
## Description

Backport of https://github.com/camunda/zeebe/pull/16889 to stable/8.4.

The conflicts were only about the file renames. I only accepted the upstream changes without any modifications

## Related issues

relates to https://github.com/camunda/zeebe/issues/5073

### CODE REVIEW

**Review by korthout — APPROVED** [review]
Thanks @mustafadagher 💯 

LGTM 👍

**Comment by mustafadagher** [comment]
funny that it backport action failed here again for 8.1 and 8.2 but worked for 8.3

**Comment by korthout** [comment]
Yup, backport-action sadly can't resolve conflicts. However, I'm open to receive contributions [open a pull request with the conflicts included](https://github.com/korthout/backport-action/issues/386), so the pull request creation is at least still automated.

**Comment by korthout** [comment]
Oops, that link contains the trigger command `/`(slash) `backport`

**Pull request merged**
