### PR TITLE
Remove unnecessary this statements

### PR DESCRIPTION
**Pull request by saig0**
## Description

* remove all unnecessary `this` statements following the new coding style (using IDEA: Analyze -> Inspect Code -> ...)

## Related issues

Discuss in our team meeting from 2020-08-20.

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/zeebe-io/zeebe/compare/stable/0.24...develop?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)

### CODE REVIEW

**Comment by saig0** [comment]
Enable the option in `Other Settings > Save Actions > Unnecessary this to field and method` to automate it.

idea-settings-save-actions-remove-this

**Review by ChrisKujawa — COMMENTED** [review]
For the record I don't like it, especially cases like:

```java
 NettyMessagingService(
      final String cluster,
      final Address address,
      final MessagingConfig config,
      final ProtocolVersion protocolVersion) {
    preamble = cluster.hashCode();
    returnAddress = address;
    this.config = config;
    this.protocolVersion = protocolVersion;
    openFutures = new CopyOnWriteArrayList<>();
    channelPool = new ChannelPool(this::openChannel, config.getConnectionPoolSize());
}
```
Looks for me weird and not consistent, but this was the team decision so :shrug: 


Please change/update also the intellij configuration so it enables this per default.

**Comment by saig0** [comment]
> Please change/update also the intellij configuration so it enables this per default.

I don't see the option to define this in Java's code style section. You can enable a warning under Inspections. It is possible to export this configuration but I'm not sure if this is necessary for now. If we use the Save Actions then it is also done :wink:

**Comment by Zelldon** [comment]
> I don't see the option to define this in Java's code style section. You can enable a warning under Inspections. It is possible to export this configuration but I'm not sure if this is necessary for now. If we use the Save Actions then it is also done wink

If the team has not the same configuration then we talk soon again about this, so yes for me it is necessary. The save actions settings can also not be exported right?

**Review by ChrisKujawa — APPROVED** [review]

**Pull request merged**
