### PR TITLE
feat(client): Add omitempty-ignoring object marshaller method to go api

### LINKED ISSUE #1753: Followup for #1375: non-strict mapping extraction
In #1375 the fix for empty source mapping were merged. However later, in `io.zeebe.broker.workflow.processor.flownode.IOMappingHelper` it was negated by always using strict version of mapping, which brings back the same issue.

I am not sure if strict mapping has any merit at all, to be honest. Interpreting missing values as null or default value for given type is a better option to throwing an exception in my perspective.

---
Edit:
On second thought, I think there are cases when this could be benificial, however not all of them such.

The main case where it is not is when you return your own gRPC structures as a result of service task, and their json is "omitempty", making every zero-value (0, "", false, nil, etc.) omited from serialization.

Anyway I think some discussion to be made how to best approach it. If simply go to replace strict with-non strict, all tests in `io.zeebe.broker.incident.MappingIncidentTest` will no longer have their way to fail mappings they are now, because their current supposedly failing mapping will become valid and functional. And I rather consult how to approach this test suit.

- Would IO-mapping parts of this tests still be relevant?
- Should we find another way to create incidents for this tests?
- Should we have a per-mapping option to choose what to do with missing sources?
- Maybe solve it via coalesce()-like operator (essentialy `$.missingValue || defaultValue` in js)?

### PR DESCRIPTION
**Pull request by iamtakingiteasy**
closes #1753

### CODE REVIEW

**Comment by iamtakingiteasy** [comment]
Please don't merge, there is a unintended behaviour on embedded structs.

**Comment by iamtakingiteasy** [comment]
Fixed. Tests added.

**Comment by iamtakingiteasy** [comment]
Added license headers.

**Review by menski — APPROVED** [review]
Thanks again for this fast PR. LGTM :balloon: 

bors r+

**Pull request merged**
