### PR TITLE
chore(monitor): backport monitor/grafana

### LINKED ISSUE #4502: [BACKPORT] Adapt Grafana dashboard for 0.20.x
**Description**

Adapt Grafana dashboard for Zeebe 0.20.x so users can easily visualize the state of their Zeebe cluster using the Prometheus metrics.

**Acceptance criterias**

- [ ] A `zeebe.json` dashboard is available and versioned in the repository in the `stable/0.20` branch

### PR DESCRIPTION
**Pull request by npepinpe**
## Description

This PR backports the Grafana dashboard and monitoring set up for usage with 0.20.x, and trims down the dashboard to display only the metrics available in 0.20.x.

## Related issues

closes #4502

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Comment by npepinpe** [comment]
**To do**

- [ ] Test in the cloud to check to test Kubernetes specific metrics and exporter metrics

**Comment by npepinpe** [comment]
This is currently deployed under "Zeebe v0.20" in our cloud grafana, but you can also run `ZEEBE_VERSION=0.20.1 make up" from the monitor folder to test locally. Afterwards, make sure to bring everything down with `make ARGS="-v" down` to prune volumes.

**Review by deepthidevaki — APPROVED** [review]
:+1:

**Pull request merged**
