### PR TITLE
Candidate steps down if election timesout with out success or failure

### LINKED ISSUE #11665: Two raft nodes caught in an election loop
**Describe the bug**

RandomizedRaftTest failed in #11632 because two nodes could not elect a leader when the third node was unavailable.

Here is what happened:

Leader at term 137 is Node 1 and it was shut down

```
Restart member with full data loss on 1
348952-16:42:57.067 [] INFO  TEST - Shutting down member 1
```
2 receives poll request from 0 and accepts
```
TRACE io.atomix.raft.roles.FollowerRole - RaftServer{2-partition-1}{role=FOLLOWER} - Received PollRequest{term=137, candidate=0, lastLogIndex=247, lastLogTerm=137}
349029-16:42:57.067 [] INFO  io.atomix.raft.roles.FollowerRole - RaftServer{2-partition-1}{role=FOLLOWER} - Accepted PollRequest{term=137, candidate=0, lastLogIndex=247, lastLogTerm=137}: candidate's log is up-to-date
```
2 receives append from 1 which was send before 1 was shutdown, before 0 becomes leader
```
349033-16:42:57.067 [] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{2-partition-1}{role=FOLLOWER} - Received AppendRequest{term=137, leader=1, prevLogIndex=247, prevLogTerm=137, entries=1, commitIndex=247}
349034-16:42:57.067 [] TRACE io.atomix.raft.roles.FollowerRole - RaftServer{2-partition-1}{role=FOLLOWER} - Appended IndexedRaftLogEntryImpl[index=248, term=137, entry=SerializedApplicationEntry[lowestPosition=198, highestPosition=198, data=UnsafeBuffer{addressOffset=61, capacity=4, byteArray=[B@32124a62, byteBuffer=null}], record=io.atomix.raft.protocol.PersistedRaftRecord@5efcc5ed]
```
0  transition to candidate and increase the term
```
349038-16:42:57.067 [] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{0-partition-1}{role=FOLLOWER} - Received accepted poll from DefaultRaftMember{id=2, type=ACTIVE, updated=2023-02-13T16:42:57.062Z}
349039-16:42:57.067 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{0-partition-1} - Transitioning to CANDIDATE
349040-16:42:57.067 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Starting election
349041-16:42:57.067 [] TRACE io.atomix.raft.storage.system.MetaStore - Store term 138
349046-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Requesting votes for term 138
```
2 rejects vote because it's log is longer now. Because it received a new append after accepting the poll request
```
349053-16:42:57.068 [] DEBUG io.atomix.raft.roles.FollowerRole - RaftServer{2-partition-1}{role=FOLLOWER} - Rejected VoteRequest{term=138, candidate=0, lastLogIndex=247, lastLogTerm=137}: candidate's last log entry (247) is at a lower index than the local log (248)
```
Now 2 sends poll requests and 0 accepts, while it is in Candidate Role (??)
```
349060-16:42:57.068 [] TRACE io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Received PollRequest{term=138, candidate=2, lastLogIndex=248, lastLogTerm=137}
349061-16:42:57.068 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Accepted PollRequest{term=138, candidate=2, lastLogIndex=248, lastLogTerm=137}: candidate's log is up-to-date
```
2 sends Vote request because it received successfull PollResponse
```
349074-16:42:57.068 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2-partition-1} - Transitioning to CANDIDATE
349075-16:42:57.068 [] INFO  io.atomix.raft.roles.CandidateRole - RaftServer{2-partition-1}{role=CANDIDATE} - Starting election
349078-16:42:57.068 [] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{2-partition-1} - Set term 139
```
Both reject each other's vote request
```
349084-16:42:57.068 [] TRACE io.atomix.raft.roles.CandidateRole - RaftServer{2-partition-1}{role=CANDIDATE} - Received VoteRequest{term=139, candidate=0, lastLogIndex=247, lastLogTerm=137}
349085-16:42:57.068 [] TRACE io.atomix.raft.roles.CandidateRole - RaftServer{2-partition-1}{role=CANDIDATE} - Sending VoteResponse{status=OK, term=139, voted=false}
349087-16:42:57.068 [] TRACE io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Sending VoteResponse{status=OK, term=139, voted=false}
349088-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Received rejected vote from DefaultRaftMember{id=2, type=ACTIVE, updated=2023-02-13T16:42:57.062Z}
349089-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{2-partition-1}{role=CANDIDATE} - Received rejected vote from DefaultRaftMember{id=0, type=ACTIVE, updated=2023-02-13T16:42:57.065Z}
```

Node 0 restarts election without PollRequest
```
349091-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Election timed out
349092-16:42:57.068 [] TRACE io.atomix.raft.storage.system.MetaStore - Store term 140
349093-16:42:57.068 [] TRACE io.atomix.raft.storage.system.MetaStore - Store vote null
349094-16:42:57.068 [] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{0-partition-1} - Set term 140
349095-16:42:57.068 [] TRACE io.atomix.raft.storage.system.MetaStore - Store vote 0
349096-16:42:57.068 [] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{0-partition-1} - Voted for 0
349097-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Requesting votes for term 140
349098-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Requesting vote from DefaultRaftMember{id=2, type=ACTIVE, updated=2023-02-13T16:42:57.062Z} for term 140
349099-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Requesting vote from DefaultRaftMember{id=1, type=ACTIVE, updated=2023-02-13T16:42:57.062Z} for term 140
349100-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{0-partition-1}{role=CANDIDATE} - Restarted election
```
Node 2 rejects vote request because it has a longer log, but also transition to follower becuase 0 has a higher term
```
349101-16:42:57.068 [] TRACE io.atomix.raft.roles.CandidateRole - RaftServer{2-partition-1}{role=CANDIDATE} - Received VoteRequest{term=140, candidate=0, lastLogIndex=247, lastLogTerm=137}
349102-16:42:57.068 [] TRACE io.atomix.raft.storage.system.MetaStore - Store term 140
349103-16:42:57.068 [] TRACE io.atomix.raft.storage.system.MetaStore - Store vote null
349104-16:42:57.068 [] DEBUG io.atomix.raft.impl.RaftContext - RaftServer{2-partition-1} - Set term 140
349105-16:42:57.068 [] TRACE io.atomix.raft.roles.CandidateRole - RaftServer{2-partition-1}{role=CANDIDATE} - Received VoteRequest{term=140, candidate=0, lastLogIndex=247, lastLogTerm=137}
349106-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{2-partition-1}{role=CANDIDATE} - Rejected VoteRequest{term=140, candidate=0, lastLogIndex=247, lastLogTerm=137}: candidate's last log entry (247) is at a lower index than the local log (248)
349107-16:42:57.068 [] TRACE io.atomix.raft.roles.CandidateRole - RaftServer{2-partition-1}{role=CANDIDATE} - Sending VoteResponse{status=OK, term=140, voted=false}
349108-16:42:57.068 [] INFO  io.atomix.raft.impl.RaftContext - RaftServer{2-partition-1} - Transitioning to FOLLOWER
349109-16:42:57.068 [] DEBUG io.atomix.raft.roles.CandidateRole - RaftServer{2-partition-1}{role=CANDIDATE} - Cancelling election
```

Node 0 stay in the candidate role with out re-sending PollRequest. It keeps sending VoteRequests, and 2 rejects because it has longer log. Each election restart increments the term. Since 0 has higher term now, 0 rejects PollRequest from 2. So they both cannot become leaders.

**To Reproduce**

Run `consistencyTestAfterDataLoss`. The seed which failed is `-3483552123818146879`. But I could not reproduce it locally.

**Expected behavior**

Two nodes must be able to elect a leader if there are no network failures, even if the third node is unavailable.

Have to look into the details, but the following seems to be the problem:
1. Candidate role should not update the term. Term should be updated only after leader is elected. Check what is the correct behavior in Raft.
2. Why is 0 restarting election with out sending PollRequest? Is this correct?

** Log **
[trimmed-log.txt](https://github.com/camunda/zeebe/files/10744696/trimmed-log.txt)

**Environment:**
- Zeebe Version: 8.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

`RandomizedRaftTest` found a case where two nodes caught in a election loop #11665. In real world the probability of this happening is very less because there is a r[andomized delay](https://github.com/camunda/zeebe/blob/main/atomix/cluster/src/main/java/io/atomix/raft/roles/CandidateRole.java#L133) set for timeouts in Candidate Role. 
In this specific scenario, one node has longer log. The other node in candidate role always had higher term, because on timeout it immediately starts another round of election. This prevented other node with longer log to become a candidate. As a fix, we now make the candidate step down and re-starts election with poll requests. 

- https://github.com/camunda/zeebe/commit/a6cd0647358049186595867fb4689bea21641a1c Steps down immediately after vote request timesout.
- https://github.com/camunda/zeebe/commit/a7f6238d0260753f0378be6bb7460d7ee514bbd5 Adds an optimization, where the candidate attempts two rounds of election before stepping down. This is to prevent the delay caused by stepping down and waiting for another election timeout. We can discuss it if it is really required.
- A regression test using the infrastructure built for `RandomizedRaftTest` is also added. Writing a unit test of `CandidateRole` was messy because of hundreds of mocks. 

## Related issues

closes #11665 

<!-- Cut-off marker
_All lines under and including the cut-off marker will be removed from the merge commit message_

### CODE REVIEW

**Comment by npepinpe** [comment]
> hundreds of mocks

:smile:

**Review by npepinpe — APPROVED** [review]
:+1: 

I'm also not sure about having the second round of election, but it's quite a small change, and well documented. We assume it helps keep election time down in most cases, but I guess we don't really know? Do we have a way to observe this, so we could later decide if it's really useful or not?

Anyway, not a blocker, feel free to merge :+1:

**Comment by deepthidevaki** [comment]
> 
> I'm also not sure about having the second round of election, but it's quite a small change, and well documented. We assume it helps keep election time down in most cases, but I guess we don't really know? Do we have a way to observe this, so we could later decide if it's really useful or not?
> 

I don't think it is easy to observe. We have the metrics for election latency. But there are several factors influencing it. Linking higher or lower values to this one change might be difficult. Since it was always retrying before, this retry would also not make things worse than before.

**Comment by deepthidevaki** [comment]
bors merge

**Pull request merged**
