### PR TITLE
chore(ci): remove system-out from test output xml

### PR DESCRIPTION
**Pull request by menski**
## Description

Mitigate to large test output files by deleting the system-out element using sed.

Note: we cannot use XML tools like xmlstarlet as they all suffer the same libxml2 limitation

Also replaces the deprecated usage of `files` with `junit_files` in the publish test result action.
 
## Related issues

related #9959

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by menski** [comment]
Please note that the "Publish Test Result" workflow is always picked up from `main` branch, so this changes will only take effect after the merge. You can find an example run in my personal fork https://github.com/menski/zeebe/actions/runs/2789777745

**Comment by oleschoenburg** [comment]
@menski Could you do one more test to verify that failing tests are still handled correctly and that the output we see from the is okay? I think it'd be as easy as breaking one of our tests intentionally and seeing what is being reported.

**Comment by menski** [comment]
sure let me break stuff

**Comment by menski** [comment]
Running test: https://github.com/menski/zeebe/pull/80

**Comment by menski** [comment]
@oleschoenburg results of the test are posted [here](https://github.com/menski/zeebe/runs/7655966877), as I'm not familiar with the expect output/format, can you check if it is what you expected?

**Review by lenaschoenburg — APPROVED** [review]
Alright, report still looks good and includes the stacktrace of the failing assertion 👍

**Comment by menski** [comment]
bors retry

**Pull request merged**
