### PR TITLE
Add BufferedStreamWriter

### PR DESCRIPTION
**Pull request by pihme**
## Description

* Adds a new class to write records into a byte buffer
* This class will replace much of `TypedStreamWriterImpl` and `LogStreamBatchWriter`

## Why a draft?
This PR is a little different from the previous PRs as part of engine abstraction, because it deviates more from the way that @Zell envisioned. His approach was to start from the code we already have and iteratively refactor from there. My approach is more: Now that we know where we want to end up, let's define the interfaces of what we want and implement the code that satisfies these interfaces.

Because of that, this PR creates a new class, which borrows heavily from `TypedStreamWriterImpl` and `LogStreamBatchWriter`. Refactoring these two classes seems not really feasible, because these classes are in use and there are dependencies to other refactoring steps. So it is difficult to keep the scope small.

Adding a new class is easy, though. With the new class we can iteratively move the code to use the new classes and once that is done, we can ditch the legacy code.

This PR is a draft, because I want to check with you, whether you are overall Ok with this approach. If yes, I would proceed in the same manner with the `TypedResponseWriter`. If not, let's discuss that. 

Second, you will note that the style of the code is different. The legacy code used a builder pattern, whereas this code is quite linear. Personally, I find it easier to read, but your mileage may vary.

Next, I want to ask you how you feel about the exceptions being thrown. In particular, whether you think this should happen on the platform side, or whether it should happen on the engine side?

Also, I wanted to know if you have any ideas how to test this. What would the test harness be for this class? Should it be a randomized test or more a test based on individual testcases?

## Related issues

related to #9780 

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [ ] The changes are backwards compatibility with previous versions
* [ ] If it fixes a bug then PRs are created to [backport](https://github.com/camunda/zeebe/compare/stable/0.24...main?expand=1&template=backport_template.md&title=[Backport%200.24]) the fix to the last two minor versions. You can trigger a backport by assigning labels (e.g. `backport stable/1.3`) to the PR, in case that fails you need to create backports manually.

Testing:
* [ ] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [ ] The behavior is tested manually
* [ ] The change has been verified by a QA run
* [ ] The impact of the changes is verified by a benchmark

Documentation:
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the [release announcement](https://drive.google.com/drive/u/0/folders/1DTIeswnEEq-NggJ25rm2BsDjcCQpDape)
* [ ] If the PR changes how BPMN processes are validated (e.g. support new BPMN element) then the Camunda modeling team should be informed to adjust the BPMN linting.

Please refer to our [review guidelines](https://github.com/camunda/zeebe/wiki/Pull-Requests-and-Code-Reviews#code-review-guidelines).

### CODE REVIEW

**Comment by npepinpe** [comment]
> This PR is a draft, because I want to check with you, whether you are overall Ok with this approach. If yes, I would proceed in the same manner with the TypedResponseWriter. If not, let's discuss that.

I'm fine with that.

> Second, you will note that the style of the code is different. The legacy code used a builder pattern, whereas this code is quite linear. Personally, I find it easier to read, but your mileage may vary.

I like the idea in general. I would also opt for a more "stateless" approach. The only advantage with a builder is when you may need to do only partial applications, but I don't think this is useful in our case, so :+1: 

> Next, I want to ask you how you feel about the exceptions being thrown. In particular, whether you think this should happen on the platform side, or whether it should happen on the engine side?

I don't think I know what you're referring to. From looking at it, it seems to be mostly serialization exceptions. Is that correct? Or are there other possible failure modes? In terms of serialization errors, I would still have preferred if the engine was just `Records -> Records`, i.e. records in/records out, but I guess we decided not to go in that direction (though if you know which issues explains why and can point me to it, I'd be very grateful!).

> Also, I wanted to know if you have any ideas how to test this. What would the test harness be for this class? Should it be a randomized test or more a test based on individual testcases?

As far as unit testing, I guess here we're just testing serialization, so it makes sense to have some randomized tests. There is the `ProtocolFactory` which generates random records, but it has some limitations. It could be a starting point, at least.

**Comment by pihme** [comment]
> I don't think I know what you're referring to.

@npepinpe Sorry, that was not very clear.
I am referring to these:
* https://github.com/camunda/zeebe/pull/9788/files#diff-e1e9da1658eca064c7f0988fb92aede1c0b1111d91e7c9e66982304d334ea5acR126
* https://github.com/camunda/zeebe/pull/9788/files#diff-e1e9da1658eca064c7f0988fb92aede1c0b1111d91e7c9e66982304d334ea5acR148

So in both these cases, you could do this logic here and throw exceptions here. You could also do this logic on the caller's site and then this class would take two more parameters and would not need to deal with the lookups

**Comment by npepinpe** [comment]
Ah. Is there a reason we expect a `RecordValue` and not the implementation type `UnifiedRecordValue`, or at least a `RecordValue & BufferWriter`? Could we just leverage the type system to enforce this check for us? I know this is not really answering your question as it's very specific to the two exceptions :sweat_smile: 

I think I'm OK in general with throwing exceptions, but in this case it feels like you shouldn't be able to pass non-serializable objects at all.

**Comment by pihme** [comment]
> I would still have preferred if the engine was just Records -> Records, i.e. records in/records out, but I guess we decided not to go in that direction (though if you know which issues explains why and can point me to it, I'd be very grateful!).

I don't think we excluded it explicitly. Chris was more looking at what we have already and modeled it alongside.

I still want to do a second implementation for `ProcessingResult` and `ProcessingResultBuilder` in tests which gives me a list of records to test against.

In production, I think we don't really need the `records -> records` as such and can do with `records -> result -> result.writeToStream(...)`

**Comment by pihme** [comment]
> Ah. Is there a reason we expect a RecordValue and not the implementation type UnifiedRecordValue, or at least a RecordValue & BufferWriter? 

I guess it's because we always did it this way. And I am sure there is a brilliant reason why

>  in this case it feels like you shouldn't be able to pass non-serializable objects at all.
That's also my inclination. I will rework this and see which I like better

**Comment by pihme** [comment]
Thanks for the comments. Closing this draft for now.

**Pull request closed without merging**
