### PR TITLE
ci(it): bump maven threads to 4 & fork count to 12

### PR DESCRIPTION
**Pull request by megglos**

### CODE REVIEW

**Comment by npepinpe** [comment]
I was about to raise that our nodes are largely underutilized, and we could make them smaller to save cost, but I guess making it faster is better 😄

**Comment by megglos** [comment]
@npepinpe at least for the IT job I'm fine to keep 16 if that helps to reduce runtime , however even higher fork counts don't yield much benefit given there are a couple of ITs with a duration in the 3-4 minutes range :/ could be worth evaluating to break them into pieces to actually parallelise

**Comment by npepinpe** [comment]
Fair point. We could easily split them into different jobs based on the interdependency. We already know that the QA modules are always built last, since they likely depend on every other module. The exporter tests could then likely run on much smaller nodes :shrug:

**Comment by megglos** [comment]
closing in favor of doing a job split first

**Pull request closed without merging**
