### PR TITLE
Remove log block index

### LINKED ISSUE #2709: Remove LogBlockIndex
We want to remove the current LogBlockindex implementation and everything related to this.

  * LogBlockIndexWriter
  * LogBlockIndex
  *  State management related to LogblockIndex

Currently the index is only used on start or exceptional scenarios, but we often fight on maintaining it (because of migration or other changes) we see no benefit in keeping it.
It might make recovering slower yes, but since we try to keep the log small as possible it should not be significant. If we really see any problems, then we can implement binary search on the segments, which should improve this a bit again. 

The replacement for finding a position should be simple as possible, which would mean iterating over the events.

### PR DESCRIPTION
**Pull request by ChrisKujawa**
closes #2709

### CODE REVIEW

**Review by saig0 — COMMENTED** [review]
Looks good :+1: 

Just one questions: is it necessary that the `AsyncSnapshotingTest` uses the `LogStreamRule`? I assume that the test should verify that the snapshotting works in the broker. But it is a rule and doesn't use the broker setup. Maybe, the test could use a mock instead, or call the methods manually. What do you think?

**Comment by Zelldon** [comment]
I think because of the interaction with the commit position and the onCommitListener, but we could also have a more 'intergration' test in the broker. 

> Maybe, the test could use a mock instead, or call the methods manually. What do you think?

Not 100% sure what you mean with this? Lets create an issue to migrate the test to broker or qa?

**Comment by saig0** [comment]
Ok, please create a new issue to migrate the test. Then, we don't need to use the logstream-test JAR in the engine module.

**Review by saig0 — APPROVED** [review]

**Pull request merged**
