### PR TITLE
Use json content type to send bulk request

### LINKED ISSUE #5059: Record with Non-ASCII characters fails to export to Elasticsearch
**Describe the bug**
A record with a non-ASCII character (e.g. a variable record) is not exported to Elasticsearch. 

**To Reproduce**
* deploy a simple workflow (e.g. a start event + end event) 
* create a new workflow instance with variables `{"x":"Á"}` 

**Expected behavior**
Records with any UFT-8 character can be exported to Elasticsearch.

**Log/Stacktrace**

<details><summary>Zeebe Log Output</summary>
 <p>

```
14:48:53.532 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] WARN  io.zeebe.broker.exporter.es - Failed to flush 1 item(s) of bulk request [type: mapper_parsing_exception, reason: failed to parse]
14:48:53.532 [Broker-0-Exporter-1] [Broker-0-zb-fs-workers-1] ERROR io.zeebe.broker.exporter.es - Unexpected exception occurred on periodically flushing bulk, will retry later.
```

</p>
</details>

<details><summary>Full Response from Elasticsearch</summary>
 <p>

```
{"took":0,"errors":true,"items":[{"index":{"_index":"test-record_workflow-instance-creation_0.24.2-snapshot_2020-07-27","_type":"_doc","_id":"1-5","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"json_parse_exception","reason":"Invalid UTF-8 middle byte 0x22\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@22d18169; line: 1, column: 127]"}}}}]}
```

</p>
</details>

**Environment:**
 - OS: Camunda Cloud
 - Zeebe Version: 0.24.1 (>= 0.24.0)
 - Configuration: Elasticsearch exporter

### PR DESCRIPTION
**Pull request by menski**
## Description

With the content-type `application/x-ndjson` elasticsearch fails to index non ASCII character. The high level rest client was also using `application/json` before, so there should not be a problem to switch back to that.

## Related issues

closes #5059

## Definition of Done

_Not all items need to be done depending on the issue and the pull request._

Code changes:
* [x] The changes are backwards compatibility with previous versions
* [x] If it fixes a bug then PRs are created to backport the fix to the last two minor versions

Testing:
* [x] There are unit/integration tests that verify all acceptance criterias of the issue
* [ ] New tests are written to ensure backwards compatibility with further versions
* [x] The behavior is tested manually
* [ ] The impact of the changes is verified by a benchmark 

Documentation: 
* [ ] The documentation is updated (e.g. BPMN reference, configuration, examples, get-started guides, etc.)
* [ ] New content is added to the release announcement

### CODE REVIEW

**Comment by menski** [comment]
@npepinpe sorry I forgot to create a PR for the develop version :see_no_evil:

**Comment by npepinpe** [comment]
btw do we know why the documentation says to use ndjson, but you can specify charset only with json?

**Review by npepinpe — APPROVED** [review]

**Comment by menski** [comment]
Not really, Philipp found this open request on their side https://github.com/elastic/elasticsearch/issues/28123. I also didn't expected that they cannot handle UTF-8 chars like this, and that the `request.setJsonEntity` also set's the content type to `application/json` as it does the official rest client. :shrug:

**Pull request merged**
