### PR TITLE
fix(broker): handle output element expression with whitespaces

### LINKED ISSUE #4100: Improve nil initialisation of locally scoped outputElement for feel expressions
For multi instance activities we can define the outputElement as a feel expression. To make sure that this variable is available during execution of the multi instance body, it needs to be initialised with a nil-value. Otherwise, each iteration over the body might write values to it at a non-local scope. This only needs to be done for expressions that are just a variable or a nested variable.

This was quickly (and ugly) coded with a simple regex check. But that might lead to some unnecessary (i.e. unwanted) variables on the local scope. For example, when a more advanced expression is used as an outputElement.

This is specifically for `engine/processor/workflow/handlers/multiinstance/AbstractMultiInstanceBodyHandler.java`

### LINKED ISSUE #4852: Multi-instance output element expression with space prefix leads to incorrect variable scope
**Describe the bug**
When the output element expression of a multi-instance element directly refers to a variable or a property of a variable, a new variable with that name should be nil initialised at the multi-instance body scope. This is especially important for parallel multi-instance elements, because this is a common trap for a race condition.

Our documentation states it like (including a space in the expression):
> `outputElement` is an expression that defines the output of the instance (e.g. `= result`). Usually, it accesses a variable of the instance that holds the output value. If the expression only accesses a variable or a nested property then it is created as local variable of the instance. 

However, the local variable is wrongly initialised when the expression is prefixed with a space.

**To Reproduce**
- deploy a simple workflow with a multi-instance service task
  - input collection `= inputs`
  - input element `input`
  - output collection `outputs`
  - output element `= output`
- create an instance with variable: `inputs:[1,2]`
- create a java worker that prints the variables of an activated job and completes it with `Map.of("output", input)`, like:
```java
final Map<String, Object> variables = job.getVariablesAsMap();
final var input = variables.get("input");
System.out.println(new ObjectMapper().writeValueAsString(variables));
client.newCompleteCommand(job.getKey())
         .variables(Map.of("output", input))
         .send()
         .join();
```
You'll note that the worker print the output variable with a space prefixed to the variable name: 
`{"input":1," output":null,"loopCounter":1,"outputs":[null,null],"inputs":[1,2]}`. 

You should also note that the `output` variable exists at the process scope instead of at the task scope.

**Expected behavior**
Output element expressions that directly refer to a variable or a property of a variable, with a space in the expression should be correctly nil initialised.

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
# Run with outputElement expression `= output`
{"input":1," output":null,"loopCounter":1,"outputs":[null,null],"inputs":[1,2]}
{"input":2," output":null,"loopCounter":2,"outputs":[null,null],"inputs":[1,2]}

# Run with outputElement expression `=output`
{"input":1,"output":null,"loopCounter":1,"outputs":[null,null],"inputs":[1,2]}
{"input":2,"output":null,"loopCounter":2,"outputs":[null,null],"inputs":[1,2]}
```

</p>
</details>

**Environment:**
 - OS: macOS 10.15.5, but shouldn't matter
 - Zeebe Version: 0.23.3
 - Configuration: default + Hazelcast exporter, but shouldn't matter

### PR DESCRIPTION
**Pull request by saig0**
## Description

* backport fix #4100 to `0.23`

## Related issues

closes #4852 

## Pull Request Checklist

- [x] All commit messages match our [commit message guidelines](https://github.com/zeebe-io/zeebe/blob/develop/CONTRIBUTING.md#commit-message-guidelines)
- [x] The submitting code follows our [code style](https://github.com/zeebe-io/zeebe/wiki/Code-Style)
- [x] If submitting code, please run `mvn clean install -DskipTests` locally before committing

### CODE REVIEW

**Review by korthout — APPROVED** [review]

**Comment by korthout** [comment]
Approved, but not sure about the ci. Please take a look before merging.

**Comment by saig0** [comment]
:+1: The CI failed because of the issue with the certificate, links in the docs, and flaky tests :sweat_smile: None of these should be related to the changes.

**Comment by saig0** [comment]
Test failure `io.atomix.raft.impl.RaftServiceManagerTest`

**Comment by saig0** [comment]
bors retry

**Comment by saig0** [comment]
These tests failing a lot:
```
Test / testSnapshotTakeInstall – io.atomix.raft.impl.RaftServiceManagerTest
Test / testInstallSnapshotOnApply – io.atomix.raft.impl.RaftServiceManagerTest
Test / testInstallSnapshotOnApply – io.atomix.raft.impl.RaftServiceManagerTest
Test / testConcurrentSnapshotWriters – io.atomix.raft.storage.snapshot.impl.FileSnapshotStoreTest
```

**Pull request merged**
