### PR TITLE
Add integration test for cluster topology management

### LINKED ISSUE #13765: Store and manage configuration via gossip
Persists configuration locally and propagates via gossip.

- On bootstrap: local configuration state is empty
   - Coordinator :  First query initial set of cluster members for the current configuration. If no member replies with a known configuration, coordinator generates a new configuration from the provided static properties with version=0. Coordinator only has to get a response from any one of the members.
   - Member: Other members request the coordinator for the configuration. Raft partitions and other zeebe services that depend on the cluster configuration are only started after this node receives the configuration from the coordinator.
- On restart
   - Member/Coordinator: All members  use the local persisted configuration.

```[tasklist]
### Tasks
- [ ] https://github.com/camunda/zeebe/issues/13793
- [x] Decide serialization format used for persisting and gossiping configuration
- [ ] https://github.com/camunda/zeebe/issues/13801
- [ ] https://github.com/camunda/zeebe/issues/13862
- [ ] https://github.com/camunda/zeebe/issues/13941
- [ ] https://github.com/camunda/zeebe/issues/13956
- [ ] Add integration test for topology manager and gossiper
```

### PR DESCRIPTION
**Pull request by deepthidevaki**
## Description

Add an integration test for ClusterTopologyManagerService that verifies initialization of cluster topology by ClusterTopologyManager via gossip. The test uses AtomixCluster so that it uses the actual communication service.

## Related issues

closes #13765

### CODE REVIEW

**Review by lenaschoenburg — APPROVED** [review]
Thanks :+1: 

While running the tests locally I noticed that `ClusterTopologyManagerService#start` provides no executor for the `ActorFuture#onComplete` callback - I think that's easy to fix though and not related to this PR.

**Comment by deepthidevaki** [comment]
I think it is ok to assume the caller `ClusterTopologyManagerService#start` will be an actor. We have interaction between non-actors and actors only at specific places. Otherwise, everything is an actor.

**Comment by deepthidevaki** [comment]
bors merge

**Comment by deepthidevaki** [comment]
bors merge

**Pull request merged**
