### PR TITLE
feat: add exit modal for batch modification (feature flagged)

### LINKED ISSUE #6223: Improve implementation of seek
Follow up #6216 

The implementation of seekToAsqn currently uses two seeks to get the correct behavior. This is not efficient. Find a better solution.

### PR DESCRIPTION
**Pull request by pedesen**
## Description

- refactor useCallbackPrompt, add code comments
- add exit modal for batch modification
- add e2e test for exit modal

## Related issues

closes https://github.com/camunda/operate/issues/6223

### CODE REVIEW

**Review by vitorwtavares — APPROVED** [review]

**Comment by pedesen** [comment]
@gastonpillet01 Please review this using docker compose. Container name is `registry.camunda.cloud/team-operate/camunda-operate:branch-fe-6223-discard-batch-modification`

**Review by gastonpillet01 — APPROVED** [review]
Exit modal for batch modification correctly implemented

**Review by Szik — CHANGES_REQUESTED** [review]
while in "batch modification mode":
-"Discard modification Modals" should not appear when making changes in "instance table" and changing "instance stats"
-"Discard modification Modals" should not appears when unchecking stats
-if at least one  stat in "instance stats" is unchecked, "Expand Filter" triggers "Discard modification Modals" (should not be)

**Comment by pedesen** [comment]
@Szik Thanks for reviewing! I'd like to fix the bugs you mentioned in a separate issue: https://github.com/camunda/zeebe/issues/17897

**Review by Szik — APPROVED** [review]

**Pull request merged**
